[#_TypeDB_Driver_Api_TypeDBOptions]
=== TypeDB.Driver.Api.TypeDBOptions

*Package*: `TypeDB.Driver.Api.TypeDBOptions`



TypeDB session and transaction options. ``TypeDBOptions`` object can be used to override the default server behaviour.

// tag::methods[]
[#_bool_TypeDB_Driver_Api_TypeDBOptions_Explain___]
==== Explain

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.Explain()
----



Returns the value set for the explanation in this ``TypeDBOptions`` object. If set to ``true``, explanations for queries are enabled.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_Explain___bool_explain_]
==== Explain

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.Explain(bool explain)
----



Explicitly enables or disables explanations. If set to ``true``, enables explanations for queries. Only affects read transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explain` a| Explicitly enable or disable explanations a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_bool_TypeDB_Driver_Api_TypeDBOptions_Infer___]
==== Infer

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.Infer()
----



Returns the value set for the inference in this ``TypeDBOptions`` object.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_Infer___bool_infer_]
==== Infer

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.Infer(bool infer)
----



Explicitly enables or disables inference. Only settable at transaction level and above. Only affects read transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `infer` a| Explicitly enable or disable inference a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_bool_TypeDB_Driver_Api_TypeDBOptions_Parallel___]
==== Parallel

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.Parallel()
----



Returns the value set for the parallel execution in this ``TypeDBOptions`` object. If set to ``true``, the server uses parallel instead of single-threaded execution.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_Parallel___bool_parallel_]
==== Parallel

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.Parallel(bool parallel)
----



Explicitly enables or disables parallel execution. If set to ``true``, the server uses parallel instead of single-threaded execution.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `parallel` a| Explicitly enable or disable parallel execution a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_bool_TypeDB_Driver_Api_TypeDBOptions_Prefetch___]
==== Prefetch

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.Prefetch()
----



Returns the value set for the prefetching in this ``TypeDBOptions`` object. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_Prefetch___bool_prefetch_]
==== Prefetch

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.Prefetch(bool prefetch)
----



Explicitly enables or disables prefetching. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `prefetch` a| Explicitly enable or disable prefetching a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_int_TypeDB_Driver_Api_TypeDBOptions_PrefetchSize___]
==== PrefetchSize

[source,cs]
----
int? TypeDB.Driver.Api.TypeDBOptions.PrefetchSize()
----



Returns the value set for the prefetch size in this ``TypeDBOptions`` object. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.


[caption=""]
.Returns
`int?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_PrefetchSize___int_prefetchSize_]
==== PrefetchSize

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.PrefetchSize(int prefetchSize)
----



Explicitly sets a prefetch size. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `prefetchSize` a| Number of answers that the server should send before the driver issues a fresh request a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_bool_TypeDB_Driver_Api_TypeDBOptions_ReadAnyReplica___]
==== ReadAnyReplica

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.ReadAnyReplica()
----



Returns the value set for reading data from any replica in this ``TypeDBOptions`` object. If set to ``True``, enables reading data from any replica, potentially boosting read throughput.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_ReadAnyReplica___bool_readAnyReplica_]
==== ReadAnyReplica

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.ReadAnyReplica(bool readAnyReplica)
----



Explicitly enables or disables reading data from any replica. If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `readAnyReplica` a| Explicitly enable or disable reading data from any replica a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_int_TypeDB_Driver_Api_TypeDBOptions_SchemaLockAcquireTimeoutMillis___]
==== SchemaLockAcquireTimeoutMillis

[source,cs]
----
int? TypeDB.Driver.Api.TypeDBOptions.SchemaLockAcquireTimeoutMillis()
----



Returns the value set for the schema lock acquire timeout in this ``TypeDBOptions`` object. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.


[caption=""]
.Returns
`int?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_SchemaLockAcquireTimeoutMillis___int_schemaLockAcquireTimeoutMillis_]
==== SchemaLockAcquireTimeoutMillis

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.SchemaLockAcquireTimeoutMillis(int schemaLockAcquireTimeoutMillis)
----



Explicitly sets schema lock acquire timeout. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `schemaLockAcquireTimeoutMillis` a| How long the driver should wait if opening a session or transaction is blocked by a schema write lock. a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_int_TypeDB_Driver_Api_TypeDBOptions_SessionIdleTimeoutMillis___]
==== SessionIdleTimeoutMillis

[source,cs]
----
int? TypeDB.Driver.Api.TypeDBOptions.SessionIdleTimeoutMillis()
----



Returns the value set for the session idle timeout in this ``TypeDBOptions`` object. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.


[caption=""]
.Returns
`int?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_SessionIdleTimeoutMillis___int_sessionIdleTimeoutMillis_]
==== SessionIdleTimeoutMillis

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.SessionIdleTimeoutMillis(int sessionIdleTimeoutMillis)
----



Explicitly sets a session idle timeout. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `sessionIdleTimeoutMillis` a| timeout that allows the server to close sessions if the driver terminates or becomes unresponsive. a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_bool_TypeDB_Driver_Api_TypeDBOptions_TraceInference___]
==== TraceInference

[source,cs]
----
bool? TypeDB.Driver.Api.TypeDBOptions.TraceInference()
----



Returns the value set for reasoning tracing in this ``TypeDBOptions`` object. If set to ``true``, reasoning tracing graphs are output in the logging directory.


[caption=""]
.Returns
`bool?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_TraceInference___bool_traceInference_]
==== TraceInference

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.TraceInference(bool traceInference)
----



Explicitly enables or disables reasoning tracing. If set to ``true``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `traceInference` a| Explicitly enable or disable reasoning tracing a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_int_TypeDB_Driver_Api_TypeDBOptions_TransactionTimeoutMillis___]
==== TransactionTimeoutMillis

[source,cs]
----
int? TypeDB.Driver.Api.TypeDBOptions.TransactionTimeoutMillis()
----



Returns the value set for the transaction timeout in this ``TypeDBOptions`` object. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.


[caption=""]
.Returns
`int?`

[#_TypeDBOptions_TypeDB_Driver_Api_TypeDBOptions_TransactionTimeoutMillis___int_transactionTimeoutMillis_]
==== TransactionTimeoutMillis

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.TypeDBOptions.TransactionTimeoutMillis(int transactionTimeoutMillis)
----



Explicitly set a transaction timeout. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transactionTimeoutMillis` a| Timeout for killing transactions automatically. a| 
|===

[caption=""]
.Returns
`TypeDBOptions`

[#_TypeDB_Driver_Api_TypeDBOptions_TypeDBOptions___]
==== TypeDBOptions

[source,cs]
----
TypeDB.Driver.Api.TypeDBOptions.TypeDBOptions()
----



Produces a new ``TypeDBOptions`` object.


[caption=""]
.Returns
`TypeDB.Driver.Api.TypeDBOptions.TypeDBOptions`

// end::methods[]

