[#_TypeDB_Driver_Api_ITypeDBSession_Interface_Reference]
=== TypeDB.Driver.Api.ITypeDBSession Interface Reference

*Package*: `TypeDB.Driver.Api.ITypeDBSession Interface Reference`

// tag::methods[]
[#_void_TypeDB_Driver_Api_ITypeDBSession_Close___]
==== Close

[source,cs]
----
void TypeDB.Driver.Api.ITypeDBSession.Close()
----



Closes the session. Before opening a new session, the session currently open should first be closed.


[caption=""]
.Returns
`void`

[#_bool_TypeDB_Driver_Api_ITypeDBSession_IsOpen___]
==== IsOpen

[source,cs]
----
bool TypeDB.Driver.Api.ITypeDBSession.IsOpen()
----



Checks whether this session is open.


[caption=""]
.Returns
`bool`

[#_void_TypeDB_Driver_Api_ITypeDBSession_OnClose___Action_function_]
==== OnClose

[source,cs]
----
void TypeDB.Driver.Api.ITypeDBSession.OnClose(Action function)
----



Registers a callback function which will be executed when this session is closed.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[#_void_TypeDB_Driver_Api_ITypeDBSession_OnReopen___Action_function_]
==== OnReopen

[source,cs]
----
void TypeDB.Driver.Api.ITypeDBSession.OnReopen(Action function)
----



Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[#_ITypeDBTransaction_TypeDB_Driver_Api_ITypeDBSession_Transaction___TransactionType_type_]
==== Transaction

[source,cs]
----
ITypeDBTransaction TypeDB.Driver.Api.ITypeDBSession.Transaction(TransactionType type)
----



Opens a transaction on the database connected to the session with default options.

 
  See also
 
 
  ITypeDBSession::Transaction(TransactionType, TypeDBOptions)
 


[caption=""]
.Returns
`ITypeDBTransaction`

[#_ITypeDBTransaction_TypeDB_Driver_Api_ITypeDBSession_Transaction___TransactionType_type__TypeDBOptions_options_]
==== Transaction

[source,cs]
----
ITypeDBTransaction TypeDB.Driver.Api.ITypeDBSession.Transaction(TransactionType type, TypeDBOptions options)
----



Opens a transaction to perform read or write queries on the database connected to the session.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `type` a| The type of transaction to be created (Read or Write) a| 
a| `options` a| Options for the session a| 
|===

[caption=""]
.Returns
`ITypeDBTransaction`

// end::methods[]

