[#_TypeDBSession.Type]
=== TypeDBSession.Type

*Package*: `com.vaticle.typedb.driver.api`

Used to specify the type of the session. 


[caption=""]
.TypeDBSession.Type examples
====

[source,java]
----
driver.session(database, TypeDBSession.Type.SCHEMA);
----

====

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols="~"]
[options="header"]
|===
|Name
a| `DATA`
a| `SCHEMA`
|===
// end::enum_constants[]

// tag::methods[]
[#_TypeDBSession.Type_id_]
==== id

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_TypeDBSession.Type_isData_]
==== isData

[source,java]
----
public boolean isData()
----



[caption=""]
.Returns
`public boolean`

[#_TypeDBSession.Type_isSchema_]
==== isSchema

[source,java]
----
public boolean isSchema()
----



[caption=""]
.Returns
`public boolean`

[#_TypeDBSession.Type_of_com_vaticle_typedb_driver_jni_SessionType]
==== of

[source,java]
----
public static TypeDBSession.Type of​(com.vaticle.typedb.driver.jni.SessionType sessionType)
----



[caption=""]
.Returns
`public static TypeDBSession.Type`

[#_TypeDBSession.Type_valueOf_java_lang_String]
==== valueOf

[source,java]
----
public static TypeDBSession.Type valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static TypeDBSession.Type`

[#_TypeDBSession.Type_values_]
==== values

[source,java]
----
public static TypeDBSession.Type[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (TypeDBSession.Type c : TypeDBSession.Type.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static TypeDBSession.Type[]`

[caption=""]
.Code examples
[source,java]
----
for (TypeDBSession.Type c : TypeDBSession.Type.values())
    System.out.println(c);
----

// end::methods[]

