[#_Concept_Transitivity]
=== Concept.Transitivity

*Package*: `com.vaticle.typedb.driver.api.concept`

This class is used for specifying whether we need explicit or transitive subtyping, instances, etc. 


[caption=""]
.Examples
[source,java]
----
attributeType.getOwners(transaction, annotation, Concept.Transitivity.EXPLICIT);
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `EXPLICIT`
a| `TRANSITIVE`
|===
// end::enum_constants[]

// tag::methods[]
[#_Concept_Transitivity_valueOf__java_lang_String]
==== valueOf

[source,java]
----
public static Concept.Transitivity valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static Concept.Transitivity`

[#_Concept_Transitivity_values__]
==== values

[source,java]
----
public static Concept.Transitivity[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (Concept.Transitivity c : Concept.Transitivity.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static Concept.Transitivity[]`

[caption=""]
.Code examples
[source,java]
----
for (Concept.Transitivity c : Concept.Transitivity.values())
    System.out.println(c);
----

// end::methods[]

