[#_Label]
=== Label

*Package*: `com.vaticle.typedb.driver.common`

A ``Label`` holds the uniquely identifying name of a type.

It consists of an optional ``scope``, and a ``name``, represented ``scope:name``. The scope is used only used to distinguish between role-types of the same name declared in different relation types.

// tag::methods[]
[#_Label_equals__java_lang_Object]
==== equals

[source,java]
----
public boolean equals​(java.lang.Object obj)
----

Checks if this Label is equal to another object. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `obj` a| Object to compare with a| `java.lang.Object`
|===

[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
label.equals(obj);
----

[#_Label_name__]
==== name

[source,java]
----
public java.lang.String name()
----

Returns the name of this Label. 


[caption=""]
.Returns
`public java.lang.String`

[caption=""]
.Code examples
[source,java]
----
label.name();
----

[#_Label_of__java_lang_String]
==== of

[source,java]
----
public static Label of​(java.lang.String name)
----

Creates a Label from a specified name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| Label name a| `java.lang.String`
|===

[caption=""]
.Returns
`public static Label`

[caption=""]
.Code examples
[source,java]
----
Label.of("entity");
----

[#_Label_of__java_lang_String__java_lang_String]
==== of

[source,java]
----
public static Label of​(java.lang.String scope,
                       java.lang.String name)
----

Creates a Label from a specified scope and name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `scope` a| Label scope a| `java.lang.String`
a| `name` a| Label name a| `java.lang.String`
|===

[caption=""]
.Returns
`public static Label`

[caption=""]
.Code examples
[source,java]
----
Label.of("relation", "role");
----

[#_Label_scope__]
==== scope

[source,java]
----
public java.util.Optional<java.lang.String> scope()
----

Returns the scope of this Label. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
label.scope();
----

[#_Label_scopedName__]
==== scopedName

[source,java]
----
public java.lang.String scopedName()
----

Returns the string representation of the scoped name. 


[caption=""]
.Returns
`public java.lang.String`

[caption=""]
.Code examples
[source,java]
----
label.scopedName();
----

[#_Label_toString__]
==== toString

[source,java]
----
public java.lang.String toString()
----

Returns the string representation of the scoped name. 


[caption=""]
.Returns
`public java.lang.String`

[caption=""]
.Code examples
[source,java]
----
label.toString();
----

// end::methods[]

