[#_RelationType]
=== RelationType

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`
* `ThingType`
* `Type`

Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles. Other types can play roles in relations if it’s mentioned in their definition. A relation type must specify at least one role.

// tag::methods[]
[#_RelationType_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_RelationType_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_RelationType_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_RelationType_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_RelationType_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_RelationType_asRelationType_]
==== asRelationType

[source,java]
----
@CheckReturnValue
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_RelationType_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_RelationType_asThing_]
==== asThing

[source,java]
----
default Thing asThing()
----

Casts the concept to ``Thing``. 


[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,java]
----
concept.asThing();
----

[#_RelationType_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_RelationType_create_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== create

[source,java]
----
@CheckReturnValue
Relation create​(TypeDBTransaction transaction)
----

Creates and returns an instance of this ``RelationType``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
relationType.create(transaction);
----

[#_RelationType_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getInstances​(TypeDBTransaction transaction)
----

Retrieves all ``Relation`` objects that are instances of this ``RelationType`` or its subtypes. Equivalent to ``getInstances(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getInstances(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[#_RelationType_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
==== getInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getInstances​(TypeDBTransaction transaction,
                                                         Concept.Transitivity transitivity)
----

Retrieves ``Relation``s that are instances of this exact ``RelationType``, OR this ``RelationType`` and any of its subtypes. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct relates only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[caption=""]
.Code examples
[source,java]
----
relationType.getInstances(transaction, transitivity)
----

[#_RelationType_getRelates_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getRelates

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getRelates​(TypeDBTransaction transaction)
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance.


See also: <<#_getRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getRelates(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[#_RelationType_getRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
==== getRelates

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getRelates​(TypeDBTransaction transaction,
                                                       Concept.Transitivity transitivity)
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited relates, ``Transitivity.EXPLICIT`` for direct relates only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
relationType.getRelates(transaction, transitivity);
----

[#_RelationType_getRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== getRelates

[source,java]
----
@Nullable
@CheckReturnValue
RoleType getRelates​(TypeDBTransaction transaction,
                    java.lang.String roleLabel)
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance. If ``role_label`` is given, returns a corresponding ``RoleType`` or ``null``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| Label of the role we wish to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
relationType.getRelates(transaction, roleLabel);
----

[#_RelationType_getRelatesOverridden_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType]
==== getRelatesOverridden

[source,java]
----
@Nullable
@CheckReturnValue
RoleType getRelatesOverridden​(TypeDBTransaction transaction,
                              RoleType roleType)
----



[caption=""]
.Returns
`RoleType`

[#_RelationType_getRelatesOverridden_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== getRelatesOverridden

[source,java]
----
@Nullable
@CheckReturnValue
RoleType getRelatesOverridden​(TypeDBTransaction transaction,
                              java.lang.String roleLabel)
----

Retrieves a ``RoleType`` that is overridden by the role with the ``role_label``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| Label of the role that overrides an inherited role a| `java.lang.String`
|===

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
relationType.getRelatesOverridden(transaction, roleLabel);
----

[#_RelationType_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RelationType> getSubtypes​(TypeDBTransaction transaction)
----

Retrieves all direct and indirect subtypes of the ``RelationType``. Equivalent to ``getSubtypes(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getSubtypes(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends RelationType>`

[#_RelationType_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RelationType> getSubtypes​(TypeDBTransaction transaction,
                                                            Concept.Transitivity transitivity)
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RelationType``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RelationType>`

[caption=""]
.Code examples
[source,java]
----
relationType.getSubtypes(transaction, transitivity);
----

[#_RelationType_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_RelationType_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_RelationType_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_RelationType_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_RelationType_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_RelationType_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_RelationType_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_RelationType_isThing_]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThing();
----

[#_RelationType_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_RelationType_setRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== setRelates

[source,java]
----
void setRelates​(TypeDBTransaction transaction,
                java.lang.String roleLabel)
----

Sets the new role that this ``RelationType`` relates to.


See also: <<#_setRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String_java_lang_String,``setRelates(TypeDBTransaction, String, String)``>>


[caption=""]
.Returns
`void`

[#_RelationType_setRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String_com_vaticle_typedb_driver_api_concept_type_RoleType]
==== setRelates

[source,java]
----
void setRelates​(TypeDBTransaction transaction,
                java.lang.String roleLabel,
                RoleType overriddenType)
----

Sets the new role that this ``RelationType`` relates to.


See also: <<#_setRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String_java_lang_String,``setRelates(TypeDBTransaction, String, String)``>>


[caption=""]
.Returns
`void`

[#_RelationType_setRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String_java_lang_String]
==== setRelates

[source,java]
----
void setRelates​(TypeDBTransaction transaction,
                java.lang.String roleLabel,
                java.lang.String overriddenLabel)
----

Sets the new role that this ``RelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| The new role for the ``RelationType`` to relate to a| `java.lang.String`
a| `overriddenLabel` a| The label being overridden, if applicable a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
relationType.setRelates(transaction, roleLabel);
 relationType.setRelates(transaction, roleLabel, overriddenLabel);
----

[#_RelationType_setSupertype_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RelationType]
==== setSupertype

[source,java]
----
void setSupertype​(TypeDBTransaction transaction,
                  RelationType superRelationType)
----

Sets the supplied ``RelationType`` as the supertype of the current ``RelationType``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `superRelationType` a| The ``RelationType`` to set as the supertype of this ``RelationType`` a| `RelationType`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
relationType.setSupertype(transaction, superRelationType);
----

[#_RelationType_unsetRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType]
==== unsetRelates

[source,java]
----
void unsetRelates​(TypeDBTransaction transaction,
                  RoleType roleType)
----

Disallows this ``RelationType`` from relating to the given role.


See also: <<#_unsetRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String,``unsetRelates(TypeDBTransaction, String)``>>


[caption=""]
.Returns
`void`

[#_RelationType_unsetRelates_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== unsetRelates

[source,java]
----
void unsetRelates​(TypeDBTransaction transaction,
                  java.lang.String roleLabel)
----

Disallows this ``RelationType`` from relating to the given role. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| The role to not relate to the relation type. a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
relationType.unsetRelates(transaction, roleLabel);
----

// end::methods[]

