[#_RoleType]
=== RoleType

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`
* `Type`

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type. Roles allow a schema to enforce logical constraints on types of role players.

// tag::methods[]
[#_RoleType_asAttribute__]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_RoleType_asAttributeType__]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_RoleType_asEntity__]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_RoleType_asEntityType__]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_RoleType_asRelation__]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_RoleType_asRelationType__]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_RoleType_asRoleType__]
==== asRoleType

[source,java]
----
@CheckReturnValue
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_RoleType_asThing__]
==== asThing

[source,java]
----
default Thing asThing()
----

Casts the concept to ``Thing``. 


[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,java]
----
concept.asThing();
----

[#_RoleType_asThingType__]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
concept.asThingType();
----

[#_RoleType_asValue__]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_RoleType_getPlayerInstances__TypeDBTransaction]
==== getPlayerInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Thing> getPlayerInstances​(TypeDBTransaction transaction)
----

Retrieves the ``Thing`` instances that play this role.


See also: <<#_getPlayerInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getPlayerInstances(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends Thing>`

[#_RoleType_getPlayerInstances__TypeDBTransaction__Concept_Transitivity]
==== getPlayerInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Thing> getPlayerInstances​(TypeDBTransaction transaction,
                                                            Concept.Transitivity transitivity)
----

Retrieves the ``Thing`` instances that play this role. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Thing>`

[caption=""]
.Code examples
[source,java]
----
roleType.getPlayerInstances(transaction, transitivity);
----

[#_RoleType_getPlayerTypes__TypeDBTransaction]
==== getPlayerTypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends ThingType> getPlayerTypes​(TypeDBTransaction transaction)
----

Retrieves the ``ThingType``s whose instances play this role. Equivalent to ``getPlayerTypes(transaction, Transitivity.TRANSITIVE)``.


See also: <<#_getPlayerTypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getPlayerTypes(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends ThingType>`

[#_RoleType_getPlayerTypes__TypeDBTransaction__Concept_Transitivity]
==== getPlayerTypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends ThingType> getPlayerTypes​(TypeDBTransaction transaction,
                                                            Concept.Transitivity transitivity)
----

Retrieves the ``ThingType``s whose instances play this role. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends ThingType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getPlayerTypes(transaction, transitivity)
----

[#_RoleType_getRelationInstances__TypeDBTransaction]
==== getRelationInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getRelationInstances​(TypeDBTransaction transaction)
----

Retrieves the ``Relation`` instances that this role is related to. Equivalent to ````getRelationInstances(transaction, Transitivity.TRANSITIVE)


See also: <<#_getRelationInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getRelationInstances(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[#_RoleType_getRelationInstances__TypeDBTransaction__Concept_Transitivity]
==== getRelationInstances

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getRelationInstances​(TypeDBTransaction transaction,
                                                                 Concept.Transitivity transitivity)
----

Retrieves the ``Relation`` instances that this role is related to. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect relation, ``Transitivity.EXPLICIT`` for direct relation only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[caption=""]
.Code examples
[source,java]
----
roleType.getRelationInstances(transaction, transitivity)
----

[#_RoleType_getRelationType__TypeDBTransaction]
==== getRelationType

[source,java]
----
@CheckReturnValue
Promise<? extends RelationType> getRelationType​(TypeDBTransaction transaction)
----

Retrieves the ``RelationType`` that this role is directly related to. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<? extends RelationType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getRelationType(transaction).resolve();
----

[#_RoleType_getRelationTypes__TypeDBTransaction]
==== getRelationTypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RelationType> getRelationTypes​(TypeDBTransaction transaction)
----

Retrieves ``RelationType``s that this role is related to (directly or indirectly). 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RelationType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getRelationTypes(transaction);
----

[#_RoleType_getSubtypes__TypeDBTransaction]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getSubtypes​(TypeDBTransaction transaction)
----

Retrieves all direct and indirect subtypes of the ``RoleType``. Equivalent to ``getSubtypes(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getSubtypes(TypeDBTransaction, Transitivity)``>>


[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[#_RoleType_getSubtypes__TypeDBTransaction__Concept_Transitivity]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getSubtypes​(TypeDBTransaction transaction,
                                                        Concept.Transitivity transitivity)
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Concept.Transitivity`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getSubtypes(transaction, transitivity);
----

[#_RoleType_getSupertype__TypeDBTransaction]
==== getSupertype

[source,java]
----
@CheckReturnValue
Promise<? extends RoleType> getSupertype​(TypeDBTransaction transaction)
----

Retrieves the most immediate supertype of the ``RoleType``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getSupertype(transaction).resolve();
----

[#_RoleType_getSupertypes__TypeDBTransaction]
==== getSupertypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getSupertypes​(TypeDBTransaction transaction)
----

Retrieves all supertypes of the ``RoleType``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
roleType.getSupertypes(transaction);
----

[#_RoleType_isAttribute__]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_RoleType_isAttributeType__]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_RoleType_isEntity__]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_RoleType_isEntityType__]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_RoleType_isRelation__]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_RoleType_isRelationType__]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_RoleType_isRoleType__]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_RoleType_isThing__]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThing();
----

[#_RoleType_isThingType__]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThingType();
----

[#_RoleType_isValue__]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]

