[#_Value_Type]
=== Value.Type

*Package*: `com.vaticle.typedb.driver.api.concept.value`

Used to specify the type of the value. 


[caption=""]
.Examples
[source,java]
----
thingType.getOwns(transaction, Value.Type.STRING);
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `BOOLEAN`
a| `DATETIME`
a| `DOUBLE`
a| `LONG`
a| `OBJECT`
a| `STRING`
|===
// end::enum_constants[]

// tag::methods[]
[#_Value_Type_isKeyable__]
==== isKeyable

[source,java]
----
@CheckReturnValue
public boolean isKeyable()
----

Returns ``true`` if this value concept can be used as a key via the @key annotation. Otherwise, returns ``false``. 


[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
valueType.isKeyable();
----

[#_Value_Type_isWritable__]
==== isWritable

[source,java]
----
@CheckReturnValue
public boolean isWritable()
----

Returns ``true`` if this value concept can be written to a database. Otherwise, returns ``false``. 


[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
valueType.isWritable();
----

[#_Value_Type_of__com_vaticle_typedb_driver_jni_ValueType]
==== of

[source,java]
----
@CheckReturnValue
public static Value.Type of​(com.vaticle.typedb.driver.jni.ValueType valueType)
----



[caption=""]
.Returns
`public static Value.Type`

[#_Value_Type_valueClass__]
==== valueClass

[source,java]
----
@CheckReturnValue
public java.lang.Class<?> valueClass()
----

Returns a ``Class`` equivalent of this value concept for this programming language. 


[caption=""]
.Returns
`public java.lang.Class<?>`

[caption=""]
.Code examples
[source,java]
----
valueType.valueClass();
----

[#_Value_Type_valueOf__java_lang_String]
==== valueOf

[source,java]
----
public static Value.Type valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static Value.Type`

[#_Value_Type_values__]
==== values

[source,java]
----
public static Value.Type[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (Value.Type c : Value.Type.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static Value.Type[]`

[caption=""]
.Code examples
[source,java]
----
for (Value.Type c : Value.Type.values())
    System.out.println(c);
----

// end::methods[]

