[#_struct_Attribute]
=== Attribute

*Implements traits:*

* `AttributeAPI`
* `Clone`
* `Debug`
* `PartialEq<Attribute>`
* `StructuralPartialEq`
* `ThingAPI`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `IID` a| The unique id of this Attribute
a| `is_inferred` a| `bool` a| If this Attribute is inferred by a [Reasoning Rule] or not
a| `type_` a| `AttributeType` a| The type which this Attribute belongs to
a| `value` a| `Value` a| The value which this Attribute instance holds.
|===
// end::properties[]

// tag::methods[]
[#_struct_Attribute_delete__]
==== delete

[source,rust]
----
fn delete<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_delete,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Attribute_get_has__]
==== get_has

[source,rust]
----
fn get_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<Attribute>>>
----

<<#_trait_ThingAPI_method_get_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Attribute>>>
----

[#_struct_Attribute_get_owners__]
==== get_owners

[source,rust]
----
fn get_owners<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    thing_type: Option<ThingType>
) -> Result<BoxStream<'tx, Result<Thing>>>
----

<<#_trait_AttributeAPI_method_get_owners,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Thing>>>
----

[#_struct_Attribute_get_playing__]
==== get_playing

[source,rust]
----
fn get_playing<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_ThingAPI_method_get_playing,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_Attribute_get_relations__]
==== get_relations

[source,rust]
----
fn get_relations<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'tx, Result<Relation>>>
----

<<#_trait_ThingAPI_method_get_relations,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Relation>>>
----

[#_struct_Attribute_iid__]
==== iid

[source,rust]
----
fn iid(&self) -> &IID
----

<<#_trait_ThingAPI_tymethod_iid,Read more>>

[caption=""]
.Returns
[source,rust]
----
&IID
----

[#_struct_Attribute_is_deleted__]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

<<#_trait_ThingAPI_tymethod_is_deleted,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[#_struct_Attribute_is_inferred__]
==== is_inferred

[source,rust]
----
fn is_inferred(&self) -> bool
----

<<#_trait_ThingAPI_tymethod_is_inferred,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_Attribute_set_has__]
==== set_has

[source,rust]
----
fn set_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_set_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Attribute_unset_has__]
==== unset_has

[source,rust]
----
fn unset_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_unset_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

// end::methods[]

