[#_struct_Relation]
=== Relation

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq<Relation>`
* `RelationAPI`
* `StructuralEq`
* `StructuralPartialEq`
* `ThingAPI`

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `IID` a| The unique id of this Relation
a| `is_inferred` a| `bool` a| If this Relation is inferred by a [Reasoning Rule] or not
a| `type_` a| `RelationType` a| The type which this Relation belongs to
|===
// end::properties[]

// tag::methods[]
[#_struct_Relation_add_role_player__]
==== add_role_player

[source,rust]
----
fn add_role_player<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    player: Thing
) -> BoxPromise<'tx, Result>
----

<<#_trait_RelationAPI_method_add_role_player,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Relation_delete__]
==== delete

[source,rust]
----
fn delete<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_delete,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Relation_get_has__]
==== get_has

[source,rust]
----
fn get_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<Attribute>>>
----

<<#_trait_ThingAPI_method_get_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Attribute>>>
----

[#_struct_Relation_get_players_by_role_type__]
==== get_players_by_role_type

[source,rust]
----
fn get_players_by_role_type<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'tx, Result<Thing>>>
----

<<#_trait_RelationAPI_method_get_players_by_role_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Thing>>>
----

[#_struct_Relation_get_playing__]
==== get_playing

[source,rust]
----
fn get_playing<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_ThingAPI_method_get_playing,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_Relation_get_relating__]
==== get_relating

[source,rust]
----
fn get_relating<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_RelationAPI_method_get_relating,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_Relation_get_relations__]
==== get_relations

[source,rust]
----
fn get_relations<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'tx, Result<Relation>>>
----

<<#_trait_ThingAPI_method_get_relations,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Relation>>>
----

[#_struct_Relation_get_role_players__]
==== get_role_players

[source,rust]
----
fn get_role_players<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<(RoleType, Thing)>>>
----

<<#_trait_RelationAPI_method_get_role_players,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<(RoleType, Thing)>>>
----

[#_struct_Relation_iid__]
==== iid

[source,rust]
----
fn iid(&self) -> &IID
----

<<#_trait_ThingAPI_tymethod_iid,Read more>>

[caption=""]
.Returns
[source,rust]
----
&IID
----

[#_struct_Relation_is_deleted__]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

<<#_trait_ThingAPI_tymethod_is_deleted,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[#_struct_Relation_is_inferred__]
==== is_inferred

[source,rust]
----
fn is_inferred(&self) -> bool
----

<<#_trait_ThingAPI_tymethod_is_inferred,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_Relation_remove_role_player__]
==== remove_role_player

[source,rust]
----
fn remove_role_player<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    player: Thing
) -> BoxPromise<'tx, Result>
----

<<#_trait_RelationAPI_method_remove_role_player,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Relation_set_has__]
==== set_has

[source,rust]
----
fn set_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_set_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_Relation_unset_has__]
==== unset_has

[source,rust]
----
fn unset_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingAPI_method_unset_has,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

// end::methods[]

