[#_trait_RelationAPI]
=== Trait RelationAPI

*Implementors:*

* `Relation`

// tag::methods[]
[#_trait_RelationAPI_add_role_player__transaction_tx_Transaction_____role_type_RoleType__player_Thing]
==== add_role_player

[source,rust]
----
fn add_role_player<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    player: Thing
) -> BoxPromise<'tx, Result>
----

Adds a new role player to play the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_type` a| The role to be played by the ``player`` a| `RoleType`
a| `player` a| The thing to play the role a| `Thing`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation.add_role_player(transaction, role_type, player).await;
----

--

sync::
+
--
[source,rust]
----
relation.add_role_player(transaction, role_type, player).resolve();
----

--
====

[#_trait_RelationAPI_get_players_by_role_type__transaction_tx_Transaction_____role_types_Vec_RoleType_]
==== get_players_by_role_type

[source,rust]
----
fn get_players_by_role_type<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'tx, Result<Thing>>>
----

Retrieves all role players of this ``Relation``, optionally filtered by given role types.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_types` a| 0 or more role types a| `Vec<RoleType>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Thing>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation.get_players_by_role_type(transaction, role_types);
----

[#_trait_RelationAPI_get_relating__transaction_tx_Transaction___]
==== get_relating

[source,rust]
----
fn get_relating<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

Retrieves all role types currently played in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation.get_relating(transaction)
----

[#_trait_RelationAPI_get_role_players__transaction_tx_Transaction______-__Result_BoxStream_tx]
==== get_role_players

[source,rust]
----
fn get_role_players<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<(RoleType, Thing)>>>
----

Retrieves a mapping of all instances involved in the ``Relation`` and the role each play.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>
) -> Result<BoxStream<'tx`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<(RoleType, Thing)>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation.get_role_players(transaction)
----

[#_trait_RelationAPI_remove_role_player__transaction_tx_Transaction_____role_type_RoleType__player_Thing]
==== remove_role_player

[source,rust]
----
fn remove_role_player<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    player: Thing
) -> BoxPromise<'tx, Result>
----

Removes the association of the given instance that plays the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_type` a| The role to no longer be played by the thing in this ``Relation`` a| `RoleType`
a| `player` a| The instance to no longer play the role in this ``Relation`` a| `Thing`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation.remove_role_player(transaction, role_type, player).await;
----

--

sync::
+
--
[source,rust]
----
relation.remove_role_player(transaction, role_type, player).resolve();
----

--
====

// end::methods[]

