[#_trait_ThingAPI]
=== Trait ThingAPI

*Implementors:*

* `Attribute`
* `Entity`
* `Relation`

// tag::methods[]
[#_trait_ThingAPI_delete__transaction_tx_Transaction___]
==== delete

[source,rust]
----
fn delete<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing.delete(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing.delete(transaction).resolve();
----

--
====

[#_trait_ThingAPI_get_has__transaction_tx_Transaction_____attribute_type__attribute_types_Vec_AttributeType___annotations_Vec_Annotation_]
==== get_has

[source,rust]
----
fn get_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<Attribute>>>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `attribute_type` a| The ``AttributeType`` to filter the attributes by a| 
a| `attribute_types` a| The ``AttributeType``s to filter the attributes by a| `Vec<AttributeType>`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Vec<Annotation>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Attribute>>>
----

[caption=""]
.Code examples
[source,rust]
----
thing.get_has(transaction, attribute_type, annotations=vec![Annotation::Key]);
----

[#_trait_ThingAPI_get_playing__transaction_tx_Transaction___]
==== get_playing

[source,rust]
----
fn get_playing<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[caption=""]
.Code examples
[source,rust]
----
thing.get_playing(transaction);
----

[#_trait_ThingAPI_get_relations__transaction_tx_Transaction_____role_types_Vec_RoleType_]
==== get_relations

[source,rust]
----
fn get_relations<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'tx, Result<Relation>>>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_types` a| The list of roles to filter the relations by. a| `Vec<RoleType>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Relation>>>
----

[caption=""]
.Code examples
[source,rust]
----
thing.get_relations(transaction, role_types);
----

[#_trait_ThingAPI_iid__]
==== iid

[source,rust]
----
fn iid(&self) -> &IID
----

Retrieves the unique id of the ``Thing``.

[caption=""]
.Returns
[source,rust]
----
&IID
----

[caption=""]
.Code examples
[source,rust]
----
thing.iid();
----

[#_trait_ThingAPI_is_deleted__transaction_tx_Transaction___]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing.is_deleted(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing.is_deleted(transaction).resolve();
----

--
====

[#_trait_ThingAPI_is_inferred__]
==== is_inferred

[source,rust]
----
fn is_inferred(&self) -> bool
----

Checks if this ``Thing`` is inferred by a [Reasoning Rule].

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
thing.is_inferred();
----

[#_trait_ThingAPI_set_has__transaction_tx_Transaction_____attribute_Attribute]
==== set_has

[source,rust]
----
fn set_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing.set_has(transaction, attribute).await;
----

--

sync::
+
--
[source,rust]
----
thing.set_has(transaction, attribute).resolve();
----

--
====

[#_trait_ThingAPI_unset_has__transaction_tx_Transaction_____attribute_Attribute]
==== unset_has

[source,rust]
----
fn unset_has<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    attribute: Attribute
) -> BoxPromise<'tx, Result>
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing.unset_has(transaction, attribute).await;
----

--

sync::
+
--
[source,rust]
----
thing.unset_has(transaction, attribute).resolve();
----

--
====

// end::methods[]

