[#_DatabaseManager]
=== DatabaseManager

`Class(name=DatabaseManager, anchor=DatabaseManager, enumConstants=[], description=[Provides access to all database management methods.], examples=[], fields=[], methods=[Method(name=all, signature=all() -> List[Database], anchor=DatabaseManager_all_, args=[], description=[Retrieves all databases present on the TypeDB server.], examples=[driver.databases.all()], mode=null, returnDescription=, returnType=List[Database]), Method(name=contains, signature=contains(name: str) -> bool, anchor=DatabaseManager_contains_name_str, args=[Variable(name=name, anchor=null, defaultValue=null, description=The database name to be checked, type=str)], description=[Checks if a database with the given name exists.], examples=[driver.databases.contains(name)], mode=null, returnDescription=, returnType=bool), Method(name=create, signature=create(name: str) -> None, anchor=DatabaseManager_create_name_str, args=[Variable(name=name, anchor=null, defaultValue=null, description=The name of the database to be created, type=str)], description=[Create a database with the given name.], examples=[driver.databases.create(name)], mode=null, returnDescription=, returnType=None), Method(name=get, signature=get(name: str) -> Database, anchor=DatabaseManager_get_name_str, args=[Variable(name=name, anchor=null, defaultValue=null, description=The name of the database to retrieve, type=str)], description=[Retrieve the database with the given name.], examples=[driver.databases.get(name)], mode=null, returnDescription=, returnType=Database), Method(name=import_from_file, signature=import_from_file(name: str, schema: str, data_file_path: str) -> None, anchor=DatabaseManager_import_from_file_name_str_schema_str_data_file_path_str, args=[Variable(name=name, anchor=null, defaultValue=null, description=The name of the database to be created, type=str), Variable(name=schema, anchor=null, defaultValue=null, description=The schema definition query string for the database, type=str), Variable(name=data_file_path, anchor=null, defaultValue=null, description=The exported database file path to import the data from, type=str)], description=[Create a database with the given name based on previously exported another database’s data loaded from a file. This is a blocking operation and may take a significant amount of time depending on the database size.], examples=[driver.databases.import_from_file(name, schema, "data.typedb")], mode=null, returnDescription=, returnType=None)], packagePath=typedb.api.connection.database, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.connection.database`

Provides access to all database management methods.

// tag::methods[]
[#_DatabaseManager_all_]
==== all

[source,python]
----
all() -> List[Database]
----

Retrieves all databases present on the TypeDB server.

[caption=""]
.Returns
`List[Database]`

[caption=""]
.Code examples
[source,python]
----
driver.databases.all()
----

[#_DatabaseManager_contains_name_str]
==== contains

[source,python]
----
contains(name: str) -> bool
----

Checks if a database with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The database name to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.databases.contains(name)
----

[#_DatabaseManager_create_name_str]
==== create

[source,python]
----
create(name: str) -> None
----

Create a database with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.databases.create(name)
----

[#_DatabaseManager_get_name_str]
==== get

[source,python]
----
get(name: str) -> Database
----

Retrieve the database with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Database`

[caption=""]
.Code examples
[source,python]
----
driver.databases.get(name)
----

[#_DatabaseManager_import_from_file_name_str_schema_str_data_file_path_str]
==== import_from_file

[source,python]
----
import_from_file(name: str, schema: str, data_file_path: str) -> None
----

Create a database with the given name based on previously exported another database’s data loaded from a file. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to be created a| `str` a| 
a| `schema` a| The schema definition query string for the database a| `str` a| 
a| `data_file_path` a| The exported database file path to import the data from a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.databases.import_from_file(name, schema, "data.typedb")
----

// end::methods[]

