[#_DatabaseManager]
=== DatabaseManager

*Package*: `typedb.api.database.database_manager`

Provides access to all database management methods.

// tag::methods[]
[#_DatabaseManager_all_consistency_level_ConsistencyLevel_None]
==== all

[source,python]
----
all(consistency_level: ConsistencyLevel | None = None) -> List[Database]
----

Retrieves all databases present on the TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`List[Database]`

[caption=""]
.Code examples
[source,python]
----
driver.databases.all()
driver.databases.all(ConsistencyLevel.Strong())
----

[#_DatabaseManager_contains_name_str_consistency_level_ConsistencyLevel_None]
==== contains

[source,python]
----
contains(name: str, consistency_level: ConsistencyLevel | None = None) -> bool
----

Checks if a database with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The database name to be checked a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.databases.contains(name)
driver.databases.contains(name, ConsistencyLevel.Strong())
----

[#_DatabaseManager_create_name_str_consistency_level_ConsistencyLevel_None]
==== create

[source,python]
----
create(name: str, consistency_level: ConsistencyLevel | None = None) -> None
----

Creates a database with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to be created a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.databases.create(name)
driver.databases.create(name, ConsistencyLevel.Strong())
----

[#_DatabaseManager_get_name_str_consistency_level_ConsistencyLevel_None]
==== get

[source,python]
----
get(name: str, consistency_level: ConsistencyLevel | None = None) -> Database
----

Retrieves the database with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to retrieve a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`Database`

[caption=""]
.Code examples
[source,python]
----
driver.databases.get(name)
driver.databases.get(name, ConsistencyLevel.Strong())
----

[#_DatabaseManager_import_from_file_name_str_schema_str_data_file_path_str]
==== import_from_file

[source,python]
----
import_from_file(name: str, schema: str, data_file_path: str) -> None
----

Creates a database with the given name based on previously exported another database’s data loaded from a file. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to be created a| `str` a| 
a| `schema` a| The schema definition query string for the database a| `str` a| 
a| `data_file_path` a| The exported database file path to import the data from a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.databases.import_from_file(name, schema, "data.typedb")
----

// end::methods[]

