[#_Database]
=== class Database

*Package*: `typedb.api.connection.database`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `str` a| The database name as a string.
|===
// end::properties[]

// tag::methods[]
[#_Database_delete_]
==== delete

[source,python]
----
delete() -> None
----

Deletes this database.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
database.delete()
----

[#_Database_export_to_file_schema_file_path_str_data_file_path_str]
==== export_to_file

[source,python]
----
export_to_file(schema_file_path: str, data_file_path: str) -> None
----

Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `schema_file_path` a| The path to the schema definition file to be created a| `str` a| 
a| `data_file_path` a| The path to the data file to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
database.export_to_file("schema.typeql", "data.typedb")
----

[#_Database_schema_]
==== schema

[source,python]
----
schema() -> str
----

Returns a full schema text as a valid TypeQL define query string.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.schema()
----

[#_Database_type_schema_]
==== type_schema

[source,python]
----
type_schema() -> str
----

Returns the types in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.type_schema()
----

// end::methods[]

