[#_Database]
=== Database

*Package*: `typedb.api.database.database`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `str` a| The database name as a string.
|===
// end::properties[]

// tag::methods[]
[#_Database_delete_consistency_level_ConsistencyLevel_None]
==== delete

[source,python]
----
delete(consistency_level: ConsistencyLevel | None = None) -> None
----

Deletes this database.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
database.delete()
database.delete(ConsistencyLevel.Strong())
----

[#_Database_export_to_file_schema_file_path_str_data_file_path_str_consistency_level_ConsistencyLevel_None]
==== export_to_file

[source,python]
----
export_to_file(schema_file_path: str, data_file_path: str, consistency_level: ConsistencyLevel | None = None) -> None
----

Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `schema_file_path` a| The path to the schema definition file to be created a| `str` a| 
a| `data_file_path` a| The path to the data file to be created a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
database.export_to_file("schema.typeql", "data.typedb")
database.export_to_file("schema.typeql", "data.typedb", ConsistencyLevel.Strong())
----

[#_Database_schema_consistency_level_ConsistencyLevel_None]
==== schema

[source,python]
----
schema(consistency_level: ConsistencyLevel | None = None) -> str
----

Returns a full schema text as a valid TypeQL define query string.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.schema()
database.schema(ConsistencyLevel.Strong())
----

[#_Database_type_schema_consistency_level_ConsistencyLevel_None]
==== type_schema

[source,python]
----
type_schema(consistency_level: ConsistencyLevel | None = None) -> str
----

Returns the types in the schema as a valid TypeQL define query string.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.type_schema()
database.type_schema(ConsistencyLevel.Strong())
----

// end::methods[]

