[#_Driver]
[.doc-api-reference-driver]
=== Driver

`class`

*Package*: `typedb.api.connection.driver`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The ``UserManager`` for this connection, providing access to user management methods.
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== method ``close``

[source,python]
----
close() -> None
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.close()
----

[#_Driver_is_open_]
==== method ``is_open``

[source,python]
----
is_open() -> bool
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.is_open()
----

[#_Driver_primary_server_server_routing_ServerRouting_None]
==== method ``primary_server``

[source,python]
----
primary_server(server_routing: ServerRouting | None = None) -> Server | None
----

Returns the primary server for this driver connection.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `server_routing` a| The server routing to use for the operation. Auto by default a| `ServerRouting \| None` a| `None`
|===

[caption=""]
.Returns
`Server | None`

[caption=""]
.Code examples
[source,python]
----
driver.primary_server()
driver.primary_server(ServerRouting.Auto())
----

[#_Driver_server_version_server_routing_ServerRouting_None]
==== method ``server_version``

[source,python]
----
server_version(server_routing: ServerRouting | None = None) -> ServerVersion
----

Retrieves the server’s version.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `server_routing` a| The server routing to use for the operation. Auto by default a| `ServerRouting \| None` a| `None`
|===

[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,python]
----
driver.server_version()
driver.server_version(ServerRouting.Auto())
----

[#_Driver_servers_server_routing_ServerRouting_None]
==== method ``servers``

[source,python]
----
servers(server_routing: ServerRouting | None = None) -> Set[Server]
----

Set of servers for this driver connection.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `server_routing` a| The server routing to use for the operation. Auto by default a| `ServerRouting \| None` a| `None`
|===

[caption=""]
.Returns
`Set[Server]`

[caption=""]
.Code examples
[source,python]
----
driver.servers()
driver.servers(ServerRouting.Auto())
----

[#_Driver_transaction_database_name_str_transaction_type_TransactionType_options_TransactionOptions_None]
==== method ``transaction``

[source,python]
----
transaction(database_name: str, transaction_type: TransactionType, options: TransactionOptions | None = None) -> Transaction
----

Opens a transaction to the given database on the running TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `database_name` a| The name of the database with which the transaction connects a| `str` a| 
a| `transaction_type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `TransactionType` a| 
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,python]
----
driver.transaction(database, transaction_type, options)
----

// end::methods[]

