[#_Driver]
[.doc-api-reference-driver]
=== Driver

`class`

*Package*: `typedb.api.connection.driver`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The ``UserManager`` for this connection, providing access to user management methods.
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== method ``close``

[source,python]
----
close() -> None
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.close()
----

[#_Driver_deregister_server_server_id_int]
==== method ``deregister_server``

[source,python]
----
deregister_server(server_id: int) -> None
----

Deregisters a server from the cluster the driver is currently connected to. This server will no longer play a raft role in this cluster.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `server_id` a| The numeric identifier of the deregistered server a| `int` a|
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.deregister_server(2)
----

[#_Driver_is_open_]
==== method ``is_open``

[source,python]
----
is_open() -> bool
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.is_open()
----

[#_Driver_primary_server_consistency_level_ConsistencyLevel_None]
==== method ``primary_server``

[source,python]
----
primary_server(consistency_level: ConsistencyLevel | None = None) -> Server | None
----

Returns the primary server for this driver connection.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`Server | None`

[caption=""]
.Code examples
[source,python]
----
driver.primary_server()
driver.primary_server(ConsistencyLevel.Strong())
----

[#_Driver_register_server_server_id_int_address_str]
==== method ``register_server``

[source,python]
----
register_server(server_id: int, address: str) -> None
----

Registers a new server in the cluster the driver is currently connected to. The registered server will become available eventually, depending on the behavior of the whole cluster. To register a server, its clustering address should be passed, not the connection address.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `server_id` a| The numeric identifier of the new server a| `int` a|
a| `address` a| The address(es) of the TypeDB server as a string a| `str` a|
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.register_server(2, "127.0.0.1:11729")
----

[#_Driver_servers_consistency_level_ConsistencyLevel_None]
==== method ``servers``

[source,python]
----
servers(consistency_level: ConsistencyLevel | None = None) -> Set[Server]
----

Set of ``Server`` instances for this driver connection.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`Set[Server]`

[caption=""]
.Code examples
[source,python]
----
driver.servers()
driver.servers(ConsistencyLevel.Strong())
----

[#_Driver_server_version_consistency_level_ConsistencyLevel_None]
==== method ``server_version``

[source,python]
----
server_version(consistency_level: ConsistencyLevel | None = None) -> ServerVersion
----

Retrieves the server’s version.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,python]
----
driver.server_version()
driver.server_version(ConsistencyLevel.Strong())
----

[#_Driver_transaction_database_name_str_transaction_type_TransactionType_options_TransactionOptions_None]
==== method ``transaction``

[source,python]
----
transaction(database_name: str, transaction_type: TransactionType, options: TransactionOptions | None = None) -> Transaction
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `database_name` a| The name of the database with which the transaction connects a| `str` a| 
a| `transaction_type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `TransactionType` a| 
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,python]
----
driver.transaction(database, transaction_type, options)
----

[#_Driver_update_address_translation_address_translation_Mapping_str_str_]
==== method ``update_address_translation``

[source,python]
----
update_address_translation(address_translation: Mapping[str, str]) -> None
----

Updates address translation of the driver. This lets you actualize new translation information without recreating the driver from scratch. Useful after registering new servers requiring address translation. This operation will update existing connections using the provided addresses.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `address_translation` a| The translation of public TypeDB cluster server addresses (keys) to server-side private addresses (values) a| `Mapping[str, str]` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.update_address_translation({"typedb-cloud.ext:11729": "127.0.0.1:11729"})
----

// end::methods[]

