[#_Driver]
=== Driver

`Class(name=Driver, anchor=Driver, enumConstants=[], description=[], examples=[], fields=[Variable(name=databases, anchor=null, defaultValue=null, description=The ``DatabaseManager`` for this connection, providing access to database management methods., type=DatabaseManager), Variable(name=users, anchor=null, defaultValue=null, description=The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud., type=UserManager)], methods=[Method(name=close, signature=close() -> None, anchor=Driver_close_, args=[], description=[Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.], examples=[driver.close()], mode=null, returnDescription=, returnType=None), Method(name=is_open, signature=is_open() -> bool, anchor=Driver_is_open_, args=[], description=[Checks whether this connection is presently open.], examples=[driver.is_open()], mode=null, returnDescription=, returnType=bool), Method(name=transaction, signature=transaction(database_name: str, transaction_type: TransactionType, options: TransactionOptions | None = None) -> Transaction, anchor=Driver_transaction_database_name_str_transaction_type_TransactionType_options_TransactionOptions_None, args=[Variable(name=database_name, anchor=null, defaultValue=null, description=The name of the database with which the transaction connects, type=str), Variable(name=transaction_type, anchor=null, defaultValue=null, description=The type of transaction to be created (READ, WRITE, or SCHEMA), type=TransactionType), Variable(name=options, anchor=null, defaultValue=None, description=``TransactionOptions`` to configure the opened transaction, type=TransactionOptions | None)], description=[Opens a communication tunnel (transaction) to the given database on the running TypeDB server.], examples=[driver.transaction(database, transaction_type, options)], mode=null, returnDescription=, returnType=Transaction)], packagePath=typedb.api.connection.driver, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.connection.driver`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud.
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== close

[source,python]
----
close() -> None
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.close()
----

[#_Driver_is_open_]
==== is_open

[source,python]
----
is_open() -> bool
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.is_open()
----

[#_Driver_transaction_database_name_str_transaction_type_TransactionType_options_TransactionOptions_None]
==== transaction

[source,python]
----
transaction(database_name: str, transaction_type: TransactionType, options: TransactionOptions | None = None) -> Transaction
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `database_name` a| The name of the database with which the transaction connects a| `str` a| 
a| `transaction_type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `TransactionType` a| 
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,python]
----
driver.transaction(database, transaction_type, options)
----

// end::methods[]

