[#_DriverOptions]
=== DriverOptions

TypeDB driver options. ``DriverOptions`` are used to specify the driver’s connection behavior.

Options could be specified either as constructor arguments or using properties assignment.

[caption=""]
.Examples
[source,python]
----
driver_options = DriverOptions(tls_enabled=True)
driver_options.tls_root_ca_path = "path/to/ca-certificate.pem"
----

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `is_tls_enabled` a| `bool` a| Returns the value set for the TLS flag in this ``DriverOptions`` object. Specifies whether the connection to TypeDB must be done over TLS.
a| `primary_failover_retries` a| `int` a| Returns the value set for the primary failover retries limit in this ``DriverOptions`` object. Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles.
a| `replica_discovery_attempts` a| `int \| None` a| Returns the value set for the replica discovery attempts limit in this ``DriverOptions`` object. Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most: - {limit} operations are performed if the limit &lt;= the number of replicas. - {number of replicas} operations are performed if the limit &gt; the number of replicas. - {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown. If not set, the maximum (practically unlimited) value is used.
a| `tls_root_ca_path` a| `str \| None` a| Returns the TLS root CA set in this ``DriverOptions`` object. Specifies the root CA used in the TLS config for server certificates authentication. Uses system roots if None is set.
a| `use_replication` a| `bool` a| Returns the value set for the replication usage flag in this ``DriverOptions`` object. Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address.
|===
// end::properties[]

