[#_Driver]
=== Driver

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The ``UserManager`` for this connection, providing access to user management methods.
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== close

[source,python]
----
close() -> None
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.close()
----

[#_Driver_deregister_replica_replica_id_int]
==== deregister_replica

[source,python]
----
deregister_replica(replica_id: int) -> None
----

Deregisters a replica from the cluster the driver is currently connected to. This replica will no longer play a raft role in this cluster.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `replica_id` a| The numeric identifier of the deregistered replica a| `int` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.deregister_replica(2)
----

[#_Driver_is_open_]
==== is_open

[source,python]
----
is_open() -> bool
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.is_open()
----

[#_Driver_primary_replica_]
==== primary_replica

[source,python]
----
primary_replica() -> ServerReplica | None
----

Returns the primary replica for this driver connection.

[caption=""]
.Returns
`ServerReplica | None`

[caption=""]
.Code examples
[source,python]
----
driver.primary_replica()
----

[#_Driver_register_replica_replica_id_int_address_str]
==== register_replica

[source,python]
----
register_replica(replica_id: int, address: str) -> None
----

Registers a new replica in the cluster the driver is currently connected to. The registered replica will become available eventually, depending on the behavior of the whole cluster.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `replica_id` a| The numeric identifier of the new replica a| `int` a| 
a| `address` a| The address(es) of the TypeDB replica as a string a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.register_replica(2, "127.0.0.1:11729")
----

[#_Driver_replicas_]
==== replicas

[source,python]
----
replicas() -> Set[ServerReplica]
----

Set of ``Replica`` instances for this driver connection.

[caption=""]
.Returns
`Set[ServerReplica]`

[caption=""]
.Code examples
[source,python]
----
driver.replicas()
----

[#_Driver_server_version_]
==== server_version

[source,python]
----
server_version() -> ServerVersion
----

Retrieves the server’s version.

[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,python]
----
driver.server_version()
----

[#_Driver_transaction_database_name_str_transaction_type_TransactionType_options_TransactionOptions_None]
==== transaction

[source,python]
----
transaction(database_name: str, transaction_type: TransactionType, options: TransactionOptions | None = None) -> Transaction
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `database_name` a| The name of the database with which the transaction connects a| `str` a| 
a| `transaction_type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `TransactionType` a| 
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,python]
----
driver.transaction(database, transaction_type, options)
----

// end::methods[]

