[#_TypeDB]
=== TypeDB

`Class(name=TypeDB, anchor=TypeDB, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=driver, signature=static driver(address: str, credentials: Credentials, driver_options: DriverOptions) -> Driver, anchor=TypeDB_driver_address_str_credentials_Credentials_driver_options_DriverOptions, args=[Variable(name=address, anchor=null, defaultValue=null, description=Address of the TypeDB server., type=str), Variable(name=credentials, anchor=null, defaultValue=null, description=The credentials to connect with., type=Credentials), Variable(name=driver_options, anchor=null, defaultValue=null, description=The connection settings to connect with., type=DriverOptions)], description=[Creates a connection to TypeDB.], examples=[], mode=null, returnDescription=, returnType=Driver)], packagePath=typedb.driver, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.driver`

// tag::methods[]
[#_TypeDB_driver_address_str_credentials_Credentials_driver_options_DriverOptions]
==== driver

[source,python]
----
static driver(address: str, credentials: Credentials, driver_options: DriverOptions) -> Driver
----

Creates a connection to TypeDB.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `address` a| Address of the TypeDB server. a| `str` a| 
a| `credentials` a| The credentials to connect with. a| `Credentials` a| 
a| `driver_options` a| The connection settings to connect with. a| `DriverOptions` a| 
|===

[caption=""]
.Returns
`Driver`

// end::methods[]

