[#_UserManager]
[.doc-api-reference-driver]
=== UserManager

`class`

*Package*: `typedb.api.user.user_manager`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== method ``all``

[source,python]
----
all() -> List[User]
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
`List[User]`

[caption=""]
.Code examples
[source,python]
----
driver.users.all()
----

[#_UserManager_contains_username_str]
==== method ``contains``

[source,python]
----
contains(username: str) -> bool
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The username to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.users.contains(username)
----

[#_UserManager_create_username_str_password_str]
==== method ``create``

[source,python]
----
create(username: str, password: str) -> None
----

Creates a user with the given name and password.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be created a| `str` a| 
a| `password` a| The password of the user to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.create(username, password)
----

[#_UserManager_get_username_str]
==== method ``get``

[source,python]
----
get(username: str) -> User | None
----

Retrieves a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get(username)
----

[#_UserManager_get_current_]
==== method ``get_current``

[source,python]
----
get_current() -> User | None
----

Retrieves the name of the user who opened the current connection.

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get_current()
----

// end::methods[]

