[#_User]
=== User

`Class(name=User, anchor=User, enumConstants=[], description=[TypeDB user information], examples=[], fields=[Variable(name=name, anchor=null, defaultValue=null, description=Returns the name of this user.

, type=str)], methods=[Method(name=delete, signature=delete() -> None, anchor=User_delete_username, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to be deleted, type=null)], description=[Deletes a user with the given name.], examples=[driver.users.delete(username)], mode=null, returnDescription=, returnType=None), Method(name=update_password, signature=update_password(password: str) -> None, anchor=User_update_password_password_old_password_new, args=[Variable(name=password_old, anchor=null, defaultValue=null, description=The current password of this user, type=null), Variable(name=password_new, anchor=null, defaultValue=null, description=The new password, type=null)], description=[Updates the password for this user.], examples=[], mode=null, returnDescription=, returnType=None)], packagePath=typedb.api.user.user, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.user.user`

TypeDB user information

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `str` a| Returns the name of this user.


|===
// end::properties[]

// tag::methods[]
[#_User_delete_username]
==== delete

[source,python]
----
delete() -> None
----

Deletes a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be deleted a|  a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.delete(username)
----

[#_User_update_password_password_old_password_new]
==== update_password

[source,python]
----
update_password(password: str) -> None
----

Updates the password for this user.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `password_old` a| The current password of this user a|  a| 
a| `password_new` a| The new password a|  a| 
|===

[caption=""]
.Returns
`None`

// end::methods[]

