[#_User]
=== User

*Package*: `typedb.api.user.user`

TypeDB user information

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `str` a| Returns the name of this user.


|===
// end::properties[]

// tag::methods[]
[#_User_delete_consistency_level_ConsistencyLevel_None]
==== delete

[source,python]
----
delete(consistency_level: ConsistencyLevel | None = None) -> None
----

Deletes this user.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
user.delete()
user.delete(ConsistencyLevel.Strong())
----

[#_User_update_password_password_str_consistency_level_ConsistencyLevel_None]
==== update_password

[source,python]
----
update_password(password: str, consistency_level: ConsistencyLevel | None = None) -> None
----

Updates the password for this user.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `password` a| The new password a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
user.update_password("new-password")
user.update_password("new-password", ConsistencyLevel.Strong())
----

// end::methods[]

