[#_UserManager]
=== UserManager

`Class(name=UserManager, anchor=UserManager, enumConstants=[], description=[Provides access to all user management methods.], examples=[], fields=[], methods=[Method(name=all, signature=all() -> List[User], anchor=UserManager_all_, args=[], description=[Retrieves all users which exist on the TypeDB server.], examples=[driver.users.all()], mode=null, returnDescription=, returnType=List[User]), Method(name=contains, signature=contains(username: str) -> bool, anchor=UserManager_contains_username_str, args=[Variable(name=username, anchor=null, defaultValue=null, description=The user name to be checked, type=str)], description=[Checks if a user with the given name exists.], examples=[driver.users.contains(username)], mode=null, returnDescription=, returnType=bool), Method(name=create, signature=create(username: str, password: str) -> None, anchor=UserManager_create_username_str_password_str, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to be created, type=str), Variable(name=password, anchor=null, defaultValue=null, description=The password of the user to be created, type=str)], description=[Create a user with the given name and password.], examples=[driver.users.create(username, password)], mode=null, returnDescription=, returnType=None), Method(name=get, signature=get(username: str) -> User | None, anchor=UserManager_get_username_str, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to retrieve, type=str)], description=[Retrieve a user with the given name.], examples=[driver.users.get(username)], mode=null, returnDescription=, returnType=User | None), Method(name=get_current_user, signature=get_current_user() -> User | None, anchor=UserManager_get_current_user_, args=[], description=[Retrieve the name of the user who opened the current connection.], examples=[driver.users.get_current_user()], mode=null, returnDescription=, returnType=User | None)], packagePath=typedb.api.user.user, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.user.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== all

[source,python]
----
all() -> List[User]
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
`List[User]`

[caption=""]
.Code examples
[source,python]
----
driver.users.all()
----

[#_UserManager_contains_username_str]
==== contains

[source,python]
----
contains(username: str) -> bool
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The user name to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.users.contains(username)
----

[#_UserManager_create_username_str_password_str]
==== create

[source,python]
----
create(username: str, password: str) -> None
----

Create a user with the given name and password.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be created a| `str` a| 
a| `password` a| The password of the user to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.create(username, password)
----

[#_UserManager_get_username_str]
==== get

[source,python]
----
get(username: str) -> User | None
----

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get(username)
----

[#_UserManager_get_current_user_]
==== get_current_user

[source,python]
----
get_current_user() -> User | None
----

Retrieve the name of the user who opened the current connection.

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get_current_user()
----

// end::methods[]

