[#_UserManager]
=== UserManager

*Package*: `typedb.api.user.user_manager`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_consistency_level_ConsistencyLevel_None]
==== all

[source,python]
----
all(consistency_level: ConsistencyLevel | None = None) -> List[User]
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`List[User]`

[caption=""]
.Code examples
[source,python]
----
driver.users.all()
driver.users.all(ConsistencyLevel.Strong())
----

[#_UserManager_contains_username_str_consistency_level_ConsistencyLevel_None]
==== contains

[source,python]
----
contains(username: str, consistency_level: ConsistencyLevel | None = None) -> bool
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The username to be checked a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.users.contains(username)
driver.users.contains(username, ConsistencyLevel.Strong())
----

[#_UserManager_create_username_str_password_str_consistency_level_ConsistencyLevel_None]
==== create

[source,python]
----
create(username: str, password: str, consistency_level: ConsistencyLevel | None = None) -> None
----

Creates a user with the given name and password.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be created a| `str` a| 
a| `password` a| The password of the user to be created a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.create(username, password)
driver.users.create(username, password, ConsistencyLevel.Strong())
----

[#_UserManager_get_username_str_consistency_level_ConsistencyLevel_None]
==== get

[source,python]
----
get(username: str, consistency_level: ConsistencyLevel | None = None) -> User | None
----

Retrieves a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to retrieve a| `str` a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get(username)
driver.users.get(username, ConsistencyLevel.Strong())
----

[#_UserManager_get_current_consistency_level_ConsistencyLevel_None]
==== get_current

[source,python]
----
get_current(consistency_level: ConsistencyLevel | None = None) -> User | None
----

Retrieves the name of the user who opened the current connection.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible by default a| `ConsistencyLevel \| None` a| `None`
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get_current()
driver.users.get_current(ConsistencyLevel.Strong())
----

// end::methods[]

