[#_UserManager]
=== UserManager

`class`

*Package*: `typedb.api.user.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== all

[source,python]
----
all() -> List[User]
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
`List[User]`

[caption=""]
.Code examples
[source,python]
----
driver.users.all()
----

[#_UserManager_contains_username_str]
==== contains

[source,python]
----
contains(username: str) -> bool
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The user name to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.users.contains(username)
----

[#_UserManager_create_username_str_password_str]
==== create

[source,python]
----
create(username: str, password: str) -> None
----

Create a user with the given name and password.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be created a| `str` a| 
a| `password` a| The password of the user to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.create(username, password)
----

[#_UserManager_get_username_str]
==== get

[source,python]
----
get(username: str) -> User | None
----

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get(username)
----

[#_UserManager_get_current_user_]
==== get_current_user

[source,python]
----
get_current_user() -> User | None
----

Retrieve the name of the user who opened the current connection.

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get_current_user()
----

// end::methods[]

