[#_Attribute]
=== Attribute

*Supertypes:*

* `Thing`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `string` a| Retrieves the unique id of the Thing.
a| `inferred` a| `boolean` a| Checks if this Thing is inferred by a [Reasoning Rule].
a| `type` a| `AttributeType` a| The type which this Attribute belongs to.
a| `value` a| `string` a| The value which the Attribute instance holds.
a| `valueType` a| `ValueType` a| The type of the value which the Attribute instance holds.
|===
// end::properties[]

// tag::methods[]
[#_Attribute_asAttribute__]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_Attribute_asAttributeType__]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_Attribute_asEntity__]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_Attribute_asEntityType__]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_Attribute_asRelation__]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_Attribute_asRelationType__]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_Attribute_asRoleType__]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_Attribute_asThing__]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_Attribute_asThingType__]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_Attribute_asType__]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_Attribute_asValue__]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_Attribute_delete__transaction_TypeDBTransaction]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.delete(transaction)
----

[#_Attribute_equals__concept_Concept]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_Attribute_getHas__transaction_TypeDBTransaction]
==== getHas

[source,nodejs]
----
getHas(transaction): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHas__transaction_TypeDBTransaction__annotations_Annotation__]
==== getHas

[source,nodejs]
----
getHas(transaction, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| The ``AttributeType``s to filter the attributes by a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHas__transaction_TypeDBTransaction__attributeType_AttributeType]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeType): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType``s to filter the attributes by a| `AttributeType`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHas__transaction_TypeDBTransaction__attributeTypes_AttributeType__]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHas__transaction_TypeDBTransaction__attributeTypes_AttributeType____annotations_Annotation__]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getOwners__transaction_TypeDBTransaction__ownerType_ThingType]
==== getOwners

[source,nodejs]
----
getOwners(transaction, ownerType?): Stream<Thing>
----

Retrieves the instances that own this ``Attribute``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `ownerType` a| If specified, filter results for only owners of the given type a| `ThingType`
|===

[caption=""]
.Returns
`Stream<Thing>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute.getOwners(transaction) attribute.getOwners(transaction, ownerType)
----

[#_Attribute_getPlaying__transaction_TypeDBTransaction]
==== getPlaying

[source,nodejs]
----
getPlaying(transaction): Stream<RoleType>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getPlaying(transaction)
----

[#_Attribute_getRelations__transaction_TypeDBTransaction]
==== getRelations

[source,nodejs]
----
getRelations(transaction): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Attribute_getRelations__transaction_TypeDBTransaction__roleTypes_RoleType__]
==== getRelations

[source,nodejs]
----
getRelations(transaction, roleTypes): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleTypes` a| The list of roles to filter the relations by. a| `RoleType[]`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Attribute_isAttribute__]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_Attribute_isAttributeType__]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_Attribute_isDeleted__transaction_TypeDBTransaction]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.isDeleted(transaction)
----

[#_Attribute_isEntity__]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_Attribute_isEntityType__]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_Attribute_isRelation__]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_Attribute_isRelationType__]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_Attribute_isRoleType__]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_Attribute_isThing__]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_Attribute_isThingType__]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_Attribute_isType__]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_Attribute_isValue__]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_Attribute_setHas__transaction_TypeDBTransaction__attribute_Attribute]
==== setHas

[source,nodejs]
----
setHas(transaction, attribute): Promise<void>
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.setHas(transaction, attribute)
----

[#_Attribute_unsetHas__transaction_TypeDBTransaction__attribute_Attribute]
==== unsetHas

[source,nodejs]
----
unsetHas(transaction, attribute): Promise<void>
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.unsetHas(transaction, attribute)
----

// end::methods[]

