[#_Attribute]
=== Attribute

*Supertypes:*

* `Thing`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `string` a| Retrieves the unique id of the Thing.
a| `inferred` a| `boolean` a| Checks if this Thing is inferred by a [Reasoning Rule].
a| `type` a| `AttributeType` a| The type which this Attribute belongs to.
a| `value` a| `string` a| The value which the Attribute instance holds.
a| `valueType` a| `ValueType` a| The type of the value which the Attribute instance holds.
|===
// end::properties[]

// tag::methods[]
[#_Attribute_asAttributeasAttribute__:_Attribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_Attribute_asAttributeTypeasAttributeType__:_AttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_Attribute_asEntityasEntity__:_Entity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_Attribute_asEntityTypeasEntityType__:_EntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_Attribute_asRelationasRelation__:_Relation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_Attribute_asRelationTypeasRelationType__:_RelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_Attribute_asRoleTypeasRoleType__:_RoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_Attribute_asThingasThing__:_Thing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_Attribute_asThingTypeasThingType__:_ThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_Attribute_asTypeasType__:_Type]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_Attribute_asValueasValue__:_Value]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_Attribute_deletedelete_transaction_:_Promise_void]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.delete(transaction)
----

[#_Attribute_equalsequals_concept_:_boolean]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_Attribute_getHasgetHas_transaction_:_Stream_Attribute]
==== getHas

[source,nodejs]
----
getHas(transaction): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHasgetHas_transaction__annotations_:_Stream_Attribute]
==== getHas

[source,nodejs]
----
getHas(transaction, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| The ``AttributeType``s to filter the attributes by a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHasgetHas_transaction__attributeType_:_Stream_Attribute]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeType): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType``s to filter the attributes by a| `AttributeType`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHasgetHas_transaction__attributeTypes_:_Stream_Attribute]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getHasgetHas_transaction__attributeTypes__annotations_:_Stream_Attribute]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Attribute_getOwnersgetOwners_transaction__ownerType?_:_Stream_Thing]
==== getOwners

[source,nodejs]
----
getOwners(transaction, ownerType?): Stream<Thing>
----

Retrieves the instances that own this ``Attribute``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `ownerType` a| If specified, filter results for only owners of the given type a| `ThingType`
|===

[caption=""]
.Returns
`Stream<Thing>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute.getOwners(transaction) attribute.getOwners(transaction, ownerType)
----

[#_Attribute_getPlayinggetPlaying_transaction_:_Stream_RoleType]
==== getPlaying

[source,nodejs]
----
getPlaying(transaction): Stream<RoleType>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getPlaying(transaction)
----

[#_Attribute_getRelationsgetRelations_transaction_:_Stream_Relation]
==== getRelations

[source,nodejs]
----
getRelations(transaction): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Attribute_getRelationsgetRelations_transaction__roleTypes_:_Stream_Relation]
==== getRelations

[source,nodejs]
----
getRelations(transaction, roleTypes): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleTypes` a| The list of roles to filter the relations by. a| `RoleType[]`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Attribute_isAttributeisAttribute__:_boolean]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_Attribute_isAttributeTypeisAttributeType__:_boolean]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_Attribute_isDeletedisDeleted_transaction_:_Promise_boolean]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.isDeleted(transaction)
----

[#_Attribute_isEntityisEntity__:_boolean]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_Attribute_isEntityTypeisEntityType__:_boolean]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_Attribute_isRelationisRelation__:_boolean]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_Attribute_isRelationTypeisRelationType__:_boolean]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_Attribute_isRoleTypeisRoleType__:_boolean]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_Attribute_isThingisThing__:_boolean]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_Attribute_isThingTypeisThingType__:_boolean]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_Attribute_isTypeisType__:_boolean]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_Attribute_isValueisValue__:_boolean]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_Attribute_setHassetHas_transaction__attribute_:_Promise_void]
==== setHas

[source,nodejs]
----
setHas(transaction, attribute): Promise<void>
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.setHas(transaction, attribute)
----

[#_Attribute_toJSONRecordtoJSONRecord__:_Record_string__string_|_number_|_boolean]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

[caption=""]
.Returns
`Record<string, string | number | boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

[#_Attribute_unsetHasunsetHas_transaction__attribute_:_Promise_void]
==== unsetHas

[source,nodejs]
----
unsetHas(transaction, attribute): Promise<void>
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.unsetHas(transaction, attribute)
----

// end::methods[]

