[#_Value]
=== Value

*Supertypes:*

* `Concept`

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `value` a| `string` a| Retrieves the value which this value concept holds.
a| `valueType` a| `ValueType` a| The ValueType of this value concept
|===
// end::properties[]

// tag::methods[]
[#_asAttribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_asBoolean]
==== asBoolean

[source,nodejs]
----
asBoolean(): boolean
----

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.asBoolean()
----

[#_asDateTime]
==== asDateTime

[source,nodejs]
----
asDateTime(): Date
----

Returns a ``datetime`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Date`

[caption=""]
.Code examples
[source,nodejs]
----
value.asDatetime()
----

[#_asDouble]
==== asDouble

[source,nodejs]
----
asDouble(): number
----

Returns a ``number`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`number`

[caption=""]
.Code examples
[source,nodejs]
----
value.asDouble()
----

[#_asEntity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_asLong]
==== asLong

[source,nodejs]
----
asLong(): number
----

Returns a ``number`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`number`

[caption=""]
.Code examples
[source,nodejs]
----
value.asLong()
----

[#_asRelation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_asString]
==== asString

[source,nodejs]
----
asString(): string
----

Returns a ``string`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,nodejs]
----
value.asString()
----

[#_asThing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_asType]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_asValue]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_equals]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_isAttribute]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_isBoolean]
==== isBoolean

[source,nodejs]
----
isBoolean(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isBoolean()
----

[#_isDateTime]
==== isDateTime

[source,nodejs]
----
isDateTime(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``datetime``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isDatetime()
----

[#_isDouble]
==== isDouble

[source,nodejs]
----
isDouble(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isDouble()
----

[#_isEntity]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_isLong]
==== isLong

[source,nodejs]
----
isLong(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isLong()
----

[#_isRelation]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_isString]
==== isString

[source,nodejs]
----
isString(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isString()
----

[#_isThing]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_isType]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_isValue]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_toJSONRecord]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

[caption=""]
.Returns
`Record<string, string | number | boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

// end::methods[]

