[#_Value]
=== Value

*Supertypes:*

* `Concept`

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `value` a| `string` a| Retrieves the value which this value concept holds.
a| `valueType` a| `ValueType` a| The ValueType of this value concept
|===
// end::properties[]

// tag::methods[]
[#_Value_asAttributeasAttribute__:_Attribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_Value_asAttributeTypeasAttributeType__:_AttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_Value_asBooleanasBoolean__:_boolean]
==== asBoolean

[source,nodejs]
----
asBoolean(): boolean
----

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.asBoolean()
----

[#_Value_asDateTimeasDateTime__:_Date]
==== asDateTime

[source,nodejs]
----
asDateTime(): Date
----

Returns a ``datetime`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Date`

[caption=""]
.Code examples
[source,nodejs]
----
value.asDatetime()
----

[#_Value_asDoubleasDouble__:_number]
==== asDouble

[source,nodejs]
----
asDouble(): number
----

Returns a ``number`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`number`

[caption=""]
.Code examples
[source,nodejs]
----
value.asDouble()
----

[#_Value_asEntityasEntity__:_Entity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_Value_asEntityTypeasEntityType__:_EntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_Value_asLongasLong__:_number]
==== asLong

[source,nodejs]
----
asLong(): number
----

Returns a ``number`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`number`

[caption=""]
.Code examples
[source,nodejs]
----
value.asLong()
----

[#_Value_asRelationasRelation__:_Relation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_Value_asRelationTypeasRelationType__:_RelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_Value_asRoleTypeasRoleType__:_RoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_Value_asStringasString__:_string]
==== asString

[source,nodejs]
----
asString(): string
----

Returns a ``string`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,nodejs]
----
value.asString()
----

[#_Value_asThingasThing__:_Thing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_Value_asThingTypeasThingType__:_ThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_Value_asTypeasType__:_Type]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_Value_asValueasValue__:_Value]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_Value_equalsequals_concept_:_boolean]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_Value_isAttributeisAttribute__:_boolean]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_Value_isAttributeTypeisAttributeType__:_boolean]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_Value_isBooleanisBoolean__:_boolean]
==== isBoolean

[source,nodejs]
----
isBoolean(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isBoolean()
----

[#_Value_isDateTimeisDateTime__:_boolean]
==== isDateTime

[source,nodejs]
----
isDateTime(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``datetime``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isDatetime()
----

[#_Value_isDoubleisDouble__:_boolean]
==== isDouble

[source,nodejs]
----
isDouble(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isDouble()
----

[#_Value_isEntityisEntity__:_boolean]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_Value_isEntityTypeisEntityType__:_boolean]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_Value_isLongisLong__:_boolean]
==== isLong

[source,nodejs]
----
isLong(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isLong()
----

[#_Value_isRelationisRelation__:_boolean]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_Value_isRelationTypeisRelationType__:_boolean]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_Value_isRoleTypeisRoleType__:_boolean]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_Value_isStringisString__:_boolean]
==== isString

[source,nodejs]
----
isString(): boolean
----

Returns ``True`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``False``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
value.isString()
----

[#_Value_isThingisThing__:_boolean]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_Value_isThingTypeisThingType__:_boolean]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_Value_isTypeisType__:_boolean]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_Value_isValueisValue__:_boolean]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

// end::methods[]

