[#_TypeDB_Driver_Api_IRule_Interface_Reference]
=== TypeDB.Driver.Api.IRule Interface Reference

*Package*: `TypeDB.Driver.Api.IRule Interface Reference`



Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

// tag::methods[]
[#_VoidPromise_TypeDB_Driver_Api_IRule_Delete___ITypeDBTransaction_transaction_]
==== Delete

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IRule.Delete(ITypeDBTransaction transaction)
----



Deletes this rule.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_Promise__bool___TypeDB_Driver_Api_IRule_IsDeleted___ITypeDBTransaction_transaction_]
==== IsDeleted

[source,cs]
----
Promise< bool > TypeDB.Driver.Api.IRule.IsDeleted(ITypeDBTransaction transaction)
----



Check if this rule has been deleted.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| 
|===

[caption=""]
.Returns
`Promise< bool >`

[#_VoidPromise_TypeDB_Driver_Api_IRule_SetLabel___ITypeDBTransaction_transaction__string_label_]
==== SetLabel

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IRule.SetLabel(ITypeDBTransaction transaction, string label)
----



Renames the label of the rule. The new label must remain unique.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| 
a| `label` a| The new label to be given to the rule a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

