[#_enum_ConnectionError]
=== ConnectionError

`class`

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `AbsentTlsConfigForTlsConnection`
a| `AddressTranslationMismatch`
a| `AnalyzeNoResponse`
a| `BrokenPipe`
a| `ClusterAllNodesFailed`
a| `ClusterReplicaNotPrimary`
a| `ConnectionFailed`
a| `DatabaseExportChannelIsClosed`
a| `DatabaseExportStreamNoResponse`
a| `DatabaseImportChannelIsClosed`
a| `DatabaseImportStreamUnexpectedResponse`
a| `DatabaseNotFound`
a| `EncryptionSettingsMismatch`
a| `InvalidResponseField`
a| `ListsNotImplemented`
a| `MissingPort`
a| `MissingResponseField`
a| `NonTlsConnectionWithHttps`
a| `QueryStreamNoResponse`
a| `RPCMethodUnavailable`
a| `SSLCertificateNotValidated`
a| `ServerConnectionFailed`
a| `ServerConnectionFailedStatusError`
a| `ServerConnectionFailedWithError`
a| `ServerConnectionIsClosed`
a| `TlsConnectionWithoutHttps`
a| `TokenCredentialInvalid`
a| `TransactionIsClosed`
a| `TransactionIsClosedWithErrors`
a| `UnexpectedConnectionClose`
a| `UnexpectedKind`
a| `UnexpectedQueryType`
a| `UnexpectedResponse`
a| `UnknownRequestId`
a| `ValueStructNotImplemented`
a| `ValueTimeZoneNameNotRecognised`
a| `ValueTimeZoneOffsetNotRecognised`
|===
// end::enum_constants[]

