[#_enum_ConnectionError]
=== ConnectionError

`Class(name=ConnectionError, anchor=enum_ConnectionError, enumConstants=[EnumConstant(name=RPCMethodUnavailable, type=null, value=null), EnumConstant(name=ServerConnectionFailed, type=null, value=null), EnumConstant(name=ServerConnectionFailedWithError, type=null, value=null), EnumConstant(name=ServerConnectionFailedStatusError, type=null, value=null), EnumConstant(name=ServerConnectionIsClosed, type=null, value=null), EnumConstant(name=TransactionIsClosed, type=null, value=null), EnumConstant(name=TransactionIsClosedWithErrors, type=null, value=null), EnumConstant(name=DatabaseNotFound, type=null, value=null), EnumConstant(name=MissingResponseField, type=null, value=null), EnumConstant(name=UnknownRequestId, type=null, value=null), EnumConstant(name=UnexpectedResponse, type=null, value=null), EnumConstant(name=InvalidResponseField, type=null, value=null), EnumConstant(name=QueryStreamNoResponse, type=null, value=null), EnumConstant(name=UnexpectedQueryType, type=null, value=null), EnumConstant(name=ClusterReplicaNotPrimary, type=null, value=null), EnumConstant(name=ClusterAllNodesFailed, type=null, value=null), EnumConstant(name=TokenCredentialInvalid, type=null, value=null), EnumConstant(name=EncryptionSettingsMismatch, type=null, value=null), EnumConstant(name=SSLCertificateNotValidated, type=null, value=null), EnumConstant(name=BrokenPipe, type=null, value=null), EnumConstant(name=ConnectionFailed, type=null, value=null), EnumConstant(name=MissingPort, type=null, value=null), EnumConstant(name=AddressTranslationMismatch, type=null, value=null), EnumConstant(name=ValueTimeZoneNameNotRecognised, type=null, value=null), EnumConstant(name=ValueTimeZoneOffsetNotRecognised, type=null, value=null), EnumConstant(name=ValueStructNotImplemented, type=null, value=null), EnumConstant(name=ListsNotImplemented, type=null, value=null), EnumConstant(name=UnexpectedKind, type=null, value=null), EnumConstant(name=UnexpectedConnectionClose, type=null, value=null), EnumConstant(name=DatabaseImportChannelIsClosed, type=null, value=null), EnumConstant(name=DatabaseImportStreamUnexpectedResponse, type=null, value=null), EnumConstant(name=DatabaseExportChannelIsClosed, type=null, value=null), EnumConstant(name=DatabaseExportStreamNoResponse, type=null, value=null), EnumConstant(name=AbsentTlsConfigForTlsConnection, type=null, value=null), EnumConstant(name=TlsConnectionWithoutHttps, type=null, value=null), EnumConstant(name=NonTlsConnectionWithHttps, type=null, value=null), EnumConstant(name=AnalyzeNoResponse, type=null, value=null)], description=[], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=async).nameDescriptor(language)`

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `AbsentTlsConfigForTlsConnection`
a| `AddressTranslationMismatch`
a| `AnalyzeNoResponse`
a| `BrokenPipe`
a| `ClusterAllNodesFailed`
a| `ClusterReplicaNotPrimary`
a| `ConnectionFailed`
a| `DatabaseExportChannelIsClosed`
a| `DatabaseExportStreamNoResponse`
a| `DatabaseImportChannelIsClosed`
a| `DatabaseImportStreamUnexpectedResponse`
a| `DatabaseNotFound`
a| `EncryptionSettingsMismatch`
a| `InvalidResponseField`
a| `ListsNotImplemented`
a| `MissingPort`
a| `MissingResponseField`
a| `NonTlsConnectionWithHttps`
a| `QueryStreamNoResponse`
a| `RPCMethodUnavailable`
a| `SSLCertificateNotValidated`
a| `ServerConnectionFailed`
a| `ServerConnectionFailedStatusError`
a| `ServerConnectionFailedWithError`
a| `ServerConnectionIsClosed`
a| `TlsConnectionWithoutHttps`
a| `TokenCredentialInvalid`
a| `TransactionIsClosed`
a| `TransactionIsClosedWithErrors`
a| `UnexpectedConnectionClose`
a| `UnexpectedKind`
a| `UnexpectedQueryType`
a| `UnexpectedResponse`
a| `UnknownRequestId`
a| `ValueStructNotImplemented`
a| `ValueTimeZoneNameNotRecognised`
a| `ValueTimeZoneOffsetNotRecognised`
|===
// end::enum_constants[]

