[#_enum_ConnectionError]
=== ConnectionError

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `AddressTranslationMismatch`
a| `BrokenPipe`
a| `ClusterAllNodesFailed`
a| `ClusterEncryptionSettingsMismatch`
a| `ClusterReplicaNotPrimary`
a| `ClusterSSLCertificateNotValidated`
a| `ClusterTokenCredentialInvalid`
a| `ConnectionFailed`
a| `DatabaseNotFound`
a| `InvalidResponseField`
a| `ListsNotImplemented`
a| `MissingPort`
a| `MissingResponseField`
a| `QueryStreamNoResponse`
a| `RPCMethodUnavailable`
a| `ServerConnectionFailed`
a| `ServerConnectionFailedStatusError`
a| `ServerConnectionFailedWithError`
a| `ServerConnectionIsClosed`
a| `TransactionIsClosed`
a| `TransactionIsClosedWithErrors`
a| `UnexpectedConnectionClose`
a| `UnexpectedKind`
a| `UnexpectedQueryType`
a| `UnexpectedResponse`
a| `UnknownRequestId`
a| `UserManagementClusterOnly`
a| `ValueStructNotImplemented`
a| `ValueTimeZoneNameNotRecognised`
a| `ValueTimeZoneOffsetNotRecognised`
|===
// end::enum_constants[]

