[#_struct_Credentials]
=== Credentials

`Class(name=Credentials, anchor=struct_Credentials, enumConstants=[], description=[User credentials for connecting to TypeDB], examples=[], fields=[], methods=[Method(name=new, signature=pub fn new(username: &str, password: &str) -> Self, anchor=struct_Credentials_new_username_str_password_str, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The name of the user to connect as, type=&str), Variable(name=password, anchor=null, defaultValue=null, description= — The password for the user, type=&str)], description=[Creates a credentials with username and password.], examples=[Credentials::new(username, password);], mode=async, returnDescription=null, returnType=Self), Method(name=username, signature=pub fn username(&self) -> &str, anchor=struct_Credentials_username_, args=[], description=[Retrieves the username used.], examples=[], mode=async, returnDescription=null, returnType=&str), Method(name=password, signature=pub fn password(&self) -> &str, anchor=struct_Credentials_password_, args=[], description=[Retrieves the password used.], examples=[], mode=async, returnDescription=null, returnType=&str)], packagePath=null, superClasses=[Clone, Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`

User credentials for connecting to TypeDB

// tag::methods[]
[#_struct_Credentials_new_username_str_password_str]
==== new

[source,rust]
----
pub fn new(username: &str, password: &str) -> Self
----

Creates a credentials with username and password.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to connect as a| `&str`
a| `password` a|  — The password for the user a| `&str`
|===

[caption=""]
.Returns
[source,rust]
----
Self
----

[caption=""]
.Code examples
[source,rust]
----
Credentials::new(username, password);
----

[#_struct_Credentials_password_]
==== password

[source,rust]
----
pub fn password(&self) -> &str
----

Retrieves the password used.

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_Credentials_username_]
==== username

[source,rust]
----
pub fn username(&self) -> &str
----

Retrieves the username used.

[caption=""]
.Returns
[source,rust]
----
&str
----

// end::methods[]

