[#_struct_DatabaseManager]
=== DatabaseManager

`Class(name=DatabaseManager, anchor=struct_DatabaseManager, enumConstants=[], description=[Provides access to all database management methods.], examples=[], fields=[], methods=[Method(name=all, signature=pub async fn all(&self) -> Result<Vec<Arc<Database>>>, anchor=struct_DatabaseManager_all_, args=[], description=[Retrieves all databases present on the TypeDB server], examples=[driver.databases().all().await;], mode=async, returnDescription=null, returnType=Result<Vec<Arc<Database>>>), Method(name=get, signature=pub async fn get(&self, name: impl AsRef<str>) -> Result<Arc<Database>>, anchor=struct_DatabaseManager_get_name_impl_AsRef_str_, args=[Variable(name=name, anchor=null, defaultValue=null, description= — The name of the database to retrieve, type=impl AsRef<str>)], description=[Retrieve the database with the given name.], examples=[driver.databases().get(name).await;], mode=async, returnDescription=null, returnType=Result<Arc<Database>>), Method(name=contains, signature=pub async fn contains(&self, name: impl Into<String>) -> Result<bool>, anchor=struct_DatabaseManager_contains_name_impl_Into_String_, args=[Variable(name=name, anchor=null, defaultValue=null, description= — The database name to be checked, type=impl Into<String>)], description=[Checks if a database with the given name exists], examples=[driver.databases().contains(name).await;], mode=async, returnDescription=null, returnType=Result<bool>), Method(name=create, signature=pub async fn create(&self, name: impl Into<String>) -> Result, anchor=struct_DatabaseManager_create_name_impl_Into_String_, args=[Variable(name=name, anchor=null, defaultValue=null, description= — The name of the database to be created, type=impl Into<String>)], description=[Create a database with the given name], examples=[driver.databases().create(name).await;], mode=async, returnDescription=null, returnType=Result), Method(name=import_from_file, signature=pub async fn import_from_file(
    &self,
    name: impl Into<String>,
    schema: impl Into<String>,
    data_file_path: impl AsRef<Path>,
) -> Result, anchor=struct_DatabaseManager_import_from_file_name_impl_Into_String_schema_impl_Into_String_data_file_path_impl_AsRef_Path_, args=[Variable(name=name, anchor=null, defaultValue=null, description= — The name of the database to be created, type=impl Into<String>), Variable(name=schema, anchor=null, defaultValue=null, description= — The schema definition query string for the database, type=impl Into<String>), Variable(name=data_file_path, anchor=null, defaultValue=null, description= — The exported database file to import the data from, type=impl AsRef<Path>)], description=[Create a database with the given name based on previously exported another database’s data loaded from a file. This is a blocking operation and may take a significant amount of time depending on the database size.], examples=[driver.databases().import_from_file(name, schema, data_path).await;], mode=async, returnDescription=null, returnType=Result)], packagePath=null, superClasses=[Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Debug`

Provides access to all database management methods.

// tag::methods[]
[#_struct_DatabaseManager_all_]
==== all

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn all(&self) -> Result<Vec<Arc<Database>>>
----

--

sync::
+
--
[source,rust]
----
pub fn all(&self) -> Result<Vec<Arc<Database>>>
----

--
====

Retrieves all databases present on the TypeDB server

[caption=""]
.Returns
[source,rust]
----
Result<Vec<Arc<Database>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().all().await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().all();
----

--
====

[#_struct_DatabaseManager_contains_name_impl_Into_String_]
==== contains

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn contains(&self, name: impl Into<String>) -> Result<bool>
----

--

sync::
+
--
[source,rust]
----
pub fn contains(&self, name: impl Into<String>) -> Result<bool>
----

--
====

Checks if a database with the given name exists

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  — The database name to be checked a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().contains(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().contains(name);
----

--
====

[#_struct_DatabaseManager_create_name_impl_Into_String_]
==== create

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn create(&self, name: impl Into<String>) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn create(&self, name: impl Into<String>) -> Result
----

--
====

Create a database with the given name

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  — The name of the database to be created a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().create(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().create(name);
----

--
====

[#_struct_DatabaseManager_get_name_impl_AsRef_str_]
==== get

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn get(&self, name: impl AsRef<str>) -> Result<Arc<Database>>
----

--

sync::
+
--
[source,rust]
----
pub fn get(&self, name: impl AsRef<str>) -> Result<Arc<Database>>
----

--
====

Retrieve the database with the given name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  — The name of the database to retrieve a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Arc<Database>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().get(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().get(name);
----

--
====

[#_struct_DatabaseManager_import_from_file_name_impl_Into_String_schema_impl_Into_String_data_file_path_impl_AsRef_Path_]
==== import_from_file

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn import_from_file(
    &self,
    name: impl Into<String>,
    schema: impl Into<String>,
    data_file_path: impl AsRef<Path>,
) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn import_from_file(
    &self,
    name: impl Into<String>,
    schema: impl Into<String>,
    data_file_path: impl AsRef<Path>,
) -> Result
----

--
====

Create a database with the given name based on previously exported another database’s data loaded from a file. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  — The name of the database to be created a| `impl Into<String>`
a| `schema` a|  — The schema definition query string for the database a| `impl Into<String>`
a| `data_file_path` a|  — The exported database file to import the data from a| `impl AsRef<Path>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().import_from_file(name, schema, data_path).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().import_from_file(name, schema, data_path);
----

--
====

// end::methods[]

