[#_struct_Database]
=== Database

`Class(name=Database, anchor=struct_Database, enumConstants=[], description=[A TypeDB database], examples=[], fields=[], methods=[Method(name=name, signature=pub fn name(&self) -> &str, anchor=struct_Database_name_, args=[], description=[Retrieves the database name as a string.], examples=[], mode=async, returnDescription=null, returnType=&str), Method(name=replicas_info, signature=pub fn replicas_info(&self) -> Vec<ReplicaInfo>, anchor=struct_Database_replicas_info_, args=[], description=[Returns the ``Replica`` instances for this database. _Only works in TypeDB Cloud / Enterprise_], examples=[database.replicas_info()], mode=async, returnDescription=null, returnType=Vec<ReplicaInfo>), Method(name=primary_replica_info, signature=pub fn primary_replica_info(&self) -> Option<ReplicaInfo>, anchor=struct_Database_primary_replica_info_, args=[], description=[Returns the primary replica for this database. _Only works in TypeDB Cloud / Enterprise_], examples=[database.primary_replica_info()], mode=async, returnDescription=null, returnType=Option<ReplicaInfo>), Method(name=preferred_replica_info, signature=pub fn preferred_replica_info(&self) -> Option<ReplicaInfo>, anchor=struct_Database_preferred_replica_info_, args=[], description=[Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud / Enterprise_], examples=[database.preferred_replica_info();], mode=async, returnDescription=null, returnType=Option<ReplicaInfo>), Method(name=delete, signature=pub async fn delete(self: Arc<Self>) -> Result, anchor=struct_Database_delete_, args=[], description=[Deletes this database.], examples=[database.delete().await;], mode=async, returnDescription=null, returnType=Result), Method(name=schema, signature=pub async fn schema(&self) -> Result<String>, anchor=struct_Database_schema_, args=[], description=[Returns a full schema text as a valid TypeQL define query string.], examples=[database.schema().await;], mode=async, returnDescription=null, returnType=Result<String>), Method(name=type_schema, signature=pub async fn type_schema(&self) -> Result<String>, anchor=struct_Database_type_schema_, args=[], description=[Returns the types in the schema as a valid TypeQL define query string.], examples=[database.type_schema().await;], mode=async, returnDescription=null, returnType=Result<String>), Method(name=export_to_file, signature=pub async fn export_to_file(
    &self,
    schema_file_path: impl AsRef<Path>,
    data_file_path: impl AsRef<Path>,
) -> Result, anchor=struct_Database_export_to_file_schema_file_path_impl_AsRef_Path_data_file_path_impl_AsRef_Path_, args=[Variable(name=schema_file_path, anchor=null, defaultValue=null, description= — The path to the schema definition file to be created, type=impl AsRef<Path>), Variable(name=data_file_path, anchor=null, defaultValue=null, description= — The path to the data file to be created, type=impl AsRef<Path>)], description=[Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size.], examples=[database.export_to_file(schema_path, data_path).await;], mode=async, returnDescription=null, returnType=Result)], packagePath=null, superClasses=[Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Debug`

A TypeDB database

// tag::methods[]
[#_struct_Database_delete_]
==== delete

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn delete(self: Arc<Self>) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn delete(self: Arc<Self>) -> Result
----

--
====

Deletes this database.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
database.delete().await;
----

--

sync::
+
--
[source,rust]
----
database.delete();
----

--
====

[#_struct_Database_export_to_file_schema_file_path_impl_AsRef_Path_data_file_path_impl_AsRef_Path_]
==== export_to_file

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn export_to_file(
    &self,
    schema_file_path: impl AsRef<Path>,
    data_file_path: impl AsRef<Path>,
) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn export_to_file(
    &self,
    schema_file_path: impl AsRef<Path>,
    data_file_path: impl AsRef<Path>,
) -> Result
----

--
====

Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schema_file_path` a|  — The path to the schema definition file to be created a| `impl AsRef<Path>`
a| `data_file_path` a|  — The path to the data file to be created a| `impl AsRef<Path>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
database.export_to_file(schema_path, data_path).await;
----

--

sync::
+
--
[source,rust]
----
database.export_to_file(schema_path, data_path);
----

--
====

[#_struct_Database_name_]
==== name

[source,rust]
----
pub fn name(&self) -> &str
----

Retrieves the database name as a string.

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_Database_preferred_replica_info_]
==== preferred_replica_info

[source,rust]
----
pub fn preferred_replica_info(&self) -> Option<ReplicaInfo>
----

Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud / Enterprise_

[caption=""]
.Returns
[source,rust]
----
Option<ReplicaInfo>
----

[caption=""]
.Code examples
[source,rust]
----
database.preferred_replica_info();
----

[#_struct_Database_primary_replica_info_]
==== primary_replica_info

[source,rust]
----
pub fn primary_replica_info(&self) -> Option<ReplicaInfo>
----

Returns the primary replica for this database. _Only works in TypeDB Cloud / Enterprise_

[caption=""]
.Returns
[source,rust]
----
Option<ReplicaInfo>
----

[caption=""]
.Code examples
[source,rust]
----
database.primary_replica_info()
----

[#_struct_Database_replicas_info_]
==== replicas_info

[source,rust]
----
pub fn replicas_info(&self) -> Vec<ReplicaInfo>
----

Returns the ``Replica`` instances for this database. _Only works in TypeDB Cloud / Enterprise_

[caption=""]
.Returns
[source,rust]
----
Vec<ReplicaInfo>
----

[caption=""]
.Code examples
[source,rust]
----
database.replicas_info()
----

[#_struct_Database_schema_]
==== schema

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn schema(&self) -> Result<String>
----

--

sync::
+
--
[source,rust]
----
pub fn schema(&self) -> Result<String>
----

--
====

Returns a full schema text as a valid TypeQL define query string.

[caption=""]
.Returns
[source,rust]
----
Result<String>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
database.schema().await;
----

--

sync::
+
--
[source,rust]
----
database.schema();
----

--
====

[#_struct_Database_type_schema_]
==== type_schema

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn type_schema(&self) -> Result<String>
----

--

sync::
+
--
[source,rust]
----
pub fn type_schema(&self) -> Result<String>
----

--
====

Returns the types in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
[source,rust]
----
Result<String>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
database.type_schema().await;
----

--

sync::
+
--
[source,rust]
----
database.type_schema();
----

--
====

// end::methods[]

