[#_struct_DriverOptions]
[.doc-api-reference-driver]
=== DriverOptions

`struct`

*Implements traits:*

* `Clone`
* `Debug`
* `Default`

TypeDB driver connection options. ``DriverOptions`` object can be used to override the default driver behavior while connecting to TypeDB.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `primary_failover_retries` a| `usize` a| Limits the number of attempts to redirect a request to another primary server in case of a failure due to the change of server replication roles. Defaults to 1.
a| `request_timeout` a| `Duration` a| Specifies the maximum time to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). Defaults to 2 hours.
a| `server_discovery_attempts` a| `Option<usize>` a| Limits the number of driver attempts to discover a single working server to perform an operation in case of a server unavailability. Every server is tested once, which means that at most:

 {limit} operations are performed if the limit &lt;= the number of servers.
 {number of servers} operations are performed if the limit &gt; the number of servers.
 {number of servers} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary server is unknown. Defaults to None.

a| `tls_config` a| `DriverTlsConfig` a| Specifies the TLS configuration of the connection to TypeDB. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext. Defaults to an enabled TLS configuration based on the system’s native trust roots.
|===
// end::properties[]

// tag::methods[]
[#_struct_DriverOptions_new_]
==== new

[source,rust]
----
pub fn new(tls_config: DriverTlsConfig) -> Self
----

Creates new ``DriverOptions`` to configure connections to TypeDB using custom TLS settings. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_primary_failover_retries_]
==== primary_failover_retries

[source,rust]
----
pub fn primary_failover_retries(self, primary_failover_retries: usize) -> Self
----

Limits the number of attempts to redirect a request to another primary server in case of a failure due to the change of server replication roles. Defaults to 1.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_request_timeout_]
==== request_timeout

[source,rust]
----
pub fn request_timeout(self, request_timeout: Duration) -> Self
----

Specifies the maximum time to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). Defaults to 2 hours.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_server_discovery_attempts_]
==== server_discovery_attempts

[source,rust]
----
pub fn server_discovery_attempts(
    self,
    server_discovery_attempts: Option<usize>,
) -> Self
----

Limits the number of driver attempts to discover a single working server to perform an operation in case of a server unavailability. Every server is tested once, which means that at most:

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_tls_config_]
==== tls_config

[source,rust]
----
pub fn tls_config(self, tls_config: DriverTlsConfig) -> Self
----

Override the existing TLS configuration. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.

[caption=""]
.Returns
[source,rust]
----
Self
----

// end::methods[]

