[#_struct_DriverOptions]
=== DriverOptions

*Implements traits:*

* `Clone`
* `Debug`
* `Default`

TypeDB driver connection options. ``DriverOptions`` object can be used to override the default driver behavior while connecting to TypeDB.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `discovery_failover_retries` a| `Option<usize>` a| Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most:

 {limit} operations are performed if the limit &lt;= the number of replicas.
 {number of replicas} operations are performed if the limit &gt; the number of replicas.
 {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown. Defaults to None.

a| `is_tls_enabled` a| `bool` a| Specifies whether the connection to TypeDB must be done over TLS. Defaults to false.
a| `redirect_failover_retries` a| `usize` a| Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles. Defaults to 1.
a| `tls_config` a| `Option<ClientTlsConfig>` a| If set, specifies the TLS config to use for server certificates authentication. Defaults to None.
a| `use_replication` a| `bool` a| Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address. Defaults to true.
|===
// end::properties[]

// tag::methods[]
[#_struct_DriverOptions_discovery_failover_retries_]
==== discovery_failover_retries

[source,rust]
----
pub fn discovery_failover_retries(
    self,
    discovery_failover_retries: Option<usize>,
) -> Self
----

Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most:

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_is_tls_enabled_]
==== is_tls_enabled

[source,rust]
----
pub fn is_tls_enabled(self, is_tls_enabled: bool) -> Self
----

Specifies whether the connection to TypeDB must be done over TLS.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_redirect_failover_retries_]
==== redirect_failover_retries

[source,rust]
----
pub fn redirect_failover_retries(self, redirect_failover_retries: usize) -> Self
----

Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles. Defaults to 1.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_DriverOptions_tls_root_ca_]
==== tls_root_ca

[source,rust]
----
pub fn tls_root_ca(self, tls_root_ca: Option<&Path>) -> Result<Self>
----

If set, specifies the path to the CA certificate to use for server certificates authentication.

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[#_struct_DriverOptions_use_replication_]
==== use_replication

[source,rust]
----
pub fn use_replication(self, use_replication: bool) -> Self
----

Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to the provided address. If set to false, restricts the driver to only a single address.

[caption=""]
.Returns
[source,rust]
----
Self
----

// end::methods[]

