[#_struct_TypeDBDriver]
[.doc-api-reference-driver]
=== TypeDBDriver

`struct`

*Implements traits:*

* `Debug`

A connection to a TypeDB server which serves as the starting point for all interaction.

// tag::methods[]
[#_struct_TypeDBDriver_configured_addresses_]
==== configured_addresses

[source,rust]
----
pub fn configured_addresses(&self) -> &Addresses
----

The ``Addresses`` this connection is configured to.

[caption=""]
.Returns
[source,rust]
----
&Addresses
----

[caption=""]
.Code examples
[source,rust]
----
driver.configured_addresses()
----

[#_struct_TypeDBDriver_databases_]
==== databases

[source,rust]
----
pub fn databases(&self) -> &DatabaseManager
----

The ``DatabaseManager`` for this connection, providing access to database management methods.

[caption=""]
.Returns
[source,rust]
----
&DatabaseManager
----

[caption=""]
.Code examples
[source,rust]
----
driver.databases()
----

[#_struct_TypeDBDriver_deregister_server_replica_id_u64]
==== deregister_server

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn deregister_server(&self, replica_id: u64) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn deregister_server(&self, replica_id: u64) -> Result
----

--
====

Deregisters a server from the cluster the driver is currently connected to. This server will no longer play a raft role in this cluster.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replica_id` a|  〔 The numeric identifier of the deregistered server a| `u64`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.deregister_server(2).await
----

--

sync::
+
--
[source,rust]
----
driver.deregister_server(2)
----

--
====

[#_struct_TypeDBDriver_force_close_]
==== force_close

[source,rust]
----
pub fn force_close(&self) -> Result
----

Closes this connection if it is open.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.force_close()
----

[#_struct_TypeDBDriver_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Checks it this connection is opened.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
driver.is_open()
----

[#_struct_TypeDBDriver_new_addresses_Addresses_credentials_Credentials_driver_options_DriverOptions]
==== new

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a|  〔 The address(es) of the TypeDB Server(s), provided in a unified format a| `Addresses`
a| `credentials` a|  〔 The Credentials to connect with a| `Credentials`
a| `driver_options` a|  〔 The DriverOptions to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), Credentials::new("username", "password"), DriverOptions::new(true, None)).await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), Credentials::new("username", "password"), DriverOptions::new(true, None))
----

--
====

[#_struct_TypeDBDriver_new_with_description_addresses_Addresses_credentials_Credentials_driver_options_DriverOptions_driver_lang_impl_AsRef_str_]
==== new_with_description

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_with_description(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_with_description(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection with a description. This method is generally used by TypeDB drivers built on top of the Rust driver. In other cases, use <<#_struct_TypeDBDriver_method_new,`Self::new`>> instead.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a|  〔 The address(es) of the TypeDB Server(s), provided in a unified format a| `Addresses`
a| `credentials` a|  〔 The Credentials to connect with a| `Credentials`
a| `driver_options` a|  〔 The DriverOptions to connect with a| `DriverOptions`
a| `driver_lang` a|  〔 The language of the driver connecting to the server a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new_with_description(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), Credentials::new("username", "password"), DriverOptions::new(true, None), "rust").await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new_with_description(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), Credentials::new("username", "password"), DriverOptions::new(true, None), "rust")
----

--
====

[#_struct_TypeDBDriver_options_]
==== options

[source,rust]
----
pub fn options(&self) -> &DriverOptions
----

Updates address translation of the driver. This lets you actualize new translation information without recreating the driver from scratch. Useful after registering new replicas requiring address translation. This operation will update existing connections using the provided addresses.

The ``DriverOptions`` for this connection.

[caption=""]
.Returns
[source,rust]
----
&DriverOptions
----

[caption=""]
.Code examples
[source,rust]
----
driver.options()
----

[#_struct_TypeDBDriver_primary_server_]
==== primary_server

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn primary_server(&self) -> Result<Option<AvailableServer>>
----

--

sync::
+
--
[source,rust]
----
pub fn primary_server(&self) -> Result<Option<AvailableServer>>
----

--
====

Retrieves the primary server, if exists, using default automatic server routing.

See <<#_struct_TypeDBDriver_method_primary_server_with_routing,`Self::primary_server_with_routing`>> for more details and options.

[caption=""]
.Returns
[source,rust]
----
Result<Option<AvailableServer>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.primary_server().await;
----

--

sync::
+
--
[source,rust]
----
driver.primary_server();
----

--
====

[#_struct_TypeDBDriver_primary_server_with_routing_server_routing_ServerRouting]
==== primary_server_with_routing

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn primary_server_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<Option<AvailableServer>>
----

--

sync::
+
--
[source,rust]
----
pub fn primary_server_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<Option<AvailableServer>>
----

--
====

Retrieves the primary server, if exists.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `server_routing` a|  〔 The server routing directive to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<AvailableServer>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.primary_server_with_routing(ServerRouting::Auto).await;
----

--

sync::
+
--
[source,rust]
----
driver.primary_server_with_routing(ServerRouting::Auto);
----

--
====

[#_struct_TypeDBDriver_register_server_replica_id_u64_address_String]
==== register_server

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn register_server(&self, replica_id: u64, address: String) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn register_server(&self, replica_id: u64, address: String) -> Result
----

--
====

Registers a new server in the cluster the driver is currently connected to. The registered server will become available eventually, depending on the behavior of the whole cluster. To register a server, its clustering address should be passed, not the connection address.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replica_id` a|  〔 The numeric identifier of the new server a| `u64`
a| `address` a|  〔 The clustering address of the TypeDB server as a string a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.register_server(2, "127.0.0.1:2729").await
----

--

sync::
+
--
[source,rust]
----
driver.register_server(2, "127.0.0.1:2729")
----

--
====

[#_struct_TypeDBDriver_server_version_]
==== server_version

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn server_version(&self) -> Result<ServerVersion>
----

--

sync::
+
--
[source,rust]
----
pub fn server_version(&self) -> Result<ServerVersion>
----

--
====

Retrieves the server〙s version, using default automatic server routing.

See <<#_struct_TypeDBDriver_method_server_version_with_routing,`Self::server_version_with_routing`>> for more details and options.

[caption=""]
.Returns
[source,rust]
----
Result<ServerVersion>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.server_version().await
----

--

sync::
+
--
[source,rust]
----
driver.server_version()
----

--
====

[#_struct_TypeDBDriver_server_version_with_routing_server_routing_ServerRouting]
==== server_version_with_routing

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn server_version_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<ServerVersion>
----

--

sync::
+
--
[source,rust]
----
pub fn server_version_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<ServerVersion>
----

--
====

Retrieves the server〙s version.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `server_routing` a|  〔 The server routing directive to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
[source,rust]
----
Result<ServerVersion>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.server_version_with_routing(ServerRouting::Auto).await;
----

--

sync::
+
--
[source,rust]
----
driver.server_version_with_routing(ServerRouting::Auto);
----

--
====

[#_struct_TypeDBDriver_servers_]
==== servers

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn servers(&self) -> Result<HashSet<Server>>
----

--

sync::
+
--
[source,rust]
----
pub fn servers(&self) -> Result<HashSet<Server>>
----

--
====

Retrieves the servers, using default automatic server routing.

See <<#_struct_TypeDBDriver_method_servers_with_routing,`Self::servers_with_routing`>> for more details and options.

[caption=""]
.Returns
[source,rust]
----
Result<HashSet<Server>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.servers().await;
----

--

sync::
+
--
[source,rust]
----
driver.servers();
----

--
====

[#_struct_TypeDBDriver_servers_with_routing_server_routing_ServerRouting]
==== servers_with_routing

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn servers_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<HashSet<Server>>
----

--

sync::
+
--
[source,rust]
----
pub fn servers_with_routing(
    &self,
    server_routing: ServerRouting,
) -> Result<HashSet<Server>>
----

--
====

Retrieves the servers.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `server_routing` a|  〔 The server routing directive to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
[source,rust]
----
Result<HashSet<Server>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.servers_with_routing(ServerRouting::Auto).await;
----

--

sync::
+
--
[source,rust]
----
driver.servers_with_routing(ServerRouting::Auto);
----

--
====

[#_struct_TypeDBDriver_transaction_]
==== transaction

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
) -> Result<Transaction>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
) -> Result<Transaction>
----

--
====

Opens a transaction with default options.

See <<#_struct_TypeDBDriver_method_transaction_with_options,`TypeDBDriver::transaction_with_options`>> for more details.

[caption=""]
.Returns
[source,rust]
----
Result<Transaction>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.transaction(database_name, TransactionType::Read).await;
----

--

sync::
+
--
[source,rust]
----
driver.transaction(database_name, TransactionType::Read);
----

--
====

[#_struct_TypeDBDriver_transaction_with_options_database_name_impl_AsRef_str_transaction_type_TransactionType_options_TransactionOptions]
==== transaction_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction_with_options(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
    options: TransactionOptions,
) -> Result<Transaction>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction_with_options(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
    options: TransactionOptions,
) -> Result<Transaction>
----

--
====

Opens a new transaction with custom transaction options.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database_name` a|  〔 The name of the database to connect to a| `impl AsRef<str>`
a| `transaction_type` a|  〔 The TransactionType to open the transaction with a| `TransactionType`
a| `options` a|  〔 The TransactionOptions to open the transaction with a| `TransactionOptions`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Transaction>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.transaction_with_options(database_name, transaction_type, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.transaction_with_options(database_name, transaction_type, options)
----

--
====

[#_struct_TypeDBDriver_users_]
==== users

[source,rust]
----
pub fn users(&self) -> &UserManager
----

The ``UserManager`` for this connection, providing access to user management methods.

[caption=""]
.Returns
[source,rust]
----
&UserManager
----

[caption=""]
.Code examples
[source,rust]
----
driver.databases()
----

// end::methods[]

