[#_struct_TypeDBDriver]
=== TypeDBDriver

*Implements traits:*

* `Debug`

A connection to a TypeDB server which serves as the starting point for all interaction.

// tag::methods[]
[#_struct_TypeDBDriver_databases_]
==== databases

[source,rust]
----
pub fn databases(&self) -> &DatabaseManager
----

The ``DatabaseManager`` for this connection, providing access to database management methods.

[caption=""]
.Returns
[source,rust]
----
&DatabaseManager
----

[caption=""]
.Code examples
[source,rust]
----
driver.databases()
----

[#_struct_TypeDBDriver_deregister_replica_replica_id_u64]
==== deregister_replica

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn deregister_replica(&self, replica_id: u64) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn deregister_replica(&self, replica_id: u64) -> Result
----

--
====

Deregisters a replica from the cluster the driver is currently connected to. This replica will no longer play a raft role in this cluster.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replica_id` a|  — The numeric identifier of the deregistered replica a| `u64`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.deregister_replica(2).await
----

--

sync::
+
--
[source,rust]
----
driver.deregister_replica(2)
----

--
====

[#_struct_TypeDBDriver_force_close_]
==== force_close

[source,rust]
----
pub fn force_close(&self) -> Result
----

Closes this connection if it is open.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.force_close()
----

[#_struct_TypeDBDriver_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Checks it this connection is opened.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
driver.is_open()
----

[#_struct_TypeDBDriver_new_addresses_Addresses_credentials_Credentials_driver_options_DriverOptions]
==== new

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a|  — The address(es) of the TypeDB Server(s), provided in a unified format a| `Addresses`
a| `credentials` a|  — The Credentials to connect with a| `Credentials`
a| `driver_options` a|  — The DriverOptions to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new(Addresses::try_from_address_str("127.0.0.1:1729").unwrap()).await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new(Addresses::try_from_address_str("127.0.0.1:1729").unwrap())
----

--
====

[#_struct_TypeDBDriver_new_with_description_addresses_Addresses_credentials_Credentials_driver_options_DriverOptions_driver_lang_impl_AsRef_str_]
==== new_with_description

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_with_description(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_with_description(
    addresses: Addresses,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection with a description. This method is generally used by TypeDB drivers built on top of the Rust driver. In other cases, use <<#_struct_TypeDBDriver_method_new,`Self::new`>> instead.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a|  — The address(es) of the TypeDB Server(s), provided in a unified format a| `Addresses`
a| `credentials` a|  — The Credentials to connect with a| `Credentials`
a| `driver_options` a|  — The DriverOptions to connect with a| `DriverOptions`
a| `driver_lang` a|  — The language of the driver connecting to the server a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new_with_description(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), "rust").await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new_with_description(Addresses::try_from_address_str("127.0.0.1:1729").unwrap(), "rust")
----

--
====

[#_struct_TypeDBDriver_primary_replica_]
==== primary_replica

[source,rust]
----
pub fn primary_replica(&self) -> Option<ServerReplica>
----

Retrieves the server’s primary replica, if exists.

[caption=""]
.Returns
[source,rust]
----
Option<ServerReplica>
----

[caption=""]
.Code examples
[source,rust]
----
driver.primary_replica()
----

[#_struct_TypeDBDriver_register_replica_replica_id_u64_address_String]
==== register_replica

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn register_replica(&self, replica_id: u64, address: String) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn register_replica(&self, replica_id: u64, address: String) -> Result
----

--
====

Registers a new replica in the cluster the driver is currently connected to. The registered replica will become available eventually, depending on the behavior of the whole cluster.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replica_id` a|  — The numeric identifier of the new replica a| `u64`
a| `address` a|  — The address(es) of the TypeDB replica as a string a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.register_replica(2, "127.0.0.1:2729").await
----

--

sync::
+
--
[source,rust]
----
driver.register_replica(2, "127.0.0.1:2729")
----

--
====

[#_struct_TypeDBDriver_replicas_]
==== replicas

[source,rust]
----
pub fn replicas(&self) -> HashSet<ServerReplica>
----

Retrieves the server’s replicas.

[caption=""]
.Returns
[source,rust]
----
HashSet<ServerReplica>
----

[caption=""]
.Code examples
[source,rust]
----
driver.replicas()
----

[#_struct_TypeDBDriver_server_version_]
==== server_version

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn server_version(&self) -> Result<ServerVersion>
----

--

sync::
+
--
[source,rust]
----
pub fn server_version(&self) -> Result<ServerVersion>
----

--
====

Retrieves the server’s version, using default strong consistency.

See <<#_struct_TypeDBDriver_method_server_version_with_consistency,`Self::server_version_with_consistency`>> for more details and options.

[caption=""]
.Returns
[source,rust]
----
Result<ServerVersion>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.server_version().await
----

--

sync::
+
--
[source,rust]
----
driver.server_version()
----

--
====

[#_struct_TypeDBDriver_server_version_with_consistency_consistency_level_ConsistencyLevel]
==== server_version_with_consistency

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn server_version_with_consistency(
    &self,
    consistency_level: ConsistencyLevel,
) -> Result<ServerVersion>
----

--

sync::
+
--
[source,rust]
----
pub fn server_version_with_consistency(
    &self,
    consistency_level: ConsistencyLevel,
) -> Result<ServerVersion>
----

--
====

Retrieves the server’s version, using default strong consistency.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistency_level` a|  — The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
[source,rust]
----
Result<ServerVersion>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.server_version_with_consistency(ConsistencyLevel::Strong).await;
----

--

sync::
+
--
[source,rust]
----
driver.server_version_with_consistency(ConsistencyLevel::Strong);
----

--
====

[#_struct_TypeDBDriver_transaction_]
==== transaction

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
) -> Result<Transaction>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
) -> Result<Transaction>
----

--
====

Opens a transaction with default options.

See <<#_struct_TypeDBDriver_method_transaction_with_options,`TypeDBDriver::transaction_with_options`>> for more details.

[caption=""]
.Returns
[source,rust]
----
Result<Transaction>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.users().all_with_consistency(ConsistencyLevel::Strong).await;
----

--

sync::
+
--
[source,rust]
----
driver.users().all_with_consistency(ConsistencyLevel::Strong);
----

--
====

[#_struct_TypeDBDriver_transaction_with_options_options_TransactionOptions_database_name_impl_AsRef_str_transaction_type_TransactionType_options_TransactionOptions]
==== transaction_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction_with_options(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
    options: TransactionOptions,
) -> Result<Transaction>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction_with_options(
    &self,
    database_name: impl AsRef<str>,
    transaction_type: TransactionType,
    options: TransactionOptions,
) -> Result<Transaction>
----

--
====

Opens a new transaction with the following consistency level:

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `options` a| read transaction - strong consistency, can be overridden through ; a| `TransactionOptions`
a| `database_name` a|  — The name of the database to connect to a| `impl AsRef<str>`
a| `transaction_type` a|  — The TransactionType to open the transaction with a| `TransactionType`
a| `options` a|  — The TransactionOptions to open the transaction with a| `TransactionOptions`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Transaction>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.transaction_with_options(database_name, transaction_type, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.transaction_with_options(database_name, transaction_type, options)
----

--
====

[#_struct_TypeDBDriver_users_]
==== users

[source,rust]
----
pub fn users(&self) -> &UserManager
----

The ``UserManager`` for this connection, providing access to user management methods.

[caption=""]
.Returns
[source,rust]
----
&UserManager
----

[caption=""]
.Code examples
[source,rust]
----
driver.databases()
----

// end::methods[]

