[#_struct_TypeDBDriver]
=== TypeDBDriver

*Implements traits:*

* `Debug`

A connection to a TypeDB server which serves as the starting point for all interaction.

// tag::methods[]
[#_struct_TypeDBDriver_force_close_]
==== force_close

[source,rust]
----
pub fn force_close(&self) -> Result
----

Closes this connection if it is open.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
connection.force_close()
----

[#_struct_TypeDBDriver_is_cloud_]
==== is_cloud

[source,rust]
----
pub fn is_cloud(&self) -> bool
----

Check if the connection is to an Cloud server.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
connection.is_cloud()
----

[#_struct_TypeDBDriver_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Checks it this connection is opened.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
connection.is_open()
----

[#_struct_TypeDBDriver_new_cloud_init_addresses_T_credential_Credential]
==== new_cloud

[source,rust]
----
pub fn new_cloud<T: AsRef<str> + Sync>(
    init_addresses: &[T],
    credential: Credential,
) -> Result<Self>
----

Creates a new TypeDB Cloud connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `init_addresses` a| Addresses (host:port) on which TypeDB Cloud nodes are running a| `&[T]`
a| `credential` a| User credential and TLS encryption setting a| `Credential`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[source,rust]
----
Connection::new_cloud(
    &["localhost:11729", "localhost:21729", "localhost:31729"],
    Credential::with_tls(
        "admin",
        "password",
        Some(&PathBuf::from(
            std::env::var("ROOT_CA")
                .expect("ROOT_CA environment variable needs to be set for cloud tests to run"),
        )),
    )?,
)
----

[#_struct_TypeDBDriver_new_cloud_with_translation_address_translation_HashMap_T_credential_Credential]
==== new_cloud_with_translation

[source,rust]
----
pub fn new_cloud_with_translation<T, U>(
    address_translation: HashMap<T, U>,
    credential: Credential,
) -> Result<Self>where
    T: AsRef<str> + Sync,
    U: AsRef<str> + Sync,
----

Creates a new TypeDB Cloud connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address_translation` a| Translation map from addresses to be used by the driver for connection to addresses received from the TypeDB server(s) a| `HashMap<T`
a| `credential` a| User credential and TLS encryption setting a| `Credential`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>where
    T: AsRef<str> + Sync,
    U: AsRef<str> + Sync,
----

[caption=""]
.Code examples
[source,rust]
----
Connection::new_cloud_with_translation(
    [
        ("typedb-cloud.ext:11729", "localhost:11729"),
        ("typedb-cloud.ext:21729", "localhost:21729"),
        ("typedb-cloud.ext:31729", "localhost:31729"),
    ].into(),
    credential,
)
----

[#_struct_TypeDBDriver_new_core_address_impl_AsRef_str_]
==== new_core

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_core(address: impl AsRef<str>) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_core(address: impl AsRef<str>) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address (host:port) on which the TypeDB Server is running a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
Connection::new_core("127.0.0.1:1729").await
----

--

sync::
+
--
[source,rust]
----
Connection::new_core("127.0.0.1:1729")
----

--
====

[#_struct_TypeDBDriver_new_core_with_description_address_impl_AsRef_str_driver_lang_impl_AsRef_str_]
==== new_core_with_description

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_core_with_description(
    address: impl AsRef<str>,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_core_with_description(
    address: impl AsRef<str>,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection with a description.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address (host:port) on which the TypeDB Server is running a| `impl AsRef<str>`
a| `driver_lang` a| The language of the driver connecting to the server a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
Connection::new_core("127.0.0.1:1729", "rust").await
----

--

sync::
+
--
[source,rust]
----
Connection::new_core("127.0.0.1:1729", "rust")
----

--
====

// end::methods[]

