[#_struct_TypeDBDriver]
=== TypeDBDriver

*Implements traits:*

* `Debug`

A connection to a TypeDB server which serves as the starting point for all interaction.

// tag::methods[]
[#_struct_TypeDBDriver_force_close_]
==== force_close

[source,rust]
----
pub fn force_close(&self) -> Result
----

Closes this connection if it is open.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.force_close()
----

[#_struct_TypeDBDriver_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Checks it this connection is opened.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
driver.is_open()
----

[#_struct_TypeDBDriver_new_address_impl_AsRef_str_credentials_Credentials_driver_options_DriverOptions]
==== new

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new(
    address: impl AsRef<str>,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new(
    address: impl AsRef<str>,
    credentials: Credentials,
    driver_options: DriverOptions,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a|  — The address (host:port) on which the TypeDB Server is running a| `impl AsRef<str>`
a| `credentials` a|  — The Credentials to connect with a| `Credentials`
a| `driver_options` a|  — The DriverOptions to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new("127.0.0.1:1729").await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new("127.0.0.1:1729")
----

--
====

[#_struct_TypeDBDriver_new_with_description_address_impl_AsRef_str_credentials_Credentials_driver_options_DriverOptions_driver_lang_impl_AsRef_str_]
==== new_with_description

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_with_description(
    address: impl AsRef<str>,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_with_description(
    address: impl AsRef<str>,
    credentials: Credentials,
    driver_options: DriverOptions,
    driver_lang: impl AsRef<str>,
) -> Result<Self>
----

--
====

Creates a new TypeDB Server connection with a description. This method is generally used by TypeDB drivers built on top of the Rust driver. In other cases, use <<#_struct_TypeDBDriver_method_new,`Self::new`>> instead.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a|  — The address (host:port) on which the TypeDB Server is running a| `impl AsRef<str>`
a| `credentials` a|  — The Credentials to connect with a| `Credentials`
a| `driver_options` a|  — The DriverOptions to connect with a| `DriverOptions`
a| `driver_lang` a|  — The language of the driver connecting to the server a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
TypeDBDriver::new_with_description("127.0.0.1:1729", "rust").await
----

--

sync::
+
--
[source,rust]
----
TypeDBDriver::new_with_description("127.0.0.1:1729", "rust")
----

--
====

// end::methods[]

