[#_struct_UserManager]
=== UserManager

*Implements traits:*

* `Debug`

Provides access to all user management methods.

// tag::methods[]
[#_struct_UserManager_all_]
==== all

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn all(&self) -> Result<Vec<User>>
----

--

sync::
+
--
[source,rust]
----
pub fn all(&self) -> Result<Vec<User>>
----

--
====

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
[source,rust]
----
Result<Vec<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.all().await;
----

[#_struct_UserManager_contains_username_impl_Into_String_]
==== contains

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn contains(&self, username: impl Into<String>) -> Result<bool>
----

--

sync::
+
--
[source,rust]
----
pub fn contains(&self, username: impl Into<String>) -> Result<bool>
----

--
====

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The user name to be checked a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.contains(username).await;
----

[#_struct_UserManager_create_username_impl_Into_String_password_impl_Into_String_]
==== create

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>,
) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>,
) -> Result
----

--
====

Create a user with the given name &amp; password.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to be created a| `impl Into<String>`
a| `password` a|  — The password of the user to be created a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.create(username, password).await;
----

[#_struct_UserManager_delete_username_impl_Into_String_]
==== delete

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn delete(&self, username: impl Into<String>) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn delete(&self, username: impl Into<String>) -> Result
----

--
====

Deletes a user with the given name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to be deleted a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.delete(username).await;
----

[#_struct_UserManager_get_username_impl_Into_String_]
==== get

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn get(&self, username: impl Into<String>) -> Result<Option<User>>
----

--

sync::
+
--
[source,rust]
----
pub fn get(&self, username: impl Into<String>) -> Result<Option<User>>
----

--
====

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to retrieve a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.get(username).await;
----

// end::methods[]

