[#_struct_UserManager]
=== UserManager

`Class(name=UserManager, anchor=struct_UserManager, enumConstants=[], description=[Provides access to all user management methods.], examples=[], fields=[], methods=[Method(name=contains, signature=pub async fn contains(&self, username: impl Into<String>) -> Result<bool>, anchor=struct_UserManager_contains_username_impl_Into_String_, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The user name to be checked, type=impl Into<String>)], description=[Checks if a user with the given name exists.], examples=[driver.users.contains(username).await;], mode=async, returnDescription=null, returnType=Result<bool>), Method(name=get, signature=pub async fn get(&self, username: impl Into<String>) -> Result<Option<User>>, anchor=struct_UserManager_get_username_impl_Into_String_, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The name of the user to retrieve, type=impl Into<String>)], description=[Retrieve a user with the given name.], examples=[driver.users.get(username).await;], mode=async, returnDescription=null, returnType=Result<Option<User>>), Method(name=all, signature=pub async fn all(&self) -> Result<Vec<User>>, anchor=struct_UserManager_all_, args=[], description=[Retrieves all users which exist on the TypeDB server.], examples=[driver.users.all().await;], mode=async, returnDescription=null, returnType=Result<Vec<User>>), Method(name=create, signature=pub async fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>,
) -> Result, anchor=struct_UserManager_create_username_impl_Into_String_password_impl_Into_String_, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The name of the user to be created, type=impl Into<String>), Variable(name=password, anchor=null, defaultValue=null, description= — The password of the user to be created, type=impl Into<String>)], description=[Create a user with the given name &amp; password.], examples=[driver.users.create(username, password).await;], mode=async, returnDescription=null, returnType=Result)], packagePath=null, superClasses=[Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Debug`

Provides access to all user management methods.

// tag::methods[]
[#_struct_UserManager_all_]
==== all

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn all(&self) -> Result<Vec<User>>
----

--

sync::
+
--
[source,rust]
----
pub fn all(&self) -> Result<Vec<User>>
----

--
====

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
[source,rust]
----
Result<Vec<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.all().await;
----

[#_struct_UserManager_contains_username_impl_Into_String_]
==== contains

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn contains(&self, username: impl Into<String>) -> Result<bool>
----

--

sync::
+
--
[source,rust]
----
pub fn contains(&self, username: impl Into<String>) -> Result<bool>
----

--
====

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The user name to be checked a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.contains(username).await;
----

[#_struct_UserManager_create_username_impl_Into_String_password_impl_Into_String_]
==== create

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>,
) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>,
) -> Result
----

--
====

Create a user with the given name &amp; password.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to be created a| `impl Into<String>`
a| `password` a|  — The password of the user to be created a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.create(username, password).await;
----

[#_struct_UserManager_get_username_impl_Into_String_]
==== get

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn get(&self, username: impl Into<String>) -> Result<Option<User>>
----

--

sync::
+
--
[source,rust]
----
pub fn get(&self, username: impl Into<String>) -> Result<Option<User>>
----

--
====

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to retrieve a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.get(username).await;
----

// end::methods[]

