[#_struct_User]
=== User

`Class(name=User, anchor=struct_User, enumConstants=[], description=[], examples=[], fields=[Variable(name=name, anchor=struct_User_name, defaultValue=null, description=null, type=String), Variable(name=password, anchor=struct_User_password, defaultValue=null, description=null, type=Option<String>), Variable(name=server_connections, anchor=struct_User_server_connections, defaultValue=null, description=null, type=HashMap<Address, ServerConnection>)], methods=[Method(name=update_password, signature=pub async fn update_password(&self, password: impl Into<String>) -> Result<()>, anchor=struct_User_update_password_username_password_impl_Into_String_-_Result_, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The name of the user, type=null), Variable(name=password, anchor=null, defaultValue=null, description= — The new password, type=impl Into<String>) -> Result<()], description=[Update the user’s password.], examples=[user.update_password(username, password).await;
user.update_password(username, password).await;], mode=async, returnDescription=null, returnType=Result<()>), Method(name=delete, signature=pub async fn delete(self) -> Result, anchor=struct_User_delete_username, args=[Variable(name=username, anchor=null, defaultValue=null, description= — The name of the user to be deleted, type=null)], description=[Deletes this user], examples=[user.delete().await;
user.delete(username).await;], mode=async, returnDescription=null, returnType=Result)], packagePath=null, superClasses=[Clone, Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `String` a| 
a| `password` a| `Option<String>` a| 
a| `server_connections` a| `HashMap<Address, ServerConnection>` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_User_delete_username]
==== delete

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn delete(self) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn delete(self) -> Result
----

--
====

Deletes this user

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user to be deleted a| 
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
user.delete().await;
user.delete(username).await;
----

--

sync::
+
--
[source,rust]
----
user.delete();
user.delete(username).await;
----

--
====

[#_struct_User_update_password_username_password_impl_Into_String_-_Result_]
==== update_password

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn update_password(&self, password: impl Into<String>) -> Result<()>
----

--

sync::
+
--
[source,rust]
----
pub fn update_password(&self, password: impl Into<String>) -> Result<()>
----

--
====

Update the user’s password.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  — The name of the user a| 
a| `password` a|  — The new password a| `impl Into<String>) -> Result<(`
|===

[caption=""]
.Returns
[source,rust]
----
Result<()>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
user.update_password(username, password).await;
user.update_password(username, password).await;
----

--

sync::
+
--
[source,rust]
----
user.update_password(username, password);
user.update_password(username, password).await;
----

--
====

// end::methods[]

