[#_struct_ConceptRow]
=== ConceptRow

`Class(name=ConceptRow, anchor=struct_ConceptRow, enumConstants=[], description=[A single row of concepts representing substitutions for variables in the query. Contains a Header (column names and query type), and the row of optional concepts. An empty concept in a column means the variable does not have a substitution in this answer.], examples=[], fields=[Variable(name=row, anchor=struct_ConceptRow_row, defaultValue=null, description=null, type=Vec<Option<Concept>>)], methods=[Method(name=get_column_names, signature=pub fn get_column_names(&self) -> &[String], anchor=struct_ConceptRow_get_column_names_, args=[], description=[Retrieve the row column names (shared by all elements in this stream).], examples=[concept_row.get_column_names()], mode=async, returnDescription=null, returnType=&[String]), Method(name=get_query_type, signature=pub fn get_query_type(&self) -> QueryType, anchor=struct_ConceptRow_get_query_type_, args=[], description=[Retrieve the executed query’s type (shared by all elements in this stream).], examples=[concept_row.get_query_type()], mode=async, returnDescription=null, returnType=QueryType), Method(name=get_query_structure, signature=pub fn get_query_structure(&self) -> Option<&Pipeline>, anchor=struct_ConceptRow_get_query_structure_, args=[], description=[Retrieve the executed query’s structure from the ``ConceptRow``’s header, if set. It must be requested via “include query structure” in ``QueryOptions``], examples=[concept_row.get_query_structure()], mode=async, returnDescription=null, returnType=Option<&Pipeline>), Method(name=get_involved_conjunctions, signature=pub fn get_involved_conjunctions(
    &self,
) -> Option<impl Iterator<Item = ConjunctionID> + '_>, anchor=struct_ConceptRow_get_involved_conjunctions_, args=[], description=[Retrieve the ``ConjunctionID``s of ``Conjunction``s that answered this row.], examples=[concept_row.get_involved_conjunctions()], mode=async, returnDescription=null, returnType=Option<impl Iterator<Item = ConjunctionID> + '_>), Method(name=get_involved_conjunctions_cloned, signature=pub fn get_involved_conjunctions_cloned(
    &self,
) -> Option<impl Iterator<Item = ConjunctionID> + 'static>, anchor=struct_ConceptRow_get_involved_conjunctions_cloned_, args=[], description=[Like ``ConceptRow::get_involved_conjunctions`` but clones the underlying data. Meant for simpler lifetimes over FFI.], examples=[], mode=async, returnDescription=null, returnType=Option<impl Iterator<Item = ConjunctionID> + 'static>), Method(name=get, signature=pub fn get(&self, column_name: &str) -> Result<Option<&Concept>>, anchor=struct_ConceptRow_get_var_name, args=[Variable(name=var_name, anchor=null, defaultValue=null, description= — The variable name in the row to retrieve, type=null)], description=[Retrieves a concept for a given variable. Returns an empty optional if the variable name has an empty answer. Returns an error if the variable name is not present.], examples=[concept_row.get(var_name)], mode=async, returnDescription=null, returnType=Result<Option<&Concept>>), Method(name=get_index, signature=pub fn get_index(&self, column_index: usize) -> Result<Option<&Concept>>, anchor=struct_ConceptRow_get_index_column_index_usize, args=[Variable(name=column_index, anchor=null, defaultValue=null, description= — The position in the row to retrieve, type=usize)], description=[Retrieves a concept for a given column index. Returns an empty optional if the index points to an empty answer. Returns an error if the index is not in the row’s range.], examples=[concept_row.get_position(column_index)], mode=async, returnDescription=null, returnType=Result<Option<&Concept>>), Method(name=get_concepts, signature=pub fn get_concepts(&self) -> impl Iterator<Item = &Concept>, anchor=struct_ConceptRow_get_concepts_, args=[], description=[Produces an iterator over all concepts in this ``ConceptRow``, skipping empty results], examples=[concept_row.concepts()], mode=async, returnDescription=null, returnType=impl Iterator<Item = &Concept>)], packagePath=null, superClasses=[Clone, Debug, Display, PartialEq], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`
* `Display`
* `PartialEq`

A single row of concepts representing substitutions for variables in the query. Contains a Header (column names and query type), and the row of optional concepts. An empty concept in a column means the variable does not have a substitution in this answer.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `row` a| `Vec<Option<Concept>>` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_ConceptRow_get_var_name]
==== get

[source,rust]
----
pub fn get(&self, column_name: &str) -> Result<Option<&Concept>>
----

Retrieves a concept for a given variable. Returns an empty optional if the variable name has an empty answer. Returns an error if the variable name is not present.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `var_name` a|  — The variable name in the row to retrieve a| 
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<&Concept>>
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get(var_name)
----

[#_struct_ConceptRow_get_column_names_]
==== get_column_names

[source,rust]
----
pub fn get_column_names(&self) -> &[String]
----

Retrieve the row column names (shared by all elements in this stream).

[caption=""]
.Returns
[source,rust]
----
&[String]
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get_column_names()
----

[#_struct_ConceptRow_get_concepts_]
==== get_concepts

[source,rust]
----
pub fn get_concepts(&self) -> impl Iterator<Item = &Concept>
----

Produces an iterator over all concepts in this ``ConceptRow``, skipping empty results

[caption=""]
.Returns
[source,rust]
----
impl Iterator<Item = &Concept>
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.concepts()
----

[#_struct_ConceptRow_get_index_column_index_usize]
==== get_index

[source,rust]
----
pub fn get_index(&self, column_index: usize) -> Result<Option<&Concept>>
----

Retrieves a concept for a given column index. Returns an empty optional if the index points to an empty answer. Returns an error if the index is not in the row’s range.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `column_index` a|  — The position in the row to retrieve a| `usize`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<&Concept>>
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get_position(column_index)
----

[#_struct_ConceptRow_get_involved_conjunctions_]
==== get_involved_conjunctions

[source,rust]
----
pub fn get_involved_conjunctions(
    &self,
) -> Option<impl Iterator<Item = ConjunctionID> + '_>
----

Retrieve the ``ConjunctionID``s of ``Conjunction``s that answered this row.

[caption=""]
.Returns
[source,rust]
----
Option<impl Iterator<Item = ConjunctionID> + '_>
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get_involved_conjunctions()
----

[#_struct_ConceptRow_get_involved_conjunctions_cloned_]
==== get_involved_conjunctions_cloned

[source,rust]
----
pub fn get_involved_conjunctions_cloned(
    &self,
) -> Option<impl Iterator<Item = ConjunctionID> + 'static>
----

Like ``ConceptRow::get_involved_conjunctions`` but clones the underlying data. Meant for simpler lifetimes over FFI.

[caption=""]
.Returns
[source,rust]
----
Option<impl Iterator<Item = ConjunctionID> + 'static>
----

[#_struct_ConceptRow_get_query_structure_]
==== get_query_structure

[source,rust]
----
pub fn get_query_structure(&self) -> Option<&Pipeline>
----

Retrieve the executed query’s structure from the ``ConceptRow``’s header, if set. It must be requested via “include query structure” in ``QueryOptions``

[caption=""]
.Returns
[source,rust]
----
Option<&Pipeline>
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get_query_structure()
----

[#_struct_ConceptRow_get_query_type_]
==== get_query_type

[source,rust]
----
pub fn get_query_type(&self) -> QueryType
----

Retrieve the executed query’s type (shared by all elements in this stream).

[caption=""]
.Returns
[source,rust]
----
QueryType
----

[caption=""]
.Code examples
[source,rust]
----
concept_row.get_query_type()
----

// end::methods[]

