[#_ConceptMap]
=== ConceptMap

Contains a mapping of variables to concepts.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `explainables` a| `Explainables` a| The Explainables object for this ConceptMap, exposing which of the concepts in this ConceptMap are explainable.
|===
// end::properties[]

// tag::methods[]
[#_ConceptMap_concepts__]
==== concepts

[source,nodejs]
----
concepts(): IterableIterator<Concept>
----

Produces an iterator over all concepts in this ``ConceptMap``.

[caption=""]
.Returns
`IterableIterator<Concept>`

[caption=""]
.Code examples
[source,nodejs]
----
conceptMap.concepts()
----

[#_ConceptMap_get__variable_string]
==== get

[source,nodejs]
----
get(variable): Concept
----

Retrieves a concept for a given variable name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `string`
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,nodejs]
----
conceptMap.get(variable)
----

[#_ConceptMap_map__]
==== map

[source,nodejs]
----
map(): Map<string, Concept>
----

Returns the inner ``Map`` where keys are query variables, and values are concepts.

[caption=""]
.Returns
`Map<string, Concept>`

[caption=""]
.Code examples
[source,nodejs]
----
conceptMap.map()
----

[#_ConceptMap_variables__]
==== variables

[source,nodejs]
----
variables(): IterableIterator<string>
----

Produces an iterator over all variables in this ``ConceptMap``.

[caption=""]
.Returns
`IterableIterator<string>`

[caption=""]
.Code examples
[source,nodejs]
----
conceptMap.variables()
----

// end::methods[]

