[#_Stream_T]
=== Stream<T>

A stream of elements offering a functional interface to manipulate elements. Typically the elements are generated/retrieved lazily.

// tag::methods[]
[#_Stream_T__asyncIterator___]
==== [asyncIterator]

[source,nodejs]
----
[asyncIterator](): AsyncIterator<T, any, undefined>
----



[caption=""]
.Returns
`AsyncIterator<T, any, undefined>`

[#_Stream_T_collect__]
==== collect

[source,nodejs]
----
collect(): Promise<T[]>
----

Collects all the answers from this stream into an array

[caption=""]
.Returns
`Promise<T[]>`

[caption=""]
.Code examples
[source,nodejs]
----
results = transaction.query.match(query).collect().await;
----

[#_Stream_T_every__callbackFn___value____unknown_]
==== every

[source,nodejs]
----
every(callbackFn): Promise<boolean>
----

Checks whether a condition is satisfied by ALL answers in this stream.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `callbackFn` a|  a| `((value) => unknown)`
|===

[caption=""]
.Returns
`Promise<boolean>`

[#_Stream_T_filter__filter___value____boolean_]
==== filter

[source,nodejs]
----
filter(filter): Stream<T>
----

Returns a new stream from this stream consisting only of elements which satisfy a given condition.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `filter` a| The condition to evaluate.
Examples
``// For a query "match $p isa person, has age $a;", only retrieve results having $a &gt;= 60.results = transaction.query.match(query).filter(cm =&gt; cm.get("a").value &gt; 60).collect();
``Copy a| `((value) => boolean)`
|===

[caption=""]
.Returns
`Stream<T>`

[#_Stream_T_first__]
==== first

[source,nodejs]
----
first(): Promise<T>
----

Returns the first element in the stream.

[caption=""]
.Returns
`Promise<T>`

[#_Stream_T_flatMap__mapper___value____Stream_U__]
==== flatMap

[source,nodejs]
----
flatMap<U>(mapper): Stream<U>
----

Given a function which accepts a single element of this stream and returns a new stream, This function returns a new stream obtained by applying the function to each element in the stream, and concatenating each result thus obtained

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `mapper` a| The mapping function to apply. Must return a stream. a| `((value) => Stream<U>)`
|===

[caption=""]
.Returns
`Stream<U>`

[#_Stream_T_forEach__fn___value____void_]
==== forEach

[source,nodejs]
----
forEach(fn): Promise<void>
----

Executes the given function for each element in the stream.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `fn` a| The function to evaluate for each element. a| `((value) => void)`
|===

[caption=""]
.Returns
`Promise<void>`

[#_Stream_T_iterator__]
==== iterator

[source,nodejs]
----
iterator(): AsyncIterator<T, any, undefined>
----



[caption=""]
.Returns
`AsyncIterator<T, any, undefined>`

[#_Stream_T_map__mapper___value____U_]
==== map

[source,nodejs]
----
map<U>(mapper): Stream<U>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `mapper` a| The mapping function to apply. Returns a new stream from this stream by applying the ``mapper`` function to each element. a| `((value) => U)`
|===

[caption=""]
.Returns
`Stream<U>`

[#_Stream_T_new_Stream__]
==== new Stream

[source,nodejs]
----
new Stream<T>(): Stream<T>
----



[caption=""]
.Returns
`Stream<T>`

[#_Stream_T_some__callbackFn___value____unknown_]
==== some

[source,nodejs]
----
some(callbackFn): Promise<boolean>
----

Checks whether a condition is satisfied by ANY answer in this stream.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `callbackFn` a|  a| `((value) => unknown)`
|===

[caption=""]
.Returns
`Promise<boolean>`

// end::methods[]

