[#_QueryManager]
=== QueryManager

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_QueryManager_define__query_str__options_TypeDBOptions]
==== define

[source,python]
----
define(query: str, options: TypeDBOptions = None) -> Promise[None]
----

Performs a TypeQL Define query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Define query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions` a| `None`
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.define(query, options).resolve()
----

[#_QueryManager_delete__query_str__options_TypeDBOptions__None]
==== delete

[source,python]
----
delete(query: str, options: TypeDBOptions | None = None) -> Promise[None]
----

Performs a TypeQL Delete query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Delete query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.delete(query, options).resolve()
----

[#_QueryManager_explain__explainable_ConceptMap_Explainable__options_TypeDBOptions__None]
==== explain

[source,python]
----
explain(explainable: ConceptMap.Explainable, options: TypeDBOptions | None = None) -> Iterator[Explanation]
----

Performs a TypeQL Explain query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `explainable` a| The Explainable to be explained a| `ConceptMap.Explainable` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[Explanation]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.explain(explainable, options)
----

[#_QueryManager_fetch__query_str__options_TypeDBOptions__None]
==== fetch

[source,python]
----
fetch(query: str, options: TypeDBOptions | None = None) -> Iterator[dict]
----

Performs a TypeQL Fetch query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Fetch query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[dict]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.fetch(query, options)
----

[#_QueryManager_get__query_str__options_TypeDBOptions__None]
==== get

[source,python]
----
get(query: str, options: TypeDBOptions | None = None) -> Iterator[ConceptMap]
----

Performs a TypeQL Match (Get) query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Match (Get) query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[ConceptMap]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.get(query, options)
----

[#_QueryManager_get_aggregate__query_str__options_TypeDBOptions__None]
==== get_aggregate

[source,python]
----
get_aggregate(query: str, options: TypeDBOptions | None = None) -> Promise[Value | None]
----

Performs a TypeQL Match Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Match Aggregate query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[Value | None]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.get_aggregate(query, options).resolve()
----

[#_QueryManager_get_group__query_str__options_TypeDBOptions__None]
==== get_group

[source,python]
----
get_group(query: str, options: TypeDBOptions | None = None) -> Iterator[ConceptMapGroup]
----

Performs a TypeQL Match Group query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Match Group query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[ConceptMapGroup]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.get_group(query, options)
----

[#_QueryManager_get_group_aggregate__query_str__options_TypeDBOptions__None]
==== get_group_aggregate

[source,python]
----
get_group_aggregate(query: str, options: TypeDBOptions | None = None) -> Iterator[ValueGroup]
----

Performs a TypeQL Match Group Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[ValueGroup]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.get_group_aggregate(query, options)
----

[#_QueryManager_insert__query_str__options_TypeDBOptions__None]
==== insert

[source,python]
----
insert(query: str, options: TypeDBOptions | None = None) -> Iterator[ConceptMap]
----

Performs a TypeQL Insert query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Insert query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[ConceptMap]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.insert(query, options)
----

[#_QueryManager_undefine__query_str__options_TypeDBOptions]
==== undefine

[source,python]
----
undefine(query: str, options: TypeDBOptions = None) -> Promise[None]
----

Performs a TypeQL Undefine query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Undefine query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions` a| `None`
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.undefine(query, options).resolve()
----

[#_QueryManager_update__query_str__options_TypeDBOptions__None]
==== update

[source,python]
----
update(query: str, options: TypeDBOptions | None = None) -> Iterator[ConceptMap]
----

Performs a TypeQL Update query in the transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The TypeQL Update query to be executed a| `str` a| 
a| `options` a| Specify query options a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[ConceptMap]`

[caption=""]
.Code examples
[source,python]
----
transaction.query.update(query, options)
----

// end::methods[]

