[#_IConcept]
[.doc-api-reference-driver]
=== IConcept

`class`

*Package*: `TypeDB.Driver.Api`



The base interface for all concepts in TypeDB.

// tag::methods[]
[#_IAttribute_TypeDB_Driver_Api_IConcept_AsAttribute_]
==== method ``AsAttribute``

[source,cs]
----
IAttribute AsAttribute()
----



Casts the concept to IAttribute.

Implemented in TypeDB.Driver.Api.IAttribute.

[caption=""]
.Returns
`IAttribute`

[caption=""]
.Code examples
[source,cs]
----
concept.AsAttribute()
----

[#_IAttributeType_TypeDB_Driver_Api_IConcept_AsAttributeType_]
==== method ``AsAttributeType``

[source,cs]
----
IAttributeType AsAttributeType()
----



Casts the concept to IAttributeType.

Implemented in TypeDB.Driver.Api.IAttributeType.

[caption=""]
.Returns
`IAttributeType`

[caption=""]
.Code examples
[source,cs]
----
concept.AsAttributeType()
----

[#_IEntity_TypeDB_Driver_Api_IConcept_AsEntity_]
==== method ``AsEntity``

[source,cs]
----
IEntity AsEntity()
----



Casts the concept to IEntity.

Implemented in TypeDB.Driver.Api.IEntity.

[caption=""]
.Returns
`IEntity`

[caption=""]
.Code examples
[source,cs]
----
concept.AsEntity()
----

[#_IEntityType_TypeDB_Driver_Api_IConcept_AsEntityType_]
==== method ``AsEntityType``

[source,cs]
----
IEntityType AsEntityType()
----



Casts the concept to IEntityType.

Implemented in TypeDB.Driver.Api.IEntityType.

[caption=""]
.Returns
`IEntityType`

[caption=""]
.Code examples
[source,cs]
----
concept.AsEntityType()
----

[#_IInstance_TypeDB_Driver_Api_IConcept_AsInstance_]
==== method ``AsInstance``

[source,cs]
----
IInstance AsInstance()
----



Casts the concept to IInstance.

Implemented in TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`IInstance`

[caption=""]
.Code examples
[source,cs]
----
concept.AsInstance()
----

[#_IRelation_TypeDB_Driver_Api_IConcept_AsRelation_]
==== method ``AsRelation``

[source,cs]
----
IRelation AsRelation()
----



Casts the concept to IRelation.

Implemented in TypeDB.Driver.Api.IRelation.

[caption=""]
.Returns
`IRelation`

[caption=""]
.Code examples
[source,cs]
----
concept.AsRelation()
----

[#_IRelationType_TypeDB_Driver_Api_IConcept_AsRelationType_]
==== method ``AsRelationType``

[source,cs]
----
IRelationType AsRelationType()
----



Casts the concept to IRelationType.

Implemented in TypeDB.Driver.Api.IRelationType.

[caption=""]
.Returns
`IRelationType`

[caption=""]
.Code examples
[source,cs]
----
concept.AsRelationType()
----

[#_IRoleType_TypeDB_Driver_Api_IConcept_AsRoleType_]
==== method ``AsRoleType``

[source,cs]
----
IRoleType AsRoleType()
----



Casts the concept to IRoleType.

Implemented in TypeDB.Driver.Api.IRoleType.

[caption=""]
.Returns
`IRoleType`

[caption=""]
.Code examples
[source,cs]
----
concept.AsRoleType()
----

[#_IType_TypeDB_Driver_Api_IConcept_AsType_]
==== method ``AsType``

[source,cs]
----
IType AsType()
----



Casts the concept to IType.

Implemented in TypeDB.Driver.Api.IType.

[caption=""]
.Returns
`IType`

[caption=""]
.Code examples
[source,cs]
----
concept.AsType()
----

[#_IValue_TypeDB_Driver_Api_IConcept_AsValue_]
==== method ``AsValue``

[source,cs]
----
IValue AsValue()
----



Casts the concept to IValue.

Implemented in TypeDB.Driver.Api.IValue.

[caption=""]
.Returns
`IValue`

[caption=""]
.Code examples
[source,cs]
----
concept.AsValue()
----

[#_string_TypeDB_Driver_Api_IConcept_GetLabel_]
==== method ``GetLabel``

[source,cs]
----
string GetLabel()
----



Retrieves the unique label of the concept. If this is an Instance, returns the label of the type of this instance ("unknown" if type fetching is disabled). If this is a Value, returns the label of the value type. If this is a Type, returns the label of the type.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
concept.GetLabel()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsAttribute_]
==== method ``IsAttribute``

[source,cs]
----
bool IsAttribute()
----



Checks if the concept is an IAttribute.

Implemented in TypeDB.Driver.Api.IAttribute.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsAttribute()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsAttributeType_]
==== method ``IsAttributeType``

[source,cs]
----
bool IsAttributeType()
----



Checks if the concept is an IAttributeType.

Implemented in TypeDB.Driver.Api.IAttributeType.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsAttributeType()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsBoolean_]
==== method ``IsBoolean``

[source,cs]
----
bool IsBoolean()
----



Returns true if the value which this Concept holds is of type boolean or if this Concept is an AttributeType of type boolean.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsBoolean()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDate_]
==== method ``IsDate``

[source,cs]
----
bool IsDate()
----



Returns true if the value which this Concept holds is of type date or if this Concept is an AttributeType of type date.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDate()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDatetime_]
==== method ``IsDatetime``

[source,cs]
----
bool IsDatetime()
----



Returns true if the value which this Concept holds is of type datetime or if this Concept is an AttributeType of type datetime.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDatetime()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDatetimeTZ_]
==== method ``IsDatetimeTZ``

[source,cs]
----
bool IsDatetimeTZ()
----



Returns true if the value which this Concept holds is of type datetime-tz or if this Concept is an AttributeType of type datetime-tz.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDatetimeTZ()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDecimal_]
==== method ``IsDecimal``

[source,cs]
----
bool IsDecimal()
----



Returns true if the value which this Concept holds is of type decimal or if this Concept is an AttributeType of type decimal.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDecimal()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDouble_]
==== method ``IsDouble``

[source,cs]
----
bool IsDouble()
----



Returns true if the value which this Concept holds is of type double or if this Concept is an AttributeType of type double.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDouble()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsDuration_]
==== method ``IsDuration``

[source,cs]
----
bool IsDuration()
----



Returns true if the value which this Concept holds is of type duration or if this Concept is an AttributeType of type duration.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsDuration()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsEntity_]
==== method ``IsEntity``

[source,cs]
----
bool IsEntity()
----



Checks if the concept is an IEntity.

Implemented in TypeDB.Driver.Api.IEntity.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsEntity()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsEntityType_]
==== method ``IsEntityType``

[source,cs]
----
bool IsEntityType()
----



Checks if the concept is an IEntityType.

Implemented in TypeDB.Driver.Api.IEntityType.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsEntityType()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsInstance_]
==== method ``IsInstance``

[source,cs]
----
bool IsInstance()
----



Checks if the concept is an instance (entity, relation, or attribute).

Implemented in TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsInstance()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsInteger_]
==== method ``IsInteger``

[source,cs]
----
bool IsInteger()
----



Returns true if the value which this Concept holds is of type integer or if this Concept is an AttributeType of type integer.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsInteger()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsRelation_]
==== method ``IsRelation``

[source,cs]
----
bool IsRelation()
----



Checks if the concept is a IRelation.

Implemented in TypeDB.Driver.Api.IRelation.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsRelation()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsRelationType_]
==== method ``IsRelationType``

[source,cs]
----
bool IsRelationType()
----



Checks if the concept is a IRelationType.

Implemented in TypeDB.Driver.Api.IRelationType.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsRelationType()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsRoleType_]
==== method ``IsRoleType``

[source,cs]
----
bool IsRoleType()
----



Checks if the concept is a IRoleType.

Implemented in TypeDB.Driver.Api.IRoleType.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsRoleType()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsString_]
==== method ``IsString``

[source,cs]
----
bool IsString()
----



Returns true if the value which this Concept holds is of type string or if this Concept is an AttributeType of type string.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsString()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsStruct_]
==== method ``IsStruct``

[source,cs]
----
bool IsStruct()
----



Returns true if the value which this Concept holds is of type struct or if this Concept is an AttributeType of type struct.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsStruct()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsType_]
==== method ``IsType``

[source,cs]
----
bool IsType()
----



Checks if the concept is a IType.

Implemented in TypeDB.Driver.Api.IType.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsType()
----

[#_bool_TypeDB_Driver_Api_IConcept_IsValue_]
==== method ``IsValue``

[source,cs]
----
bool IsValue()
----



Checks if the concept is a IValue.

Implemented in TypeDB.Driver.Api.IValue.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
concept.IsValue()
----

[#_bool_TypeDB_Driver_Api_IConcept_TryGetBoolean_]
==== method ``TryGetBoolean``

[source,cs]
----
bool? TryGetBoolean()
----



Returns a boolean value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`bool?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetBoolean()
----

[#_DateOnly_TypeDB_Driver_Api_IConcept_TryGetDate_]
==== method ``TryGetDate``

[source,cs]
----
DateOnly? TryGetDate()
----



Returns a date value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`DateOnly?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDate()
----

[#_Datetime_TypeDB_Driver_Api_IConcept_TryGetDatetime_]
==== method ``TryGetDatetime``

[source,cs]
----
Datetime? TryGetDatetime()
----



Returns a datetime value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`Datetime?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDatetime()
----

[#_DatetimeTZ_TypeDB_Driver_Api_IConcept_TryGetDatetimeTZ_]
==== method ``TryGetDatetimeTZ``

[source,cs]
----
DatetimeTZ? TryGetDatetimeTZ()
----



Returns a datetime-tz value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`DatetimeTZ?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDatetimeTZ()
----

[#_decimal_TypeDB_Driver_Api_IConcept_TryGetDecimal_]
==== method ``TryGetDecimal``

[source,cs]
----
decimal? TryGetDecimal()
----



Returns a decimal value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`decimal?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDecimal()
----

[#_double_TypeDB_Driver_Api_IConcept_TryGetDouble_]
==== method ``TryGetDouble``

[source,cs]
----
double? TryGetDouble()
----



Returns a double value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`double?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDouble()
----

[#_Duration_TypeDB_Driver_Api_IConcept_TryGetDuration_]
==== method ``TryGetDuration``

[source,cs]
----
Duration? TryGetDuration()
----



Returns a duration value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`Duration?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetDuration()
----

[#_string_TypeDB_Driver_Api_IConcept_TryGetIID_]
==== method ``TryGetIID``

[source,cs]
----
string? TryGetIID()
----



Retrieves the unique id (IID) of the Concept. Returns null if absent.

[caption=""]
.Returns
`string?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetIID()
----

[#_long_TypeDB_Driver_Api_IConcept_TryGetInteger_]
==== method ``TryGetInteger``

[source,cs]
----
long? TryGetInteger()
----



Returns an integer value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`long?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetInteger()
----

[#_string_TypeDB_Driver_Api_IConcept_TryGetLabel_]
==== method ``TryGetLabel``

[source,cs]
----
string? TryGetLabel()
----



Retrieves the unique label of the concept, or null if type fetching is disabled for instances.

[caption=""]
.Returns
`string?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetLabel()
----

[#_string_TypeDB_Driver_Api_IConcept_TryGetString_]
==== method ``TryGetString``

[source,cs]
----
string? TryGetString()
----



Returns a string value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`string?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetString()
----

[#_IReadOnlyDictionary_string_IValue_TypeDB_Driver_Api_IConcept_TryGetStruct_]
==== method ``TryGetStruct``

[source,cs]
----
IReadOnlyDictionary< string, IValue? >? TryGetStruct()
----



Returns a struct value of this Concept. If it's not a Value or it has another type, returns null.

[caption=""]
.Returns
`IReadOnlyDictionary< string, IValue? >?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetStruct()
----

[#_IValue_TypeDB_Driver_Api_IConcept_TryGetValue_]
==== method ``TryGetValue``

[source,cs]
----
IValue? TryGetValue()
----



Retrieves the value which this Concept holds. Returns null if this Concept does not hold any value.

[caption=""]
.Returns
`IValue?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetValue()
----

[#_string_TypeDB_Driver_Api_IConcept_TryGetValueType_]
==== method ``TryGetValueType``

[source,cs]
----
string? TryGetValueType()
----



Retrieves the string describing the value type of this Concept. Returns null if absent.

[caption=""]
.Returns
`string?`

[caption=""]
.Code examples
[source,cs]
----
concept.TryGetValueType()
----

// end::methods[]

