[#_IConcept]
=== IConcept

*Package*: `TypeDB.Driver.Api`



The base interface for all concepts in TypeDB.

// tag::methods[]
[#_IAttribute_TypeDB_Driver_Api_IConcept_AsAttribute_]
==== AsAttribute

[source,cs]
----
IAttribute AsAttribute()
----



Casts the concept to IAttribute.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an attribute.
    
   
  
 


 
  concept.AsAttribute()
 


Implemented in TypeDB.Driver.Api.IAttribute.

[caption=""]
.Returns
`IAttribute`

[#_IAttributeType_TypeDB_Driver_Api_IConcept_AsAttributeType_]
==== AsAttributeType

[source,cs]
----
IAttributeType AsAttributeType()
----



Casts the concept to IAttributeType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an attribute type.
    
   
  
 


 
  concept.AsAttributeType()
 


Implemented in TypeDB.Driver.Api.IAttributeType.

[caption=""]
.Returns
`IAttributeType`

[#_IEntity_TypeDB_Driver_Api_IConcept_AsEntity_]
==== AsEntity

[source,cs]
----
IEntity AsEntity()
----



Casts the concept to IEntity.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an entity.
    
   
  
 


 
  concept.AsEntity()
 


Implemented in TypeDB.Driver.Api.IEntity.

[caption=""]
.Returns
`IEntity`

[#_IEntityType_TypeDB_Driver_Api_IConcept_AsEntityType_]
==== AsEntityType

[source,cs]
----
IEntityType AsEntityType()
----



Casts the concept to IEntityType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an entity type.
    
   
  
 


 
  concept.AsEntityType()
 


Implemented in TypeDB.Driver.Api.IEntityType.

[caption=""]
.Returns
`IEntityType`

[#_IRelation_TypeDB_Driver_Api_IConcept_AsRelation_]
==== AsRelation

[source,cs]
----
IRelation AsRelation()
----



Casts the concept to IRelation.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a relation.
    
   
  
 


 
  concept.AsRelation()
 


Implemented in TypeDB.Driver.Api.IRelation.

[caption=""]
.Returns
`IRelation`

[#_IRelationType_TypeDB_Driver_Api_IConcept_AsRelationType_]
==== AsRelationType

[source,cs]
----
IRelationType AsRelationType()
----



Casts the concept to IRelationType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a relation type.
    
   
  
 


 
  concept.AsRelationType()
 


Implemented in TypeDB.Driver.Api.IRelationType.

[caption=""]
.Returns
`IRelationType`

[#_IRoleType_TypeDB_Driver_Api_IConcept_AsRoleType_]
==== AsRoleType

[source,cs]
----
IRoleType AsRoleType()
----



Casts the concept to IRoleType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a role type.
    
   
  
 


 
  concept.AsRoleType()
 


Implemented in TypeDB.Driver.Api.IRoleType.

[caption=""]
.Returns
`IRoleType`

[#_IThing_TypeDB_Driver_Api_IConcept_AsThing_]
==== AsThing

[source,cs]
----
IThing AsThing()
----



Casts the concept to IThing (instance).

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a thing/instance.
    
   
  
 


 
  concept.AsThing()
 


Implemented in TypeDB.Driver.Api.IThing.

[caption=""]
.Returns
`IThing`

[#_IThingType_TypeDB_Driver_Api_IConcept_AsThingType_]
==== AsThingType

[source,cs]
----
IThingType AsThingType()
----



Casts the concept to IThingType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a thing type.
    
   
  
 


 
  concept.AsThingType()
 


Implemented in TypeDB.Driver.Api.IThingType.

[caption=""]
.Returns
`IThingType`

[#_IType_TypeDB_Driver_Api_IConcept_AsType_]
==== AsType

[source,cs]
----
IType AsType()
----



Casts the concept to IType.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a type.
    
   
  
 


 
  concept.AsType()
 


Implemented in TypeDB.Driver.Api.IType.

[caption=""]
.Returns
`IType`

[#_IValue_TypeDB_Driver_Api_IConcept_AsValue_]
==== AsValue

[source,cs]
----
IValue AsValue()
----



Casts the concept to IValue.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a value.
    
   
  
 


 
  concept.AsValue()
 


Implemented in TypeDB.Driver.Api.IValue.

[caption=""]
.Returns
`IValue`

[#_string_TypeDB_Driver_Api_IConcept_GetLabel_]
==== GetLabel

[source,cs]
----
string GetLabel()
----



Retrieves the unique label of the concept. If this is an Instance, returns the label of the type of this instance ("unknown" if type fetching is disabled). If this is a Value, returns the label of the value type. If this is a Type, returns the label of the type.

 
  concept.GetLabel()
 


[caption=""]
.Returns
`string`

[#_bool_TypeDB_Driver_Api_IConcept_IsAttribute_]
==== IsAttribute

[source,cs]
----
bool IsAttribute()
----



Checks if the concept is an IAttribute.

 
  concept.IsAttribute()
 


Implemented in TypeDB.Driver.Api.IAttribute.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsAttributeType_]
==== IsAttributeType

[source,cs]
----
bool IsAttributeType()
----



Checks if the concept is an IAttributeType.

 
  concept.IsAttributeType()
 


Implemented in TypeDB.Driver.Api.IAttributeType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsBoolean_]
==== IsBoolean

[source,cs]
----
bool IsBoolean()
----



Returns true if the value which this Concept holds is of type boolean or if this Concept is an AttributeType of type boolean.

 
  concept.IsBoolean()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDate_]
==== IsDate

[source,cs]
----
bool IsDate()
----



Returns true if the value which this Concept holds is of type date or if this Concept is an AttributeType of type date.

 
  concept.IsDate()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDatetime_]
==== IsDatetime

[source,cs]
----
bool IsDatetime()
----



Returns true if the value which this Concept holds is of type datetime or if this Concept is an AttributeType of type datetime.

 
  concept.IsDatetime()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDatetimeTZ_]
==== IsDatetimeTZ

[source,cs]
----
bool IsDatetimeTZ()
----



Returns true if the value which this Concept holds is of type datetime-tz or if this Concept is an AttributeType of type datetime-tz.

 
  concept.IsDatetimeTZ()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDecimal_]
==== IsDecimal

[source,cs]
----
bool IsDecimal()
----



Returns true if the value which this Concept holds is of type decimal or if this Concept is an AttributeType of type decimal.

 
  concept.IsDecimal()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDouble_]
==== IsDouble

[source,cs]
----
bool IsDouble()
----



Returns true if the value which this Concept holds is of type double or if this Concept is an AttributeType of type double.

 
  concept.IsDouble()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsDuration_]
==== IsDuration

[source,cs]
----
bool IsDuration()
----



Returns true if the value which this Concept holds is of type duration or if this Concept is an AttributeType of type duration.

 
  concept.IsDuration()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsEntity_]
==== IsEntity

[source,cs]
----
bool IsEntity()
----



Checks if the concept is an IEntity.

 
  concept.IsEntity()
 


Implemented in TypeDB.Driver.Api.IEntity.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsEntityType_]
==== IsEntityType

[source,cs]
----
bool IsEntityType()
----



Checks if the concept is an IEntityType.

 
  concept.IsEntityType()
 


Implemented in TypeDB.Driver.Api.IEntityType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsInstance_]
==== IsInstance

[source,cs]
----
bool IsInstance()
----



Checks if the concept is an instance (entity, relation, or attribute). This is the 3.0 name for what was previously called "Thing".

 
  concept.IsInstance()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsInteger_]
==== IsInteger

[source,cs]
----
bool IsInteger()
----



Returns true if the value which this Concept holds is of type integer or if this Concept is an AttributeType of type integer.

 
  concept.IsInteger()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsRelation_]
==== IsRelation

[source,cs]
----
bool IsRelation()
----



Checks if the concept is a IRelation.

 
  concept.IsRelation()
 


Implemented in TypeDB.Driver.Api.IRelation.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsRelationType_]
==== IsRelationType

[source,cs]
----
bool IsRelationType()
----



Checks if the concept is a IRelationType.

 
  concept.IsRelationType()
 


Implemented in TypeDB.Driver.Api.IRelationType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsRoleType_]
==== IsRoleType

[source,cs]
----
bool IsRoleType()
----



Checks if the concept is a IRoleType.

 
  concept.IsRoleType()
 


Implemented in TypeDB.Driver.Api.IRoleType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsString_]
==== IsString

[source,cs]
----
bool IsString()
----



Returns true if the value which this Concept holds is of type string or if this Concept is an AttributeType of type string.

 
  concept.IsString()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsStruct_]
==== IsStruct

[source,cs]
----
bool IsStruct()
----



Returns true if the value which this Concept holds is of type struct or if this Concept is an AttributeType of type struct.

 
  concept.IsStruct()
 


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsThing_]
==== IsThing

[source,cs]
----
bool IsThing()
----



Checks if the concept is a IThing. Note: In 3.0, this is also known as IsInstance().

 
  concept.IsThing()
 


Implemented in TypeDB.Driver.Api.IThing.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsThingType_]
==== IsThingType

[source,cs]
----
bool IsThingType()
----



Checks if the concept is a IThingType.

 
  concept.IsThingType()
 


Implemented in TypeDB.Driver.Api.IThingType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsType_]
==== IsType

[source,cs]
----
bool IsType()
----



Checks if the concept is a IType.

 
  concept.IsType()
 


Implemented in TypeDB.Driver.Api.IType.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_IsValue_]
==== IsValue

[source,cs]
----
bool IsValue()
----



Checks if the concept is a IValue.

 
  concept.IsValue()
 


Implemented in TypeDB.Driver.Api.IValue.

[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IConcept_TryGetBoolean_]
==== TryGetBoolean

[source,cs]
----
bool? TryGetBoolean()
----



Returns a boolean value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetBoolean()
 


[caption=""]
.Returns
`bool?`

[#_DateOnly_TypeDB_Driver_Api_IConcept_TryGetDate_]
==== TryGetDate

[source,cs]
----
DateOnly? TryGetDate()
----



Returns a date value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDate()
 


[caption=""]
.Returns
`DateOnly?`

[#_DateTime_TypeDB_Driver_Api_IConcept_TryGetDatetime_]
==== TryGetDatetime

[source,cs]
----
DateTime? TryGetDatetime()
----



Returns a datetime value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDatetime()
 


[caption=""]
.Returns
`DateTime?`

[#_DateTimeOffset_TypeDB_Driver_Api_IConcept_TryGetDatetimeTZ_]
==== TryGetDatetimeTZ

[source,cs]
----
DateTimeOffset? TryGetDatetimeTZ()
----



Returns a datetime-tz value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDatetimeTZ()
 


[caption=""]
.Returns
`DateTimeOffset?`

[#_decimal_TypeDB_Driver_Api_IConcept_TryGetDecimal_]
==== TryGetDecimal

[source,cs]
----
decimal? TryGetDecimal()
----



Returns a decimal value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDecimal()
 


[caption=""]
.Returns
`decimal?`

[#_double_TypeDB_Driver_Api_IConcept_TryGetDouble_]
==== TryGetDouble

[source,cs]
----
double? TryGetDouble()
----



Returns a double value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDouble()
 


[caption=""]
.Returns
`double?`

[#_Duration_TypeDB_Driver_Api_IConcept_TryGetDuration_]
==== TryGetDuration

[source,cs]
----
Duration? TryGetDuration()
----



Returns a duration value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetDuration()
 


[caption=""]
.Returns
`Duration?`

[#_string_TypeDB_Driver_Api_IConcept_TryGetIID_]
==== TryGetIID

[source,cs]
----
string? TryGetIID()
----



Retrieves the unique id (IID) of the Concept. Returns null if absent.

 
  concept.TryGetIID()
 


[caption=""]
.Returns
`string?`

[#_long_TypeDB_Driver_Api_IConcept_TryGetInteger_]
==== TryGetInteger

[source,cs]
----
long? TryGetInteger()
----



Returns an integer value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetInteger()
 


[caption=""]
.Returns
`long?`

[#_string_TypeDB_Driver_Api_IConcept_TryGetLabel_]
==== TryGetLabel

[source,cs]
----
string? TryGetLabel()
----



Retrieves the unique label of the concept, or null if type fetching is disabled for instances.

 
  concept.TryGetLabel()
 


[caption=""]
.Returns
`string?`

[#_string_TypeDB_Driver_Api_IConcept_TryGetString_]
==== TryGetString

[source,cs]
----
string? TryGetString()
----



Returns a string value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetString()
 


[caption=""]
.Returns
`string?`

[#_IReadOnlyDictionary_string_IValue_TypeDB_Driver_Api_IConcept_TryGetStruct_]
==== TryGetStruct

[source,cs]
----
IReadOnlyDictionary< string, IValue? >? TryGetStruct()
----



Returns a struct value of this Concept. If it's not a Value or it has another type, returns null.

 
  concept.TryGetStruct()
 


[caption=""]
.Returns
`IReadOnlyDictionary< string, IValue? >?`

[#_IValue_TypeDB_Driver_Api_IConcept_TryGetValue_]
==== TryGetValue

[source,cs]
----
IValue? TryGetValue()
----



Retrieves the value which this Concept holds. Returns null if this Concept does not hold any value.

 
  concept.TryGetValue()
 


[caption=""]
.Returns
`IValue?`

[#_string_TypeDB_Driver_Api_IConcept_TryGetValueType_]
==== TryGetValueType

[source,cs]
----
string? TryGetValueType()
----



Retrieves the string describing the value type of this Concept. Returns null if absent.

 
  concept.TryGetValueType()
 


[caption=""]
.Returns
`string?`

// end::methods[]

