[#_struct_QueryOptions]
=== QueryOptions

`Class(name=QueryOptions, anchor=struct_QueryOptions, enumConstants=[], description=[TypeDB query options. ``QueryOptions`` object can be used to override the default server behaviour for executed queries.], examples=[], fields=[Variable(name=include_instance_types, anchor=struct_QueryOptions_include_instance_types, defaultValue=null, description=If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted., type=Option<bool>), Variable(name=prefetch_size, anchor=struct_QueryOptions_prefetch_size, defaultValue=null, description=If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1., type=Option<u64>), Variable(name=include_query_structure, anchor=struct_QueryOptions_include_query_structure, defaultValue=null, description=If set, requests the server to return the structure of the query in the ConceptRow header., type=Option<bool>)], methods=[Method(name=include_instance_types, signature=pub fn include_instance_types(self, include_instance_types: bool) -> Self, anchor=struct_QueryOptions_include_instance_types_, args=[], description=[If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.], examples=[], mode=async, returnDescription=null, returnType=Self), Method(name=prefetch_size, signature=pub fn prefetch_size(self, prefetch_size: u64) -> Self, anchor=struct_QueryOptions_prefetch_size_, args=[], description=[If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side.], examples=[], mode=async, returnDescription=null, returnType=Self), Method(name=include_query_structure, signature=pub fn include_query_structure(self, include_query_structure: bool) -> Self, anchor=struct_QueryOptions_include_query_structure_, args=[], description=[If set, requests the server to return the structure of the query in the ConceptRow header.], examples=[], mode=async, returnDescription=null, returnType=Self)], packagePath=null, superClasses=[Clone, Copy, Debug, Default], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Copy`
* `Debug`
* `Default`

TypeDB query options. ``QueryOptions`` object can be used to override the default server behaviour for executed queries.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `include_instance_types` a| `Option<bool>` a| If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.
a| `include_query_structure` a| `Option<bool>` a| If set, requests the server to return the structure of the query in the ConceptRow header.
a| `prefetch_size` a| `Option<u64>` a| If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1.
|===
// end::properties[]

// tag::methods[]
[#_struct_QueryOptions_include_instance_types_]
==== include_instance_types

[source,rust]
----
pub fn include_instance_types(self, include_instance_types: bool) -> Self
----

If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_QueryOptions_include_query_structure_]
==== include_query_structure

[source,rust]
----
pub fn include_query_structure(self, include_query_structure: bool) -> Self
----

If set, requests the server to return the structure of the query in the ConceptRow header.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_QueryOptions_prefetch_size_]
==== prefetch_size

[source,rust]
----
pub fn prefetch_size(self, prefetch_size: u64) -> Self
----

If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side.

[caption=""]
.Returns
[source,rust]
----
Self
----

// end::methods[]

