[#_struct_Transaction]
=== Transaction

*Implements traits:*

* `Debug`

A transaction with a TypeDB database.

// tag::methods[]
[#_struct_Transaction_commit_]
==== commit

[source,rust]
----
pub fn commit(self) -> impl Promise<'static, Result>
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.commit().await
----

--

sync::
+
--
[source,rust]
----
transaction.commit()
----

--
====

[#_struct_Transaction_force_close_]
==== force_close

[source,rust]
----
pub fn force_close(&self)
----

Closes the transaction.

[caption=""]
.Returns
[source,rust]
----
null
----

[caption=""]
.Code examples
[source,rust]
----
transaction.force_close()
----

[#_struct_Transaction_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Closes the transaction.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
transaction.close()
----

[#_struct_Transaction_on_close_function]
==== on_close

[source,rust]
----
pub fn on_close(
    &self,
    callback: impl FnOnce(Option<Error>) + Send + Sync + 'static,
)
----

Registers a callback function which will be executed when this transaction is closed.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a|  — The callback function. a| 
|===

[caption=""]
.Returns
[source,rust]
----
null
----

[caption=""]
.Code examples
[source,rust]
----
transaction.on_close(function)
----

[#_struct_Transaction_query_]
==== query

[source,rust]
----
pub fn query(
    &self,
    query: impl AsRef<str>,
) -> impl Promise<'static, Result<QueryAnswer>>
----

Performs a TypeQL query with default options. See <<#_struct_Transaction_method_query_with_options,`Transaction::query_with_options`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result<QueryAnswer>>
----

[#_struct_Transaction_query_with_options_query_impl_AsRef_str_options_Options]
==== query_with_options

[source,rust]
----
pub fn query_with_options(
    &self,
    query: impl AsRef<str>,
    options: Options,
) -> impl Promise<'static, Result<QueryAnswer>>
----

Performs a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a|  — The TypeQL query to be executed a| `impl AsRef<str>`
a| `options` a|  — Query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result<QueryAnswer>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query_with_options(query, options)
----

[#_struct_Transaction_rollback_]
==== rollback

[source,rust]
----
pub fn rollback(&self) -> impl Promise<'_, Result>
----

Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
[source,rust]
----
impl Promise<'_, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.rollback().await
----

--

sync::
+
--
[source,rust]
----
transaction.rollback()
----

--
====

[#_struct_Transaction_type_]
==== type_

[source,rust]
----
pub fn type_(&self) -> TransactionType
----

Retrieves the transaction’s type (READ or WRITE).

[caption=""]
.Returns
[source,rust]
----
TransactionType
----

// end::methods[]

