[#_struct_TransactionOptions]
=== enum TransactionOptions

*Implements traits:*

* `Clone`
* `Copy`
* `Debug`
* `Default`

TypeDB transaction options. ``TransactionOptions`` object can be used to override the default server behaviour for opened transactions.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `schema_lock_acquire_timeout` a| `Option<Duration>` a| If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.
a| `transaction_timeout` a| `Option<Duration>` a| If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.
|===
// end::properties[]

// tag::methods[]
[#_struct_TransactionOptions_schema_lock_acquire_timeout_]
==== schema_lock_acquire_timeout

[source,rust]
----
pub fn schema_lock_acquire_timeout(self, timeout: Duration) -> Self
----

If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_TransactionOptions_transaction_timeout_]
==== transaction_timeout

[source,rust]
----
pub fn transaction_timeout(self, timeout: Duration) -> Self
----

If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
[source,rust]
----
Self
----

// end::methods[]

