[#_struct_Transaction]
=== Transaction

`Class(name=Transaction, anchor=struct_Transaction, enumConstants=[], description=[A transaction with a TypeDB database.], examples=[], fields=[], methods=[Method(name=is_open, signature=pub fn is_open(&self) -> bool, anchor=struct_Transaction_is_open_, args=[], description=[Closes the transaction.], examples=[transaction.close()], mode=async, returnDescription=null, returnType=bool), Method(name=query, signature=pub fn query(
    &self,
    query: impl AsRef<str>,
) -> impl Promise<'static, Result<QueryAnswer>>, anchor=struct_Transaction_query_, args=[], description=[Performs a TypeQL query with default options. See <<#_struct_Transaction_method_query_with_options,`Transaction::query_with_options`>>], examples=[], mode=async, returnDescription=null, returnType=impl Promise<'static, Result<QueryAnswer>>), Method(name=query_with_options, signature=pub fn query_with_options(
    &self,
    query: impl AsRef<str>,
    options: QueryOptions,
) -> impl Promise<'static, Result<QueryAnswer>>, anchor=struct_Transaction_query_with_options_query_impl_AsRef_str_options_QueryOptions, args=[Variable(name=query, anchor=null, defaultValue=null, description= — The TypeQL query to be executed, type=impl AsRef<str>), Variable(name=options, anchor=null, defaultValue=null, description= — The QueryOptions to execute the query with, type=QueryOptions)], description=[Performs a TypeQL query in this transaction.], examples=[transaction.query_with_options(query, options)], mode=async, returnDescription=null, returnType=impl Promise<'static, Result<QueryAnswer>>), Method(name=analyze, signature=pub fn analyze(
    &self,
    query: impl AsRef<str>,
) -> impl Promise<'static, Result<AnalyzedQuery>>, anchor=struct_Transaction_analyze_query_impl_AsRef_str_, args=[Variable(name=query, anchor=null, defaultValue=null, description= — The TypeQL query to be analyzed, type=impl AsRef<str>)], description=[Analyzes a TypeQL query in this transaction, returning the translated structure &amp; inferred types.], examples=[transaction.analyze(query)], mode=async, returnDescription=null, returnType=impl Promise<'static, Result<AnalyzedQuery>>), Method(name=type_, signature=pub fn type_(&self) -> TransactionType, anchor=struct_Transaction_type_, args=[], description=[Retrieves the transaction’s type (READ or WRITE).], examples=[], mode=async, returnDescription=null, returnType=TransactionType), Method(name=on_close, signature=pub fn on_close(
    &self,
    callback: impl FnOnce(Option<Error>) + Send + Sync + 'static,
) -> impl Promise<'_, Result<()>>, anchor=struct_Transaction_on_close_function, args=[Variable(name=function, anchor=null, defaultValue=null, description= — The callback function., type=null)], description=[Registers a callback function which will be executed when this transaction is closed returns a resolvable promise that must be awaited otherwise the callback may not be registered], examples=[transaction.on_close(function)], mode=async, returnDescription=null, returnType=impl Promise<'_, Result<()>>), Method(name=close, signature=pub fn close(&self) -> impl Promise<'_, Result<()>>, anchor=struct_Transaction_close_, args=[], description=[Closes the transaction and returns a resolvable promise], examples=[transaction.close().await], mode=async, returnDescription=null, returnType=impl Promise<'_, Result<()>>), Method(name=commit, signature=pub fn commit(self) -> impl Promise<'static, Result>, anchor=struct_Transaction_commit_, args=[], description=[Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.], examples=[transaction.commit().await], mode=async, returnDescription=null, returnType=impl Promise<'static, Result>), Method(name=rollback, signature=pub fn rollback(&self) -> impl Promise<'_, Result>, anchor=struct_Transaction_rollback_, args=[], description=[Rolls back the uncommitted changes made via this transaction.], examples=[transaction.rollback().await], mode=async, returnDescription=null, returnType=impl Promise<'_, Result>)], packagePath=null, superClasses=[Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Debug`

A transaction with a TypeDB database.

// tag::methods[]
[#_struct_Transaction_analyze_query_impl_AsRef_str_]
==== analyze

[source,rust]
----
pub fn analyze(
    &self,
    query: impl AsRef<str>,
) -> impl Promise<'static, Result<AnalyzedQuery>>
----

Analyzes a TypeQL query in this transaction, returning the translated structure &amp; inferred types.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a|  — The TypeQL query to be analyzed a| `impl AsRef<str>`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result<AnalyzedQuery>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.analyze(query)
----

[#_struct_Transaction_close_]
==== close

[source,rust]
----
pub fn close(&self) -> impl Promise<'_, Result<()>>
----

Closes the transaction and returns a resolvable promise

[caption=""]
.Returns
[source,rust]
----
impl Promise<'_, Result<()>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.close().await
----

--

sync::
+
--
[source,rust]
----
transaction.close().resolve()
----

--
====

[#_struct_Transaction_commit_]
==== commit

[source,rust]
----
pub fn commit(self) -> impl Promise<'static, Result>
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.commit().await
----

--

sync::
+
--
[source,rust]
----
transaction.commit()
----

--
====

[#_struct_Transaction_is_open_]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Closes the transaction.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
transaction.close()
----

[#_struct_Transaction_on_close_function]
==== on_close

[source,rust]
----
pub fn on_close(
    &self,
    callback: impl FnOnce(Option<Error>) + Send + Sync + 'static,
) -> impl Promise<'_, Result<()>>
----

Registers a callback function which will be executed when this transaction is closed returns a resolvable promise that must be awaited otherwise the callback may not be registered

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a|  — The callback function. a| 
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'_, Result<()>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.on_close(function)
----

[#_struct_Transaction_query_]
==== query

[source,rust]
----
pub fn query(
    &self,
    query: impl AsRef<str>,
) -> impl Promise<'static, Result<QueryAnswer>>
----

Performs a TypeQL query with default options. See <<#_struct_Transaction_method_query_with_options,`Transaction::query_with_options`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result<QueryAnswer>>
----

[#_struct_Transaction_query_with_options_query_impl_AsRef_str_options_QueryOptions]
==== query_with_options

[source,rust]
----
pub fn query_with_options(
    &self,
    query: impl AsRef<str>,
    options: QueryOptions,
) -> impl Promise<'static, Result<QueryAnswer>>
----

Performs a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a|  — The TypeQL query to be executed a| `impl AsRef<str>`
a| `options` a|  — The QueryOptions to execute the query with a| `QueryOptions`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'static, Result<QueryAnswer>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query_with_options(query, options)
----

[#_struct_Transaction_rollback_]
==== rollback

[source,rust]
----
pub fn rollback(&self) -> impl Promise<'_, Result>
----

Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
[source,rust]
----
impl Promise<'_, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.rollback().await
----

--

sync::
+
--
[source,rust]
----
transaction.rollback()
----

--
====

[#_struct_Transaction_type_]
==== type_

[source,rust]
----
pub fn type_(&self) -> TransactionType
----

Retrieves the transaction’s type (READ or WRITE).

[caption=""]
.Returns
[source,rust]
----
TransactionType
----

// end::methods[]

