[#_AnalyzedQuery]
=== AnalyzedQuery

`Class(name=AnalyzedQuery, anchor=AnalyzedQuery, enumConstants=[], description=[An AnalyzedQuery contains the server’s representation of the query and preamble functions; as well as the result of types inferred for each variable by type-inference.], examples=[], fields=[], methods=[Method(name=fetch, signature=fetch() -> 'Fetch' | None, anchor=AnalyzedQuery_fetch_, args=[], description=[A representation of the Fetch stage of the query, if it has one.], examples=[], mode=null, returnDescription=an Optional containing the fetch stage if present, otherwise None, returnType='Fetch' | None), Method(name=pipeline, signature=pipeline() -> Pipeline, anchor=AnalyzedQuery_pipeline_, args=[], description=[A representation of the query as a Pipeline.], examples=[], mode=null, returnDescription=the Pipeline representing the query., returnType=Pipeline), Method(name=preamble, signature=preamble() -> Iterator['Function'], anchor=AnalyzedQuery_preamble_, args=[], description=[A representation of the Functions in the preamble of the query.], examples=[], mode=null, returnDescription=an iterator over the analyzed functions in the preamble., returnType=Iterator['Function'])], packagePath=typedb.api.analyze.analyzed_query, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.analyzed_query`

An AnalyzedQuery contains the server’s representation of the query and preamble functions; as well as the result of types inferred for each variable by type-inference.

// tag::methods[]
[#_AnalyzedQuery_fetch_]
==== fetch

[source,python]
----
fetch() -> 'Fetch' | None
----

A representation of the Fetch stage of the query, if it has one.

[caption=""]
.Returns
`'Fetch' | None`

[#_AnalyzedQuery_pipeline_]
==== pipeline

[source,python]
----
pipeline() -> Pipeline
----

A representation of the query as a Pipeline.

[caption=""]
.Returns
`Pipeline`

[#_AnalyzedQuery_preamble_]
==== preamble

[source,python]
----
preamble() -> Iterator['Function']
----

A representation of the Functions in the preamble of the query.

[caption=""]
.Returns
`Iterator['Function']`

// end::methods[]

