[#_Comparison]
=== Comparison

`Class(name=Comparison, anchor=Comparison, enumConstants=[], description=[Represents a comparison: &lt;lhs&gt; &lt;comparator&gt; &lt;rhs&gt;], examples=[], fields=[], methods=[Method(name=comparator, signature=comparator() -> Comparator, anchor=Comparison_comparator_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Comparator), Method(name=lhs, signature=lhs() -> ConstraintVertex, anchor=Comparison_lhs_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=rhs, signature=rhs() -> ConstraintVertex, anchor=Comparison_rhs_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents a comparison: &lt;lhs&gt; &lt;comparator&gt; &lt;rhs&gt;

// tag::methods[]
[#_Comparison_comparator_]
==== comparator

[source,python]
----
comparator() -> Comparator
----



[caption=""]
.Returns
`Comparator`

[#_Comparison_lhs_]
==== lhs

[source,python]
----
lhs() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Comparison_rhs_]
==== rhs

[source,python]
----
rhs() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

