[#_ConstraintVertex]
=== ConstraintVertex

`Class(name=ConstraintVertex, anchor=ConstraintVertex, enumConstants=[], description=[The answer to a TypeDB query is a set of concepts which satisfy the constraints in the query. A ConstraintVertex is either a variable, or some identifier of the concept.], examples=[], fields=[], methods=[Method(name=as_label, signature=as_label() -> typedb.api.concept.type.type.Type, anchor=ConstraintVertex_as_label_, args=[], description=[Down-casts this vertex to a type label.], examples=[], mode=null, returnDescription=the type representation of this vertex, returnType=typedb.api.concept.type.type.Type), Method(name=as_named_role, signature=as_named_role() -> typedb.api.analyze.named_role.NamedRole, anchor=ConstraintVertex_as_named_role_, args=[], description=[Down-casts this vertex to a NamedRole. This is an internal variable injected to handle ambiguity in unscoped role-names.], examples=[], mode=null, returnDescription=, returnType=typedb.api.analyze.named_role.NamedRole), Method(name=as_value, signature=as_value() -> typedb.api.concept.value.value.Value, anchor=ConstraintVertex_as_value_, args=[], description=[Down-casts this vertex to a value.], examples=[], mode=null, returnDescription=, returnType=typedb.api.concept.value.value.Value), Method(name=as_variable, signature=as_variable() -> Variable, anchor=ConstraintVertex_as_variable_, args=[], description=[Down-casts this vertex to a variable.], examples=[], mode=null, returnDescription=, returnType=Variable), Method(name=is_label, signature=is_label() -> bool, anchor=ConstraintVertex_is_label_, args=[], description=[Checks if this vertex is a label.], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_named_role, signature=is_named_role() -> bool, anchor=ConstraintVertex_is_named_role_, args=[], description=[Checks if this vertex is a named role.], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_value, signature=is_value() -> bool, anchor=ConstraintVertex_is_value_, args=[], description=[Checks if this vertex is a value.], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_variable, signature=is_variable() -> bool, anchor=ConstraintVertex_is_variable_, args=[], description=[Checks if this vertex is a variable.], examples=[], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.analyze.constraint_vertex, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint_vertex`

The answer to a TypeDB query is a set of concepts which satisfy the constraints in the query. A ConstraintVertex is either a variable, or some identifier of the concept.

// tag::methods[]
[#_ConstraintVertex_as_label_]
==== as_label

[source,python]
----
as_label() -> typedb.api.concept.type.type.Type
----

Down-casts this vertex to a type label.

[caption=""]
.Returns
`typedb.api.concept.type.type.Type`

[#_ConstraintVertex_as_named_role_]
==== as_named_role

[source,python]
----
as_named_role() -> typedb.api.analyze.named_role.NamedRole
----

Down-casts this vertex to a NamedRole. This is an internal variable injected to handle ambiguity in unscoped role-names.

[caption=""]
.Returns
`typedb.api.analyze.named_role.NamedRole`

[#_ConstraintVertex_as_value_]
==== as_value

[source,python]
----
as_value() -> typedb.api.concept.value.value.Value
----

Down-casts this vertex to a value.

[caption=""]
.Returns
`typedb.api.concept.value.value.Value`

[#_ConstraintVertex_as_variable_]
==== as_variable

[source,python]
----
as_variable() -> Variable
----

Down-casts this vertex to a variable.

[caption=""]
.Returns
`Variable`

[#_ConstraintVertex_is_label_]
==== is_label

[source,python]
----
is_label() -> bool
----

Checks if this vertex is a label.

[caption=""]
.Returns
`bool`

[#_ConstraintVertex_is_named_role_]
==== is_named_role

[source,python]
----
is_named_role() -> bool
----

Checks if this vertex is a named role.

[caption=""]
.Returns
`bool`

[#_ConstraintVertex_is_value_]
==== is_value

[source,python]
----
is_value() -> bool
----

Checks if this vertex is a value.

[caption=""]
.Returns
`bool`

[#_ConstraintVertex_is_variable_]
==== is_variable

[source,python]
----
is_variable() -> bool
----

Checks if this vertex is a variable.

[caption=""]
.Returns
`bool`

// end::methods[]

