[#_Constraint]
=== Constraint

`Class(name=Constraint, anchor=Constraint, enumConstants=[], description=[A representation of a TypeQL constraint.], examples=[], fields=[], methods=[Method(name=as_comparison, signature=as_comparison() -> Comparison, anchor=Constraint_as_comparison_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Comparison), Method(name=as_expression, signature=as_expression() -> Expression, anchor=Constraint_as_expression_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Expression), Method(name=as_function_call, signature=as_function_call() -> FunctionCall, anchor=Constraint_as_function_call_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=FunctionCall), Method(name=as_has, signature=as_has() -> Has, anchor=Constraint_as_has_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Has), Method(name=as_iid, signature=as_iid() -> Iid, anchor=Constraint_as_iid_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Iid), Method(name=as_is, signature=as_is() -> Is, anchor=Constraint_as_is_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Is), Method(name=as_isa, signature=as_isa() -> Isa, anchor=Constraint_as_isa_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Isa), Method(name=as_kind, signature=as_kind() -> Kind, anchor=Constraint_as_kind_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Kind), Method(name=as_label, signature=as_label() -> Label, anchor=Constraint_as_label_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Label), Method(name=as_links, signature=as_links() -> Links, anchor=Constraint_as_links_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Links), Method(name=as_not, signature=as_not() -> Not, anchor=Constraint_as_not_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Not), Method(name=as_or, signature=as_or() -> Or, anchor=Constraint_as_or_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Or), Method(name=as_owns, signature=as_owns() -> Owns, anchor=Constraint_as_owns_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Owns), Method(name=as_plays, signature=as_plays() -> Plays, anchor=Constraint_as_plays_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Plays), Method(name=as_relates, signature=as_relates() -> Relates, anchor=Constraint_as_relates_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Relates), Method(name=as_sub, signature=as_sub() -> Sub, anchor=Constraint_as_sub_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Sub), Method(name=as_try, signature=as_try() -> Try, anchor=Constraint_as_try_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Try), Method(name=as_value, signature=as_value() -> Value, anchor=Constraint_as_value_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Value), Method(name=is_comparison, signature=is_comparison() -> bool, anchor=Constraint_is_comparison_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_expression, signature=is_expression() -> bool, anchor=Constraint_is_expression_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_function_call, signature=is_function_call() -> bool, anchor=Constraint_is_function_call_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_has, signature=is_has() -> bool, anchor=Constraint_is_has_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_iid, signature=is_iid() -> bool, anchor=Constraint_is_iid_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_is, signature=is_is() -> bool, anchor=Constraint_is_is_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_isa, signature=is_isa() -> bool, anchor=Constraint_is_isa_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_kind_of, signature=is_kind_of() -> bool, anchor=Constraint_is_kind_of_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_label, signature=is_label() -> bool, anchor=Constraint_is_label_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_links, signature=is_links() -> bool, anchor=Constraint_is_links_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_not, signature=is_not() -> bool, anchor=Constraint_is_not_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_or, signature=is_or() -> bool, anchor=Constraint_is_or_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_owns, signature=is_owns() -> bool, anchor=Constraint_is_owns_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_plays, signature=is_plays() -> bool, anchor=Constraint_is_plays_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_relates, signature=is_relates() -> bool, anchor=Constraint_is_relates_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_sub, signature=is_sub() -> bool, anchor=Constraint_is_sub_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_try, signature=is_try() -> bool, anchor=Constraint_is_try_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_value, signature=is_value() -> bool, anchor=Constraint_is_value_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=span, signature=span() -> Span, anchor=Constraint_span_, args=[], description=[Gets the span of this constraint in the source query.], examples=[], mode=null, returnDescription=, returnType=Span)], packagePath=typedb.api.analyze.constraint, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

A representation of a TypeQL constraint.

// tag::methods[]
[#_Constraint_as_comparison_]
==== as_comparison

[source,python]
----
as_comparison() -> Comparison
----



[caption=""]
.Returns
`Comparison`

[#_Constraint_as_expression_]
==== as_expression

[source,python]
----
as_expression() -> Expression
----



[caption=""]
.Returns
`Expression`

[#_Constraint_as_function_call_]
==== as_function_call

[source,python]
----
as_function_call() -> FunctionCall
----



[caption=""]
.Returns
`FunctionCall`

[#_Constraint_as_has_]
==== as_has

[source,python]
----
as_has() -> Has
----



[caption=""]
.Returns
`Has`

[#_Constraint_as_iid_]
==== as_iid

[source,python]
----
as_iid() -> Iid
----



[caption=""]
.Returns
`Iid`

[#_Constraint_as_is_]
==== as_is

[source,python]
----
as_is() -> Is
----



[caption=""]
.Returns
`Is`

[#_Constraint_as_isa_]
==== as_isa

[source,python]
----
as_isa() -> Isa
----



[caption=""]
.Returns
`Isa`

[#_Constraint_as_kind_]
==== as_kind

[source,python]
----
as_kind() -> Kind
----



[caption=""]
.Returns
`Kind`

[#_Constraint_as_label_]
==== as_label

[source,python]
----
as_label() -> Label
----



[caption=""]
.Returns
`Label`

[#_Constraint_as_links_]
==== as_links

[source,python]
----
as_links() -> Links
----



[caption=""]
.Returns
`Links`

[#_Constraint_as_not_]
==== as_not

[source,python]
----
as_not() -> Not
----



[caption=""]
.Returns
`Not`

[#_Constraint_as_or_]
==== as_or

[source,python]
----
as_or() -> Or
----



[caption=""]
.Returns
`Or`

[#_Constraint_as_owns_]
==== as_owns

[source,python]
----
as_owns() -> Owns
----



[caption=""]
.Returns
`Owns`

[#_Constraint_as_plays_]
==== as_plays

[source,python]
----
as_plays() -> Plays
----



[caption=""]
.Returns
`Plays`

[#_Constraint_as_relates_]
==== as_relates

[source,python]
----
as_relates() -> Relates
----



[caption=""]
.Returns
`Relates`

[#_Constraint_as_sub_]
==== as_sub

[source,python]
----
as_sub() -> Sub
----



[caption=""]
.Returns
`Sub`

[#_Constraint_as_try_]
==== as_try

[source,python]
----
as_try() -> Try
----



[caption=""]
.Returns
`Try`

[#_Constraint_as_value_]
==== as_value

[source,python]
----
as_value() -> Value
----



[caption=""]
.Returns
`Value`

[#_Constraint_is_comparison_]
==== is_comparison

[source,python]
----
is_comparison() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_expression_]
==== is_expression

[source,python]
----
is_expression() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_function_call_]
==== is_function_call

[source,python]
----
is_function_call() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_has_]
==== is_has

[source,python]
----
is_has() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_iid_]
==== is_iid

[source,python]
----
is_iid() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_is_]
==== is_is

[source,python]
----
is_is() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_isa_]
==== is_isa

[source,python]
----
is_isa() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_kind_of_]
==== is_kind_of

[source,python]
----
is_kind_of() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_label_]
==== is_label

[source,python]
----
is_label() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_links_]
==== is_links

[source,python]
----
is_links() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_not_]
==== is_not

[source,python]
----
is_not() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_or_]
==== is_or

[source,python]
----
is_or() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_owns_]
==== is_owns

[source,python]
----
is_owns() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_plays_]
==== is_plays

[source,python]
----
is_plays() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_relates_]
==== is_relates

[source,python]
----
is_relates() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_sub_]
==== is_sub

[source,python]
----
is_sub() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_try_]
==== is_try

[source,python]
----
is_try() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_is_value_]
==== is_value

[source,python]
----
is_value() -> bool
----



[caption=""]
.Returns
`bool`

[#_Constraint_span_]
==== span

[source,python]
----
span() -> Span
----

Gets the span of this constraint in the source query.

[caption=""]
.Returns
`Span`

// end::methods[]

