[#_DeleteStage]
=== DeleteStage

`Class(name=DeleteStage, anchor=DeleteStage, enumConstants=[], description=[Represents a ‘delete’ stage.], examples=[], fields=[], methods=[Method(name=block, signature=block() -> ConjunctionID, anchor=DeleteStage_block_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConjunctionID), Method(name=deleted_variables, signature=deleted_variables() -> Iterator['Variable'], anchor=DeleteStage_deleted_variables_, args=[], description=[The variables for which the unified concepts are to be deleted.], examples=[], mode=null, returnDescription=, returnType=Iterator['Variable'])], packagePath=typedb.api.analyze.pipeline_stage, superClasses=[PipelineStage], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.pipeline_stage`

*Supertypes:*

* `PipelineStage`

Represents a ‘delete’ stage.

// tag::methods[]
[#_DeleteStage_block_]
==== block

[source,python]
----
block() -> ConjunctionID
----



[caption=""]
.Returns
`ConjunctionID`

[#_DeleteStage_deleted_variables_]
==== deleted_variables

[source,python]
----
deleted_variables() -> Iterator['Variable']
----

The variables for which the unified concepts are to be deleted.

[caption=""]
.Returns
`Iterator['Variable']`

// end::methods[]

