[#_Expression]
=== Expression

`Class(name=Expression, anchor=Expression, enumConstants=[], description=[Represents an expression: let &lt;assigned&gt; = &lt;expression&gt;], examples=[], fields=[], methods=[Method(name=arguments, signature=arguments() -> Iterator['ConstraintVertex'], anchor=Expression_arguments_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Iterator['ConstraintVertex']), Method(name=assigned, signature=assigned() -> ConstraintVertex, anchor=Expression_assigned_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=text, signature=text() -> str, anchor=Expression_text_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=str)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents an expression: let &lt;assigned&gt; = &lt;expression&gt;

// tag::methods[]
[#_Expression_arguments_]
==== arguments

[source,python]
----
arguments() -> Iterator['ConstraintVertex']
----



[caption=""]
.Returns
`Iterator['ConstraintVertex']`

[#_Expression_assigned_]
==== assigned

[source,python]
----
assigned() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Expression_text_]
==== text

[source,python]
----
text() -> str
----



[caption=""]
.Returns
`str`

// end::methods[]

