[#_FetchObject]
=== FetchObject

`Class(name=FetchObject, anchor=FetchObject, enumConstants=[], description=[A mapping of string keys to Fetch documents.], examples=[], fields=[], methods=[Method(name=get, signature=get(key: str) -> Fetch, anchor=FetchObject_get_, args=[], description=[The Fetch object for the given key.], examples=[], mode=null, returnDescription=, returnType=Fetch), Method(name=keys, signature=keys() -> Iterator[str], anchor=FetchObject_keys_, args=[], description=[The available keys of this Fetch document.], examples=[], mode=null, returnDescription=, returnType=Iterator[str])], packagePath=typedb.api.analyze.fetch, superClasses=[Fetch], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.fetch`

*Supertypes:*

* `Fetch`

A mapping of string keys to Fetch documents.

// tag::methods[]
[#_FetchObject_get_]
==== get

[source,python]
----
get(key: str) -> Fetch
----

The Fetch object for the given key.

[caption=""]
.Returns
`Fetch`

[#_FetchObject_keys_]
==== keys

[source,python]
----
keys() -> Iterator[str]
----

The available keys of this Fetch document.

[caption=""]
.Returns
`Iterator[str]`

// end::methods[]

