[#_Function]
[.doc-api-reference-driver]
=== Function

`class`

*Package*: `typedb.api.analyze.function`

Holds a representation of a function, and the result of type-inference for each variable.

// tag::methods[]
[#_Function_argument_annotations_]
==== method <code>argument_annotations</code>

[source,python]
----
argument_annotations() -> Iterator['VariableAnnotations']
----

Gets the type annotations for each argument of the function.

[caption=""]
.Returns
`Iterator['VariableAnnotations']`

[#_Function_argument_variables_]
==== method <code>argument_variables</code>

[source,python]
----
argument_variables() -> Iterator['Variable']
----

Gets the variables which are the arguments of the function.

[caption=""]
.Returns
`Iterator['Variable']`

[#_Function_body_]
==== method <code>body</code>

[source,python]
----
body() -> Pipeline
----

Gets the pipeline which forms the body of the function.

[caption=""]
.Returns
`Pipeline`

[#_Function_return_annotations_]
==== method <code>return_annotations</code>

[source,python]
----
return_annotations() -> Iterator['VariableAnnotations']
----

Gets the type annotations for each concept returned by the function.

[caption=""]
.Returns
`Iterator['VariableAnnotations']`

[#_Function_return_operation_]
==== method <code>return_operation</code>

[source,python]
----
return_operation() -> ReturnOperation
----

Gets the return operation of the function.

[caption=""]
.Returns
`ReturnOperation`

// end::methods[]

