[#_Iid]
=== Iid

`Class(name=Iid, anchor=Iid, enumConstants=[], description=[Represents an IID constraint: &lt;concept&gt; iid &lt;iid&gt;], examples=[], fields=[], methods=[Method(name=iid, signature=iid() -> str, anchor=Iid_iid_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=str), Method(name=variable, signature=variable() -> ConstraintVertex, anchor=Iid_variable_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents an IID constraint: &lt;concept&gt; iid &lt;iid&gt;

// tag::methods[]
[#_Iid_iid_]
==== iid

[source,python]
----
iid() -> str
----



[caption=""]
.Returns
`str`

[#_Iid_variable_]
==== variable

[source,python]
----
variable() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

