[#_Is]
=== Is

`Class(name=Is, anchor=Is, enumConstants=[], description=[Represents an ‘is’ constraint: &lt;lhs&gt; is &lt;rhs&gt;], examples=[], fields=[], methods=[Method(name=lhs, signature=lhs() -> ConstraintVertex, anchor=Is_lhs_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=rhs, signature=rhs() -> ConstraintVertex, anchor=Is_rhs_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents an ‘is’ constraint: &lt;lhs&gt; is &lt;rhs&gt;

// tag::methods[]
[#_Is_lhs_]
==== lhs

[source,python]
----
lhs() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Is_rhs_]
==== rhs

[source,python]
----
rhs() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

