[#_Isa]
=== Isa

`Class(name=Isa, anchor=Isa, enumConstants=[], description=[Represents an ‘isa’ constraint: &lt;instance&gt; isa(!) &lt;type&gt;], examples=[], fields=[], methods=[Method(name=exactness, signature=exactness() -> ConstraintExactness, anchor=Isa_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintExactness), Method(name=instance, signature=instance() -> ConstraintVertex, anchor=Isa_instance_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=type, signature=type() -> ConstraintVertex, anchor=Isa_type_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents an ‘isa’ constraint: &lt;instance&gt; isa(!) &lt;type&gt;

// tag::methods[]
[#_Isa_exactness_]
==== exactness

[source,python]
----
exactness() -> ConstraintExactness
----



[caption=""]
.Returns
`ConstraintExactness`

[#_Isa_instance_]
==== instance

[source,python]
----
instance() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Isa_type_]
==== type

[source,python]
----
type() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

