[#_Links]
=== Links

`Class(name=Links, anchor=Links, enumConstants=[], description=[Represents a ‘links’ constraint: &lt;relation&gt; links (&lt;role&gt;: &lt;player&gt;)], examples=[], fields=[], methods=[Method(name=exactness, signature=exactness() -> ConstraintExactness, anchor=Links_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintExactness), Method(name=player, signature=player() -> ConstraintVertex, anchor=Links_player_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=relation, signature=relation() -> ConstraintVertex, anchor=Links_relation_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=role, signature=role() -> ConstraintVertex, anchor=Links_role_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents a ‘links’ constraint: &lt;relation&gt; links (&lt;role&gt;: &lt;player&gt;)

// tag::methods[]
[#_Links_exactness_]
==== exactness

[source,python]
----
exactness() -> ConstraintExactness
----



[caption=""]
.Returns
`ConstraintExactness`

[#_Links_player_]
==== player

[source,python]
----
player() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Links_relation_]
==== relation

[source,python]
----
relation() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Links_role_]
==== role

[source,python]
----
role() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

