[#_Owns]
=== Owns

`Class(name=Owns, anchor=Owns, enumConstants=[], description=[Represents an ‘owns’ constraint: &lt;owner&gt; owns &lt;attribute&gt;], examples=[], fields=[], methods=[Method(name=attribute, signature=attribute() -> ConstraintVertex, anchor=Owns_attribute_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=exactness, signature=exactness() -> ConstraintExactness, anchor=Owns_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintExactness), Method(name=owner, signature=owner() -> ConstraintVertex, anchor=Owns_owner_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents an ‘owns’ constraint: &lt;owner&gt; owns &lt;attribute&gt;

// tag::methods[]
[#_Owns_attribute_]
==== attribute

[source,python]
----
attribute() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Owns_exactness_]
==== exactness

[source,python]
----
exactness() -> ConstraintExactness
----



[caption=""]
.Returns
`ConstraintExactness`

[#_Owns_owner_]
==== owner

[source,python]
----
owner() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

