[#_PipelineStage]
=== PipelineStage

`Class(name=PipelineStage, anchor=PipelineStage, enumConstants=[], description=[Representation of a stage in a Pipeline.], examples=[], fields=[], methods=[Method(name=as_delete, signature=as_delete() -> DeleteStage, anchor=PipelineStage_as_delete_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=DeleteStage), Method(name=as_distinct, signature=as_distinct() -> DistinctStage, anchor=PipelineStage_as_distinct_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=DistinctStage), Method(name=as_insert, signature=as_insert() -> InsertStage, anchor=PipelineStage_as_insert_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=InsertStage), Method(name=as_limit, signature=as_limit() -> LimitStage, anchor=PipelineStage_as_limit_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=LimitStage), Method(name=as_match, signature=as_match() -> MatchStage, anchor=PipelineStage_as_match_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=MatchStage), Method(name=as_offset, signature=as_offset() -> OffsetStage, anchor=PipelineStage_as_offset_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=OffsetStage), Method(name=as_put, signature=as_put() -> PutStage, anchor=PipelineStage_as_put_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=PutStage), Method(name=as_reduce, signature=as_reduce() -> ReduceStage, anchor=PipelineStage_as_reduce_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ReduceStage), Method(name=as_require, signature=as_require() -> RequireStage, anchor=PipelineStage_as_require_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=RequireStage), Method(name=as_select, signature=as_select() -> SelectStage, anchor=PipelineStage_as_select_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=SelectStage), Method(name=as_sort, signature=as_sort() -> SortStage, anchor=PipelineStage_as_sort_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=SortStage), Method(name=as_update, signature=as_update() -> UpdateStage, anchor=PipelineStage_as_update_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=UpdateStage), Method(name=is_delete, signature=is_delete() -> bool, anchor=PipelineStage_is_delete_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_distinct, signature=is_distinct() -> bool, anchor=PipelineStage_is_distinct_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_insert, signature=is_insert() -> bool, anchor=PipelineStage_is_insert_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_limit, signature=is_limit() -> bool, anchor=PipelineStage_is_limit_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_match, signature=is_match() -> bool, anchor=PipelineStage_is_match_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_offset, signature=is_offset() -> bool, anchor=PipelineStage_is_offset_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_put, signature=is_put() -> bool, anchor=PipelineStage_is_put_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_reduce, signature=is_reduce() -> bool, anchor=PipelineStage_is_reduce_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_require, signature=is_require() -> bool, anchor=PipelineStage_is_require_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_select, signature=is_select() -> bool, anchor=PipelineStage_is_select_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_sort, signature=is_sort() -> bool, anchor=PipelineStage_is_sort_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_update, signature=is_update() -> bool, anchor=PipelineStage_is_update_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.analyze.pipeline_stage, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.pipeline_stage`

Representation of a stage in a Pipeline.

// tag::methods[]
[#_PipelineStage_as_delete_]
==== as_delete

[source,python]
----
as_delete() -> DeleteStage
----



[caption=""]
.Returns
`DeleteStage`

[#_PipelineStage_as_distinct_]
==== as_distinct

[source,python]
----
as_distinct() -> DistinctStage
----



[caption=""]
.Returns
`DistinctStage`

[#_PipelineStage_as_insert_]
==== as_insert

[source,python]
----
as_insert() -> InsertStage
----



[caption=""]
.Returns
`InsertStage`

[#_PipelineStage_as_limit_]
==== as_limit

[source,python]
----
as_limit() -> LimitStage
----



[caption=""]
.Returns
`LimitStage`

[#_PipelineStage_as_match_]
==== as_match

[source,python]
----
as_match() -> MatchStage
----



[caption=""]
.Returns
`MatchStage`

[#_PipelineStage_as_offset_]
==== as_offset

[source,python]
----
as_offset() -> OffsetStage
----



[caption=""]
.Returns
`OffsetStage`

[#_PipelineStage_as_put_]
==== as_put

[source,python]
----
as_put() -> PutStage
----



[caption=""]
.Returns
`PutStage`

[#_PipelineStage_as_reduce_]
==== as_reduce

[source,python]
----
as_reduce() -> ReduceStage
----



[caption=""]
.Returns
`ReduceStage`

[#_PipelineStage_as_require_]
==== as_require

[source,python]
----
as_require() -> RequireStage
----



[caption=""]
.Returns
`RequireStage`

[#_PipelineStage_as_select_]
==== as_select

[source,python]
----
as_select() -> SelectStage
----



[caption=""]
.Returns
`SelectStage`

[#_PipelineStage_as_sort_]
==== as_sort

[source,python]
----
as_sort() -> SortStage
----



[caption=""]
.Returns
`SortStage`

[#_PipelineStage_as_update_]
==== as_update

[source,python]
----
as_update() -> UpdateStage
----



[caption=""]
.Returns
`UpdateStage`

[#_PipelineStage_is_delete_]
==== is_delete

[source,python]
----
is_delete() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_distinct_]
==== is_distinct

[source,python]
----
is_distinct() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_insert_]
==== is_insert

[source,python]
----
is_insert() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_limit_]
==== is_limit

[source,python]
----
is_limit() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_match_]
==== is_match

[source,python]
----
is_match() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_offset_]
==== is_offset

[source,python]
----
is_offset() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_put_]
==== is_put

[source,python]
----
is_put() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_reduce_]
==== is_reduce

[source,python]
----
is_reduce() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_require_]
==== is_require

[source,python]
----
is_require() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_select_]
==== is_select

[source,python]
----
is_select() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_sort_]
==== is_sort

[source,python]
----
is_sort() -> bool
----



[caption=""]
.Returns
`bool`

[#_PipelineStage_is_update_]
==== is_update

[source,python]
----
is_update() -> bool
----



[caption=""]
.Returns
`bool`

// end::methods[]

