[#_ReduceStage]
=== ReduceStage

`Class(name=ReduceStage, anchor=ReduceStage, enumConstants=[], description=[Represents a ‘reduce’ stage: reduce &lt;reducers&gt; groupby &lt;groupby&gt;], examples=[], fields=[], methods=[Method(name=group_by, signature=group_by() -> Iterator['Variable'], anchor=ReduceStage_group_by_, args=[], description=[The variables to group by.], examples=[], mode=null, returnDescription=, returnType=Iterator['Variable']), Method(name=reduce_assignments, signature=reduce_assignments() -> Iterator[ReduceAssignment], anchor=ReduceStage_reduce_assignments_, args=[], description=[The reducer assignments.], examples=[], mode=null, returnDescription=, returnType=Iterator[ReduceAssignment])], packagePath=typedb.api.analyze.pipeline_stage, superClasses=[PipelineStage], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.pipeline_stage`

*Supertypes:*

* `PipelineStage`

Represents a ‘reduce’ stage: reduce &lt;reducers&gt; groupby &lt;groupby&gt;

// tag::methods[]
[#_ReduceStage_group_by_]
==== group_by

[source,python]
----
group_by() -> Iterator['Variable']
----

The variables to group by.

[caption=""]
.Returns
`Iterator['Variable']`

[#_ReduceStage_reduce_assignments_]
==== reduce_assignments

[source,python]
----
reduce_assignments() -> Iterator[ReduceAssignment]
----

The reducer assignments.

[caption=""]
.Returns
`Iterator[ReduceAssignment]`

// end::methods[]

