[#_ReduceAssignment]
=== ReduceAssignment

`Class(name=ReduceAssignment, anchor=ReduceAssignment, enumConstants=[], description=[An assignment of a reducer to a variable.], examples=[], fields=[], methods=[Method(name=assigned, signature=assigned() -> Variable, anchor=ReduceAssignment_assigned_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Variable), Method(name=reducer, signature=reducer() -> Reducer, anchor=ReduceAssignment_reducer_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Reducer)], packagePath=typedb.api.analyze.pipeline_stage.ReduceStage, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.pipeline_stage.ReduceStage`

An assignment of a reducer to a variable.

// tag::methods[]
[#_ReduceAssignment_assigned_]
==== assigned

[source,python]
----
assigned() -> Variable
----



[caption=""]
.Returns
`Variable`

[#_ReduceAssignment_reducer_]
==== reducer

[source,python]
----
reducer() -> Reducer
----



[caption=""]
.Returns
`Reducer`

// end::methods[]

