[#_Relates]
=== Relates

`Class(name=Relates, anchor=Relates, enumConstants=[], description=[Represents a ‘relates’ constraint: &lt;relation&gt; relates &lt;role&gt;], examples=[], fields=[], methods=[Method(name=exactness, signature=exactness() -> ConstraintExactness, anchor=Relates_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintExactness), Method(name=relation, signature=relation() -> ConstraintVertex, anchor=Relates_relation_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=role, signature=role() -> ConstraintVertex, anchor=Relates_role_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents a ‘relates’ constraint: &lt;relation&gt; relates &lt;role&gt;

// tag::methods[]
[#_Relates_exactness_]
==== exactness

[source,python]
----
exactness() -> ConstraintExactness
----



[caption=""]
.Returns
`ConstraintExactness`

[#_Relates_relation_]
==== relation

[source,python]
----
relation() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Relates_role_]
==== role

[source,python]
----
role() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

