[#_ReturnOperationSingle]
=== ReturnOperationSingle

`Class(name=ReturnOperationSingle, anchor=ReturnOperationSingle, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=selector, signature=selector() -> str, anchor=ReturnOperationSingle_selector_, args=[], description=[Gets the selector that determines how the operation selects the row.], examples=[], mode=null, returnDescription=, returnType=str), Method(name=variables, signature=variables() -> Iterator['Variable'], anchor=ReturnOperationSingle_variables_, args=[], description=[Gets the variables in the returned row.], examples=[], mode=null, returnDescription=, returnType=Iterator['Variable'])], packagePath=typedb.api.analyze.function, superClasses=[ReturnOperation], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.function`

*Supertypes:*

* `ReturnOperation`

// tag::methods[]
[#_ReturnOperationSingle_selector_]
==== selector

[source,python]
----
selector() -> str
----

Gets the selector that determines how the operation selects the row.

[caption=""]
.Returns
`str`

[#_ReturnOperationSingle_variables_]
==== variables

[source,python]
----
variables() -> Iterator['Variable']
----

Gets the variables in the returned row.

[caption=""]
.Returns
`Iterator['Variable']`

// end::methods[]

