[#_ReturnOperation]
=== ReturnOperation

`Class(name=ReturnOperation, anchor=ReturnOperation, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=as_check, signature=as_check() -> ReturnOperationCheck, anchor=ReturnOperation_as_check_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ReturnOperationCheck), Method(name=as_reduce, signature=as_reduce() -> ReturnOperationReduce, anchor=ReturnOperation_as_reduce_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ReturnOperationReduce), Method(name=as_single, signature=as_single() -> ReturnOperationSingle, anchor=ReturnOperation_as_single_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ReturnOperationSingle), Method(name=as_stream, signature=as_stream() -> ReturnOperationStream, anchor=ReturnOperation_as_stream_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ReturnOperationStream), Method(name=is_check, signature=is_check() -> bool, anchor=ReturnOperation_is_check_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_reduce, signature=is_reduce() -> bool, anchor=ReturnOperation_is_reduce_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_single, signature=is_single() -> bool, anchor=ReturnOperation_is_single_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_stream, signature=is_stream() -> bool, anchor=ReturnOperation_is_stream_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.analyze.function, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.function`

// tag::methods[]
[#_ReturnOperation_as_check_]
==== as_check

[source,python]
----
as_check() -> ReturnOperationCheck
----



[caption=""]
.Returns
`ReturnOperationCheck`

[#_ReturnOperation_as_reduce_]
==== as_reduce

[source,python]
----
as_reduce() -> ReturnOperationReduce
----



[caption=""]
.Returns
`ReturnOperationReduce`

[#_ReturnOperation_as_single_]
==== as_single

[source,python]
----
as_single() -> ReturnOperationSingle
----



[caption=""]
.Returns
`ReturnOperationSingle`

[#_ReturnOperation_as_stream_]
==== as_stream

[source,python]
----
as_stream() -> ReturnOperationStream
----



[caption=""]
.Returns
`ReturnOperationStream`

[#_ReturnOperation_is_check_]
==== is_check

[source,python]
----
is_check() -> bool
----



[caption=""]
.Returns
`bool`

[#_ReturnOperation_is_reduce_]
==== is_reduce

[source,python]
----
is_reduce() -> bool
----



[caption=""]
.Returns
`bool`

[#_ReturnOperation_is_single_]
==== is_single

[source,python]
----
is_single() -> bool
----



[caption=""]
.Returns
`bool`

[#_ReturnOperation_is_stream_]
==== is_stream

[source,python]
----
is_stream() -> bool
----



[caption=""]
.Returns
`bool`

// end::methods[]

