[#_SortVariable]
=== SortVariable

`Class(name=SortVariable, anchor=SortVariable, enumConstants=[], description=[A variable and its sort order.], examples=[], fields=[], methods=[Method(name=order, signature=order() -> SortOrder, anchor=SortVariable_order_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=SortOrder), Method(name=variable, signature=variable() -> Variable, anchor=SortVariable_variable_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=Variable)], packagePath=typedb.api.analyze.pipeline_stage.SortStage, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.pipeline_stage.SortStage`

A variable and its sort order.

// tag::methods[]
[#_SortVariable_order_]
==== order

[source,python]
----
order() -> SortOrder
----



[caption=""]
.Returns
`SortOrder`

[#_SortVariable_variable_]
==== variable

[source,python]
----
variable() -> Variable
----



[caption=""]
.Returns
`Variable`

// end::methods[]

