[#_Sub]
=== Sub

`Class(name=Sub, anchor=Sub, enumConstants=[], description=[Represents a ‘sub’ constraint: &lt;subtype&gt; sub(!) &lt;supertype&gt;], examples=[], fields=[], methods=[Method(name=exactness, signature=exactness() -> ConstraintExactness, anchor=Sub_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintExactness), Method(name=subtype, signature=subtype() -> ConstraintVertex, anchor=Sub_subtype_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=supertype, signature=supertype() -> ConstraintVertex, anchor=Sub_supertype_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents a ‘sub’ constraint: &lt;subtype&gt; sub(!) &lt;supertype&gt;

// tag::methods[]
[#_Sub_exactness_]
==== exactness

[source,python]
----
exactness() -> ConstraintExactness
----



[caption=""]
.Returns
`ConstraintExactness`

[#_Sub_subtype_]
==== subtype

[source,python]
----
subtype() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Sub_supertype_]
==== supertype

[source,python]
----
supertype() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

// end::methods[]

