[#_Value]
=== Value

`Class(name=Value, anchor=Value, enumConstants=[], description=[Represents a value constraint: &lt;attribute_type&gt; value &lt;value_type&gt;], examples=[], fields=[], methods=[Method(name=attribute_type, signature=attribute_type() -> ConstraintVertex, anchor=Value_attribute_type_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=ConstraintVertex), Method(name=value_type, signature=value_type() -> str, anchor=Value_value_type_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=str)], packagePath=typedb.api.analyze.constraint, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.constraint`

*Supertypes:*

* `Constraint`

Represents a value constraint: &lt;attribute_type&gt; value &lt;value_type&gt;

// tag::methods[]
[#_Value_attribute_type_]
==== attribute_type

[source,python]
----
attribute_type() -> ConstraintVertex
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Value_value_type_]
==== value_type

[source,python]
----
value_type() -> str
----



[caption=""]
.Returns
`str`

// end::methods[]

