[#_VariableAnnotations]
=== VariableAnnotations

`Class(name=VariableAnnotations, anchor=VariableAnnotations, enumConstants=[], description=[Holds typing information about a variable (instance/type/value annotations).], examples=[], fields=[], methods=[Method(name=as_instance, signature=as_instance() -> Iterator['Type'], anchor=VariableAnnotations_as_instance_, args=[], description=[The possible Types of instances this variable can hold.], examples=[], mode=null, returnDescription=, returnType=Iterator['Type']), Method(name=as_type, signature=as_type() -> Iterator['Type'], anchor=VariableAnnotations_as_type_, args=[], description=[The possible types this variable can hold.], examples=[], mode=null, returnDescription=, returnType=Iterator['Type']), Method(name=as_value, signature=as_value() -> Iterator[str], anchor=VariableAnnotations_as_value_, args=[], description=[The possible ValueType(s) of values this variable can hold.], examples=[], mode=null, returnDescription=, returnType=Iterator[str]), Method(name=is_instance, signature=is_instance() -> bool, anchor=VariableAnnotations_is_instance_, args=[], description=[Returns True if this variable is an Instance variable.], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_type, signature=is_type() -> bool, anchor=VariableAnnotations_is_type_, args=[], description=[Returns True if this variable is a Type variable.], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_value, signature=is_value() -> bool, anchor=VariableAnnotations_is_value_, args=[], description=[Returns True if this variable is a Value variable.], examples=[], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.analyze.variable_annotations, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.analyze.variable_annotations`

Holds typing information about a variable (instance/type/value annotations).

// tag::methods[]
[#_VariableAnnotations_as_instance_]
==== as_instance

[source,python]
----
as_instance() -> Iterator['Type']
----

The possible Types of instances this variable can hold.

[caption=""]
.Returns
`Iterator['Type']`

[#_VariableAnnotations_as_type_]
==== as_type

[source,python]
----
as_type() -> Iterator['Type']
----

The possible types this variable can hold.

[caption=""]
.Returns
`Iterator['Type']`

[#_VariableAnnotations_as_value_]
==== as_value

[source,python]
----
as_value() -> Iterator[str]
----

The possible ValueType(s) of values this variable can hold.

[caption=""]
.Returns
`Iterator[str]`

[#_VariableAnnotations_is_instance_]
==== is_instance

[source,python]
----
is_instance() -> bool
----

Returns True if this variable is an Instance variable.

[caption=""]
.Returns
`bool`

[#_VariableAnnotations_is_type_]
==== is_type

[source,python]
----
is_type() -> bool
----

Returns True if this variable is a Type variable.

[caption=""]
.Returns
`bool`

[#_VariableAnnotations_is_value_]
==== is_value

[source,python]
----
is_value() -> bool
----

Returns True if this variable is a Value variable.

[caption=""]
.Returns
`bool`

// end::methods[]

