[#_Options]
=== Options

*Package*: `TypeDB`



TypeDB Session and Transaction options.

``Options`` can be used to override the default server behaviour.

// tag::methods[]
[#_a43fba027bc2e111b49b5a931ccd7c159]
==== Options

[source,cpp]
----
TypeDB::Options::Options()
----



Produces a new ``Options`` object.


[caption=""]
.Returns
`TypeDB::Options::Options`

[#_a25eba1c41df7bd92dffc934718639732]
==== explain

[source,cpp]
----
std::optional<bool> TypeDB::Options::explain()
----



Returns the value set for the explanation in this ``TypeDBOptions`` object. If set to ``true``, explanations for queries are enabled.


[caption=""]
.Returns
`std::optional< bool >`

[#_a4b9eddb9257d037ae8132806328f62a5]
==== explain

[source,cpp]
----
Options& TypeDB::Options::explain(bool explain)
----



Explicitly enables or disables explanations. If set to ``true``, enables explanations for queries. Only affects read transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explain` a| Explicitly enable or disable explanations a| 
|===

[caption=""]
.Returns
`Options&`

[#_a628c4b22a7c58af816cf48b8474f1320]
==== infer

[source,cpp]
----
std::optional<bool> TypeDB::Options::infer()
----



Returns the value set for the inference in this ``TypeDBOptions`` object.


[caption=""]
.Returns
`std::optional< bool >`

[#_a95609d81c02401bb12d1434db88080cc]
==== infer

[source,cpp]
----
Options& TypeDB::Options::infer(bool infer)
----



Explicitly enables or disables inference. Only settable at transaction level and above. Only affects read transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `infer` a| Explicitly enable or disable inference a| 
|===

[caption=""]
.Returns
`Options&`

[#_a5d40c07960a9560cd8873415f1b3b578]
==== parallel

[source,cpp]
----
std::optional<bool> TypeDB::Options::parallel()
----



Returns the value set for the parallel execution in this ``TypeDBOptions`` object. If set to ``true``, the server uses parallel instead of single-threaded execution.


[caption=""]
.Returns
`std::optional< bool >`

[#_ac978aeb54c431c4558b5cb21f0ee41a2]
==== parallel

[source,cpp]
----
Options& TypeDB::Options::parallel(bool parallel)
----



Explicitly enables or disables parallel execution. If set to ``true``, the server uses parallel instead of single-threaded execution.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `parallel` a| Explicitly enable or disable parallel execution a| 
|===

[caption=""]
.Returns
`Options&`

[#_a9daa488dfb58b9a9634e2272de9eaf5a]
==== prefetch

[source,cpp]
----
std::optional<bool> TypeDB::Options::prefetch()
----



Returns the value set for the prefetching in this ``TypeDBOptions`` object. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it.


[caption=""]
.Returns
`std::optional< bool >`

[#_a033e3bc9a27a83d401a6bb67a7ecd971]
==== prefetch

[source,cpp]
----
Options& TypeDB::Options::prefetch(bool prefetch)
----



Explicitly enables or disables prefetching. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `prefetch` a| Explicitly enable or disable prefetching a| 
|===

[caption=""]
.Returns
`Options&`

[#_ac1d57dd513acdee4868369bd44723f98]
==== prefetchSize

[source,cpp]
----
std::optional<int32_t> TypeDB::Options::prefetchSize()
----



Returns the value set for the prefetch size in this ``TypeDBOptions`` object. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.


[caption=""]
.Returns
`std::optional< int32_t >`

[#_a3fe142577420f0d1c1f2a5f8df6eb0f3]
==== prefetchSize

[source,cpp]
----
Options& TypeDB::Options::prefetchSize(int32_t prefetchSize)
----



Explicitly sets a prefetch size. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `prefetchSize` a| Number of answers that the server should send before the driver issues a fresh request a| 
|===

[caption=""]
.Returns
`Options&`

[#_a65b5c4a88cffc056bcbbf1e1740d1b24]
==== readAnyReplica

[source,cpp]
----
std::optional<bool> TypeDB::Options::readAnyReplica()
----



Returns the value set for reading data from any replica in this ``TypeDBOptions`` object. If set to ``True``, enables reading data from any replica, potentially boosting read throughput.


[caption=""]
.Returns
`std::optional< bool >`

[#_ad02332d37a10f90fef9e35cd2e537264]
==== readAnyReplica

[source,cpp]
----
Options& TypeDB::Options::readAnyReplica(bool readAnyReplica)
----



Explicitly enables or disables reading data from any replica. If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `readAnyReplica` a| Explicitly enable or disable reading data from any replica a| 
|===

[caption=""]
.Returns
`Options&`

[#_a0dde0c8ffa6d70c3184cc2b14e85d0a9]
==== schemaLockAcquireTimeoutMillis

[source,cpp]
----
std::optional<int64_t> TypeDB::Options::schemaLockAcquireTimeoutMillis()
----



Returns the value set for the schema lock acquire timeout in this ``TypeDBOptions`` object. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.


[caption=""]
.Returns
`std::optional< int64_t >`

[#_ac2e2656da85fe30c9d67032184b5403f]
==== schemaLockAcquireTimeoutMillis

[source,cpp]
----
Options& TypeDB::Options::schemaLockAcquireTimeoutMillis(int64_t timeoutMillis)
----



Explicitly sets schema lock acquire timeout. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `schemaLockAcquireTimeoutMillis` a| How long the driver should wait if opening a session or transaction is blocked by a schema write lock a| 
|===

[caption=""]
.Returns
`Options&`

[#_a5c4d52c50cf9703f464b8041b80312f8]
==== sessionIdleTimeoutMillis

[source,cpp]
----
std::optional<int64_t> TypeDB::Options::sessionIdleTimeoutMillis()
----



Returns the value set for the session idle timeout in this ``TypeDBOptions`` object. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.


[caption=""]
.Returns
`std::optional< int64_t >`

[#_a3d9fddc7c9d8b13eec1ca21dd465ff36]
==== sessionIdleTimeoutMillis

[source,cpp]
----
Options& TypeDB::Options::sessionIdleTimeoutMillis(int64_t timeoutMillis)
----



Explicitly sets a session idle timeout. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `sessionIdleTimeoutMillis` a| timeout that allows the server to close sessions if the driver terminates or becomes unresponsive a| 
|===

[caption=""]
.Returns
`Options&`

[#_ac395d1712502cee629884ebcfa16573b]
==== traceInference

[source,cpp]
----
std::optional<bool> TypeDB::Options::traceInference()
----



Returns the value set for reasoning tracing in this ``TypeDBOptions`` object. If set to ``true``, reasoning tracing graphs are output in the logging directory.


[caption=""]
.Returns
`std::optional< bool >`

[#_a70d8c7436bb86fa36ba45289a7d08216]
==== traceInference

[source,cpp]
----
Options& TypeDB::Options::traceInference(bool traceInference)
----



Explicitly enables or disables reasoning tracing. If set to ``true``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `traceInference` a| Explicitly enable or disable reasoning tracing a| 
|===

[caption=""]
.Returns
`Options&`

[#_ac592e89ce3d29725e81b40d3fbd9b980]
==== transactionTimeoutMillis

[source,cpp]
----
std::optional<int64_t> TypeDB::Options::transactionTimeoutMillis()
----



Returns the value set for the transaction timeout in this ``TypeDBOptions`` object. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.


[caption=""]
.Returns
`std::optional< int64_t >`

[#_a8d2f0fc6edeeec82013c828e084dbb22]
==== transactionTimeoutMillis

[source,cpp]
----
Options& TypeDB::Options::transactionTimeoutMillis(int64_t timeoutMillis)
----



Explicitly set a transaction timeout. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transactionTimeoutMillis` a| Timeout for killing transactions automatically a| 
|===

[caption=""]
.Returns
`Options&`

// end::methods[]

