[#_Session]
=== Session

*Package*: `TypeDB`



A session with a TypeDB database.

// tag::methods[]
[#_void_TypeDBSessionclose___]
==== close

[source,cpp]
----
void TypeDB::Session::close()
----



Closes the session. Before opening a new session, the session currently open should first be closed.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
session.close();
----

[#_stdstring_TypeDBSessiondatabaseName_____const]
==== databaseName

[source,cpp]
----
std::string TypeDB::Session::databaseName() const
----



Returns the name of the database of the session.


[caption=""]
.Returns
`std::string`

[caption=""]
.Code examples
[source,cpp]
----
session.databaseName();
----

[#_bool_TypeDBSessionisOpen_____const]
==== isOpen

[source,cpp]
----
bool TypeDB::Session::isOpen() const
----



Checks whether this session is open.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
session.isOpen();
----

[#_void_TypeDBSessiononClose___stdfunction__void____callback_]
==== onClose

[source,cpp]
----
void TypeDB::Session::onClose(std::function< void()> callback)
----



Registers a callback function which will be executed when this session is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
session.onClose(function)
----

[#_void_TypeDBSessiononReopen___stdfunction__void____callback_]
==== onReopen

[source,cpp]
----
void TypeDB::Session::onReopen(std::function< void()> callback)
----



Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
session.onReopen(function)
----

[#_Transaction_TypeDBSessiontransaction___TransactionType_type__const_Options__options__Options_____const]
==== transaction

[source,cpp]
----
Transaction TypeDB::Session::transaction(TransactionType type, const Options& options = Options()) const
----



Opens a transaction to perform read or write queries on the database connected to the session.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `type` a| The type of transaction to be created (READ or WRITE) a| `TransactionType`
a| `options` a| Options for the session a| 
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,cpp]
----
session.transaction(transactionType, options);
----

[#_SessionType_TypeDBSessiontype_____const]
==== type

[source,cpp]
----
SessionType TypeDB::Session::type() const
----



The current session’s type (SCHEMA or DATA)

[caption=""]
.Returns
`SessionType`

// end::methods[]

