[#_struct_RoleType]
=== RoleType

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq<RoleType>`
* `RoleTypeAPI`
* `StructuralEq`
* `StructuralPartialEq`

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type.

Roles allow a schema to enforce logical constraints on types of role players.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `is_abstract` a| `bool` a| 
a| `is_root` a| `bool` a| 
a| `label` a| `ScopedLabel` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_RoleType_delete__]
==== delete

[source,rust]
----
fn delete<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_RoleTypeAPI_method_delete,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_RoleType_get_player_instances__]
==== get_player_instances

[source,rust]
----
fn get_player_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Thing>>>
----

<<#_trait_RoleTypeAPI_method_get_player_instances,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Thing>>>
----

[#_struct_RoleType_get_player_types__]
==== get_player_types

[source,rust]
----
fn get_player_types<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<ThingType>>>
----

<<#_trait_RoleTypeAPI_method_get_player_types,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<ThingType>>>
----

[#_struct_RoleType_get_relation_instances__]
==== get_relation_instances

[source,rust]
----
fn get_relation_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Relation>>>
----

<<#_trait_RoleTypeAPI_method_get_relation_instances,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Relation>>>
----

[#_struct_RoleType_get_relation_type__]
==== get_relation_type

[source,rust]
----
fn get_relation_type<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<RelationType>>>
----

<<#_trait_RoleTypeAPI_tymethod_get_relation_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RelationType>>>
----

[#_struct_RoleType_get_relation_types__]
==== get_relation_types

[source,rust]
----
fn get_relation_types<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RelationType>>>
----

<<#_trait_RoleTypeAPI_method_get_relation_types,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RelationType>>>
----

[#_struct_RoleType_get_subtypes__]
==== get_subtypes

[source,rust]
----
fn get_subtypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_RoleTypeAPI_method_get_subtypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_RoleType_get_supertype__]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

<<#_trait_RoleTypeAPI_method_get_supertype,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[#_struct_RoleType_get_supertypes__]
==== get_supertypes

[source,rust]
----
fn get_supertypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_RoleTypeAPI_method_get_supertypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_RoleType_is_abstract__]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

<<#_trait_RoleTypeAPI_tymethod_is_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_RoleType_is_deleted__]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

<<#_trait_RoleTypeAPI_tymethod_is_deleted,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[#_struct_RoleType_set_label__]
==== set_label

[source,rust]
----
fn set_label<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    new_label: String
) -> BoxPromise<'tx, Result>
----

<<#_trait_RoleTypeAPI_method_set_label,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

// end::methods[]

