[#_trait_RoleTypeAPI]
=== Trait RoleTypeAPI

*Implementors:*

* `RoleType`

// tag::methods[]
[#_trait_RoleTypeAPI_method_delete]
==== delete

[source,rust]
----
fn delete<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
role_type.delete(transaction).await;
----

--

sync::
+
--
[source,rust]
----
role_type.delete(transaction).resolve();
----

--
====

[#_trait_RoleTypeAPI_method_get_player_instances]
==== get_player_instances

[source,rust]
----
fn get_player_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Thing>>>
----

Retrieves the ``Thing`` instances that play this role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect playing, ``Transitivity::Explicit`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Thing>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_player_instances(transaction, transitivity)
----

[#_trait_RoleTypeAPI_method_get_player_types]
==== get_player_types

[source,rust]
----
fn get_player_types(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<ThingType>>>
----

Retrieves the ``ThingType``s whose instances play this role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect playing, ``Transitivity::Explicit`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<ThingType>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_player_types(transaction, transitivity)
----

[#_trait_RoleTypeAPI_method_get_relation_instances]
==== get_relation_instances

[source,rust]
----
fn get_relation_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Relation>>>
----

Retrieves the ``Relation`` instances that this role is related to.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect relation, ``Transitivity::Explicit`` for direct relation only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Relation>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_relation_instances(transaction, transitivity)
----

[#_trait_RoleTypeAPI_tymethod_get_relation_type]
==== get_relation_type

[source,rust]
----
fn get_relation_type<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result<Option<RelationType>>>
----

Retrieves the ``RelationType`` that this role is directly related to.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RelationType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
role_type.get_relation_type(transaction).await;
----

--

sync::
+
--
[source,rust]
----
role_type.get_relation_type(transaction).resolve();
----

--
====

[#_trait_RoleTypeAPI_method_get_relation_types]
==== get_relation_types

[source,rust]
----
fn get_relation_types(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RelationType>>>
----

Retrieves ``RelationType``s that this role is related to (directly or indirectly).

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RelationType>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_relation_types(transaction)
----

[#_trait_RoleTypeAPI_method_get_subtypes]
==== get_subtypes

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_subtypes(transaction, transitivity)
----

[#_trait_RoleTypeAPI_method_get_supertype]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

Retrieves the most immediate supertype of the ``RoleType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
role_type.get_supertype(transaction).await;
----

--

sync::
+
--
[source,rust]
----
role_type.get_supertype(transaction).resolve();
----

--
====

[#_trait_RoleTypeAPI_method_get_supertypes]
==== get_supertypes

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RoleType>>>
----

Retrieves all supertypes of the ``RoleType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[caption=""]
.Code examples
[source,rust]
----
role_type.get_supertypes(transaction)
----

[#_trait_RoleTypeAPI_tymethod_is_abstract]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

Checks if the type is prevented from having data instances (i.e., ``abstract``).

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
role_type.is_abstract()
----

[#_trait_RoleTypeAPI_tymethod_is_deleted]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result<bool>>
----

Checks if this type is deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
role_type.is_deleted(transaction).await;
----

--

sync::
+
--
[source,rust]
----
role_type.is_deleted(transaction).resolve();
----

--
====

[#_trait_RoleTypeAPI_method_set_label]
==== set_label

[source,rust]
----
fn set_label<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>,
    new_label: String
) -> BoxPromise<'tx, Result>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'tx>`
a| `new_label` a| The new ``Label`` to be given to the type. a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
role_type.set_label(transaction, new_label).await;
----

--

sync::
+
--
[source,rust]
----
role_type.set_label(transaction, new_label).resolve();
----

--
====

// end::methods[]

