[#_trait_RelationTypeAPI]
=== Trait RelationTypeAPI

*Implementors:*

* `RelationType`

// tag::methods[]
[#_trait_RelationTypeAPI_create__transaction_tx_Transaction___]
==== create

[source,rust]
----
fn create<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Relation>>
----

Creates and returns an instance of this ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Relation>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.create(transaction).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.create(transaction).resolve();
----

--
====

[#_trait_RelationTypeAPI_get_instances__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_instances

[source,rust]
----
fn get_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Relation>>>
----

Retrieves all direct and indirect (or direct only) ``Relation``s that are instances of this ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect instances, ``Transitivity::Explicit`` for direct relates only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Relation>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation_type.get_instances(transaction, Transitivity::Explicit);
----

[#_trait_RelationTypeAPI_get_relates__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_relates

[source,rust]
----
fn get_relates<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and inherited relates, ``Transitivity::Explicit`` for direct relates only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation_type.get_relates(transaction, Transitivity::Transitive);
----

[#_trait_RelationTypeAPI_get_relates_for_role_label__transaction_tx_Transaction_____role_label_String]
==== get_relates_for_role_label

[source,rust]
----
fn get_relates_for_role_label<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    role_label: String
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

Retrieves role with a given ``role_label`` that this ``RelationType`` relates to.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_label` a| Label of the role we wish to retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.get_relates_for_role_label(transaction, role_label).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.get_relates_for_role_label(transaction, role_label).resolve();
----

--
====

[#_trait_RelationTypeAPI_get_relates_overridden__transaction_tx_Transaction_____overridden_role_label_String]
==== get_relates_overridden

[source,rust]
----
fn get_relates_overridden<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    overridden_role_label: String
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

Retrieves a ``RoleType`` that is overridden by the role with the ``overridden_role_label``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `overridden_role_label` a| Label of the role that overrides an inherited role a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.get_relates_overridden(transaction, overridden_role_label).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.get_relates_overridden(transaction, overridden_role_label).resolve();
----

--
====

[#_trait_RelationTypeAPI_get_subtypes__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_subtypes

[source,rust]
----
fn get_subtypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<RelationType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RelationType>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation_type.get_subtypes(transaction, Transitivity::Transitive);
----

[#_trait_RelationTypeAPI_get_supertype__transaction_tx_Transaction___]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<RelationType>>>
----

Retrieves the most immediate supertype of the ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RelationType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.get_supertype(transaction).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.get_supertype(transaction).resolve();
----

--
====

[#_trait_RelationTypeAPI_get_supertypes__transaction_tx_Transaction___]
==== get_supertypes

[source,rust]
----
fn get_supertypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<RelationType>>>
----

Retrieves all supertypes of the ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RelationType>>>
----

[caption=""]
.Code examples
[source,rust]
----
relation_type.get_supertypes(transaction);
----

[#_trait_RelationTypeAPI_set_relates__transaction_tx_Transaction_____role_label_String__overridden_role_label_Option_String_]
==== set_relates

[source,rust]
----
fn set_relates<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_label: String,
    overridden_role_label: Option<String>
) -> BoxPromise<'tx, Result>
----

Sets the new role that this ``RelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_label` a| The new role for the ``RelationType`` to relate to a| `String`
a| `overridden_role_label` a| The label being overridden, if applicable a| `Option<String>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.set_relates(transaction, role_label, None).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.set_relates(transaction, role_label, None).resolve();
----

--
====

[#_trait_RelationTypeAPI_set_supertype__transaction_tx_Transaction_____supertype_RelationType]
==== set_supertype

[source,rust]
----
fn set_supertype<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    supertype: RelationType
) -> BoxPromise<'tx, Result>
----

Sets the supplied ``RelationType`` as the supertype of the current ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `supertype` a| The ``RelationType`` to set as the supertype of this ``RelationType`` a| `RelationType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.set_supertype(transaction, super_relation_type).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.set_supertype(transaction, super_relation_type).resolve();
----

--
====

[#_trait_RelationTypeAPI_unset_relates__transaction_tx_Transaction_____role_label_String]
==== unset_relates

[source,rust]
----
fn unset_relates<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_label: String
) -> BoxPromise<'tx, Result>
----

Disallows this ``RelationType`` from relating to the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_label` a| The role to not relate to the relation type. a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
relation_type.unset_relates(transaction, role_label).await;
----

--

sync::
+
--
[source,rust]
----
relation_type.unset_relates(transaction, role_label).resolve();
----

--
====

// end::methods[]

