[#_trait_EntityTypeAPI]
=== Trait EntityTypeAPI

*Implementors:*

* `EntityType`

// tag::methods[]
[#_trait_EntityTypeAPI_method_create]
==== create

[tabs]
====
async::
+
--
[source,rust]
----
fn create<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<Entity>> + Send + 'async_trait>>
where
     Self: Sync + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn create(&self, transaction: &Transaction<'_>) -> Result<Entity>
----

--
====

Creates and returns a new instance of this ``EntityType``.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result<Entity>> + Send + 'async_trait>>
where
     Self: Sync + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result<Entity>
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.create(transaction).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.create(transaction);
----

--
====

[#_trait_EntityTypeAPI_method_get_instances]
==== get_instances

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Entity>>>
----

Retrieves all direct and indirect (or direct only) ``Entity`` objects that are instances of this ``EntityType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect instances, ``Transitivity::Explicit`` for direct instances only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Entity>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.get_instances(transaction, Transitivity::Explicit).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.get_instances(transaction, Transitivity::Explicit);
----

--
====

[#_trait_EntityTypeAPI_method_get_subtypes]
==== get_subtypes

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<EntityType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.get_subtypes(transaction, transitivity).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.get_subtypes(transaction, transitivity);
----

--
====

[#_trait_EntityTypeAPI_method_get_supertype]
==== get_supertype

[tabs]
====
async::
+
--
[source,rust]
----
fn get_supertype<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<Option<EntityType>>> + Send + 'async_trait>>
where
     Self: Sync + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<EntityType>>
----

--
====

Retrieves the most immediate supertype of the ``EntityType``.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result<Option<EntityType>>> + Send + 'async_trait>>
where
     Self: Sync + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result<Option<EntityType>>
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.get_supertype(transaction).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.get_supertype(transaction);
----

--
====

[#_trait_EntityTypeAPI_method_get_supertypes]
==== get_supertypes

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<EntityType>>>
----

Retrieves all supertypes of the ``EntityType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.get_supertypes(transaction).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.get_supertypes(transaction);
----

--
====

[#_trait_EntityTypeAPI_method_set_supertype]
==== set_supertype

[tabs]
====
async::
+
--
[source,rust]
----
fn set_supertype<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 mut self,
    transaction: &'life1 Transaction<'life2>,
    supertype: EntityType
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: Send + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: EntityType
) -> Result
----

--
====

Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>`
a| `supertype` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `supertype` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: Send + 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.set_supertype(transaction, super_entity_type).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.set_supertype(transaction, super_entity_type);
----

--
====

// end::methods[]

