[#_trait_ThingTypeAPI]
=== Trait ThingTypeAPI

*Implementors:*

* `AttributeType`
* `EntityType`
* `RelationType`
* `RootThingType`

// tag::methods[]
[#_trait_ThingTypeAPI_delete__transaction_tx_Transaction___]
==== delete

[source,rust]
----
fn delete<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.delete(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.delete(transaction).resolve();
----

--
====

[#_trait_ThingTypeAPI_get_owns__transaction_tx_Transaction_____value_type_Option_ValueType___transitivity_Transitivity__annotations_Vec_Annotation_]
==== get_owns

[source,rust]
----
fn get_owns<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `value_type` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Option<ValueType>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and inherited ownership, ``Transitivity::Explicit`` for direct ownership only a| `Transitivity`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Vec<Annotation>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.get_owns(transaction, Some(value_type), Transitivity::Explicit, vec![Annotation::Key]).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.get_owns(transaction, Some(value_type), Transitivity::Explicit, vec![Annotation::Key]);
----

--
====

[#_trait_ThingTypeAPI_get_owns_overridden__transaction_tx_Transaction_____overridden_attribute_type_AttributeType]
==== get_owns_overridden

[source,rust]
----
fn get_owns_overridden<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> BoxPromise<'tx, Result<Option<AttributeType>>>
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `overridden_attribute_type` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<AttributeType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.get_owns_overridden(transaction, attribute_type).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.get_owns_overridden(transaction, attribute_type).resolve();
----

--
====

[#_trait_ThingTypeAPI_get_plays__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_plays

[source,rust]
----
fn get_plays<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect playing, ``Transitivity::Explicit`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.get_plays(transaction, Transitivity::Explicit).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.get_plays(transaction, Transitivity::Explicit).resolve();
----

--
====

[#_trait_ThingTypeAPI_get_plays_overridden__transaction_tx_Transaction_____overridden_role_type_RoleType]
==== get_plays_overridden

[source,rust]
----
fn get_plays_overridden<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    overridden_role_type: RoleType
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `overridden_role_type` a| The ``RoleType`` that overrides an inherited role a| `RoleType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.get_plays_overridden(transaction, role_type).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.get_plays_overridden(transaction, role_type).resolve();
----

--
====

[#_trait_ThingTypeAPI_get_syntax__transaction_tx_Transaction___]
==== get_syntax

[source,rust]
----
fn get_syntax<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<String>>
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<String>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.get_syntax(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.get_syntax(transaction).resolve();
----

--
====

[#_trait_ThingTypeAPI_is_abstract__]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

Checks if the type is prevented from having data instances (i.e. ``abstract``).

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
thing_type.is_abstract();
----

[#_trait_ThingTypeAPI_is_deleted__transaction_tx_Transaction___]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

Checks if this type is deleted.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.is_deleted(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.is_deleted(transaction).resolve();
----

--
====

[#_trait_ThingTypeAPI_is_root__]
==== is_root

[source,rust]
----
fn is_root(&self) -> bool
----

Checks if the type is a root type.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
thing_type.is_root();
----

[#_trait_ThingTypeAPI_label__]
==== label

[source,rust]
----
fn label(&self) -> &str
----

Retrieves the unique label of the type.

[caption=""]
.Returns
[source,rust]
----
&str
----

[caption=""]
.Code examples
[source,rust]
----
thing_type.label();
----

[#_trait_ThingTypeAPI_set_abstract__transaction_tx_Transaction___]
==== set_abstract

[source,rust]
----
fn set_abstract<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

Set a type to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.set_abstract(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.set_abstract(transaction).resolve();
----

--
====

[#_trait_ThingTypeAPI_set_label__transaction_tx_Transaction_____new_label_String]
==== set_label

[source,rust]
----
fn set_label<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    new_label: String
) -> BoxPromise<'tx, Result>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `new_label` a| The new ``Label`` to be given to the type. a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.set_label(transaction, new_label).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.set_label(transaction, new_label).resolve();
----

--
====

[#_trait_ThingTypeAPI_set_owns__transaction_tx_Transaction_____attribute_type_AttributeType__overridden_attribute_type_Option_AttributeType___annotations_Vec_Annotation_]
==== set_owns

[source,rust]
----
fn set_owns<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> BoxPromise<'tx, Result>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `attribute_type` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overridden_attribute_type` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `Option<AttributeType>`
a| `annotations` a| Adds annotations to the ownership. a| `Vec<Annotation>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.set_owns(transaction, attribute_type, Some(overridden_type), vec![Annotation::Key]).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.set_owns(transaction, attribute_type, Some(overridden_type), vec![Annotation::Key]);
----

--
====

[#_trait_ThingTypeAPI_set_plays__transaction_tx_Transaction_____role_type_RoleType__overridden_role_type_Option_RoleType_]
==== set_plays

[source,rust]
----
fn set_plays<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> BoxPromise<'tx, Result>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_type` a| The role to be played by the instances of this type a| `RoleType`
a| `overridden_role_type` a| The role type that this role overrides, if applicable a| `Option<RoleType>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.set_plays(transaction, role_type, None).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.set_plays(transaction, role_type, None).resolve();
----

--
====

[#_trait_ThingTypeAPI_unset_abstract__transaction_tx_Transaction___]
==== unset_abstract

[source,rust]
----
fn unset_abstract<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

Set a type to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.unset_abstract(transaction).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.unset_abstract(transaction).resolve();
----

--
====

[#_trait_ThingTypeAPI_unset_owns__transaction_tx_Transaction_____attribute_type_AttributeType]
==== unset_owns

[source,rust]
----
fn unset_owns<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    attribute_type: AttributeType
) -> BoxPromise<'tx, Result>
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `attribute_type` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.unset_owns(transaction, attribute_type).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.unset_owns(transaction, attribute_type).resolve();
----

--
====

[#_trait_ThingTypeAPI_unset_plays__transaction_tx_Transaction_____role_type_RoleType]
==== unset_plays

[source,rust]
----
fn unset_plays<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType
) -> BoxPromise<'tx, Result>
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `role_type` a| The role to not be played by the instances of this type. a| `RoleType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
thing_type.unset_plays(transaction, role_type).await;
----

--

sync::
+
--
[source,rust]
----
thing_type.unset_plays(transaction, role_type).resolve();
----

--
====

// end::methods[]

