[#_trait_AttributeTypeAPI]
=== Trait AttributeTypeAPI

*Implementors:*

* `AttributeType`

// tag::methods[]
[#_trait_AttributeTypeAPI_get__transaction_tx_Transaction_____value_Value]
==== get

[source,rust]
----
fn get<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value: Value
) -> BoxPromise<'tx, Result<Option<Attribute>>>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `value` a| ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<Attribute>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute = attribute_type.get(transaction, value).await;
----

--

sync::
+
--
[source,rust]
----
attribute = attribute_type.get(transaction, value).resolve();
----

--
====

[#_trait_AttributeTypeAPI_get_instances__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_instances

[source,rust]
----
fn get_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Attribute>>>
----

Retrieves all direct and indirect (or direct only) ``Attributes`` that are instances of this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Attribute>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_instances(transaction, transitivity)
----

[#_trait_AttributeTypeAPI_get_owners__transaction_tx_Transaction_____transitivity_Transitivity__annotations_Vec_Annotation_]
==== get_owners

[source,rust]
----
fn get_owners<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<ThingType>>>
----

Retrieve all ``Things`` that own an attribute of this ``AttributeType`` and have all given ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and inherited ownership, ``Transitivity::Explicit`` for direct ownership only a| `Transitivity`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``AttributeType`` with all given ``Annotation``s a| `Vec<Annotation>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<ThingType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_owners(transaction, transitivity, annotations)
----

[#_trait_AttributeTypeAPI_get_regex__transaction_tx_Transaction___]
==== get_regex

[source,rust]
----
fn get_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<String>>>
----

Retrieves the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<String>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute_type.get_regex(transaction).await;
----

--

sync::
+
--
[source,rust]
----
attribute_type.get_regex(transaction).resolve();
----

--
====

[#_trait_AttributeTypeAPI_get_subtypes__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_subtypes

[source,rust]
----
fn get_subtypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_subtypes(transaction, transitivity)
----

[#_trait_AttributeTypeAPI_get_subtypes_with_value_type__transaction_tx_Transaction_____value_type_ValueType__transitivity_Transitivity]
==== get_subtypes_with_value_type

[source,rust]
----
fn get_subtypes_with_value_type<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value_type: ValueType,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType`` with given ``ValueType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `value_type` a| ``ValueType`` for retrieving subtypes a| `ValueType`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_subtypes_with_value_type(transaction, value_type, transitivity)
----

[#_trait_AttributeTypeAPI_get_supertype__transaction_tx_Transaction___]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<AttributeType>>>
----

Retrieves the most immediate supertype of this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<AttributeType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute_type.get_supertype(transaction).await;
----

--

sync::
+
--
[source,rust]
----
attribute_type.get_supertype(transaction).resolve();
----

--
====

[#_trait_AttributeTypeAPI_get_supertypes__transaction_tx_Transaction___]
==== get_supertypes

[source,rust]
----
fn get_supertypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

Retrieves all supertypes of this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_supertypes(transaction)
----

[#_trait_AttributeTypeAPI_put__transaction_tx_Transaction_____value_Value]
==== put

[source,rust]
----
fn put<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value: Value
) -> BoxPromise<'tx, Result<Attribute>>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `value` a| New ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Attribute>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute = attribute_type.put(transaction, value).await;
----

--

sync::
+
--
[source,rust]
----
attribute = attribute_type.put(transaction, value).resolve();
----

--
====

[#_trait_AttributeTypeAPI_set_regex__transaction_tx_Transaction_____regex_String]
==== set_regex

[source,rust]
----
fn set_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    regex: String
) -> BoxPromise<'tx, Result>
----

Sets a regular expression as a constraint for this ``AttributeType``. ``Values`` of all ``Attribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``AttributeType``s with a ``string`` value type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `regex` a| Regular expression a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute_type.set_regex(transaction, regex).await;
----

--

sync::
+
--
[source,rust]
----
attribute_type.set_regex(transaction, regex).resolve();
----

--
====

[#_trait_AttributeTypeAPI_set_supertype__transaction_tx_Transaction_____supertype_AttributeType]
==== set_supertype

[source,rust]
----
fn set_supertype<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    supertype: AttributeType
) -> BoxPromise<'tx, Result>
----

Sets the supplied ``AttributeType`` as the supertype of the current ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `supertype` a| The ``AttributeType`` to set as the supertype of this ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute_type.set_supertype(transaction, supertype).await;
----

--

sync::
+
--
[source,rust]
----
attribute_type.set_supertype(transaction, supertype).resolve();
----

--
====

[#_trait_AttributeTypeAPI_unset_regex__transaction_tx_Transaction___]
==== unset_regex

[source,rust]
----
fn unset_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

Removes the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
attribute_type.unset_regex(transaction).await;
----

--

sync::
+
--
[source,rust]
----
attribute_type.unset_regex(transaction).resolve();
----

--
====

[#_trait_AttributeTypeAPI_value_type__]
==== value_type

[source,rust]
----
fn value_type(&self) -> ValueType
----

Retrieves the ``ValueType`` of this ``AttributeType``.

[caption=""]
.Returns
[source,rust]
----
ValueType
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.value_type()
----

// end::methods[]

