[#_trait_EntityTypeAPI]
=== Trait EntityTypeAPI

*Implementors:*

* `EntityType`

// tag::methods[]
[#_trait_EntityTypeAPI_create__transaction_tx_Transaction___]
==== create

[source,rust]
----
fn create<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Entity>>
----

Creates and returns a new instance of this ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Entity>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.create(transaction).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.create(transaction).resolve();
----

--
====

[#_trait_EntityTypeAPI_get_instances__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_instances

[source,rust]
----
fn get_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Entity>>>
----

Retrieves all direct and indirect (or direct only) ``Entity`` objects that are instances of this ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect instances, ``Transitivity::Explicit`` for direct instances only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Entity>>>
----

[caption=""]
.Code examples
[source,rust]
----
entity_type.get_instances(transaction, Transitivity::Explicit);
----

[#_trait_EntityTypeAPI_get_subtypes__transaction_tx_Transaction_____transitivity_Transitivity]
==== get_subtypes

[source,rust]
----
fn get_subtypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<EntityType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<EntityType>>>
----

[caption=""]
.Code examples
[source,rust]
----
entity_type.get_subtypes(transaction, Transitivity::Transitive);
----

[#_trait_EntityTypeAPI_get_supertype__transaction_tx_Transaction___]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<EntityType>>>
----

Retrieves the most immediate supertype of the ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<EntityType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.get_supertype(transaction).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.get_supertype(transaction).resolve();
----

--
====

[#_trait_EntityTypeAPI_get_supertypes__transaction_tx_Transaction___]
==== get_supertypes

[source,rust]
----
fn get_supertypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<EntityType>>>
----

Retrieves all supertypes of the ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<EntityType>>>
----

[caption=""]
.Code examples
[source,rust]
----
entity_type.get_supertypes(transaction);
----

[#_trait_EntityTypeAPI_set_supertype__transaction_tx_Transaction_____supertype_EntityType]
==== set_supertype

[source,rust]
----
fn set_supertype<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    supertype: EntityType
) -> BoxPromise<'tx, Result>
----

Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'tx Transaction<'_>`
a| `supertype` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
entity_type.set_supertype(transaction, super_entity_type).await;
----

--

sync::
+
--
[source,rust]
----
entity_type.set_supertype(transaction, super_entity_type).resolve();
----

--
====

// end::methods[]

