[#_methods_concept_concept]
=== concept

[#_Struct_Concept]
[.doc-api-reference-driver]
==== Struct Concept

`rust struct (pointer)`



The fundamental TypeQL object.

[#_concept_drop]
==== function <code>concept_drop</code>

[source,c]
----
void concept_drop(struct Concept* concept)
----



Frees the native rust ``Concept`` object

[caption=""]
.Returns
`void`

[#_concept_equals]
==== function <code>concept_equals</code>

[source,c]
----
bool concept_equals(const struct Concept* lhs, const struct Concept* rhs)
----



Checks whether the provided ``Concept`` objects are equal

[caption=""]
.Returns
`bool`

[#_concept_get_boolean]
==== function <code>concept_get_boolean</code>

[source,c]
----
bool concept_get_boolean(const struct Concept* concept)
----



Returns a ``boolean`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`bool`

[#_concept_get_date_as_seconds]
==== function <code>concept_get_date_as_seconds</code>

[source,c]
----
int64_t concept_get_date_as_seconds(const struct Concept* concept)
----



Returns the value of this date value concept as seconds since the start of the UNIX epoch. If the value has another type, the error is set.

[caption=""]
.Returns
`int64_t`

[#_concept_get_datetime]
==== function <code>concept_get_datetime</code>

[source,c]
----
struct DatetimeInNanos concept_get_datetime(const struct Concept* concept)
----



Returns the value of this datetime value concept as seconds and nanoseconds parts since the start of the UNIX epoch. If the value has another type, the error is set.

[caption=""]
.Returns
`struct DatetimeInNanos`

[#_concept_get_datetime_tz]
==== function <code>concept_get_datetime_tz</code>

[source,c]
----
struct DatetimeAndTimeZone concept_get_datetime_tz(const struct Concept* concept)
----



Returns the value of this datetime-tz value concept as seconds and nanoseconds parts since the start of the UNIX epoch and timezone information. If the value has another type, the error is set.

[caption=""]
.Returns
`struct DatetimeAndTimeZone`

[#_concept_get_decimal]
==== function <code>concept_get_decimal</code>

[source,c]
----
struct Decimal concept_get_decimal(const struct Concept* concept)
----



Returns the ``decimal`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`struct Decimal`

[#_concept_get_double]
==== function <code>concept_get_double</code>

[source,c]
----
double concept_get_double(const struct Concept* concept)
----



Returns the ``double`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`double`

[#_concept_get_duration]
==== function <code>concept_get_duration</code>

[source,c]
----
struct Duration concept_get_duration(const struct Concept* concept)
----



Returns the value of this duration value. If the value has another type, the error is set.

[caption=""]
.Returns
`struct Duration`

[#_concept_get_integer]
==== function <code>concept_get_integer</code>

[source,c]
----
int64_t concept_get_integer(const struct Concept* concept)
----



Returns the ``integer`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`int64_t`

[#_concept_get_label]
==== function <code>concept_get_label</code>

[source,c]
----
char* concept_get_label(const struct Concept* concept)
----



Retrieves the label of this ``Concept``. If this is an ``Instance``, returns the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, returns the label of the value type of the value. If this is a ``Type``, returns the label of the type.

[caption=""]
.Returns
`char*`

[#_concept_get_string]
==== function <code>concept_get_string</code>

[source,c]
----
char* concept_get_string(const struct Concept* concept)
----



Returns the ``string`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`char*`

[#_concept_get_struct]
==== function <code>concept_get_struct</code>

[source,c]
----
struct StringAndOptValueIterator* concept_get_struct(const struct Concept* concept)
----



Returns the value of this struct value concept represented as an iterator of {field_name: value?} pairs. If the value has another type, the error is set.

[caption=""]
.Returns
`struct StringAndOptValueIterator*`

[#_concept_is_attribute]
==== function <code>concept_is_attribute</code>

[source,c]
----
bool concept_is_attribute(const struct Concept* concept)
----



Checks if this ``Concept`` is an ``Attribute``.

[caption=""]
.Returns
`bool`

[#_concept_is_attribute_type]
==== function <code>concept_is_attribute_type</code>

[source,c]
----
bool concept_is_attribute_type(const struct Concept* concept)
----



Checks if this ``Concept`` is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[#_concept_is_boolean]
==== function <code>concept_is_boolean</code>

[source,c]
----
bool concept_is_boolean(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_date]
==== function <code>concept_is_date</code>

[source,c]
----
bool concept_is_date(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``date``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_datetime]
==== function <code>concept_is_datetime</code>

[source,c]
----
bool concept_is_datetime(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_datetime_tz]
==== function <code>concept_is_datetime_tz</code>

[source,c]
----
bool concept_is_datetime_tz(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_decimal]
==== function <code>concept_is_decimal</code>

[source,c]
----
bool concept_is_decimal(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_double]
==== function <code>concept_is_double</code>

[source,c]
----
bool concept_is_double(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``double``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_duration]
==== function <code>concept_is_duration</code>

[source,c]
----
bool concept_is_duration(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``duration``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_entity]
==== function <code>concept_is_entity</code>

[source,c]
----
bool concept_is_entity(const struct Concept* concept)
----



Checks if this ``Concept`` is an ``Entity``.

[caption=""]
.Returns
`bool`

[#_concept_is_entity_type]
==== function <code>concept_is_entity_type</code>

[source,c]
----
bool concept_is_entity_type(const struct Concept* concept)
----



Checks if this ``Concept`` is an ``EntityType``.

[caption=""]
.Returns
`bool`

[#_concept_is_integer]
==== function <code>concept_is_integer</code>

[source,c]
----
bool concept_is_integer(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``integer``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_relation]
==== function <code>concept_is_relation</code>

[source,c]
----
bool concept_is_relation(const struct Concept* concept)
----



Checks if this ``Concept`` is a ``Relation``.

[caption=""]
.Returns
`bool`

[#_concept_is_relation_type]
==== function <code>concept_is_relation_type</code>

[source,c]
----
bool concept_is_relation_type(const struct Concept* concept)
----



Checks if this ``Concept`` is a ``RelationType``.

[caption=""]
.Returns
`bool`

[#_concept_is_role_type]
==== function <code>concept_is_role_type</code>

[source,c]
----
bool concept_is_role_type(const struct Concept* concept)
----



Checks if this ``Concept`` is a ``RoleType``.

[caption=""]
.Returns
`bool`

[#_concept_is_string]
==== function <code>concept_is_string</code>

[source,c]
----
bool concept_is_string(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``string``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_struct]
==== function <code>concept_is_struct</code>

[source,c]
----
bool concept_is_struct(const struct Concept* concept)
----



Returns ``true`` if the value which this ``Concept`` holds is of type ``struct``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_concept_is_value]
==== function <code>concept_is_value</code>

[source,c]
----
bool concept_is_value(const struct Concept* concept)
----



Checks if this ``Concept`` is a ``Value``.

[caption=""]
.Returns
`bool`

[#_concept_to_string]
==== function <code>concept_to_string</code>

[source,c]
----
char* concept_to_string(const struct Concept* concept)
----



A string representation of this ``Concept`` object.

[caption=""]
.Returns
`char*`

[#_concept_try_get_iid]
==== function <code>concept_try_get_iid</code>

[source,c]
----
char* concept_try_get_iid(struct Concept* instance)
----



Retrieves the unique id (IID) of this ``Concept``. If this is an Entity or Relation Instance, returns the IID of the instance. Otherwise, returns null.

[caption=""]
.Returns
`char*`

[#_concept_try_get_label]
==== function <code>concept_try_get_label</code>

[source,c]
----
char* concept_try_get_label(const struct Concept* concept)
----



Retrieves the optional label of this ``Concept``. If this is an ``Instance``, returns the label of the type of this instance (None if type fetching is disabled). If this is a ``Value``, returns the label of the value type of the value. If this is a ``Type``, returns the label of the type.

[caption=""]
.Returns
`char*`

[#_concept_try_get_value]
==== function <code>concept_try_get_value</code>

[source,c]
----
struct Concept* concept_try_get_value(const struct Concept* concept)
----



Retrieves the value of this ``Concept``, if it exists. If this is an ``Attribute`` instance, returns the value of this instance. If this a ``Value``, returns the value. Otherwise, returns null.

[caption=""]
.Returns
`struct Concept*`

[#_concept_try_get_value_type]
==== function <code>concept_try_get_value_type</code>

[source,c]
----
char* concept_try_get_value_type(const struct Concept* concept)
----



Retrieves the value type of this ``Concept``, if it exists. If this is an ``Attribute`` instance, returns the value type of this instance. If this is a ``Value``, returns its value type. If this is an ``AttributeType``, returns the value type that the schema permits for the attribute type, if one is defined. Otherwise, returns null.

[caption=""]
.Returns
`char*`

