[#_methods_concept_datetimeandtimezone]
=== datetimeandtimezone

[#_Struct_DatetimeAndTimeZone]
==== Struct DatetimeAndTimeZone

`Class(name=Struct DatetimeAndTimeZone, anchor=Struct_DatetimeAndTimeZone, enumConstants=[], description=[, A ``DatetimeAndTimeZone`` used to represent time zoned datetime in FFI. Time zone can be represented either as an IANA ``Tz`` or as a ``FixedOffset``. Either the zone_name (is_fixed_offset == false) or offset (is_fixed_offset == true) is set.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



A ``DatetimeAndTimeZone`` used to represent time zoned datetime in FFI. Time zone can be represented either as an IANA ``Tz`` or as a ``FixedOffset``. Either the zone_name (is_fixed_offset == false) or offset (is_fixed_offset == true) is set.

[#_datetime_and_time_zone_drop]
==== datetime_and_time_zone_drop

[source,cpp]
----
void datetime_and_time_zone_drop(struct DatetimeAndTimeZone* datetime_tz)
----



Frees the native rust ``DatetimeAndTimeZone`` object

[caption=""]
.Returns
`void`

