[#_methods_concept_kind]
=== kind

[#_Struct_Kind]
==== Struct Kind

`Class(name=Struct Kind, anchor=Struct_Kind, enumConstants=[], description=[, Kind represents the base of a defined type to describe its capabilities. For example, "define entity person;" defines a type "person" of a kind "entity".], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



Kind represents the base of a defined type to describe its capabilities. For example, "define entity person;" defines a type "person" of a kind "entity".

[#_Enum_Kind]
==== Enum Kind

`Class(name=Enum Kind, anchor=Enum_Kind, enumConstants=[EnumConstant(name=Entity, type=null, value=null), EnumConstant(name=Attribute, type=null, value=null), EnumConstant(name=Relation, type=null, value=null), EnumConstant(name=Role, type=null, value=null)], description=[, Kind represents the base of a defined type to describe its capabilities. For example, "define entity person;" defines a type "person" of a kind "entity".], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



Kind represents the base of a defined type to describe its capabilities. For example, "define entity person;" defines a type "person" of a kind "entity".

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `Attribute`
a| `Entity`
a| `Relation`
a| `Role`
|===
// end::enum_constants[]

