[#_methods_analyze_comparator]
=== comparator

[#_Struct_Comparator]
==== Struct Comparator

`Class(name=Struct Comparator, anchor=Struct_Comparator, enumConstants=[], description=[, A representation of the comparator used in a comparison constraint.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



A representation of the comparator used in a comparison constraint.

[#_Enum_Comparator]
==== Enum Comparator

`Class(name=Enum Comparator, anchor=Enum_Comparator, enumConstants=[EnumConstant(name=Equal, type=null, value=null), EnumConstant(name=NotEqual, type=null, value=null), EnumConstant(name=LessThan, type=null, value=null), EnumConstant(name=LessOrEqual, type=null, value=null), EnumConstant(name=Greater, type=null, value=null), EnumConstant(name=GreaterOrEqual, type=null, value=null), EnumConstant(name=Like, type=null, value=null), EnumConstant(name=Contains, type=null, value=null)], description=[, A representation of the comparator used in a comparison constraint.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



A representation of the comparator used in a comparison constraint.

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `Contains`
a| `Equal`
a| `Greater`
a| `GreaterOrEqual`
a| `LessOrEqual`
a| `LessThan`
a| `Like`
a| `NotEqual`
|===
// end::enum_constants[]

[#_comparator_get_name]
==== comparator_get_name

[source,cpp]
----
char* comparator_get_name(enum Comparator comparator)
----



Unwraps the ``Comparator`` and returns its name (or symbol).

[caption=""]
.Returns
`char*`

