[#_methods_analyze_fetch]
=== fetch

[#_Struct_Fetch]
==== Struct Fetch

`class`



A representation of the 'fetch' stage of a query

[#_fetch_drop]
==== fetch_drop()

[source,cpp]
----
void fetch_drop(struct Fetch* obj)
----



Frees the native rust ``Fetch`` object.

[caption=""]
.Returns
`void`

[#_fetch_leaf_annotations]
==== fetch_leaf_annotations()

[source,cpp]
----
struct StringIterator* fetch_leaf_annotations(const struct Fetch* fetch)
----



Unwraps the ``Fetch`` instance as a Leaf variant, and returns an iterator over possible value types. Will panic if the instance is not a Leaf variant.

[caption=""]
.Returns
`struct StringIterator*`

[#_fetch_list_element]
==== fetch_list_element()

[source,cpp]
----
struct Fetch* fetch_list_element(const struct Fetch* fetch)
----



Unwraps the ``Fetch`` instance as a List variant, and returns the ``Fetch`` for an element of the list. Will panic if the instance is not a List variant.

[caption=""]
.Returns
`struct Fetch*`

[#_fetch_object_fields]
==== fetch_object_fields()

[source,cpp]
----
struct StringIterator* fetch_object_fields(const struct Fetch* fetch)
----



Unwraps the ``Fetch`` instance as an Object variant, and returns the available fields. Will panic if the instance is not an Object variant.

[caption=""]
.Returns
`struct StringIterator*`

[#_fetch_object_get_field]
==== fetch_object_get_field()

[source,cpp]
----
struct Fetch* fetch_object_get_field(const struct Fetch* fetch, const char* field)
----



Unwraps the ``Fetch`` instance as an Object variant, and returns the value of the specified field. Will panic if the instance is not an Object variant.

[caption=""]
.Returns
`struct Fetch*`

[#_fetch_variant]
==== fetch_variant()

[source,cpp]
----
enum FetchVariant fetch_variant(const struct Fetch* fetch)
----



Returns the variant of the ``Fetch`` instance.

[caption=""]
.Returns
`enum FetchVariant`

