[#_methods_analyze_sortorder]
=== sortorder

[#_Struct_SortOrder]
==== Struct SortOrder

`Class(name=Struct SortOrder, anchor=Struct_SortOrder, enumConstants=[], description=[, The order of a variable being sorted on in a ``PipelineStage::Sort``], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



The order of a variable being sorted on in a ``PipelineStage::Sort``

[#_Enum_SortOrder]
==== Enum SortOrder

`Class(name=Enum SortOrder, anchor=Enum_SortOrder, enumConstants=[EnumConstant(name=Ascending, type=null, value=null), EnumConstant(name=Descending, type=null, value=null)], description=[, The order of a variable being sorted on in a ``PipelineStage::Sort``], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



The order of a variable being sorted on in a ``PipelineStage::Sort``

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `Ascending`
a| `Descending`
|===
// end::enum_constants[]

