[#_ConceptManager]
=== ConceptManager

*Package*: `TypeDB`



Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptPtrFuture_Attribute_TypeDBConceptManagergetAttribute_const_stdstring_iid_const]
==== getAttribute

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::ConceptManager::getAttribute(const std::string& iid) const
----



Retrieves an ``Attribute`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getAttribute(iid).get();
----

[#_ConceptPtrFuture_AttributeType_TypeDBConceptManagergetAttributeType_const_stdstring_label_const]
==== getAttributeType

[source,cpp]
----
ConceptPtrFuture< AttributeType > TypeDB::ConceptManager::getAttributeType(const std::string& label) const
----



Retrieves an ``AttributeType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getAttributeType(label).get();
----

[#_ConceptPtrFuture_Entity_TypeDBConceptManagergetEntity_const_stdstring_iid_const]
==== getEntity

[source,cpp]
----
ConceptPtrFuture< Entity > TypeDB::ConceptManager::getEntity(const std::string& iid) const
----



Retrieves an ``Entity`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Entity >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getEntity(iid).get();
----

[#_ConceptPtrFuture_EntityType_TypeDBConceptManagergetEntityType_const_stdstring_label_const]
==== getEntityType

[source,cpp]
----
ConceptPtrFuture< EntityType > TypeDB::ConceptManager::getEntityType(const std::string& label) const
----



Retrieves an ``EntityType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getEntityType(label).get();
----

[#_ConceptPtrFuture_Relation_TypeDBConceptManagergetRelation_const_stdstring_iid_const]
==== getRelation

[source,cpp]
----
ConceptPtrFuture< Relation > TypeDB::ConceptManager::getRelation(const std::string& iid) const
----



Retrieves a ``Relation`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Relation >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getRelation(iid).get();
----

[#_ConceptPtrFuture_RelationType_TypeDBConceptManagergetRelationType_const_stdstring_label_const]
==== getRelationType

[source,cpp]
----
ConceptPtrFuture< RelationType > TypeDB::ConceptManager::getRelationType(const std::string& label) const
----



Retrieves a ``RelationType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getRelationType(label).get();
----

[#_stdunique_ptr_AttributeType_TypeDBConceptManagergetRootAttributeType_const]
==== getRootAttributeType

[source,cpp]
----
std::unique_ptr< AttributeType > TypeDB::ConceptManager::getRootAttributeType() const
----



Retrieve the root ``AttributeType``, “attribute”.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getRootAttributeType();
----

[#_stdunique_ptr_EntityType_TypeDBConceptManagergetRootEntityType_const]
==== getRootEntityType

[source,cpp]
----
std::unique_ptr< EntityType > TypeDB::ConceptManager::getRootEntityType() const
----



Retrieves the root ``EntityType``, “entity”.


[caption=""]
.Returns
`std::unique_ptr< EntityType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getRootEntityType();
----

[#_stdunique_ptr_RelationType_TypeDBConceptManagergetRootRelationType_const]
==== getRootRelationType

[source,cpp]
----
std::unique_ptr< RelationType > TypeDB::ConceptManager::getRootRelationType() const
----



Retrieve the root ``RelationType``, “relation”.


[caption=""]
.Returns
`std::unique_ptr< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getRootRelationType();
----

[#_stdvector_DriverException_TypeDBConceptManagergetSchemaExceptions_]
==== getSchemaExceptions

[source,cpp]
----
std::vector< DriverException > TypeDB::ConceptManager::getSchemaExceptions()
----



Retrieves a list of all schema exceptions for the current transaction.


[caption=""]
.Returns
`std::vector< DriverException >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.getSchemaExceptions();
----

[#_ConceptPtrFuture_AttributeType_TypeDBConceptManagerputAttributeType_const_stdstring_label_ValueType_valueType_const]
==== putAttributeType

[source,cpp]
----
ConceptPtrFuture< AttributeType > TypeDB::ConceptManager::putAttributeType(const std::string& label, ValueType valueType) const
----



Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `const std::string&`
a| `valueType` a| The value type of the ``AttributeType`` to create a| `ValueType`
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.putAttributeType(label, valueType).get();
----

[#_ConceptPtrFuture_EntityType_TypeDBConceptManagerputEntityType_const_stdstring_label_const]
==== putEntityType

[source,cpp]
----
ConceptPtrFuture< EntityType > TypeDB::ConceptManager::putEntityType(const std::string& label) const
----



Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.putEntityType(label).get();
----

[#_ConceptPtrFuture_RelationType_TypeDBConceptManagerputRelationType_const_stdstring_label_const]
==== putRelationType

[source,cpp]
----
ConceptPtrFuture< RelationType > TypeDB::ConceptManager::putRelationType(const std::string& label) const
----



Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
transaction.concepts.putRelationType(label).get();
----

// end::methods[]

