
[#_connection_header]
== Connection

{page-version}@api-ref::partial$rust/connection/Connection.adoc[]

{page-version}@api-ref::partial$rust/connection/Credential.adoc[]

{page-version}@api-ref::partial$rust/connection/DatabaseManager.adoc[]

{page-version}@api-ref::partial$rust/connection/Database.adoc[]

{page-version}@api-ref::partial$rust/connection/ReplicaInfo.adoc[]

{page-version}@api-ref::partial$rust/connection/UserManager.adoc[]

{page-version}@api-ref::partial$rust/connection/User.adoc[]

[#_session_header]
== Session

{page-version}@api-ref::partial$rust/session/Session.adoc[]

{page-version}@api-ref::partial$rust/session/SessionType.adoc[]

{page-version}@api-ref::partial$rust/session/Options.adoc[]

[#_transaction_header]
== Transaction

{page-version}@api-ref::partial$rust/transaction/Transaction.adoc[]

{page-version}@api-ref::partial$rust/transaction/TransactionType.adoc[]

{page-version}@api-ref::partial$rust/transaction/QueryManager.adoc[]

[#_answer_header]
== Answer

{page-version}@api-ref::partial$rust/answer/ConceptMapGroup.adoc[]

{page-version}@api-ref::partial$rust/answer/ConceptMap.adoc[]

{page-version}@api-ref::partial$rust/answer/ValueGroup.adoc[]

{page-version}@api-ref::partial$rust/answer/JSON.adoc[]

{page-version}@api-ref::partial$rust/answer/Trait_Promise.adoc[]

{page-version}@api-ref::partial$rust/answer/Explainables.adoc[]

{page-version}@api-ref::partial$rust/answer/Explainable.adoc[]

{page-version}@api-ref::partial$rust/answer/Explanation.adoc[]

[#_concept_header]
== Concept

{page-version}@api-ref::partial$rust/concept/ConceptManager.adoc[]

{page-version}@api-ref::partial$rust/concept/Concept.adoc[]

[#_schema_header]
== Schema

//{page-version}@api-ref::partial$rust/schema/Type.adoc[]

{page-version}@api-ref::partial$rust/schema/RootThingType.adoc[]

{page-version}@api-ref::partial$rust/schema/ThingType.adoc[]

{page-version}@api-ref::partial$rust/schema/Trait_ThingTypeAPI.adoc[]

{page-version}@api-ref::partial$rust/schema/EntityType.adoc[]

{page-version}@api-ref::partial$rust/schema/Trait_EntityTypeAPI.adoc[]

{page-version}@api-ref::partial$rust/schema/RelationType.adoc[]

{page-version}@api-ref::partial$rust/schema/Trait_RelationTypeAPI.adoc[]

{page-version}@api-ref::partial$rust/schema/RoleType.adoc[]

{page-version}@api-ref::partial$rust/schema/Trait_RoleTypeAPI.adoc[]

{page-version}@api-ref::partial$rust/schema/AttributeType.adoc[]

{page-version}@api-ref::partial$rust/schema/Trait_AttributeTypeAPI.adoc[]

{page-version}@api-ref::partial$rust/schema/Annotation.adoc[]

{page-version}@api-ref::partial$rust/schema/Transitivity.adoc[]

{page-version}@api-ref::partial$rust/schema/ValueType.adoc[]

{page-version}@api-ref::partial$rust/schema/ScopedLabel.adoc[]

[#_data_header]
== Data

{page-version}@api-ref::partial$rust/data/Thing.adoc[]

{page-version}@api-ref::partial$rust/data/Trait_ThingAPI.adoc[]

{page-version}@api-ref::partial$rust/data/Entity.adoc[]

{page-version}@api-ref::partial$rust/data/Relation.adoc[]

{page-version}@api-ref::partial$rust/data/Attribute.adoc[]

{page-version}@api-ref::partial$rust/data/Value.adoc[]

[#_logic_header]
== Logic

{page-version}@api-ref::partial$rust/logic/LogicManager.adoc[]

{page-version}@api-ref::partial$rust/logic/Rule.adoc[]

{page-version}@api-ref::partial$rust/logic/Trait_RuleAPI.adoc[]

[#_errors_header]
== Errors

{page-version}@api-ref::partial$rust/errors/SchemaException.adoc[]

{page-version}@api-ref::partial$rust/errors/Error.adoc[]

{page-version}@api-ref::partial$rust/errors/ConnectionError.adoc[]

{page-version}@api-ref::partial$rust/errors/InternalError.adoc[]
