[#_methods__concept__concept]
=== concept

[#_Struct_Concept]
==== Struct Concept



The fundamental TypeQL object. A Concept is either a Type, Thing, or Value. To use subtype specific methods, the Concept must be of the expected subtype.

[#_Struct_ConceptIterator]
==== Struct ConceptIterator



Iterator over the ``Concepts``s returned by an API method or query.

[#_Struct_ConceptPromise]
==== Struct ConceptPromise



Promise object representing the result of an asynchronous operation. Use concept_promise_resolve(ConceptPromise*) to wait for and retrieve the resulting boolean value.

[#_concept_drop]
==== concept_drop

[source,cpp]
----
void concept_drop(struct Concept* concept)
----



Frees the native rust ``Concept`` object

[caption=""]
.Returns
`void`

[#_concept_equals]
==== concept_equals

[source,cpp]
----
bool concept_equals(const struct Concept* lhs, const struct Concept* rhs)
----



Checks whether the provided ``Concept`` objects are equal

[caption=""]
.Returns
`bool`

[#_concept_is_attribute]
==== concept_is_attribute

[source,cpp]
----
bool concept_is_attribute(const struct Concept* concept)
----



Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[#_concept_is_attribute_type]
==== concept_is_attribute_type

[source,cpp]
----
bool concept_is_attribute_type(const struct Concept* concept)
----



Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[#_concept_is_entity]
==== concept_is_entity

[source,cpp]
----
bool concept_is_entity(const struct Concept* concept)
----



Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`bool`

[#_concept_is_entity_type]
==== concept_is_entity_type

[source,cpp]
----
bool concept_is_entity_type(const struct Concept* concept)
----



Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`bool`

[#_concept_is_relation]
==== concept_is_relation

[source,cpp]
----
bool concept_is_relation(const struct Concept* concept)
----



Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[#_concept_is_relation_type]
==== concept_is_relation_type

[source,cpp]
----
bool concept_is_relation_type(const struct Concept* concept)
----



Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`bool`

[#_concept_is_role_type]
==== concept_is_role_type

[source,cpp]
----
bool concept_is_role_type(const struct Concept* concept)
----



Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`bool`

[#_concept_is_root_thing_type]
==== concept_is_root_thing_type

[source,cpp]
----
bool concept_is_root_thing_type(const struct Concept* concept)
----



Checks if the concept is the root ``thing`` type.

[caption=""]
.Returns
`bool`

[#_concept_is_value]
==== concept_is_value

[source,cpp]
----
bool concept_is_value(const struct Concept* concept)
----



Checks if the concept is a ``Value``.

[caption=""]
.Returns
`bool`

[#_concept_iterator_drop]
==== concept_iterator_drop

[source,cpp]
----
void concept_iterator_drop(struct ConceptIterator* it)
----



Frees the native rust ``ConceptIterator`` object

[caption=""]
.Returns
`void`

[#_concept_iterator_next]
==== concept_iterator_next

[source,cpp]
----
struct Concept* concept_iterator_next(struct ConceptIterator* it)
----



Forwards the ``ConceptIterator`` and returns the next ``Concept`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct Concept*`

[#_concept_promise_resolve]
==== concept_promise_resolve

[source,cpp]
----
struct Concept* concept_promise_resolve(struct ConceptPromise* promise)
----



Waits for and returns the result of the operation represented by the ``ConceptPromise`` object. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`struct Concept*`

[#_concept_to_string]
==== concept_to_string

[source,cpp]
----
char* concept_to_string(const struct Concept* concept)
----



A string representation of this ``Concept`` object

[caption=""]
.Returns
`char*`

[#_concepts_get_attribute]
==== concepts_get_attribute

[source,cpp]
----
struct ConceptPromise* concepts_get_attribute(const struct Transaction* transaction, const char* iid)
----



Retrieves an ``Attribute`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_attribute_type]
==== concepts_get_attribute_type

[source,cpp]
----
struct ConceptPromise* concepts_get_attribute_type(const struct Transaction* transaction, const char* label)
----



Retrieves an ``AttributeType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_entity]
==== concepts_get_entity

[source,cpp]
----
struct ConceptPromise* concepts_get_entity(const struct Transaction* transaction, const char* iid)
----



Retrieves an ``Entity`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_entity_type]
==== concepts_get_entity_type

[source,cpp]
----
struct ConceptPromise* concepts_get_entity_type(const struct Transaction* transaction, const char* label)
----



Retrieves an ``EntityType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_relation]
==== concepts_get_relation

[source,cpp]
----
struct ConceptPromise* concepts_get_relation(const struct Transaction* transaction, const char* iid)
----



Retrieves a ``relation`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_relation_type]
==== concepts_get_relation_type

[source,cpp]
----
struct ConceptPromise* concepts_get_relation_type(const struct Transaction* transaction, const char* label)
----



Retrieves a ``RelationType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_get_root_attribute_type]
==== concepts_get_root_attribute_type

[source,cpp]
----
struct Concept* concepts_get_root_attribute_type(void)
----



Retrieves the root ``AttributeType``, “attribute”.

[caption=""]
.Returns
`struct Concept*`

[#_concepts_get_root_entity_type]
==== concepts_get_root_entity_type

[source,cpp]
----
struct Concept* concepts_get_root_entity_type(void)
----



Retrieves the root ``EntityType``, “entity”.

[caption=""]
.Returns
`struct Concept*`

[#_concepts_get_root_relation_type]
==== concepts_get_root_relation_type

[source,cpp]
----
struct Concept* concepts_get_root_relation_type(void)
----



Retrieves the root ``RelationType``, “relation”.

[caption=""]
.Returns
`struct Concept*`

[#_concepts_get_schema_exceptions]
==== concepts_get_schema_exceptions

[source,cpp]
----
struct SchemaExceptionIterator* concepts_get_schema_exceptions(const struct Transaction* transaction)
----



Retrieves a list of all schema exceptions for the current transaction.

[caption=""]
.Returns
`struct SchemaExceptionIterator*`

[#_concepts_put_attribute_type]
==== concepts_put_attribute_type

[source,cpp]
----
struct ConceptPromise* concepts_put_attribute_type(const struct Transaction* transaction, const char* label, enum ValueType value_type)
----



Creates a new ``AttributeType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_put_entity_type]
==== concepts_put_entity_type

[source,cpp]
----
struct ConceptPromise* concepts_put_entity_type(const struct Transaction* transaction, const char* label)
----



Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_concepts_put_relation_type]
==== concepts_put_relation_type

[source,cpp]
----
struct ConceptPromise* concepts_put_relation_type(const struct Transaction* transaction, const char* label)
----



Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

