[#_◆_concept_drop_]
==== concept_drop

[source,cpp]
----
void concept_drop(struct Concept* concept)
----



Frees the native rust ``Concept`` object

[caption=""]
.Returns
`void`

[#_◆_concept_equals_]
==== concept_equals

[source,cpp]
----
bool concept_equals(const struct Concept* lhs, const struct Concept* rhs)
----



Checks whether the provided ``Concept`` objects are equal

[caption=""]
.Returns
`bool`

[#_◆_concept_is_attribute_]
==== concept_is_attribute

[source,cpp]
----
bool concept_is_attribute(const struct Concept* concept)
----



Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_attribute_type_]
==== concept_is_attribute_type

[source,cpp]
----
bool concept_is_attribute_type(const struct Concept* concept)
----



Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_entity_]
==== concept_is_entity

[source,cpp]
----
bool concept_is_entity(const struct Concept* concept)
----



Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_entity_type_]
==== concept_is_entity_type

[source,cpp]
----
bool concept_is_entity_type(const struct Concept* concept)
----



Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_relation_]
==== concept_is_relation

[source,cpp]
----
bool concept_is_relation(const struct Concept* concept)
----



Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_relation_type_]
==== concept_is_relation_type

[source,cpp]
----
bool concept_is_relation_type(const struct Concept* concept)
----



Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_role_type_]
==== concept_is_role_type

[source,cpp]
----
bool concept_is_role_type(const struct Concept* concept)
----



Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_root_thing_type_]
==== concept_is_root_thing_type

[source,cpp]
----
bool concept_is_root_thing_type(const struct Concept* concept)
----



Checks if the concept is the root ``thing`` type.

[caption=""]
.Returns
`bool`

[#_◆_concept_is_value_]
==== concept_is_value

[source,cpp]
----
bool concept_is_value(const struct Concept* concept)
----



Checks if the concept is a ``Value``.

[caption=""]
.Returns
`bool`

[#_◆_concept_iterator_drop_]
==== concept_iterator_drop

[source,cpp]
----
void concept_iterator_drop(struct ConceptIterator* it)
----



Frees the native rust ``ConceptIterator`` object

[caption=""]
.Returns
`void`

[#_◆_concept_iterator_next_]
==== concept_iterator_next

[source,cpp]
----
struct Concept* concept_iterator_next(struct ConceptIterator* it)
----



Forwards the ``ConceptIterator`` and returns the next ``Concept`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct Concept*`

[#_◆_concept_promise_resolve_]
==== concept_promise_resolve

[source,cpp]
----
struct Concept* concept_promise_resolve(struct ConceptPromise* promise)
----



Waits for and returns the result of the operation represented by the ``ConceptPromise`` object. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`struct Concept*`

[#_◆_concept_to_string_]
==== concept_to_string

[source,cpp]
----
char* concept_to_string(const struct Concept* concept)
----



A string representation of this ``Concept`` object

[caption=""]
.Returns
`char*`

[#_◆_concepts_get_attribute_]
==== concepts_get_attribute

[source,cpp]
----
struct ConceptPromise* concepts_get_attribute(const struct Transaction* transaction, const char* iid)
----



Retrieves an ``Attribute`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_attribute_type_]
==== concepts_get_attribute_type

[source,cpp]
----
struct ConceptPromise* concepts_get_attribute_type(const struct Transaction* transaction, const char* label)
----



Retrieves an ``AttributeType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_entity_]
==== concepts_get_entity

[source,cpp]
----
struct ConceptPromise* concepts_get_entity(const struct Transaction* transaction, const char* iid)
----



Retrieves an ``Entity`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_entity_type_]
==== concepts_get_entity_type

[source,cpp]
----
struct ConceptPromise* concepts_get_entity_type(const struct Transaction* transaction, const char* label)
----



Retrieves an ``EntityType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_relation_]
==== concepts_get_relation

[source,cpp]
----
struct ConceptPromise* concepts_get_relation(const struct Transaction* transaction, const char* iid)
----



Retrieves a ``relation`` instance by its iid.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_relation_type_]
==== concepts_get_relation_type

[source,cpp]
----
struct ConceptPromise* concepts_get_relation_type(const struct Transaction* transaction, const char* label)
----



Retrieves a ``RelationType`` by its label.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_get_root_attribute_type_]
==== concepts_get_root_attribute_type

[source,cpp]
----
struct Concept* concepts_get_root_attribute_type(void)
----



Retrieves the root ``AttributeType``, “attribute”.

[caption=""]
.Returns
`struct Concept*`

[#_◆_concepts_get_root_entity_type_]
==== concepts_get_root_entity_type

[source,cpp]
----
struct Concept* concepts_get_root_entity_type(void)
----



Retrieves the root ``EntityType``, “entity”.

[caption=""]
.Returns
`struct Concept*`

[#_◆_concepts_get_root_relation_type_]
==== concepts_get_root_relation_type

[source,cpp]
----
struct Concept* concepts_get_root_relation_type(void)
----



Retrieves the root ``RelationType``, “relation”.

[caption=""]
.Returns
`struct Concept*`

[#_◆_concepts_get_schema_exceptions_]
==== concepts_get_schema_exceptions

[source,cpp]
----
struct SchemaExceptionIterator* concepts_get_schema_exceptions(const struct Transaction* transaction)
----



Retrieves a list of all schema exceptions for the current transaction.

[caption=""]
.Returns
`struct SchemaExceptionIterator*`

[#_◆_concepts_put_attribute_type_]
==== concepts_put_attribute_type

[source,cpp]
----
struct ConceptPromise* concepts_put_attribute_type(const struct Transaction* transaction, const char* label, enum ValueType value_type)
----



Creates a new ``AttributeType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_put_entity_type_]
==== concepts_put_entity_type

[source,cpp]
----
struct ConceptPromise* concepts_put_entity_type(const struct Transaction* transaction, const char* label)
----



Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_concepts_put_relation_type_]
==== concepts_put_relation_type

[source,cpp]
----
struct ConceptPromise* concepts_put_relation_type(const struct Transaction* transaction, const char* label)
----



Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Returns
`struct ConceptPromise*`

