[#_◆_thing_delete_]
==== thing_delete

[source,cpp]
----
struct VoidPromise* thing_delete(struct Transaction* transaction, struct Concept* thing)
----



Deletes this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_get_has_]
==== thing_get_has

[source,cpp]
----
struct ConceptIterator* thing_get_has(struct Transaction* transaction, const struct Concept* thing, const struct Concept*const* attribute_types, const struct Annotation*const* annotations)
----



Retrieves the ``Attribute``s that this ``Thing`` owns, optionally filtered by ``AttributeType``s.

 
  Parameters
 
 
  
   
    
     transaction
     The current transaction
    
    
     thing
     The thing to get owned attributes of
    
    
     attribute_types
     a null-terminated array holding the attribute-types to include
    
    
     annotations
     a null-terminated array of annotations - If non-empty, Only retrieves attributes with all given ``Annotation``s
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `thing` a| The thing to get owned attributes of a| 
a| `attribute_types` a| a null-terminated array holding the attribute-types to include a| 
a| `annotations` a| a null-terminated array of annotations - If non-empty, Only retrieves attributes with all given ``Annotation``s a| 
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_◆_thing_get_iid_]
==== thing_get_iid

[source,cpp]
----
char* thing_get_iid(struct Concept* thing)
----



Retrieves the unique id of the ``Thing``.

[caption=""]
.Returns
`char*`

[#_◆_thing_get_is_inferred_]
==== thing_get_is_inferred

[source,cpp]
----
bool thing_get_is_inferred(struct Concept* thing)
----



Checks if this ``Thing`` is inferred by a [Reasoning Rule].

[caption=""]
.Returns
`bool`

[#_◆_thing_get_playing_]
==== thing_get_playing

[source,cpp]
----
struct ConceptIterator* thing_get_playing(struct Transaction* transaction, const struct Concept* thing)
----



Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Returns
`struct ConceptIterator*`

[#_◆_thing_get_relations_]
==== thing_get_relations

[source,cpp]
----
struct ConceptIterator* thing_get_relations(struct Transaction* transaction, const struct Concept* thing, const struct Concept*const* role_types)
----



Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

 
  Parameters
 
 
  
   
    
     role_types
     a null-terminated array of ``RoleType``s to include.
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `role_types` a| a null-terminated array of ``RoleType``s to include. a| 
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_◆_thing_is_deleted_]
==== thing_is_deleted

[source,cpp]
----
struct BoolPromise* thing_is_deleted(struct Transaction* transaction, const struct Concept* thing)
----



Checks if this ``Thing`` is deleted.

[caption=""]
.Returns
`struct BoolPromise*`

[#_◆_thing_set_has_]
==== thing_set_has

[source,cpp]
----
struct VoidPromise* thing_set_has(struct Transaction* transaction, struct Concept* thing, const struct Concept* attribute)
----



Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_delete_]
==== thing_type_delete

[source,cpp]
----
struct VoidPromise* thing_type_delete(const struct Transaction* transaction, struct Concept* thing_type)
----



Deletes this thing type from the database.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_get_label_]
==== thing_type_get_label

[source,cpp]
----
char* thing_type_get_label(const struct Concept* thing_type)
----



Retrieves the unique label of the thing type.

[caption=""]
.Returns
`char*`

[#_◆_thing_type_get_owns_]
==== thing_type_get_owns

[source,cpp]
----
struct ConceptIterator* thing_type_get_owns(const struct Transaction* transaction, const struct Concept* thing_type, const enum ValueType* value_type, enum Transitivity transitivity, const struct Annotation*const* annotations)
----



Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance. Specify ``Explicit`` to only include directly owned types, or ``Transitive`` to include inherited

 
  Parameters
 
 
  
   
    
     annotations
     a null-terminated array of ``Annotation``s - If non-empty, Only retrieves attribute types owned with all specified annotations.
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `annotations` a| a null-terminated array of ``Annotation``s - If non-empty, Only retrieves attribute types owned with all specified annotations. a| 
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_◆_thing_type_get_owns_overridden_]
==== thing_type_get_owns_overridden

[source,cpp]
----
struct ConceptPromise* thing_type_get_owns_overridden(const struct Transaction* transaction, const struct Concept* thing_type, const struct Concept* overridden_attribute_type)
----



Retrieves the ``AttributeType``, ownership of which is overridden for this ``ThingType`` by the specified ``AttributeType``.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_thing_type_get_plays_]
==== thing_type_get_plays

[source,cpp]
----
struct ConceptIterator* thing_type_get_plays(const struct Transaction* transaction, const struct Concept* thing_type, enum Transitivity transitivity)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``. Specify ``Transitive`` for direct and inherited roles, Or ``Explicit`` for directly played roles only.

[caption=""]
.Returns
`struct ConceptIterator*`

[#_◆_thing_type_get_plays_overridden_]
==== thing_type_get_plays_overridden

[source,cpp]
----
struct ConceptPromise* thing_type_get_plays_overridden(const struct Transaction* transaction, const struct Concept* thing_type, const struct Concept* overridden_role_type)
----



Retrieves the ``RoleType`` that is overridden by the given ``RoleType`` for this ``ThingType``.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_thing_type_get_syntax_]
==== thing_type_get_syntax

[source,cpp]
----
struct StringPromise* thing_type_get_syntax(const struct Transaction* transaction, const struct Concept* thing_type)
----



Produces a TypeQL pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Returns
`struct StringPromise*`

[#_◆_thing_type_is_abstract_]
==== thing_type_is_abstract

[source,cpp]
----
bool thing_type_is_abstract(const struct Concept* thing_type)
----



Checks if this thing type is prevented from having data instances (i.e., abstract).

[caption=""]
.Returns
`bool`

[#_◆_thing_type_is_deleted_]
==== thing_type_is_deleted

[source,cpp]
----
struct BoolPromise* thing_type_is_deleted(const struct Transaction* transaction, const struct Concept* thing_type)
----



Checks if the thing type has been deleted

[caption=""]
.Returns
`struct BoolPromise*`

[#_◆_thing_type_is_root_]
==== thing_type_is_root

[source,cpp]
----
bool thing_type_is_root(const struct Concept* thing_type)
----



Checks if this type is a root type (""entity"", ""relation"", ""attribute"")

[caption=""]
.Returns
`bool`

[#_◆_thing_type_set_abstract_]
==== thing_type_set_abstract

[source,cpp]
----
struct VoidPromise* thing_type_set_abstract(const struct Transaction* transaction, struct Concept* thing_type)
----



Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_set_label_]
==== thing_type_set_label

[source,cpp]
----
struct VoidPromise* thing_type_set_label(const struct Transaction* transaction, struct Concept* thing_type, const char* new_label)
----



Renames the label of the type. The new label must remain unique.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_set_owns_]
==== thing_type_set_owns

[source,cpp]
----
struct VoidPromise* thing_type_set_owns(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* attribute_type, const struct Concept* overridden_attribute_type, const struct Annotation*const* annotations)
----



Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. With the specified annotations to the ownership.

 
  Parameters
 
 
  
   
    
     transaction
     The current transaction
    
    
     thing_type
     The thing type which is to own the specified attribute
    
    
     attribute_type
     The attribute type which is to be owned by the specified thing type
    
    
     overridden_attribute_type
     Optional, The attribute whose ownership must be overridden
    
    
     annotations
     A null-terminated array of ``Annotation``s to be added to the ownership
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `thing_type` a| The thing type which is to own the specified attribute a| 
a| `attribute_type` a| The attribute type which is to be owned by the specified thing type a| 
a| `overridden_attribute_type` a| Optional, The attribute whose ownership must be overridden a| 
a| `annotations` a| A null-terminated array of ``Annotation``s to be added to the ownership a| 
|===

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_set_plays_]
==== thing_type_set_plays

[source,cpp]
----
struct VoidPromise* thing_type_set_plays(struct Transaction* transaction, struct Concept* thing_type, const struct Concept* role_type, const struct Concept* overridden_role_type)
----



Allows the instances of this ``ThingType`` to play the given role. Optionally, overriding the existing ability to play a role.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_unset_abstract_]
==== thing_type_unset_abstract

[source,cpp]
----
struct VoidPromise* thing_type_unset_abstract(const struct Transaction* transaction, struct Concept* thing_type)
----



Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_unset_owns_]
==== thing_type_unset_owns

[source,cpp]
----
struct VoidPromise* thing_type_unset_owns(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* attribute_type)
----



Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_type_unset_plays_]
==== thing_type_unset_plays

[source,cpp]
----
struct VoidPromise* thing_type_unset_plays(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* role_type)
----



Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_thing_unset_has_]
==== thing_unset_has

[source,cpp]
----
struct VoidPromise* thing_unset_has(struct Transaction* transaction, struct Concept* thing, const struct Concept* attribute)
----



Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

