[#_methods__concept__thing]
=== thing

[#_thing_delete]
==== thing_delete

[source,cpp]
----
struct VoidPromise* thing_delete(struct Transaction* transaction, struct Concept* thing)
----



Deletes this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_get_has]
==== thing_get_has

[source,cpp]
----
struct ConceptIterator* thing_get_has(struct Transaction* transaction, const struct Concept* thing, const struct Concept*const* attribute_types, const struct Annotation*const* annotations)
----



Retrieves the ``Attribute``s that this ``Thing`` owns, optionally filtered by ``AttributeType``s.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `struct Transaction*`
a| `thing` a| The thing to get owned attributes of a| `const struct Concept*`
a| `attribute_types` a| a null-terminated array holding the attribute-types to include a| `const struct Concept*const*`
a| `annotations` a| a null-terminated array of annotations - If non-empty, Only retrieves attributes with all given ``Annotation``s a| `const struct Annotation*const*`
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_thing_get_iid]
==== thing_get_iid

[source,cpp]
----
char* thing_get_iid(struct Concept* thing)
----



Retrieves the unique id of the ``Thing``.

[caption=""]
.Returns
`char*`

[#_thing_get_is_inferred]
==== thing_get_is_inferred

[source,cpp]
----
bool thing_get_is_inferred(struct Concept* thing)
----



Checks if this ``Thing`` is inferred by a [Reasoning Rule].

[caption=""]
.Returns
`bool`

[#_thing_get_playing]
==== thing_get_playing

[source,cpp]
----
struct ConceptIterator* thing_get_playing(struct Transaction* transaction, const struct Concept* thing)
----



Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Returns
`struct ConceptIterator*`

[#_thing_get_relations]
==== thing_get_relations

[source,cpp]
----
struct ConceptIterator* thing_get_relations(struct Transaction* transaction, const struct Concept* thing, const struct Concept*const* role_types)
----



Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `role_types` a| a null-terminated array of ``RoleType``s to include. a| `const struct Concept*const*`
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_thing_is_deleted]
==== thing_is_deleted

[source,cpp]
----
struct BoolPromise* thing_is_deleted(struct Transaction* transaction, const struct Concept* thing)
----



Checks if this ``Thing`` is deleted.

[caption=""]
.Returns
`struct BoolPromise*`

[#_thing_set_has]
==== thing_set_has

[source,cpp]
----
struct VoidPromise* thing_set_has(struct Transaction* transaction, struct Concept* thing, const struct Concept* attribute)
----



Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_delete]
==== thing_type_delete

[source,cpp]
----
struct VoidPromise* thing_type_delete(const struct Transaction* transaction, struct Concept* thing_type)
----



Deletes this thing type from the database.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_get_label]
==== thing_type_get_label

[source,cpp]
----
char* thing_type_get_label(const struct Concept* thing_type)
----



Retrieves the unique label of the thing type.

[caption=""]
.Returns
`char*`

[#_thing_type_get_owns]
==== thing_type_get_owns

[source,cpp]
----
struct ConceptIterator* thing_type_get_owns(const struct Transaction* transaction, const struct Concept* thing_type, const enum ValueType* value_type, enum Transitivity transitivity, const struct Annotation*const* annotations)
----



Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance. Specify ``Explicit`` to only include directly owned types, or ``Transitive`` to include inherited


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `annotations` a| a null-terminated array of ``Annotation``s - If non-empty, Only retrieves attribute types owned with all specified annotations. a| `const struct Annotation*const*`
|===

[caption=""]
.Returns
`struct ConceptIterator*`

[#_thing_type_get_owns_overridden]
==== thing_type_get_owns_overridden

[source,cpp]
----
struct ConceptPromise* thing_type_get_owns_overridden(const struct Transaction* transaction, const struct Concept* thing_type, const struct Concept* overridden_attribute_type)
----



Retrieves the ``AttributeType``, ownership of which is overridden for this ``ThingType`` by the specified ``AttributeType``.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_thing_type_get_plays]
==== thing_type_get_plays

[source,cpp]
----
struct ConceptIterator* thing_type_get_plays(const struct Transaction* transaction, const struct Concept* thing_type, enum Transitivity transitivity)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``. Specify ``Transitive`` for direct and inherited roles, Or ``Explicit`` for directly played roles only.

[caption=""]
.Returns
`struct ConceptIterator*`

[#_thing_type_get_plays_overridden]
==== thing_type_get_plays_overridden

[source,cpp]
----
struct ConceptPromise* thing_type_get_plays_overridden(const struct Transaction* transaction, const struct Concept* thing_type, const struct Concept* overridden_role_type)
----



Retrieves the ``RoleType`` that is overridden by the given ``RoleType`` for this ``ThingType``.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_thing_type_get_syntax]
==== thing_type_get_syntax

[source,cpp]
----
struct StringPromise* thing_type_get_syntax(const struct Transaction* transaction, const struct Concept* thing_type)
----



Produces a TypeQL pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Returns
`struct StringPromise*`

[#_thing_type_is_abstract]
==== thing_type_is_abstract

[source,cpp]
----
bool thing_type_is_abstract(const struct Concept* thing_type)
----



Checks if this thing type is prevented from having data instances (i.e., abstract).

[caption=""]
.Returns
`bool`

[#_thing_type_is_deleted]
==== thing_type_is_deleted

[source,cpp]
----
struct BoolPromise* thing_type_is_deleted(const struct Transaction* transaction, const struct Concept* thing_type)
----



Checks if the thing type has been deleted

[caption=""]
.Returns
`struct BoolPromise*`

[#_thing_type_is_root]
==== thing_type_is_root

[source,cpp]
----
bool thing_type_is_root(const struct Concept* thing_type)
----



Checks if this type is a root type (""entity"", ""relation"", ""attribute"")

[caption=""]
.Returns
`bool`

[#_thing_type_set_abstract]
==== thing_type_set_abstract

[source,cpp]
----
struct VoidPromise* thing_type_set_abstract(const struct Transaction* transaction, struct Concept* thing_type)
----



Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_set_label]
==== thing_type_set_label

[source,cpp]
----
struct VoidPromise* thing_type_set_label(const struct Transaction* transaction, struct Concept* thing_type, const char* new_label)
----



Renames the label of the type. The new label must remain unique.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_set_owns]
==== thing_type_set_owns

[source,cpp]
----
struct VoidPromise* thing_type_set_owns(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* attribute_type, const struct Concept* overridden_attribute_type, const struct Annotation*const* annotations)
----



Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. With the specified annotations to the ownership.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `const struct Transaction*`
a| `thing_type` a| The thing type which is to own the specified attribute a| `struct Concept*`
a| `attribute_type` a| The attribute type which is to be owned by the specified thing type a| `const struct Concept*`
a| `overridden_attribute_type` a| Optional, The attribute whose ownership must be overridden a| `const struct Concept*`
a| `annotations` a| A null-terminated array of ``Annotation``s to be added to the ownership a| `const struct Annotation*const*`
|===

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_set_plays]
==== thing_type_set_plays

[source,cpp]
----
struct VoidPromise* thing_type_set_plays(struct Transaction* transaction, struct Concept* thing_type, const struct Concept* role_type, const struct Concept* overridden_role_type)
----



Allows the instances of this ``ThingType`` to play the given role. Optionally, overriding the existing ability to play a role.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_unset_abstract]
==== thing_type_unset_abstract

[source,cpp]
----
struct VoidPromise* thing_type_unset_abstract(const struct Transaction* transaction, struct Concept* thing_type)
----



Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_unset_owns]
==== thing_type_unset_owns

[source,cpp]
----
struct VoidPromise* thing_type_unset_owns(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* attribute_type)
----



Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_type_unset_plays]
==== thing_type_unset_plays

[source,cpp]
----
struct VoidPromise* thing_type_unset_plays(const struct Transaction* transaction, struct Concept* thing_type, const struct Concept* role_type)
----



Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Returns
`struct VoidPromise*`

[#_thing_unset_has]
==== thing_unset_has

[source,cpp]
----
struct VoidPromise* thing_unset_has(struct Transaction* transaction, struct Concept* thing, const struct Concept* attribute)
----



Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Returns
`struct VoidPromise*`

