[#_◆_value_get_boolean_]
==== value_get_boolean

[source,cpp]
----
bool value_get_boolean(const struct Concept* value)
----



Returns a ``boolean`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`bool`

[#_◆_value_get_date_time_as_millis_]
==== value_get_date_time_as_millis

[source,cpp]
----
int64_t value_get_date_time_as_millis(const struct Concept* value)
----



Returns the value of this datetime value concept as milliseconds since the start of the UNIX epoch. If the value has another type, the error is set.

[caption=""]
.Returns
`int64_t`

[#_◆_value_get_double_]
==== value_get_double

[source,cpp]
----
double value_get_double(const struct Concept* value)
----



Returns the ``double`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`double`

[#_◆_value_get_long_]
==== value_get_long

[source,cpp]
----
int64_t value_get_long(const struct Concept* value)
----



Returns the ``long`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`int64_t`

[#_◆_value_get_string_]
==== value_get_string

[source,cpp]
----
char* value_get_string(const struct Concept* value)
----



Returns the ``string`` value of this value concept. If the value has another type, the error is set.

[caption=""]
.Returns
`char*`

[#_◆_value_is_boolean_]
==== value_is_boolean

[source,cpp]
----
bool value_is_boolean(const struct Concept* value)
----



Returns ``true`` if the value which this ``Value`` concept holds is of type ``boolean``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_◆_value_is_date_time_]
==== value_is_date_time

[source,cpp]
----
bool value_is_date_time(const struct Concept* value)
----



Returns ``true`` if the value which this ``Value`` concept holds is of type ``datetime``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_◆_value_is_double_]
==== value_is_double

[source,cpp]
----
bool value_is_double(const struct Concept* value)
----



Returns ``true`` if the value which this ``Value`` concept holds is of type ``double``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_◆_value_is_long_]
==== value_is_long

[source,cpp]
----
bool value_is_long(const struct Concept* value)
----



Returns ``true`` if the value which this ``Value`` concept holds is of type ``long``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_◆_value_is_string_]
==== value_is_string

[source,cpp]
----
bool value_is_string(const struct Concept* value)
----



Returns ``true`` if the value which this ``Value`` concept holds is of type ``string``. Otherwise, returns ``false``.

[caption=""]
.Returns
`bool`

[#_◆_value_new_boolean_]
==== value_new_boolean

[source,cpp]
----
struct Concept* value_new_boolean(bool bool_)
----



Creates a new ``Value`` object of the specified boolean value.

[caption=""]
.Returns
`struct Concept*`

[#_◆_value_new_date_time_from_millis_]
==== value_new_date_time_from_millis

[source,cpp]
----
struct Concept* value_new_date_time_from_millis(int64_t millis)
----



Creates a new ``Value`` object of the specified datetime value.

[caption=""]
.Returns
`struct Concept*`

[#_◆_value_new_double_]
==== value_new_double

[source,cpp]
----
struct Concept* value_new_double(double double_)
----



Creates a new ``Value`` object of the specified double value.

[caption=""]
.Returns
`struct Concept*`

[#_◆_value_new_long_]
==== value_new_long

[source,cpp]
----
struct Concept* value_new_long(int64_t long_)
----



Creates a new ``Value`` object of the specified long value.

[caption=""]
.Returns
`struct Concept*`

[#_◆_value_new_string_]
==== value_new_string

[source,cpp]
----
struct Concept* value_new_string(const char* string)
----



Creates a new ``Value`` object of the specified string value.

[caption=""]
.Returns
`struct Concept*`

