[#_Attribute]
[.doc-api-reference-driver]
=== Attribute

`class`

*Package*: `typedb.api.concept.instance.attribute`

*Supertypes:*

* `Instance`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_as_attribute_]
==== method <code>as_attribute</code>

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
attribute.as_attribute()
----

[#_Attribute_get_boolean_]
==== method <code>get_boolean</code>

[source,python]
----
get_boolean() -> bool
----

Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.get_boolean()
----

[#_Attribute_get_date_]
==== method <code>get_date</code>

[source,python]
----
get_date() -> date
----

Returns a timezone naive ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`date`

[caption=""]
.Code examples
[source,python]
----
attribute.get_date()
----

[#_Attribute_get_datetime_]
==== method <code>get_datetime</code>

[source,python]
----
get_datetime() -> Datetime
----

Returns a timezone naive ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.get_datetime()
----

[#_Attribute_get_datetime_tz_]
==== method <code>get_datetime_tz</code>

[source,python]
----
get_datetime_tz() -> Datetime
----

Returns a timezone naive ``datetime_tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.get_datetime_tz()
----

[#_Attribute_get_decimal_]
==== method <code>get_decimal</code>

[source,python]
----
get_decimal() -> Decimal
----

Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Decimal`

[caption=""]
.Code examples
[source,python]
----
attribute.get_decimal()
----

[#_Attribute_get_double_]
==== method <code>get_double</code>

[source,python]
----
get_double() -> float
----

Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`float`

[caption=""]
.Code examples
[source,python]
----
attribute.get_double()
----

[#_Attribute_get_duration_]
==== method <code>get_duration</code>

[source,python]
----
get_duration() -> Duration
----

Returns a timezone naive ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,python]
----
attribute.get_duration()
----

[#_Attribute_get_integer_]
==== method <code>get_integer</code>

[source,python]
----
get_integer() -> int
----

Returns a ``integer`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,python]
----
attribute.get_integer()
----

[#_Attribute_get_string_]
==== method <code>get_string</code>

[source,python]
----
get_string() -> str
----

Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.get_string()
----

[#_Attribute_get_struct_]
==== method <code>get_struct</code>

[source,python]
----
get_struct() -> Concept.STRUCT
----

Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`Concept.STRUCT`

[caption=""]
.Code examples
[source,python]
----
attribute.get_struct()
----

[#_Attribute_get_type_]
==== method <code>get_type</code>

[source,python]
----
get_type() -> AttributeType
----

Retrieves the type which this ``Attribute`` belongs to.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
attribute.get_type()
----

[#_Attribute_get_value_]
==== method <code>get_value</code>

[source,python]
----
get_value() -> Concept.VALUE
----

Retrieves the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`Concept.VALUE`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value()
----

[#_Attribute_get_value_type_]
==== method <code>get_value_type</code>

[source,python]
----
get_value_type() -> str
----

Retrieves the description of the value type of the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value_type()
----

[#_Attribute_is_attribute_]
==== method <code>is_attribute</code>

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_attribute()
----

// end::methods[]

