[#_Attribute]
=== Attribute

`Class(name=Attribute, anchor=Attribute, enumConstants=[], description=[Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type., Attributes can be uniquely addressed by their type and value.], examples=[], fields=[], methods=[Method(name=as_attribute, signature=as_attribute() -> Attribute, anchor=Attribute_as_attribute_, args=[], description=[Casts the concept to ``Attribute``.], examples=[attribute.as_attribute()], mode=null, returnDescription=, returnType=Attribute), Method(name=get_boolean, signature=get_boolean() -> bool, anchor=Attribute_get_boolean_, args=[], description=[Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_boolean()], mode=null, returnDescription=, returnType=bool), Method(name=get_date, signature=get_date() -> date, anchor=Attribute_get_date_, args=[], description=[Returns a timezone naive ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_date()], mode=null, returnDescription=, returnType=date), Method(name=get_datetime, signature=get_datetime() -> Datetime, anchor=Attribute_get_datetime_, args=[], description=[Returns a timezone naive ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_datetime()], mode=null, returnDescription=, returnType=Datetime), Method(name=get_datetime_tz, signature=get_datetime_tz() -> Datetime, anchor=Attribute_get_datetime_tz_, args=[], description=[Returns a timezone naive ``datetime_tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_datetime_tz()], mode=null, returnDescription=, returnType=Datetime), Method(name=get_decimal, signature=get_decimal() -> Decimal, anchor=Attribute_get_decimal_, args=[], description=[Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_decimal()], mode=null, returnDescription=, returnType=Decimal), Method(name=get_double, signature=get_double() -> float, anchor=Attribute_get_double_, args=[], description=[Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_double()], mode=null, returnDescription=, returnType=float), Method(name=get_duration, signature=get_duration() -> Duration, anchor=Attribute_get_duration_, args=[], description=[Returns a timezone naive ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_duration()], mode=null, returnDescription=, returnType=Duration), Method(name=get_integer, signature=get_integer() -> int, anchor=Attribute_get_integer_, args=[], description=[Returns a ``integer`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_integer()], mode=null, returnDescription=, returnType=int), Method(name=get_string, signature=get_string() -> str, anchor=Attribute_get_string_, args=[], description=[Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception.], examples=[attribute.get_string()], mode=null, returnDescription=, returnType=str), Method(name=get_struct, signature=get_struct() -> Concept.STRUCT, anchor=Attribute_get_struct_, args=[], description=[Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception.], examples=[attribute.get_struct()], mode=null, returnDescription=, returnType=Concept.STRUCT), Method(name=get_type, signature=get_type() -> AttributeType, anchor=Attribute_get_type_, args=[], description=[Retrieves the type which this ``Attribute`` belongs to.], examples=[attribute.get_type()], mode=null, returnDescription=, returnType=AttributeType), Method(name=get_value, signature=get_value() -> Concept.VALUE, anchor=Attribute_get_value_, args=[], description=[Retrieves the value which the ``Attribute`` instance holds.], examples=[attribute.get_value()], mode=null, returnDescription=, returnType=Concept.VALUE), Method(name=get_value_type, signature=get_value_type() -> str, anchor=Attribute_get_value_type_, args=[], description=[Retrieves the description of the value type of the value which the ``Attribute`` instance holds.], examples=[attribute.get_value_type()], mode=null, returnDescription=, returnType=str), Method(name=is_attribute, signature=is_attribute() -> bool, anchor=Attribute_is_attribute_, args=[], description=[Checks if the concept is an ``Attribute``.], examples=[attribute.is_attribute()], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.concept.instance.attribute, superClasses=[Instance], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.concept.instance.attribute`

*Supertypes:*

* `Instance`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_as_attribute_]
==== as_attribute

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
attribute.as_attribute()
----

[#_Attribute_get_boolean_]
==== get_boolean

[source,python]
----
get_boolean() -> bool
----

Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.get_boolean()
----

[#_Attribute_get_date_]
==== get_date

[source,python]
----
get_date() -> date
----

Returns a timezone naive ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`date`

[caption=""]
.Code examples
[source,python]
----
attribute.get_date()
----

[#_Attribute_get_datetime_]
==== get_datetime

[source,python]
----
get_datetime() -> Datetime
----

Returns a timezone naive ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.get_datetime()
----

[#_Attribute_get_datetime_tz_]
==== get_datetime_tz

[source,python]
----
get_datetime_tz() -> Datetime
----

Returns a timezone naive ``datetime_tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.get_datetime_tz()
----

[#_Attribute_get_decimal_]
==== get_decimal

[source,python]
----
get_decimal() -> Decimal
----

Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Decimal`

[caption=""]
.Code examples
[source,python]
----
attribute.get_decimal()
----

[#_Attribute_get_double_]
==== get_double

[source,python]
----
get_double() -> float
----

Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`float`

[caption=""]
.Code examples
[source,python]
----
attribute.get_double()
----

[#_Attribute_get_duration_]
==== get_duration

[source,python]
----
get_duration() -> Duration
----

Returns a timezone naive ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,python]
----
attribute.get_duration()
----

[#_Attribute_get_integer_]
==== get_integer

[source,python]
----
get_integer() -> int
----

Returns a ``integer`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,python]
----
attribute.get_integer()
----

[#_Attribute_get_string_]
==== get_string

[source,python]
----
get_string() -> str
----

Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.get_string()
----

[#_Attribute_get_struct_]
==== get_struct

[source,python]
----
get_struct() -> Concept.STRUCT
----

Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`Concept.STRUCT`

[caption=""]
.Code examples
[source,python]
----
attribute.get_struct()
----

[#_Attribute_get_type_]
==== get_type

[source,python]
----
get_type() -> AttributeType
----

Retrieves the type which this ``Attribute`` belongs to.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
attribute.get_type()
----

[#_Attribute_get_value_]
==== get_value

[source,python]
----
get_value() -> Concept.VALUE
----

Retrieves the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`Concept.VALUE`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value()
----

[#_Attribute_get_value_type_]
==== get_value_type

[source,python]
----
get_value_type() -> str
----

Retrieves the description of the value type of the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value_type()
----

[#_Attribute_is_attribute_]
==== is_attribute

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_attribute()
----

// end::methods[]

