[#_Attribute]
=== Attribute

*Supertypes:*

* `Thing`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_as_attribute_]
==== as_attribute

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
attribute.as_attribute()
----

[#_Attribute_as_boolean_]
==== as_boolean

[source,python]
----
as_boolean() -> bool
----

Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.as_boolean()
----

[#_Attribute_as_date_]
==== as_date

[source,python]
----
as_date() -> date
----

Returns a timezone naive ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`date`

[caption=""]
.Code examples
[source,python]
----
attribute.as_date()
----

[#_Attribute_as_datetime_]
==== as_datetime

[source,python]
----
as_datetime() -> Datetime
----

Returns a timezone naive ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.as_datetime()
----

[#_Attribute_as_datetime_tz_]
==== as_datetime_tz

[source,python]
----
as_datetime_tz() -> Datetime
----

Returns a timezone naive ``datetime_tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.as_datetime_tz()
----

[#_Attribute_as_decimal_]
==== as_decimal

[source,python]
----
as_decimal() -> Decimal
----

Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Decimal`

[caption=""]
.Code examples
[source,python]
----
attribute.as_decimal()
----

[#_Attribute_as_double_]
==== as_double

[source,python]
----
as_double() -> float
----

Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`float`

[caption=""]
.Code examples
[source,python]
----
attribute.as_double()
----

[#_Attribute_as_duration_]
==== as_duration

[source,python]
----
as_duration() -> Duration
----

Returns a timezone naive ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,python]
----
attribute.as_duration()
----

[#_Attribute_as_long_]
==== as_long

[source,python]
----
as_long() -> int
----

Returns a ``long`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,python]
----
attribute.as_long()
----

[#_Attribute_as_string_]
==== as_string

[source,python]
----
as_string() -> str
----

Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.as_string()
----

[#_Attribute_as_struct_]
==== as_struct

[source,python]
----
as_struct() -> Dict[str, Value | None]
----

Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`Dict[str, Value | None]`

[caption=""]
.Code examples
[source,python]
----
attribute.as_struct()
----

[#_Attribute_get_type_]
==== get_type

[source,python]
----
get_type() -> AttributeType
----

Retrieves the type which this ``Attribute`` belongs to.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
attribute.get_type()
----

[#_Attribute_get_value_]
==== get_value

[source,python]
----
get_value() -> VALUE
----

Retrieves the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`VALUE`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value()
----

[#_Attribute_is_attribute_]
==== is_attribute

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_attribute()
----

[#_Attribute_is_boolean_]
==== is_boolean

[source,python]
----
is_boolean() -> bool
----

Returns ``True`` if this attribute holds a value of type ``boolean``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_boolean()
----

[#_Attribute_is_date_]
==== is_date

[source,python]
----
is_date() -> bool
----

Returns ``True`` if this attribute holds a value of type ``date``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_date()
----

[#_Attribute_is_datetime_]
==== is_datetime

[source,python]
----
is_datetime() -> bool
----

Returns ``True`` if this attribute holds a value of type ``datetime``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_datetime()
----

[#_Attribute_is_datetime_tz_]
==== is_datetime_tz

[source,python]
----
is_datetime_tz() -> bool
----

Returns ``True`` if this attribute holds a value of type ``datetime_tz``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_datetime_tz()
----

[#_Attribute_is_decimal_]
==== is_decimal

[source,python]
----
is_decimal() -> bool
----

Returns ``True`` if this attribute holds a value of type ``decimal``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_decimal()
----

[#_Attribute_is_double_]
==== is_double

[source,python]
----
is_double() -> bool
----

Returns ``True`` if this attribute holds a value of type ``double``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_double()
----

[#_Attribute_is_duration_]
==== is_duration

[source,python]
----
is_duration() -> bool
----

Returns ``True`` if this attribute holds a value of type ``duration``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_duration()
----

[#_Attribute_is_long_]
==== is_long

[source,python]
----
is_long() -> bool
----

Returns ``True`` if this attribute holds a value of type ``long``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_long()
----

[#_Attribute_is_string_]
==== is_string

[source,python]
----
is_string() -> bool
----

Returns ``True`` if this attribute holds a value of type ``string``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_string()
----

[#_Attribute_is_struct_]
==== is_struct

[source,python]
----
is_struct() -> bool
----

Returns ``True`` if this attribute holds a value of type ``struct``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_struct()
----

// end::methods[]

