[#_Instance]
=== Instance

`Class(name=Instance, anchor=Instance, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=as_instance, signature=as_instance() -> Instance, anchor=Instance_as_instance_, args=[], description=[Casts the concept to ``Instance``.], examples=[instance.as_instance()], mode=null, returnDescription=, returnType=Instance), Method(name=get_type, signature=get_type() -> Type, anchor=Instance_get_type_, args=[], description=[Retrieves the type which this ``Instance`` belongs to.], examples=[instance.get_type()], mode=null, returnDescription=, returnType=Type), Method(name=is_instance, signature=is_instance() -> bool, anchor=Instance_is_instance_, args=[], description=[Checks if the concept is a ``Instance``.], examples=[instance.is_instance()], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.concept.instance.instance, superClasses=[Concept], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.concept.instance.instance`

*Supertypes:*

* `Concept`

// tag::methods[]
[#_Instance_as_instance_]
==== as_instance

[source,python]
----
as_instance() -> Instance
----

Casts the concept to ``Instance``.

[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,python]
----
instance.as_instance()
----

[#_Instance_get_type_]
==== get_type

[source,python]
----
get_type() -> Type
----

Retrieves the type which this ``Instance`` belongs to.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,python]
----
instance.get_type()
----

[#_Instance_is_instance_]
==== is_instance

[source,python]
----
is_instance() -> bool
----

Checks if the concept is a ``Instance``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
instance.is_instance()
----

// end::methods[]

