[#_Relation]
=== Relation

`Class(name=Relation, anchor=Relation, enumConstants=[], description=[Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.], examples=[], fields=[], methods=[Method(name=as_relation, signature=as_relation() -> Relation, anchor=Relation_as_relation_, args=[], description=[Casts the concept to ``Relation``.], examples=[relation.as_relation()], mode=null, returnDescription=, returnType=Relation), Method(name=get_iid, signature=get_iid() -> str, anchor=Relation_get_iid_, args=[], description=[Retrieves the unique id of the ``Relation``.], examples=[relation.get_iid()], mode=null, returnDescription=, returnType=str), Method(name=get_type, signature=get_type() -> RelationType, anchor=Relation_get_type_, args=[], description=[Retrieves the type which this ``Relation`` belongs to.], examples=[relation.get_type()], mode=null, returnDescription=, returnType=RelationType), Method(name=is_relation, signature=is_relation() -> bool, anchor=Relation_is_relation_, args=[], description=[Checks if the concept is a ``Relation``.], examples=[relation.is_relation()], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.concept.instance.relation, superClasses=[Instance], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.concept.instance.relation`

*Supertypes:*

* `Instance`

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

// tag::methods[]
[#_Relation_as_relation_]
==== as_relation

[source,python]
----
as_relation() -> Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,python]
----
relation.as_relation()
----

[#_Relation_get_iid_]
==== get_iid

[source,python]
----
get_iid() -> str
----

Retrieves the unique id of the ``Relation``.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
relation.get_iid()
----

[#_Relation_get_type_]
==== get_type

[source,python]
----
get_type() -> RelationType
----

Retrieves the type which this ``Relation`` belongs to.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
relation.get_type()
----

[#_Relation_is_relation_]
==== is_relation

[source,python]
----
is_relation() -> bool
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
relation.is_relation()
----

// end::methods[]

