[#_Value]
=== Value

`Class(name=Value, anchor=Value, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=as_value, signature=as_value() -> Value, anchor=Value_as_value_, args=[], description=[Casts the concept to ``Value``.], examples=[value.as_value()], mode=null, returnDescription=, returnType=Value), Method(name=get, signature=get() -> bool | int | float | Decimal | str | date | Datetime | Duration | Dict[str, Value | None], anchor=Value_get_, args=[], description=[Retrieves the value which this value concept holds.], examples=[value.get()], mode=null, returnDescription=, returnType=bool | int | float | Decimal | str | date | Datetime | Duration | Dict[str, Value | None]), Method(name=get_boolean, signature=get_boolean() -> bool, anchor=Value_get_boolean_, args=[], description=[Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_boolean()], mode=null, returnDescription=, returnType=bool), Method(name=get_date, signature=get_date() -> date, anchor=Value_get_date_, args=[], description=[Returns a timezone naive ``date`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_date()], mode=null, returnDescription=, returnType=date), Method(name=get_datetime, signature=get_datetime() -> Datetime, anchor=Value_get_datetime_, args=[], description=[Returns a timezone naive ``datetime`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_datetime()], mode=null, returnDescription=, returnType=Datetime), Method(name=get_datetime_tz, signature=get_datetime_tz() -> Datetime, anchor=Value_get_datetime_tz_, args=[], description=[Returns a timezone naive ``datetime_tz`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_datetime_tz()], mode=null, returnDescription=, returnType=Datetime), Method(name=get_decimal, signature=get_decimal() -> Decimal, anchor=Value_get_decimal_, args=[], description=[Returns a ``decimal`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_decimal()], mode=null, returnDescription=, returnType=Decimal), Method(name=get_double, signature=get_double() -> float, anchor=Value_get_double_, args=[], description=[Returns a ``double`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_double()], mode=null, returnDescription=, returnType=float), Method(name=get_duration, signature=get_duration() -> Duration, anchor=Value_get_duration_, args=[], description=[Returns a timezone naive ``duration`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_duration()], mode=null, returnDescription=, returnType=Duration), Method(name=get_integer, signature=get_integer() -> int, anchor=Value_get_integer_, args=[], description=[Returns a ``integer`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_integer()], mode=null, returnDescription=, returnType=int), Method(name=get_string, signature=get_string() -> str, anchor=Value_get_string_, args=[], description=[Returns a ``string`` value of this value concept. If the value has another type, raises an exception.], examples=[value.get_string()], mode=null, returnDescription=, returnType=str), Method(name=get_struct, signature=get_struct() -> Dict[str, Value | None], anchor=Value_get_struct_, args=[], description=[Returns a ``struct`` value of this value concept represented as a map from field names to values. If the value has another type, raises an exception.], examples=[value.get_struct()], mode=null, returnDescription=, returnType=Dict[str, Value | None]), Method(name=get_type, signature=get_type() -> str, anchor=Value_get_type_, args=[], description=[Retrieves the ``str`` describing the value type of this ``Value`` concept.], examples=[value.get_type()], mode=null, returnDescription=, returnType=str), Method(name=is_value, signature=is_value() -> bool, anchor=Value_is_value_, args=[], description=[Checks if the concept is a ``Value``.], examples=[value.is_value()], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.concept.value.value, superClasses=[Concept], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.concept.value.value`

*Supertypes:*

* `Concept`

// tag::methods[]
[#_Value_as_value_]
==== as_value

[source,python]
----
as_value() -> Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,python]
----
value.as_value()
----

[#_Value_get_]
==== get

[source,python]
----
get() -> bool | int | float | Decimal | str | date | Datetime | Duration | Dict[str, Value | None]
----

Retrieves the value which this value concept holds.

[caption=""]
.Returns
`bool | int | float | Decimal | str | date | Datetime | Duration | Dict[str, Value | None]`

[caption=""]
.Code examples
[source,python]
----
value.get()
----

[#_Value_get_boolean_]
==== get_boolean

[source,python]
----
get_boolean() -> bool
----

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
value.get_boolean()
----

[#_Value_get_date_]
==== get_date

[source,python]
----
get_date() -> date
----

Returns a timezone naive ``date`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`date`

[caption=""]
.Code examples
[source,python]
----
value.get_date()
----

[#_Value_get_datetime_]
==== get_datetime

[source,python]
----
get_datetime() -> Datetime
----

Returns a timezone naive ``datetime`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
value.get_datetime()
----

[#_Value_get_datetime_tz_]
==== get_datetime_tz

[source,python]
----
get_datetime_tz() -> Datetime
----

Returns a timezone naive ``datetime_tz`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[caption=""]
.Code examples
[source,python]
----
value.get_datetime_tz()
----

[#_Value_get_decimal_]
==== get_decimal

[source,python]
----
get_decimal() -> Decimal
----

Returns a ``decimal`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Decimal`

[caption=""]
.Code examples
[source,python]
----
value.get_decimal()
----

[#_Value_get_double_]
==== get_double

[source,python]
----
get_double() -> float
----

Returns a ``double`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`float`

[caption=""]
.Code examples
[source,python]
----
value.get_double()
----

[#_Value_get_duration_]
==== get_duration

[source,python]
----
get_duration() -> Duration
----

Returns a timezone naive ``duration`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,python]
----
value.get_duration()
----

[#_Value_get_integer_]
==== get_integer

[source,python]
----
get_integer() -> int
----

Returns a ``integer`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,python]
----
value.get_integer()
----

[#_Value_get_string_]
==== get_string

[source,python]
----
get_string() -> str
----

Returns a ``string`` value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
value.get_string()
----

[#_Value_get_struct_]
==== get_struct

[source,python]
----
get_struct() -> Dict[str, Value | None]
----

Returns a ``struct`` value of this value concept represented as a map from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`Dict[str, Value | None]`

[caption=""]
.Code examples
[source,python]
----
value.get_struct()
----

[#_Value_get_type_]
==== get_type

[source,python]
----
get_type() -> str
----

Retrieves the ``str`` describing the value type of this ``Value`` concept.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
value.get_type()
----

[#_Value_is_value_]
==== is_value

[source,python]
----
is_value() -> bool
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
value.is_value()
----

// end::methods[]

