[#_methods__answer__primitives]
=== primitives

[#_Struct_StringIterator]
==== Struct StringIterator



Iterator over the strings in the result of a request or a TypeQL Fetch query.

[#_Struct_StringPair]
==== Struct StringPair



A ``StringPair`` used to represent the pair of variables involved in an ownership. ``_0`` and ``_1`` are the owner and attribute variables respectively.

[#_Struct_StringPairIterator]
==== Struct StringPairIterator



Iterator over the ``StringPair``s representing explainable owner-attribute variable pairs

[#_Struct_StringPromise]
==== Struct StringPromise



Promise object representing the result of an asynchronous operation. Use string_promise_resolve(StringPromise*) to wait for and retrieve the resulting string.

[#_string_free]
==== string_free

[source,cpp]
----
void string_free(char* str)
----



Frees a native rust string. _WARNING: Always use this function to free strings returned by the driver. Using the standard C free function will create a dangling reference on the rust side._

[caption=""]
.Returns
`void`

[#_string_iterator_drop]
==== string_iterator_drop

[source,cpp]
----
void string_iterator_drop(struct StringIterator* it)
----



Frees the native rust ``StringIterator`` object

[caption=""]
.Returns
`void`

[#_string_iterator_next]
==== string_iterator_next

[source,cpp]
----
char* string_iterator_next(struct StringIterator* it)
----



Forwards the ``StringIterator`` and returns the next string if it exists, or null if there are no more elements.

[caption=""]
.Returns
`char*`

[#_string_pair_drop]
==== string_pair_drop

[source,cpp]
----
void string_pair_drop(struct StringPair* string_pair)
----



Frees the native rust ``StringPair`` object

[caption=""]
.Returns
`void`

[#_string_pair_iterator_drop]
==== string_pair_iterator_drop

[source,cpp]
----
void string_pair_iterator_drop(struct StringPairIterator* it)
----



Frees the native rust ``StringPairIterator`` object

[caption=""]
.Returns
`void`

[#_string_pair_iterator_next]
==== string_pair_iterator_next

[source,cpp]
----
struct StringPair* string_pair_iterator_next(struct StringPairIterator* it)
----



Forwards the ``StringIterator`` and returns the next ``StringPair`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct StringPair*`

[#_string_promise_resolve]
==== string_promise_resolve

[source,cpp]
----
char* string_promise_resolve(struct StringPromise* promise)
----



Waits for and returns the result of the operation represented by the ``BoolPromise`` object. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`char*`

[#_methods__answer__primitives]
=== primitives

[#_Struct_BoolPromise]
==== Struct BoolPromise



Promise object representing the result of an asynchronous operation. Use bool_promise_resolve(BoolPromise*) to wait for and retrieve the resulting boolean value.

[#_bool_promise_resolve]
==== bool_promise_resolve

[source,cpp]
----
bool bool_promise_resolve(struct BoolPromise* promise)
----



Waits for and returns the result of the operation represented by the ``BoolPromise`` object. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`bool`

[#_methods__answer__primitives]
=== primitives

[#_Struct_VoidPromise]
==== Struct VoidPromise



Promise object representing the result of an asynchronous operation. A VoidPromise does not return a value, but must be resolved using void_promise_resolve(VoidPromise*) to ensure the operation has completed, or for a failed operation to set the error.

[#_void_promise_resolve]
==== void_promise_resolve

[source,cpp]
----
void void_promise_resolve(struct VoidPromise* promise)
----



Waits for the operation represented by the ``VoidPromise`` to complete. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`void`

