[#_struct_QueryManager]
=== QueryManager

*Implements traits:*

* `Debug`

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_struct_QueryManager_method_define]
==== define

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn define(&self, query: &str) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn define(&self, query: &str) -> Result
----

--
====

Performs a TypeQL Define query with default options. See <<#_struct_QueryManager_method_define_with_options,`QueryManager::define_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_QueryManager_method_define_with_options]
==== define_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn define_with_options(&self, query: &str, options: Options) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn define_with_options(&self, query: &str, options: Options) -> Result
----

--
====

Performs a TypeQL Define query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().define_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().define_with_options(query, options)
----

--
====

[#_struct_QueryManager_method_delete]
==== delete

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn delete(&self, query: &str) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn delete(&self, query: &str) -> Result
----

--
====

Performs a TypeQL Delete query with default options. See <<#_struct_QueryManager_method_delete_with_options,`QueryManager::delete_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_QueryManager_method_delete_with_options]
==== delete_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn delete_with_options(&self, query: &str, options: Options) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn delete_with_options(&self, query: &str, options: Options) -> Result
----

--
====

Performs a TypeQL Delete query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().delete_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().delete_with_options(query, options)
----

--
====

[#_struct_QueryManager_method_explain]
==== explain

[source,rust]
----
pub fn explain(
    &self,
    explainable: &Explainable
) -> Result<impl Stream<Item = Result<Explanation>>>
----

Performs a TypeQL Explain query in the transaction. See ``QueryManager::explain_with_options

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<Explanation>>>
----

[#_struct_QueryManager_method_explain_with_options]
==== explain_with_options

[source,rust]
----
pub fn explain_with_options(
    &self,
    explainable: &Explainable,
    options: Options
) -> Result<impl Stream<Item = Result<Explanation>>>
----

Performs a TypeQL Explain query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `&Explainable`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<Explanation>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().explain_with_options(explainable, options)
----

[#_struct_QueryManager_method_insert]
==== insert

[source,rust]
----
pub fn insert(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Insert query with default options. See <<#_struct_QueryManager_method_insert_with_options,`QueryManager::insert_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[#_struct_QueryManager_method_insert_with_options]
==== insert_with_options

[source,rust]
----
pub fn insert_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Insert query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().insert_with_options(query, options)
----

[#_struct_QueryManager_method_match]
==== match_

[source,rust]
----
pub fn match_(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Match (Get) query with default options. See <<#_struct_QueryManager_method_match_with_options,`QueryManager::match_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[#_struct_QueryManager_method_match_aggregate]
==== match_aggregate

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn match_aggregate(&self, query: &str) -> Result<Numeric>
----

--

sync::
+
--
[source,rust]
----
pub fn match_aggregate(&self, query: &str) -> Result<Numeric>
----

--
====

Performs a TypeQL Match Aggregate query with default options. See <<#_struct_QueryManager_method_match_aggregate,`QueryManager::match_aggregate`>>

[caption=""]
.Returns
[source,rust]
----
Result<Numeric>
----

[#_struct_QueryManager_method_match_aggregate_with_options]
==== match_aggregate_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn match_aggregate_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<Numeric>
----

--

sync::
+
--
[source,rust]
----
pub fn match_aggregate_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<Numeric>
----

--
====

Performs a TypeQL Match Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Aggregate query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Numeric>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().match_aggregate_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().match_aggregate_with_options(query, options)
----

--
====

[#_struct_QueryManager_method_match_group]
==== match_group

[source,rust]
----
pub fn match_group(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMapGroup>>>
----

Performs a TypeQL Match Group query with default options. See <<#_struct_QueryManager_method_match_group,`QueryManager::match_group`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMapGroup>>>
----

[#_struct_QueryManager_method_match_group_aggregate]
==== match_group_aggregate

[source,rust]
----
pub fn match_group_aggregate(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<NumericGroup>>>
----

Performs a TypeQL Match Group Aggregate query with default options. See <<#_struct_QueryManager_method_match_group_aggregate_with_options,`QueryManager::match_group_aggregate_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<NumericGroup>>>
----

[#_struct_QueryManager_method_match_group_aggregate_with_options]
==== match_group_aggregate_with_options

[source,rust]
----
pub fn match_group_aggregate_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<NumericGroup>>>
----

Performs a TypeQL Match Group Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<NumericGroup>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().match_group_aggregate(query, options)
----

[#_struct_QueryManager_method_match_group_with_options]
==== match_group_with_options

[source,rust]
----
pub fn match_group_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMapGroup>>>
----

Performs a TypeQL Match Group query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMapGroup>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().match_group_with_options(query, options)
----

[#_struct_QueryManager_method_match_with_options]
==== match_with_options

[source,rust]
----
pub fn match_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Match (Get) query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match (Get) query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().match_with_options(query, options)
----

[#_struct_QueryManager_method_undefine]
==== undefine

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn undefine(&self, query: &str) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn undefine(&self, query: &str) -> Result
----

--
====

Performs a TypeQL Undefine query with default options See <<#_struct_QueryManager_method_undefine_with_options,`QueryManager::undefine_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_QueryManager_method_undefine_with_options]
==== undefine_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn undefine_with_options(&self, query: &str, options: Options) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn undefine_with_options(&self, query: &str, options: Options) -> Result
----

--
====

Performs a TypeQL Undefine query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().undefine_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().undefine_with_options(query, options)
----

--
====

[#_struct_QueryManager_method_update]
==== update

[source,rust]
----
pub fn update(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Update query with default options. See <<#_struct_QueryManager_method_update_with_options,`QueryManager::update_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[#_struct_QueryManager_method_update_with_options]
==== update_with_options

[source,rust]
----
pub fn update_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>>>
----

Performs a TypeQL Update query in the transaction.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>>>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().update_with_options(query, options)
----

// end::methods[]

