[#_struct_QueryManager]
=== QueryManager

*Implements traits:*

* `Debug`

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_struct_QueryManager_define__]
==== define

[source,rust]
----
pub fn define(&self, query: &str) -> impl Promise<'tx, Result>
----

Performs a TypeQL Define query with default options. See <<#_struct_QueryManager_method_define_with_options,`QueryManager::define_with_options`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[#_struct_QueryManager_define_with_options__query_str__options_Options]
==== define_with_options

[source,rust]
----
pub fn define_with_options(
    &self,
    query: &str,
    options: Options
) -> impl Promise<'tx, Result>
----

Performs a TypeQL Define query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().define_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().define_with_options(query, options).resolve()
----

--
====

[#_struct_QueryManager_delete__]
==== delete

[source,rust]
----
pub fn delete(&self, query: &str) -> impl Promise<'tx, Result>
----

Performs a TypeQL Delete query with default options. See <<#_struct_QueryManager_method_delete_with_options,`QueryManager::delete_with_options`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[#_struct_QueryManager_delete_with_options__query_str__options_Options]
==== delete_with_options

[source,rust]
----
pub fn delete_with_options(
    &self,
    query: &str,
    options: Options
) -> impl Promise<'tx, Result>
----

Performs a TypeQL Delete query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().delete_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().delete_with_options(query, options).resolve()
----

--
====

[#_struct_QueryManager_explain__]
==== explain

[source,rust]
----
pub fn explain(
    &self,
    explainable: &Explainable
) -> Result<impl Stream<Item = Result<Explanation>> + 'tx>
----

Performs a TypeQL Explain query in the transaction. See ``QueryManager::explain_with_options

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<Explanation>> + 'tx>
----

[#_struct_QueryManager_explain_with_options__explainable_Explainable__options_Options]
==== explain_with_options

[source,rust]
----
pub fn explain_with_options(
    &self,
    explainable: &Explainable,
    options: Options
) -> Result<impl Stream<Item = Result<Explanation>> + 'tx>
----

Performs a TypeQL Explain query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `&Explainable`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<Explanation>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().explain_with_options(explainable, options)
----

[#_struct_QueryManager_fetch__]
==== fetch

[source,rust]
----
pub fn fetch(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<JSON>> + 'tx>
----

Performs a TypeQL Fetch query with default options. See <<#_struct_QueryManager_method_fetch_with_options,`QueryManager::fetch_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<JSON>> + 'tx>
----

[#_struct_QueryManager_fetch_with_options__query_str__options_Options]
==== fetch_with_options

[source,rust]
----
pub fn fetch_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<JSON>> + 'tx>
----

Performs a TypeQL Match Group Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<JSON>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().fetch_with_options(query, options)
----

[#_struct_QueryManager_get__]
==== get

[source,rust]
----
pub fn get(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Match (Get) query with default options. See <<#_struct_QueryManager_method_get_with_options,`QueryManager::get_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[#_struct_QueryManager_get_aggregate__]
==== get_aggregate

[source,rust]
----
pub fn get_aggregate(
    &self,
    query: &str
) -> impl Promise<'tx, Result<Option<Value>>>
----

Performs a TypeQL Match Aggregate query with default options. See <<#_struct_QueryManager_method_get_aggregate,`QueryManager::get_aggregate`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<Value>>>
----

[#_struct_QueryManager_get_aggregate_with_options__query_str__options_Options]
==== get_aggregate_with_options

[source,rust]
----
pub fn get_aggregate_with_options(
    &self,
    query: &str,
    options: Options
) -> impl Promise<'tx, Result<Option<Value>>>
----

Performs a TypeQL Match Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Aggregate query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<Value>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().get_aggregate_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().get_aggregate_with_options(query, options).resolve()
----

--
====

[#_struct_QueryManager_get_group__]
==== get_group

[source,rust]
----
pub fn get_group(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMapGroup>> + 'tx>
----

Performs a TypeQL Match Group query with default options. See <<#_struct_QueryManager_method_get_group,`QueryManager::get_group`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMapGroup>> + 'tx>
----

[#_struct_QueryManager_get_group_aggregate__]
==== get_group_aggregate

[source,rust]
----
pub fn get_group_aggregate(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ValueGroup>> + 'tx>
----

Performs a TypeQL Match Group Aggregate query with default options. See <<#_struct_QueryManager_method_get_group_aggregate_with_options,`QueryManager::get_group_aggregate_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ValueGroup>> + 'tx>
----

[#_struct_QueryManager_get_group_aggregate_with_options__query_str__options_Options]
==== get_group_aggregate_with_options

[source,rust]
----
pub fn get_group_aggregate_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ValueGroup>> + 'tx>
----

Performs a TypeQL Match Group Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ValueGroup>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().get_group_aggregate_with_options(query, options)
----

[#_struct_QueryManager_get_group_with_options__query_str__options_Options]
==== get_group_with_options

[source,rust]
----
pub fn get_group_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMapGroup>> + 'tx>
----

Performs a TypeQL Match Group query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMapGroup>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().get_group_with_options(query, options)
----

[#_struct_QueryManager_get_with_options__query_str__options_Options]
==== get_with_options

[source,rust]
----
pub fn get_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Match (Get) query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match (Get) query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().get_with_options(query, options)
----

[#_struct_QueryManager_insert__]
==== insert

[source,rust]
----
pub fn insert(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Insert query with default options. See <<#_struct_QueryManager_method_insert_with_options,`QueryManager::insert_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[#_struct_QueryManager_insert_with_options__query_str__options_Options]
==== insert_with_options

[source,rust]
----
pub fn insert_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Insert query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().insert_with_options(query, options)
----

[#_struct_QueryManager_undefine__]
==== undefine

[source,rust]
----
pub fn undefine(&self, query: &str) -> impl Promise<'tx, Result>
----

Performs a TypeQL Undefine query with default options See <<#_struct_QueryManager_method_undefine_with_options,`QueryManager::undefine_with_options`>>

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[#_struct_QueryManager_undefine_with_options__query_str__options_Options]
==== undefine_with_options

[source,rust]
----
pub fn undefine_with_options(
    &self,
    query: &str,
    options: Options
) -> impl Promise<'tx, Result>
----

Performs a TypeQL Undefine query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.query().undefine_with_options(query, options).await
----

--

sync::
+
--
[source,rust]
----
transaction.query().undefine_with_options(query, options).resolve()
----

--
====

[#_struct_QueryManager_update__]
==== update

[source,rust]
----
pub fn update(
    &self,
    query: &str
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Update query with default options. See <<#_struct_QueryManager_method_update_with_options,`QueryManager::update_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[#_struct_QueryManager_update_with_options__query_str__options_Options]
==== update_with_options

[source,rust]
----
pub fn update_with_options(
    &self,
    query: &str,
    options: Options
) -> Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

Performs a TypeQL Update query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `&str`
a| `options` a| Specify query options a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<ConceptMap>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.query().update_with_options(query, options)
----

// end::methods[]

