[#_QueryManager]
=== QueryManager

*Package*: `TypeDB`



Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_a730553d491e3a1feb08f1b12804861eb]
==== define

[source,cpp]
----
VoidFuture TypeDB::QueryManager::define(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Define query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a3d04852ac62b3c93c3af5ee7830069a4]
==== explain

[source,cpp]
----
ExplanationIterable TypeDB::QueryManager::explain(const Explainable& explainable, const Options& = Options()) const
----



Performs a TypeQL Explain query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ExplanationIterable`

[#_a5e0dff39702ebeca0386b5825d4d46a7]
==== fetch

[source,cpp]
----
JSONIterable TypeDB::QueryManager::fetch(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Fetch query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Fetch query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`JSONIterable`

[#_afdf40c3a101625e8ac0fa76671ac3696]
==== get

[source,cpp]
----
ConceptMapIterable TypeDB::QueryManager::get(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Get query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ConceptMapIterable`

[#_a527000a169865c097a4b0d9a436bf2e6]
==== getAggregate

[source,cpp]
----
AggregateFuture TypeDB::QueryManager::getAggregate(const std::string& query, const Options& = Options()) const
----



Performs a TypeQL Get Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Aggregate query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`AggregateFuture`

[#_a8eade8379b967da5a13d342b3974f725]
==== getGroup

[source,cpp]
----
ConceptMapGroupIterable TypeDB::QueryManager::getGroup(const std::string& query, const Options& = Options()) const
----



Performs a TypeQL Get Group query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ConceptMapGroupIterable`

[#_a2a464c315cba60d906c066fe0d3fd957]
==== getGroupAggregate

[source,cpp]
----
ValueGroupIterable TypeDB::QueryManager::getGroupAggregate(const std::string& query, const Options& = Options()) const
----



Performs a TypeQL Get Group Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group Aggregate query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ValueGroupIterable`

[#_ae43e746a66a58f5f9b1bddccc4d5f6a0]
==== insert

[source,cpp]
----
ConceptMapIterable TypeDB::QueryManager::insert(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Insert query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ConceptMapIterable`

[#_ae3f3240f800c49d34e8d84d51993b173]
==== matchDelete

[source,cpp]
----
VoidFuture TypeDB::QueryManager::matchDelete(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Delete query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_aad5516f19190f2ceb6a84295e5d48024]
==== undefine

[source,cpp]
----
VoidFuture TypeDB::QueryManager::undefine(const std::string& query, const Options& options = Options()) const
----



Performs a TypeQL Undefine query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a228f4986414e36e2b8875544a6b28222]
==== update

[source,cpp]
----
ConceptMapIterable TypeDB::QueryManager::update(const std::string& query, const Options& = Options()) const
----



Performs a TypeQL Update query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`ConceptMapIterable`

// end::methods[]

