[#_Transaction]
=== Transaction

*Package*: `TypeDB`



A transaction with a TypeDB database.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `concepts` a| `const ConceptManager TypeDB::Transaction` a| The ``ConceptManager`` for this transaction, providing access to all Concept API methods.
a| `logic` a| `const LogicManager TypeDB::Transaction` a| The ``LogicManager`` for this Transaction, providing access to all Concept API - Logic methods.
a| `query` a| `const QueryManager TypeDB::Transaction` a| The````QueryManager```` for this Transaction, from which any TypeQL query can be executed.
|===
// end::properties[]

// tag::methods[]
[#_void_TypeDBTransactionclose___]
==== close

[source,cpp]
----
void TypeDB::Transaction::close()
----



Closes the transaction.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
transaction.close()
----

[#_void_TypeDBTransactioncommit___]
==== commit

[source,cpp]
----
void TypeDB::Transaction::commit()
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
transaction.commit()
----

[#_void_TypeDBTransactionforceClose___]
==== forceClose

[source,cpp]
----
void TypeDB::Transaction::forceClose()
----



Closes the transaction.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
transaction.close()
----

[#_bool_TypeDBTransactionisOpen_____const]
==== isOpen

[source,cpp]
----
bool TypeDB::Transaction::isOpen() const
----



Checks whether this transaction is open.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
transaction.isOpen();
----

[#_void_TypeDBTransactiononClose___stdfunction__void_const_stdoptional__DriverException______callback_]
==== onClose

[source,cpp]
----
void TypeDB::Transaction::onClose(std::function< void(const std::optional< DriverException >&)> callback)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
transaction.onClose(function);
----

[#_void_TypeDBTransactionrollback___]
==== rollback

[source,cpp]
----
void TypeDB::Transaction::rollback()
----



Rolls back the uncommitted changes made via this transaction.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
transaction.rollback()
----

[#_TypeDBTransactionType_TypeDBTransactiontype_____const]
==== type

[source,cpp]
----
TypeDB::TransactionType TypeDB::Transaction::type() const
----



The transaction’s type (READ or WRITE)

[caption=""]
.Returns
`TypeDB::TransactionType`

// end::methods[]

