[#_Transaction]
=== Transaction

*Package*: `TypeDB`



A transaction with a TypeDB database.

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `concepts` a| `const ConceptManager TypeDB::Transaction` a| The ``ConceptManager`` for this transaction, providing access to all Concept API methods.
a| `logic` a| `const LogicManager TypeDB::Transaction` a| The ``LogicManager`` for this Transaction, providing access to all Concept API - Logic methods.
a| `query` a| `const QueryManager TypeDB::Transaction` a| The````QueryManager```` for this Transaction, from which any TypeQL query can be executed.
|===
// end::properties[]

// tag::methods[]
[#_a72b95076b272216dbaa8429ce8099cf1]
==== close

[source,cpp]
----
void TypeDB::Transaction::close()
----



Closes the transaction.


[caption=""]
.Returns
`void`

[#_ae08dac47fd65d68598b56473f706519f]
==== commit

[source,cpp]
----
void TypeDB::Transaction::commit()
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.


[caption=""]
.Returns
`void`

[#_a7f9a154ee5f9b23afdcbfd5386b7d071]
==== forceClose

[source,cpp]
----
void TypeDB::Transaction::forceClose()
----



Closes the transaction.


[caption=""]
.Returns
`void`

[#_ae27c571ce26376e474ef587c65d15e24]
==== isOpen

[source,cpp]
----
bool TypeDB::Transaction::isOpen() const
----



Checks whether this transaction is open.


[caption=""]
.Returns
`bool`

[#_a3acde5cc7b85e8dabedd46d07b1c5863]
==== onClose

[source,cpp]
----
void TypeDB::Transaction::onClose(std::function< void(const std::optional< DriverException >&)> callback)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
`void`

[#_adcb322bac345023cf69332c4aa736e76]
==== rollback

[source,cpp]
----
void TypeDB::Transaction::rollback()
----



Rolls back the uncommitted changes made via this transaction.


[caption=""]
.Returns
`void`

[#_a7d3d9b771b4464a44a4bba6e98c8c592]
==== type

[source,cpp]
----
TypeDB::TransactionType TypeDB::Transaction::type() const
----



The transaction’s type (READ or WRITE)

[caption=""]
.Returns
`TypeDB::TransactionType`

// end::methods[]

