[#_EntityType]
=== EntityType

*Supertypes:*

* `ThingType`

Entity types represent the classification of independent objects in the data model of the business domain.

// tag::methods[]
[#_EntityType_as_entity_type__]
==== as_entity_type

[source,python]
----
as_entity_type() -> EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,python]
----
entity_type.as_entity_type()
----

[#_EntityType_create__transaction_TypeDBTransaction]
==== create

[source,python]
----
create(transaction: TypeDBTransaction) -> Promise[Entity]
----

Creates and returns a new instance of this ``EntityType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[Entity]`

[caption=""]
.Code examples
[source,python]
----
entity_type.create(transaction).resolve()
----

[#_EntityType_get_instances__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_instances

[source,python]
----
get_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Entity]
----

Retrieves all direct and indirect (or direct only) ``Entity`` objects that are instances of this ``EntityType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct instances only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Entity]`

[caption=""]
.Code examples
[source,python]
----
entity_type.get_instances(transaction, transitivity)
----

[#_EntityType_get_subtypes__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[EntityType]
----

Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[EntityType]`

[caption=""]
.Code examples
[source,python]
----
entity_type.get_subtypes(transaction, transitivity)
----

[#_EntityType_is_entity_type__]
==== is_entity_type

[source,python]
----
is_entity_type() -> bool
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
entity_type.is_entity_type()
----

[#_EntityType_set_supertype__transaction_TypeDBTransaction__super_entity_type_EntityType]
==== set_supertype

[source,python]
----
set_supertype(transaction: TypeDBTransaction, super_entity_type: EntityType) -> Promise[None]
----

Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `super_entity_type` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
entity_type.set_supertype(transaction, super_entity_type).resolve()
----

// end::methods[]

