[#_RoleType]
=== RoleType

*Supertypes:*

* `Type`

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type.

Roles allow a schema to enforce logical constraints on types of role players.

// tag::methods[]
[#_RoleType_as_role_type__]
==== as_role_type

[source,python]
----
as_role_type() -> RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,python]
----
role_type.as_role_type()
----

[#_RoleType_get_player_instances__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_player_instances

[source,python]
----
get_player_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Thing]
----

Retrieves the ``Thing`` instances that play this role.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Thing]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_player_instances(transaction, transitivity)
----

[#_RoleType_get_player_types__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_player_types

[source,python]
----
get_player_types(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[ThingType]
----

Retrieves the ``ThingType``s whose instances play this role.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[ThingType]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_player_types(transaction, transitivity)
----

[#_RoleType_get_relation_instances__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_relation_instances

[source,python]
----
get_relation_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Relation]
----

Retrieves the ``Relation`` instances that this role is related to.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect relation, ``Transitivity.EXPLICIT`` for direct relation only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Relation]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_relation_instances(transaction, transitivity)
----

[#_RoleType_get_relation_type__transaction_TypeDBTransaction]
==== get_relation_type

[source,python]
----
get_relation_type(transaction: TypeDBTransaction) -> Promise[RelationType]
----

Retrieves the ``RelationType`` that this role is directly related to.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[RelationType]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_relation_type(transaction).resolve()
----

[#_RoleType_get_relation_types__transaction_TypeDBTransaction]
==== get_relation_types

[source,python]
----
get_relation_types(transaction: TypeDBTransaction) -> Iterator[RelationType]
----

Retrieves ``RelationType``s that this role is related to (directly or indirectly).

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[RelationType]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_relation_types(transaction)
----

[#_RoleType_get_subtypes__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[RoleType]
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_subtypes(transaction, transitivity)
----

[#_RoleType_get_supertype__transaction_TypeDBTransaction]
==== get_supertype

[source,python]
----
get_supertype(transaction: TypeDBTransaction) -> Promise[RoleType | None]
----

Retrieves the most immediate supertype of the ``RoleType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[RoleType | None]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_supertype(transaction).resolve()
----

[#_RoleType_get_supertypes__transaction_TypeDBTransaction]
==== get_supertypes

[source,python]
----
get_supertypes(transaction: TypeDBTransaction) -> Iterator[RoleType]
----

Retrieves all supertypes of the ``RoleType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
role_type.get_supertypes(transaction)
----

[#_RoleType_is_role_type__]
==== is_role_type

[source,python]
----
is_role_type() -> bool
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
role_type.is_role_type()
----

// end::methods[]

