[#_ThingType]
=== ThingType

*Supertypes:*

* `Type`

// tag::methods[]
[#_ThingType_get_instances__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_instances

[source,python]
----
get_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Thing]
----

Retrieves all direct and indirect (or direct only) ``Thing`` objects that are instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct instances only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Thing]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_instances(transaction)
thing_type.get_instances(transaction, Transitivity.EXPLICIT)
----

[#_ThingType_get_owns__transaction_TypeDBTransaction__value_type_ValueType__None__transitivity_Transitivity__annotations_set_Annotation___None]
==== get_owns

[source,python]
----
get_owns(transaction: TypeDBTransaction, value_type: ValueType | None = None, transitivity: Transitivity = Transitivity.TRANSITIVE, annotations: set[Annotation] | None = None) -> Iterator[AttributeType]
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `value_type` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType \| None` a| `None`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity` a| `Transitivity.TRANSITIVE`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `set[Annotation] \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[AttributeType]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_owns(transaction)
thing_type.get_owns(transaction, value_type,
                    transitivity=Transitivity.EXPLICIT,
                    annotations={Annotation.key()})
----

[#_ThingType_get_owns_overridden__transaction_TypeDBTransaction__attribute_type_AttributeType]
==== get_owns_overridden

[source,python]
----
get_owns_overridden(transaction: TypeDBTransaction, attribute_type: AttributeType) -> Promise[AttributeType | None]
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType` a| 
|===

[caption=""]
.Returns
`Promise[AttributeType | None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_owns_overridden(transaction, attribute_type).resolve()
----

[#_ThingType_get_plays__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_plays

[source,python]
----
get_plays(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[RoleType]
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_plays(transaction)
thing_type.get_plays(transaction, Transitivity.EXPLICIT)
----

[#_ThingType_get_plays_overridden__transaction_TypeDBTransaction__role_type_RoleType]
==== get_plays_overridden

[source,python]
----
get_plays_overridden(transaction: TypeDBTransaction, role_type: RoleType) -> Promise[RoleType | None]
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The ``RoleType`` that overrides an inherited role a| `RoleType` a| 
|===

[caption=""]
.Returns
`Promise[RoleType | None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_plays_overridden(transaction, role_type).resolve()
----

[#_ThingType_get_subtypes__transaction_TypeDBTransaction__transitivity_Transitivity]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[ThingType]
----

Retrieves all direct and indirect (or direct only) subtypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[ThingType]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_subtypes(transaction)
thing_type.get_subtypes(transaction, Transitivity.EXPLICIT)
----

[#_ThingType_get_supertype__transaction_TypeDBTransaction]
==== get_supertype

[source,python]
----
get_supertype(transaction: TypeDBTransaction) -> Promise[ThingType | None]
----

Retrieves the most immediate supertype of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[ThingType | None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_supertype(transaction).resolve()
----

[#_ThingType_get_supertypes__transaction_TypeDBTransaction]
==== get_supertypes

[source,python]
----
get_supertypes(transaction: TypeDBTransaction) -> Iterator[ThingType]
----

Retrieves all supertypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[ThingType]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_supertypes(transaction)
----

[#_ThingType_get_syntax__transaction_TypeDBTransaction]
==== get_syntax

[source,python]
----
get_syntax(transaction: TypeDBTransaction) -> Promise[str]
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[str]`

[caption=""]
.Code examples
[source,python]
----
thing_type.get_syntax(transaction).resolve()
----

[#_ThingType_is_thing_type__]
==== is_thing_type

[source,python]
----
is_thing_type() -> bool
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
thing_type.is_thing_type()
----

[#_ThingType_set_abstract__transaction_TypeDBTransaction]
==== set_abstract

[source,python]
----
set_abstract(transaction: TypeDBTransaction) -> Promise[None]
----

Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.set_abstract(transaction).resolve()
----

[#_ThingType_set_owns__transaction_TypeDBTransaction__attribute_type_AttributeType__overridden_type_AttributeType__None__annotations_set_Annotation___None]
==== set_owns

[source,python]
----
set_owns(transaction: TypeDBTransaction, attribute_type: AttributeType, overridden_type: AttributeType | None = None, annotations: set[Annotation] | None = None) -> Promise[None]
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType` a| 
a| `overridden_type` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType \| None` a| `None`
a| `annotations` a| Adds annotations to the ownership. a| `set[Annotation] \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.set_owns(transaction, attribute_type).resolve()
thing_type.set_owns(transaction, attribute_type,
                    overridden_type=overridden_type,
                    annotations={Annotation.key()}).resolve()
----

[#_ThingType_set_plays__transaction_TypeDBTransaction__role_type_RoleType__overriden_type_RoleType__None]
==== set_plays

[source,python]
----
set_plays(transaction: TypeDBTransaction, role_type: RoleType, overriden_type: RoleType | None = None) -> Promise[None]
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to be played by the instances of this type a| `RoleType` a| 
a| `overriden_type` a| The role type that this role overrides, if applicable a| `RoleType \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.set_plays(transaction, role_type).resolve()
thing_type.set_plays(transaction, role_type, overridden_type).resolve()
----

[#_ThingType_unset_abstract__transaction_TypeDBTransaction]
==== unset_abstract

[source,python]
----
unset_abstract(transaction: TypeDBTransaction) -> Promise[None]
----

Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.unset_abstract(transaction).resolve()
----

[#_ThingType_unset_owns__transaction_TypeDBTransaction__attribute_type_AttributeType]
==== unset_owns

[source,python]
----
unset_owns(transaction: TypeDBTransaction, attribute_type: AttributeType) -> Promise[None]
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.unset_owns(transaction, attribute_type).resolve()
----

[#_ThingType_unset_plays__transaction_TypeDBTransaction__role_type_RoleType]
==== unset_plays

[source,python]
----
unset_plays(transaction: TypeDBTransaction, role_type: RoleType) -> Promise[None]
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to not be played by the instances of this type. a| `RoleType` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing_type.unset_plays(transaction, role_type).resolve()
----

// end::methods[]

