[#_Type]
=== Type

*Supertypes:*

* `Concept`

// tag::methods[]
[#_Type_delete]
==== delete

[source,python]
----
delete(transaction: TypeDBTransaction) -> None
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
type_.delete(transaction)
----

[#_Type_get_label]
==== get_label

[source,python]
----
get_label() -> Label
----

Retrieves the unique label of the type.

[caption=""]
.Returns
`Label`

[caption=""]
.Code examples
[source,python]
----
type_.get_label()
----

[#_Type_get_subtypes]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Type]
----

Retrieves all direct and indirect (or direct only) subtypes of the type.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Type]`

[caption=""]
.Code examples
[source,python]
----
type_.get_subtypes(transaction)
type_.get_subtypes(transaction, Transitivity.EXPLICIT)
----

[#_Type_get_supertype]
==== get_supertype

[source,python]
----
get_supertype(transaction: TypeDBTransaction) -> Type | None
----

Retrieves the most immediate supertype of the type.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Type | None`

[caption=""]
.Code examples
[source,python]
----
type_.get_supertype(transaction)
----

[#_Type_get_supertypes]
==== get_supertypes

[source,python]
----
get_supertypes(transaction: TypeDBTransaction) -> Iterator[Type]
----

Retrieves all supertypes of the type.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[Type]`

[caption=""]
.Code examples
[source,python]
----
type_.get_supertypes(transaction)
----

[#_Type_is_abstract]
==== is_abstract

[source,python]
----
is_abstract() -> bool
----

Checks if the type is prevented from having data instances (i.e., ``abstract``).

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_abstract()
----

[#_Type_is_root]
==== is_root

[source,python]
----
is_root() -> bool
----

Checks if the type is a root type.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_root()
----

[#_Type_is_type]
==== is_type

[source,python]
----
is_type() -> bool
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_type()
----

[#_Type_set_label]
==== set_label

[source,python]
----
set_label(transaction: TypeDBTransaction, new_label: Label) -> None
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `new_label` a| The new ``Label`` to be given to the type. a| `Label` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
type_.set_label(transaction, new_label)
----

[#_Type_to_json]
==== to_json

[source,python]
----
to_json() -> Mapping[str, str]
----

Retrieves the type as JSON.

[caption=""]
.Returns
`Mapping[str, str]`

[caption=""]
.Code examples
[source,python]
----
type_.to_json()
----

// end::methods[]

