[#_LogicManager]
=== LogicManager

*Package*: `TypeDB`



Provides methods for manipulating ``Rule``s in the database.

// tag::methods[]
[#_OptionalRuleFuture_TypeDBLogicManagergetRule___const_stdstring__label___const]
==== getRule

[source,cpp]
----
OptionalRuleFuture TypeDB::LogicManager::getRule(const std::string& label) const
----



Retrieves the Rule that has the given label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`OptionalRuleFuture`

[caption=""]
.Code examples
[source,cpp]
----
transaction.logic.getRule(label).get();
----

[#_RuleIterable_TypeDBLogicManagergetRules_____const]
==== getRules

[source,cpp]
----
RuleIterable TypeDB::LogicManager::getRules() const
----



Retrieves all rules.


[caption=""]
.Returns
`RuleIterable`

[caption=""]
.Code examples
[source,cpp]
----
transaction.logic.getRules()
----

[#_RuleFuture_TypeDBLogicManagerputRule___const_stdstring__label__const_stdstring__when__const_stdstring__then___const]
==== putRule

[source,cpp]
----
RuleFuture TypeDB::LogicManager::putRule(const std::string& label, const std::string& when, const std::string& then) const
----



Creates a new Rule if none exists with the given label, or replaces the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or replace a| `const std::string&`
a| `when` a| The when body of the rule to create a| `const std::string&`
a| `then` a| The then body of the rule to create a| `const std::string&`
|===

[caption=""]
.Returns
`RuleFuture`

[caption=""]
.Code examples
[source,cpp]
----
transaction.logic.putRule(label, when, then).get();
----

// end::methods[]

