[#_Rule]
=== Rule

*Package*: `TypeDB`



Rules are a part of schema and define embedded logic.

The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

// tag::methods[]
[#_VoidFuture_TypeDBRuledeleteRule___Transaction__transaction_]
==== deleteRule

[source,cpp]
----
VoidFuture TypeDB::Rule::deleteRule(Transaction& transaction)
----



Deletes this rule.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `Transaction&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
rule.deleteRule(transaction).get();
----

[#_BoolFuture_TypeDBRuleisDeleted___Transaction__transaction_]
==== isDeleted

[source,cpp]
----
BoolFuture TypeDB::Rule::isDeleted(Transaction& transaction)
----



Check if this rule has been deleted.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `Transaction&`
|===

[caption=""]
.Returns
`BoolFuture`

[caption=""]
.Code examples
[source,cpp]
----
rule.isDeleted(transaction).get();
----

[#_stdstring_TypeDBRulelabel___]
==== label

[source,cpp]
----
std::string TypeDB::Rule::label()
----



Retrieves the unique label of the rule.

[caption=""]
.Returns
`std::string`

[#_VoidFuture_TypeDBRulesetLabel___Transaction__transaction__const_stdstring__label_]
==== setLabel

[source,cpp]
----
VoidFuture TypeDB::Rule::setLabel(Transaction& transaction, const std::string& label)
----



Renames the label of the rule. The new label must remain unique.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `Transaction&`
a| `label` a| The new label to be given to the rule a| `const std::string&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
rule.setLabel(transaction, newLabel).get();
----

[#_stdstring_TypeDBRulethen___]
==== then

[source,cpp]
----
std::string TypeDB::Rule::then()
----



The single statement that constitutes the ‘then’ of the rule.

[caption=""]
.Returns
`std::string`

[#_stdstring_TypeDBRuletoString___]
==== toString

[source,cpp]
----
std::string TypeDB::Rule::toString()
----



A string representation of this Rule.

[caption=""]
.Returns
`std::string`

[#_stdstring_TypeDBRulewhen___]
==== when

[source,cpp]
----
std::string TypeDB::Rule::when()
----



The statements that constitute the ‘when’ of the rule.

[caption=""]
.Returns
`std::string`

// end::methods[]

