[#_Attribute]
=== Attribute

*Package*: `com.typedb.driver.api.concept.instance`

*Superinterfaces:*

* `Concept`
* `Instance`



Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_asAttribute_]
==== asAttribute

[source,java]
----
@CheckReturnValue
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
attribute.asAttribute();
----

[#_Attribute_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Attribute_asBoolean_]
==== asBoolean

[source,java]
----
boolean asBoolean()
----

Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.asBoolean();
----

[#_Attribute_asDate_]
==== asDate

[source,java]
----
java.time.LocalDate asDate()
----

Returns a ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDate`

[caption=""]
.Code examples
[source,java]
----
attribute.asDate();
----

[#_Attribute_asDatetime_]
==== asDatetime

[source,java]
----
java.time.LocalDateTime asDatetime()
----

Returns a ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDateTime`

[caption=""]
.Code examples
[source,java]
----
attribute.asDatetime();
----

[#_Attribute_asDatetimeTZ_]
==== asDatetimeTZ

[source,java]
----
java.time.ZonedDateTime asDatetimeTZ()
----

Returns a ``datetime-tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.ZonedDateTime`

[caption=""]
.Code examples
[source,java]
----
attribute.asDatetimeTZ();
----

[#_Attribute_asDecimal_]
==== asDecimal

[source,java]
----
java.math.BigDecimal asDecimal()
----

Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.math.BigDecimal`

[caption=""]
.Code examples
[source,java]
----
attribute.asDecimal();
----

[#_Attribute_asDouble_]
==== asDouble

[source,java]
----
double asDouble()
----

Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,java]
----
attribute.asDouble();
----

[#_Attribute_asDuration_]
==== asDuration

[source,java]
----
Duration asDuration()
----

Returns a ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,java]
----
attribute.asDuration();
----

[#_Attribute_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Attribute_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Attribute_asLong_]
==== asLong

[source,java]
----
long asLong()
----

Returns a ``long`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,java]
----
attribute.asLong();
----

[#_Attribute_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Attribute_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Attribute_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Attribute_asString_]
==== asString

[source,java]
----
java.lang.String asString()
----

Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
attribute.asString();
----

[#_Attribute_asStruct_]
==== asStruct

[source,java]
----
java.util.Map<java.lang.String,​java.util.Optional<Value>> asStruct()
----

Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.util.Map<java.lang.String,​java.util.Optional<Value>>`

[caption=""]
.Code examples
[source,java]
----
attribute.asStruct();
----

[#_Attribute_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Attribute_asUntyped_]
==== asUntyped

[source,java]
----
java.lang.Object asUntyped()
----

Returns an untyped ``Object`` value of the value concept that this attribute holds. This is useful for value equality or printing without having to switch on the actual contained value. 


[caption=""]
.Returns
`java.lang.Object`

[caption=""]
.Code examples
[source,java]
----
attribute.asUntyped();
----

[#_Attribute_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Attribute_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Attribute_getType_]
==== getType

[source,java]
----
@CheckReturnValue
AttributeType getType()
----

Retrieves the type which this ``Attribute`` belongs to. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
attribute.getType();
----

[#_Attribute_getValue_]
==== getValue

[source,java]
----
Value getValue()
----

Retrieves the value which the ``Attribute`` instance holds. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
attribute.getValue();
----

[#_Attribute_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isAttribute();
----

[#_Attribute_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Attribute_isBoolean_]
==== isBoolean

[source,java]
----
boolean isBoolean()
----

Returns ``True`` if this attribute holds a value of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isBoolean()
----

[#_Attribute_isDate_]
==== isDate

[source,java]
----
boolean isDate()
----

Returns ``True`` if this attribute holds a value of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDate();
----

[#_Attribute_isDatetime_]
==== isDatetime

[source,java]
----
boolean isDatetime()
----

Returns ``True`` if this attribute holds a value of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDatetime();
----

[#_Attribute_isDatetimeTZ_]
==== isDatetimeTZ

[source,java]
----
boolean isDatetimeTZ()
----

Returns ``True`` if this attribute holds a value of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDatetimeTZ();
----

[#_Attribute_isDecimal_]
==== isDecimal

[source,java]
----
boolean isDecimal()
----

Returns ``True`` if this attribute holds a value of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDecimal();
----

[#_Attribute_isDouble_]
==== isDouble

[source,java]
----
boolean isDouble()
----

Returns ``True`` if this attribute holds a value of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDouble();
----

[#_Attribute_isDuration_]
==== isDuration

[source,java]
----
boolean isDuration()
----

Returns ``True`` if this attribute holds a value of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isDuration();
----

[#_Attribute_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Attribute_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Attribute_isLong_]
==== isLong

[source,java]
----
boolean isLong()
----

Returns ``True`` if this attribute holds a value of type ``long``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isLong();
----

[#_Attribute_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Attribute_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Attribute_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Attribute_isString_]
==== isString

[source,java]
----
boolean isString()
----

Returns ``True`` if this attribute holds a value of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isString();
----

[#_Attribute_isStruct_]
==== isStruct

[source,java]
----
boolean isStruct()
----

Returns ``True`` if this attribute holds a value of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.isStruct();
----

[#_Attribute_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Attribute_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]

