[#_Attribute]
=== Attribute

`Class(name=Attribute, anchor=Attribute, enumConstants=[], description=[, Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type., Attributes can be uniquely addressed by their type and value.], examples=[], fields=[], methods=[Method(name=isAttribute, signature=@CheckReturnValue
default boolean isAttribute(), anchor=Attribute_isAttribute_, args=[], description=[Checks if the concept is an ``Attribute``. 
], examples=[concept.isAttribute();], mode=null, returnDescription=null, returnType=boolean), Method(name=asAttribute, signature=@CheckReturnValue
default Attribute asAttribute(), anchor=Attribute_asAttribute_, args=[], description=[Casts the concept to ``Attribute``. 
], examples=[concept.asAttribute();], mode=null, returnDescription=null, returnType=Attribute), Method(name=getType, signature=@CheckReturnValue
AttributeType getType(), anchor=Attribute_getType_, args=[], description=[Retrieves the type which this ``Attribute`` belongs to. 
], examples=[attribute.getType();], mode=null, returnDescription=null, returnType=AttributeType), Method(name=getValue, signature=@CheckReturnValue
Value getValue(), anchor=Attribute_getValue_, args=[], description=[Retrieves the value which the ``Attribute`` instance holds. 
], examples=[attribute.getValue();], mode=null, returnDescription=null, returnType=Value), Method(name=getValueType, signature=@CheckReturnValue
java.lang.String getValueType(), anchor=Attribute_getValueType_, args=[], description=[Retrieves the description of the value type of the value which the ``Attribute`` instance holds. 
], examples=[attribute.getValueType();], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=getBoolean, signature=boolean getBoolean(), anchor=Attribute_getBoolean_, args=[], description=[Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getBoolean();], mode=null, returnDescription=null, returnType=boolean), Method(name=getInteger, signature=long getInteger(), anchor=Attribute_getInteger_, args=[], description=[Returns a ``integer`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getInteger();], mode=null, returnDescription=null, returnType=long), Method(name=getDouble, signature=double getDouble(), anchor=Attribute_getDouble_, args=[], description=[Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDouble();], mode=null, returnDescription=null, returnType=double), Method(name=getDecimal, signature=java.math.BigDecimal getDecimal(), anchor=Attribute_getDecimal_, args=[], description=[Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDecimal();], mode=null, returnDescription=null, returnType=java.math.BigDecimal), Method(name=getString, signature=java.lang.String getString(), anchor=Attribute_getString_, args=[], description=[Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getString();], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=getDate, signature=java.time.LocalDate getDate(), anchor=Attribute_getDate_, args=[], description=[Returns a ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDate();], mode=null, returnDescription=null, returnType=java.time.LocalDate), Method(name=getDatetime, signature=java.time.LocalDateTime getDatetime(), anchor=Attribute_getDatetime_, args=[], description=[Returns a ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDatetime();], mode=null, returnDescription=null, returnType=java.time.LocalDateTime), Method(name=getDatetimeTZ, signature=java.time.ZonedDateTime getDatetimeTZ(), anchor=Attribute_getDatetimeTZ_, args=[], description=[Returns a ``datetime-tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDatetimeTZ();], mode=null, returnDescription=null, returnType=java.time.ZonedDateTime), Method(name=getDuration, signature=Duration getDuration(), anchor=Attribute_getDuration_, args=[], description=[Returns a ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 
], examples=[attribute.getDuration();], mode=null, returnDescription=null, returnType=Duration), Method(name=getStruct, signature=java.util.Map<java.lang.String,​java.util.Optional<Value>> getStruct(), anchor=Attribute_getStruct_, args=[], description=[Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception. 
], examples=[attribute.getStruct();], mode=null, returnDescription=null, returnType=java.util.Map<java.lang.String,​java.util.Optional<Value>>), Method(name=asAttributeType, signature=default AttributeType asAttributeType(), anchor=Attribute_asAttributeType_, args=[], description=[Casts the concept to ``AttributeType``. 
], examples=[concept.asAttributeType();], mode=null, returnDescription=null, returnType=AttributeType), Method(name=asEntity, signature=default Entity asEntity(), anchor=Attribute_asEntity_, args=[], description=[Casts the concept to ``Entity``. 
], examples=[concept.asEntity();], mode=null, returnDescription=null, returnType=Entity), Method(name=asEntityType, signature=default EntityType asEntityType(), anchor=Attribute_asEntityType_, args=[], description=[Casts the concept to ``EntityType``. 
], examples=[concept.asEntityType();], mode=null, returnDescription=null, returnType=EntityType), Method(name=asRelation, signature=default Relation asRelation(), anchor=Attribute_asRelation_, args=[], description=[Casts the concept to ``Relation``. 
], examples=[concept.asRelation();], mode=null, returnDescription=null, returnType=Relation), Method(name=asRelationType, signature=default RelationType asRelationType(), anchor=Attribute_asRelationType_, args=[], description=[Casts the concept to ``RelationType``. 
], examples=[concept.asRelationType();], mode=null, returnDescription=null, returnType=RelationType), Method(name=asRoleType, signature=default RoleType asRoleType(), anchor=Attribute_asRoleType_, args=[], description=[Casts the concept to ``RoleType``. 
], examples=[concept.asRoleType();], mode=null, returnDescription=null, returnType=RoleType), Method(name=asType, signature=default Type asType(), anchor=Attribute_asType_, args=[], description=[Casts the concept to ``Type``. 
], examples=[concept.asType();], mode=null, returnDescription=null, returnType=Type), Method(name=asValue, signature=default Value asValue(), anchor=Attribute_asValue_, args=[], description=[Casts the concept to ``Value``. 
], examples=[concept.asValue();], mode=null, returnDescription=null, returnType=Value), Method(name=getLabel, signature=@CheckReturnValue
java.lang.String getLabel(), anchor=Attribute_getLabel_, args=[], description=[Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 
], examples=[concept.getLabel();], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=isAttributeType, signature=@CheckReturnValue
default boolean isAttributeType(), anchor=Attribute_isAttributeType_, args=[], description=[Checks if the concept is an ``AttributeType``. 
], examples=[concept.isAttributeType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isBoolean, signature=@CheckReturnValue
boolean isBoolean(), anchor=Attribute_isBoolean_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 
], examples=[concept.isBoolean()], mode=null, returnDescription=null, returnType=boolean), Method(name=isDate, signature=@CheckReturnValue
boolean isDate(), anchor=Attribute_isDate_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 
], examples=[concept.isDate();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDatetime, signature=@CheckReturnValue
boolean isDatetime(), anchor=Attribute_isDatetime_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 
], examples=[concept.isDatetime();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDatetimeTZ, signature=@CheckReturnValue
boolean isDatetimeTZ(), anchor=Attribute_isDatetimeTZ_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 
], examples=[concept.isDatetimeTZ();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDecimal, signature=@CheckReturnValue
boolean isDecimal(), anchor=Attribute_isDecimal_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 
], examples=[concept.isDecimal();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDouble, signature=@CheckReturnValue
boolean isDouble(), anchor=Attribute_isDouble_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 
], examples=[concept.isDouble();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDuration, signature=@CheckReturnValue
boolean isDuration(), anchor=Attribute_isDuration_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 
], examples=[concept.isDuration();], mode=null, returnDescription=null, returnType=boolean), Method(name=isEntity, signature=@CheckReturnValue
default boolean isEntity(), anchor=Attribute_isEntity_, args=[], description=[Checks if the concept is an ``Entity``. 
], examples=[concept.isEntity();], mode=null, returnDescription=null, returnType=boolean), Method(name=isEntityType, signature=@CheckReturnValue
default boolean isEntityType(), anchor=Attribute_isEntityType_, args=[], description=[Checks if the concept is an ``EntityType``. 
], examples=[concept.isEntityType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isInteger, signature=@CheckReturnValue
boolean isInteger(), anchor=Attribute_isInteger_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 
], examples=[concept.isInteger();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelation, signature=@CheckReturnValue
default boolean isRelation(), anchor=Attribute_isRelation_, args=[], description=[Checks if the concept is a ``Relation``. 
], examples=[concept.isRelation();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelationType, signature=@CheckReturnValue
default boolean isRelationType(), anchor=Attribute_isRelationType_, args=[], description=[Checks if the concept is a ``RelationType``. 
], examples=[concept.isRelationType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRoleType, signature=@CheckReturnValue
default boolean isRoleType(), anchor=Attribute_isRoleType_, args=[], description=[Checks if the concept is a ``RoleType``. 
], examples=[concept.isRoleType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isString, signature=@CheckReturnValue
boolean isString(), anchor=Attribute_isString_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 
], examples=[concept.isString();], mode=null, returnDescription=null, returnType=boolean), Method(name=isStruct, signature=@CheckReturnValue
boolean isStruct(), anchor=Attribute_isStruct_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 
], examples=[concept.isStruct();], mode=null, returnDescription=null, returnType=boolean), Method(name=isType, signature=@CheckReturnValue
default boolean isType(), anchor=Attribute_isType_, args=[], description=[Checks if the concept is a ``Type``. 
], examples=[concept.isType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=@CheckReturnValue
default boolean isValue(), anchor=Attribute_isValue_, args=[], description=[Checks if the concept is a ``Value``. 
], examples=[concept.isValue();], mode=null, returnDescription=null, returnType=boolean), Method(name=tryGetBoolean, signature=java.util.Optional<java.lang.Boolean> tryGetBoolean(), anchor=Attribute_tryGetBoolean_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetBoolean();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Boolean>), Method(name=tryGetDate, signature=java.util.Optional<java.time.LocalDate> tryGetDate(), anchor=Attribute_tryGetDate_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDate();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.LocalDate>), Method(name=tryGetDatetime, signature=java.util.Optional<java.time.LocalDateTime> tryGetDatetime(), anchor=Attribute_tryGetDatetime_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDatetime();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.LocalDateTime>), Method(name=tryGetDatetimeTZ, signature=java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ(), anchor=Attribute_tryGetDatetimeTZ_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDatetimeTZ();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.ZonedDateTime>), Method(name=tryGetDecimal, signature=java.util.Optional<java.math.BigDecimal> tryGetDecimal(), anchor=Attribute_tryGetDecimal_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDecimal();], mode=null, returnDescription=null, returnType=java.util.Optional<java.math.BigDecimal>), Method(name=tryGetDouble, signature=java.util.Optional<java.lang.Double> tryGetDouble(), anchor=Attribute_tryGetDouble_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDouble();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Double>), Method(name=tryGetDuration, signature=java.util.Optional<Duration> tryGetDuration(), anchor=Attribute_tryGetDuration_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDuration();], mode=null, returnDescription=null, returnType=java.util.Optional<Duration>), Method(name=tryGetIID, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID(), anchor=Attribute_tryGetIID_, args=[], description=[Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 
], examples=[concept.tryGetIID();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetInteger, signature=java.util.Optional<java.lang.Long> tryGetInteger(), anchor=Attribute_tryGetInteger_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetInteger();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Long>), Method(name=tryGetLabel, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel(), anchor=Attribute_tryGetLabel_, args=[], description=[Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 
], examples=[concept.tryGetLabel();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetString, signature=java.util.Optional<java.lang.String> tryGetString(), anchor=Attribute_tryGetString_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetString();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetStruct, signature=java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct(), anchor=Attribute_tryGetStruct_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetStruct();], mode=null, returnDescription=null, returnType=java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>), Method(name=tryGetValue, signature=@CheckReturnValue
java.util.Optional<Value> tryGetValue(), anchor=Attribute_tryGetValue_, args=[], description=[Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 
], examples=[concept.tryGetValue();], mode=null, returnDescription=null, returnType=java.util.Optional<Value>), Method(name=tryGetValueType, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType(), anchor=Attribute_tryGetValueType_, args=[], description=[Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 
], examples=[concept.tryGetValueType();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>)], packagePath=com.typedb.driver.api.concept.instance, superClasses=[Concept, Instance], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.concept.instance`

*Superinterfaces:*

* `Concept`
* `Instance`



Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_asAttribute_]
==== asAttribute

[source,java]
----
@CheckReturnValue
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Attribute_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Attribute_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Attribute_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Attribute_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Attribute_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Attribute_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Attribute_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Attribute_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Attribute_getBoolean_]
==== getBoolean

[source,java]
----
boolean getBoolean()
----

Returns a ``boolean`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
attribute.getBoolean();
----

[#_Attribute_getDate_]
==== getDate

[source,java]
----
java.time.LocalDate getDate()
----

Returns a ``date`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDate`

[caption=""]
.Code examples
[source,java]
----
attribute.getDate();
----

[#_Attribute_getDatetime_]
==== getDatetime

[source,java]
----
java.time.LocalDateTime getDatetime()
----

Returns a ``datetime`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDateTime`

[caption=""]
.Code examples
[source,java]
----
attribute.getDatetime();
----

[#_Attribute_getDatetimeTZ_]
==== getDatetimeTZ

[source,java]
----
java.time.ZonedDateTime getDatetimeTZ()
----

Returns a ``datetime-tz`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.ZonedDateTime`

[caption=""]
.Code examples
[source,java]
----
attribute.getDatetimeTZ();
----

[#_Attribute_getDecimal_]
==== getDecimal

[source,java]
----
java.math.BigDecimal getDecimal()
----

Returns a ``decimal`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.math.BigDecimal`

[caption=""]
.Code examples
[source,java]
----
attribute.getDecimal();
----

[#_Attribute_getDouble_]
==== getDouble

[source,java]
----
double getDouble()
----

Returns a ``double`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,java]
----
attribute.getDouble();
----

[#_Attribute_getDuration_]
==== getDuration

[source,java]
----
Duration getDuration()
----

Returns a ``duration`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,java]
----
attribute.getDuration();
----

[#_Attribute_getInteger_]
==== getInteger

[source,java]
----
long getInteger()
----

Returns a ``integer`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,java]
----
attribute.getInteger();
----

[#_Attribute_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Attribute_getString_]
==== getString

[source,java]
----
java.lang.String getString()
----

Returns a ``string`` value of the value concept that this attribute holds. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
attribute.getString();
----

[#_Attribute_getStruct_]
==== getStruct

[source,java]
----
java.util.Map<java.lang.String,​java.util.Optional<Value>> getStruct()
----

Returns a ``struct`` value of the value concept that this attribute holds represented as a map from field names to values. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.util.Map<java.lang.String,​java.util.Optional<Value>>`

[caption=""]
.Code examples
[source,java]
----
attribute.getStruct();
----

[#_Attribute_getType_]
==== getType

[source,java]
----
@CheckReturnValue
AttributeType getType()
----

Retrieves the type which this ``Attribute`` belongs to. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
attribute.getType();
----

[#_Attribute_getValue_]
==== getValue

[source,java]
----
@CheckReturnValue
Value getValue()
----

Retrieves the value which the ``Attribute`` instance holds. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
attribute.getValue();
----

[#_Attribute_getValueType_]
==== getValueType

[source,java]
----
@CheckReturnValue
java.lang.String getValueType()
----

Retrieves the description of the value type of the value which the ``Attribute`` instance holds. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
attribute.getValueType();
----

[#_Attribute_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Attribute_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Attribute_isBoolean_]
==== isBoolean

[source,java]
----
@CheckReturnValue
boolean isBoolean()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isBoolean()
----

[#_Attribute_isDate_]
==== isDate

[source,java]
----
@CheckReturnValue
boolean isDate()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDate();
----

[#_Attribute_isDatetime_]
==== isDatetime

[source,java]
----
@CheckReturnValue
boolean isDatetime()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetime();
----

[#_Attribute_isDatetimeTZ_]
==== isDatetimeTZ

[source,java]
----
@CheckReturnValue
boolean isDatetimeTZ()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetimeTZ();
----

[#_Attribute_isDecimal_]
==== isDecimal

[source,java]
----
@CheckReturnValue
boolean isDecimal()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDecimal();
----

[#_Attribute_isDouble_]
==== isDouble

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDouble();
----

[#_Attribute_isDuration_]
==== isDuration

[source,java]
----
@CheckReturnValue
boolean isDuration()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDuration();
----

[#_Attribute_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Attribute_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Attribute_isInteger_]
==== isInteger

[source,java]
----
@CheckReturnValue
boolean isInteger()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInteger();
----

[#_Attribute_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Attribute_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Attribute_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Attribute_isString_]
==== isString

[source,java]
----
@CheckReturnValue
boolean isString()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isString();
----

[#_Attribute_isStruct_]
==== isStruct

[source,java]
----
@CheckReturnValue
boolean isStruct()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isStruct();
----

[#_Attribute_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Attribute_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Attribute_tryGetBoolean_]
==== tryGetBoolean

[source,java]
----
java.util.Optional<java.lang.Boolean> tryGetBoolean()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetBoolean();
----

[#_Attribute_tryGetDate_]
==== tryGetDate

[source,java]
----
java.util.Optional<java.time.LocalDate> tryGetDate()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDate>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDate();
----

[#_Attribute_tryGetDatetime_]
==== tryGetDatetime

[source,java]
----
java.util.Optional<java.time.LocalDateTime> tryGetDatetime()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetime();
----

[#_Attribute_tryGetDatetimeTZ_]
==== tryGetDatetimeTZ

[source,java]
----
java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ()
----

Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.ZonedDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetimeTZ();
----

[#_Attribute_tryGetDecimal_]
==== tryGetDecimal

[source,java]
----
java.util.Optional<java.math.BigDecimal> tryGetDecimal()
----

Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.math.BigDecimal>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDecimal();
----

[#_Attribute_tryGetDouble_]
==== tryGetDouble

[source,java]
----
java.util.Optional<java.lang.Double> tryGetDouble()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Double>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDouble();
----

[#_Attribute_tryGetDuration_]
==== tryGetDuration

[source,java]
----
java.util.Optional<Duration> tryGetDuration()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<Duration>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDuration();
----

[#_Attribute_tryGetIID_]
==== tryGetIID

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID()
----

Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetIID();
----

[#_Attribute_tryGetInteger_]
==== tryGetInteger

[source,java]
----
java.util.Optional<java.lang.Long> tryGetInteger()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Long>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetInteger();
----

[#_Attribute_tryGetLabel_]
==== tryGetLabel

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLabel();
----

[#_Attribute_tryGetString_]
==== tryGetString

[source,java]
----
java.util.Optional<java.lang.String> tryGetString()
----

Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetString();
----

[#_Attribute_tryGetStruct_]
==== tryGetStruct

[source,java]
----
java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetStruct();
----

[#_Attribute_tryGetValue_]
==== tryGetValue

[source,java]
----
@CheckReturnValue
java.util.Optional<Value> tryGetValue()
----

Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 


[caption=""]
.Returns
`java.util.Optional<Value>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValue();
----

[#_Attribute_tryGetValueType_]
==== tryGetValueType

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType()
----

Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValueType();
----

// end::methods[]

