[#_Entity]
[.doc-api-reference-driver]
=== Entity

`class`

*Package*: `com.typedb.driver.api.concept.instance`

*Superinterfaces:*

* `Concept`
* `Instance`

Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances.

// tag::methods[]
[#_Entity_asAttribute_]
==== method <code>asAttribute</code>

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Entity_asAttributeType_]
==== method <code>asAttributeType</code>

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Entity_asEntity_]
==== method <code>asEntity</code>

[source,java]
----
@CheckReturnValue
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
entity.asEntity();
----

[#_Entity_asEntityType_]
==== method <code>asEntityType</code>

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Entity_asRelation_]
==== method <code>asRelation</code>

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Entity_asRelationType_]
==== method <code>asRelationType</code>

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Entity_asRoleType_]
==== method <code>asRoleType</code>

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Entity_asType_]
==== method <code>asType</code>

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Entity_asValue_]
==== method <code>asValue</code>

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Entity_getIID_]
==== method <code>getIID</code>

[source,java]
----
@CheckReturnValue
java.lang.String getIID()
----

Retrieves the unique id of the ``Entity``. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
entity.getIID();
----

[#_Entity_getLabel_]
==== method <code>getLabel</code>

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Entity_getType_]
==== method <code>getType</code>

[source,java]
----
@CheckReturnValue
EntityType getType()
----

Retrieves the type which this ``Entity`` belongs to. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
entity.getType();
----

[#_Entity_isAttribute_]
==== method <code>isAttribute</code>

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Entity_isAttributeType_]
==== method <code>isAttributeType</code>

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Entity_isBoolean_]
==== method <code>isBoolean</code>

[source,java]
----
@CheckReturnValue
boolean isBoolean()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isBoolean()
----

[#_Entity_isDate_]
==== method <code>isDate</code>

[source,java]
----
@CheckReturnValue
boolean isDate()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDate();
----

[#_Entity_isDatetime_]
==== method <code>isDatetime</code>

[source,java]
----
@CheckReturnValue
boolean isDatetime()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetime();
----

[#_Entity_isDatetimeTZ_]
==== method <code>isDatetimeTZ</code>

[source,java]
----
@CheckReturnValue
boolean isDatetimeTZ()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetimeTZ();
----

[#_Entity_isDecimal_]
==== method <code>isDecimal</code>

[source,java]
----
@CheckReturnValue
boolean isDecimal()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDecimal();
----

[#_Entity_isDouble_]
==== method <code>isDouble</code>

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDouble();
----

[#_Entity_isDuration_]
==== method <code>isDuration</code>

[source,java]
----
@CheckReturnValue
boolean isDuration()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDuration();
----

[#_Entity_isEntity_]
==== method <code>isEntity</code>

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
entity.isEntity();
----

[#_Entity_isEntityType_]
==== method <code>isEntityType</code>

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Entity_isInteger_]
==== method <code>isInteger</code>

[source,java]
----
@CheckReturnValue
boolean isInteger()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInteger();
----

[#_Entity_isRelation_]
==== method <code>isRelation</code>

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Entity_isRelationType_]
==== method <code>isRelationType</code>

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Entity_isRoleType_]
==== method <code>isRoleType</code>

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Entity_isString_]
==== method <code>isString</code>

[source,java]
----
@CheckReturnValue
boolean isString()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isString();
----

[#_Entity_isStruct_]
==== method <code>isStruct</code>

[source,java]
----
@CheckReturnValue
boolean isStruct()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isStruct();
----

[#_Entity_isType_]
==== method <code>isType</code>

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Entity_isValue_]
==== method <code>isValue</code>

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Entity_tryGetBoolean_]
==== method <code>tryGetBoolean</code>

[source,java]
----
java.util.Optional<java.lang.Boolean> tryGetBoolean()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetBoolean();
----

[#_Entity_tryGetDate_]
==== method <code>tryGetDate</code>

[source,java]
----
java.util.Optional<java.time.LocalDate> tryGetDate()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDate>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDate();
----

[#_Entity_tryGetDatetime_]
==== method <code>tryGetDatetime</code>

[source,java]
----
java.util.Optional<java.time.LocalDateTime> tryGetDatetime()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetime();
----

[#_Entity_tryGetDatetimeTZ_]
==== method <code>tryGetDatetimeTZ</code>

[source,java]
----
java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ()
----

Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.ZonedDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetimeTZ();
----

[#_Entity_tryGetDecimal_]
==== method <code>tryGetDecimal</code>

[source,java]
----
java.util.Optional<java.math.BigDecimal> tryGetDecimal()
----

Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.math.BigDecimal>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDecimal();
----

[#_Entity_tryGetDouble_]
==== method <code>tryGetDouble</code>

[source,java]
----
java.util.Optional<java.lang.Double> tryGetDouble()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Double>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDouble();
----

[#_Entity_tryGetDuration_]
==== method <code>tryGetDuration</code>

[source,java]
----
java.util.Optional<Duration> tryGetDuration()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<Duration>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDuration();
----

[#_Entity_tryGetIID_]
==== method <code>tryGetIID</code>

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID()
----

Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetIID();
----

[#_Entity_tryGetInteger_]
==== method <code>tryGetInteger</code>

[source,java]
----
java.util.Optional<java.lang.Long> tryGetInteger()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Long>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetInteger();
----

[#_Entity_tryGetLabel_]
==== method <code>tryGetLabel</code>

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLabel();
----

[#_Entity_tryGetString_]
==== method <code>tryGetString</code>

[source,java]
----
java.util.Optional<java.lang.String> tryGetString()
----

Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetString();
----

[#_Entity_tryGetStruct_]
==== method <code>tryGetStruct</code>

[source,java]
----
java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetStruct();
----

[#_Entity_tryGetValue_]
==== method <code>tryGetValue</code>

[source,java]
----
@CheckReturnValue
java.util.Optional<Value> tryGetValue()
----

Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 


[caption=""]
.Returns
`java.util.Optional<Value>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValue();
----

[#_Entity_tryGetValueType_]
==== method <code>tryGetValueType</code>

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType()
----

Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValueType();
----

// end::methods[]

