[#_Instance]
=== Instance

*Package*: `com.typedb.driver.api.concept.instance`

*Superinterfaces:*

* `Concept`

// tag::methods[]
[#_Instance_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Instance_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Instance_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Instance_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Instance_asInstance_]
==== asInstance

[source,java]
----
@CheckReturnValue
default Instance asInstance()
----

Casts the concept to ``Instance``. 


[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,java]
----
instance.asInstance();
----

[#_Instance_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Instance_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Instance_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Instance_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Instance_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Instance_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Instance_getType_]
==== getType

[source,java]
----
@CheckReturnValue
Type getType()
----

Retrieves the type which this ``Instance`` belongs to. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
instance.getType();
----

[#_Instance_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Instance_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Instance_isBoolean_]
==== isBoolean

[source,java]
----
@CheckReturnValue
boolean isBoolean()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isBoolean()
----

[#_Instance_isDate_]
==== isDate

[source,java]
----
@CheckReturnValue
boolean isDate()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDate();
----

[#_Instance_isDatetime_]
==== isDatetime

[source,java]
----
@CheckReturnValue
boolean isDatetime()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetime();
----

[#_Instance_isDatetimeTZ_]
==== isDatetimeTZ

[source,java]
----
@CheckReturnValue
boolean isDatetimeTZ()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetimeTZ();
----

[#_Instance_isDecimal_]
==== isDecimal

[source,java]
----
@CheckReturnValue
boolean isDecimal()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDecimal();
----

[#_Instance_isDouble_]
==== isDouble

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDouble();
----

[#_Instance_isDuration_]
==== isDuration

[source,java]
----
@CheckReturnValue
boolean isDuration()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDuration();
----

[#_Instance_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Instance_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Instance_isInstance_]
==== isInstance

[source,java]
----
@CheckReturnValue
default boolean isInstance()
----

Checks if the concept is a ``Instance``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
instance.isInstance();
----

[#_Instance_isLong_]
==== isLong

[source,java]
----
@CheckReturnValue
boolean isLong()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``long`` or if this ``Concept`` is an ``AttributeType`` of type ``long``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isLong();
----

[#_Instance_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Instance_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Instance_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Instance_isString_]
==== isString

[source,java]
----
@CheckReturnValue
boolean isString()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isString();
----

[#_Instance_isStruct_]
==== isStruct

[source,java]
----
@CheckReturnValue
boolean isStruct()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isStruct();
----

[#_Instance_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Instance_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Instance_tryGetBoolean_]
==== tryGetBoolean

[source,java]
----
java.util.Optional<java.lang.Boolean> tryGetBoolean()
----

Returns a ``boolean`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetBoolean();
----

[#_Instance_tryGetDate_]
==== tryGetDate

[source,java]
----
java.util.Optional<java.time.LocalDate> tryGetDate()
----

Returns a ``date`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDate>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDate();
----

[#_Instance_tryGetDatetime_]
==== tryGetDatetime

[source,java]
----
java.util.Optional<java.time.LocalDateTime> tryGetDatetime()
----

Returns a ``datetime`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetime();
----

[#_Instance_tryGetDatetimeTZ_]
==== tryGetDatetimeTZ

[source,java]
----
java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ()
----

Returns a ``datetime-tz`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.ZonedDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetimeTZ();
----

[#_Instance_tryGetDecimal_]
==== tryGetDecimal

[source,java]
----
java.util.Optional<java.math.BigDecimal> tryGetDecimal()
----

Returns a ``decimal`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.math.BigDecimal>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDecimal();
----

[#_Instance_tryGetDouble_]
==== tryGetDouble

[source,java]
----
java.util.Optional<java.lang.Double> tryGetDouble()
----

Returns a ``double`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Double>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDouble();
----

[#_Instance_tryGetDuration_]
==== tryGetDuration

[source,java]
----
java.util.Optional<Duration> tryGetDuration()
----

Returns a ``duration`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<Duration>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDuration();
----

[#_Instance_tryGetIID_]
==== tryGetIID

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID()
----

Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetIID();
----

[#_Instance_tryGetLabel_]
==== tryGetLabel

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLabel();
----

[#_Instance_tryGetLong_]
==== tryGetLong

[source,java]
----
java.util.Optional<java.lang.Long> tryGetLong()
----

Returns a ``long`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Long>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLong();
----

[#_Instance_tryGetString_]
==== tryGetString

[source,java]
----
java.util.Optional<java.lang.String> tryGetString()
----

Returns a ``string`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetString();
----

[#_Instance_tryGetStruct_]
==== tryGetStruct

[source,java]
----
java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct()
----

Returns a ``struct`` value of this ``Concept``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetStruct();
----

[#_Instance_tryGetValue_]
==== tryGetValue

[source,java]
----
@CheckReturnValue
java.util.Optional<Value> tryGetValue()
----

Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 


[caption=""]
.Returns
`java.util.Optional<Value>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValue();
----

[#_Instance_tryGetValueType_]
==== tryGetValueType

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType()
----

Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValueType();
----

// end::methods[]

