[#_Thing]
=== Thing

*Package*: `com.vaticle.typedb.driver.api.concept.thing`

*Superinterfaces:*

* `Concept`

// tag::methods[]
[#_Thing_asAttribute__]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Thing_asAttributeType__]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Thing_asEntity__]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Thing_asEntityType__]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Thing_asRelation__]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Thing_asRelationType__]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Thing_asRoleType__]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Thing_asThing__]
==== asThing

[source,java]
----
@CheckReturnValue
default Thing asThing()
----

Casts the concept to ``Thing``. 


[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,java]
----
thing.asThing();
----

[#_Thing_asThingType__]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
concept.asThingType();
----

[#_Thing_asType__]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Thing_asValue__]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Thing_delete__TypeDBTransaction]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(TypeDBTransaction transaction)
----

Deletes this ``Thing``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
thing.delete(transaction).resolve();
----

[#_Thing_getHas__TypeDBTransaction__AttributeType___]
==== getHas

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    AttributeType... attributeTypes)
----

Retrieves the ``Attribute``s that this ``Thing`` owns, optionally filtered by ``AttributeType``s. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Attribute>`

[caption=""]
.Code examples
[source,java]
----
thing.getHas(transaction);
 thing.getHas(transaction, attributeType);
----

[#_Thing_getHas__TypeDBTransaction__java_util_Set_ThingType_Annotation_]
==== getHas

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    java.util.Set<ThingType.Annotation> annotations)
----

Retrieves the ``Attribute``s that this ``Thing`` owns, filtered by ``Annotation``s. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `java.util.Set<ThingType.Annotation>`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Attribute>`

[caption=""]
.Code examples
[source,java]
----
thing.getHas(transaction);
 thing.getHas(transaction, set(Annotation.key()));
----

[#_Thing_getIID__]
==== getIID

[source,java]
----
@CheckReturnValue
java.lang.String getIID()
----

Retrieves the unique id of the ``Thing``. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
thing.getIID();
----

[#_Thing_getPlaying__TypeDBTransaction]
==== getPlaying

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getPlaying​(TypeDBTransaction transaction)
----

Retrieves the roles that this ``Thing`` is currently playing. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
thing.getPlaying(transaction);
----

[#_Thing_getRelations__TypeDBTransaction__RoleType___]
==== getRelations

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getRelations​(TypeDBTransaction transaction,
                                                         RoleType... roleTypes)
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleTypes` a| The array of roles to filter the relations by. a| `RoleType[]`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[caption=""]
.Code examples
[source,java]
----
thing.getRelations(transaction, roleTypes);
----

[#_Thing_getType__]
==== getType

[source,java]
----
@CheckReturnValue
ThingType getType()
----

Retrieves the type which this ``Thing`` belongs to. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
thing.getType();
----

[#_Thing_isAttribute__]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Thing_isAttributeType__]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Thing_isDeleted__TypeDBTransaction]
==== isDeleted

[source,java]
----
@CheckReturnValue
Promise<java.lang.Boolean> isDeleted​(TypeDBTransaction transaction)
----

Checks if this ``Thing`` is deleted. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
thing.isDeleted(transaction).resolve();
----

[#_Thing_isEntity__]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Thing_isEntityType__]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Thing_isInferred__]
==== isInferred

[source,java]
----
@CheckReturnValue
boolean isInferred()
----

Checks if this ``Thing`` is inferred by a [Reasoning Rule]. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
thing.isInferred();
----

[#_Thing_isRelation__]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Thing_isRelationType__]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Thing_isRoleType__]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Thing_isThing__]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
thing.isThing();
----

[#_Thing_isThingType__]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThingType();
----

[#_Thing_isType__]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Thing_isValue__]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Thing_setHas__TypeDBTransaction__Attribute]
==== setHas

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> setHas​(TypeDBTransaction transaction,
                               Attribute attribute)
----

Assigns an ``Attribute`` to be owned by this ``Thing``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
thing.setHas(transaction, attribute).resolve();
----

[#_Thing_unsetHas__TypeDBTransaction__Attribute]
==== unsetHas

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> unsetHas​(TypeDBTransaction transaction,
                                 Attribute attribute)
----

Unassigns an ``Attribute`` from this ``Thing``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
thing.unsetHas(transaction, attribute).resolve();
----

// end::methods[]

