[#_Value]
=== Value

*Package*: `com.typedb.driver.api.concept.value`

*Superinterfaces:*

* `Concept`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `DECIMAL_SCALE` a| `static int` a| 
a| `ISO_LOCAL_DATE_TIME_MILLIS` a| `static java.time.format.DateTimeFormatter` a| 
|===
// end::properties[]

// tag::methods[]
[#_Value_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Value_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Value_asBoolean_]
==== asBoolean

[source,java]
----
boolean asBoolean()
----

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.asBoolean();
----

[#_Value_asDate_]
==== asDate

[source,java]
----
java.time.LocalDate asDate()
----

Returns a ``date`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDate`

[caption=""]
.Code examples
[source,java]
----
value.asDate();
----

[#_Value_asDatetime_]
==== asDatetime

[source,java]
----
java.time.LocalDateTime asDatetime()
----

Returns a ``datetime`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDateTime`

[caption=""]
.Code examples
[source,java]
----
value.asDatetime();
----

[#_Value_asDatetimeTZ_]
==== asDatetimeTZ

[source,java]
----
java.time.ZonedDateTime asDatetimeTZ()
----

Returns a ``datetime-tz`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.ZonedDateTime`

[caption=""]
.Code examples
[source,java]
----
value.asDatetimeTZ();
----

[#_Value_asDecimal_]
==== asDecimal

[source,java]
----
java.math.BigDecimal asDecimal()
----

Returns a ``decimal`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.math.BigDecimal`

[caption=""]
.Code examples
[source,java]
----
value.asDecimal();
----

[#_Value_asDouble_]
==== asDouble

[source,java]
----
double asDouble()
----

Returns a ``double`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,java]
----
value.asDouble();
----

[#_Value_asDuration_]
==== asDuration

[source,java]
----
Duration asDuration()
----

Returns a ``duration`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`Duration`

[caption=""]
.Code examples
[source,java]
----
value.asDuration();
----

[#_Value_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Value_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Value_asInstance_]
==== asInstance

[source,java]
----
default Instance asInstance()
----

Casts the concept to ``Instance``. 


[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,java]
----
concept.asInstance();
----

[#_Value_asLong_]
==== asLong

[source,java]
----
long asLong()
----

Returns a ``long`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,java]
----
value.asLong();
----

[#_Value_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Value_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Value_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Value_asString_]
==== asString

[source,java]
----
java.lang.String asString()
----

Returns a ``string`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
value.asString();
----

[#_Value_asStruct_]
==== asStruct

[source,java]
----
java.util.Map<java.lang.String,​java.util.Optional<Value>> asStruct()
----

Returns a ``struct`` value of this value concept represented as a map from field names to values. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.util.Map<java.lang.String,​java.util.Optional<Value>>`

[caption=""]
.Code examples
[source,java]
----
value.asStruct();
----

[#_Value_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Value_asUntyped_]
==== asUntyped

[source,java]
----
java.lang.Object asUntyped()
----

Returns an untyped ``Object`` value of this value concept. This is useful for value equality or printing without having to switch on the actual contained value. 


[caption=""]
.Returns
`java.lang.Object`

[caption=""]
.Code examples
[source,java]
----
value.asUntyped();
----

[#_Value_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Value_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Value_getType_]
==== getType

[source,java]
----
java.lang.String getType()
----

Retrieves the ``String`` describing the value type of this ``Value`` concept. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
value.getType()
----

[#_Value_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Value_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Value_isBoolean_]
==== isBoolean

[source,java]
----
boolean isBoolean()
----

Returns ``True`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isBoolean()
----

[#_Value_isDate_]
==== isDate

[source,java]
----
boolean isDate()
----

Returns ``True`` if the value which this value concept holds is of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDate();
----

[#_Value_isDatetime_]
==== isDatetime

[source,java]
----
boolean isDatetime()
----

Returns ``True`` if the value which this value concept holds is of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDatetime();
----

[#_Value_isDatetimeTZ_]
==== isDatetimeTZ

[source,java]
----
boolean isDatetimeTZ()
----

Returns ``True`` if the value which this value concept holds is of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDatetimeTZ();
----

[#_Value_isDecimal_]
==== isDecimal

[source,java]
----
boolean isDecimal()
----

Returns ``True`` if the value which this value concept holds is of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDecimal();
----

[#_Value_isDouble_]
==== isDouble

[source,java]
----
boolean isDouble()
----

Returns ``True`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDouble();
----

[#_Value_isDuration_]
==== isDuration

[source,java]
----
boolean isDuration()
----

Returns ``True`` if the value which this value concept holds is of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDuration();
----

[#_Value_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Value_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Value_isInstance_]
==== isInstance

[source,java]
----
@CheckReturnValue
default boolean isInstance()
----

Checks if the concept is an ``Instance``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInstance();
----

[#_Value_isLong_]
==== isLong

[source,java]
----
boolean isLong()
----

Returns ``True`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isLong();
----

[#_Value_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Value_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Value_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Value_isString_]
==== isString

[source,java]
----
boolean isString()
----

Returns ``True`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isString();
----

[#_Value_isStruct_]
==== isStruct

[source,java]
----
boolean isStruct()
----

Returns ``True`` if the value which this value concept holds is of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isStruct();
----

[#_Value_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Value_isValue_]
==== isValue

[source,java]
----
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]

