[#_Value]
=== Value

*Package*: `com.vaticle.typedb.driver.api.concept.value`

*Superinterfaces:*

* `Concept`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `ISO_LOCAL_DATE_TIME_MILLIS` a| `static java.time.format.DateTimeFormatter` a| 
|===
// end::properties[]

// tag::methods[]
[#_Value_asAttribute__]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Value_asAttributeType__]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Value_asBoolean__]
==== asBoolean

[source,java]
----
boolean asBoolean()
----

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.asBoolean();
----

[#_Value_asDateTime__]
==== asDateTime

[source,java]
----
java.time.LocalDateTime asDateTime()
----

Returns a ``datetime`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.time.LocalDateTime`

[caption=""]
.Code examples
[source,java]
----
value.asDatetime();
----

[#_Value_asDouble__]
==== asDouble

[source,java]
----
double asDouble()
----

Returns a ``double`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,java]
----
value.asDouble();
----

[#_Value_asEntity__]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Value_asEntityType__]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Value_asLong__]
==== asLong

[source,java]
----
long asLong()
----

Returns a ``long`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,java]
----
value.asLong();
----

[#_Value_asRelation__]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Value_asRelationType__]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Value_asRoleType__]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Value_asString__]
==== asString

[source,java]
----
java.lang.String asString()
----

Returns a ``string`` value of this value concept. If the value has another type, raises an exception. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
value.asString();
----

[#_Value_asThing__]
==== asThing

[source,java]
----
default Thing asThing()
----

Casts the concept to ``Thing``. 


[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,java]
----
concept.asThing();
----

[#_Value_asThingType__]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
concept.asThingType();
----

[#_Value_asType__]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Value_asUntyped__]
==== asUntyped

[source,java]
----
java.lang.Object asUntyped()
----

Returns an untyped ``Object`` value of this value concept. This is useful for value equality or printing without having to switch on the actual contained value. 


[caption=""]
.Returns
`java.lang.Object`

[caption=""]
.Code examples
[source,java]
----
value.asUntyped();
----

[#_Value_asValue__]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Value_getType__]
==== getType

[source,java]
----
Value.Type getType()
----

Retrieves the ``Value.Type`` of this value concept. 


[caption=""]
.Returns
`Value.Type`

[caption=""]
.Code examples
[source,java]
----
value.getType()
----

[#_Value_isAttribute__]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Value_isAttributeType__]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Value_isBoolean__]
==== isBoolean

[source,java]
----
boolean isBoolean()
----

Returns ``True`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isBoolean()
----

[#_Value_isDateTime__]
==== isDateTime

[source,java]
----
boolean isDateTime()
----

Returns ``True`` if the value which this value concept holds is of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDatetime();
----

[#_Value_isDouble__]
==== isDouble

[source,java]
----
boolean isDouble()
----

Returns ``True`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isDouble();
----

[#_Value_isEntity__]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Value_isEntityType__]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Value_isLong__]
==== isLong

[source,java]
----
boolean isLong()
----

Returns ``True`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isLong();
----

[#_Value_isRelation__]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Value_isRelationType__]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Value_isRoleType__]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Value_isString__]
==== isString

[source,java]
----
boolean isString()
----

Returns ``True`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
value.isString();
----

[#_Value_isThing__]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThing();
----

[#_Value_isThingType__]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThingType();
----

[#_Value_isType__]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Value_isValue__]
==== isValue

[source,java]
----
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]

