[#_IConceptRow]
=== IConceptRow

*Package*: `TypeDB.Driver.Api.Answer`



Contains a row of concepts with a header.

// tag::methods[]
[#_IEnumerable_string_TypeDB_Driver_Api_Answer_IConceptRow_ColumnNames]
==== ColumnNames

[source,cs]
----
IEnumerable< string > TypeDB.Driver.Api.Answer.IConceptRow.ColumnNames
----



Produces a collection of all column names (variables) in the header of this IConceptRow. Shared between all the rows in a QueryAnswer.

 
  conceptRow.ColumnNames
 


[caption=""]
.Returns
`IEnumerable< string >`

[#_IEnumerable_IConcept_TypeDB_Driver_Api_Answer_IConceptRow_Concepts]
==== Concepts

[source,cs]
----
IEnumerable< IConcept > TypeDB.Driver.Api.Answer.IConceptRow.Concepts
----



Produces a collection over all concepts in this IConceptRow, skipping empty results.

 
  conceptRow.Concepts
 


[caption=""]
.Returns
`IEnumerable< IConcept >`

[#_IConcept_TypeDB_Driver_Api_Answer_IConceptRow_Get_string_columnName_]
==== Get

[source,cs]
----
IConcept? Get(string columnName)
----



Retrieves a concept for a given column name (variable). Returns null if the variable has an empty answer. Throws an exception if the variable is not present.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnName` a| The variable (column name from ColumnNames) a| `string`
|===

[caption=""]
.Returns
`IConcept?`

[#_IConcept_TypeDB_Driver_Api_Answer_IConceptRow_GetIndex_long_columnIndex_]
==== GetIndex

[source,cs]
----
IConcept? GetIndex(long columnIndex)
----



Retrieves a concept for a given index of the header (ColumnNames). Returns null if the index points to an empty answer. Throws an exception if the index is not in the row's range.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnIndex` a| The column index a| `long`
|===

[caption=""]
.Returns
`IConcept?`

[#_QueryType_TypeDB_Driver_Api_Answer_IConceptRow_QueryType]
==== QueryType

[source,cs]
----
QueryType TypeDB.Driver.Api.Answer.IConceptRow.QueryType
----



Retrieves the executed query's type of this IConceptRow. Shared between all the rows in a QueryAnswer.

 
  conceptRow.QueryType
 


[caption=""]
.Returns
`QueryType`

// end::methods[]

