[#_IExplainables]
=== IExplainables

*Package*: `TypeDB.Driver.Api.IConceptMap`



Contains explainable objects.

// tag::methods[]
[#_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_Attribute_string_variable_]
==== Attribute

[source,cs]
----
IExplainable Attribute(string variable)
----



Retrieves the explainable attribute with the given variable name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `string`
|===

[caption=""]
.Returns
`IExplainable`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.Attribute(variable);
----

[#_IEnumerable_KeyValuePair_string_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_GetAttributes_]
==== GetAttributes

[source,cs]
----
IEnumerable< KeyValuePair< string, IExplainable > > GetAttributes()
----



Retrieves all of this ``IConceptMap``’s explainable attributes.


[caption=""]
.Returns
`IEnumerable< KeyValuePair< string, IExplainable > >`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.GetAttributes();
----

[#_IEnumerable_KeyValuePair_KeyValuePair_string_string_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_GetOwnerships_]
==== GetOwnerships

[source,cs]
----
IEnumerable< KeyValuePair< KeyValuePair< string, string >, IExplainable > > GetOwnerships()
----



Retrieves all of this ``IConceptMap``’s explainable ownerships.


[caption=""]
.Returns
`IEnumerable< KeyValuePair< KeyValuePair< string, string >, IExplainable > >`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.GetOwnerships();
----

[#_IEnumerable_KeyValuePair_string_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_GetRelations_]
==== GetRelations

[source,cs]
----
IEnumerable< KeyValuePair< string, IExplainable > > GetRelations()
----



Retrieves all of this ``IConceptMap``’s explainable relations.


[caption=""]
.Returns
`IEnumerable< KeyValuePair< string, IExplainable > >`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.GetRelations();
----

[#_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_Ownership_string_owner_string_attribute_]
==== Ownership

[source,cs]
----
IExplainable Ownership(string owner, string attribute)
----



Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `owner` a| The string representation of the owner variable a| `string`
a| `attribute` a| The string representation of the attribute variable a| `string`
|===

[caption=""]
.Returns
`IExplainable`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.Ownership(owner, attribute);
----

[#_IExplainable_TypeDB_Driver_Api_IConceptMap_IExplainables_Relation_string_variable_]
==== Relation

[source,cs]
----
IExplainable Relation(string variable)
----



Retrieves the explainable relation with the given variable name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `string`
|===

[caption=""]
.Returns
`IExplainable`

[caption=""]
.Code examples
[source,cs]
----
conceptMap.AllExplainables.Relation(variable);
----

// end::methods[]

