[#_IQueryAnswer]
[.doc-api-reference-driver]
=== IQueryAnswer

`class`

*Package*: `TypeDB.Driver.Api.Answer`



General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.

// tag::methods[]
[#_IConceptDocumentIterator_TypeDB_Driver_Api_Answer_IQueryAnswer_AsConceptDocuments_]
==== method ``AsConceptDocuments``

[source,cs]
----
IConceptDocumentIterator AsConceptDocuments()
----



Casts the query answer to IConceptDocumentIterator.

Implemented in TypeDB.Driver.Api.Answer.IConceptDocumentIterator.

[caption=""]
.Returns
`IConceptDocumentIterator`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.AsConceptDocuments()
----

[#_IConceptRowIterator_TypeDB_Driver_Api_Answer_IQueryAnswer_AsConceptRows_]
==== method ``AsConceptRows``

[source,cs]
----
IConceptRowIterator AsConceptRows()
----



Casts the query answer to IConceptRowIterator.

Implemented in TypeDB.Driver.Api.Answer.IConceptRowIterator.

[caption=""]
.Returns
`IConceptRowIterator`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.AsConceptRows()
----

[#_IOkQueryAnswer_TypeDB_Driver_Api_Answer_IQueryAnswer_AsOk_]
==== method ``AsOk``

[source,cs]
----
IOkQueryAnswer AsOk()
----



Casts the query answer to IOkQueryAnswer.

Implemented in TypeDB.Driver.Api.Answer.IOkQueryAnswer.

[caption=""]
.Returns
`IOkQueryAnswer`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.AsOk()
----

[#_bool_TypeDB_Driver_Api_Answer_IQueryAnswer_IsConceptDocuments]
==== method ``IsConceptDocuments``

[source,cs]
----
bool TypeDB.Driver.Api.Answer.IQueryAnswer.IsConceptDocuments
----



Checks if the query answer is a IConceptDocumentIterator.

Implemented in TypeDB.Driver.Api.Answer.IConceptDocumentIterator.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.IsConceptDocuments
----

[#_bool_TypeDB_Driver_Api_Answer_IQueryAnswer_IsConceptRows]
==== method ``IsConceptRows``

[source,cs]
----
bool TypeDB.Driver.Api.Answer.IQueryAnswer.IsConceptRows
----



Checks if the query answer is a IConceptRowIterator.

Implemented in TypeDB.Driver.Api.Answer.IConceptRowIterator.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.IsConceptRows
----

[#_bool_TypeDB_Driver_Api_Answer_IQueryAnswer_IsOk]
==== method ``IsOk``

[source,cs]
----
bool TypeDB.Driver.Api.Answer.IQueryAnswer.IsOk
----



Checks if the query answer is an IOkQueryAnswer.

Implemented in TypeDB.Driver.Api.Answer.IOkQueryAnswer.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.IsOk
----

[#_QueryType_TypeDB_Driver_Api_Answer_IQueryAnswer_QueryType]
==== method ``QueryType``

[source,cs]
----
QueryType TypeDB.Driver.Api.Answer.IQueryAnswer.QueryType
----



Retrieves the executed query's type of this IQueryAnswer.

[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,cs]
----
queryAnswer.QueryType
----

// end::methods[]

