[#_IDatabase]
=== IDatabase

*Package*: `TypeDB.Driver.Api`

// tag::methods[]
[#_void_TypeDB_Driver_Api_IDatabase_Delete___]
==== Delete

[source,cs]
----
void Delete()
----



Deletes this database.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
database.Delete();
----

[#_ISet__IReplica___TypeDB_Driver_Api_IDatabase_GetReplicas___]
==== GetReplicas

[source,cs]
----
ISet< IReplica > GetReplicas()
----



Set of ``Replica`` instances for this database. Only works in TypeDB Cloud


[caption=""]
.Returns
`ISet< IReplica >`

[caption=""]
.Code examples
[source,cs]
----
database.GetReplicas();
----

[#_string_TypeDB_Driver_Api_IDatabase_GetRuleSchema___]
==== GetRuleSchema

[source,cs]
----
string GetRuleSchema()
----



The rules in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.GetRuleSchema();
----

[#_string_TypeDB_Driver_Api_IDatabase_GetSchema___]
==== GetSchema

[source,cs]
----
string GetSchema()
----



A full schema text as a valid TypeQL define query string.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.GetSchema();
----

[#_string_TypeDB_Driver_Api_IDatabase_GetTypeSchema___]
==== GetTypeSchema

[source,cs]
----
string GetTypeSchema()
----



The types in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.GetTypeSchema();
----

[#_string_TypeDB_Driver_Api_IDatabase_Name]
==== Name

[source,cs]
----
string TypeDB.Driver.Api.IDatabase.Name
----



The database name as a string.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.Name;
----

[#_IReplica_TypeDB_Driver_Api_IDatabase_PreferredReplica]
==== PreferredReplica

[source,cs]
----
IReplica? TypeDB.Driver.Api.IDatabase.PreferredReplica
----



Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`IReplica?`

[caption=""]
.Code examples
[source,cs]
----
database.PreferredReplica;
----

[#_IReplica_TypeDB_Driver_Api_IDatabase_PrimaryReplica]
==== PrimaryReplica

[source,cs]
----
IReplica? TypeDB.Driver.Api.IDatabase.PrimaryReplica
----



Returns the primary replica for this database. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`IReplica?`

[caption=""]
.Code examples
[source,cs]
----
database.PrimaryReplica;
----

// end::methods[]

