[#_ITypeDBDriver]
=== ITypeDBDriver

*Package*: `TypeDB.Driver.Api`

// tag::methods[]
[#_void_TypeDB_Driver_Api_ITypeDBDriver_Close___]
==== Close

[source,cs]
----
void Close()
----



Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
driver.Close();
----

[#_IDatabaseManager_TypeDB_Driver_Api_ITypeDBDriver_Databases]
==== Databases

[source,cs]
----
IDatabaseManager TypeDB.Driver.Api.ITypeDBDriver.Databases
----



The ``IDatabaseManager`` for this connection, providing access to database management methods.


[caption=""]
.Returns
`IDatabaseManager`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases;
----

[#_IUser_TypeDB_Driver_Api_ITypeDBDriver_GetCurrentUser___]
==== GetCurrentUser

[source,cs]
----
IUser GetCurrentUser()
----



Returns the logged-in user for the connection. Only for TypeDB Cloud.


[caption=""]
.Returns
`IUser`

[caption=""]
.Code examples
[source,cs]
----
driver.GetCurrentUser();
----

[#_bool_TypeDB_Driver_Api_ITypeDBDriver_IsOpen___]
==== IsOpen

[source,cs]
----
bool IsOpen()
----



Checks whether this connection is presently open.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
driver.IsOpen();
----

[#_ITypeDBSession_TypeDB_Driver_Api_ITypeDBDriver_Session___string_database__SessionType_type_]
==== Session

[source,cs]
----
ITypeDBSession Session(string database, SessionType type)
----



Opens a session to the given database with default options.

 

See also
[source,cs]
----
 
 
ITypeDBDriver::Session(string, SessionType, TypeDBOptions);
---- 


[caption=""]
.Returns
`ITypeDBSession`

[#_ITypeDBSession_TypeDB_Driver_Api_ITypeDBDriver_Session___string_database__SessionType_type__TypeDBOptions_options_]
==== Session

[source,cs]
----
ITypeDBSession Session(string database, SessionType type, TypeDBOptions options)
----



Opens a communication tunnel (session) to the given database on the running TypeDB server. For more information on the methods, available with sessions, see the ``ITypeDBSession`` section.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the session connects a| `string`
a| `type` a| The type of session to be created (Data or Schema) a| `SessionType`
a| `options` a| ``TypeDBOptions`` for the session a| `TypeDBOptions`
|===

[caption=""]
.Returns
`ITypeDBSession`

[caption=""]
.Code examples
[source,cs]
----
driver.Session(database, sessionType, options);
----

[#_IUserManager_TypeDB_Driver_Api_ITypeDBDriver_Users]
==== Users

[source,cs]
----
IUserManager TypeDB.Driver.Api.ITypeDBDriver.Users
----



The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud.


[caption=""]
.Returns
`IUserManager`

[caption=""]
.Code examples
[source,cs]
----
driver.Users;
----

// end::methods[]

