[#_IUserManager]
=== IUserManager

*Package*: `TypeDB.Driver.Api`



Provides access to all user management methods.

// tag::methods[]
[#_bool_TypeDB_Driver_Api_IUserManager_Contains___string_username_]
==== Contains

[source,csharp]
----
bool Contains(string username)
----



Checks if a user with the given name exists.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| 
|===

[caption=""]
.Returns
`bool`

[#_void_TypeDB_Driver_Api_IUserManager_Create___string_username__string_password_]
==== Create

[source,csharp]
----
void Create(string username, string password)
----



Creates a user with the given name &amp; password.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| 
a| `password` a| The password of the user to be created a| 
|===

[caption=""]
.Returns
`void`

[#_void_TypeDB_Driver_Api_IUserManager_Delete___string_username_]
==== Delete

[source,csharp]
----
void Delete(string username)
----



Deletes a user with the given name.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be deleted a| 
|===

[caption=""]
.Returns
`void`

[#_IUser_TypeDB_Driver_Api_IUserManager_Get___string_username_]
==== Get

[source,csharp]
----
IUser? Get(string username)
----



Retrieves a user with the given name.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| 
|===

[caption=""]
.Returns
`IUser?`

[#_ISet__IUser___TypeDB_Driver_Api_IUserManager_GetAll___]
==== GetAll

[source,csharp]
----
ISet< IUser > GetAll()
----



Retrieves all users which exist on the TypeDB server.


[caption=""]
.Returns
`ISet< IUser >`

[#_void_TypeDB_Driver_Api_IUserManager_SetPassword___string_username__string_password_]
==== SetPassword

[source,csharp]
----
void SetPassword(string username, string password)
----



Sets a new password for a user. This operation can only be performed by administrators.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to set the password of a| 
a| `password` a| The new password a| 
|===

[caption=""]
.Returns
`void`

// end::methods[]

