[#_TypeDBCredential]
=== TypeDBCredential

*Package*: `TypeDB.Driver.Api`



User credentials and TLS encryption settings for connecting to TypeDB Cloud.


[caption=""]
.Examples
[source,cs]
----
// Creates a credential as above, but the connection will be made over TLS.
TypeDBCredential credential = new TypeDBCredential(username, password, true);

// Creates a credential as above, but TLS will use the specified CA to authenticate server certificates.
TypeDBCredential credential = new TypeDBCredential(username, password, Path.of("path/to/ca-certificate.pem"));
----

// tag::methods[]
[#_TypeDB_Driver_Api_TypeDBCredential_TypeDBCredential___string_username__string_password__bool_tlsEnabled_]
==== TypeDBCredential

[source,cs]
----
TypeDBCredential(string username, string password, bool tlsEnabled)
----


 
  Parameters
 
 
  
   
    
     username
     The name of the user to connect as
    
    
     password
     The password for the user
    
    
     tlsEnabled
     Specify whether the connection to TypeDB Cloud must be done over TLS
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `string`
a| `password` a| The password for the user a| `string`
a| `tlsEnabled` a| Specify whether the connection to TypeDB Cloud must be done over TLS a| `bool`
|===

[caption=""]
.Returns
`TypeDBCredential`

[#_TypeDB_Driver_Api_TypeDBCredential_TypeDBCredential___string_username__string_password__string_tlsRootCAPath_]
==== TypeDBCredential

[source,cs]
----
TypeDBCredential(string username, string password, string? tlsRootCAPath)
----


 
  Parameters
 
 
  
   
    
     username
     The name of the user to connect as
    
    
     password
     The password for the user
    
    
     tlsRootCAPath
     Path to the CA certificate to use for authenticating server certificates
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `string`
a| `password` a| The password for the user a| `string`
a| `tlsRootCAPath` a| Path to the CA certificate to use for authenticating server certificates a| `string?`
|===

[caption=""]
.Returns
`TypeDBCredential`

// end::methods[]

