
[#_connection_header]
== Connection

{page-version}@api-ref::partial$java/connection/TypeDB.adoc[]

{page-version}@api-ref::partial$java/connection/TypeDBDriver.adoc[]

{page-version}@api-ref::partial$java/connection/TypeDBCredential.adoc[]

{page-version}@api-ref::partial$java/connection/DatabaseManager.adoc[]

{page-version}@api-ref::partial$java/connection/Database.adoc[]

{page-version}@api-ref::partial$java/connection/Database.Replica.adoc[]

{page-version}@api-ref::partial$java/connection/UserManager.adoc[]

{page-version}@api-ref::partial$java/connection/User.adoc[]

[#_session_header]
== Session

{page-version}@api-ref::partial$java/session/TypeDBSession.adoc[]

{page-version}@api-ref::partial$java/session/TypeDBSession.Type.adoc[]

{page-version}@api-ref::partial$java/session/TypeDBOptions.adoc[]

[#_transaction_header]
== Transaction

{page-version}@api-ref::partial$java/transaction/TypeDBTransaction.adoc[]

{page-version}@api-ref::partial$java/transaction/TypeDBTransaction.Type.adoc[]

{page-version}@api-ref::partial$java/transaction/QueryManager.adoc[]

[#_answer_header]
== Answer

{page-version}@api-ref::partial$java/answer/ConceptMapGroup.adoc[]

{page-version}@api-ref::partial$java/answer/ConceptMap.adoc[]

{page-version}@api-ref::partial$java/answer/ValueGroup.adoc[]

{page-version}@api-ref::partial$java/answer/JSON.adoc[]

{page-version}@api-ref::partial$java/answer/Promise_T_.adoc[]

{page-version}@api-ref::partial$java/answer/ConceptMap.Explainables.adoc[]

{page-version}@api-ref::partial$java/answer/ConceptMap.Explainable.adoc[]

{page-version}@api-ref::partial$java/answer/Explanation.adoc[]

[#_concept_header]
== Concept

{page-version}@api-ref::partial$java/concept/ConceptManager.adoc[]

{page-version}@api-ref::partial$java/concept/Concept.adoc[]

[#_schema_header]
== Schema

{page-version}@api-ref::partial$java/schema/Type.adoc[]

{page-version}@api-ref::partial$java/schema/Label.adoc[]

{page-version}@api-ref::partial$java/schema/ThingType.adoc[]

{page-version}@api-ref::partial$java/schema/EntityType.adoc[]

{page-version}@api-ref::partial$java/schema/RelationType.adoc[]

{page-version}@api-ref::partial$java/schema/RoleType.adoc[]

{page-version}@api-ref::partial$java/schema/AttributeType.adoc[]

{page-version}@api-ref::partial$java/schema/ThingType.Annotation.adoc[]

{page-version}@api-ref::partial$java/schema/Concept.Transitivity.adoc[]

{page-version}@api-ref::partial$java/schema/Value.Type.adoc[]

[#_data_header]
== Data

{page-version}@api-ref::partial$java/data/Thing.adoc[]

{page-version}@api-ref::partial$java/data/Entity.adoc[]

{page-version}@api-ref::partial$java/data/Relation.adoc[]

{page-version}@api-ref::partial$java/data/Attribute.adoc[]

{page-version}@api-ref::partial$java/data/Value.adoc[]

[#_logic_header]
== Logic

{page-version}@api-ref::partial$java/logic/LogicManager.adoc[]

{page-version}@api-ref::partial$java/logic/Rule.adoc[]

[#_errors_header]
== Errors

{page-version}@api-ref::partial$java/errors/TypeDBDriverException.adoc[]

//{page-version}@api-ref::partial$java/errors/ErrorMessage.adoc[]
