[#_AnalyzedFunction]
=== AnalyzedFunction

`Class(name=AnalyzedFunction, anchor=AnalyzedFunction, enumConstants=[], description=[], examples=[], fields=[Variable(name=argumentAnnotations, anchor=null, defaultValue=null, description=null, type=VariableAnnotations), Variable(name=arguments, anchor=null, defaultValue=null, description=null, type=string), Variable(name=body, anchor=null, defaultValue=null, description=null, type=AnalyzedPipeline), Variable(name=returnAnnotations, anchor=null, defaultValue=null, description=null, type=VariableAnnotations), Variable(name=returns, anchor=null, defaultValue=null, description=null, type=FunctionReturnStructure)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `argumentAnnotations` a| `VariableAnnotations` a| 
a| `arguments` a| `string` a| 
a| `body` a| `AnalyzedPipeline` a| 
a| `returnAnnotations` a| `VariableAnnotations` a| 
a| `returns` a| `FunctionReturnStructure` a| 
|===
// end::properties[]

