[#_analyzeStaticFunctions]
=== Static Functions

`Class(name=Static Functions, anchor=analyzeStaticFunctions, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=getVariableName, signature=getVariableName( structure: AnalyzedPipeline | QueryStructureLegacy, variable: ConstraintVertexVariable, ): string, anchor=getVariableName_getVariableName_structure_AnalyzedPipeline_variable_ConstraintVertexVariable, args=[Variable(name=structure, anchor=null, defaultValue=null, description=null, type=AnalyzedPipeline), Variable(name=variable, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable)], description=[], examples=[], mode=null, returnDescription=null, returnType=string)], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

// tag::methods[]
[#_getVariableName_getVariableName_structure_AnalyzedPipeline_variable_ConstraintVertexVariable]
==== getVariableName

[source,typescript]
----
getVariableName( structure: AnalyzedPipeline | QueryStructureLegacy, variable: ConstraintVertexVariable, ): string
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `structure` a|  a| `AnalyzedPipeline`
a| `variable` a|  a| `ConstraintVertexVariable`
|===

[caption=""]
.Returns
`string`

// end::methods[]

