[#_ConstraintFunction]
==== ConstraintFunction

`Class(name=ConstraintFunction, anchor=ConstraintFunction, enumConstants=[], description=[], examples=[], fields=[Variable(name=arguments, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=assigned, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=name, anchor=null, defaultValue=null, description=null, type=string), Variable(name=tag, anchor=null, defaultValue=null, description=null, type="functionCall"), Variable(name=textSpan, anchor=null, defaultValue=null, description=null, type=ConstraintSpan)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `arguments` a| `ConstraintVertexVariable` a| 
a| `assigned` a| `ConstraintVertexVariable` a| 
a| `name` a| `string` a| 
a| `tag` a| `"functionCall"` a| 
a| `textSpan` a| `ConstraintSpan` a| 
|===
// end::properties[]

