[#_ConstraintLinks]
==== ConstraintLinks

`Class(name=ConstraintLinks, anchor=ConstraintLinks, enumConstants=[], description=[], examples=[], fields=[Variable(name=player, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=relation, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=role, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=tag, anchor=null, defaultValue=null, description=null, type="links"), Variable(name=textSpan, anchor=null, defaultValue=null, description=null, type=ConstraintSpan)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `player` a| `ConstraintVertexVariable` a| 
a| `relation` a| `ConstraintVertexVariable` a| 
a| `role` a| `ConstraintVertexVariable` a| 
a| `tag` a| `"links"` a| 
a| `textSpan` a| `ConstraintSpan` a| 
|===
// end::properties[]

