[#_methods__logic__rule]
=== rule

[#_Struct_Rule]
==== Struct Rule



Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

[#_Struct_RuleIterator]
==== Struct RuleIterator



An iterator over ``Rule``s in the database

[#_Struct_RulePromise]
==== Struct RulePromise



Promise object representing the result of an asynchronous operation. Use rule_promise_resolve(RulePromise*) to wait for and retrieve the resulting ``Rule``.

[#_rule_delete]
==== rule_delete

[source,cpp]
----
struct VoidPromise* rule_delete(const struct Transaction* transaction, struct Rule* rule)
----



Deletes this rule.

[caption=""]
.Returns
`struct VoidPromise*`

[#_rule_drop]
==== rule_drop

[source,cpp]
----
void rule_drop(struct Rule* rule)
----



Frees the native rust ``ReplicaInfoIterator`` object.

[caption=""]
.Returns
`void`

[#_rule_get_label]
==== rule_get_label

[source,cpp]
----
char* rule_get_label(const struct Rule* rule)
----



Retrieves the unique label of the rule.

[caption=""]
.Returns
`char*`

[#_rule_get_then]
==== rule_get_then

[source,cpp]
----
char* rule_get_then(const struct Rule* rule)
----



The single statement that constitutes the ‘then’ of the rule.

[caption=""]
.Returns
`char*`

[#_rule_get_when]
==== rule_get_when

[source,cpp]
----
char* rule_get_when(const struct Rule* rule)
----



The statements that constitute the ‘when’ of the rule.

[caption=""]
.Returns
`char*`

[#_rule_is_deleted]
==== rule_is_deleted

[source,cpp]
----
struct BoolPromise* rule_is_deleted(const struct Transaction* transaction, struct Rule* rule)
----



Check if this rule has been deleted.

[caption=""]
.Returns
`struct BoolPromise*`

[#_rule_iterator_drop]
==== rule_iterator_drop

[source,cpp]
----
void rule_iterator_drop(struct RuleIterator* it)
----



Frees the native rust ``RuleIterator`` object.

[caption=""]
.Returns
`void`

[#_rule_iterator_next]
==== rule_iterator_next

[source,cpp]
----
struct Rule* rule_iterator_next(struct RuleIterator* it)
----



Forwards the ``RuleIterator`` and returns the next ``Rule`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct Rule*`

[#_rule_promise_resolve]
==== rule_promise_resolve

[source,cpp]
----
struct Rule* rule_promise_resolve(struct RulePromise* promise)
----



Waits for and returns the result of the operation represented by the ``RulePromise`` object. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`struct Rule*`

[#_rule_set_label]
==== rule_set_label

[source,cpp]
----
struct VoidPromise* rule_set_label(const struct Transaction* transaction, struct Rule* rule, const char* new_label)
----



Renames the label of the rule. The new label must remain unique.

[caption=""]
.Returns
`struct VoidPromise*`

[#_rule_to_string]
==== rule_to_string

[source,cpp]
----
char* rule_to_string(const struct Rule* rule)
----



A string representation of this ``Rule`` object

[caption=""]
.Returns
`char*`

