[#_LogicManager]
=== LogicManager

*Package*: `com.vaticle.typedb.driver.api.logic`

Provides methods for manipulating rules in the database.

// tag::methods[]
[#_LogicManager_getRule__java_lang_String]
==== getRule

[source,java]
----
@CheckReturnValue
Promise<Rule> getRule​(java.lang.String label)
----

Retrieves the Rule that has the given label. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<Rule>`

[caption=""]
.Code examples
[source,java]
----
transaction.logic().getRule(label).resolve();
----

[#_LogicManager_getRules__]
==== getRules

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Rule> getRules()
----

Retrieves all rules. 


[caption=""]
.Returns
`java.util.stream.Stream<? extends Rule>`

[caption=""]
.Code examples
[source,java]
----
transaction.logic().getRules()
----

[#_LogicManager_putRule__java_lang_String__com_vaticle_typeql_lang_pattern_Pattern__com_vaticle_typeql_lang_pattern_Pattern]
==== putRule

[source,java]
----
@CheckReturnValue
Promise<Rule> putRule​(java.lang.String label,
                      com.vaticle.typeql.lang.pattern.Pattern when,
                      com.vaticle.typeql.lang.pattern.Pattern then)
----

Creates a new Rule if none exists with the given label, or replaces the existing one. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or replace a| `java.lang.String`
a| `when` a| The when body of the rule to create a| `com.vaticle.typeql.lang.pattern.Pattern`
a| `then` a| The then body of the rule to create a| `com.vaticle.typeql.lang.pattern.Pattern`
|===

[caption=""]
.Returns
`Promise<Rule>`

[caption=""]
.Code examples
[source,java]
----
transaction.logic().putRule(label, when, then).resolve();
----

// end::methods[]

