[#_ConceptManager]
=== ConceptManager

Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptManager_get_attribute__iid_str]
==== get_attribute

[source,python]
----
get_attribute(iid: str) -> Promise[Attribute]
----

Retrieves an ``Attribute`` by its iid.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[Attribute]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_attribute(iid).resolve()
----

[#_ConceptManager_get_attribute_type__label_str]
==== get_attribute_type

[source,python]
----
get_attribute_type(label: str) -> Promise[AttributeType]
----

Retrieves an ``AttributeType`` by its label.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``AttributeType`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[AttributeType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_attribute_type(label).resolve()
----

[#_ConceptManager_get_entity__iid_str]
==== get_entity

[source,python]
----
get_entity(iid: str) -> Promise[Entity]
----

Retrieves an ``Entity`` by its iid.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the ``Entity`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[Entity]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_entity(iid).resolve()
----

[#_ConceptManager_get_entity_type__label_str]
==== get_entity_type

[source,python]
----
get_entity_type(label: str) -> Promise[EntityType]
----

Retrieves an ``EntityType`` by its label.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``EntityType`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[EntityType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_entity_type(label).resolve()
----

[#_ConceptManager_get_relation__iid_str]
==== get_relation

[source,python]
----
get_relation(iid: str) -> Promise[Relation]
----

Retrieves a ``Relation`` by its iid.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the ``Relation`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[Relation]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_relation(iid).resolve()
----

[#_ConceptManager_get_relation_type__label_str]
==== get_relation_type

[source,python]
----
get_relation_type(label: str) -> Promise[RelationType]
----

Retrieves a ``RelationType`` by its label.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``RelationType`` to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[RelationType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_relation_type(label).resolve()
----

[#_ConceptManager_get_root_attribute_type__]
==== get_root_attribute_type

[source,python]
----
get_root_attribute_type() -> AttributeType
----

Retrieve the root ``AttributeType``, “attribute”.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_root_attribute_type()
----

[#_ConceptManager_get_root_entity_type__]
==== get_root_entity_type

[source,python]
----
get_root_entity_type() -> EntityType
----

Retrieves the root ``EntityType``, “entity”.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_root_entity_type()
----

[#_ConceptManager_get_root_relation_type__]
==== get_root_relation_type

[source,python]
----
get_root_relation_type() -> RelationType
----

Retrieve the root ``RelationType``, “relation”.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_root_relation_type()
----

[#_ConceptManager_get_schema_exception__]
==== get_schema_exception

[source,python]
----
get_schema_exception() -> list[TypeDBException]
----

Retrieves a list of all schema exceptions for the current transaction.

[caption=""]
.Returns
`list[TypeDBException]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.get_schema_exception()
----

[#_ConceptManager_put_attribute_type__label_str__value_type_ValueType]
==== put_attribute_type

[source,python]
----
put_attribute_type(label: str, value_type: ValueType) -> Promise[AttributeType]
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `str` a| 
a| `value_type` a| The value type of the ``AttributeType`` to create or retrieve. a| `ValueType` a| 
|===

[caption=""]
.Returns
`Promise[AttributeType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.put_attribute_type(label, value_type).resolve()
----

[#_ConceptManager_put_entity_type__label_str]
==== put_entity_type

[source,python]
----
put_entity_type(label: str) -> Promise[EntityType]
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[EntityType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.put_entity_type(label).resolve()
----

[#_ConceptManager_put_relation_type__label_str]
==== put_relation_type

[source,python]
----
put_relation_type(label: str) -> Promise[RelationType]
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Promise[RelationType]`

[caption=""]
.Code examples
[source,python]
----
transaction.concepts.put_relation_type(label).resolve()
----

// end::methods[]

