[#_Concept]
=== Concept

// tag::methods[]
[#_Concept_as_attribute__]
==== as_attribute

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
concept.as_attribute()
----

[#_Concept_as_attribute_type__]
==== as_attribute_type

[source,python]
----
as_attribute_type() -> AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
concept.as_attribute_type()
----

[#_Concept_as_entity__]
==== as_entity

[source,python]
----
as_entity() -> Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,python]
----
concept.as_entity()
----

[#_Concept_as_entity_type__]
==== as_entity_type

[source,python]
----
as_entity_type() -> EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,python]
----
concept.as_entity_type()
----

[#_Concept_as_relation__]
==== as_relation

[source,python]
----
as_relation() -> Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,python]
----
concept.as_relation()
----

[#_Concept_as_relation_type__]
==== as_relation_type

[source,python]
----
as_relation_type() -> RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
concept.as_relation_type()
----

[#_Concept_as_role_type__]
==== as_role_type

[source,python]
----
as_role_type() -> RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,python]
----
concept.as_role_type()
----

[#_Concept_as_thing__]
==== as_thing

[source,python]
----
as_thing() -> Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,python]
----
concept.as_thing()
----

[#_Concept_as_thing_type__]
==== as_thing_type

[source,python]
----
as_thing_type() -> ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,python]
----
concept.as_thing_type()
----

[#_Concept_as_type__]
==== as_type

[source,python]
----
as_type() -> Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,python]
----
concept.as_type()
----

[#_Concept_as_value__]
==== as_value

[source,python]
----
as_value() -> Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,python]
----
concept.as_value()
----

[#_Concept_is_attribute__]
==== is_attribute

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_attribute()
----

[#_Concept_is_attribute_type__]
==== is_attribute_type

[source,python]
----
is_attribute_type() -> bool
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_attribute_type()
----

[#_Concept_is_entity__]
==== is_entity

[source,python]
----
is_entity() -> bool
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_entity()
----

[#_Concept_is_entity_type__]
==== is_entity_type

[source,python]
----
is_entity_type() -> bool
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_entity_type()
----

[#_Concept_is_relation__]
==== is_relation

[source,python]
----
is_relation() -> bool
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_relation()
----

[#_Concept_is_relation_type__]
==== is_relation_type

[source,python]
----
is_relation_type() -> bool
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_relation_type()
----

[#_Concept_is_role_type__]
==== is_role_type

[source,python]
----
is_role_type() -> bool
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_role_type()
----

[#_Concept_is_thing__]
==== is_thing

[source,python]
----
is_thing() -> bool
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_thing()
----

[#_Concept_is_thing_type__]
==== is_thing_type

[source,python]
----
is_thing_type() -> bool
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_thing_type()
----

[#_Concept_is_type__]
==== is_type

[source,python]
----
is_type() -> bool
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_type()
----

[#_Concept_is_value__]
==== is_value

[source,python]
----
is_value() -> bool
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_value()
----

// end::methods[]

