[#_Constraint_Not]
=== Constraint.Not

`Class(name=Constraint.Not, anchor=Constraint_Not, enumConstants=[], description=[Represents a "not" constraint: not { 
 }
], examples=[], fields=[], methods=[Method(name=conjunction, signature=ConjunctionID conjunction(), anchor=Constraint_Not_conjunction_, args=[], description=[Index into ``Pipeline.conjunctions``], examples=[], mode=null, returnDescription=null, returnType=ConjunctionID), Method(name=asComparison, signature=Constraint.Comparison asComparison(), anchor=Constraint_Not_asComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Comparison), Method(name=asExpression, signature=Constraint.Expression asExpression(), anchor=Constraint_Not_asExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Expression), Method(name=asFunctionCall, signature=Constraint.FunctionCall asFunctionCall(), anchor=Constraint_Not_asFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.FunctionCall), Method(name=asHas, signature=Constraint.Has asHas(), anchor=Constraint_Not_asHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Has), Method(name=asIid, signature=Constraint.Iid asIid(), anchor=Constraint_Not_asIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Iid), Method(name=asIs, signature=Constraint.Is asIs(), anchor=Constraint_Not_asIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Is), Method(name=asIsa, signature=Constraint.Isa asIsa(), anchor=Constraint_Not_asIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Isa), Method(name=asKind, signature=Constraint.Kind asKind(), anchor=Constraint_Not_asKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Kind), Method(name=asLabel, signature=Constraint.Label asLabel(), anchor=Constraint_Not_asLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Label), Method(name=asLinks, signature=Constraint.Links asLinks(), anchor=Constraint_Not_asLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Links), Method(name=asNot, signature=Constraint.Not asNot(), anchor=Constraint_Not_asNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Not), Method(name=asOr, signature=Constraint.Or asOr(), anchor=Constraint_Not_asOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Or), Method(name=asOwns, signature=Constraint.Owns asOwns(), anchor=Constraint_Not_asOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Owns), Method(name=asPlays, signature=Constraint.Plays asPlays(), anchor=Constraint_Not_asPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Plays), Method(name=asRelates, signature=Constraint.Relates asRelates(), anchor=Constraint_Not_asRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Relates), Method(name=asSub, signature=Constraint.Sub asSub(), anchor=Constraint_Not_asSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Sub), Method(name=asTry, signature=Constraint.Try asTry(), anchor=Constraint_Not_asTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Try), Method(name=asValue, signature=Constraint.Value asValue(), anchor=Constraint_Not_asValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Value), Method(name=isComparison, signature=boolean isComparison(), anchor=Constraint_Not_isComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isExpression, signature=boolean isExpression(), anchor=Constraint_Not_isExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isFunctionCall, signature=boolean isFunctionCall(), anchor=Constraint_Not_isFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isHas, signature=boolean isHas(), anchor=Constraint_Not_isHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIid, signature=boolean isIid(), anchor=Constraint_Not_isIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIs, signature=boolean isIs(), anchor=Constraint_Not_isIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIsa, signature=boolean isIsa(), anchor=Constraint_Not_isIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isKind, signature=boolean isKind(), anchor=Constraint_Not_isKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLabel, signature=boolean isLabel(), anchor=Constraint_Not_isLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLinks, signature=boolean isLinks(), anchor=Constraint_Not_isLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isNot, signature=boolean isNot(), anchor=Constraint_Not_isNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOr, signature=boolean isOr(), anchor=Constraint_Not_isOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOwns, signature=boolean isOwns(), anchor=Constraint_Not_isOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPlays, signature=boolean isPlays(), anchor=Constraint_Not_isPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelates, signature=boolean isRelates(), anchor=Constraint_Not_isRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSub, signature=boolean isSub(), anchor=Constraint_Not_isSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isTry, signature=boolean isTry(), anchor=Constraint_Not_isTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=Constraint_Not_isValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=span, signature=Constraint.Span span(), anchor=Constraint_Not_span_, args=[], description=[Gets the span of this constraint.], examples=[], mode=null, returnDescription=null, returnType=Constraint.Span), Method(name=variant, signature=com.typedb.driver.jni.ConstraintVariant variant(), anchor=Constraint_Not_variant_, args=[], description=[Gets the variant of this constraint.], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ConstraintVariant)], packagePath=com.typedb.driver.api.analyze, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Constraint`

Represents a "not" constraint: not { 
 }


// tag::methods[]
[#_Constraint_Not_asComparison_]
==== asComparison

[source,java]
----
Constraint.Comparison asComparison()
----



[caption=""]
.Returns
`Constraint.Comparison`

[#_Constraint_Not_asExpression_]
==== asExpression

[source,java]
----
Constraint.Expression asExpression()
----



[caption=""]
.Returns
`Constraint.Expression`

[#_Constraint_Not_asFunctionCall_]
==== asFunctionCall

[source,java]
----
Constraint.FunctionCall asFunctionCall()
----



[caption=""]
.Returns
`Constraint.FunctionCall`

[#_Constraint_Not_asHas_]
==== asHas

[source,java]
----
Constraint.Has asHas()
----



[caption=""]
.Returns
`Constraint.Has`

[#_Constraint_Not_asIid_]
==== asIid

[source,java]
----
Constraint.Iid asIid()
----



[caption=""]
.Returns
`Constraint.Iid`

[#_Constraint_Not_asIs_]
==== asIs

[source,java]
----
Constraint.Is asIs()
----



[caption=""]
.Returns
`Constraint.Is`

[#_Constraint_Not_asIsa_]
==== asIsa

[source,java]
----
Constraint.Isa asIsa()
----



[caption=""]
.Returns
`Constraint.Isa`

[#_Constraint_Not_asKind_]
==== asKind

[source,java]
----
Constraint.Kind asKind()
----



[caption=""]
.Returns
`Constraint.Kind`

[#_Constraint_Not_asLabel_]
==== asLabel

[source,java]
----
Constraint.Label asLabel()
----



[caption=""]
.Returns
`Constraint.Label`

[#_Constraint_Not_asLinks_]
==== asLinks

[source,java]
----
Constraint.Links asLinks()
----



[caption=""]
.Returns
`Constraint.Links`

[#_Constraint_Not_asNot_]
==== asNot

[source,java]
----
Constraint.Not asNot()
----



[caption=""]
.Returns
`Constraint.Not`

[#_Constraint_Not_asOr_]
==== asOr

[source,java]
----
Constraint.Or asOr()
----



[caption=""]
.Returns
`Constraint.Or`

[#_Constraint_Not_asOwns_]
==== asOwns

[source,java]
----
Constraint.Owns asOwns()
----



[caption=""]
.Returns
`Constraint.Owns`

[#_Constraint_Not_asPlays_]
==== asPlays

[source,java]
----
Constraint.Plays asPlays()
----



[caption=""]
.Returns
`Constraint.Plays`

[#_Constraint_Not_asRelates_]
==== asRelates

[source,java]
----
Constraint.Relates asRelates()
----



[caption=""]
.Returns
`Constraint.Relates`

[#_Constraint_Not_asSub_]
==== asSub

[source,java]
----
Constraint.Sub asSub()
----



[caption=""]
.Returns
`Constraint.Sub`

[#_Constraint_Not_asTry_]
==== asTry

[source,java]
----
Constraint.Try asTry()
----



[caption=""]
.Returns
`Constraint.Try`

[#_Constraint_Not_asValue_]
==== asValue

[source,java]
----
Constraint.Value asValue()
----



[caption=""]
.Returns
`Constraint.Value`

[#_Constraint_Not_conjunction_]
==== conjunction

[source,java]
----
ConjunctionID conjunction()
----

Index into ``Pipeline.conjunctions``

[caption=""]
.Returns
`ConjunctionID`

[#_Constraint_Not_isComparison_]
==== isComparison

[source,java]
----
boolean isComparison()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isExpression_]
==== isExpression

[source,java]
----
boolean isExpression()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isFunctionCall_]
==== isFunctionCall

[source,java]
----
boolean isFunctionCall()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isHas_]
==== isHas

[source,java]
----
boolean isHas()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isIid_]
==== isIid

[source,java]
----
boolean isIid()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isIs_]
==== isIs

[source,java]
----
boolean isIs()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isIsa_]
==== isIsa

[source,java]
----
boolean isIsa()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isKind_]
==== isKind

[source,java]
----
boolean isKind()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isLabel_]
==== isLabel

[source,java]
----
boolean isLabel()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isLinks_]
==== isLinks

[source,java]
----
boolean isLinks()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isNot_]
==== isNot

[source,java]
----
boolean isNot()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isOr_]
==== isOr

[source,java]
----
boolean isOr()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isOwns_]
==== isOwns

[source,java]
----
boolean isOwns()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isPlays_]
==== isPlays

[source,java]
----
boolean isPlays()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isRelates_]
==== isRelates

[source,java]
----
boolean isRelates()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isSub_]
==== isSub

[source,java]
----
boolean isSub()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isTry_]
==== isTry

[source,java]
----
boolean isTry()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Not_span_]
==== span

[source,java]
----
Constraint.Span span()
----

Gets the span of this constraint.

[caption=""]
.Returns
`Constraint.Span`

[#_Constraint_Not_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ConstraintVariant variant()
----

Gets the variant of this constraint.

[caption=""]
.Returns
`com.typedb.driver.jni.ConstraintVariant`

// end::methods[]

