[#_Constraint_Has]
=== Constraint.Has

`Class(name=Constraint.Has, anchor=Constraint_Has, enumConstants=[], description=[Represents a "has" constraint: 
 has 
 
], examples=[], fields=[], methods=[Method(name=owner, signature=ConstraintVertex owner(), anchor=Constraint_Has_owner_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=ConstraintVertex), Method(name=attribute, signature=ConstraintVertex attribute(), anchor=Constraint_Has_attribute_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=ConstraintVertex), Method(name=exactness, signature=com.typedb.driver.jni.ConstraintExactness exactness(), anchor=Constraint_Has_exactness_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ConstraintExactness), Method(name=asComparison, signature=Constraint.Comparison asComparison(), anchor=Constraint_Has_asComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Comparison), Method(name=asExpression, signature=Constraint.Expression asExpression(), anchor=Constraint_Has_asExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Expression), Method(name=asFunctionCall, signature=Constraint.FunctionCall asFunctionCall(), anchor=Constraint_Has_asFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.FunctionCall), Method(name=asHas, signature=Constraint.Has asHas(), anchor=Constraint_Has_asHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Has), Method(name=asIid, signature=Constraint.Iid asIid(), anchor=Constraint_Has_asIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Iid), Method(name=asIs, signature=Constraint.Is asIs(), anchor=Constraint_Has_asIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Is), Method(name=asIsa, signature=Constraint.Isa asIsa(), anchor=Constraint_Has_asIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Isa), Method(name=asKind, signature=Constraint.Kind asKind(), anchor=Constraint_Has_asKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Kind), Method(name=asLabel, signature=Constraint.Label asLabel(), anchor=Constraint_Has_asLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Label), Method(name=asLinks, signature=Constraint.Links asLinks(), anchor=Constraint_Has_asLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Links), Method(name=asNot, signature=Constraint.Not asNot(), anchor=Constraint_Has_asNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Not), Method(name=asOr, signature=Constraint.Or asOr(), anchor=Constraint_Has_asOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Or), Method(name=asOwns, signature=Constraint.Owns asOwns(), anchor=Constraint_Has_asOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Owns), Method(name=asPlays, signature=Constraint.Plays asPlays(), anchor=Constraint_Has_asPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Plays), Method(name=asRelates, signature=Constraint.Relates asRelates(), anchor=Constraint_Has_asRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Relates), Method(name=asSub, signature=Constraint.Sub asSub(), anchor=Constraint_Has_asSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Sub), Method(name=asTry, signature=Constraint.Try asTry(), anchor=Constraint_Has_asTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Try), Method(name=asValue, signature=Constraint.Value asValue(), anchor=Constraint_Has_asValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Value), Method(name=isComparison, signature=boolean isComparison(), anchor=Constraint_Has_isComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isExpression, signature=boolean isExpression(), anchor=Constraint_Has_isExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isFunctionCall, signature=boolean isFunctionCall(), anchor=Constraint_Has_isFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isHas, signature=boolean isHas(), anchor=Constraint_Has_isHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIid, signature=boolean isIid(), anchor=Constraint_Has_isIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIs, signature=boolean isIs(), anchor=Constraint_Has_isIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIsa, signature=boolean isIsa(), anchor=Constraint_Has_isIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isKind, signature=boolean isKind(), anchor=Constraint_Has_isKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLabel, signature=boolean isLabel(), anchor=Constraint_Has_isLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLinks, signature=boolean isLinks(), anchor=Constraint_Has_isLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isNot, signature=boolean isNot(), anchor=Constraint_Has_isNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOr, signature=boolean isOr(), anchor=Constraint_Has_isOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOwns, signature=boolean isOwns(), anchor=Constraint_Has_isOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPlays, signature=boolean isPlays(), anchor=Constraint_Has_isPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelates, signature=boolean isRelates(), anchor=Constraint_Has_isRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSub, signature=boolean isSub(), anchor=Constraint_Has_isSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isTry, signature=boolean isTry(), anchor=Constraint_Has_isTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=Constraint_Has_isValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=span, signature=Constraint.Span span(), anchor=Constraint_Has_span_, args=[], description=[Gets the span of this constraint.], examples=[], mode=null, returnDescription=null, returnType=Constraint.Span), Method(name=variant, signature=com.typedb.driver.jni.ConstraintVariant variant(), anchor=Constraint_Has_variant_, args=[], description=[Gets the variant of this constraint.], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ConstraintVariant)], packagePath=com.typedb.driver.api.analyze, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Constraint`

Represents a "has" constraint: 
 has 
 


// tag::methods[]
[#_Constraint_Has_asComparison_]
==== asComparison

[source,java]
----
Constraint.Comparison asComparison()
----



[caption=""]
.Returns
`Constraint.Comparison`

[#_Constraint_Has_asExpression_]
==== asExpression

[source,java]
----
Constraint.Expression asExpression()
----



[caption=""]
.Returns
`Constraint.Expression`

[#_Constraint_Has_asFunctionCall_]
==== asFunctionCall

[source,java]
----
Constraint.FunctionCall asFunctionCall()
----



[caption=""]
.Returns
`Constraint.FunctionCall`

[#_Constraint_Has_asHas_]
==== asHas

[source,java]
----
Constraint.Has asHas()
----



[caption=""]
.Returns
`Constraint.Has`

[#_Constraint_Has_asIid_]
==== asIid

[source,java]
----
Constraint.Iid asIid()
----



[caption=""]
.Returns
`Constraint.Iid`

[#_Constraint_Has_asIs_]
==== asIs

[source,java]
----
Constraint.Is asIs()
----



[caption=""]
.Returns
`Constraint.Is`

[#_Constraint_Has_asIsa_]
==== asIsa

[source,java]
----
Constraint.Isa asIsa()
----



[caption=""]
.Returns
`Constraint.Isa`

[#_Constraint_Has_asKind_]
==== asKind

[source,java]
----
Constraint.Kind asKind()
----



[caption=""]
.Returns
`Constraint.Kind`

[#_Constraint_Has_asLabel_]
==== asLabel

[source,java]
----
Constraint.Label asLabel()
----



[caption=""]
.Returns
`Constraint.Label`

[#_Constraint_Has_asLinks_]
==== asLinks

[source,java]
----
Constraint.Links asLinks()
----



[caption=""]
.Returns
`Constraint.Links`

[#_Constraint_Has_asNot_]
==== asNot

[source,java]
----
Constraint.Not asNot()
----



[caption=""]
.Returns
`Constraint.Not`

[#_Constraint_Has_asOr_]
==== asOr

[source,java]
----
Constraint.Or asOr()
----



[caption=""]
.Returns
`Constraint.Or`

[#_Constraint_Has_asOwns_]
==== asOwns

[source,java]
----
Constraint.Owns asOwns()
----



[caption=""]
.Returns
`Constraint.Owns`

[#_Constraint_Has_asPlays_]
==== asPlays

[source,java]
----
Constraint.Plays asPlays()
----



[caption=""]
.Returns
`Constraint.Plays`

[#_Constraint_Has_asRelates_]
==== asRelates

[source,java]
----
Constraint.Relates asRelates()
----



[caption=""]
.Returns
`Constraint.Relates`

[#_Constraint_Has_asSub_]
==== asSub

[source,java]
----
Constraint.Sub asSub()
----



[caption=""]
.Returns
`Constraint.Sub`

[#_Constraint_Has_asTry_]
==== asTry

[source,java]
----
Constraint.Try asTry()
----



[caption=""]
.Returns
`Constraint.Try`

[#_Constraint_Has_asValue_]
==== asValue

[source,java]
----
Constraint.Value asValue()
----



[caption=""]
.Returns
`Constraint.Value`

[#_Constraint_Has_attribute_]
==== attribute

[source,java]
----
ConstraintVertex attribute()
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Constraint_Has_exactness_]
==== exactness

[source,java]
----
com.typedb.driver.jni.ConstraintExactness exactness()
----



[caption=""]
.Returns
`com.typedb.driver.jni.ConstraintExactness`

[#_Constraint_Has_isComparison_]
==== isComparison

[source,java]
----
boolean isComparison()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isExpression_]
==== isExpression

[source,java]
----
boolean isExpression()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isFunctionCall_]
==== isFunctionCall

[source,java]
----
boolean isFunctionCall()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isHas_]
==== isHas

[source,java]
----
boolean isHas()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isIid_]
==== isIid

[source,java]
----
boolean isIid()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isIs_]
==== isIs

[source,java]
----
boolean isIs()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isIsa_]
==== isIsa

[source,java]
----
boolean isIsa()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isKind_]
==== isKind

[source,java]
----
boolean isKind()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isLabel_]
==== isLabel

[source,java]
----
boolean isLabel()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isLinks_]
==== isLinks

[source,java]
----
boolean isLinks()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isNot_]
==== isNot

[source,java]
----
boolean isNot()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isOr_]
==== isOr

[source,java]
----
boolean isOr()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isOwns_]
==== isOwns

[source,java]
----
boolean isOwns()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isPlays_]
==== isPlays

[source,java]
----
boolean isPlays()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isRelates_]
==== isRelates

[source,java]
----
boolean isRelates()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isSub_]
==== isSub

[source,java]
----
boolean isSub()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isTry_]
==== isTry

[source,java]
----
boolean isTry()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Has_owner_]
==== owner

[source,java]
----
ConstraintVertex owner()
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Constraint_Has_span_]
==== span

[source,java]
----
Constraint.Span span()
----

Gets the span of this constraint.

[caption=""]
.Returns
`Constraint.Span`

[#_Constraint_Has_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ConstraintVariant variant()
----

Gets the variant of this constraint.

[caption=""]
.Returns
`com.typedb.driver.jni.ConstraintVariant`

// end::methods[]

