[#_Constraint]
=== Constraint

`Class(name=Constraint, anchor=Constraint, enumConstants=[], description=[A representation of a TypeQL constraint.], examples=[], fields=[], methods=[Method(name=variant, signature=com.typedb.driver.jni.ConstraintVariant variant(), anchor=Constraint_variant_, args=[], description=[Gets the variant of this constraint.], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ConstraintVariant), Method(name=span, signature=Constraint.Span span(), anchor=Constraint_span_, args=[], description=[Gets the span of this constraint.], examples=[], mode=null, returnDescription=null, returnType=Constraint.Span), Method(name=isIsa, signature=boolean isIsa(), anchor=Constraint_isIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isHas, signature=boolean isHas(), anchor=Constraint_isHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLinks, signature=boolean isLinks(), anchor=Constraint_isLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSub, signature=boolean isSub(), anchor=Constraint_isSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOwns, signature=boolean isOwns(), anchor=Constraint_isOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelates, signature=boolean isRelates(), anchor=Constraint_isRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPlays, signature=boolean isPlays(), anchor=Constraint_isPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isFunctionCall, signature=boolean isFunctionCall(), anchor=Constraint_isFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isExpression, signature=boolean isExpression(), anchor=Constraint_isExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIs, signature=boolean isIs(), anchor=Constraint_isIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIid, signature=boolean isIid(), anchor=Constraint_isIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isComparison, signature=boolean isComparison(), anchor=Constraint_isComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isKind, signature=boolean isKind(), anchor=Constraint_isKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLabel, signature=boolean isLabel(), anchor=Constraint_isLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=Constraint_isValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOr, signature=boolean isOr(), anchor=Constraint_isOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isNot, signature=boolean isNot(), anchor=Constraint_isNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isTry, signature=boolean isTry(), anchor=Constraint_isTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asIsa, signature=Constraint.Isa asIsa(), anchor=Constraint_asIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Isa), Method(name=asHas, signature=Constraint.Has asHas(), anchor=Constraint_asHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Has), Method(name=asLinks, signature=Constraint.Links asLinks(), anchor=Constraint_asLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Links), Method(name=asSub, signature=Constraint.Sub asSub(), anchor=Constraint_asSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Sub), Method(name=asOwns, signature=Constraint.Owns asOwns(), anchor=Constraint_asOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Owns), Method(name=asRelates, signature=Constraint.Relates asRelates(), anchor=Constraint_asRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Relates), Method(name=asPlays, signature=Constraint.Plays asPlays(), anchor=Constraint_asPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Plays), Method(name=asFunctionCall, signature=Constraint.FunctionCall asFunctionCall(), anchor=Constraint_asFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.FunctionCall), Method(name=asExpression, signature=Constraint.Expression asExpression(), anchor=Constraint_asExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Expression), Method(name=asIs, signature=Constraint.Is asIs(), anchor=Constraint_asIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Is), Method(name=asIid, signature=Constraint.Iid asIid(), anchor=Constraint_asIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Iid), Method(name=asComparison, signature=Constraint.Comparison asComparison(), anchor=Constraint_asComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Comparison), Method(name=asKind, signature=Constraint.Kind asKind(), anchor=Constraint_asKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Kind), Method(name=asLabel, signature=Constraint.Label asLabel(), anchor=Constraint_asLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Label), Method(name=asValue, signature=Constraint.Value asValue(), anchor=Constraint_asValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Value), Method(name=asOr, signature=Constraint.Or asOr(), anchor=Constraint_asOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Or), Method(name=asNot, signature=Constraint.Not asNot(), anchor=Constraint_asNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Not), Method(name=asTry, signature=Constraint.Try asTry(), anchor=Constraint_asTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Try)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A representation of a TypeQL constraint.

// tag::methods[]
[#_Constraint_asComparison_]
==== asComparison

[source,java]
----
Constraint.Comparison asComparison()
----



[caption=""]
.Returns
`Constraint.Comparison`

[#_Constraint_asExpression_]
==== asExpression

[source,java]
----
Constraint.Expression asExpression()
----



[caption=""]
.Returns
`Constraint.Expression`

[#_Constraint_asFunctionCall_]
==== asFunctionCall

[source,java]
----
Constraint.FunctionCall asFunctionCall()
----



[caption=""]
.Returns
`Constraint.FunctionCall`

[#_Constraint_asHas_]
==== asHas

[source,java]
----
Constraint.Has asHas()
----



[caption=""]
.Returns
`Constraint.Has`

[#_Constraint_asIid_]
==== asIid

[source,java]
----
Constraint.Iid asIid()
----



[caption=""]
.Returns
`Constraint.Iid`

[#_Constraint_asIs_]
==== asIs

[source,java]
----
Constraint.Is asIs()
----



[caption=""]
.Returns
`Constraint.Is`

[#_Constraint_asIsa_]
==== asIsa

[source,java]
----
Constraint.Isa asIsa()
----



[caption=""]
.Returns
`Constraint.Isa`

[#_Constraint_asKind_]
==== asKind

[source,java]
----
Constraint.Kind asKind()
----



[caption=""]
.Returns
`Constraint.Kind`

[#_Constraint_asLabel_]
==== asLabel

[source,java]
----
Constraint.Label asLabel()
----



[caption=""]
.Returns
`Constraint.Label`

[#_Constraint_asLinks_]
==== asLinks

[source,java]
----
Constraint.Links asLinks()
----



[caption=""]
.Returns
`Constraint.Links`

[#_Constraint_asNot_]
==== asNot

[source,java]
----
Constraint.Not asNot()
----



[caption=""]
.Returns
`Constraint.Not`

[#_Constraint_asOr_]
==== asOr

[source,java]
----
Constraint.Or asOr()
----



[caption=""]
.Returns
`Constraint.Or`

[#_Constraint_asOwns_]
==== asOwns

[source,java]
----
Constraint.Owns asOwns()
----



[caption=""]
.Returns
`Constraint.Owns`

[#_Constraint_asPlays_]
==== asPlays

[source,java]
----
Constraint.Plays asPlays()
----



[caption=""]
.Returns
`Constraint.Plays`

[#_Constraint_asRelates_]
==== asRelates

[source,java]
----
Constraint.Relates asRelates()
----



[caption=""]
.Returns
`Constraint.Relates`

[#_Constraint_asSub_]
==== asSub

[source,java]
----
Constraint.Sub asSub()
----



[caption=""]
.Returns
`Constraint.Sub`

[#_Constraint_asTry_]
==== asTry

[source,java]
----
Constraint.Try asTry()
----



[caption=""]
.Returns
`Constraint.Try`

[#_Constraint_asValue_]
==== asValue

[source,java]
----
Constraint.Value asValue()
----



[caption=""]
.Returns
`Constraint.Value`

[#_Constraint_isComparison_]
==== isComparison

[source,java]
----
boolean isComparison()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isExpression_]
==== isExpression

[source,java]
----
boolean isExpression()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isFunctionCall_]
==== isFunctionCall

[source,java]
----
boolean isFunctionCall()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isHas_]
==== isHas

[source,java]
----
boolean isHas()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isIid_]
==== isIid

[source,java]
----
boolean isIid()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isIs_]
==== isIs

[source,java]
----
boolean isIs()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isIsa_]
==== isIsa

[source,java]
----
boolean isIsa()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isKind_]
==== isKind

[source,java]
----
boolean isKind()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isLabel_]
==== isLabel

[source,java]
----
boolean isLabel()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isLinks_]
==== isLinks

[source,java]
----
boolean isLinks()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isNot_]
==== isNot

[source,java]
----
boolean isNot()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isOr_]
==== isOr

[source,java]
----
boolean isOr()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isOwns_]
==== isOwns

[source,java]
----
boolean isOwns()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isPlays_]
==== isPlays

[source,java]
----
boolean isPlays()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isRelates_]
==== isRelates

[source,java]
----
boolean isRelates()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isSub_]
==== isSub

[source,java]
----
boolean isSub()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isTry_]
==== isTry

[source,java]
----
boolean isTry()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_span_]
==== span

[source,java]
----
Constraint.Span span()
----

Gets the span of this constraint.

[caption=""]
.Returns
`Constraint.Span`

[#_Constraint_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ConstraintVariant variant()
----

Gets the variant of this constraint.

[caption=""]
.Returns
`com.typedb.driver.jni.ConstraintVariant`

// end::methods[]

