[#_Constraint_Expression]
=== Constraint.Expression

`Class(name=Constraint.Expression, anchor=Constraint_Expression, enumConstants=[], description=[Represents an expression: let 
 = 
 
  e.g., let $x = $y + 5; Here, arguments will be `[$y]`
 
], examples=[], fields=[], methods=[Method(name=text, signature=java.lang.String text(), anchor=Constraint_Expression_text_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=arguments, signature=java.util.stream.Stream<? extends ConstraintVertex> arguments(), anchor=Constraint_Expression_arguments_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends ConstraintVertex>), Method(name=assigned, signature=ConstraintVertex assigned(), anchor=Constraint_Expression_assigned_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=ConstraintVertex), Method(name=asComparison, signature=Constraint.Comparison asComparison(), anchor=Constraint_Expression_asComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Comparison), Method(name=asExpression, signature=Constraint.Expression asExpression(), anchor=Constraint_Expression_asExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Expression), Method(name=asFunctionCall, signature=Constraint.FunctionCall asFunctionCall(), anchor=Constraint_Expression_asFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.FunctionCall), Method(name=asHas, signature=Constraint.Has asHas(), anchor=Constraint_Expression_asHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Has), Method(name=asIid, signature=Constraint.Iid asIid(), anchor=Constraint_Expression_asIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Iid), Method(name=asIs, signature=Constraint.Is asIs(), anchor=Constraint_Expression_asIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Is), Method(name=asIsa, signature=Constraint.Isa asIsa(), anchor=Constraint_Expression_asIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Isa), Method(name=asKind, signature=Constraint.Kind asKind(), anchor=Constraint_Expression_asKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Kind), Method(name=asLabel, signature=Constraint.Label asLabel(), anchor=Constraint_Expression_asLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Label), Method(name=asLinks, signature=Constraint.Links asLinks(), anchor=Constraint_Expression_asLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Links), Method(name=asNot, signature=Constraint.Not asNot(), anchor=Constraint_Expression_asNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Not), Method(name=asOr, signature=Constraint.Or asOr(), anchor=Constraint_Expression_asOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Or), Method(name=asOwns, signature=Constraint.Owns asOwns(), anchor=Constraint_Expression_asOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Owns), Method(name=asPlays, signature=Constraint.Plays asPlays(), anchor=Constraint_Expression_asPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Plays), Method(name=asRelates, signature=Constraint.Relates asRelates(), anchor=Constraint_Expression_asRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Relates), Method(name=asSub, signature=Constraint.Sub asSub(), anchor=Constraint_Expression_asSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Sub), Method(name=asTry, signature=Constraint.Try asTry(), anchor=Constraint_Expression_asTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Try), Method(name=asValue, signature=Constraint.Value asValue(), anchor=Constraint_Expression_asValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Constraint.Value), Method(name=isComparison, signature=boolean isComparison(), anchor=Constraint_Expression_isComparison_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isExpression, signature=boolean isExpression(), anchor=Constraint_Expression_isExpression_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isFunctionCall, signature=boolean isFunctionCall(), anchor=Constraint_Expression_isFunctionCall_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isHas, signature=boolean isHas(), anchor=Constraint_Expression_isHas_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIid, signature=boolean isIid(), anchor=Constraint_Expression_isIid_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIs, signature=boolean isIs(), anchor=Constraint_Expression_isIs_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isIsa, signature=boolean isIsa(), anchor=Constraint_Expression_isIsa_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isKind, signature=boolean isKind(), anchor=Constraint_Expression_isKind_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLabel, signature=boolean isLabel(), anchor=Constraint_Expression_isLabel_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLinks, signature=boolean isLinks(), anchor=Constraint_Expression_isLinks_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isNot, signature=boolean isNot(), anchor=Constraint_Expression_isNot_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOr, signature=boolean isOr(), anchor=Constraint_Expression_isOr_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOwns, signature=boolean isOwns(), anchor=Constraint_Expression_isOwns_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPlays, signature=boolean isPlays(), anchor=Constraint_Expression_isPlays_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelates, signature=boolean isRelates(), anchor=Constraint_Expression_isRelates_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSub, signature=boolean isSub(), anchor=Constraint_Expression_isSub_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isTry, signature=boolean isTry(), anchor=Constraint_Expression_isTry_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=Constraint_Expression_isValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=span, signature=Constraint.Span span(), anchor=Constraint_Expression_span_, args=[], description=[Gets the span of this constraint.], examples=[], mode=null, returnDescription=null, returnType=Constraint.Span), Method(name=variant, signature=com.typedb.driver.jni.ConstraintVariant variant(), anchor=Constraint_Expression_variant_, args=[], description=[Gets the variant of this constraint.], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ConstraintVariant)], packagePath=com.typedb.driver.api.analyze, superClasses=[Constraint], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Constraint`

Represents an expression: let 
 = 
 
  e.g., let $x = $y + 5; Here, arguments will be `[$y]`
 


// tag::methods[]
[#_Constraint_Expression_arguments_]
==== arguments

[source,java]
----
java.util.stream.Stream<? extends ConstraintVertex> arguments()
----



[caption=""]
.Returns
`java.util.stream.Stream<? extends ConstraintVertex>`

[#_Constraint_Expression_asComparison_]
==== asComparison

[source,java]
----
Constraint.Comparison asComparison()
----



[caption=""]
.Returns
`Constraint.Comparison`

[#_Constraint_Expression_asExpression_]
==== asExpression

[source,java]
----
Constraint.Expression asExpression()
----



[caption=""]
.Returns
`Constraint.Expression`

[#_Constraint_Expression_asFunctionCall_]
==== asFunctionCall

[source,java]
----
Constraint.FunctionCall asFunctionCall()
----



[caption=""]
.Returns
`Constraint.FunctionCall`

[#_Constraint_Expression_asHas_]
==== asHas

[source,java]
----
Constraint.Has asHas()
----



[caption=""]
.Returns
`Constraint.Has`

[#_Constraint_Expression_asIid_]
==== asIid

[source,java]
----
Constraint.Iid asIid()
----



[caption=""]
.Returns
`Constraint.Iid`

[#_Constraint_Expression_asIs_]
==== asIs

[source,java]
----
Constraint.Is asIs()
----



[caption=""]
.Returns
`Constraint.Is`

[#_Constraint_Expression_asIsa_]
==== asIsa

[source,java]
----
Constraint.Isa asIsa()
----



[caption=""]
.Returns
`Constraint.Isa`

[#_Constraint_Expression_asKind_]
==== asKind

[source,java]
----
Constraint.Kind asKind()
----



[caption=""]
.Returns
`Constraint.Kind`

[#_Constraint_Expression_asLabel_]
==== asLabel

[source,java]
----
Constraint.Label asLabel()
----



[caption=""]
.Returns
`Constraint.Label`

[#_Constraint_Expression_asLinks_]
==== asLinks

[source,java]
----
Constraint.Links asLinks()
----



[caption=""]
.Returns
`Constraint.Links`

[#_Constraint_Expression_asNot_]
==== asNot

[source,java]
----
Constraint.Not asNot()
----



[caption=""]
.Returns
`Constraint.Not`

[#_Constraint_Expression_asOr_]
==== asOr

[source,java]
----
Constraint.Or asOr()
----



[caption=""]
.Returns
`Constraint.Or`

[#_Constraint_Expression_asOwns_]
==== asOwns

[source,java]
----
Constraint.Owns asOwns()
----



[caption=""]
.Returns
`Constraint.Owns`

[#_Constraint_Expression_asPlays_]
==== asPlays

[source,java]
----
Constraint.Plays asPlays()
----



[caption=""]
.Returns
`Constraint.Plays`

[#_Constraint_Expression_asRelates_]
==== asRelates

[source,java]
----
Constraint.Relates asRelates()
----



[caption=""]
.Returns
`Constraint.Relates`

[#_Constraint_Expression_asSub_]
==== asSub

[source,java]
----
Constraint.Sub asSub()
----



[caption=""]
.Returns
`Constraint.Sub`

[#_Constraint_Expression_asTry_]
==== asTry

[source,java]
----
Constraint.Try asTry()
----



[caption=""]
.Returns
`Constraint.Try`

[#_Constraint_Expression_asValue_]
==== asValue

[source,java]
----
Constraint.Value asValue()
----



[caption=""]
.Returns
`Constraint.Value`

[#_Constraint_Expression_assigned_]
==== assigned

[source,java]
----
ConstraintVertex assigned()
----



[caption=""]
.Returns
`ConstraintVertex`

[#_Constraint_Expression_isComparison_]
==== isComparison

[source,java]
----
boolean isComparison()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isExpression_]
==== isExpression

[source,java]
----
boolean isExpression()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isFunctionCall_]
==== isFunctionCall

[source,java]
----
boolean isFunctionCall()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isHas_]
==== isHas

[source,java]
----
boolean isHas()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isIid_]
==== isIid

[source,java]
----
boolean isIid()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isIs_]
==== isIs

[source,java]
----
boolean isIs()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isIsa_]
==== isIsa

[source,java]
----
boolean isIsa()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isKind_]
==== isKind

[source,java]
----
boolean isKind()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isLabel_]
==== isLabel

[source,java]
----
boolean isLabel()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isLinks_]
==== isLinks

[source,java]
----
boolean isLinks()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isNot_]
==== isNot

[source,java]
----
boolean isNot()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isOr_]
==== isOr

[source,java]
----
boolean isOr()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isOwns_]
==== isOwns

[source,java]
----
boolean isOwns()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isPlays_]
==== isPlays

[source,java]
----
boolean isPlays()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isRelates_]
==== isRelates

[source,java]
----
boolean isRelates()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isSub_]
==== isSub

[source,java]
----
boolean isSub()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isTry_]
==== isTry

[source,java]
----
boolean isTry()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----



[caption=""]
.Returns
`boolean`

[#_Constraint_Expression_span_]
==== span

[source,java]
----
Constraint.Span span()
----

Gets the span of this constraint.

[caption=""]
.Returns
`Constraint.Span`

[#_Constraint_Expression_text_]
==== text

[source,java]
----
java.lang.String text()
----



[caption=""]
.Returns
`java.lang.String`

[#_Constraint_Expression_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ConstraintVariant variant()
----

Gets the variant of this constraint.

[caption=""]
.Returns
`com.typedb.driver.jni.ConstraintVariant`

// end::methods[]

