[#_ConstraintVertex]
=== ConstraintVertex

`Class(name=ConstraintVertex, anchor=ConstraintVertex, enumConstants=[], description=[The answer to a TypeDB query is a set of concepts which satisfy the constraints in the query. A ConstraintVertex is either a variable, or some identifier of the concept. A ``Variable`` is a vertex the query must match and return. A ``Label`` uniquely identifies a type A ``Value`` represents a primitive value literal in TypeDB. A ``NamedRole`` vertex is used in links &amp; relates constraints, as multiple relations may have roles with the same name.], examples=[], fields=[], methods=[Method(name=isVariable, signature=boolean isVariable(), anchor=ConstraintVertex_isVariable_, args=[], description=[Checks if this vertex is a variable.], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLabel, signature=boolean isLabel(), anchor=ConstraintVertex_isLabel_, args=[], description=[Checks if this vertex is a label.], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=ConstraintVertex_isValue_, args=[], description=[Checks if this vertex is a value.], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isNamedRole, signature=boolean isNamedRole(), anchor=ConstraintVertex_isNamedRole_, args=[], description=[Checks if this vertex is a named role.], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asVariable, signature=Variable asVariable(), anchor=ConstraintVertex_asVariable_, args=[], description=[Down-casts this variable to a vertex.], examples=[], mode=null, returnDescription=null, returnType=Variable), Method(name=asLabel, signature=Type asLabel(), anchor=ConstraintVertex_asLabel_, args=[], description=[Down-casts this vertex to a type label.], examples=[], mode=null, returnDescription=null, returnType=Type), Method(name=asValue, signature=Value asValue(), anchor=ConstraintVertex_asValue_, args=[], description=[Down-casts this vertex to a value.], examples=[], mode=null, returnDescription=null, returnType=Value), Method(name=asNamedRole, signature=NamedRole asNamedRole(), anchor=ConstraintVertex_asNamedRole_, args=[], description=[Down-casts this vertex to a NamedRole. This is an internal variable injected to handle ambiguity in unscoped role-names.], examples=[], mode=null, returnDescription=null, returnType=NamedRole)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

The answer to a TypeDB query is a set of concepts which satisfy the constraints in the query. A ConstraintVertex is either a variable, or some identifier of the concept. A ``Variable`` is a vertex the query must match and return. A ``Label`` uniquely identifies a type A ``Value`` represents a primitive value literal in TypeDB. A ``NamedRole`` vertex is used in links &amp; relates constraints, as multiple relations may have roles with the same name.

// tag::methods[]
[#_ConstraintVertex_asLabel_]
==== asLabel

[source,java]
----
Type asLabel()
----

Down-casts this vertex to a type label.

[caption=""]
.Returns
`Type`

[#_ConstraintVertex_asNamedRole_]
==== asNamedRole

[source,java]
----
NamedRole asNamedRole()
----

Down-casts this vertex to a NamedRole. This is an internal variable injected to handle ambiguity in unscoped role-names.

[caption=""]
.Returns
`NamedRole`

[#_ConstraintVertex_asValue_]
==== asValue

[source,java]
----
Value asValue()
----

Down-casts this vertex to a value.

[caption=""]
.Returns
`Value`

[#_ConstraintVertex_asVariable_]
==== asVariable

[source,java]
----
Variable asVariable()
----

Down-casts this variable to a vertex.

[caption=""]
.Returns
`Variable`

[#_ConstraintVertex_isLabel_]
==== isLabel

[source,java]
----
boolean isLabel()
----

Checks if this vertex is a label.

[caption=""]
.Returns
`boolean`

[#_ConstraintVertex_isNamedRole_]
==== isNamedRole

[source,java]
----
boolean isNamedRole()
----

Checks if this vertex is a named role.

[caption=""]
.Returns
`boolean`

[#_ConstraintVertex_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----

Checks if this vertex is a value.

[caption=""]
.Returns
`boolean`

[#_ConstraintVertex_isVariable_]
==== isVariable

[source,java]
----
boolean isVariable()
----

Checks if this vertex is a variable.

[caption=""]
.Returns
`boolean`

// end::methods[]

