[#_Fetch]
=== Fetch

`Class(name=Fetch, anchor=Fetch, enumConstants=[], description=[A representation of the 'fetch' stage of a query], examples=[], fields=[], methods=[Method(name=variant, signature=com.typedb.driver.jni.FetchVariant variant(), anchor=Fetch_variant_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.FetchVariant), Method(name=isLeaf, signature=boolean isLeaf(), anchor=Fetch_isLeaf_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isList, signature=boolean isList(), anchor=Fetch_isList_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isObject, signature=boolean isObject(), anchor=Fetch_isObject_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asLeaf, signature=Fetch.FetchLeaf asLeaf(), anchor=Fetch_asLeaf_, args=[], description=[Down-casts this ``Fetch`` as a ``FetchLeaf`` variant], examples=[], mode=null, returnDescription=null, returnType=Fetch.FetchLeaf), Method(name=asList, signature=Fetch.FetchList asList(), anchor=Fetch_asList_, args=[], description=[Down-casts this ``Fetch`` as a ``FetchList`` variant], examples=[], mode=null, returnDescription=null, returnType=Fetch.FetchList), Method(name=asObject, signature=Fetch.FetchObject asObject(), anchor=Fetch_asObject_, args=[], description=[Down-casts this ``Fetch`` as a ``FetchObject`` variant], examples=[], mode=null, returnDescription=null, returnType=Fetch.FetchObject)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A representation of the 'fetch' stage of a query

// tag::methods[]
[#_Fetch_asLeaf_]
==== asLeaf

[source,java]
----
Fetch.FetchLeaf asLeaf()
----

Down-casts this ``Fetch`` as a ``FetchLeaf`` variant

[caption=""]
.Returns
`Fetch.FetchLeaf`

[#_Fetch_asList_]
==== asList

[source,java]
----
Fetch.FetchList asList()
----

Down-casts this ``Fetch`` as a ``FetchList`` variant

[caption=""]
.Returns
`Fetch.FetchList`

[#_Fetch_asObject_]
==== asObject

[source,java]
----
Fetch.FetchObject asObject()
----

Down-casts this ``Fetch`` as a ``FetchObject`` variant

[caption=""]
.Returns
`Fetch.FetchObject`

[#_Fetch_isLeaf_]
==== isLeaf

[source,java]
----
boolean isLeaf()
----



[caption=""]
.Returns
`boolean`

[#_Fetch_isList_]
==== isList

[source,java]
----
boolean isList()
----



[caption=""]
.Returns
`boolean`

[#_Fetch_isObject_]
==== isObject

[source,java]
----
boolean isObject()
----



[caption=""]
.Returns
`boolean`

[#_Fetch_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.FetchVariant variant()
----



[caption=""]
.Returns
`com.typedb.driver.jni.FetchVariant`

// end::methods[]

