[#_Fetch_FetchObject]
=== Fetch.FetchObject

`Class(name=Fetch.FetchObject, anchor=Fetch_FetchObject, enumConstants=[], description=[A mapping of string keys to ``Fetch`` documents.], examples=[], fields=[], methods=[Method(name=keys, signature=java.util.stream.Stream<java.lang.String> keys(), anchor=Fetch_FetchObject_keys_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<java.lang.String>), Method(name=get, signature=Fetch get​(java.lang.String key), anchor=Fetch_FetchObject_get_java_lang_String, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Fetch)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A mapping of string keys to ``Fetch`` documents.

// tag::methods[]
[#_Fetch_FetchObject_get_java_lang_String]
==== get

[source,java]
----
Fetch get​(java.lang.String key)
----



[caption=""]
.Returns
`Fetch`

[#_Fetch_FetchObject_keys_]
==== keys

[source,java]
----
java.util.stream.Stream<java.lang.String> keys()
----



[caption=""]
.Returns
`java.util.stream.Stream<java.lang.String>`

// end::methods[]

