[#_Function_ReturnOperation_Single]
[.doc-api-reference-driver]
=== Function.ReturnOperation.Single

`class`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Function.ReturnOperation`

Indicates the function returns a single row of the specified variables. e.g. ``return first $x, $y;``

// tag::methods[]
[#_Function_ReturnOperation_Single_asCheck_]
==== method <code>asCheck</code>

[source,java]
----
Function.ReturnOperation.Check asCheck()
----

Down-casts this ReturnOperation to a ``Check`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Check`

[#_Function_ReturnOperation_Single_asReduce_]
==== method <code>asReduce</code>

[source,java]
----
Function.ReturnOperation.Reduce asReduce()
----

Down-casts this ReturnOperation to a Reduce return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Reduce`

[#_Function_ReturnOperation_Single_asSingle_]
==== method <code>asSingle</code>

[source,java]
----
Function.ReturnOperation.Single asSingle()
----

Down-casts this ReturnOperation to a ``Single`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Single`

[#_Function_ReturnOperation_Single_asStream_]
==== method <code>asStream</code>

[source,java]
----
Function.ReturnOperation.Stream asStream()
----

Down-casts this ReturnOperation to a ``Stream`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Stream`

[#_Function_ReturnOperation_Single_isCheck_]
==== method <code>isCheck</code>

[source,java]
----
boolean isCheck()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Single_isReduce_]
==== method <code>isReduce</code>

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Single_isSingle_]
==== method <code>isSingle</code>

[source,java]
----
boolean isSingle()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Single_isStream_]
==== method <code>isStream</code>

[source,java]
----
boolean isStream()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Single_selector_]
==== method <code>selector</code>

[source,java]
----
java.lang.String selector()
----

Gets the selector that determines how the operation selects the row.

[caption=""]
.Returns
`java.lang.String`

[#_Function_ReturnOperation_Single_variables_]
==== method <code>variables</code>

[source,java]
----
java.util.stream.Stream<? extends Variable> variables()
----

Gets the variables in the returned row.

[caption=""]
.Returns
`java.util.stream.Stream<? extends Variable>`

[#_Function_ReturnOperation_Single_variant_]
==== method <code>variant</code>

[source,java]
----
com.typedb.driver.jni.ReturnOperationVariant variant()
----

Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``

[caption=""]
.Returns
`com.typedb.driver.jni.ReturnOperationVariant`

// end::methods[]

