[#_Function_ReturnOperation_Stream]
=== Function.ReturnOperation.Stream

`Class(name=Function.ReturnOperation.Stream, anchor=Function_ReturnOperation_Stream, enumConstants=[], description=[Indicates the function returns a stream of concepts. e.g. ``return { $x, $y };``], examples=[], fields=[], methods=[Method(name=variables, signature=java.util.stream.Stream<? extends Variable> variables(), anchor=Function_ReturnOperation_Stream_variables_, args=[], description=[Gets the variables in the returned row.], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends Variable>), Method(name=asCheck, signature=Function.ReturnOperation.Check asCheck(), anchor=Function_ReturnOperation_Stream_asCheck_, args=[], description=[Down-casts this ReturnOperation to a ``Check`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Check), Method(name=asReduce, signature=Function.ReturnOperation.Reduce asReduce(), anchor=Function_ReturnOperation_Stream_asReduce_, args=[], description=[Down-casts this ReturnOperation to a Reduce return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Reduce), Method(name=asSingle, signature=Function.ReturnOperation.Single asSingle(), anchor=Function_ReturnOperation_Stream_asSingle_, args=[], description=[Down-casts this ReturnOperation to a ``Single`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Single), Method(name=asStream, signature=Function.ReturnOperation.Stream asStream(), anchor=Function_ReturnOperation_Stream_asStream_, args=[], description=[Down-casts this ReturnOperation to a ``Stream`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Stream), Method(name=isCheck, signature=boolean isCheck(), anchor=Function_ReturnOperation_Stream_isCheck_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isReduce, signature=boolean isReduce(), anchor=Function_ReturnOperation_Stream_isReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSingle, signature=boolean isSingle(), anchor=Function_ReturnOperation_Stream_isSingle_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isStream, signature=boolean isStream(), anchor=Function_ReturnOperation_Stream_isStream_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=variant, signature=com.typedb.driver.jni.ReturnOperationVariant variant(), anchor=Function_ReturnOperation_Stream_variant_, args=[], description=[Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ReturnOperationVariant)], packagePath=com.typedb.driver.api.analyze, superClasses=[Function.ReturnOperation], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Function.ReturnOperation`

Indicates the function returns a stream of concepts. e.g. ``return { $x, $y };``

// tag::methods[]
[#_Function_ReturnOperation_Stream_asCheck_]
==== asCheck

[source,java]
----
Function.ReturnOperation.Check asCheck()
----

Down-casts this ReturnOperation to a ``Check`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Check`

[#_Function_ReturnOperation_Stream_asReduce_]
==== asReduce

[source,java]
----
Function.ReturnOperation.Reduce asReduce()
----

Down-casts this ReturnOperation to a Reduce return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Reduce`

[#_Function_ReturnOperation_Stream_asSingle_]
==== asSingle

[source,java]
----
Function.ReturnOperation.Single asSingle()
----

Down-casts this ReturnOperation to a ``Single`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Single`

[#_Function_ReturnOperation_Stream_asStream_]
==== asStream

[source,java]
----
Function.ReturnOperation.Stream asStream()
----

Down-casts this ReturnOperation to a ``Stream`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Stream`

[#_Function_ReturnOperation_Stream_isCheck_]
==== isCheck

[source,java]
----
boolean isCheck()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Stream_isReduce_]
==== isReduce

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Stream_isSingle_]
==== isSingle

[source,java]
----
boolean isSingle()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Stream_isStream_]
==== isStream

[source,java]
----
boolean isStream()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Stream_variables_]
==== variables

[source,java]
----
java.util.stream.Stream<? extends Variable> variables()
----

Gets the variables in the returned row.

[caption=""]
.Returns
`java.util.stream.Stream<? extends Variable>`

[#_Function_ReturnOperation_Stream_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ReturnOperationVariant variant()
----

Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``

[caption=""]
.Returns
`com.typedb.driver.jni.ReturnOperationVariant`

// end::methods[]

