[#_Function_ReturnOperation]
=== Function.ReturnOperation

`Class(name=Function.ReturnOperation, anchor=Function_ReturnOperation, enumConstants=[], description=[A representation of the return operation of a function.], examples=[], fields=[], methods=[Method(name=variant, signature=com.typedb.driver.jni.ReturnOperationVariant variant(), anchor=Function_ReturnOperation_variant_, args=[], description=[Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.ReturnOperationVariant), Method(name=isStream, signature=boolean isStream(), anchor=Function_ReturnOperation_isStream_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSingle, signature=boolean isSingle(), anchor=Function_ReturnOperation_isSingle_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isCheck, signature=boolean isCheck(), anchor=Function_ReturnOperation_isCheck_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isReduce, signature=boolean isReduce(), anchor=Function_ReturnOperation_isReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asStream, signature=Function.ReturnOperation.Stream asStream(), anchor=Function_ReturnOperation_asStream_, args=[], description=[Down-casts this ReturnOperation to a ``Stream`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Stream), Method(name=asSingle, signature=Function.ReturnOperation.Single asSingle(), anchor=Function_ReturnOperation_asSingle_, args=[], description=[Down-casts this ReturnOperation to a ``Single`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Single), Method(name=asCheck, signature=Function.ReturnOperation.Check asCheck(), anchor=Function_ReturnOperation_asCheck_, args=[], description=[Down-casts this ReturnOperation to a ``Check`` return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Check), Method(name=asReduce, signature=Function.ReturnOperation.Reduce asReduce(), anchor=Function_ReturnOperation_asReduce_, args=[], description=[Down-casts this ReturnOperation to a Reduce return operation.], examples=[], mode=null, returnDescription=null, returnType=Function.ReturnOperation.Reduce)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A representation of the return operation of a function.

// tag::methods[]
[#_Function_ReturnOperation_asCheck_]
==== asCheck

[source,java]
----
Function.ReturnOperation.Check asCheck()
----

Down-casts this ReturnOperation to a ``Check`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Check`

[#_Function_ReturnOperation_asReduce_]
==== asReduce

[source,java]
----
Function.ReturnOperation.Reduce asReduce()
----

Down-casts this ReturnOperation to a Reduce return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Reduce`

[#_Function_ReturnOperation_asSingle_]
==== asSingle

[source,java]
----
Function.ReturnOperation.Single asSingle()
----

Down-casts this ReturnOperation to a ``Single`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Single`

[#_Function_ReturnOperation_asStream_]
==== asStream

[source,java]
----
Function.ReturnOperation.Stream asStream()
----

Down-casts this ReturnOperation to a ``Stream`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Stream`

[#_Function_ReturnOperation_isCheck_]
==== isCheck

[source,java]
----
boolean isCheck()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_isReduce_]
==== isReduce

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_isSingle_]
==== isSingle

[source,java]
----
boolean isSingle()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_isStream_]
==== isStream

[source,java]
----
boolean isStream()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.ReturnOperationVariant variant()
----

Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``

[caption=""]
.Returns
`com.typedb.driver.jni.ReturnOperationVariant`

// end::methods[]

