[#_Function_ReturnOperation_Reduce]
[.doc-api-reference-driver]
=== Function.ReturnOperation.Reduce

`class`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `Function.ReturnOperation`

Indicates the function returns an aggregation over the rows in the body. e.g. ``return count($x), sum($y);``

// tag::methods[]
[#_Function_ReturnOperation_Reduce_asCheck_]
===== method ``asCheck``

[source,java]
----
Function.ReturnOperation.Check asCheck()
----

Down-casts this ReturnOperation to a ``Check`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Check`

[#_Function_ReturnOperation_Reduce_asReduce_]
===== method ``asReduce``

[source,java]
----
default Function.ReturnOperation.Reduce asReduce()
----

Down-casts this ReturnOperation to a Reduce return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Reduce`

[#_Function_ReturnOperation_Reduce_asSingle_]
===== method ``asSingle``

[source,java]
----
Function.ReturnOperation.Single asSingle()
----

Down-casts this ReturnOperation to a ``Single`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Single`

[#_Function_ReturnOperation_Reduce_asStream_]
===== method ``asStream``

[source,java]
----
Function.ReturnOperation.Stream asStream()
----

Down-casts this ReturnOperation to a ``Stream`` return operation.

[caption=""]
.Returns
`Function.ReturnOperation.Stream`

[#_Function_ReturnOperation_Reduce_isCheck_]
===== method ``isCheck``

[source,java]
----
boolean isCheck()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Reduce_isReduce_]
===== method ``isReduce``

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Reduce_isSingle_]
===== method ``isSingle``

[source,java]
----
boolean isSingle()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Reduce_isStream_]
===== method ``isStream``

[source,java]
----
boolean isStream()
----



[caption=""]
.Returns
`boolean`

[#_Function_ReturnOperation_Reduce_reducers_]
===== method ``reducers``

[source,java]
----
java.util.stream.Stream<? extends Reducer> reducers()
----

Gets the reducers used to compute the aggregations.

[caption=""]
.Returns
`java.util.stream.Stream<? extends Reducer>`

[#_Function_ReturnOperation_Reduce_variant_]
===== method ``variant``

[source,java]
----
com.typedb.driver.jni.ReturnOperationVariant variant()
----

Gets the variant of this return operation. One of: ``StreamReturn, SingleReturn, CheckReturn, ReduceReturn``

[caption=""]
.Returns
`com.typedb.driver.jni.ReturnOperationVariant`

// end::methods[]

