[#_Function]
[.doc-api-reference-driver]
=== Function

`class`

*Package*: `com.typedb.driver.api.analyze`

Holds a representation of a function, and the result of type-inference for each variable.

// tag::methods[]
[#_Function_argument_annotations_]
==== method <code>argument_annotations</code>

[source,java]
----
java.util.stream.Stream<? extends VariableAnnotations> argument_annotations()
----

Gets the type annotations for each argument of the function.

[caption=""]
.Returns
`java.util.stream.Stream<? extends VariableAnnotations>`

[#_Function_argument_variables_]
==== method <code>argument_variables</code>

[source,java]
----
java.util.stream.Stream<? extends Variable> argument_variables()
----

Gets the variables which are the arguments of the function.

[caption=""]
.Returns
`java.util.stream.Stream<? extends Variable>`

[#_Function_body_]
==== method <code>body</code>

[source,java]
----
Pipeline body()
----

Gets the pipeline which forms the body of the function.

[caption=""]
.Returns
`Pipeline`

[#_Function_return_annotations_]
==== method <code>return_annotations</code>

[source,java]
----
java.util.stream.Stream<? extends VariableAnnotations> return_annotations()
----

Gets the type annotations for each concept returned by the function.

[caption=""]
.Returns
`java.util.stream.Stream<? extends VariableAnnotations>`

[#_Function_return_operation_]
==== method <code>return_operation</code>

[source,java]
----
Function.ReturnOperation return_operation()
----

Gets the return operation of the function.

[caption=""]
.Returns
`Function.ReturnOperation`

// end::methods[]

