[#_Pipeline]
=== Pipeline

`Class(name=Pipeline, anchor=Pipeline, enumConstants=[], description=[A representation of a query pipeline.], examples=[], fields=[], methods=[Method(name=stages, signature=java.util.stream.Stream<? extends PipelineStage> stages(), anchor=Pipeline_stages_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends PipelineStage>), Method(name=getVariableName, signature=java.util.Optional<java.lang.String> getVariableName​(Variable variable), anchor=Pipeline_getVariableName_Variable, args=[], description=[Gets the name of the specified variable, if it has one.], examples=[], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=conjunction, signature=java.util.Optional<? extends Conjunction> conjunction​(ConjunctionID conjunctionID), anchor=Pipeline_conjunction_ConjunctionID, args=[Variable(name=conjunctionID, anchor=null, defaultValue=null, description=The ConjunctionID of the conjunction to retrieve, type=ConjunctionID)], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.Optional<? extends Conjunction>)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A representation of a query pipeline.

// tag::methods[]
[#_Pipeline_conjunction_ConjunctionID]
==== conjunction

[source,java]
----
java.util.Optional<? extends Conjunction> conjunction​(ConjunctionID conjunctionID)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `conjunctionID` a| The ConjunctionID of the conjunction to retrieve a| `ConjunctionID`
|===

[caption=""]
.Returns
`java.util.Optional<? extends Conjunction>`

[#_Pipeline_getVariableName_Variable]
==== getVariableName

[source,java]
----
java.util.Optional<java.lang.String> getVariableName​(Variable variable)
----

Gets the name of the specified variable, if it has one.

[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[#_Pipeline_stages_]
==== stages

[source,java]
----
java.util.stream.Stream<? extends PipelineStage> stages()
----



[caption=""]
.Returns
`java.util.stream.Stream<? extends PipelineStage>`

// end::methods[]

