[#_PipelineStage_SortStage_SortVariable]
=== PipelineStage.SortStage.SortVariable

`Class(name=PipelineStage.SortStage.SortVariable, anchor=PipelineStage_SortStage_SortVariable, enumConstants=[], description=[A variable and its sort order], examples=[], fields=[], methods=[Method(name=variable, signature=Variable variable(), anchor=PipelineStage_SortStage_SortVariable_variable_, args=[], description=[The variable to sort by], examples=[], mode=null, returnDescription=null, returnType=Variable), Method(name=order, signature=com.typedb.driver.jni.SortOrder order(), anchor=PipelineStage_SortStage_SortVariable_order_, args=[], description=[The sort order (ascending or descending)], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.SortOrder)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

A variable and its sort order

// tag::methods[]
[#_PipelineStage_SortStage_SortVariable_order_]
==== order

[source,java]
----
com.typedb.driver.jni.SortOrder order()
----

The sort order (ascending or descending)

[caption=""]
.Returns
`com.typedb.driver.jni.SortOrder`

[#_PipelineStage_SortStage_SortVariable_variable_]
==== variable

[source,java]
----
Variable variable()
----

The variable to sort by

[caption=""]
.Returns
`Variable`

// end::methods[]

