[#_PipelineStage]
=== PipelineStage

`Class(name=PipelineStage, anchor=PipelineStage, enumConstants=[], description=[Representation of a stage in a ``Pipeline``.], examples=[], fields=[], methods=[Method(name=getVariant, signature=com.typedb.driver.jni.PipelineStageVariant getVariant(), anchor=PipelineStage_getVariant_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.PipelineStageVariant), Method(name=isMatch, signature=boolean isMatch(), anchor=PipelineStage_isMatch_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isInsert, signature=boolean isInsert(), anchor=PipelineStage_isInsert_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPut, signature=boolean isPut(), anchor=PipelineStage_isPut_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isUpdate, signature=boolean isUpdate(), anchor=PipelineStage_isUpdate_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isDelete, signature=boolean isDelete(), anchor=PipelineStage_isDelete_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSelect, signature=boolean isSelect(), anchor=PipelineStage_isSelect_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSort, signature=boolean isSort(), anchor=PipelineStage_isSort_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRequire, signature=boolean isRequire(), anchor=PipelineStage_isRequire_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOffset, signature=boolean isOffset(), anchor=PipelineStage_isOffset_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLimit, signature=boolean isLimit(), anchor=PipelineStage_isLimit_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isDistinct, signature=boolean isDistinct(), anchor=PipelineStage_isDistinct_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isReduce, signature=boolean isReduce(), anchor=PipelineStage_isReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asMatch, signature=PipelineStage.MatchStage asMatch(), anchor=PipelineStage_asMatch_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.MatchStage), Method(name=asInsert, signature=PipelineStage.InsertStage asInsert(), anchor=PipelineStage_asInsert_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.InsertStage), Method(name=asPut, signature=PipelineStage.PutStage asPut(), anchor=PipelineStage_asPut_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.PutStage), Method(name=asUpdate, signature=PipelineStage.UpdateStage asUpdate(), anchor=PipelineStage_asUpdate_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.UpdateStage), Method(name=asDelete, signature=PipelineStage.DeleteStage asDelete(), anchor=PipelineStage_asDelete_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.DeleteStage), Method(name=asSelect, signature=PipelineStage.SelectStage asSelect(), anchor=PipelineStage_asSelect_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.SelectStage), Method(name=asSort, signature=PipelineStage.SortStage asSort(), anchor=PipelineStage_asSort_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.SortStage), Method(name=asRequire, signature=PipelineStage.RequireStage asRequire(), anchor=PipelineStage_asRequire_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.RequireStage), Method(name=asOffset, signature=PipelineStage.OffsetStage asOffset(), anchor=PipelineStage_asOffset_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.OffsetStage), Method(name=asLimit, signature=PipelineStage.LimitStage asLimit(), anchor=PipelineStage_asLimit_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.LimitStage), Method(name=asDistinct, signature=PipelineStage.DistinctStage asDistinct(), anchor=PipelineStage_asDistinct_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.DistinctStage), Method(name=asReduce, signature=PipelineStage.ReduceStage asReduce(), anchor=PipelineStage_asReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.ReduceStage)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

Representation of a stage in a ``Pipeline``.

// tag::methods[]
[#_PipelineStage_asDelete_]
==== asDelete

[source,java]
----
PipelineStage.DeleteStage asDelete()
----



[caption=""]
.Returns
`PipelineStage.DeleteStage`

[#_PipelineStage_asDistinct_]
==== asDistinct

[source,java]
----
PipelineStage.DistinctStage asDistinct()
----



[caption=""]
.Returns
`PipelineStage.DistinctStage`

[#_PipelineStage_asInsert_]
==== asInsert

[source,java]
----
PipelineStage.InsertStage asInsert()
----



[caption=""]
.Returns
`PipelineStage.InsertStage`

[#_PipelineStage_asLimit_]
==== asLimit

[source,java]
----
PipelineStage.LimitStage asLimit()
----



[caption=""]
.Returns
`PipelineStage.LimitStage`

[#_PipelineStage_asMatch_]
==== asMatch

[source,java]
----
PipelineStage.MatchStage asMatch()
----



[caption=""]
.Returns
`PipelineStage.MatchStage`

[#_PipelineStage_asOffset_]
==== asOffset

[source,java]
----
PipelineStage.OffsetStage asOffset()
----



[caption=""]
.Returns
`PipelineStage.OffsetStage`

[#_PipelineStage_asPut_]
==== asPut

[source,java]
----
PipelineStage.PutStage asPut()
----



[caption=""]
.Returns
`PipelineStage.PutStage`

[#_PipelineStage_asReduce_]
==== asReduce

[source,java]
----
PipelineStage.ReduceStage asReduce()
----



[caption=""]
.Returns
`PipelineStage.ReduceStage`

[#_PipelineStage_asRequire_]
==== asRequire

[source,java]
----
PipelineStage.RequireStage asRequire()
----



[caption=""]
.Returns
`PipelineStage.RequireStage`

[#_PipelineStage_asSelect_]
==== asSelect

[source,java]
----
PipelineStage.SelectStage asSelect()
----



[caption=""]
.Returns
`PipelineStage.SelectStage`

[#_PipelineStage_asSort_]
==== asSort

[source,java]
----
PipelineStage.SortStage asSort()
----



[caption=""]
.Returns
`PipelineStage.SortStage`

[#_PipelineStage_asUpdate_]
==== asUpdate

[source,java]
----
PipelineStage.UpdateStage asUpdate()
----



[caption=""]
.Returns
`PipelineStage.UpdateStage`

[#_PipelineStage_getVariant_]
==== getVariant

[source,java]
----
com.typedb.driver.jni.PipelineStageVariant getVariant()
----



[caption=""]
.Returns
`com.typedb.driver.jni.PipelineStageVariant`

[#_PipelineStage_isDelete_]
==== isDelete

[source,java]
----
boolean isDelete()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isDistinct_]
==== isDistinct

[source,java]
----
boolean isDistinct()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isInsert_]
==== isInsert

[source,java]
----
boolean isInsert()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isLimit_]
==== isLimit

[source,java]
----
boolean isLimit()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isMatch_]
==== isMatch

[source,java]
----
boolean isMatch()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isOffset_]
==== isOffset

[source,java]
----
boolean isOffset()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isPut_]
==== isPut

[source,java]
----
boolean isPut()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isReduce_]
==== isReduce

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isRequire_]
==== isRequire

[source,java]
----
boolean isRequire()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isSelect_]
==== isSelect

[source,java]
----
boolean isSelect()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isSort_]
==== isSort

[source,java]
----
boolean isSort()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_isUpdate_]
==== isUpdate

[source,java]
----
boolean isUpdate()
----



[caption=""]
.Returns
`boolean`

// end::methods[]

