[#_PipelineStage_OffsetStage]
=== PipelineStage.OffsetStage

`Class(name=PipelineStage.OffsetStage, anchor=PipelineStage_OffsetStage, enumConstants=[], description=[Represents an "offset" stage: offset &lt;offset&gt; e.g. ``offset 3``], examples=[], fields=[], methods=[Method(name=offset, signature=long offset(), anchor=PipelineStage_OffsetStage_offset_, args=[], description=[The number of results to skip], examples=[], mode=null, returnDescription=null, returnType=long), Method(name=asDelete, signature=PipelineStage.DeleteStage asDelete(), anchor=PipelineStage_OffsetStage_asDelete_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.DeleteStage), Method(name=asDistinct, signature=PipelineStage.DistinctStage asDistinct(), anchor=PipelineStage_OffsetStage_asDistinct_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.DistinctStage), Method(name=asInsert, signature=PipelineStage.InsertStage asInsert(), anchor=PipelineStage_OffsetStage_asInsert_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.InsertStage), Method(name=asLimit, signature=PipelineStage.LimitStage asLimit(), anchor=PipelineStage_OffsetStage_asLimit_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.LimitStage), Method(name=asMatch, signature=PipelineStage.MatchStage asMatch(), anchor=PipelineStage_OffsetStage_asMatch_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.MatchStage), Method(name=asOffset, signature=PipelineStage.OffsetStage asOffset(), anchor=PipelineStage_OffsetStage_asOffset_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.OffsetStage), Method(name=asPut, signature=PipelineStage.PutStage asPut(), anchor=PipelineStage_OffsetStage_asPut_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.PutStage), Method(name=asReduce, signature=PipelineStage.ReduceStage asReduce(), anchor=PipelineStage_OffsetStage_asReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.ReduceStage), Method(name=asRequire, signature=PipelineStage.RequireStage asRequire(), anchor=PipelineStage_OffsetStage_asRequire_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.RequireStage), Method(name=asSelect, signature=PipelineStage.SelectStage asSelect(), anchor=PipelineStage_OffsetStage_asSelect_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.SelectStage), Method(name=asSort, signature=PipelineStage.SortStage asSort(), anchor=PipelineStage_OffsetStage_asSort_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.SortStage), Method(name=asUpdate, signature=PipelineStage.UpdateStage asUpdate(), anchor=PipelineStage_OffsetStage_asUpdate_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=PipelineStage.UpdateStage), Method(name=getVariant, signature=com.typedb.driver.jni.PipelineStageVariant getVariant(), anchor=PipelineStage_OffsetStage_getVariant_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.PipelineStageVariant), Method(name=isDelete, signature=boolean isDelete(), anchor=PipelineStage_OffsetStage_isDelete_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isDistinct, signature=boolean isDistinct(), anchor=PipelineStage_OffsetStage_isDistinct_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isInsert, signature=boolean isInsert(), anchor=PipelineStage_OffsetStage_isInsert_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isLimit, signature=boolean isLimit(), anchor=PipelineStage_OffsetStage_isLimit_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isMatch, signature=boolean isMatch(), anchor=PipelineStage_OffsetStage_isMatch_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isOffset, signature=boolean isOffset(), anchor=PipelineStage_OffsetStage_isOffset_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isPut, signature=boolean isPut(), anchor=PipelineStage_OffsetStage_isPut_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isReduce, signature=boolean isReduce(), anchor=PipelineStage_OffsetStage_isReduce_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isRequire, signature=boolean isRequire(), anchor=PipelineStage_OffsetStage_isRequire_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSelect, signature=boolean isSelect(), anchor=PipelineStage_OffsetStage_isSelect_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isSort, signature=boolean isSort(), anchor=PipelineStage_OffsetStage_isSort_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isUpdate, signature=boolean isUpdate(), anchor=PipelineStage_OffsetStage_isUpdate_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean)], packagePath=com.typedb.driver.api.analyze, superClasses=[PipelineStage], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

*Superinterfaces:*

* `PipelineStage`

Represents an "offset" stage: offset &lt;offset&gt; e.g. ``offset 3``

// tag::methods[]
[#_PipelineStage_OffsetStage_asDelete_]
==== asDelete

[source,java]
----
PipelineStage.DeleteStage asDelete()
----



[caption=""]
.Returns
`PipelineStage.DeleteStage`

[#_PipelineStage_OffsetStage_asDistinct_]
==== asDistinct

[source,java]
----
PipelineStage.DistinctStage asDistinct()
----



[caption=""]
.Returns
`PipelineStage.DistinctStage`

[#_PipelineStage_OffsetStage_asInsert_]
==== asInsert

[source,java]
----
PipelineStage.InsertStage asInsert()
----



[caption=""]
.Returns
`PipelineStage.InsertStage`

[#_PipelineStage_OffsetStage_asLimit_]
==== asLimit

[source,java]
----
PipelineStage.LimitStage asLimit()
----



[caption=""]
.Returns
`PipelineStage.LimitStage`

[#_PipelineStage_OffsetStage_asMatch_]
==== asMatch

[source,java]
----
PipelineStage.MatchStage asMatch()
----



[caption=""]
.Returns
`PipelineStage.MatchStage`

[#_PipelineStage_OffsetStage_asOffset_]
==== asOffset

[source,java]
----
PipelineStage.OffsetStage asOffset()
----



[caption=""]
.Returns
`PipelineStage.OffsetStage`

[#_PipelineStage_OffsetStage_asPut_]
==== asPut

[source,java]
----
PipelineStage.PutStage asPut()
----



[caption=""]
.Returns
`PipelineStage.PutStage`

[#_PipelineStage_OffsetStage_asReduce_]
==== asReduce

[source,java]
----
PipelineStage.ReduceStage asReduce()
----



[caption=""]
.Returns
`PipelineStage.ReduceStage`

[#_PipelineStage_OffsetStage_asRequire_]
==== asRequire

[source,java]
----
PipelineStage.RequireStage asRequire()
----



[caption=""]
.Returns
`PipelineStage.RequireStage`

[#_PipelineStage_OffsetStage_asSelect_]
==== asSelect

[source,java]
----
PipelineStage.SelectStage asSelect()
----



[caption=""]
.Returns
`PipelineStage.SelectStage`

[#_PipelineStage_OffsetStage_asSort_]
==== asSort

[source,java]
----
PipelineStage.SortStage asSort()
----



[caption=""]
.Returns
`PipelineStage.SortStage`

[#_PipelineStage_OffsetStage_asUpdate_]
==== asUpdate

[source,java]
----
PipelineStage.UpdateStage asUpdate()
----



[caption=""]
.Returns
`PipelineStage.UpdateStage`

[#_PipelineStage_OffsetStage_getVariant_]
==== getVariant

[source,java]
----
com.typedb.driver.jni.PipelineStageVariant getVariant()
----



[caption=""]
.Returns
`com.typedb.driver.jni.PipelineStageVariant`

[#_PipelineStage_OffsetStage_isDelete_]
==== isDelete

[source,java]
----
boolean isDelete()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isDistinct_]
==== isDistinct

[source,java]
----
boolean isDistinct()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isInsert_]
==== isInsert

[source,java]
----
boolean isInsert()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isLimit_]
==== isLimit

[source,java]
----
boolean isLimit()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isMatch_]
==== isMatch

[source,java]
----
boolean isMatch()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isOffset_]
==== isOffset

[source,java]
----
boolean isOffset()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isPut_]
==== isPut

[source,java]
----
boolean isPut()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isReduce_]
==== isReduce

[source,java]
----
boolean isReduce()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isRequire_]
==== isRequire

[source,java]
----
boolean isRequire()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isSelect_]
==== isSelect

[source,java]
----
boolean isSelect()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isSort_]
==== isSort

[source,java]
----
boolean isSort()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_isUpdate_]
==== isUpdate

[source,java]
----
boolean isUpdate()
----



[caption=""]
.Returns
`boolean`

[#_PipelineStage_OffsetStage_offset_]
==== offset

[source,java]
----
long offset()
----

The number of results to skip

[caption=""]
.Returns
`long`

// end::methods[]

