[#_PipelineStage_ReduceStage_ReduceAssignment]
=== PipelineStage.ReduceStage.ReduceAssignment

`Class(name=PipelineStage.ReduceStage.ReduceAssignment, anchor=PipelineStage_ReduceStage_ReduceAssignment, enumConstants=[], description=[An assignment of a reducer to a variable], examples=[], fields=[], methods=[Method(name=assigned, signature=Variable assigned(), anchor=PipelineStage_ReduceStage_ReduceAssignment_assigned_, args=[], description=[The variable being assigned to], examples=[], mode=null, returnDescription=null, returnType=Variable), Method(name=reducer, signature=Reducer reducer(), anchor=PipelineStage_ReduceStage_ReduceAssignment_reducer_, args=[], description=[The reducer being applied], examples=[], mode=null, returnDescription=null, returnType=Reducer)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

An assignment of a reducer to a variable

// tag::methods[]
[#_PipelineStage_ReduceStage_ReduceAssignment_assigned_]
==== assigned

[source,java]
----
Variable assigned()
----

The variable being assigned to

[caption=""]
.Returns
`Variable`

[#_PipelineStage_ReduceStage_ReduceAssignment_reducer_]
==== reducer

[source,java]
----
Reducer reducer()
----

The reducer being applied

[caption=""]
.Returns
`Reducer`

// end::methods[]

