[#_Reducer]
=== Reducer

`Class(name=Reducer, anchor=Reducer, enumConstants=[], description=[Representation of a reducer used either in a ``PipelineStage::Reduce`` or in a function's ``ReturnOperation``.], examples=[], fields=[], methods=[Method(name=name, signature=java.lang.String name(), anchor=Reducer_name_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=arguments, signature=java.util.stream.Stream<? extends Variable> arguments(), anchor=Reducer_arguments_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends Variable>)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

Representation of a reducer used either in a ``PipelineStage::Reduce`` or in a function's ``ReturnOperation``.

// tag::methods[]
[#_Reducer_arguments_]
==== arguments

[source,java]
----
java.util.stream.Stream<? extends Variable> arguments()
----



[caption=""]
.Returns
`java.util.stream.Stream<? extends Variable>`

[#_Reducer_name_]
==== name

[source,java]
----
java.lang.String name()
----



[caption=""]
.Returns
`java.lang.String`

// end::methods[]

