[#_VariableAnnotations]
=== VariableAnnotations

`Class(name=VariableAnnotations, anchor=VariableAnnotations, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=variant, signature=com.typedb.driver.jni.VariableAnnotationsVariant variant(), anchor=VariableAnnotations_variant_, args=[], description=[The variant indicates whether this is an instance variable, type variable, or value variable.], examples=[], mode=null, returnDescription=null, returnType=com.typedb.driver.jni.VariableAnnotationsVariant), Method(name=isInstance, signature=boolean isInstance(), anchor=VariableAnnotations_isInstance_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isType, signature=boolean isType(), anchor=VariableAnnotations_isType_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=boolean isValue(), anchor=VariableAnnotations_isValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=boolean), Method(name=asInstance, signature=java.util.stream.Stream<? extends Type> asInstance(), anchor=VariableAnnotations_asInstance_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends Type>), Method(name=asType, signature=java.util.stream.Stream<? extends Type> asType(), anchor=VariableAnnotations_asType_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<? extends Type>), Method(name=asValue, signature=java.util.stream.Stream<java.lang.String> asValue(), anchor=VariableAnnotations_asValue_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<java.lang.String>)], packagePath=com.typedb.driver.api.analyze, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.analyze`

// tag::methods[]
[#_VariableAnnotations_asInstance_]
==== asInstance

[source,java]
----
java.util.stream.Stream<? extends Type> asInstance()
----



[caption=""]
.Returns
`java.util.stream.Stream<? extends Type>`

[#_VariableAnnotations_asType_]
==== asType

[source,java]
----
java.util.stream.Stream<? extends Type> asType()
----



[caption=""]
.Returns
`java.util.stream.Stream<? extends Type>`

[#_VariableAnnotations_asValue_]
==== asValue

[source,java]
----
java.util.stream.Stream<java.lang.String> asValue()
----



[caption=""]
.Returns
`java.util.stream.Stream<java.lang.String>`

[#_VariableAnnotations_isInstance_]
==== isInstance

[source,java]
----
boolean isInstance()
----



[caption=""]
.Returns
`boolean`

[#_VariableAnnotations_isType_]
==== isType

[source,java]
----
boolean isType()
----



[caption=""]
.Returns
`boolean`

[#_VariableAnnotations_isValue_]
==== isValue

[source,java]
----
boolean isValue()
----



[caption=""]
.Returns
`boolean`

[#_VariableAnnotations_variant_]
==== variant

[source,java]
----
com.typedb.driver.jni.VariableAnnotationsVariant variant()
----

The variant indicates whether this is an instance variable, type variable, or value variable.

[caption=""]
.Returns
`com.typedb.driver.jni.VariableAnnotationsVariant`

// end::methods[]

