[#_ConceptRow]
=== ConceptRow

`class`

*Package*: `typedb.api.answer.concept_row`

Contains a row of concepts with a header.

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `query_type` a| `QueryType` a| Retrieves the executed query’s type of this ``ConceptRow``. Shared between all the rows in a QueryAnswer.


|===
// end::properties[]

// tag::methods[]
[#_ConceptRow_column_names_]
==== column_names

[source,python]
----
column_names() -> Iterator[str]
----

Produces an iterator over all column names (variables) in the header of this ``ConceptRow``. Shared between all the rows in a QueryAnswer.

[caption=""]
.Returns
`Iterator[str]`

[caption=""]
.Code examples
[source,python]
----
concept_row.column_names()
----

[#_ConceptRow_concepts_]
==== concepts

[source,python]
----
concepts() -> Iterator[Concept]
----

Produces an iterator over all concepts in this ConceptRow, skipping empty results.

[caption=""]
.Returns
`Iterator[Concept]`

[caption=""]
.Code examples
[source,python]
----
concept_row.concepts()
----

[#_ConceptRow_get_column_name_str]
==== get

[source,python]
----
get(column_name: str) -> Concept | None
----

Retrieves a concept for a given column name (variable). Returns ``None`` if the variable has an empty answer. Throws an exception if the variable is not present.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `column_name` a| The string representation of a variable (column name from ``column_names``) a| `str` a| 
|===

[caption=""]
.Returns
`Concept | None`

[caption=""]
.Code examples
[source,python]
----
concept_row.get(column_name)
----

[#_ConceptRow_get_index_column_index_int]
==== get_index

[source,python]
----
get_index(column_index: int) -> Concept | None
----

Retrieves a concept for a given index of the header (‘’column_names’’). Returns ``None`` if the index points to an empty answer. Throws an exception if the index is not in the row’s range.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `column_index` a| The column index a| `int` a| 
|===

[caption=""]
.Returns
`Concept | None`

[caption=""]
.Code examples
[source,python]
----
concept_row.get_index(column_index)
----

[#_ConceptRow_involved_conjunctions_]
==== involved_conjunctions

[source,python]
----
involved_conjunctions() -> Iterator['ConjunctionID'] | None
----

Retrieve the ConjunctionIDs of Conjunctions that answered this row.

[caption=""]
.Returns
`Iterator['ConjunctionID'] | None`

[caption=""]
.Code examples
[source,python]
----
concept_row.involved_conjunctions()
----

[#_ConceptRow_query_structure_]
==== query_structure

[source,python]
----
query_structure() -> 'Pipeline' | None
----

Retrieve the executed query’s structure from the ``ConceptRow``’s header, if set. It must be requested via “include query structure” in ``QueryOptions`` Shared between all the rows in a QueryAnswer.

[caption=""]
.Returns
`'Pipeline' | None`

[caption=""]
.Code examples
[source,python]
----
concept_row.query_structure()
----

// end::methods[]

