[#_QueryAnswer]
=== QueryAnswer

`Class(name=QueryAnswer, anchor=QueryAnswer, enumConstants=[], description=[General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.], examples=[], fields=[Variable(name=query_type, anchor=null, defaultValue=null, description=Retrieves the executed query’s type of this ``QueryAnswer``.

, type=QueryType)], methods=[Method(name=as_concept_documents, signature=as_concept_documents() -> ConceptDocumentIterator, anchor=QueryAnswer_as_concept_documents_, args=[], description=[Casts the query answer to ``ConceptDocumentIterator``.], examples=[query_answer.as_concept_documents()], mode=null, returnDescription=, returnType=ConceptDocumentIterator), Method(name=as_concept_rows, signature=as_concept_rows() -> ConceptRowIterator, anchor=QueryAnswer_as_concept_rows_, args=[], description=[Casts the query answer to ``ConceptRowIterator``.], examples=[query_answer.as_concept_rows()], mode=null, returnDescription=, returnType=ConceptRowIterator), Method(name=as_ok, signature=as_ok() -> OkQueryAnswer, anchor=QueryAnswer_as_ok_, args=[], description=[Casts the query answer to ``OkQueryAnswer``.], examples=[query_answer.as_ok()], mode=null, returnDescription=, returnType=OkQueryAnswer), Method(name=is_concept_documents, signature=is_concept_documents() -> bool, anchor=QueryAnswer_is_concept_documents_, args=[], description=[Checks if the query answer is a ``ConceptDocumentIterator``.], examples=[query_answer.is_concept_documents()], mode=null, returnDescription=, returnType=bool), Method(name=is_concept_rows, signature=is_concept_rows() -> bool, anchor=QueryAnswer_is_concept_rows_, args=[], description=[Checks if the query answer is a ``ConceptRowIterator``.], examples=[query_answer.is_concept_rows()], mode=null, returnDescription=, returnType=bool), Method(name=is_ok, signature=is_ok() -> bool, anchor=QueryAnswer_is_ok_, args=[], description=[Checks if the query answer is an ``Ok``.], examples=[query_answer.is_ok()], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.answer.query_answer, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.answer.query_answer`

General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `query_type` a| `QueryType` a| Retrieves the executed query’s type of this ``QueryAnswer``.


|===
// end::properties[]

// tag::methods[]
[#_QueryAnswer_as_concept_documents_]
==== as_concept_documents

[source,python]
----
as_concept_documents() -> ConceptDocumentIterator
----

Casts the query answer to ``ConceptDocumentIterator``.

[caption=""]
.Returns
`ConceptDocumentIterator`

[caption=""]
.Code examples
[source,python]
----
query_answer.as_concept_documents()
----

[#_QueryAnswer_as_concept_rows_]
==== as_concept_rows

[source,python]
----
as_concept_rows() -> ConceptRowIterator
----

Casts the query answer to ``ConceptRowIterator``.

[caption=""]
.Returns
`ConceptRowIterator`

[caption=""]
.Code examples
[source,python]
----
query_answer.as_concept_rows()
----

[#_QueryAnswer_as_ok_]
==== as_ok

[source,python]
----
as_ok() -> OkQueryAnswer
----

Casts the query answer to ``OkQueryAnswer``.

[caption=""]
.Returns
`OkQueryAnswer`

[caption=""]
.Code examples
[source,python]
----
query_answer.as_ok()
----

[#_QueryAnswer_is_concept_documents_]
==== is_concept_documents

[source,python]
----
is_concept_documents() -> bool
----

Checks if the query answer is a ``ConceptDocumentIterator``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
query_answer.is_concept_documents()
----

[#_QueryAnswer_is_concept_rows_]
==== is_concept_rows

[source,python]
----
is_concept_rows() -> bool
----

Checks if the query answer is a ``ConceptRowIterator``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
query_answer.is_concept_rows()
----

[#_QueryAnswer_is_ok_]
==== is_ok

[source,python]
----
is_ok() -> bool
----

Checks if the query answer is an ``Ok``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
query_answer.is_ok()
----

// end::methods[]

