[#_methods_transaction_queryoptions]
=== queryoptions

[#_Struct_QueryOptions]
[.doc-api-reference-driver]
==== Struct QueryOptions

`rust struct (pointer)`



TypeDB query options. ``QueryOptions`` object can be used to override the default server behaviour for executed queries.


[#_query_options_drop]
===== function ``query_options_drop``

[source,c]
----
void query_options_drop(struct QueryOptions* options)
----



Frees the native Rust ``QueryOptions`` object.

[caption=""]
.Returns
`void`

[#_query_options_get_include_instance_types]
===== function ``query_options_get_include_instance_types``

[source,c]
----
bool query_options_get_include_instance_types(const struct QueryOptions* options)
----



Returns the value set for the "include instance types" flag in this ``QueryOptions`` object. If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.

[caption=""]
.Returns
`bool`

[#_query_options_get_include_query_structure]
===== function ``query_options_get_include_query_structure``

[source,c]
----
bool query_options_get_include_query_structure(const struct QueryOptions* options)
----



Returns the value set for 'include query structure' in this ``QueryOptions`` object.

[caption=""]
.Returns
`bool`

[#_query_options_get_prefetch_size]
===== function ``query_options_get_prefetch_size``

[source,c]
----
int64_t query_options_get_prefetch_size(const struct QueryOptions* options)
----



Returns the value set for the prefetch size in this ``QueryOptions`` object. If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1.

[caption=""]
.Returns
`int64_t`

[#_query_options_has_include_instance_types]
===== function ``query_options_has_include_instance_types``

[source,c]
----
bool query_options_has_include_instance_types(const struct QueryOptions* options)
----



Checks whether the "include instance types" flag was explicitly set for this ``QueryOptions`` object.

[caption=""]
.Returns
`bool`

[#_query_options_has_include_query_structure]
===== function ``query_options_has_include_query_structure``

[source,c]
----
bool query_options_has_include_query_structure(const struct QueryOptions* options)
----



Checks whether the prefetch size was explicitly set for this ``QueryOptions`` object.

[caption=""]
.Returns
`bool`

[#_query_options_has_prefetch_size]
===== function ``query_options_has_prefetch_size``

[source,c]
----
bool query_options_has_prefetch_size(const struct QueryOptions* options)
----



Checks whether the prefetch size was explicitly set for this ``QueryOptions`` object.

[caption=""]
.Returns
`bool`

[#_query_options_new]
===== function ``query_options_new``

[source,c]
----
struct QueryOptions* query_options_new(void)
----



Produces a new ``QueryOptions`` object.

[caption=""]
.Returns
`struct QueryOptions*`

[#_query_options_set_include_instance_types]
===== function ``query_options_set_include_instance_types``

[source,c]
----
void query_options_set_include_instance_types(struct QueryOptions* options, bool include_instance_types)
----



Explicitly set the "include instance types" flag. If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.

[caption=""]
.Returns
`void`

[#_query_options_set_include_query_structure]
===== function ``query_options_set_include_query_structure``

[source,c]
----
void query_options_set_include_query_structure(struct QueryOptions* options, bool include_query_structure)
----



Explicitly set the prefetch size. If set, it requests the server to include the query structure in the answer header.

[caption=""]
.Returns
`void`

[#_query_options_set_prefetch_size]
===== function ``query_options_set_prefetch_size``

[source,c]
----
void query_options_set_prefetch_size(struct QueryOptions* options, int64_t prefetch_size)
----



Explicitly set the prefetch size. If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1.

[caption=""]
.Returns
`void`

