[#_methods_transaction_transactionoptions]
=== transactionoptions

[#_Struct_TransactionOptions]
[.doc-api-reference-driver]
==== Struct TransactionOptions

`rust struct (pointer)`



TypeDB transaction options. TransactionOptions object can be used to override the default behaviour for opened transactions.


[#_transaction_options_drop]
==== function ``transaction_options_drop``

[source,c]
----
void transaction_options_drop(struct TransactionOptions* options)
----



Frees the native Rust ``TransactionOptions`` object.

[caption=""]
.Returns
`void`

[#_transaction_options_get_read_consistency_level]
==== function ``transaction_options_get_read_consistency_level``

[source,c]
----
struct ConsistencyLevel* transaction_options_get_read_consistency_level(const struct TransactionOptions* options)
----



Returns the value set for the read consistency level in this ``TransactionOptions`` object. If set, specifies the requested consistency level of the transaction opening operation. Affects only read transactions, as write and schema transactions require primary replicas.

[caption=""]
.Returns
`struct ConsistencyLevel*`

[#_transaction_options_get_schema_lock_acquire_timeout_millis]
==== function ``transaction_options_get_schema_lock_acquire_timeout_millis``

[source,c]
----
int64_t transaction_options_get_schema_lock_acquire_timeout_millis(const struct TransactionOptions* options)
----



Returns the value set for the schema lock acquire timeout in this ``TransactionOptions`` object. If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.

[caption=""]
.Returns
`int64_t`

[#_transaction_options_get_transaction_timeout_millis]
==== function ``transaction_options_get_transaction_timeout_millis``

[source,c]
----
int64_t transaction_options_get_transaction_timeout_millis(const struct TransactionOptions* options)
----



Returns the value set for the transaction timeout in this ``TransactionOptions`` object. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
`int64_t`

[#_transaction_options_has_read_consistency_level]
==== function ``transaction_options_has_read_consistency_level``

[source,c]
----
bool transaction_options_has_read_consistency_level(const struct TransactionOptions* options)
----



Checks whether the option for read consistency level was explicitly set for this ``TransactionOptions`` object.

[caption=""]
.Returns
`bool`

[#_transaction_options_has_schema_lock_acquire_timeout_millis]
==== function ``transaction_options_has_schema_lock_acquire_timeout_millis``

[source,c]
----
bool transaction_options_has_schema_lock_acquire_timeout_millis(const struct TransactionOptions* options)
----



Checks whether the option for schema lock acquire timeout was explicitly set for this ``TransactionOptions`` object.

[caption=""]
.Returns
`bool`

[#_transaction_options_has_transaction_timeout_millis]
==== function ``transaction_options_has_transaction_timeout_millis``

[source,c]
----
bool transaction_options_has_transaction_timeout_millis(const struct TransactionOptions* options)
----



Checks whether the option for transaction timeout was explicitly set for this ``TransactionOptions`` object.

[caption=""]
.Returns
`bool`

[#_transaction_options_new]
==== function ``transaction_options_new``

[source,c]
----
struct TransactionOptions* transaction_options_new(void)
----



Produces a new ``TransactionOptions`` object.

[caption=""]
.Returns
`struct TransactionOptions*`

[#_transaction_options_set_read_consistency_level]
==== function ``transaction_options_set_read_consistency_level``

[source,c]
----
void transaction_options_set_read_consistency_level(struct TransactionOptions* options, const struct ConsistencyLevel* read_consistency_level)
----



Explicitly sets read consistency level. If set, specifies the requested consistency level of the transaction opening operation. Affects only read transactions, as write and schema transactions require primary replicas.

[caption=""]
.Returns
`void`

[#_transaction_options_set_schema_lock_acquire_timeout_millis]
==== function ``transaction_options_set_schema_lock_acquire_timeout_millis``

[source,c]
----
void transaction_options_set_schema_lock_acquire_timeout_millis(struct TransactionOptions* options, int64_t timeout_millis)
----



Explicitly sets schema lock acquire timeout. If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.

[caption=""]
.Returns
`void`

[#_transaction_options_set_transaction_timeout_millis]
==== function ``transaction_options_set_transaction_timeout_millis``

[source,c]
----
void transaction_options_set_transaction_timeout_millis(struct TransactionOptions* options, int64_t timeout_millis)
----



Explicitly sets a transaction timeout. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
`void`

