[#_methods_transaction_transaction]
=== transaction

[#_Struct_Transaction]
==== Struct Transaction

`class`



A transaction with a TypeDB database.

[#_transaction_analyze]
==== transaction_analyze

[source,cpp]
----
struct AnalyzedQueryPromise* transaction_analyze(struct Transaction* transaction, const char* query)
----



Analyzes a TypeQL query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The ``Transaction`` to analyze the query within. a| `struct Transaction*`
a| `query` a| The query string. a| `const char*`
|===

[caption=""]
.Returns
`struct AnalyzedQueryPromise*`

[#_transaction_close]
==== transaction_close

[source,cpp]
----
struct VoidPromise* transaction_close(struct Transaction* txn)
----



Forcibly closes this transaction. To be used in exceptional cases.

[caption=""]
.Returns
`struct VoidPromise*`

[#_transaction_commit]
==== transaction_commit

[source,cpp]
----
struct VoidPromise* transaction_commit(struct Transaction* txn)
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, the transaction is closed after the commit call and the native rust object is freed.

[caption=""]
.Returns
`struct VoidPromise*`

[#_transaction_is_open]
==== transaction_is_open

[source,cpp]
----
bool transaction_is_open(const struct Transaction* txn)
----



Checks whether this transaction is open.

[caption=""]
.Returns
`bool`

[#_transaction_new]
==== transaction_new

[source,cpp]
----
struct Transaction* transaction_new(struct TypeDBDriver* driver, const char* database_name, enum TransactionType type_, const struct TransactionOptions* options)
----



Opens a transaction to perform read or write queries on the database connected to the session.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `databases` a| The ``DatabaseManager`` object on this connection. a| 
a| `database_name` a| The name of the database with which the transaction connects. a| `const char*`
a| `type_` a| The type of transaction to be created (Write / Read / Schema). a| `enum TransactionType`
a| `options` a| ``TransactionOptions`` to configure the opened transaction. a| `const struct TransactionOptions*`
|===

[caption=""]
.Returns
`struct Transaction*`

[#_transaction_on_close]
==== transaction_on_close

[source,cpp]
----
struct VoidPromise* transaction_on_close(const struct Transaction* txn, uintptr_t callback_id, void(*)(uintptr_t, struct Error*) callback)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `txn` a| The transaction on which to register the callback a| `const struct Transaction*`
a| `callback_id` a| The argument to be passed to the callback function when it is executed. a| `uintptr_t`
a| `callback` a| The function to be called a| 
|===

[caption=""]
.Returns
`struct VoidPromise*`

[#_transaction_query]
==== transaction_query

[source,cpp]
----
struct QueryAnswerPromise* transaction_query(struct Transaction* transaction, const char* query, const struct QueryOptions* options)
----



Performs a TypeQL query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The ``Transaction`` to execute the query within. a| `struct Transaction*`
a| `query` a| The query string. a| `const char*`
a| `options` a| ``QueryOptions`` to configure the executed query. a| `const struct QueryOptions*`
|===

[caption=""]
.Returns
`struct QueryAnswerPromise*`

[#_transaction_rollback]
==== transaction_rollback

[source,cpp]
----
struct VoidPromise* transaction_rollback(const struct Transaction* txn)
----



Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
`struct VoidPromise*`

[#_transaction_submit_close]
==== transaction_submit_close

[source,cpp]
----
void transaction_submit_close(struct Transaction* txn)
----



Closes the transaction and frees the native rust object.

[caption=""]
.Returns
`void`

