[#_methods_transaction_transactiontype]
=== transactiontype

[#_Struct_TransactionType]
==== Struct TransactionType

`Class(name=Struct TransactionType, anchor=Struct_TransactionType, enumConstants=[], description=[, This enum is used to specify the type of transaction.
], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



This enum is used to specify the type of transaction.


[#_Enum_TransactionType]
==== Enum TransactionType

`Class(name=Enum TransactionType, anchor=Enum_TransactionType, enumConstants=[EnumConstant(name=Read = 0, type=null, value=null), EnumConstant(name=Write = 1, type=null, value=null), EnumConstant(name=Schema = 2, type=null, value=null)], description=[, This enum is used to specify the type of transaction.
], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



This enum is used to specify the type of transaction.


[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `Read = 0`
a| `Schema = 2`
a| `Write = 1`
|===
// end::enum_constants[]

