[#_enum_Concept]
=== Concept

The fundamental TypeQL object.

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `Attribute(Attribute)`
a| `AttributeType(AttributeType)`
a| `Entity(Entity)`
a| `EntityType(EntityType)`
a| `Relation(Relation)`
a| `RelationType(RelationType)`
a| `RoleType(RoleType)`
a| `Value(Value)`
|===
// end::enum_constants[]

// tag::methods[]
[#_enum_Concept_get_category_]
==== get_category

[source,rust]
----
pub fn get_category(&self) -> ConceptCategory
----

Retrieves the category of this Concept.

[caption=""]
.Returns
[source,rust]
----
ConceptCategory
----

[#_enum_Concept_get_label_]
==== get_label

[source,rust]
----
pub fn get_label(&self) -> &str
----

Retrieves the label of this Concept. If this is an Instance, returns the label of the type of this instance (“unknown” if type fetching is disabled). If this is a Value, returns the label of the value type of the value. If this is a Type, returns the label of the type.

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_enum_Concept_is_attribute_]
==== is_attribute

[source,rust]
----
pub fn is_attribute(&self) -> bool
----

Check if this Concept represents an Attribute instance from the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_attribute_type_]
==== is_attribute_type

[source,rust]
----
pub fn is_attribute_type(&self) -> bool
----

Check if this Concept represents an Attribute Type from the schema of the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_boolean_]
==== is_boolean

[source,rust]
----
pub fn is_boolean(&self) -> bool
----

Check if this Concept holds a boolean as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_date_]
==== is_date

[source,rust]
----
pub fn is_date(&self) -> bool
----

Check if this Concept holds a date as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_datetime_]
==== is_datetime

[source,rust]
----
pub fn is_datetime(&self) -> bool
----

Check if this Concept holds a datetime as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_datetime_tz_]
==== is_datetime_tz

[source,rust]
----
pub fn is_datetime_tz(&self) -> bool
----

Check if this Concept holds a timezoned-datetime as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_decimal_]
==== is_decimal

[source,rust]
----
pub fn is_decimal(&self) -> bool
----

Check if this Concept holds a fixed-decimal as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_double_]
==== is_double

[source,rust]
----
pub fn is_double(&self) -> bool
----

Check if this Concept holds a double as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_duration_]
==== is_duration

[source,rust]
----
pub fn is_duration(&self) -> bool
----

Check if this Concept holds a duration as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_entity_]
==== is_entity

[source,rust]
----
pub fn is_entity(&self) -> bool
----

Check if this Concept represents an Entity instance from the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_entity_type_]
==== is_entity_type

[source,rust]
----
pub fn is_entity_type(&self) -> bool
----

Check if this Concept represents an Entity Type from the schema of the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_instance_]
==== is_instance

[source,rust]
----
pub fn is_instance(&self) -> bool
----

Check if this Concept represents a stored database instance from the database. These are exactly: Entity, Relation, and Attribute

Equivalent to:

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
concept.is_entity() || concept.is_relation() ||  concept.is_attribute()
----

[#_enum_Concept_is_long_]
==== is_long

[source,rust]
----
pub fn is_long(&self) -> bool
----

Check if this Concept holds a long as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_relation_]
==== is_relation

[source,rust]
----
pub fn is_relation(&self) -> bool
----

Check if this Concept represents an Relation instance from the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_relation_type_]
==== is_relation_type

[source,rust]
----
pub fn is_relation_type(&self) -> bool
----

Check if this Concept represents a Relation Type from the schema of the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_role_type_]
==== is_role_type

[source,rust]
----
pub fn is_role_type(&self) -> bool
----

Check if this Concept represents a Role Type from the schema of the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_string_]
==== is_string

[source,rust]
----
pub fn is_string(&self) -> bool
----

Check if this Concept holds a string as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_struct_]
==== is_struct

[source,rust]
----
pub fn is_struct(&self) -> bool
----

Check if this Concept holds a struct as an AttributeType, an Attribute, or a Value

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_is_type_]
==== is_type

[source,rust]
----
pub fn is_type(&self) -> bool
----

Check if this Concept represents a Type from the schema of the database. These are exactly: Entity Types, Relation Types, Role Types, and Attribute Types

Equivalent to:

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
concept.is_entity_type() || concept.is_relation_type() || concept.is_role_type() || concept.is_attribute_type()
----

[#_enum_Concept_is_value_]
==== is_value

[source,rust]
----
pub fn is_value(&self) -> bool
----

Check if this Concept represents a Value returned by the database

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_enum_Concept_try_get_boolean_]
==== try_get_boolean

[source,rust]
----
pub fn try_get_boolean(&self) -> Option<bool>
----

Retrieves the boolean value of this Concept, if it exists. If this is a boolean-valued Attribute Instance, returns the boolean value of this instance. If this a boolean-valued Value, returns the boolean value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<bool>
----

[#_enum_Concept_try_get_date_]
==== try_get_date

[source,rust]
----
pub fn try_get_date(&self) -> Option<NaiveDate>
----

Retrieves the date value of this Concept, if it exists. If this is a date-valued Attribute Instance, returns the date value of this instance. If this a date-valued Value, returns the date value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<NaiveDate>
----

[#_enum_Concept_try_get_datetime_]
==== try_get_datetime

[source,rust]
----
pub fn try_get_datetime(&self) -> Option<NaiveDateTime>
----

Retrieves the datetime value of this Concept, if it exists. If this is a datetime-valued Attribute Instance, returns the datetime value of this instance. If this a datetime-valued Value, returns the datetime value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<NaiveDateTime>
----

[#_enum_Concept_try_get_datetime_tz_]
==== try_get_datetime_tz

[source,rust]
----
pub fn try_get_datetime_tz(&self) -> Option<DateTime<TimeZone>>
----

Retrieves the timezoned-datetime value of this Concept, if it exists. If this is a timezoned-datetime valued Attribute Instance, returns the timezoned-datetime value of this instance. If this a timezoned-datetime valued Value, returns the timezoned-datetime value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<DateTime<TimeZone>>
----

[#_enum_Concept_try_get_decimal_]
==== try_get_decimal

[source,rust]
----
pub fn try_get_decimal(&self) -> Option<Decimal>
----

Retrieves the fixed-decimal value of this Concept, if it exists. If this is a fixed-decimal valued Attribute Instance, returns the fixed-decimal value of this instance. If this a fixed-decimal valued Value, returns the fixed-decimal value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<Decimal>
----

[#_enum_Concept_try_get_double_]
==== try_get_double

[source,rust]
----
pub fn try_get_double(&self) -> Option<f64>
----

Retrieves the double value of this Concept, if it exists. If this is a double-valued Attribute Instance, returns the double value of this instance. If this a double-valued Value, returns the double value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<f64>
----

[#_enum_Concept_try_get_duration_]
==== try_get_duration

[source,rust]
----
pub fn try_get_duration(&self) -> Option<Duration>
----

Retrieves the duration value of this Concept, if it exists. If this is a duration-valued Attribute Instance, returns the duration value of this instance. If this a duration-valued Value, returns the duration value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<Duration>
----

[#_enum_Concept_try_get_iid_]
==== try_get_iid

[source,rust]
----
pub fn try_get_iid(&self) -> Option<&IID>
----

Retrieves the unique id (IID) of this Concept. If this is an Entity or Relation Instance, returns the IID of the instance. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<&IID>
----

[#_enum_Concept_try_get_label_]
==== try_get_label

[source,rust]
----
pub fn try_get_label(&self) -> Option<&str>
----

Retrieves the optional label of the concept. If this is an Instance, returns the label of the type of this instance (None if type fetching is disabled). If this is a Value, returns the label of the value type of the value. If this is a Type, returns the label of the type.

[caption=""]
.Returns
[source,rust]
----
Option<&str>
----

[#_enum_Concept_try_get_long_]
==== try_get_long

[source,rust]
----
pub fn try_get_long(&self) -> Option<i64>
----

Retrieves the long value of this Concept, if it exists. If this is a long-valued Attribute Instance, returns the long value of this instance. If this a long-valued Value, returns the long value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<i64>
----

[#_enum_Concept_try_get_string_]
==== try_get_string

[source,rust]
----
pub fn try_get_string(&self) -> Option<&str>
----

Retrieves the string value of this Concept, if it exists. If this is a string-valued Attribute Instance, returns the string value of this instance. If this a string-valued Value, returns the string value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<&str>
----

[#_enum_Concept_try_get_struct_]
==== try_get_struct

[source,rust]
----
pub fn try_get_struct(&self) -> Option<&Struct>
----

Retrieves the struct value of this Concept, if it exists. If this is a struct-valued Attribute Instance, returns the struct value of this instance. If this a struct-valued Value, returns the struct value. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<&Struct>
----

[#_enum_Concept_try_get_value_]
==== try_get_value

[source,rust]
----
pub fn try_get_value(&self) -> Option<&Value>
----

Retrieves the value of this Concept, if it exists. If this is an Attribute Instance, returns the value of this instance. If this a Value, returns the value. Otherwise, returns empty.

[caption=""]
.Returns
[source,rust]
----
Option<&Value>
----

[#_enum_Concept_try_get_value_label_]
==== try_get_value_label

[source,rust]
----
pub fn try_get_value_label(&self) -> Option<&str>
----

Retrieves the label of the value type of the concept, if it exists. If this is an Attribute Instance, returns the label of the value of this instance. If this is a Value, returns the label of the value. If this is an Attribute Type, returns the label of the value type that the schema permits for the attribute type, if one is defined. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<&str>
----

[#_enum_Concept_try_get_value_type_]
==== try_get_value_type

[source,rust]
----
pub fn try_get_value_type(&self) -> Option<ValueType>
----

Retrieves the value type enum of the concept, if it exists. If this is an Attribute Instance, returns the value type of the value of this instance. If this is a Value, returns the value type of the value. If this is an Attribute Type, returns value type that the schema permits for the attribute type, if one is defined. Otherwise, returns None.

[caption=""]
.Returns
[source,rust]
----
Option<ValueType>
----

// end::methods[]

