[#_struct_AttributeType]
=== AttributeType

*Implements traits:*

* `AttributeTypeAPI`
* `Clone`
* `Debug`
* `PartialEq<AttributeType>`
* `StructuralPartialEq`
* `ThingTypeAPI`

Attribute types represent properties that other types can own.

Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `is_abstract` a| `bool` a| 
a| `is_root` a| `bool` a| 
a| `label` a| `String` a| 
a| `value_type` a| `ValueType` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_AttributeType_delete_]
==== delete

[source,rust]
----
fn delete<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_delete,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_get_]
==== get

[source,rust]
----
fn get<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value: Value
) -> BoxPromise<'tx, Result<Option<Attribute>>>
----

<<#_trait_AttributeTypeAPI_method_get,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<Attribute>>>
----

[#_struct_AttributeType_get_instances_]
==== get_instances

[source,rust]
----
fn get_instances<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<Attribute>>>
----

<<#_trait_AttributeTypeAPI_method_get_instances,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<Attribute>>>
----

[#_struct_AttributeType_get_owners_]
==== get_owners

[source,rust]
----
fn get_owners<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<ThingType>>>
----

<<#_trait_AttributeTypeAPI_method_get_owners,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<ThingType>>>
----

[#_struct_AttributeType_get_owns_]
==== get_owns

[source,rust]
----
fn get_owns<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

<<#_trait_ThingTypeAPI_method_get_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[#_struct_AttributeType_get_owns_overridden_]
==== get_owns_overridden

[source,rust]
----
fn get_owns_overridden<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> BoxPromise<'tx, Result<Option<AttributeType>>>
----

<<#_trait_ThingTypeAPI_method_get_owns_overridden,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<AttributeType>>>
----

[#_struct_AttributeType_get_plays_]
==== get_plays

[source,rust]
----
fn get_plays<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<RoleType>>>
----

<<#_trait_ThingTypeAPI_method_get_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<RoleType>>>
----

[#_struct_AttributeType_get_plays_overridden_]
==== get_plays_overridden

[source,rust]
----
fn get_plays_overridden<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    overridden_role_type: RoleType
) -> BoxPromise<'tx, Result<Option<RoleType>>>
----

<<#_trait_ThingTypeAPI_method_get_plays_overridden,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<RoleType>>>
----

[#_struct_AttributeType_get_regex_]
==== get_regex

[source,rust]
----
fn get_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<String>>>
----

<<#_trait_AttributeTypeAPI_method_get_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<String>>>
----

[#_struct_AttributeType_get_subtypes_]
==== get_subtypes

[source,rust]
----
fn get_subtypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_subtypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[#_struct_AttributeType_get_subtypes_with_value_type_]
==== get_subtypes_with_value_type

[source,rust]
----
fn get_subtypes_with_value_type<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value_type: ValueType,
    transitivity: Transitivity
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_subtypes_with_value_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[#_struct_AttributeType_get_supertype_]
==== get_supertype

[source,rust]
----
fn get_supertype<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<Option<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_supertype,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Option<AttributeType>>>
----

[#_struct_AttributeType_get_supertypes_]
==== get_supertypes

[source,rust]
----
fn get_supertypes<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> Result<BoxStream<'tx, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_supertypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'tx, Result<AttributeType>>>
----

[#_struct_AttributeType_get_syntax_]
==== get_syntax

[source,rust]
----
fn get_syntax<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<String>>
----

<<#_trait_ThingTypeAPI_method_get_syntax,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<String>>
----

[#_struct_AttributeType_is_abstract_]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

<<#_trait_ThingTypeAPI_tymethod_is_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_AttributeType_is_deleted_]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result<bool>>
----

<<#_trait_ThingTypeAPI_tymethod_is_deleted,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[#_struct_AttributeType_is_root_]
==== is_root

[source,rust]
----
fn is_root(&self) -> bool
----

<<#_trait_ThingTypeAPI_tymethod_is_root,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_AttributeType_label_]
==== label

[source,rust]
----
fn label(&self) -> &str
----

<<#_trait_ThingTypeAPI_tymethod_label,Read more>>

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_AttributeType_put_]
==== put

[source,rust]
----
fn put<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    value: Value
) -> BoxPromise<'tx, Result<Attribute>>
----

<<#_trait_AttributeTypeAPI_method_put,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<Attribute>>
----

[#_struct_AttributeType_root_]
==== root

[source,rust]
----
pub fn root() -> Self
----

Returns the root ``AttributeType``

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_AttributeType_set_abstract_]
==== set_abstract

[source,rust]
----
fn set_abstract<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_set_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_set_label_]
==== set_label

[source,rust]
----
fn set_label<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    new_label: String
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_set_label,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_set_owns_]
==== set_owns

[source,rust]
----
fn set_owns<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_set_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_set_plays_]
==== set_plays

[source,rust]
----
fn set_plays<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_set_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_set_regex_]
==== set_regex

[source,rust]
----
fn set_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>,
    regex: String
) -> BoxPromise<'tx, Result>
----

<<#_trait_AttributeTypeAPI_method_set_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_set_supertype_]
==== set_supertype

[source,rust]
----
fn set_supertype<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    supertype: AttributeType
) -> BoxPromise<'tx, Result>
----

<<#_trait_AttributeTypeAPI_method_set_supertype,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_unset_abstract_]
==== unset_abstract

[source,rust]
----
fn unset_abstract<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_unset_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_unset_owns_]
==== unset_owns

[source,rust]
----
fn unset_owns<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    attribute_type: AttributeType
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_unset_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_unset_plays_]
==== unset_plays

[source,rust]
----
fn unset_plays<'tx>(
    &mut self,
    transaction: &'tx Transaction<'_>,
    role_type: RoleType
) -> BoxPromise<'tx, Result>
----

<<#_trait_ThingTypeAPI_method_unset_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_unset_regex_]
==== unset_regex

[source,rust]
----
fn unset_regex<'tx>(
    &self,
    transaction: &'tx Transaction<'_>
) -> BoxPromise<'tx, Result>
----

<<#_trait_AttributeTypeAPI_method_unset_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[#_struct_AttributeType_value_type_]
==== value_type

[source,rust]
----
fn value_type(&self) -> ValueType
----

<<#_trait_AttributeTypeAPI_tymethod_value_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
ValueType
----

// end::methods[]

