[#_struct_EntityType]
=== EntityType

`Class(name=EntityType, anchor=struct_EntityType, enumConstants=[], description=[Entity types represent the classification of independent objects in the data model of the business domain.], examples=[], fields=[Variable(name=label, anchor=struct_EntityType_label, defaultValue=null, description=null, type=String)], methods=[Method(name=label, signature=pub fn label(&self) -> &str, anchor=struct_EntityType_label_, args=[], description=[Retrieves the unique label of the ``EntityType``.], examples=[entity_type.label()], mode=async, returnDescription=null, returnType=&str)], packagePath=null, superClasses=[Clone, Debug, Display, Eq, PartialEq, StructuralPartialEq], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`
* `Display`
* `Eq`
* `PartialEq`
* `StructuralPartialEq`

Entity types represent the classification of independent objects in the data model of the business domain.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `String` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_EntityType_label_]
==== label

[source,rust]
----
pub fn label(&self) -> &str
----

Retrieves the unique label of the ``EntityType``.

[caption=""]
.Returns
[source,rust]
----
&str
----

[caption=""]
.Code examples
[source,rust]
----
entity_type.label()
----

// end::methods[]

