[#_struct_RelationType]
=== RelationType

`Class(name=RelationType, anchor=struct_RelationType, enumConstants=[], description=[Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles., Other types can play roles in relations if it’s mentioned in their definition., A relation type must specify at least one role.], examples=[], fields=[Variable(name=label, anchor=struct_RelationType_label, defaultValue=null, description=null, type=String)], methods=[Method(name=label, signature=pub fn label(&self) -> &str, anchor=struct_RelationType_label_, args=[], description=[Retrieves the unique label of the ``RelationType``.], examples=[relation_type.label()], mode=async, returnDescription=null, returnType=&str)], packagePath=null, superClasses=[Clone, Debug, Display, Eq, PartialEq, StructuralPartialEq], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`
* `Display`
* `Eq`
* `PartialEq`
* `StructuralPartialEq`

Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles.

Other types can play roles in relations if it’s mentioned in their definition.

A relation type must specify at least one role.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `String` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_RelationType_label_]
==== label

[source,rust]
----
pub fn label(&self) -> &str
----

Retrieves the unique label of the ``RelationType``.

[caption=""]
.Returns
[source,rust]
----
&str
----

[caption=""]
.Code examples
[source,rust]
----
relation_type.label()
----

// end::methods[]

