[#_TypeDBSession]
=== TypeDBSession

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `options` a| `TypeDBOptions` a| Gets the options for the session
a| `type` a| `SessionType` a| The current session’s type (SCHEMA or DATA)
|===
// end::properties[]

// tag::methods[]
[#_TypeDBSession_close__]
==== close

[source,python]
----
close() -> None
----

Closes the session. Before opening a new session, the session currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
session.close()
----

[#_TypeDBSession_database_name__]
==== database_name

[source,python]
----
database_name() -> str
----

Returns the name of the database of the session.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
session.database_name()
----

[#_TypeDBSession_is_open__]
==== is_open

[source,python]
----
is_open() -> bool
----

Checks whether this session is open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
session.is_open()
----

[#_TypeDBSession_on_close__function_callable]
==== on_close

[source,python]
----
on_close(function: callable) -> None
----

Registers a callback function which will be executed when this session is closed.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `function` a| The callback function. a| `callable` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
session.on_close(function)
----

[#_TypeDBSession_on_reopen__function_callable]
==== on_reopen

[source,python]
----
on_reopen(function: callable) -> None
----

Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `function` a| The callback function. a| `callable` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
session.on_close(function)
----

[#_TypeDBSession_transaction__transaction_type_TransactionType__options_TypeDBOptions]
==== transaction

[source,python]
----
transaction(transaction_type: TransactionType, options: TypeDBOptions = None) -> TypeDBTransaction
----

Opens a transaction to perform read or write queries on the database connected to the session.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction_type` a| The type of transaction to be created (READ or WRITE) a| `TransactionType` a| 
a| `options` a| Options for the session a| `TypeDBOptions` a| `None`
|===

[caption=""]
.Returns
`TypeDBTransaction`

[caption=""]
.Code examples
[source,python]
----
session.transaction(transaction_type, options)
----

// end::methods[]

