[#_QueryOptions]
=== QueryOptions

[source,java]
----
class
----

*Package*: `com.typedb.driver.api`

TypeDB transaction options. ``QueryOptions`` object can be used to override the default server behaviour for executed queries.

// tag::methods[]
[#_QueryOptions_QueryOptions_]
==== QueryOptions

[source,java]
----
public QueryOptions()
----

Produces a new ``QueryOptions`` object. 


[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
QueryOptions options = QueryOptions();
----

[#_QueryOptions_includeInstanceTypes_]
==== includeInstanceTypes

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> includeInstanceTypes()
----

Returns the value set for the "include instance types" flag in this ``QueryOptions`` object. If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.includeInstanceTypes();
----

[#_QueryOptions_includeInstanceTypes_boolean]
==== includeInstanceTypes

[source,java]
----
public QueryOptions includeInstanceTypes​(boolean includeInstanceTypes)
----

Explicitly set the "include instance types" flag. If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `includeInstanceTypes` a| Whether to include instance types in ConceptRow answers. a| `boolean`
|===

[caption=""]
.Returns
`public QueryOptions`

[caption=""]
.Code examples
[source,java]
----
options.includeInstanceTypes(includeInstanceTypes);
----

[#_QueryOptions_includeQueryStructure_]
==== includeQueryStructure

[source,java]
----
public java.util.Optional<java.lang.Boolean> includeQueryStructure()
----

Returns the value set for the "include query structure" flag in this ``QueryOptions`` object. If set, requests the server to return the structure of the query in the ConceptRow header. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `includeQueryStructure` a| Whether to include query structure in ConceptRow header. a| 
|===

[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.includeQueryStructure();
----

[#_QueryOptions_includeQueryStructure_boolean]
==== includeQueryStructure

[source,java]
----
public QueryOptions includeQueryStructure​(boolean includeQueryStructure)
----

Explicitly set the "include query structure" flag. If set, requests the server to return the structure of the query in the ConceptRow header. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `includeQueryStructure` a| Whether to include query structure in ConceptRow header. a| `boolean`
|===

[caption=""]
.Returns
`public QueryOptions`

[caption=""]
.Code examples
[source,java]
----
options.includeQueryStructure(true);
----

[#_QueryOptions_prefetchSize_]
==== prefetchSize

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> prefetchSize()
----

Returns the value set for the prefetch size in this ``QueryOptions`` object. If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.prefetchSize();
----

[#_QueryOptions_prefetchSize_int]
==== prefetchSize

[source,java]
----
public QueryOptions prefetchSize​(int prefetchSize)
----

Explicitly set the prefetch size. If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `prefetchSize` a| Whether to include instance types in ConceptRow answers. a| `int`
|===

[caption=""]
.Returns
`public QueryOptions`

[caption=""]
.Code examples
[source,java]
----
options.prefetchSize(prefetchSize);
----

// end::methods[]

