[#_TransactionOptions]
=== TransactionOptions

*Package*: `com.typedb.driver.api`

TypeDB transaction options. ``TransactionOptions`` object can be used to override the default server behaviour for opened transactions.

// tag::methods[]
[#_TransactionOptions_TransactionOptions_]
==== TransactionOptions

[source,java]
----
public TransactionOptions()
----

Produces a new ``TransactionOptions`` object. 


[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
TransactionOptions options = TransactionOptions();
----

[#_TransactionOptions_readConsistencyLevel_]
==== readConsistencyLevel

[source,java]
----
public java.util.Optional<ConsistencyLevel> readConsistencyLevel()
----

Returns the value set for the read consistency level in this ``TransactionOptions`` object. If set, specifies the requested consistency level of the transaction opening operation. Affects only read transactions, as write and schema transactions require primary replicas. 


[caption=""]
.Returns
`public java.util.Optional<ConsistencyLevel>`

[caption=""]
.Code examples
[source,java]
----
options.readConsistencyLevel();
----

[#_TransactionOptions_readConsistencyLevel_ConsistencyLevel]
==== readConsistencyLevel

[source,java]
----
public TransactionOptions readConsistencyLevel​(ConsistencyLevel readConsistencyLevel)
----

Explicitly sets read consistency level. If set, specifies the requested consistency level of the transaction opening operation. Affects only read transactions, as write and schema transactions require primary replicas. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `readConsistencyLevel` a| The requested consistency level a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`public TransactionOptions`

[caption=""]
.Code examples
[source,java]
----
options.schemaLockAcquireTimeoutMillis(schemaLockAcquireTimeoutMillis);
----

[#_TransactionOptions_schemaLockAcquireTimeoutMillis_]
==== schemaLockAcquireTimeoutMillis

[source,java]
----
public java.util.Optional<java.lang.Integer> schemaLockAcquireTimeoutMillis()
----

Returns the value set for the schema lock acquire timeout in this ``TransactionOptions`` object. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.schemaLockAcquireTimeoutMillis();
----

[#_TransactionOptions_schemaLockAcquireTimeoutMillis_int]
==== schemaLockAcquireTimeoutMillis

[source,java]
----
public TransactionOptions schemaLockAcquireTimeoutMillis​(int schemaLockAcquireTimeoutMillis)
----

Explicitly sets schema lock acquire timeout. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaLockAcquireTimeoutMillis` a| How long the driver should wait if opening a transaction is blocked by a schema write lock a| `int`
|===

[caption=""]
.Returns
`public TransactionOptions`

[caption=""]
.Code examples
[source,java]
----
options.schemaLockAcquireTimeoutMillis(schemaLockAcquireTimeoutMillis);
----

[#_TransactionOptions_transactionTimeoutMillis_]
==== transactionTimeoutMillis

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> transactionTimeoutMillis()
----

Returns the value set for the transaction timeout in this ``TransactionOptions`` object. If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.transactionTimeoutMillis();
----

[#_TransactionOptions_transactionTimeoutMillis_int]
==== transactionTimeoutMillis

[source,java]
----
public TransactionOptions transactionTimeoutMillis​(int transactionTimeoutMillis)
----

Explicitly sets a transaction timeout. If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionTimeoutMillis` a| Timeout for killing transactions automatically a| `int`
|===

[caption=""]
.Returns
`public TransactionOptions`

[caption=""]
.Code examples
[source,java]
----
options.transactionTimeoutMillis(transactionTimeoutMillis);
----

// end::methods[]

