[#_Transaction]
=== Transaction

`class`

*Package*: `com.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

// tag::methods[]
[#_Transaction_analyze_java_lang_String]
==== - analyze

[source,java]
----
@CheckReturnValue
Promise<? extends AnalyzedQuery> analyze​(java.lang.String query)
                                  throws TypeDBDriverException
----

Analayze a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to analyze. a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends AnalyzedQuery>`

[caption=""]
.Code examples
[source,java]
----
transaction.analyze("match $x isa person;");
----

[#_Transaction_close_]
==== - close

[source,java]
----
void close()
    throws TypeDBDriverException
----

Closes the transaction. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.close()
----

[#_Transaction_commit_]
==== - commit

[source,java]
----
void commit()
     throws TypeDBDriverException
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.commit()
----

[#_Transaction_getType_]
==== - getType

[source,java]
----
@CheckReturnValue
Transaction.Type getType()
----

The transaction’s type (READ, WRITE, or SCHEMA) 


[caption=""]
.Returns
`Transaction.Type`

[caption=""]
.Code examples
[source,java]
----
transaction.getType();
----

[#_Transaction_isOpen_]
==== - isOpen

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this transaction is open. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
transaction.isOpen();
----

[#_Transaction_onClose_java_util_function_Consumer_java_lang_Throwable_]
==== - onClose

[source,java]
----
void onClose​(java.util.function.Consumer<java.lang.Throwable> function)
----

Registers a callback function which will be executed when this transaction is closed. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `java.util.function.Consumer<java.lang.Throwable>`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.onClose(function);
----

[#_Transaction_options_]
==== - options

[source,java]
----
@CheckReturnValue
TransactionOptions options()
----

The options for the transaction

[caption=""]
.Returns
`TransactionOptions`

[#_Transaction_query_java_lang_String]
==== - query

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[caption=""]
.Code examples
[source,java]
----
transaction.query("define entity person;");
----

[#_Transaction_query_java_lang_String_QueryOptions]
==== - query

[source,java]
----
@CheckReturnValue
Promise<? extends QueryAnswer> query​(java.lang.String query,
                                     QueryOptions options)
                              throws TypeDBDriverException
----

Execute a TypeQL query in this transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The query to execute. a| `java.lang.String`
a| `options` a| The ``QueryOptions`` to execute the query with. a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<? extends QueryAnswer>`

[caption=""]
.Code examples
[source,java]
----
transaction.query("define entity person;");
----

[#_Transaction_rollback_]
==== - rollback

[source,java]
----
void rollback()
       throws TypeDBDriverException
----

Rolls back the uncommitted changes made via this transaction. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.rollback()
----

// end::methods[]

