[#_Transaction_Type]
=== Transaction.Type

`Class(name=Transaction.Type, anchor=Transaction_Type, enumConstants=[EnumConstant(name=READ, type=null, value=null), EnumConstant(name=SCHEMA, type=null, value=null), EnumConstant(name=WRITE, type=null, value=null)], description=[Used to specify the type of transaction. 
], examples=[driver.transaction(dbName, TransactionType.READ);], fields=[Variable(name=nativeObject, anchor=null, defaultValue=null, description=, type=com.typedb.driver.jni.TransactionType)], methods=[Method(name=values, signature=public static Transaction.Type[] values(), anchor=Transaction_Type_values_, args=[], description=[Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (Transaction.Type c : Transaction.Type.values())
    System.out.println(c);

----
], examples=[for (Transaction.Type c : Transaction.Type.values())
    System.out.println(c);], mode=null, returnDescription=null, returnType=public static Transaction.Type[]), Method(name=valueOf, signature=public static Transaction.Type valueOf​(java.lang.String name), anchor=Transaction_Type_valueOf_java_lang_String, args=[Variable(name=name, anchor=null, defaultValue=null, description=the name of the enum constant to be returned., type=java.lang.String)], description=[Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)], examples=[], mode=null, returnDescription=null, returnType=public static Transaction.Type), Method(name=id, signature=public int id(), anchor=Transaction_Type_id_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public int), Method(name=isRead, signature=public boolean isRead(), anchor=Transaction_Type_isRead_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isWrite, signature=public boolean isWrite(), anchor=Transaction_Type_isWrite_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isSchema, signature=public boolean isSchema(), anchor=Transaction_Type_isSchema_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean)], packagePath=com.typedb.driver.api, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api`

Used to specify the type of transaction. 


[caption=""]
.Examples
[source,java]
----
driver.transaction(dbName, TransactionType.READ);
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `READ`
a| `SCHEMA`
a| `WRITE`
|===
// end::enum_constants[]

// tag::methods[]
[#_Transaction_Type_id_]
==== id

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_Transaction_Type_isRead_]
==== isRead

[source,java]
----
public boolean isRead()
----



[caption=""]
.Returns
`public boolean`

[#_Transaction_Type_isSchema_]
==== isSchema

[source,java]
----
public boolean isSchema()
----



[caption=""]
.Returns
`public boolean`

[#_Transaction_Type_isWrite_]
==== isWrite

[source,java]
----
public boolean isWrite()
----



[caption=""]
.Returns
`public boolean`

[#_Transaction_Type_valueOf_java_lang_String]
==== valueOf

[source,java]
----
public static Transaction.Type valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static Transaction.Type`

[#_Transaction_Type_values_]
==== values

[source,java]
----
public static Transaction.Type[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (Transaction.Type c : Transaction.Type.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static Transaction.Type[]`

[caption=""]
.Code examples
[source,java]
----
for (Transaction.Type c : Transaction.Type.values())
    System.out.println(c);
----

// end::methods[]

