[#_QueryOptions]
=== QueryOptions

[caption=""]
.class
*Package*: `typedb.api.connection.query_options`

TypeDB transaction options. ``QueryOptions`` object can be used to override the default server behaviour for executed queries.

Options could be specified either as constructor arguments or using properties assignment.

[caption=""]
.Examples
[source,python]
----
query_options = QueryOptions(include_instance_types=True)
query_options.prefetch_size = 10
----

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `include_instance_types` a| `bool \| None` a| If set, specifies if types should be included in instance structs returned in ConceptRow answers. This option allows reducing the amount of unnecessary data transmitted.
a| `include_query_structure` a| `bool \| None` a| If set, specifies if types should be included in instance structs returned in ConceptRow answers.
a| `prefetch_size` a| `int \| None` a| If set, specifies the number of extra query responses sent before the client side has to re-request more responses. Increasing this may increase performance for queries with a huge number of answers, as it can reduce the number of network round-trips at the cost of more resources on the server side. Minimal value: 1.
|===
// end::properties[]

