[#_Transaction]
=== Transaction

`Class(name=Transaction, anchor=Transaction, enumConstants=[], description=[], examples=[], fields=[Variable(name=options, anchor=null, defaultValue=null, description=The options for the transaction, type=TransactionOptions), Variable(name=type, anchor=null, defaultValue=null, description=The transaction’s type (READ, WRITE, or SCHEMA), type=TransactionType)], methods=[Method(name=close, signature=close() -> None, anchor=Transaction_close_, args=[], description=[Closes the transaction.], examples=[transaction.close()], mode=null, returnDescription=, returnType=None), Method(name=commit, signature=commit() -> None, anchor=Transaction_commit_, args=[], description=[Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.], examples=[transaction.commit()], mode=null, returnDescription=, returnType=None), Method(name=is_open, signature=is_open() -> bool, anchor=Transaction_is_open_, args=[], description=[Checks whether this transaction is open.], examples=[transaction.is_open()], mode=null, returnDescription=, returnType=bool), Method(name=on_close, signature=on_close(function: Callable) -> None, anchor=Transaction_on_close_function_Callable, args=[Variable(name=function, anchor=null, defaultValue=null, description=The callback function., type=Callable)], description=[Registers a callback function which will be executed when this transaction is closed.], examples=[transaction.on_close(function)], mode=null, returnDescription=, returnType=None), Method(name=query, signature=query(query: str, options: QueryOptions | None = None) -> Promise[QueryAnswer], anchor=Transaction_query_query_str_options_QueryOptions_None, args=[Variable(name=query, anchor=null, defaultValue=null, description=The query to execute., type=str), Variable(name=options, anchor=null, defaultValue=None, description=The ``QueryOptions`` to execute the query with.., type=QueryOptions | None)], description=[Execute a TypeQL query in this transaction.], examples=[transaction.query("define entity person;", options).resolve()], mode=null, returnDescription=, returnType=Promise[QueryAnswer]), Method(name=rollback, signature=rollback() -> None, anchor=Transaction_rollback_, args=[], description=[Rolls back the uncommitted changes made via this transaction.], examples=[transaction.rollback()], mode=null, returnDescription=, returnType=None)], packagePath=typedb.api.connection.transaction, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.connection.transaction`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `options` a| `TransactionOptions` a| The options for the transaction
a| `type` a| `TransactionType` a| The transaction’s type (READ, WRITE, or SCHEMA)
|===
// end::properties[]

// tag::methods[]
[#_Transaction_close_]
==== close

[source,python]
----
close() -> None
----

Closes the transaction.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.close()
----

[#_Transaction_commit_]
==== commit

[source,python]
----
commit() -> None
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.commit()
----

[#_Transaction_is_open_]
==== is_open

[source,python]
----
is_open() -> bool
----

Checks whether this transaction is open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
transaction.is_open()
----

[#_Transaction_on_close_function_Callable]
==== on_close

[source,python]
----
on_close(function: Callable) -> None
----

Registers a callback function which will be executed when this transaction is closed.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `function` a| The callback function. a| `Callable` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.on_close(function)
----

[#_Transaction_query_query_str_options_QueryOptions_None]
==== query

[source,python]
----
query(query: str, options: QueryOptions | None = None) -> Promise[QueryAnswer]
----

Execute a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The query to execute. a| `str` a| 
a| `options` a| The ``QueryOptions`` to execute the query with.. a| `QueryOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[QueryAnswer]`

[caption=""]
.Code examples
[source,python]
----
transaction.query("define entity person;", options).resolve()
----

[#_Transaction_rollback_]
==== rollback

[source,python]
----
rollback() -> None
----

Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.rollback()
----

// end::methods[]

