[#_Transaction]
=== Transaction

`class`

*Package*: `typedb.api.connection.transaction`

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `options` a| `TransactionOptions` a| The options for the transaction
a| `type` a| `TransactionType` a| The transaction’s type (READ, WRITE, or SCHEMA)
|===
// end::properties[]

// tag::methods[]
[#_Transaction_close_]
==== - close

[source,python]
----
close() -> None
----

Closes the transaction.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.close()
----

[#_Transaction_commit_]
==== - commit

[source,python]
----
commit() -> None
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.commit()
----

[#_Transaction_is_open_]
==== - is_open

[source,python]
----
is_open() -> bool
----

Checks whether this transaction is open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
transaction.is_open()
----

[#_Transaction_on_close_function_Callable]
==== - on_close

[source,python]
----
on_close(function: Callable) -> None
----

Registers a callback function which will be executed when this transaction is closed.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `function` a| The callback function. a| `Callable` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.on_close(function)
----

[#_Transaction_query_query_str_options_QueryOptions_None]
==== - query

[source,python]
----
query(query: str, options: QueryOptions | None = None) -> Promise[QueryAnswer]
----

Execute a TypeQL query in this transaction.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `query` a| The query to execute. a| `str` a| 
a| `options` a| The ``QueryOptions`` to execute the query with.. a| `QueryOptions \| None` a| `None`
|===

[caption=""]
.Returns
`Promise[QueryAnswer]`

[caption=""]
.Code examples
[source,python]
----
transaction.query("define entity person;", options).resolve()
----

[#_Transaction_rollback_]
==== - rollback

[source,python]
----
rollback() -> None
----

Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
transaction.rollback()
----

// end::methods[]

