[#_TransactionType]
=== TransactionType

`Class(name=TransactionType, anchor=TransactionType, enumConstants=[EnumConstant(name=READ, type=null, value=0), EnumConstant(name=SCHEMA, type=null, value=2), EnumConstant(name=WRITE, type=null, value=1)], description=[This class is used to specify the type of transaction.], examples=[driver.transaction(database, TransactionType.READ)], fields=[], methods=[Method(name=is_read, signature=is_read() -> bool, anchor=TransactionType_is_read_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_schema, signature=is_schema() -> bool, anchor=TransactionType_is_schema_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool), Method(name=is_write, signature=is_write() -> bool, anchor=TransactionType_is_write_, args=[], description=[], examples=[], mode=null, returnDescription=, returnType=bool)], packagePath=typedb.api.connection.transaction, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `typedb.api.connection.transaction`

This class is used to specify the type of transaction.

[caption=""]
.Examples
[source,python]
----
driver.transaction(database, TransactionType.READ)
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=","]
[options="header"]
|===
|Name |Value
a| `READ` a| `0`
a| `SCHEMA` a| `2`
a| `WRITE` a| `1`
|===
// end::enum_constants[]

// tag::methods[]
[#_TransactionType_is_read_]
==== is_read

[source,python]
----
is_read() -> bool
----



[caption=""]
.Returns
`bool`

[#_TransactionType_is_schema_]
==== is_schema

[source,python]
----
is_schema() -> bool
----



[caption=""]
.Returns
`bool`

[#_TransactionType_is_write_]
==== is_write

[source,python]
----
is_write() -> bool
----



[caption=""]
.Returns
`bool`

// end::methods[]

