[#_ConceptManager]
=== ConceptManager

Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptManager_getAttribute__iid_string]
==== getAttribute

[source,nodejs]
----
getAttribute(iid): Promise<Attribute>
----

Retrieves an ``Attribute`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getAttribute(iid)
----

[#_ConceptManager_getAttributeType__label_string]
==== getAttributeType

[source,nodejs]
----
getAttributeType(label): Promise<AttributeType>
----

Retrieves an ``AttributeType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getAttributeType(label)
----

[#_ConceptManager_getEntity__iid_string]
==== getEntity

[source,nodejs]
----
getEntity(iid): Promise<Entity>
----

Retrieves an ``Entity`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<Entity>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getEntity(iid)
----

[#_ConceptManager_getEntityType__label_string]
==== getEntityType

[source,nodejs]
----
getEntityType(label): Promise<EntityType>
----

Retrieves an ``EntityType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getEntityType(label)
----

[#_ConceptManager_getRelation__iid_string]
==== getRelation

[source,nodejs]
----
getRelation(iid): Promise<Relation>
----

Retrieves a ``Relation`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRelation(iid)
----

[#_ConceptManager_getRelationType__label_string]
==== getRelationType

[source,nodejs]
----
getRelationType(label): Promise<RelationType>
----

Retrieves a ``RelationType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRelationType(label)
----

[#_ConceptManager_getRootAttributeType__]
==== getRootAttributeType

[source,nodejs]
----
getRootAttributeType(): Promise<AttributeType>
----

Retrieve the root ``AttributeType``, “attribute”.

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRootAttributeType()
----

[#_ConceptManager_getRootEntityType__]
==== getRootEntityType

[source,nodejs]
----
getRootEntityType(): Promise<EntityType>
----

Retrieves the root ``EntityType``, “entity”.

[caption=""]
.Returns
`Promise<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRootEntityType()
----

[#_ConceptManager_getRootRelationType__]
==== getRootRelationType

[source,nodejs]
----
getRootRelationType(): Promise<RelationType>
----

Retrieve the root ``RelationType``, “relation”.

[caption=""]
.Returns
`Promise<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRootRelationType()
----

[#_ConceptManager_getRootThingType__]
==== getRootThingType

[source,nodejs]
----
getRootThingType(): Promise<ThingType>
----

Retrieves the root ``ThingType``, “thing”.

[caption=""]
.Returns
`Promise<ThingType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getRootThingType()
----

[#_ConceptManager_getSchemaExceptions__]
==== getSchemaExceptions

[source,nodejs]
----
getSchemaExceptions(): Promise<TypeDBDriverError[]>
----

Retrieves a list of all schema exceptions for the current transaction.

[caption=""]
.Returns
`Promise<TypeDBDriverError[]>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().getSchemaException()
----

[#_ConceptManager_putAttributeType__label_string__valueType_ValueType]
==== putAttributeType

[source,nodejs]
----
putAttributeType(label, valueType): Promise<AttributeType>
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one. or retrieve. :return:

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `string`
a| `valueType` a| The value type of the ``AttributeType`` to create a| `ValueType`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
await transaction.concepts().putAttributeType(label, valueType)
----

[#_ConceptManager_putEntityType__label_string]
==== putEntityType

[source,nodejs]
----
putEntityType(label): Promise<EntityType>
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().putEntityType(label)
----

[#_ConceptManager_putRelationType__label_string]
==== putRelationType

[source,nodejs]
----
putRelationType(label): Promise<RelationType>
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `string`
|===

[caption=""]
.Returns
`Promise<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.concepts().putRelationType(label)
----

// end::methods[]

