[#_TypeDBDriver]
=== TypeDBDriver

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The DatabaseManager for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The UserManager instance for this connection, providing access to user management methods. Only for TypeDB Cloud.
|===
// end::properties[]

// tag::methods[]
[#_TypeDBDriver_close__]
==== close

[source,nodejs]
----
close(): Promise<void>
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
driver.close()
----

[#_TypeDBDriver_isOpen__]
==== isOpen

[source,nodejs]
----
isOpen(): boolean
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
driver.isOpen()
----

[#_TypeDBDriver_session__database_string__type_SessionType__options_TypeDBOptions]
==== session

[source,nodejs]
----
session(database, type, options?): Promise<TypeDBSession>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a|  a| `string`
a| `type` a|  a| `SessionType`
a| `options` a|  a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<TypeDBSession>`

[#_TypeDBDriver_user__]
==== user

[source,nodejs]
----
user(): Promise<User>
----

Returns the logged-in user for the connection. Only for TypeDB Cloud.

[caption=""]
.Returns
`Promise<User>`

[caption=""]
.Code examples
[source,nodejs]
----
driver.user()
----

// end::methods[]

