[#_methods__session__session]
=== session

[#_Struct_Session]
==== Struct Session



A session with a TypeDB database.

[#_Struct_SessionType]
==== Struct SessionType



This enum is used to specify the type of the session.


[#_Enum_SessionType]
==== Enum SessionType



This enum is used to specify the type of the session.


[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `Data = 0`
a| `Schema = 1`
|===
// end::enum_constants[]

[#_session_close]
==== session_close

[source,cpp]
----
void session_close(struct Session* session)
----



Closes the session. Before opening a new session, the session currently open should first be closed. The native rust object is freed on close.

[caption=""]
.Returns
`void`

[#_session_force_close]
==== session_force_close

[source,cpp]
----
void session_force_close(struct Session* session)
----



Forcibly closes the session. To be used in exceptional cases.

[caption=""]
.Returns
`void`

[#_session_get_database_name]
==== session_get_database_name

[source,cpp]
----
char* session_get_database_name(const struct Session* session)
----



Returns the name of the database of the session.

[caption=""]
.Returns
`char*`

[#_session_is_open]
==== session_is_open

[source,cpp]
----
bool session_is_open(const struct Session* session)
----



Checks whether this session is open.

[caption=""]
.Returns
`bool`

[#_session_new]
==== session_new

[source,cpp]
----
struct Session* session_new(struct DatabaseManager* databases, const char* database_name, enum SessionType session_type, const struct Options* options)
----



Opens a session to the given database.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `databases` a| The ``DatabaseManager`` object on this connection. a| `struct DatabaseManager*`
a| `database_name` a| The name of the database with which the session connects a| `const char*`
a| `session_type` a| The type of session to be created (Schema or Data) a| `enum SessionType`
a| `options` a| ``Options`` for this session a| `const struct Options*`
|===

[caption=""]
.Returns
`struct Session*`

[#_session_on_close]
==== session_on_close

[source,cpp]
----
void session_on_close(const struct Session* session, void* data, void(*)(void*) callback, void(*)(void*) finished)
----



Registers a callback function which will be executed when this session is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `session` a| The session on which to register the callback a| `const struct Session*`
a| `data` a| The argument to be passed to the callback function when it is executed a| `void*`
a| `callback` a| The function to be called a| 
a| `finished` a| A function which will be executed when the session is destroyed, allowing cleanup a| 
|===

[caption=""]
.Returns
`void`

[#_session_on_reopen]
==== session_on_reopen

[source,cpp]
----
void session_on_reopen(const struct Session* session, void* data, void(*)(void*) callback, void(*)(void*) finished)
----



Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `session` a| The session on which to register the callback a| `const struct Session*`
a| `data` a| The argument to be passed to the callback function when it is executed a| `void*`
a| `callback` a| The function to be called a| 
a| `finished` a| A function which will be executed when the session is destroyed, allowing cleanup a| 
|===

[caption=""]
.Returns
`void`

