[#_◆_session_close_]
==== session_close

[source,cpp]
----
void session_close(struct Session* session)
----



Closes the session. Before opening a new session, the session currently open should first be closed.

[caption=""]
.Returns
`void`

[#_◆_session_force_close_]
==== session_force_close

[source,cpp]
----
void session_force_close(struct Session* session)
----



Forcibly closes the session. To be used in exceptional cases.

[caption=""]
.Returns
`void`

[#_◆_session_get_database_name_]
==== session_get_database_name

[source,cpp]
----
char* session_get_database_name(const struct Session* session)
----



Returns the name of the database of the session.

[caption=""]
.Returns
`char*`

[#_◆_session_is_open_]
==== session_is_open

[source,cpp]
----
bool session_is_open(const struct Session* session)
----



Checks whether this session is open.

[caption=""]
.Returns
`bool`

[#_◆_session_new_]
==== session_new

[source,cpp]
----
struct Session* session_new(struct DatabaseManager* databases, const char* database_name, enum SessionType session_type, const struct Options* options)
----



Opens a session to the given database.

 
  Parameters
 
 
  
   
    
     databases
     The ``DatabaseManager`` object on this connection.
    
    
     database_name
     The name of the database with which the session connects
    
    
     session_type
     The type of session to be created (Schema or Data)
    
    
     options
     ``Options`` for this session
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `databases` a| The ``DatabaseManager`` object on this connection. a| 
a| `database_name` a| The name of the database with which the session connects a| 
a| `session_type` a| The type of session to be created (Schema or Data) a| 
a| `options` a| ``Options`` for this session a| 
|===

[caption=""]
.Returns
`struct Session*`

[#_◆_session_on_close_]
==== session_on_close

[source,cpp]
----
void session_on_close(const struct Session* session, void* data, void(*)(void*) callback, void(*)(void*) finished)
----



Registers a callback function which will be executed when this session is closed.

 
  Parameters
 
 
  
   
    
     session
     The session on which to register the callback
    
    
     data
     The argument to be passed to the callback function when it is executed
    
    
     callback
     The function to be called
    
    
     finished
     A function which will be executed when the session is destroyed, allowing cleanup
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `session` a| The session on which to register the callback a| 
a| `data` a| The argument to be passed to the callback function when it is executed a| 
a| `callback` a| The function to be called a| 
a| `finished` a| A function which will be executed when the session is destroyed, allowing cleanup a| 
|===

[caption=""]
.Returns
`void`

[#_◆_session_on_reopen_]
==== session_on_reopen

[source,cpp]
----
void session_on_reopen(const struct Session* session, void* data, void(*)(void*) callback, void(*)(void*) finished)
----



Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.

 
  Parameters
 
 
  
   
    
     session
     The session on which to register the callback
    
    
     data
     The argument to be passed to the callback function when it is executed
    
    
     callback
     The function to be called
    
    
     finished
     A function which will be executed when the session is destroyed, allowing cleanup
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `session` a| The session on which to register the callback a| 
a| `data` a| The argument to be passed to the callback function when it is executed a| 
a| `callback` a| The function to be called a| 
a| `finished` a| A function which will be executed when the session is destroyed, allowing cleanup a| 
|===

[caption=""]
.Returns
`void`

