maven = use_extension("@typedb_dependencies//library/maven:maven_extension.bzl", "maven")
maven.artifacts(artifacts = [
    "io.cucumber:cucumber-java",       # //java/test/behaviour/...
    "io.cucumber:cucumber-junit",      # //java/test/behaviour/...
    "junit:junit",                     # //java/test/behaviour/...
    "org.hamcrest:hamcrest-library",   # //java/test/behaviour/connection/transaction
    "org.slf4j:slf4j-api",             # //java/test/integration
])
