[#_Credentials]
=== Credentials

`Class(name=Credentials, anchor=Credentials, enumConstants=[], description=[User credentials for connecting to TypeDB Server. 
], examples=[Credential credentials = new Credential(username, password);], fields=[], methods=[Method(name=Credentials, signature=public Credentials​(java.lang.String username,
                   java.lang.String password), anchor=Credentials_Credentials_java_lang_String_java_lang_String, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to connect as, type=java.lang.String), Variable(name=password, anchor=null, defaultValue=null, description=The password for the user, type=java.lang.String)], description=[], examples=[], mode=null, returnDescription=null, returnType=public)], packagePath=com.typedb.driver.api, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api`

User credentials for connecting to TypeDB Server. 


[caption=""]
.Examples
[source,java]
----
Credential credentials = new Credential(username, password);
----

// tag::methods[]
[#_Credentials_Credentials_java_lang_String_java_lang_String]
==== Credentials

[source,java]
----
public Credentials​(java.lang.String username,
                   java.lang.String password)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `java.lang.String`
a| `password` a| The password for the user a| `java.lang.String`
|===

[caption=""]
.Returns
`public`

// end::methods[]

