[#_Database]
=== Database

`class`

*Package*: `com.typedb.driver.api.database`

// tag::methods[]
[#_Database_delete_]
==== delete()

[source,java]
----
void delete()
     throws TypeDBDriverException
----

Deletes this database. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.delete()
----

[#_Database_exportToFile_java_lang_String_java_lang_String]
==== exportToFile()

[source,java]
----
void exportToFile​(java.lang.String schemaFilePath,
                  java.lang.String dataFilePath)
           throws TypeDBDriverException
----

Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaFilePath` a| The path to the schema definition file to be created a| `java.lang.String`
a| `dataFilePath` a| The path to the data file to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.exportToFile("schema.typeql", "data.typedb")
----

[#_Database_name_]
==== name()

[source,java]
----
@CheckReturnValue
java.lang.String name()
----

The database name as a string.

[caption=""]
.Returns
`java.lang.String`

[#_Database_schema_]
==== schema()

[source,java]
----
@CheckReturnValue
java.lang.String schema()
                 throws TypeDBDriverException
----

A full schema text as a valid TypeQL define query string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.schema()
----

[#_Database_typeSchema_]
==== typeSchema()

[source,java]
----
@CheckReturnValue
java.lang.String typeSchema()
                     throws TypeDBDriverException
----

The types in the schema as a valid TypeQL define query string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.typeSchema()
----

// end::methods[]

