[#_Database]
=== Database

*Package*: `com.vaticle.typedb.driver.api.database`

// tag::methods[]
[#_Database_delete__]
==== delete

[source,java]
----
void delete()
----

Deletes this database. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.delete()
----

[#_Database_name__]
==== name

[source,java]
----
@CheckReturnValue
java.lang.String name()
----

The database name as a string.

[caption=""]
.Returns
`java.lang.String`

[#_Database_preferredReplica__]
==== preferredReplica

[source,java]
----
@CheckReturnValue
java.util.Optional<? extends Database.Replica> preferredReplica()
----

Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud_ 


[caption=""]
.Returns
`java.util.Optional<? extends Database.Replica>`

[caption=""]
.Code examples
[source,java]
----
database.preferredReplica()
----

[#_Database_primaryReplica__]
==== primaryReplica

[source,java]
----
@CheckReturnValue
java.util.Optional<? extends Database.Replica> primaryReplica()
----

Returns the primary replica for this database. _Only works in TypeDB Cloud_ 


[caption=""]
.Returns
`java.util.Optional<? extends Database.Replica>`

[caption=""]
.Code examples
[source,java]
----
database.primaryReplica()
----

[#_Database_replicas__]
==== replicas

[source,java]
----
@CheckReturnValue
java.util.Set<? extends Database.Replica> replicas()
----

Set of ``Replica`` instances for this database. Only works in TypeDB Cloud


[caption=""]
.Returns
`java.util.Set<? extends Database.Replica>`

[caption=""]
.Code examples
[source,java]
----
database.replicas()
----

[#_Database_ruleSchema__]
==== ruleSchema

[source,java]
----
@CheckReturnValue
java.lang.String ruleSchema()
----

The rules in the schema as a valid TypeQL define query string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.ruleSchema()
----

[#_Database_schema__]
==== schema

[source,java]
----
@CheckReturnValue
java.lang.String schema()
----

A full schema text as a valid TypeQL define query string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.schema()
----

[#_Database_typeSchema__]
==== typeSchema

[source,java]
----
@CheckReturnValue
java.lang.String typeSchema()
----

The types in the schema as a valid TypeQL define query string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.typeSchema()
----

// end::methods[]

