[#_Database]
=== Database

*Package*: `com.typedb.driver.api.database`

// tag::methods[]
[#_Database_delete_]
==== delete

[source,java]
----
default void delete()
             throws TypeDBDriverException
----

Deletes this database, using default strong consistency. See <<#_delete_com_typedb_driver_api_ConsistencyLevel,``delete(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.delete()
----

[#_Database_delete_ConsistencyLevel]
==== delete

[source,java]
----
void delete​(ConsistencyLevel consistencyLevel)
     throws TypeDBDriverException
----

Deletes this database. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.delete(new ConsistencyLevel.Strong())
----

[#_Database_exportToFile_java_lang_String_java_lang_String]
==== exportToFile

[source,java]
----
default void exportToFile​(java.lang.String schemaFilePath,
                          java.lang.String dataFilePath)
                   throws TypeDBDriverException
----

Export a database into a schema definition and a data files saved to the disk, using default strong consistency. This is a blocking operation and may take a significant amount of time depending on the database size. See <<#_exportToFile_java_lang_String_java_lang_String_com_typedb_driver_api_ConsistencyLevel,``exportToFile(String, String, ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaFilePath` a| The path to the schema definition file to be created a| `java.lang.String`
a| `dataFilePath` a| The path to the data file to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.exportToFile("schema.typeql", "data.typedb")
----

[#_Database_exportToFile_java_lang_String_java_lang_String_ConsistencyLevel]
==== exportToFile

[source,java]
----
void exportToFile​(java.lang.String schemaFilePath,
                  java.lang.String dataFilePath,
                  ConsistencyLevel consistencyLevel)
           throws TypeDBDriverException
----

Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaFilePath` a| The path to the schema definition file to be created a| `java.lang.String`
a| `dataFilePath` a| The path to the data file to be created a| `java.lang.String`
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
database.exportToFile("schema.typeql", "data.typedb", new ConsistencyLevel.Strong())
----

[#_Database_name_]
==== name

[source,java]
----
@CheckReturnValue
java.lang.String name()
----

The database name as a string. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.name()
----

[#_Database_schema_]
==== schema

[source,java]
----
@CheckReturnValue
default java.lang.String schema()
                         throws TypeDBDriverException
----

A full schema text as a valid TypeQL define query string, using default strong consistency. See <<#_schema_com_typedb_driver_api_ConsistencyLevel,``schema(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.schema()
----

[#_Database_schema_ConsistencyLevel]
==== schema

[source,java]
----
@CheckReturnValue
java.lang.String schema​(ConsistencyLevel consistencyLevel)
                 throws TypeDBDriverException
----

A full schema text as a valid TypeQL define query string. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.schema(new ConsistencyLevel.Strong())
----

[#_Database_typeSchema_]
==== typeSchema

[source,java]
----
@CheckReturnValue
default java.lang.String typeSchema()
                             throws TypeDBDriverException
----

The types in the schema as a valid TypeQL define query string, using default strong consistency. See <<#_typeSchema_com_typedb_driver_api_ConsistencyLevel,``typeSchema(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.typeSchema()
----

[#_Database_typeSchema_ConsistencyLevel]
==== typeSchema

[source,java]
----
@CheckReturnValue
java.lang.String typeSchema​(ConsistencyLevel consistencyLevel)
                     throws TypeDBDriverException
----

The types in the schema as a valid TypeQL define query string. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
database.typeSchema(new ConsistencyLevel.Strong())
----

// end::methods[]

