[#_DriverOptions]
[.doc-api-reference-driver]
=== DriverOptions

`class`

*Package*: `com.typedb.driver.api`

TypeDB driver options. ``DriverOptions`` are used to specify the driver's connection behavior.

// tag::methods[]
[#_DriverOptions_DriverOptions_DriverTlsConfig]
==== method ``DriverOptions``

[source,java]
----
public DriverOptionsвЂ‹(DriverTlsConfig tlsConfig)
----

Produces a new ``DriverOptions`` object for connecting to TypeDB Server using custom TLS settings. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext. 


[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
DriverOptions options = new DriverOptions(DriverTlsConfig.enabledWithNativeRootCA());
----

[#_DriverOptions_primaryFailoverRetries_]
==== method ``primaryFailoverRetries``

[source,java]
----
@CheckReturnValue
public java.lang.Integer primaryFailoverRetries()
----

Returns the value set for the primary failover retries limit in this ``DriverOptions`` object. Limits the number of attempts to redirect a request to another primary server in case of a failure due to the change of server roles. 


[caption=""]
.Returns
`publicВ java.lang.Integer`

[caption=""]
.Code examples
[source,java]
----
options.primaryFailoverRetries();
----

[#_DriverOptions_primaryFailoverRetries_int]
==== method ``primaryFailoverRetries``

[source,java]
----
public DriverOptions primaryFailoverRetriesвЂ‹(int primaryFailoverRetries)
----

Explicitly sets the limit on the number of attempts to redirect a request to another primary server in case of a failure due to the change of server roles. Defaults to 1. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `primaryFailoverRetries` a| The limit of primary failover retries. a| `int`
|===

[caption=""]
.Returns
`publicВ DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.primaryFailoverRetries(1);
----

[#_DriverOptions_requestTimeoutMillis_]
==== method ``requestTimeoutMillis``

[source,java]
----
@CheckReturnValue
public java.lang.Long requestTimeoutMillis()
----

Returns the request timeout in milliseconds set for this ``DriverOptions`` object. Specifies the maximum time to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). 


[caption=""]
.Returns
`publicВ java.lang.Long`

[caption=""]
.Code examples
[source,java]
----
options.requestTimeoutMillis();
----

[#_DriverOptions_requestTimeoutMillis_long]
==== method ``requestTimeoutMillis``

[source,java]
----
public DriverOptions requestTimeoutMillisвЂ‹(long requestTimeoutMillis)
----

Sets the maximum time (in milliseconds) to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). Defaults to 2 hours (7200000 milliseconds). 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `requestTimeoutMillis` a| The request timeout in milliseconds. Must be non-negative. a| `long`
|===

[caption=""]
.Returns
`publicВ DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.requestTimeoutMillis(30000); // 30 seconds
----

[#_DriverOptions_tlsConfig_]
==== method ``tlsConfig``

[source,java]
----
@CheckReturnValue
public DriverTlsConfig tlsConfig()
----

Returns the TLS configuration associated with this ``DriverOptions``. Specifies the TLS configuration of the connection to TypeDB. 


[caption=""]
.Returns
`publicВ DriverTlsConfig`

[caption=""]
.Code examples
[source,java]
----
options.tlsConfig();
----

[#_DriverOptions_tlsConfig_DriverTlsConfig]
==== method ``tlsConfig``

[source,java]
----
public DriverOptions tlsConfigвЂ‹(DriverTlsConfig tlsConfig)
----

Overrides the TLS configuration associated with this ``DriverOptions``. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext. 


[caption=""]
.Returns
`publicВ DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.tlsConfig(DriverTlsConfig.enabledWithNativeRootCA());
----

// end::methods[]

