[#_Driver]
=== Driver

*Package*: `com.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `LANGUAGE` a| `static java.lang.String` a| 
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== close

[source,java]
----
void close()
----

Closes the driver. Before instantiating a new driver, the driver thatŌĆÖs currently open should first be closed. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.close();
----

[#_Driver_databases_]
==== databases

[source,java]
----
@CheckReturnValue
DatabaseManager databases()
----

The ``DatabaseManager`` for this connection, providing access to database management methods. 


[caption=""]
.Returns
`DatabaseManager`

[caption=""]
.Code examples
[source,java]
----
driver.databases();
----

[#_Driver_deregisterReplica_long]
==== deregisterReplica

[source,java]
----
void deregisterReplicaŌĆŗ(long replicaID)
----

Deregisters a replica from the cluster the driver is currently connected to. This replica will no longer play a raft role in this cluster. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replicaID` a| The numeric identifier of the deregistered replica a| `long`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.deregisterReplica(2);
----

[#_Driver_isOpen_]
==== isOpen

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this connection is presently open. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.isOpen();
----

[#_Driver_primaryReplica_]
==== primaryReplica

[source,java]
----
@CheckReturnValue
java.util.Optional<? extends ServerReplica> primaryReplica()
----

Returns the primary replica for this driver connection. 


[caption=""]
.Returns
`java.util.Optional<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.primaryReplica();
----

[#_Driver_registerReplica_long_java_lang_String]
==== registerReplica

[source,java]
----
void registerReplicaŌĆŗ(long replicaID,
                     java.lang.String address)
----

Registers a new replica in the cluster the driver is currently connected to. The registered replica will become available eventually, depending on the behavior of the whole cluster. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replicaID` a| The numeric identifier of the new replica a| `long`
a| `address` a| The address(es) of the TypeDB replica as a string a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.registerReplica(2, "127.0.0.1:11729");
----

[#_Driver_replicas_]
==== replicas

[source,java]
----
@CheckReturnValue
java.util.Set<? extends ServerReplica> replicas()
----

Set of ``Replica`` instances for this driver connection. 


[caption=""]
.Returns
`java.util.Set<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.replicas();
----

[#_Driver_serverVersion_]
==== serverVersion

[source,java]
----
@CheckReturnValue
ServerVersion serverVersion()
----

Retrieves the server's version. 


[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,java]
----
driver.serverVersion();
----

[#_Driver_transaction_java_lang_String_Transaction_Type]
==== transaction

[source,java]
----
@CheckReturnValue
Transaction transactionŌĆŗ(java.lang.String database,
                        Transaction.Type type)
                 throws TypeDBDriverException
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the transaction connects a| `java.lang.String`
a| `type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `Transaction.Type`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,java]
----
driver.transaction(database, sessionType);
----

[#_Driver_transaction_java_lang_String_Transaction_Type_TransactionOptions]
==== transaction

[source,java]
----
@CheckReturnValue
Transaction transactionŌĆŗ(java.lang.String database,
                        Transaction.Type type,
                        TransactionOptions options)
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the transaction connects a| `java.lang.String`
a| `type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `Transaction.Type`
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,java]
----
driver.transaction(database, sessionType);
----

[#_Driver_users_]
==== users

[source,java]
----
@CheckReturnValue
UserManager users()
----

The ``UserManager`` for this connection, providing access to user management methods. 


[caption=""]
.Returns
`UserManager`

[caption=""]
.Code examples
[source,java]
----
driver.users();
----

// end::methods[]

