[#_DriverOptions]
=== DriverOptions

*Package*: `com.typedb.driver.api`

TypeDB driver options. ``DriverOptions`` are used to specify the driver's connection behavior.

// tag::methods[]
[#_DriverOptions_DriverOptions_]
==== DriverOptions

[source,java]
----
public DriverOptions()
----

Produces a new ``DriverOptions`` object. 


[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
DriverOptions options = DriverOptions();
----

[#_DriverOptions_primaryFailoverRetries_]
==== primaryFailoverRetries

[source,java]
----
@CheckReturnValue
public java.lang.Integer primaryFailoverRetries()
----

Returns the value set for the primary failover retries limit in this ``DriverOptions`` object. Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles. 


[caption=""]
.Returns
`public java.lang.Integer`

[caption=""]
.Code examples
[source,java]
----
options.primaryFailoverRetries();
----

[#_DriverOptions_primaryFailoverRetries_int]
==== primaryFailoverRetries

[source,java]
----
public DriverOptions primaryFailoverRetries​(int primaryFailoverRetries)
----

Explicitly sets the limit on the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles. Defaults to 1. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `primaryFailoverRetries` a| The limit of primary failover retries. a| `int`
|===

[caption=""]
.Returns
`public DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.primaryFailoverRetries(1);
----

[#_DriverOptions_replicaDiscoveryAttempts_]
==== replicaDiscoveryAttempts

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> replicaDiscoveryAttempts()
----

Returns the value set for the replica discovery attempts limit in this ``DriverOptions`` object. Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most: - {limit} operations are performed if the limit &lt;= the number of replicas. - {number of replicas} operations are performed if the limit &gt; the number of replicas. - {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.replicaDiscoveryAttempts();
----

[#_DriverOptions_replicaDiscoveryAttempts_int]
==== replicaDiscoveryAttempts

[source,java]
----
public DriverOptions replicaDiscoveryAttempts​(int replicaDiscoveryAttempts)
----

Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most: - {limit} operations are performed if the limit &lt;= the number of replicas. - {number of replicas} operations are performed if the limit &gt; the number of replicas. - {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown. If not set, the maximum (practically unlimited) value is used. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replicaDiscoveryAttempts` a| The limit of replica discovery attempts. a| `int`
|===

[caption=""]
.Returns
`public DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.primaryFailoverRetries(1);
----

[#_DriverOptions_tlsEnabled_]
==== tlsEnabled

[source,java]
----
@CheckReturnValue
public java.lang.Boolean tlsEnabled()
----

Returns the value set for the TLS flag in this ``DriverOptions`` object. Specifies whether the connection to TypeDB must be done over TLS. 


[caption=""]
.Returns
`public java.lang.Boolean`

[caption=""]
.Code examples
[source,java]
----
options.tlsEnabled();
----

[#_DriverOptions_tlsEnabled_boolean]
==== tlsEnabled

[source,java]
----
public DriverOptions tlsEnabled​(boolean tlsEnabled)
----

Explicitly sets whether the connection to TypeDB must be done over TLS. WARNING: Setting this to false will make the driver sending passwords as plaintext. Defaults to true. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `tlsEnabled` a| Whether the connection to TypeDB must be done over TLS. a| `boolean`
|===

[caption=""]
.Returns
`public DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.tlsEnabled(true);
----

[#_DriverOptions_tlsRootCAPath_]
==== tlsRootCAPath

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.String> tlsRootCAPath()
----

Returns the TLS root CA set in this ``DriverOptions`` object. Specifies the root CA used in the TLS config for server certificates authentication. Uses system roots if None is set. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
options.tlsRootCAPath();
----

[#_DriverOptions_tlsRootCAPath_java_util_Optional_java_lang_String_]
==== tlsRootCAPath

[source,java]
----
public DriverOptions tlsRootCAPath​(java.util.Optional<java.lang.String> tlsRootCAPath)
----

Returns the TLS root CA set in this ``DriverOptions`` object. Specifies the root CA used in the TLS config for server certificates authentication. Uses system roots if None is set. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `tlsRootCAPath` a| The path to the TLS root CA. If None, system roots are used. a| `java.util.Optional<java.lang.String>`
|===

[caption=""]
.Returns
`public DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.tlsRootCAPath(Optional.of("/path/to/ca-certificate.pem"));
----

[#_DriverOptions_useReplication_]
==== useReplication

[source,java]
----
@CheckReturnValue
public java.lang.Boolean useReplication()
----

Returns the value set for the replication usage flag in this ``DriverOptions`` object. Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address. 


[caption=""]
.Returns
`public java.lang.Boolean`

[caption=""]
.Code examples
[source,java]
----
options.useReplication();
----

[#_DriverOptions_useReplication_boolean]
==== useReplication

[source,java]
----
public DriverOptions useReplication​(boolean useReplication)
----

Explicitly sets whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address. Defaults to true. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `useReplication` a| Whether the connection to TypeDB can use replication. a| `boolean`
|===

[caption=""]
.Returns
`public DriverOptions`

[caption=""]
.Code examples
[source,java]
----
options.useReplication(true);
----

// end::methods[]

