[#_Driver]
[.doc-api-reference-driver]
=== Driver

`class`

*Package*: `com.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `LANGUAGE` a| `static java.lang.String` a| 
|===
// end::properties[]

// tag::methods[]
[#_Driver_close_]
==== method ``close``

[source,java]
----
void close()
----

Closes the driver. Before instantiating a new driver, the driver that's currently open should first be closed. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.close();
----

[#_Driver_databases_]
==== method ``databases``

[source,java]
----
@CheckReturnValue
DatabaseManager databases()
----

The ``DatabaseManager`` for this connection, providing access to database management methods. 


[caption=""]
.Returns
`DatabaseManager`

[caption=""]
.Code examples
[source,java]
----
driver.databases();
----

[#_Driver_deregisterReplica_long]
==== method ``deregisterReplica``

[source,java]
----
void deregisterReplica​(long replicaID)
----

Deregisters a replica from the cluster the driver is currently connected to. This replica will no longer play a raft role in this cluster. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replicaID` a| The numeric identifier of the deregistered replica a| `long`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.deregisterReplica(2);
----

[#_Driver_isOpen_]
==== method ``isOpen``

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this connection is presently open. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.isOpen();
----

[#_Driver_primaryReplica_]
==== method ``primaryReplica``

[source,java]
----
@CheckReturnValue
default java.util.Optional<? extends ServerReplica> primaryReplica()
----

Returns the primary replica for this driver connection, using default automatic routing. See <<#_primaryReplica_com_typedb_driver_api_ServerRouting,``primaryReplica(ServerRouting)``>> for more details and options. 


[caption=""]
.Returns
`java.util.Optional<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.primaryReplica();
----

[#_Driver_primaryReplica_ServerRouting]
==== method ``primaryReplica``

[source,java]
----
@CheckReturnValue
java.util.Optional<? extends ServerReplica> primaryReplica​(ServerRouting serverRouting)
----

Returns the primary replica for this driver connection. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `serverRouting` a| The server routing to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
`java.util.Optional<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.primaryReplica(new ServerRouting.Auto());
----

[#_Driver_registerReplica_long_java_lang_String]
==== method ``registerReplica``

[source,java]
----
void registerReplica​(long replicaID,
                     java.lang.String address)
----

Registers a new replica in the cluster the driver is currently connected to. The registered replica will become available eventually, depending on the behavior of the whole cluster. To register a replica, its clustering address should be passed, not the connection address. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `replicaID` a| The numeric identifier of the new replica a| `long`
a| `address` a| The address(es) of the TypeDB replica as a string a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.registerReplica(2, "127.0.0.1:11729");
----

[#_Driver_serverVersion_]
==== method ``serverVersion``

[source,java]
----
@CheckReturnValue
default ServerVersion serverVersion()
----

Retrieves the server's version, using default automatic routing. See <<#_serverVersion_com_typedb_driver_api_ServerRouting,``serverVersion(ServerRouting)``>> for more details and options. 


[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,java]
----
driver.serverVersion();
----

[#_Driver_serverVersion_ServerRouting]
==== method ``serverVersion``

[source,java]
----
@CheckReturnValue
ServerVersion serverVersion​(ServerRouting serverRouting)
----

Retrieves the server's version. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `serverRouting` a| The server routing to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
`ServerVersion`

[caption=""]
.Code examples
[source,java]
----
driver.serverVersion();
----

[#_Driver_servers_]
==== method ``servers``

[source,java]
----
@CheckReturnValue
default java.util.Set<? extends ServerReplica> servers()
----

Set of servers for this driver connection, using default automatic routing. See <<#_servers_com_typedb_driver_api_ServerRouting,``servers(ServerRouting)``>> for more details and options. 


[caption=""]
.Returns
`java.util.Set<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.servers();
----

[#_Driver_servers_ServerRouting]
==== method ``servers``

[source,java]
----
@CheckReturnValue
java.util.Set<? extends ServerReplica> servers​(ServerRouting serverRouting)
----

Set of servers for this driver connection. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `serverRouting` a| The server routing to use for the operation a| `ServerRouting`
|===

[caption=""]
.Returns
`java.util.Set<? extends ServerReplica>`

[caption=""]
.Code examples
[source,java]
----
driver.servers(new ServerRouting.Auto());
----

[#_Driver_transaction_java_lang_String_Transaction_Type]
==== method ``transaction``

[source,java]
----
@CheckReturnValue
Transaction transaction​(java.lang.String database,
                        Transaction.Type type)
                 throws TypeDBDriverException
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the transaction connects a| `java.lang.String`
a| `type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `Transaction.Type`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,java]
----
driver.transaction(database, sessionType);
----

[#_Driver_transaction_java_lang_String_Transaction_Type_TransactionOptions]
==== method ``transaction``

[source,java]
----
@CheckReturnValue
Transaction transaction​(java.lang.String database,
                        Transaction.Type type,
                        TransactionOptions options)
----

Opens a communication tunnel (transaction) to the given database on the running TypeDB server. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the transaction connects a| `java.lang.String`
a| `type` a| The type of transaction to be created (READ, WRITE, or SCHEMA) a| `Transaction.Type`
a| `options` a| ``TransactionOptions`` to configure the opened transaction a| `TransactionOptions`
|===

[caption=""]
.Returns
`Transaction`

[caption=""]
.Code examples
[source,java]
----
driver.transaction(database, sessionType);
----

[#_Driver_updateAddressTranslation_java_util_Map_java_lang_String_​java_lang_String_]
==== method ``updateAddressTranslation``

[source,java]
----
void updateAddressTranslation​(java.util.Map<java.lang.String,​java.lang.String> addressTranslation)
----

Updates address translation of the driver. This lets you actualize new translation information without recreating the driver from scratch. Useful after registering new replicas requiring address translation. This operation will update existing connections using the provided addresses. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addressTranslation` a| The translation of public TypeDB cluster replica addresses (keys) to server-side private addresses (values) a| `java.util.Map<java.lang.String,​java.lang.String>`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.updateAddressTranslation(2);
----

[#_Driver_users_]
==== method ``users``

[source,java]
----
@CheckReturnValue
UserManager users()
----

The ``UserManager`` for this connection, providing access to user management methods. 


[caption=""]
.Returns
`UserManager`

[caption=""]
.Code examples
[source,java]
----
driver.users();
----

// end::methods[]

