[#_ReplicationRole]
[.doc-api-reference-driver]
=== ReplicationRole

`class`

*Package*: `com.typedb.driver.api.server`

This enum is used to specify the replication role of a server. 


[caption=""]
.Examples
[source,java]
----
server.getRole();
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `CANDIDATE`
a| `PRIMARY`
a| `SECONDARY`
|===
// end::enum_constants[]

// tag::methods[]
[#_ReplicationRole_id_]
==== method ``id``

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_ReplicationRole_isCandidate_]
==== method ``isCandidate``

[source,java]
----
public boolean isCandidate()
----

Checks whether this is a candidate server of the cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicationRole_isPrimary_]
==== method ``isPrimary``

[source,java]
----
public boolean isPrimary()
----

Checks whether this is the primary server of the cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicationRole_isSecondary_]
==== method ``isSecondary``

[source,java]
----
public boolean isSecondary()
----

Checks whether this is a secondary server of the cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicationRole_of_com_typedb_driver_jni_ReplicationRole]
==== method ``of``

[source,java]
----
public static ReplicationRole of​(com.typedb.driver.jni.ReplicationRole nativeType)
----



[caption=""]
.Returns
`public static ReplicationRole`

[#_ReplicationRole_valueOf_java_lang_String]
==== method ``valueOf``

[source,java]
----
public static ReplicationRole valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static ReplicationRole`

[#_ReplicationRole_values_]
==== method ``values``

[source,java]
----
public static ReplicationRole[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (ReplicationRole c : ReplicationRole.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static ReplicationRole[]`

[caption=""]
.Code examples
[source,java]
----
for (ReplicationRole c : ReplicationRole.values())
    System.out.println(c);
----

// end::methods[]

