[#_ReplicaRole]
=== ReplicaRole

*Package*: `com.typedb.driver.api.server`

This enum is used to specify the type of replica. 


[caption=""]
.Examples
[source,java]
----
replica.getType();
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `PRIMARY`
a| `SECONDARY`
|===
// end::enum_constants[]

// tag::methods[]
[#_ReplicaRole_id_]
==== id

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_ReplicaRole_isCandidate_]
==== isCandidate

[source,java]
----
public boolean isCandidate()
----

Checks whether this is a candidate replica of the raft cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicaRole_isPrimary_]
==== isPrimary

[source,java]
----
public boolean isPrimary()
----

Checks whether this is the primary replica of the raft cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicaRole_isSecondary_]
==== isSecondary

[source,java]
----
public boolean isSecondary()
----

Checks whether this is a secondary replica of the raft cluster.

[caption=""]
.Returns
`public boolean`

[#_ReplicaRole_of_com_typedb_driver_jni_ReplicaRole]
==== of

[source,java]
----
public static ReplicaRole of​(com.typedb.driver.jni.ReplicaRole nativeType)
----



[caption=""]
.Returns
`public static ReplicaRole`

[#_ReplicaRole_valueOf_java_lang_String]
==== valueOf

[source,java]
----
public static ReplicaRole valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static ReplicaRole`

[#_ReplicaRole_values_]
==== values

[source,java]
----
public static ReplicaRole[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (ReplicaRole c : ReplicaRole.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static ReplicaRole[]`

[caption=""]
.Code examples
[source,java]
----
for (ReplicaRole c : ReplicaRole.values())
    System.out.println(c);
----

// end::methods[]

