[#_TypeDBCredential]
=== TypeDBCredential

*Package*: `com.vaticle.typedb.driver.api`

User credentials and TLS encryption settings for connecting to TypeDB Cloud. 


[caption=""]
.Examples
[source,java]
----
// Creates a credential as above, but the connection will be made over TLS.
 TypeDBCredential credential = new TypeDBCredential(username, password, true);

 // Creates a credential as above, but TLS will use the specified CA to authenticate server certificates.
 TypeDBCredential credential = new TypeDBCredential(username, password, Path.of("path/to/ca-certificate.pem"));
----

// tag::methods[]
[#_TypeDBCredential_TypeDBCredential__java_lang_String__java_lang_String__boolean]
==== TypeDBCredential

[source,java]
----
public TypeDBCredential​(java.lang.String username,
                        java.lang.String password,
                        boolean tlsEnabled)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `java.lang.String`
a| `password` a| The password for the user a| `java.lang.String`
a| `tlsEnabled` a| Specify whether the connection to TypeDB Cloud must be done over TLS a| `boolean`
|===

[caption=""]
.Returns
`public`

[#_TypeDBCredential_TypeDBCredential__java_lang_String__java_lang_String__java_nio_file_Path]
==== TypeDBCredential

[source,java]
----
public TypeDBCredential​(java.lang.String username,
                        java.lang.String password,
                        java.nio.file.Path tlsRootCAPath)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `java.lang.String`
a| `password` a| The password for the user a| `java.lang.String`
a| `tlsRootCAPath` a| Path to the CA certificate to use for authenticating server certificates. a| `java.nio.file.Path`
|===

[caption=""]
.Returns
`public`

// end::methods[]

