[#_TypeDB]
=== TypeDB

`Class(name=TypeDB, anchor=TypeDB, enumConstants=[], description=[], examples=[], fields=[Variable(name=DEFAULT_ADDRESS, anchor=null, defaultValue=null, description=, type=static java.lang.String)], methods=[Method(name=TypeDB, signature=public TypeDB(), anchor=TypeDB_TypeDB_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public), Method(name=driver, signature=public static Driver driver​(java.lang.String address,
                            Credentials credentials,
                            DriverOptions driverOptions)
                     throws TypeDBDriverException, anchor=TypeDB_driver_java_lang_String_Credentials_DriverOptions, args=[Variable(name=address, anchor=null, defaultValue=null, description=The address of the TypeDB server, type=java.lang.String), Variable(name=credentials, anchor=null, defaultValue=null, description=The credentials to connect with, type=Credentials), Variable(name=driverOptions, anchor=null, defaultValue=null, description=The connection settings to connect with, type=DriverOptions)], description=[Open a TypeDB Driver to a TypeDB server available at the provided address. 
], examples=[TypeDB.driver(address);], mode=null, returnDescription=null, returnType=public static Driver)], packagePath=com.typedb.driver, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `DEFAULT_ADDRESS` a| `static java.lang.String` a| 
|===
// end::properties[]

// tag::methods[]
[#_TypeDB_TypeDB_]
==== TypeDB

[source,java]
----
public TypeDB()
----



[caption=""]
.Returns
`public`

[#_TypeDB_driver_java_lang_String_Credentials_DriverOptions]
==== driver

[source,java]
----
public static Driver driver​(java.lang.String address,
                            Credentials credentials,
                            DriverOptions driverOptions)
                     throws TypeDBDriverException
----

Open a TypeDB Driver to a TypeDB server available at the provided address. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `java.lang.String`
a| `credentials` a| The credentials to connect with a| `Credentials`
a| `driverOptions` a| The connection settings to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
`public static Driver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.driver(address);
----

// end::methods[]

