[#_TypeDBDriver]
=== TypeDBDriver

*Package*: `com.vaticle.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

// tag::methods[]
[#_TypeDBDriver_close__]
==== close

[source,java]
----
void close()
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.close()
----

[#_TypeDBDriver_databases__]
==== databases

[source,java]
----
@CheckReturnValue
DatabaseManager databases()
----

The ``DatabaseManager`` for this connection, providing access to database management methods.

[caption=""]
.Returns
`DatabaseManager`

[#_TypeDBDriver_isOpen__]
==== isOpen

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this connection is presently open. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.isOpen();
----

[#_TypeDBDriver_session__java_lang_String__TypeDBSession_Type]
==== session

[source,java]
----
@CheckReturnValue
TypeDBSession session​(java.lang.String database,
                      TypeDBSession.Type type)
----

Opens a session to the given database with default options.


See also: <<#_session_java_lang_String_com_vaticle_typedb_driver_api_TypeDBSession_Type_com_vaticle_typedb_driver_api_TypeDBOptions,``session(String, TypeDBSession.Type, TypeDBOptions)``>>


[caption=""]
.Returns
`TypeDBSession`

[#_TypeDBDriver_session__java_lang_String__TypeDBSession_Type__TypeDBOptions]
==== session

[source,java]
----
@CheckReturnValue
TypeDBSession session​(java.lang.String database,
                      TypeDBSession.Type type,
                      TypeDBOptions options)
----

Opens a communication tunnel (session) to the given database on the running TypeDB server. For more information on the methods, available with sessions, see the ``TypeDBSession`` section. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the session connects a| `java.lang.String`
a| `type` a| The type of session to be created (DATA or SCHEMA) a| `TypeDBSession.Type`
a| `options` a| ``TypeDBOptions`` for the session a| `TypeDBOptions`
|===

[caption=""]
.Returns
`TypeDBSession`

[caption=""]
.Code examples
[source,java]
----
driver.session(database, sessionType, options);
----

[#_TypeDBDriver_user__]
==== user

[source,java]
----
@CheckReturnValue
User user()
----

Returns the logged-in user for the connection. Only for TypeDB Cloud. 


[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.user();
----

[#_TypeDBDriver_users__]
==== users

[source,java]
----
@CheckReturnValue
UserManager users()
----

The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud. 


[caption=""]
.Returns
`UserManager`

[caption=""]
.Code examples
[source,java]
----
driver.users();
----

// end::methods[]

