[#_TypeDB]
=== TypeDB

*Package*: `com.typedb.driver`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `DEFAULT_ADDRESS` a| `static java.lang.String` a| 
|===
// end::properties[]

// tag::methods[]
[#_TypeDB_TypeDB_]
==== TypeDB

[source,java]
----
public TypeDB()
----



[caption=""]
.Returns
`public`

[#_TypeDB_cloudDriver_java_lang_String_Credentials_DriverOptions]
==== cloudDriver

[source,java]
----
public static Driver cloudDriver​(java.lang.String address,
                                 Credentials credentials,
                                 DriverOptions driverOptions)
                          throws TypeDBDriverException
----

Open a TypeDB Driver to a TypeDB Cluster server available at the provided address, using the provided credential. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `java.lang.String`
a| `credentials` a| The credential to connect with a| `Credentials`
a| `driverOptions` a| The connection settings to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
`public static Driver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.cloudDriver(address, credential);
----

[#_TypeDB_cloudDriver_java_util_Set_java_lang_String_Credentials_DriverOptions]
==== cloudDriver

[source,java]
----
public static Driver cloudDriver​(java.util.Set<java.lang.String> addresses,
                                 Credentials credentials,
                                 DriverOptions driverOptions)
                          throws TypeDBDriverException
----

Open a TypeDB Driver to TypeDB Cluster server(s) available at the provided addresses, using the provided credential. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a| The address(es) of the TypeDB server(s) a| `java.util.Set<java.lang.String>`
a| `credentials` a| The credential to connect with a| `Credentials`
a| `driverOptions` a| The connection settings to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
`public static Driver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.cloudDriver(addresses, credential);
----

[#_TypeDB_cloudDriver_java_util_Map_java_lang_String_​java_lang_String_Credentials_DriverOptions]
==== cloudDriver

[source,java]
----
public static Driver cloudDriver​(java.util.Map<java.lang.String,​java.lang.String> addressTranslation,
                                 Credentials credentials,
                                 DriverOptions driverOptions)
                          throws TypeDBDriverException
----

Open a TypeDB Driver to TypeDB Cluster server(s), using provided address translation, with the provided credential. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addressTranslation` a| Translation map from addresses to be used by the driver for connection to addresses received from the TypeDB server(s) a| `java.util.Map<java.lang.String,​java.lang.String>`
a| `credentials` a| The credential to connect with a| `Credentials`
a| `driverOptions` a| The connection settings to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
`public static Driver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.cloudDriver(addressTranslation, credential);
----

[#_TypeDB_coreDriver_java_lang_String_Credentials_DriverOptions]
==== coreDriver

[source,java]
----
public static Driver coreDriver​(java.lang.String address,
                                Credentials credentials,
                                DriverOptions driverOptions)
                         throws TypeDBDriverException
----

Open a TypeDB Driver to a TypeDB Core server available at the provided address. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `java.lang.String`
a| `credentials` a| The credentials to connect with a| `Credentials`
a| `driverOptions` a| The connection settings to connect with a| `DriverOptions`
|===

[caption=""]
.Returns
`public static Driver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.coreDriver(address);
----

// end::methods[]

