[#_UserManager]
=== UserManager

*Package*: `com.vaticle.typedb.driver.api.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all__]
==== all

[source,java]
----
java.util.Set<User> all()
----

Retrieves all users which exist on the TypeDB server. 


[caption=""]
.Returns
`java.util.Set<User>`

[caption=""]
.Code examples
[source,java]
----
driver.users().all();
----

[#_UserManager_contains__java_lang_String]
==== contains

[source,java]
----
@CheckReturnValue
boolean contains​(java.lang.String username)
----

Checks if a user with the given name exists. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| `java.lang.String`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.users().contains(username);
----

[#_UserManager_create__java_lang_String__java_lang_String]
==== create

[source,java]
----
void create​(java.lang.String username,
            java.lang.String password)
----

Creates a user with the given name &amp; password. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `java.lang.String`
a| `password` a| The password of the user to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().create(username, password);
----

[#_UserManager_delete__java_lang_String]
==== delete

[source,java]
----
void delete​(java.lang.String username)
----

Deletes a user with the given name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be deleted a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().delete(username);
----

[#_UserManager_get__java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
User get​(java.lang.String username)
----

Retrieves a user with the given name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().get(username);
----

[#_UserManager_passwordSet__java_lang_String__java_lang_String]
==== passwordSet

[source,java]
----
void passwordSet​(java.lang.String username,
                 java.lang.String password)
----

Sets a new password for a user. This operation can only be performed by administrators. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to set the password of a| `java.lang.String`
a| `password` a| The new password a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().passwordSet(username, password);
----

// end::methods[]

