[#_UserManager]
=== UserManager

*Package*: `com.typedb.driver.api.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== all

[source,java]
----
default java.util.Set<User> all()
                         throws TypeDBDriverException
----

Retrieves all users which exist on the TypeDB server, using default strong consistency. See <<#_all_com_typedb_driver_api_ConsistencyLevel,``all(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`java.util.Set<User>`

[caption=""]
.Code examples
[source,java]
----
driver.users().all();
----

[#_UserManager_all_ConsistencyLevel]
==== all

[source,java]
----
java.util.Set<User> all​(ConsistencyLevel consistencyLevel)
                 throws TypeDBDriverException
----

Retrieves all users which exist on the TypeDB server. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`java.util.Set<User>`

[caption=""]
.Code examples
[source,java]
----
driver.users().all(new ConsistencyLevel.Strong());
----

[#_UserManager_contains_java_lang_String]
==== contains

[source,java]
----
@CheckReturnValue
default boolean contains​(java.lang.String username)
                  throws TypeDBDriverException
----

Checks if a user with the given name exists., using default strong consistency. See <<#_contains_java_lang_String_com_typedb_driver_api_ConsistencyLevel,``contains(String, ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The username to be checked a| `java.lang.String`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.users().contains(username);
----

[#_UserManager_contains_java_lang_String_ConsistencyLevel]
==== contains

[source,java]
----
@CheckReturnValue
boolean contains​(java.lang.String username,
                 ConsistencyLevel consistencyLevel)
          throws TypeDBDriverException
----

Checks if a user with the given name exists. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The username to be checked a| `java.lang.String`
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.users().contains(username, new ConsistencyLevel.Strong());
----

[#_UserManager_create_java_lang_String_java_lang_String]
==== create

[source,java]
----
default void create​(java.lang.String username,
                    java.lang.String password)
             throws TypeDBDriverException
----

Creates a user with the given name &amp; password, using default strong consistency. See <<#_create_java_lang_String_java_lang_String_com_typedb_driver_api_ConsistencyLevel,``create(String, String, ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `java.lang.String`
a| `password` a| The password of the user to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().create(username, password);
----

[#_UserManager_create_java_lang_String_java_lang_String_ConsistencyLevel]
==== create

[source,java]
----
void create​(java.lang.String username,
            java.lang.String password,
            ConsistencyLevel consistencyLevel)
     throws TypeDBDriverException
----

Creates a user with the given name &amp; password. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `java.lang.String`
a| `password` a| The password of the user to be created a| `java.lang.String`
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().create(username, password, new ConsistencyLevel.Strong());
----

[#_UserManager_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
default User get​(java.lang.String username)
          throws TypeDBDriverException
----

Retrieves a user with the given name, using default strong consistency. See <<#_get_java_lang_String_com_typedb_driver_api_ConsistencyLevel,``get(String, ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().get(username);
----

[#_UserManager_get_java_lang_String_ConsistencyLevel]
==== get

[source,java]
----
@CheckReturnValue
User get​(java.lang.String username,
         ConsistencyLevel consistencyLevel)
  throws TypeDBDriverException
----

Retrieves a user with the given name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `java.lang.String`
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().get(username, new ConsistencyLevel.Strong());
----

[#_UserManager_getCurrent_]
==== getCurrent

[source,java]
----
@CheckReturnValue
default User getCurrent()
                 throws TypeDBDriverException
----

Retrieves the name of the user who opened the current connection, using default strong consistency. See <<#_getCurrent_com_typedb_driver_api_ConsistencyLevel,``getCurrent(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().getCurrent();
----

[#_UserManager_getCurrent_ConsistencyLevel]
==== getCurrent

[source,java]
----
@CheckReturnValue
User getCurrent​(ConsistencyLevel consistencyLevel)
         throws TypeDBDriverException
----

Retrieves the name of the user who opened the current connection. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().getCurrent(new ConsistencyLevel.Strong());
----

// end::methods[]

