[#_User]
=== User

*Package*: `com.typedb.driver.api.user`

TypeDB user information

// tag::methods[]
[#_User_delete_]
==== delete

[source,java]
----
default void delete()
----

Deletes this user, using default strong consistency. See <<#_delete_com_typedb_driver_api_ConsistencyLevel,``delete(ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
user.delete();
----

[#_User_delete_ConsistencyLevel]
==== delete

[source,java]
----
void delete​(ConsistencyLevel consistencyLevel)
----

Deletes this user. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
user.delete(new ConsistencyLevel.Strong());
----

[#_User_name_]
==== name

[source,java]
----
@CheckReturnValue
java.lang.String name()
----

Returns the name of this user.

[caption=""]
.Returns
`java.lang.String`

[#_User_updatePassword_java_lang_String]
==== updatePassword

[source,java]
----
default void updatePassword​(java.lang.String password)
----

Updates the password for this user, using default strong consistency. See <<#_updatePassword_java_lang_String_com_typedb_driver_api_ConsistencyLevel,``updatePassword(String, ConsistencyLevel)``>> for more details and options. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `password` a| The new password a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
user.updatePassword("new-password");
----

[#_User_updatePassword_java_lang_String_ConsistencyLevel]
==== updatePassword

[source,java]
----
void updatePassword​(java.lang.String password,
                    ConsistencyLevel consistencyLevel)
----

Updates the password for this user. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `password` a| The new password a| `java.lang.String`
a| `consistencyLevel` a| The consistency level to use for the operation a| `ConsistencyLevel`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
user.updatePassword("new-password", new ConsistencyLevel.Strong());
----

// end::methods[]

