[#_UserManager]
=== UserManager

*Package*: `com.typedb.driver.api.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== all

[source,java]
----
java.util.Set<User> all()
                 throws TypeDBDriverException
----

Retrieves all users which exist on the TypeDB server. 


[caption=""]
.Returns
`java.util.Set<User>`

[caption=""]
.Code examples
[source,java]
----
driver.users().all();
----

[#_UserManager_contains_java_lang_String]
==== contains

[source,java]
----
@CheckReturnValue
boolean contains​(java.lang.String username)
          throws TypeDBDriverException
----

Checks if a user with the given name exists. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| `java.lang.String`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.users().contains(username);
----

[#_UserManager_create_java_lang_String_java_lang_String]
==== create

[source,java]
----
void create​(java.lang.String username,
            java.lang.String password)
     throws TypeDBDriverException
----

Creates a user with the given name &amp; password. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `java.lang.String`
a| `password` a| The password of the user to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().create(username, password);
----

[#_UserManager_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
User get​(java.lang.String username)
  throws TypeDBDriverException
----

Retrieves a user with the given name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().get(username);
----

[#_UserManager_getCurrentUser_]
==== getCurrentUser

[source,java]
----
@CheckReturnValue
User getCurrentUser()
             throws TypeDBDriverException
----

Retrieves the name of the user who opened the current connection. 


[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().getCurrentUsername();
----

// end::methods[]

