[#_UserManager]
=== UserManager

`Class(name=UserManager, anchor=UserManager, enumConstants=[], description=[Provides access to all user management methods.], examples=[], fields=[], methods=[Method(name=contains, signature=@CheckReturnValue
boolean contains​(java.lang.String username)
          throws TypeDBDriverException, anchor=UserManager_contains_java_lang_String, args=[Variable(name=username, anchor=null, defaultValue=null, description=The user name to be checked, type=java.lang.String)], description=[Checks if a user with the given name exists. 
], examples=[driver.users().contains(username);], mode=null, returnDescription=null, returnType=boolean), Method(name=get, signature=@CheckReturnValue
User get​(java.lang.String username)
  throws TypeDBDriverException, anchor=UserManager_get_java_lang_String, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to retrieve, type=java.lang.String)], description=[Retrieves a user with the given name. 
], examples=[driver.users().get(username);], mode=null, returnDescription=null, returnType=User), Method(name=getCurrentUser, signature=@CheckReturnValue
User getCurrentUser()
             throws TypeDBDriverException, anchor=UserManager_getCurrentUser_, args=[], description=[Retrieves the name of the user who opened the current connection. 
], examples=[driver.users().getCurrentUsername();], mode=null, returnDescription=null, returnType=User), Method(name=all, signature=java.util.Set<User> all()
                 throws TypeDBDriverException, anchor=UserManager_all_, args=[], description=[Retrieves all users which exist on the TypeDB server. 
], examples=[driver.users().all();], mode=null, returnDescription=null, returnType=java.util.Set<User>), Method(name=create, signature=void create​(java.lang.String username,
            java.lang.String password)
     throws TypeDBDriverException, anchor=UserManager_create_java_lang_String_java_lang_String, args=[Variable(name=username, anchor=null, defaultValue=null, description=The name of the user to be created, type=java.lang.String), Variable(name=password, anchor=null, defaultValue=null, description=The password of the user to be created, type=java.lang.String)], description=[Creates a user with the given name &amp; password. 
], examples=[driver.users().create(username, password);], mode=null, returnDescription=null, returnType=void)], packagePath=com.typedb.driver.api.user, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.user`

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all_]
==== all

[source,java]
----
java.util.Set<User> all()
                 throws TypeDBDriverException
----

Retrieves all users which exist on the TypeDB server. 


[caption=""]
.Returns
`java.util.Set<User>`

[caption=""]
.Code examples
[source,java]
----
driver.users().all();
----

[#_UserManager_contains_java_lang_String]
==== contains

[source,java]
----
@CheckReturnValue
boolean contains​(java.lang.String username)
          throws TypeDBDriverException
----

Checks if a user with the given name exists. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| `java.lang.String`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
driver.users().contains(username);
----

[#_UserManager_create_java_lang_String_java_lang_String]
==== create

[source,java]
----
void create​(java.lang.String username,
            java.lang.String password)
     throws TypeDBDriverException
----

Creates a user with the given name &amp; password. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `java.lang.String`
a| `password` a| The password of the user to be created a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
driver.users().create(username, password);
----

[#_UserManager_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
User get​(java.lang.String username)
  throws TypeDBDriverException
----

Retrieves a user with the given name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().get(username);
----

[#_UserManager_getCurrentUser_]
==== getCurrentUser

[source,java]
----
@CheckReturnValue
User getCurrentUser()
             throws TypeDBDriverException
----

Retrieves the name of the user who opened the current connection. 


[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,java]
----
driver.users().getCurrentUsername();
----

// end::methods[]

