[#_Attribute]
=== Attribute

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Thing`
* `TypeDB::Concept`



Attribute is an instance of the attribute type and has a value.

This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_a9d7bf345550cc8975e946f199417d67c]
==== getOwners

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Attribute::getOwners(Transaction& transaction)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_af40edbb6dd90584efd674608b017a583]
==== getOwners

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Attribute::getOwners(Transaction& transaction, const ThingType* ownerType)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `ownerType` a| Filter results for only owners of the given type a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_a99ac2fb893c129001a961d0774689e1d]
==== getType

[source,cpp]
----
std::unique_ptr< AttributeType > TypeDB::Attribute::getType()
----



Retrieves the type which this ``Attribute`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[#_a31902b34d14f8db9094b785186c4c6af]
==== getValue

[source,cpp]
----
std::unique_ptr< Value > TypeDB::Attribute::getValue()
----



Retrieves the value which the ``Attribute`` instance holds.


[caption=""]
.Returns
`std::unique_ptr< Value >`

// end::methods[]

