[#_Attribute]
=== Attribute

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Thing`
* `TypeDB::Concept`



Attribute is an instance of the attribute type and has a value.

This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_a5e783f4f2cc8db60e50fe2bb7a193d7a]
==== getOwners

[source,cpp]
----
ConceptIterable<Thing> TypeDB::Attribute::getOwners(Transaction& transaction)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_a878d27599b4c5cd73f107f233ee047e2]
==== getOwners

[source,cpp]
----
ConceptIterable<Thing> TypeDB::Attribute::getOwners(Transaction& transaction, const ThingType* ownerType)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `ownerType` a| Filter results for only owners of the given type a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_ab0c016c51a92f42ce9afc39d05592063]
==== getType

[source,cpp]
----
std::unique_ptr<AttributeType> TypeDB::Attribute::getType()
----



Retrieves the type which this ``Attribute`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[#_a038eb0aeb015629a7eda9fbce43043d1]
==== getValue

[source,cpp]
----
std::unique_ptr<Value> TypeDB::Attribute::getValue()
----



Retrieves the value which the ``Attribute`` instance holds.


[caption=""]
.Returns
`std::unique_ptr< Value >`

// end::methods[]

