[#_Attribute]
=== Attribute

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Thing`
* `TypeDB::Concept`



Attribute is an instance of the attribute type and has a value.

This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_ConceptIterable__Thing___TypeDBAttributegetOwners___Transaction__transaction_]
==== getOwners

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Attribute::getOwners(Transaction& transaction)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_ConceptIterable__Thing___TypeDBAttributegetOwners___Transaction__transaction__const_ThingType__ptr__ownerType_]
==== getOwners

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Attribute::getOwners(Transaction& transaction, const ThingType* ownerType)
----



Retrieves the instances that own this ``Attribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `ownerType` a| Filter results for only owners of the given type a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_stdunique_ptr__AttributeType___TypeDBAttributegetType___]
==== getType

[source,cpp]
----
std::unique_ptr< AttributeType > TypeDB::Attribute::getType()
----



Retrieves the type which this ``Attribute`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[#_stdunique_ptr__Value___TypeDBAttributegetValue___]
==== getValue

[source,cpp]
----
std::unique_ptr< Value > TypeDB::Attribute::getValue()
----



Retrieves the value which the ``Attribute`` instance holds.


[caption=""]
.Returns
`std::unique_ptr< Value >`

// end::methods[]

