[#_Relation]
=== Relation

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Thing`
* `TypeDB::Concept`



Relation is an instance of a relation type.

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

// tag::methods[]
[#_VoidFuture_TypeDBRelationaddPlayer___Transaction__transaction__RoleType__ptr__roleType__Thing__ptr__player_]
==== addPlayer

[source,cpp]
----
VoidFuture TypeDB::Relation::addPlayer(Transaction& transaction, RoleType* roleType, Thing* player)
----



Adds a new role player to play the given role in this ``Relation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleType` a| The role to be played by the ``player`` a| `RoleType*`
a| `player` a| The thing to play the role a| `Thing*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
relation.addPlayer(transaction, roleType, player).get();
----

[#_stdmap__stdunique_ptr__RoleType____stdunique_ptr__Thing_____TypeDBRelationgetPlayers___Transaction__transaction_]
==== getPlayers

[source,cpp]
----
std::map< std::unique_ptr< RoleType >, std::unique_ptr< Thing > > TypeDB::Relation::getPlayers(Transaction& transaction)
----



Retrieves a mapping of all instances involved in the ``Relation`` and the role each play.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`std::map< std::unique_ptr< RoleType >, std::unique_ptr< Thing > >`

[caption=""]
.Code examples
[source,cpp]
----
relation.getPlayers(transaction)
----

[#_ConceptIterable__Thing___TypeDBRelationgetPlayersByRoleType___Transaction__transaction__const_stdvector__stdunique_ptr__RoleType______roleTypes_]
==== getPlayersByRoleType

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Relation::getPlayersByRoleType(Transaction& transaction, const std::vector< std::unique_ptr< RoleType > >& roleTypes)
----



Retrieves all role players of this ``Relation``, optionally filtered by given role types.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleTypes` a| 0 or more role types a| `const std::vector< std::unique_ptr< RoleType > >&`
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[caption=""]
.Code examples
[source,cpp]
----
relation.getPlayersByRoleType(transaction, roleTypes);
----

[#_ConceptIterable__Thing___TypeDBRelationgetPlayersByRoleType___Transaction__transaction__const_stdvector__RoleType__ptr_____roleTypes_]
==== getPlayersByRoleType

[source,cpp]
----
ConceptIterable< Thing > TypeDB::Relation::getPlayersByRoleType(Transaction& transaction, const std::vector< RoleType* >& roleTypes)
----



See <<#_ConceptIterable__Thing___TypeDBRelationgetPlayersByRoleType___Transaction__transaction__const_stdvector__stdunique_ptr__RoleType______roleTypes_,getPlayersByRoleType>>

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_ConceptIterable__RoleType___TypeDBRelationgetRelating___Transaction__transaction_]
==== getRelating

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::Relation::getRelating(Transaction& transaction)
----



Retrieves all role types currently played in this ``Relation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
relation.getRelating(transaction);
----

[#_stdunique_ptr__RelationType___TypeDBRelationgetType___]
==== getType

[source,cpp]
----
std::unique_ptr< RelationType > TypeDB::Relation::getType()
----



Retrieves the type which this ``Relation`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
relation.getType();
----

[#_VoidFuture_TypeDBRelationremovePlayer___Transaction__transaction__RoleType__ptr__roleType__Thing__ptr__player_]
==== removePlayer

[source,cpp]
----
VoidFuture TypeDB::Relation::removePlayer(Transaction& transaction, RoleType* roleType, Thing* player)
----



Removes the association of the given instance that plays the given role in this ``Relation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleType` a| The role to no longer be played by the thing in this ``Relation`` a| `RoleType*`
a| `player` a| The instance to no longer play the role in this ``Relation`` a| `Thing*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
relation.removePlayer(transaction, roleType, player).get();
----

// end::methods[]

