[#_Thing]
=== Thing

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Concept`



Common super-type of Entity, Relation, and Attribute.

// tag::methods[]
[#_abe0ff63f087da14046affd0c857f09c1]
==== deleteThing

[source,cpp]
----
VoidFuture TypeDB::Thing::deleteThing(Transaction& transaction)
----



Deletes this ``Thing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a992203a23bccf01253e03c6e830bf7ee]
==== getHas

[source,cpp]
----
ConceptIterable<Attribute> TypeDB::Thing::getHas(Transaction& transaction, const std::initializer_list< Annotation >& annotations = {})
----



Retrieves the ``Attribute``s that this ``Thing`` owns, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| 
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_a912e4bc1d61c1b7ba3c77756b7de249d]
==== getHas

[source,cpp]
----
ConceptIterable<Attribute> TypeDB::Thing::getHas(Transaction& transaction, const AttributeType* attribute)
----



See <<#_a46f15a0bdfcf112599b7494e45e164d5,getHas(Transaction&amp;, const std::vector&lt;std::unique_ptr&lt;AttributeType&gt;&gt;&amp;)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_a46f15a0bdfcf112599b7494e45e164d5]
==== getHas

[source,cpp]
----
ConceptIterable<Attribute> TypeDB::Thing::getHas(Transaction& transaction, const std::vector< std::unique_ptr< AttributeType >>& attributeTypes)
----



Retrieves the ``Attribute``s of the specified ``AttributeType``s that this ``Thing`` owns.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| 
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_a02dd231bca631b0efa9d85a0e27d2f70]
==== getHas

[source,cpp]
----
ConceptIterable<Attribute> TypeDB::Thing::getHas(Transaction& transaction, const std::vector< const AttributeType* >& attributeTypes)
----



See <<#_a46f15a0bdfcf112599b7494e45e164d5,getHas(Transaction&amp; transaction, const std::vector&lt;std::unique_ptr&lt;AttributeType&gt;&gt;&amp; attributeTypes)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_a849524a6fa7dc982ed7f7888fa274a12]
==== getHas

[source,cpp]
----
ConceptIterable<Attribute> TypeDB::Thing::getHas(Transaction& transaction, const std::vector< Annotation >& annotations)
----



See <<#_a992203a23bccf01253e03c6e830bf7ee,getHas(Transaction&amp;, const std::initializer_list&lt;Annotation&gt;&amp;)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_af68dd23809c07ce832a195d45181b969]
==== getIID

[source,cpp]
----
std::string TypeDB::Thing::getIID()
----



Retrieves the unique id of the ``Thing``.


[caption=""]
.Returns
`std::string`

[#_a20ec2c8e15c710c7331b52c8150f2143]
==== getPlaying

[source,cpp]
----
ConceptIterable<RoleType> TypeDB::Thing::getPlaying(Transaction& transaction)
----



Retrieves the roles that this ``Thing`` is currently playing.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[#_a4599a090f805ffcc6e028ed18b04f281]
==== getRelations

[source,cpp]
----
ConceptIterable<Relation> TypeDB::Thing::getRelations(Transaction& transaction, const std::vector< std::unique_ptr< RoleType >>& roleTypes = {})
----



Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleTypes` a| The array of roles to filter the relations by. a| 
|===

[caption=""]
.Returns
`ConceptIterable< Relation >`

[#_a0a5d5252d78c8a8ed73c373ae06370b8]
==== getRelations

[source,cpp]
----
ConceptIterable<Relation> TypeDB::Thing::getRelations(Transaction& transaction, const std::vector< RoleType* >& roleTypes)
----



See <<#_a4599a090f805ffcc6e028ed18b04f281,getRelations(Transaction&amp; transaction, const std::vector&lt;std::unique_ptr&lt;RoleType&gt;&gt;&amp; roleTypes)>>

[caption=""]
.Returns
`ConceptIterable< Relation >`

[#_adcb7670438d8f9ef0c39ddb32944394b]
==== getType

[source,cpp]
----
std::unique_ptr<ThingType> TypeDB::Thing::getType()
----



Retrieves the type which this ``Thing`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< ThingType >`

[#_af67ee0aa60e5fd9aa135f257b7ad7bfd]
==== isDeleted

[source,cpp]
----
BoolFuture TypeDB::Thing::isDeleted(Transaction& transaction)
----



Checks if this ``Thing`` is deleted.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`BoolFuture`

[#_abfb6cf44f242546cbe0d6975608743c0]
==== isInferred

[source,cpp]
----
bool TypeDB::Thing::isInferred()
----



Checks if this ``Thing`` is inferred by a [Reasoning Rule].


[caption=""]
.Returns
`bool`

[#_a596f2c1b391425ee4ba6694b827f64d3]
==== setHas

[source,cpp]
----
VoidFuture TypeDB::Thing::setHas(Transaction& transaction, Attribute* attribute)
----



Assigns an ``Attribute`` to be owned by this ``Thing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a8ec0dd499b28fec81010dfca5910dd9c]
==== unsetHas

[source,cpp]
----
VoidFuture TypeDB::Thing::unsetHas(Transaction& transaction, Attribute* attribute)
----



Unassigns an ``Attribute`` from this ``Thing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| 
|===

[caption=""]
.Returns
`VoidFuture`

// end::methods[]

