[#_Thing]
=== Thing

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Concept`



Common super-type of Entity, Relation, and Attribute.

// tag::methods[]
[#_VoidFuture_TypeDBThingdeleteThing___Transaction__transaction_]
==== deleteThing

[source,cpp]
----
VoidFuture TypeDB::Thing::deleteThing(Transaction& transaction)
----



Deletes this ``Thing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thing.deleteThing(transaction).get();
----

[#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdinitializer_list__Annotation____annotations___]
==== getHas

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::Thing::getHas(Transaction& transaction, const std::initializer_list< Annotation >& annotations = {})
----



Retrieves the ``Attribute``s that this ``Thing`` owns, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| 
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
thing.getHas(transaction);
thing.getHas(transaction, {Annotation.key()}));
----

[#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_AttributeType__ptr__attribute_]
==== getHas

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::Thing::getHas(Transaction& transaction, const AttributeType* attribute)
----



See <<#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdvector__stdunique_ptr__AttributeType______attributeTypes_,getHas(Transaction&amp;, const std::vector&lt;std::unique_ptr&lt;AttributeType&gt;&gt;&amp;)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdvector__stdunique_ptr__AttributeType______attributeTypes_]
==== getHas

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::Thing::getHas(Transaction& transaction, const std::vector< std::unique_ptr< AttributeType > >& attributeTypes)
----



Retrieves the ``Attribute``s of the specified ``AttributeType``s that this ``Thing`` owns.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `const std::vector< std::unique_ptr< AttributeType > >&`
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
thing.getHas(transaction, attributeTypes);
----

[#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdvector__const_AttributeType__ptr_____attributeTypes_]
==== getHas

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::Thing::getHas(Transaction& transaction, const std::vector< const AttributeType* >& attributeTypes)
----



See <<#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdvector__stdunique_ptr__AttributeType______attributeTypes_,getHas(Transaction&amp; transaction, const std::vector&lt;std::unique_ptr&lt;AttributeType&gt;&gt;&amp; attributeTypes)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdvector__Annotation____annotations_]
==== getHas

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::Thing::getHas(Transaction& transaction, const std::vector< Annotation >& annotations)
----



See <<#_ConceptIterable__Attribute___TypeDBThinggetHas___Transaction__transaction__const_stdinitializer_list__Annotation____annotations___,getHas(Transaction&amp;, const std::initializer_list&lt;Annotation&gt;&amp;)>>

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_stdstring_TypeDBThinggetIID___]
==== getIID

[source,cpp]
----
std::string TypeDB::Thing::getIID()
----



Retrieves the unique id of the ``Thing``.


[caption=""]
.Returns
`std::string`

[caption=""]
.Code examples
[source,cpp]
----
thing.getIID();
----

[#_ConceptIterable__RoleType___TypeDBThinggetPlaying___Transaction__transaction_]
==== getPlaying

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::Thing::getPlaying(Transaction& transaction)
----



Retrieves the roles that this ``Thing`` is currently playing.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
thing.getPlaying(transaction);
----

[#_ConceptIterable__Relation___TypeDBThinggetRelations___Transaction__transaction__const_stdvector__stdunique_ptr__RoleType______roleTypes___]
==== getRelations

[source,cpp]
----
ConceptIterable< Relation > TypeDB::Thing::getRelations(Transaction& transaction, const std::vector< std::unique_ptr< RoleType > >& roleTypes = {})
----



Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleTypes` a| The array of roles to filter the relations by. a| 
|===

[caption=""]
.Returns
`ConceptIterable< Relation >`

[caption=""]
.Code examples
[source,cpp]
----
thing.getRelations(transaction);
thing.getRelations(transaction, roleTypes);
----

[#_ConceptIterable__Relation___TypeDBThinggetRelations___Transaction__transaction__const_stdvector__RoleType__ptr_____roleTypes_]
==== getRelations

[source,cpp]
----
ConceptIterable< Relation > TypeDB::Thing::getRelations(Transaction& transaction, const std::vector< RoleType* >& roleTypes)
----



See <<#_ConceptIterable__Relation___TypeDBThinggetRelations___Transaction__transaction__const_stdvector__stdunique_ptr__RoleType______roleTypes___,getRelations(Transaction&amp; transaction, const std::vector&lt;std::unique_ptr&lt;RoleType&gt;&gt;&amp; roleTypes)>>

[caption=""]
.Returns
`ConceptIterable< Relation >`

[#_stdunique_ptr__ThingType___TypeDBThinggetType___]
==== getType

[source,cpp]
----
std::unique_ptr< ThingType > TypeDB::Thing::getType()
----



Retrieves the type which this ``Thing`` belongs to.


[caption=""]
.Returns
`std::unique_ptr< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
thing.getType();
----

[#_BoolFuture_TypeDBThingisDeleted___Transaction__transaction_]
==== isDeleted

[source,cpp]
----
BoolFuture TypeDB::Thing::isDeleted(Transaction& transaction)
----



Checks if this ``Thing`` is deleted.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`BoolFuture`

[caption=""]
.Code examples
[source,cpp]
----
thing.isDeleted(transaction).get();
----

[#_bool_TypeDBThingisInferred___]
==== isInferred

[source,cpp]
----
bool TypeDB::Thing::isInferred()
----



Checks if this ``Thing`` is inferred by a [Reasoning Rule].


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
thing.isInferred();
----

[#_VoidFuture_TypeDBThingsetHas___Transaction__transaction__Attribute__ptr__attribute_]
==== setHas

[source,cpp]
----
VoidFuture TypeDB::Thing::setHas(Transaction& transaction, Attribute* attribute)
----



Assigns an ``Attribute`` to be owned by this ``Thing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thing.setHas(transaction, attribute).get();
----

[#_VoidFuture_TypeDBThingunsetHas___Transaction__transaction__Attribute__ptr__attribute_]
==== unsetHas

[source,cpp]
----
VoidFuture TypeDB::Thing::unsetHas(Transaction& transaction, Attribute* attribute)
----



Unassigns an ``Attribute`` from this ``Thing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thing.unsetHas(transaction, attribute).get();
----

// end::methods[]

