[#_Value]
=== Value

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Concept`



A primitive value. Holds the value of an attribute, or the result of an expression in a query.

// tag::methods[]
[#_bool_TypeDBValueasBoolean_]
==== asBoolean

[source,cpp]
----
bool TypeDB::Value::asBoolean()
----



Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.asBoolean();
----

[#_DateTime_TypeDBValueasDateTime_]
==== asDateTime

[source,cpp]
----
DateTime TypeDB::Value::asDateTime()
----



Returns a ``DateTime`` value of this value concept. If the value has another type, raises an exception.


[caption=""]
.Returns
`DateTime`

[caption=""]
.Code examples
[source,cpp]
----
value.asDatetime();
----

[#_double_TypeDBValueasDouble_]
==== asDouble

[source,cpp]
----
double TypeDB::Value::asDouble()
----



Returns a ``double`` value of this value concept. If the value has another type, raises an exception.


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,cpp]
----
value.asDouble();
----

[#_int64_t_TypeDBValueasLong_]
==== asLong

[source,cpp]
----
int64_t TypeDB::Value::asLong()
----



Returns a ``long`` value of this value concept. If the value has another type, raises an exception.


[caption=""]
.Returns
`int64_t`

[caption=""]
.Code examples
[source,cpp]
----
value.asLong();
----

[#_stdstring_TypeDBValueasString_]
==== asString

[source,cpp]
----
std::string TypeDB::Value::asString()
----



Returns a ``string`` value of this value concept. If the value has another type, raises an exception.


[caption=""]
.Returns
`std::string`

[caption=""]
.Code examples
[source,cpp]
----
value.asString();
----

[#_static_stdstring_TypeDBValueformatDateTime_DateTime_t_]
==== formatDateTime

[source,cpp]
----
static std::string TypeDB::Value::formatDateTime(DateTime t)
----



Returns a string in the TypeQL DateTime format corresponding to the specified DateTime (yyyy-mm-dd'T'HH:MM:SS)


[caption=""]
.Returns
`static std::string`

[caption=""]
.Code examples
[source,cpp]
----
Value::formatDateTime(datetime);
----

[#_bool_TypeDBValueisBoolean_]
==== isBoolean

[source,cpp]
----
bool TypeDB::Value::isBoolean()
----



Returns ``true`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``false``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.isBoolean()
----

[#_bool_TypeDBValueisDateTime_]
==== isDateTime

[source,cpp]
----
bool TypeDB::Value::isDateTime()
----



Returns ``True`` if the value which this value concept holds is of type ``DateTime``. Otherwise, returns ``false``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.isDatetime();
----

[#_bool_TypeDBValueisDouble_]
==== isDouble

[source,cpp]
----
bool TypeDB::Value::isDouble()
----



Returns ``true`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``false``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.isDouble();
----

[#_bool_TypeDBValueisLong_]
==== isLong

[source,cpp]
----
bool TypeDB::Value::isLong()
----



Returns ``true`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``false``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.isLong()
----

[#_bool_TypeDBValueisString_]
==== isString

[source,cpp]
----
bool TypeDB::Value::isString()
----



Returns ``true`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``false``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
value.isString();
----

[#_static_stdunique_ptr_Value_TypeDBValueof_bool_value_]
==== of

[source,cpp]
----
static std::unique_ptr< Value > TypeDB::Value::of(bool value)
----



Creates a new Value object of the specified boolean value.


[caption=""]
.Returns
`static std::unique_ptr< Value >`

[caption=""]
.Code examples
[source,cpp]
----
Value::of(value);
----

[#_static_stdunique_ptr_Value_TypeDBValueof_int64_t_value_]
==== of

[source,cpp]
----
static std::unique_ptr< Value > TypeDB::Value::of(int64_t value)
----



Creates a new Value object of the specified long value.


[caption=""]
.Returns
`static std::unique_ptr< Value >`

[caption=""]
.Code examples
[source,cpp]
----
Value::of(value);
----

[#_static_stdunique_ptr_Value_TypeDBValueof_double_value_]
==== of

[source,cpp]
----
static std::unique_ptr< Value > TypeDB::Value::of(double value)
----



Creates a new Value object of the specified double value.


[caption=""]
.Returns
`static std::unique_ptr< Value >`

[caption=""]
.Code examples
[source,cpp]
----
Value::of(value);
----

[#_static_stdunique_ptr_Value_TypeDBValueof_const_stdstring_value_]
==== of

[source,cpp]
----
static std::unique_ptr< Value > TypeDB::Value::of(const std::string& value)
----



Creates a new Value object of the specified string value.


[caption=""]
.Returns
`static std::unique_ptr< Value >`

[caption=""]
.Code examples
[source,cpp]
----
Value::of(value);
----

[#_static_stdunique_ptr_Value_TypeDBValueof_DateTime_value_]
==== of

[source,cpp]
----
static std::unique_ptr< Value > TypeDB::Value::of(DateTime value)
----



Creates a new Value object of the specified DateTime value.


[caption=""]
.Returns
`static std::unique_ptr< Value >`

[caption=""]
.Code examples
[source,cpp]
----
Value::of(value);
----

[#_static_DateTime_TypeDBValueparseDateTime_const_stdstring_s_]
==== parseDateTime

[source,cpp]
----
static DateTime TypeDB::Value::parseDateTime(const std::string& s)
----



Parses a DateTime from a string in the TypeQL DateTime format (yyyy-mm-dd'T'HH:MM:SS)


[caption=""]
.Returns
`static DateTime`

[caption=""]
.Code examples
[source,cpp]
----
Value::parseDateTime(str);
----

[#_ValueType_TypeDBValuevalueType_]
==== valueType

[source,cpp]
----
ValueType TypeDB::Value::valueType()
----



Retrieves the ``ValueType`` of this value concept.


[caption=""]
.Returns
`ValueType`

[caption=""]
.Code examples
[source,cpp]
----
value.getType()
----

// end::methods[]

