[#_struct_AttributeType]
=== AttributeType

*Implements traits:*

* `AttributeTypeAPI`
* `Clone`
* `Debug`
* `PartialEq<AttributeType>`
* `StructuralPartialEq`
* `ThingTypeAPI`

Attribute types represent properties that other types can own.

Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `String` a| 
a| `is_root` a| `bool` a| 
a| `is_abstract` a| `bool` a| 
a| `value_type` a| `ValueType` a| 
|===
// end::properties[]

// tag::methods[]
[#_struct_AttributeType_tymethod_value_type]
==== value_type

[source,rust]
----
fn value_type(&self) -> ValueType
----

<<#_trait_AttributeTypeAPI_tymethod_value_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
ValueType
----

[#_struct_AttributeType_method_put]
==== put

[source,rust]
----
fn put(&self, transaction: &Transaction<'_>, value: Value) -> Result<Attribute>
----

<<#_trait_AttributeTypeAPI_method_put,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Attribute>
----

[#_struct_AttributeType_method_get]
==== get

[source,rust]
----
fn get(
    &self,
    transaction: &Transaction<'_>,
    value: Value
) -> Result<Option<Attribute>>
----

<<#_trait_AttributeTypeAPI_method_get,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Option<Attribute>>
----

[#_struct_AttributeType_method_get_supertype]
==== get_supertype

[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<AttributeType>>
----

<<#_trait_AttributeTypeAPI_method_get_supertype,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Option<AttributeType>>
----

[#_struct_AttributeType_method_set_supertype]
==== set_supertype

[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: AttributeType
) -> Result
----

<<#_trait_AttributeTypeAPI_method_set_supertype,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_get_supertypes]
==== get_supertypes

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_supertypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_AttributeType_method_get_subtypes]
==== get_subtypes

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_subtypes,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_AttributeType_method_get_subtypes_with_value_type]
==== get_subtypes_with_value_type

[source,rust]
----
fn get_subtypes_with_value_type(
    &self,
    transaction: &Transaction<'_>,
    value_type: ValueType,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

<<#_trait_AttributeTypeAPI_method_get_subtypes_with_value_type,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_AttributeType_method_get_instances]
==== get_instances

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Attribute>>>
----

<<#_trait_AttributeTypeAPI_method_get_instances,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Attribute>>>
----

[#_struct_AttributeType_method_get_regex]
==== get_regex

[source,rust]
----
fn get_regex(&self, transaction: &Transaction<'_>) -> Result<Option<String>>
----

<<#_trait_AttributeTypeAPI_method_get_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Option<String>>
----

[#_struct_AttributeType_method_set_regex]
==== set_regex

[source,rust]
----
fn set_regex(&self, transaction: &Transaction<'_>, regex: String) -> Result
----

<<#_trait_AttributeTypeAPI_method_set_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_unset_regex]
==== unset_regex

[source,rust]
----
fn unset_regex(&self, transaction: &Transaction<'_>) -> Result
----

<<#_trait_AttributeTypeAPI_method_unset_regex,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_get_owners]
==== get_owners

[source,rust]
----
fn get_owners(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<ThingType>>>
----

<<#_trait_AttributeTypeAPI_method_get_owners,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<ThingType>>>
----

[#_struct_AttributeType_tymethod_label]
==== label

[source,rust]
----
fn label(&self) -> &str
----

<<#_trait_ThingTypeAPI_tymethod_label,Read more>>

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_AttributeType_tymethod_is_abstract]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

<<#_trait_ThingTypeAPI_tymethod_is_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_AttributeType_tymethod_is_root]
==== is_root

[source,rust]
----
fn is_root(&self) -> bool
----

<<#_trait_ThingTypeAPI_tymethod_is_root,Read more>>

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_AttributeType_tymethod_is_deleted]
==== is_deleted

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

<<#_trait_ThingTypeAPI_tymethod_is_deleted,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[#_struct_AttributeType_method_delete]
==== delete

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

<<#_trait_ThingTypeAPI_method_delete,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_set_label]
==== set_label

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

<<#_trait_ThingTypeAPI_method_set_label,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_set_abstract]
==== set_abstract

[source,rust]
----
fn set_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

<<#_trait_ThingTypeAPI_method_set_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_unset_abstract]
==== unset_abstract

[source,rust]
----
fn unset_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

<<#_trait_ThingTypeAPI_method_unset_abstract,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_get_owns]
==== get_owns

[source,rust]
----
fn get_owns(
    &self,
    transaction: &Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

<<#_trait_ThingTypeAPI_method_get_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_AttributeType_method_get_owns_overridden]
==== get_owns_overridden

[source,rust]
----
fn get_owns_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> Result<Option<AttributeType>>
----

<<#_trait_ThingTypeAPI_method_get_owns_overridden,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Option<AttributeType>>
----

[#_struct_AttributeType_method_set_owns]
==== set_owns

[source,rust]
----
fn set_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> Result
----

<<#_trait_ThingTypeAPI_method_set_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_unset_owns]
==== unset_owns

[source,rust]
----
fn unset_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType
) -> Result
----

<<#_trait_ThingTypeAPI_method_unset_owns,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_get_plays]
==== get_plays

[source,rust]
----
fn get_plays(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

<<#_trait_ThingTypeAPI_method_get_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[#_struct_AttributeType_method_get_plays_overridden]
==== get_plays_overridden

[source,rust]
----
fn get_plays_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_type: RoleType
) -> Result<Option<RoleType>>
----

<<#_trait_ThingTypeAPI_method_get_plays_overridden,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_AttributeType_method_set_plays]
==== set_plays

[source,rust]
----
fn set_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> Result
----

<<#_trait_ThingTypeAPI_method_set_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_unset_plays]
==== unset_plays

[source,rust]
----
fn unset_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType
) -> Result
----

<<#_trait_ThingTypeAPI_method_unset_plays,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result
----

[#_struct_AttributeType_method_get_syntax]
==== get_syntax

[source,rust]
----
fn get_syntax(&self, transaction: &Transaction<'_>) -> Result<String>
----

<<#_trait_ThingTypeAPI_method_get_syntax,Read more>>

[caption=""]
.Returns
[source,rust]
----
Result<String>
----

// end::methods[]

