[#_struct_ConceptMap]
= ConceptMap

*Implements traits:*

* `Clone`
* `Debug`
* `From<ConceptMap>`
* `Index<String>`
* `IntoIterator`
* `PartialEq<ConceptMap>`
* `StructuralPartialEq`

== Description

Contains a mapping of variables to concepts.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `map` a| `HashMap<String, Concept>` a| The `HashMap` where keys are query variables, and values are concepts.
a| `explainables` a| `Explainables` a| The `Explainables` object for this `ConceptMap`, that exposes which of the concepts in this `ConceptMap` are explainable.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_struct_ConceptMap_method_get]
=== get

==== Signature

[source,rust]
----
pub fn get(&self, var_name: &str) -> Option<&Concept>
----

==== Description

Retrieves a concept for a given variable name.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `var_name` a| The string representation of a variable a| `&str` 
|===

==== Returns

[source,rust]
----
Option<&Concept>
----

==== Code examples

[source,rust]
----
concept_map.get(var_name)
----

[#_struct_ConceptMap_method_concepts]
=== concepts

==== Signature

[source,rust]
----
pub fn concepts(&self) -> impl Iterator<Item = &Concept>
----

==== Description

Produces an iterator over all concepts in this `ConceptMap`.

==== Returns

[source,rust]
----
impl Iterator<Item = &Concept>
----

==== Code examples

[source,rust]
----
concept_map.concepts()
----

// end::methods[]
