[#_struct_Credential]
= Credential

*Implements traits:*

* `Clone`
* `Debug`

== Methods

// tag::methods[]
[#_struct_Credential_method_with_tls]
=== with_tls

==== Signature

[source,rust]
----
pub fn with_tls(
    username: &str,
    password: &str,
    tls_root_ca: Option<&Path>
) -> Result<Self>
----

==== Description

Creates a credential with username and password. Specifies the connection must use TLS

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `&str` 
a| `password` a| The password for the user a| `&str` 
a| `tls_root_ca` a| Path to the CA certificate to use for authenticating server certificates. a| `Option<&Path>` 
|===

==== Returns

[source,rust]
----
Result<Self>
----

==== Code examples

[source,rust]
----
Credential::with_tls(username, password, Some(&path_to_ca));
----

[#_struct_Credential_method_without_tls]
=== without_tls

==== Signature

[source,rust]
----
pub fn without_tls(username: &str, password: &str) -> Self
----

==== Description

Creates a credential with username and password. The connection will not use TLS

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `&str` 
a| `password` a| The password for the user a| `&str` 
|===

==== Returns

[source,rust]
----
Self
----

==== Code examples

[source,rust]
----
Credential::without_tls(username, password);
----

[#_struct_Credential_method_username]
=== username

==== Signature

[source,rust]
----
pub fn username(&self) -> &str
----

==== Description

Retrieves the username used.

==== Returns

[source,rust]
----
&str
----

[#_struct_Credential_method_password]
=== password

==== Signature

[source,rust]
----
pub fn password(&self) -> &str
----

==== Description

Retrieves the password used.

==== Returns

[source,rust]
----
&str
----

[#_struct_Credential_method_is_tls_enabled]
=== is_tls_enabled

==== Signature

[source,rust]
----
pub fn is_tls_enabled(&self) -> bool
----

==== Description

Retrieves whether TLS is enabled for the connection.

==== Returns

[source,rust]
----
bool
----

// end::methods[]
