[#_struct_EntityType]
= EntityType

*Implements traits:*

* `Clone`
* `Debug`
* `EntityTypeAPI`
* `Eq`
* `PartialEq<EntityType>`
* `StructuralEq`
* `StructuralPartialEq`
* `ThingTypeAPI`

== Description

Entity types represent the classification of independent objects in the data model of the business domain.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `String` a| 
a| `is_root` a| `bool` a| 
a| `is_abstract` a| `bool` a| 
|===
// end::properties[]

== Methods

// tag::methods[]
[#_struct_EntityType_method_create]
=== create

==== Signature

[source,rust]
----
fn create(&self, transaction: &Transaction<'_>) -> Result<Entity>
----

==== Description

<<#_trait_EntityTypeAPI_method_create,Read more>>

==== Returns

[source,rust]
----
Result<Entity>
----

[#_struct_EntityType_method_get_supertype]
=== get_supertype

==== Signature

[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<EntityType>>
----

==== Description

<<#_trait_EntityTypeAPI_method_get_supertype,Read more>>

==== Returns

[source,rust]
----
Result<Option<EntityType>>
----

[#_struct_EntityType_method_set_supertype]
=== set_supertype

==== Signature

[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: EntityType
) -> Result
----

==== Description

<<#_trait_EntityTypeAPI_method_set_supertype,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_get_supertypes]
=== get_supertypes

==== Signature

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<EntityType>>>
----

==== Description

<<#_trait_EntityTypeAPI_method_get_supertypes,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

[#_struct_EntityType_method_get_subtypes]
=== get_subtypes

==== Signature

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<EntityType>>>
----

==== Description

<<#_trait_EntityTypeAPI_method_get_subtypes,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

[#_struct_EntityType_method_get_instances]
=== get_instances

==== Signature

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Entity>>>
----

==== Description

<<#_trait_EntityTypeAPI_method_get_instances,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Entity>>>
----

[#_struct_EntityType_tymethod_label]
=== label

==== Signature

[source,rust]
----
fn label(&self) -> &str
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_label,Read more>>

==== Returns

[source,rust]
----
&str
----

[#_struct_EntityType_tymethod_is_abstract]
=== is_abstract

==== Signature

[source,rust]
----
fn is_abstract(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_abstract,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_EntityType_tymethod_is_root]
=== is_root

==== Signature

[source,rust]
----
fn is_root(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_root,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_EntityType_tymethod_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_deleted,Read more>>

==== Returns

[source,rust]
----
Result<bool>
----

[#_struct_EntityType_method_delete]
=== delete

==== Signature

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_delete,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_set_label]
=== set_label

==== Signature

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_label,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_set_abstract]
=== set_abstract

==== Signature

[source,rust]
----
fn set_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_unset_abstract]
=== unset_abstract

==== Signature

[source,rust]
----
fn unset_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_get_owns]
=== get_owns

==== Signature

[source,rust]
----
fn get_owns(
    &self,
    transaction: &Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_EntityType_method_get_owns_overridden]
=== get_owns_overridden

==== Signature

[source,rust]
----
fn get_owns_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> Result<Option<AttributeType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<AttributeType>>
----

[#_struct_EntityType_method_set_owns]
=== set_owns

==== Signature

[source,rust]
----
fn set_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_unset_owns]
=== unset_owns

==== Signature

[source,rust]
----
fn unset_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_get_plays]
=== get_plays

==== Signature

[source,rust]
----
fn get_plays(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[#_struct_EntityType_method_get_plays_overridden]
=== get_plays_overridden

==== Signature

[source,rust]
----
fn get_plays_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_type: RoleType
) -> Result<Option<RoleType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_EntityType_method_set_plays]
=== set_plays

==== Signature

[source,rust]
----
fn set_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_unset_plays]
=== unset_plays

==== Signature

[source,rust]
----
fn unset_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_EntityType_method_get_syntax]
=== get_syntax

==== Signature

[source,rust]
----
fn get_syntax(&self, transaction: &Transaction<'_>) -> Result<String>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_syntax,Read more>>

==== Returns

[source,rust]
----
Result<String>
----

// end::methods[]
