[#_struct_RelationType]
= RelationType

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq<RelationType>`
* `RelationTypeAPI`
* `StructuralEq`
* `StructuralPartialEq`
* `ThingTypeAPI`

== Description

Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles.

Other types can play roles in relations if it’s mentioned in their definition.

A relation type must specify at least one role.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `String` a| 
a| `is_root` a| `bool` a| 
a| `is_abstract` a| `bool` a| 
|===
// end::properties[]

== Methods

// tag::methods[]
[#_struct_RelationType_method_create]
=== create

==== Signature

[source,rust]
----
fn create(&self, transaction: &Transaction<'_>) -> Result<Relation>
----

==== Description

<<#_trait_RelationTypeAPI_method_create,Read more>>

==== Returns

[source,rust]
----
Result<Relation>
----

[#_struct_RelationType_method_get_supertype]
=== get_supertype

==== Signature

[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<RelationType>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_supertype,Read more>>

==== Returns

[source,rust]
----
Result<Option<RelationType>>
----

[#_struct_RelationType_method_set_supertype]
=== set_supertype

==== Signature

[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: RelationType
) -> Result
----

==== Description

<<#_trait_RelationTypeAPI_method_set_supertype,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_get_supertypes]
=== get_supertypes

==== Signature

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RelationType>>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_supertypes,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RelationType>>>
----

[#_struct_RelationType_method_get_subtypes]
=== get_subtypes

==== Signature

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RelationType>>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_subtypes,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RelationType>>>
----

[#_struct_RelationType_method_get_instances]
=== get_instances

==== Signature

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Relation>>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_instances,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Relation>>>
----

[#_struct_RelationType_method_get_relates]
=== get_relates

==== Signature

[source,rust]
----
fn get_relates(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_relates,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[#_struct_RelationType_method_get_relates_for_role_label]
=== get_relates_for_role_label

==== Signature

[source,rust]
----
fn get_relates_for_role_label(
    &self,
    transaction: &Transaction<'_>,
    role_label: String
) -> Result<Option<RoleType>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_relates_for_role_label,Read more>>

==== Returns

[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_RelationType_method_get_relates_overridden]
=== get_relates_overridden

==== Signature

[source,rust]
----
fn get_relates_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_label: String
) -> Result<Option<RoleType>>
----

==== Description

<<#_trait_RelationTypeAPI_method_get_relates_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_RelationType_method_set_relates]
=== set_relates

==== Signature

[source,rust]
----
fn set_relates(
    &mut self,
    transaction: &Transaction<'_>,
    role_label: String,
    overridden_role_label: Option<String>
) -> Result
----

==== Description

<<#_trait_RelationTypeAPI_method_set_relates,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_unset_relates]
=== unset_relates

==== Signature

[source,rust]
----
fn unset_relates(
    &mut self,
    transaction: &Transaction<'_>,
    role_label: String
) -> Result
----

==== Description

<<#_trait_RelationTypeAPI_method_unset_relates,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_tymethod_label]
=== label

==== Signature

[source,rust]
----
fn label(&self) -> &str
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_label,Read more>>

==== Returns

[source,rust]
----
&str
----

[#_struct_RelationType_tymethod_is_abstract]
=== is_abstract

==== Signature

[source,rust]
----
fn is_abstract(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_abstract,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_RelationType_tymethod_is_root]
=== is_root

==== Signature

[source,rust]
----
fn is_root(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_root,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_RelationType_tymethod_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_deleted,Read more>>

==== Returns

[source,rust]
----
Result<bool>
----

[#_struct_RelationType_method_delete]
=== delete

==== Signature

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_delete,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_set_label]
=== set_label

==== Signature

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_label,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_set_abstract]
=== set_abstract

==== Signature

[source,rust]
----
fn set_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_unset_abstract]
=== unset_abstract

==== Signature

[source,rust]
----
fn unset_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_get_owns]
=== get_owns

==== Signature

[source,rust]
----
fn get_owns(
    &self,
    transaction: &Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_RelationType_method_get_owns_overridden]
=== get_owns_overridden

==== Signature

[source,rust]
----
fn get_owns_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> Result<Option<AttributeType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<AttributeType>>
----

[#_struct_RelationType_method_set_owns]
=== set_owns

==== Signature

[source,rust]
----
fn set_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_unset_owns]
=== unset_owns

==== Signature

[source,rust]
----
fn unset_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_get_plays]
=== get_plays

==== Signature

[source,rust]
----
fn get_plays(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[#_struct_RelationType_method_get_plays_overridden]
=== get_plays_overridden

==== Signature

[source,rust]
----
fn get_plays_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_type: RoleType
) -> Result<Option<RoleType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_RelationType_method_set_plays]
=== set_plays

==== Signature

[source,rust]
----
fn set_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_unset_plays]
=== unset_plays

==== Signature

[source,rust]
----
fn unset_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RelationType_method_get_syntax]
=== get_syntax

==== Signature

[source,rust]
----
fn get_syntax(&self, transaction: &Transaction<'_>) -> Result<String>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_syntax,Read more>>

==== Returns

[source,rust]
----
Result<String>
----

// end::methods[]
