[#_struct_RootThingType]
= RootThingType

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq<RootThingType>`
* `StructuralEq`
* `StructuralPartialEq`
* `ThingTypeAPI`

== Methods

// tag::methods[]
[#_struct_RootThingType_tymethod_label]
=== label

==== Signature

[source,rust]
----
fn label(&self) -> &str
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_label,Read more>>

==== Returns

[source,rust]
----
&str
----

[#_struct_RootThingType_tymethod_is_abstract]
=== is_abstract

==== Signature

[source,rust]
----
fn is_abstract(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_abstract,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_RootThingType_tymethod_is_root]
=== is_root

==== Signature

[source,rust]
----
fn is_root(&self) -> bool
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_root,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_RootThingType_tymethod_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted(&self, _transaction: &Transaction<'_>) -> Result<bool>
----

==== Description

<<#_trait_ThingTypeAPI_tymethod_is_deleted,Read more>>

==== Returns

[source,rust]
----
Result<bool>
----

[#_struct_RootThingType_method_delete]
=== delete

==== Signature

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_delete,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_set_label]
=== set_label

==== Signature

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_label,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_set_abstract]
=== set_abstract

==== Signature

[source,rust]
----
fn set_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_unset_abstract]
=== unset_abstract

==== Signature

[source,rust]
----
fn unset_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_abstract,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_get_owns]
=== get_owns

==== Signature

[source,rust]
----
fn get_owns(
    &self,
    transaction: &Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[#_struct_RootThingType_method_get_owns_overridden]
=== get_owns_overridden

==== Signature

[source,rust]
----
fn get_owns_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> Result<Option<AttributeType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_owns_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<AttributeType>>
----

[#_struct_RootThingType_method_set_owns]
=== set_owns

==== Signature

[source,rust]
----
fn set_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_unset_owns]
=== unset_owns

==== Signature

[source,rust]
----
fn unset_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_owns,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_get_plays]
=== get_plays

==== Signature

[source,rust]
----
fn get_plays(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

[#_struct_RootThingType_method_get_plays_overridden]
=== get_plays_overridden

==== Signature

[source,rust]
----
fn get_plays_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_type: RoleType
) -> Result<Option<RoleType>>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_plays_overridden,Read more>>

==== Returns

[source,rust]
----
Result<Option<RoleType>>
----

[#_struct_RootThingType_method_set_plays]
=== set_plays

==== Signature

[source,rust]
----
fn set_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_set_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_unset_plays]
=== unset_plays

==== Signature

[source,rust]
----
fn unset_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType
) -> Result
----

==== Description

<<#_trait_ThingTypeAPI_method_unset_plays,Read more>>

==== Returns

[source,rust]
----
Result
----

[#_struct_RootThingType_method_get_syntax]
=== get_syntax

==== Signature

[source,rust]
----
fn get_syntax(&self, transaction: &Transaction<'_>) -> Result<String>
----

==== Description

<<#_trait_ThingTypeAPI_method_get_syntax,Read more>>

==== Returns

[source,rust]
----
Result<String>
----

// end::methods[]
