[#_struct_Session]
= Session

*Implements traits:*

* `Debug`
* `Drop`

== Methods

// tag::methods[]
[#_struct_Session_method_new]
=== new

==== Signature

[source,rust]
----
pub fn new(database: Database, session_type: SessionType) -> Result<Self>
----

==== Description

Opens a communication tunnel (session) to the given database with default options. See <<#_struct_Session_method_new_with_options,`Session::new_with_options`>>

==== Returns

[source,rust]
----
Result<Self>
----

[#_struct_Session_method_new_with_options]
=== new_with_options

==== Signature

[source,rust]
----
pub fn new_with_options(
    database: Database,
    session_type: SessionType,
    options: Options
) -> Result<Self>
----

==== Description

Opens a communication tunnel (session) to the given database on the running TypeDB server.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The database with which the session connects a| `Database` 
a| `session_type` a| The type of session to be created (DATA or SCHEMA) a| `SessionType` 
a| `options` a| `TypeDBOptions` for the session a| `Options` 
|===

==== Returns

[source,rust]
----
Result<Self>
----

==== Code examples

[source,rust]
----
Session::new_with_options(database, session_type, options);
----

[#_struct_Session_method_database_name]
=== database_name

==== Signature

[source,rust]
----
pub fn database_name(&self) -> &str
----

==== Description

Returns the name of the database of the session.

==== Returns

[source,rust]
----
&str
----

==== Code examples

[source,rust]
----
session.database_name();
----

[#_struct_Session_method_type]
=== type_

==== Signature

[source,rust]
----
pub fn type_(&self) -> SessionType
----

==== Description

The current session’s type (SCHEMA or DATA)

==== Returns

[source,rust]
----
SessionType
----

[#_struct_Session_method_is_open]
=== is_open

==== Signature

[source,rust]
----
pub fn is_open(&self) -> bool
----

==== Description

Checks whether this session is open.

==== Returns

[source,rust]
----
bool
----

==== Code examples

[source,rust]
----
session.is_open();
----

[#_struct_Session_method_force_close]
=== force_close

==== Signature

[source,rust]
----
pub fn force_close(&self) -> Result
----

==== Description

Closes the session. Before opening a new session, the session currently open should first be closed.

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
session.force_close();
----

[#_struct_Session_method_on_close]
=== on_close

==== Signature

[source,rust]
----
pub fn on_close(&self, callback: impl FnOnce() + Send + 'static)
----

==== Description

Registers a callback function which will be executed when this session is closed.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

==== Returns

[source,rust]
----
null
----

==== Code examples

[source,rust]
----
session.on_close(function);
----

[#_struct_Session_method_transaction]
=== transaction

==== Signature

[source,rust]
----
pub fn transaction(
    &self,
    transaction_type: TransactionType
) -> Result<Transaction<'_>>
----

==== Description

Opens a transaction to perform read or write queries on the database connected to the session. See <<#_struct_Session_method_transaction_with_options,`Session::transaction_with_options`>>

==== Returns

[source,rust]
----
Result<Transaction<'_>>
----

[#_struct_Session_method_transaction_with_options]
=== transaction_with_options

==== Signature

[source,rust]
----
pub fn transaction_with_options(
    &self,
    transaction_type: TransactionType,
    options: Options
) -> Result<Transaction<'_>>
----

==== Description

Opens a transaction to perform read or write queries on the database connected to the session.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction_type` a| The type of transaction to be created (READ or WRITE) a| `TransactionType` 
a| `options` a| Options for the session a| `Options` 
|===

==== Returns

[source,rust]
----
Result<Transaction<'_>>
----

==== Code examples

[source,rust]
----
session.transaction_with_options(transaction_type, options);
----

// end::methods[]
