[#_trait_ThingTypeAPI]
=== Trait ThingTypeAPI

// tag::methods[]
[#_trait_ThingTypeAPI_tymethod_label]
==== label

[source,rust]
----
fn label(&self) -> &str
----

Retrieves the unique label of the type.

.Returns
[source,rust]
----
&str
----

.Code examples
[source,rust]
----
thing_type.label();
----

[#_trait_ThingTypeAPI_tymethod_is_abstract]
==== is_abstract

[source,rust]
----
fn is_abstract(&self) -> bool
----

Checks if the type is prevented from having data instances (i.e. ``abstract``).

.Returns
[source,rust]
----
bool
----

.Code examples
[source,rust]
----
thing_type.is_abstract();
----

[#_trait_ThingTypeAPI_tymethod_is_root]
==== is_root

[source,rust]
----
fn is_root(&self) -> bool
----

Checks if the type is a root type.

.Returns
[source,rust]
----
bool
----

.Code examples
[source,rust]
----
thing_type.is_root();
----

[#_trait_ThingTypeAPI_tymethod_is_deleted]
==== is_deleted

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

Checks if this type is deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result<bool>
----

.Code examples
[source,rust]
----
thing_type.is_deleted(transaction);
----

[#_trait_ThingTypeAPI_method_delete]
==== delete

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.delete(transaction);
----

[#_trait_ThingTypeAPI_method_set_label]
==== set_label

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `new_label` a| The new ``Label`` to be given to the type. a| `String` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.set_label(transaction, new_label);
----

[#_trait_ThingTypeAPI_method_set_abstract]
==== set_abstract

[source,rust]
----
fn set_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

Set a type to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.set_abstract(transaction);
----

[#_trait_ThingTypeAPI_method_unset_abstract]
==== unset_abstract

[source,rust]
----
fn unset_abstract(&mut self, transaction: &Transaction<'_>) -> Result
----

Set a type to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.unset_abstract(transaction);
----

[#_trait_ThingTypeAPI_method_get_owns]
==== get_owns

[source,rust]
----
fn get_owns(
    &self,
    transaction: &Transaction<'_>,
    value_type: Option<ValueType>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `value_type` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Option<ValueType>` 
a| `transitivity` a| ``Transitivity::Transitive`` for direct and inherited ownership, ``Transitivity::Explicit`` for direct ownership only a| `Transitivity` 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Vec<Annotation>` 
|===

.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

.Code examples
[source,rust]
----
thing_type.get_owns(transaction, Some(value_type), Transitivity::Explicit, vec![Annotation::Key]);
----

[#_trait_ThingTypeAPI_method_get_owns_overridden]
==== get_owns_overridden

[source,rust]
----
fn get_owns_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_attribute_type: AttributeType
) -> Result<Option<AttributeType>>
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `overridden_attribute_type` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType` 
|===

.Returns
[source,rust]
----
Result<Option<AttributeType>>
----

.Code examples
[source,rust]
----
thing_type.get_owns_overridden(transaction, attribute_type);
----

[#_trait_ThingTypeAPI_method_set_owns]
==== set_owns

[source,rust]
----
fn set_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType,
    overridden_attribute_type: Option<AttributeType>,
    annotations: Vec<Annotation>
) -> Result
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute_type` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType` 
a| `overridden_attribute_type` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `Option<AttributeType>` 
a| `annotations` a| Adds annotations to the ownership. a| `Vec<Annotation>` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.set_owns(transaction, attribute_type, Some(overridden_type), vec![Annotation::Key]);
----

[#_trait_ThingTypeAPI_method_unset_owns]
==== unset_owns

[source,rust]
----
fn unset_owns(
    &mut self,
    transaction: &Transaction<'_>,
    attribute_type: AttributeType
) -> Result
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute_type` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.unset_owns(transaction, attribute_type);
----

[#_trait_ThingTypeAPI_method_get_plays]
==== get_plays

[source,rust]
----
fn get_plays(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<RoleType>>>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect playing, ``Transitivity::Explicit`` for direct playing only a| `Transitivity` 
|===

.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

.Code examples
[source,rust]
----
thing_type.get_plays(transaction, Transitivity::Explicit);
----

[#_trait_ThingTypeAPI_method_get_plays_overridden]
==== get_plays_overridden

[source,rust]
----
fn get_plays_overridden(
    &self,
    transaction: &Transaction<'_>,
    overridden_role_type: RoleType
) -> Result<Option<RoleType>>
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `overridden_role_type` a| The ``RoleType`` that overrides an inherited role a| `RoleType` 
|===

.Returns
[source,rust]
----
Result<Option<RoleType>>
----

.Code examples
[source,rust]
----
thing_type.get_plays_overridden(transaction, role_type);
----

[#_trait_ThingTypeAPI_method_set_plays]
==== set_plays

[source,rust]
----
fn set_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType,
    overridden_role_type: Option<RoleType>
) -> Result
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `role_type` a| The role to be played by the instances of this type a| `RoleType` 
a| `overridden_role_type` a| The role type that this role overrides, if applicable a| `Option<RoleType>` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.set_plays(transaction, role_type, None);
----

[#_trait_ThingTypeAPI_method_unset_plays]
==== unset_plays

[source,rust]
----
fn unset_plays(
    &mut self,
    transaction: &Transaction<'_>,
    role_type: RoleType
) -> Result
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `role_type` a| The role to not be played by the instances of this type. a| `RoleType` 
|===

.Returns
[source,rust]
----
Result
----

.Code examples
[source,rust]
----
thing_type.unset_plays(transaction, role_type);
----

[#_trait_ThingTypeAPI_method_get_syntax]
==== get_syntax

[source,rust]
----
fn get_syntax(&self, transaction: &Transaction<'_>) -> Result<String>
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result<String>
----

.Code examples
[source,rust]
----
thing_type.get_syntax(transaction);
----

// end::methods[]
