[#_trait_AttributeTypeAPI]
=== Trait AttributeTypeAPI

// tag::methods[]
[#_trait_AttributeTypeAPI_tymethod_value_type]
==== value_type

[source,rust]
----
fn value_type(&self) -> ValueType
----

Retrieves the ``ValueType`` of this ``AttributeType``.

[caption=""]
.Returns
[source,rust]
----
ValueType
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.value_type()
----

[#_trait_AttributeTypeAPI_method_put]
==== put

[source,rust]
----
fn put(&self, transaction: &Transaction<'_>, value: Value) -> Result<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `value` a| New ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Attribute>
----

[caption=""]
.Code examples
[source,rust]
----
attribute = attribute_type.put(transaction, value);
----

[#_trait_AttributeTypeAPI_method_get]
==== get

[source,rust]
----
fn get(
    &self,
    transaction: &Transaction<'_>,
    value: Value
) -> Result<Option<Attribute>>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `value` a| ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<Attribute>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute = attribute_type.get(transaction, value);
----

[#_trait_AttributeTypeAPI_method_get_supertype]
==== get_supertype

[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<AttributeType>>
----

Retrieves the most immediate supertype of this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<AttributeType>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_supertype(transaction);
----

[#_trait_AttributeTypeAPI_method_set_supertype]
==== set_supertype

[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: AttributeType
) -> Result
----

Sets the supplied ``AttributeType`` as the supertype of the current ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `supertype` a| The ``AttributeType`` to set as the supertype of this ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.set_supertype(transaction, supertype);
----

[#_trait_AttributeTypeAPI_method_get_supertypes]
==== get_supertypes

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

Retrieves all supertypes of this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_supertypes(transaction)
----

[#_trait_AttributeTypeAPI_method_get_subtypes]
==== get_subtypes

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_subtypes(transaction, transitivity)
----

[#_trait_AttributeTypeAPI_method_get_subtypes_with_value_type]
==== get_subtypes_with_value_type

[source,rust]
----
fn get_subtypes_with_value_type(
    &self,
    transaction: &Transaction<'_>,
    value_type: ValueType,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<AttributeType>>>
----

Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType`` with given ``ValueType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `value_type` a| ``ValueType`` for retrieving subtypes a| `ValueType`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<AttributeType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_subtypes_with_value_type(transaction, value_type, transitivity)
----

[#_trait_AttributeTypeAPI_method_get_instances]
==== get_instances

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Attribute>>>
----

Retrieves all direct and indirect (or direct only) ``Attributes`` that are instances of this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Attribute>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_instances(transaction, transitivity)
----

[#_trait_AttributeTypeAPI_method_get_regex]
==== get_regex

[source,rust]
----
fn get_regex(&self, transaction: &Transaction<'_>) -> Result<Option<String>>
----

Retrieves the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<String>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_regex(transaction);
----

[#_trait_AttributeTypeAPI_method_set_regex]
==== set_regex

[source,rust]
----
fn set_regex(&self, transaction: &Transaction<'_>, regex: String) -> Result
----

Sets a regular expression as a constraint for this ``AttributeType``. ``Values`` of all ``Attribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``AttributeType``s with a ``string`` value type.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `regex` a| Regular expression a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.set_regex(transaction, regex);
----

[#_trait_AttributeTypeAPI_method_unset_regex]
==== unset_regex

[source,rust]
----
fn unset_regex(&self, transaction: &Transaction<'_>) -> Result
----

Removes the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.unset_regex(transaction);
----

[#_trait_AttributeTypeAPI_method_get_owners]
==== get_owners

[source,rust]
----
fn get_owners(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<ThingType>>>
----

Retrieve all ``Things`` that own an attribute of this ``AttributeType`` and have all given ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>`
a| `transitivity` a| ``Transitivity::Transitive`` for direct and inherited ownership, ``Transitivity::Explicit`` for direct ownership only a| `Transitivity`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``AttributeType`` with all given ``Annotation``s a| `Vec<Annotation>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<BoxStream<'_, Result<ThingType>>>
----

[caption=""]
.Code examples
[source,rust]
----
attribute_type.get_owners(transaction, transitivity, annotations)
----

// end::methods[]

