[#_trait_ThingAPI]
= Trait ThingAPI

== Methods

// tag::methods[]
[#_trait_ThingAPI_tymethod_iid]
=== iid

==== Signature

[source,rust]
----
fn iid(&self) -> &IID
----

==== Description

Retrieves the unique id of the `Thing`.

==== Returns

[source,rust]
----
&IID
----

==== Code examples

[source,rust]
----
thing.iid();
----

[#_trait_ThingAPI_tymethod_is_inferred]
=== is_inferred

==== Signature

[source,rust]
----
fn is_inferred(&self) -> bool
----

==== Description

Checks if this `Thing` is inferred by a [Reasoning Rule].

==== Returns

[source,rust]
----
bool
----

==== Code examples

[source,rust]
----
thing.is_inferred();
----

[#_trait_ThingAPI_tymethod_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

==== Description

Checks if this `Thing` is deleted.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<bool>
----

==== Code examples

[source,rust]
----
thing.is_deleted(transaction);
----

[#_trait_ThingAPI_method_delete]
=== delete

==== Signature

[source,rust]
----
fn delete(&self, transaction: &Transaction<'_>) -> Result
----

==== Description

Deletes this `Thing`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
thing.delete(transaction);
----

[#_trait_ThingAPI_method_get_has]
=== get_has

==== Signature

[source,rust]
----
fn get_has(
    &self,
    transaction: &Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<Attribute>>>
----

==== Description

Retrieves the `Attribute`s that this `Thing` owns. Optionally, filtered by an `AttributeType` or a list of `AttributeType`s. Optionally, filtered by `Annotation`s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute_type` a| The `AttributeType` to filter the attributes by a| 
a| `attribute_types` a| The `AttributeType`s to filter the attributes by a| `Vec<AttributeType>` 
a| `annotations` a| Only retrieve attributes with all given `Annotation`s a| `Vec<Annotation>` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Attribute>>>
----

==== Code examples

[source,rust]
----
thing.get_has(transaction, attribute_type, annotations=vec![Annotation::Key]);
----

[#_trait_ThingAPI_method_set_has]
=== set_has

==== Signature

[source,rust]
----
fn set_has(&self, transaction: &Transaction<'_>, attribute: Attribute) -> Result
----

==== Description

Assigns an `Attribute` to be owned by this `Thing`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute` a| The `Attribute` to be owned by this `Thing`. a| `Attribute` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
thing.set_has(transaction, attribute);
----

[#_trait_ThingAPI_method_unset_has]
=== unset_has

==== Signature

[source,rust]
----
fn unset_has(&self, transaction: &Transaction<'_>, attribute: Attribute) -> Result
----

==== Description

Unassigns an `Attribute` from this `Thing`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute` a| The `Attribute` to be disowned from this `Thing`. a| `Attribute` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
thing.unset_has(transaction, attribute);
----

[#_trait_ThingAPI_method_get_relations]
=== get_relations

==== Signature

[source,rust]
----
fn get_relations(
    &self,
    transaction: &Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'_, Result<Relation>>>
----

==== Description

Retrieves all the `Relations` which this `Thing` plays a role in, optionally filtered by one or more given roles.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `role_types` a| The list of roles to filter the relations by. a| `Vec<RoleType>` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Relation>>>
----

==== Code examples

[source,rust]
----
thing.get_relations(transaction, role_types);
----

[#_trait_ThingAPI_method_get_playing]
=== get_playing

==== Signature

[source,rust]
----
fn get_playing(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

Retrieves the roles that this `Thing` is currently playing.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

==== Code examples

[source,rust]
----
thing.get_playing(transaction);
----

// end::methods[]
