[#_trait_EntityTypeAPI]
= Trait EntityTypeAPI

== Methods

// tag::methods[]
[#_trait_EntityTypeAPI_method_create]
=== create

==== Signature

[source,rust]
----
fn create(&self, transaction: &Transaction<'_>) -> Result<Entity>
----

==== Description

Creates and returns a new instance of this ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<Entity>
----

==== Code examples

[source,rust]
----
entity_type.create(transaction);
----

[#_trait_EntityTypeAPI_method_get_supertype]
=== get_supertype

==== Signature

[source,rust]
----
fn get_supertype(
    &self,
    transaction: &Transaction<'_>
) -> Result<Option<EntityType>>
----

==== Description

Retrieves the most immediate supertype of the ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<Option<EntityType>>
----

==== Code examples

[source,rust]
----
entity_type.get_supertype(transaction);
----

[#_trait_EntityTypeAPI_method_set_supertype]
=== set_supertype

==== Signature

[source,rust]
----
fn set_supertype(
    &mut self,
    transaction: &Transaction<'_>,
    supertype: EntityType
) -> Result
----

==== Description

Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `supertype` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
entity_type.set_supertype(transaction, super_entity_type);
----

[#_trait_EntityTypeAPI_method_get_supertypes]
=== get_supertypes

==== Signature

[source,rust]
----
fn get_supertypes(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<EntityType>>>
----

==== Description

Retrieves all supertypes of the ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

==== Code examples

[source,rust]
----
entity_type.get_supertypes(transaction);
----

[#_trait_EntityTypeAPI_method_get_subtypes]
=== get_subtypes

==== Signature

[source,rust]
----
fn get_subtypes(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<EntityType>>>
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect subtypes, ``Transitivity::Explicit`` for direct subtypes only a| `Transitivity` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<EntityType>>>
----

==== Code examples

[source,rust]
----
entity_type.get_subtypes(transaction, transitivity);
----

[#_trait_EntityTypeAPI_method_get_instances]
=== get_instances

==== Signature

[source,rust]
----
fn get_instances(
    &self,
    transaction: &Transaction<'_>,
    transitivity: Transitivity
) -> Result<BoxStream<'_, Result<Entity>>>
----

==== Description

Retrieves all direct and indirect (or direct only) ``Entity`` objects that are instances of this ``EntityType``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `transitivity` a| ``Transitivity::Transitive`` for direct and indirect instances, ``Transitivity::Explicit`` for direct instances only a| `Transitivity` 
|===

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Entity>>>
----

==== Code examples

[source,rust]
----
entity_type.get_instances(transaction, Transitivity::Explicit);
----

// end::methods[]
