[#_trait_RuleAPI]
= Trait RuleAPI

== Methods

// tag::methods[]
[#_trait_RuleAPI_tymethod_label]
=== label

==== Signature

[source,rust]
----
fn label(&self) -> &String
----

==== Description

Retrieves the unique label of the rule.

==== Returns

[source,rust]
----
&String
----

[#_trait_RuleAPI_tymethod_delete]
=== delete

==== Signature

[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

==== Description

Deletes this rule.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
rule.delete(transaction);
----

[#_trait_RuleAPI_tymethod_set_label]
=== set_label

==== Signature

[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

==== Description

Renames the label of the rule. The new label must remain unique.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `&Transaction<'_>` 
a| `new_label` a| The new label to be given to the rule a| `String` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
rule.set_label(transaction, new_label);
----

[#_trait_RuleAPI_method_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

==== Description

Check if this rule has been deleted.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `&Transaction<'_>` 
|===

==== Returns

[source,rust]
----
Result<bool>
----

==== Code examples

[source,rust]
----
rule.is_deleted(transaction)
----

// end::methods[]
