[#_struct_UserManager]
=== UserManager

*Implements traits:*

* `Clone`
* `Debug`

Provides access to all user management methods.

// tag::methods[]
[#_struct_UserManager_method_current_user]
==== current_user

[source,rust]
----
pub fn current_user(&self) -> Result<Option<User>>
----

Returns the logged-in user for the connection.

[caption=""]
.Returns
[source,rust]
----
Result<Option<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.current_user().await;
----

[#_struct_UserManager_method_all]
==== all

[source,rust]
----
pub fn all(&self) -> Result<Vec<User>>
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
[source,rust]
----
Result<Vec<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.all().await;
----

[#_struct_UserManager_method_contains]
==== contains

[source,rust]
----
pub fn contains(&self, username: impl Into<String>) -> Result<bool>
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.contains(username).await;
----

[#_struct_UserManager_method_create]
==== create

[source,rust]
----
pub fn create(
    &self,
    username: impl Into<String>,
    password: impl Into<String>
) -> Result
----

Create a user with the given name &amp; password.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| `impl Into<String>`
a| `password` a| The password of the user to be created a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.create(username, password).await;
----

[#_struct_UserManager_method_delete]
==== delete

[source,rust]
----
pub fn delete(&self, username: impl Into<String>) -> Result
----

Deletes a user with the given name.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be deleted a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.delete(username).await;
----

[#_struct_UserManager_method_get]
==== get

[source,rust]
----
pub fn get(&self, username: impl Into<String>) -> Result<Option<User>>
----

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Option<User>>
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.get(username).await;
----

[#_struct_UserManager_method_set_password]
==== set_password

[source,rust]
----
pub fn set_password(
    &self,
    username: impl Into<String>,
    password: impl Into<String>
) -> Result
----

Sets a new password for a user. This operation can only be performed by administrators.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to set the password of a| `impl Into<String>`
a| `password` a| The new password a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
driver.users.password_set(username, password).await;
----

// end::methods[]

