[#_TypeDBOptions]
=== TypeDBOptions

TypeDB session and transaction options. ``TypeDBOptions`` object can be used to override the default server behaviour. Options could be specified either as constructor arguments or using setters.

// tag::methods[]
[#_TypeDBOptions_explain_]
====  explain

[source,nodejs]
----
get explain(): boolean
----

If set to ``True``, enables explanations for queries. Only affects read transactions.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_explain_value_boolean]
====  explain

[source,nodejs]
----
set explain(value): void
----

If set to ``True``, enables explanations for queries. Only affects read transactions.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_infer_]
====  infer

[source,nodejs]
----
get infer(): boolean
----

If set to ``True``, enables inference for queries. Only settable at transaction level and above. Only affects read transactions.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_infer_value_boolean]
====  infer

[source,nodejs]
----
set infer(value): void
----

If set to ``True``, enables inference for queries. Only settable at transaction level and above. Only affects read transactions.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_parallel_]
====  parallel

[source,nodejs]
----
get parallel(): boolean
----

If set to ``True``, the server uses parallel instead of single-threaded execution.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_parallel_value_boolean]
====  parallel

[source,nodejs]
----
set parallel(value): void
----

If set to ``True``, the server uses parallel instead of single-threaded execution.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_prefetch_]
====  prefetch

[source,nodejs]
----
get prefetch(): boolean
----

If set to ``True``, the first batch of answers is streamed to the driver even without an explicit request for it.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_prefetch_value_boolean]
====  prefetch

[source,nodejs]
----
set prefetch(value): void
----

If set to ``True``, the first batch of answers is streamed to the driver even without an explicit request for it.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_prefetchSize_]
====  prefetchSize

[source,nodejs]
----
get prefetchSize(): number
----

If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.

[caption=""]
.Returns
`number`

[#_TypeDBOptions_prefetchSize_value_number]
====  prefetchSize

[source,nodejs]
----
set prefetchSize(value): void
----

If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_readAnyReplica_]
====  readAnyReplica

[source,nodejs]
----
get readAnyReplica(): boolean
----

If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_readAnyReplica_value_boolean]
====  readAnyReplica

[source,nodejs]
----
set readAnyReplica(value): void
----

If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_schemaLockAcquireTimeoutMillis_]
====  schemaLockAcquireTimeoutMillis

[source,nodejs]
----
get schemaLockAcquireTimeoutMillis(): number
----

If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.

[caption=""]
.Returns
`number`

[#_TypeDBOptions_schemaLockAcquireTimeoutMillis_value_number]
====  schemaLockAcquireTimeoutMillis

[source,nodejs]
----
set schemaLockAcquireTimeoutMillis(value): void
----

If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_sessionIdleTimeoutMillis_]
====  sessionIdleTimeoutMillis

[source,nodejs]
----
get sessionIdleTimeoutMillis(): number
----

If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.

[caption=""]
.Returns
`number`

[#_TypeDBOptions_sessionIdleTimeoutMillis_millis_number]
====  sessionIdleTimeoutMillis

[source,nodejs]
----
set sessionIdleTimeoutMillis(millis): void
----

If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_traceInference_]
====  traceInference

[source,nodejs]
----
get traceInference(): boolean
----

If set to ``True``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.

[caption=""]
.Returns
`boolean`

[#_TypeDBOptions_traceInference_value_boolean]
====  traceInference

[source,nodejs]
----
set traceInference(value): void
----

If set to ``True``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_transactionTimeoutMillis_]
====  transactionTimeoutMillis

[source,nodejs]
----
get transactionTimeoutMillis(): number
----

If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
`number`

[#_TypeDBOptions_transactionTimeoutMillis_millis_number]
====  transactionTimeoutMillis

[source,nodejs]
----
set transactionTimeoutMillis(millis): void
----

If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
`void`

[#_TypeDBOptions_new_TypeDBOptions_obj_explain_boolean_infer_boolean_parallel_boolean_prefetch_boolean_prefetchSize_number_readAnyReplica_boolean_schemaLockAcquireTimeoutMillis_number_sessionIdleTimeoutMillis_number_traceInference_boolean_transactionTimeoutMillis_number_]
==== new TypeDBOptions

[source,nodejs]
----
new TypeDBOptions(obj?): TypeDBOptions
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `obj` a| If set to ``True``, enables explanations for queries. Only affects read transactions. a| `{ explain?: boolean; infer?: boolean; parallel?: boolean; prefetch?: boolean; prefetchSize?: number; readAnyReplica?: boolean; schemaLockAcquireTimeoutMillis?: number; sessionIdleTimeoutMillis?: number; traceInference?: boolean; transactionTimeoutMillis?: number; } = {}`
|===

[caption=""]
.Returns
`TypeDBOptions`

// end::methods[]

