# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

dir_mapping = {
    "AnalyzedQuery.adoc": "analyze",
    "Conjunction.adoc": "analyze",
    "Constraint.adoc": "analyze",
    "Constraint.Isa.adoc": "analyze",
    "Constraint.Has.adoc": "analyze",
    "Constraint.Links.adoc": "analyze",
    "Constraint.Sub.adoc": "analyze",
    "Constraint.Owns.adoc": "analyze",
    "Constraint.Relates.adoc": "analyze",
    "Constraint.Plays.adoc": "analyze",
    "Constraint.FunctionCall.adoc": "analyze",
    "Constraint.Expression.adoc": "analyze",
    "Constraint.Is.adoc": "analyze",
    "Constraint.Iid.adoc": "analyze",
    "Constraint.Comparison.adoc": "analyze",
    "Constraint.Kind.adoc": "analyze",
    "Constraint.Label.adoc": "analyze",
    "Constraint.Value.adoc": "analyze",
    "Constraint.Or.adoc": "analyze",
    "Constraint.Not.adoc": "analyze",
    "Constraint.Try.adoc": "analyze",
    "Constraint.Span.adoc": "analyze",
    "ConstraintVertex.adoc": "analyze",
    "Fetch.adoc": "analyze",
    "Fetch.FetchObject.adoc": "analyze",
    "Fetch.FetchList.adoc": "analyze",
    "Fetch.FetchLeaf.adoc": "analyze",
    "Function.adoc": "analyze",
    "Function.ReturnOperation.adoc": "analyze",
    "Function.ReturnOperation.Stream.adoc": "analyze",
    "Function.ReturnOperation.Single.adoc": "analyze",
    "Function.ReturnOperation.Check.adoc": "analyze",
    "Function.ReturnOperation.Reduce.adoc": "analyze",
    "Function.ReturnOperation.Reduce.ReduceAssignment.adoc": "analyze",
    "Pipeline.adoc": "analyze",
    "PipelineStage.adoc": "analyze",
    "PipelineStage.MatchStage.adoc": "analyze",
    "PipelineStage.InsertStage.adoc": "analyze",
    "PipelineStage.PutStage.adoc": "analyze",
    "PipelineStage.UpdateStage.adoc": "analyze",
    "PipelineStage.DeleteStage.adoc": "analyze",
    "PipelineStage.SelectStage.adoc": "analyze",
    "PipelineStage.SortStage.adoc": "analyze",
    "PipelineStage.RequireStage.adoc": "analyze",
    "PipelineStage.OffsetStage.adoc": "analyze",
    "PipelineStage.LimitStage.adoc": "analyze",
    "PipelineStage.DistinctStage.adoc": "analyze",
    "PipelineStage.ReduceStage.adoc": "analyze",
    "PipelineStage.SortStage.SortVariable.adoc": "analyze",
    "PipelineStage.ReduceStage.ReduceAssignment.adoc": "analyze",
    "ReduceAssignment.adoc": "analyze",
    "Reducer.adoc": "analyze",
    "SortOrder.adoc": "analyze",
    "TypeAnnotations.adoc": "analyze",
    "VariableAnnotations.adoc": "analyze",
    "ConceptRow.adoc": "answer",
    "ConceptRowIterator.adoc": "answer",
    "ConceptDocumentIterator.adoc": "answer",
    "JSON.adoc": "answer",
    "OkQueryAnswer.adoc": "answer",
    "QueryAnswer.adoc": "answer",
    "QueryType.adoc": "answer",
    "Promise_T_.adoc": "answer",
    "Concept.adoc": "concept",
    "TypeDB.adoc": "connection",
    "DriverOptions.adoc": "connection",
    "Credentials.adoc": "connection",
    "Driver.adoc": "connection",
    "User.adoc": "connection",
    "UserManager.adoc": "connection",
#    "Database.Replica.adoc": "connection",
    "Database.adoc": "connection",
    "DatabaseManager.adoc": "connection",
    "Relation.adoc": "data",
    "Entity.adoc": "data",
    "Attribute.adoc": "data",
    "Instance.adoc": "data",
    "Value.adoc": "data",
    "Value.Type.adoc": "schema",
    "RelationType.adoc": "schema",
    "AttributeType.adoc": "schema",
    "RoleType.adoc": "schema",
    "EntityType.adoc": "schema",
    "Type.adoc": "schema",
    "Transaction.adoc": "transaction",
    "Transaction.Type.adoc": "transaction",
    "TransactionOptions.adoc": "transaction",
    "QueryOptions.adoc": "transaction",
    "Duration.adoc": "value",
    "TypeDBDriverException.adoc": "errors",
}
