maven = use_extension("@typedb_dependencies//library/maven:maven_extension.bzl", "maven")
maven.artifacts(artifacts = [
    "ch.qos.logback:logback-classic",                  # //java/user, //java/connection
    "ch.qos.logback:logback-core",                     # //java/user, //java/connection
    "com.eclipsesource.minimal-json:minimal-json",     # //java/api
    "com.google.code.findbugs:jsr305",                 # //java/concept, //java/api, //java/answer, //java/common
    "io.netty:netty-tcnative-boringssl-static",        # //java/user, //java/connection
])
