[#_Database]
=== Database

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `name` a| `str` a| The database name as a string.
|===
// end::properties[]

// tag::methods[]
[#_Database_delete__]
==== delete

[source,python]
----
delete() -> None
----

Deletes this database.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
database.delete()
----

[#_Database_preferred_replica__]
==== preferred_replica

[source,python]
----
preferred_replica() -> Replica | None
----

Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud_

[caption=""]
.Returns
`Replica | None`

[caption=""]
.Code examples
[source,python]
----
database.preferred_replica()
----

[#_Database_primary_replica__]
==== primary_replica

[source,python]
----
primary_replica() -> Replica | None
----

Returns the primary replica for this database. _Only works in TypeDB Cloud_

[caption=""]
.Returns
`Replica | None`

[caption=""]
.Code examples
[source,python]
----
database.primary_replica()
----

[#_Database_replicas__]
==== replicas

[source,python]
----
replicas() -> Set[Replica]
----

Set of ``Replica`` instances for this database. _Only works in TypeDB Cloud_

[caption=""]
.Returns
`Set[Replica]`

[caption=""]
.Code examples
[source,python]
----
database.replicas()
----

[#_Database_rule_schema__]
==== rule_schema

[source,python]
----
rule_schema() -> str
----

Returns the rules in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.rule_schema()
----

[#_Database_schema__]
==== schema

[source,python]
----
schema() -> str
----

Returns a full schema text as a valid TypeQL define query string.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.schema()
----

[#_Database_type_schema__]
==== type_schema

[source,python]
----
type_schema() -> str
----

Returns the types in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
database.type_schema()
----

// end::methods[]

