[#_TypeDBDriver]
=== TypeDBDriver

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager` a| The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud.
|===
// end::properties[]

// tag::methods[]
[#_TypeDBDriver_close__]
==== close

[source,python]
----
close() -> None
----

Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.close()
----

[#_TypeDBDriver_is_open__]
==== is_open

[source,python]
----
is_open() -> bool
----

Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.is_open()
----

[#_TypeDBDriver_session__database_name_str__session_type_SessionType__options_TypeDBOptions__None]
==== session

[source,python]
----
session(database_name: str, session_type: SessionType, options: TypeDBOptions | None = None) -> TypeDBSession
----

Opens a communication tunnel (session) to the given database on the running TypeDB server. For more information on the methods, available with sessions, see the ``TypeDBSession`` section.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `database_name` a| The name of the database with which the session connects a| `str` a| 
a| `session_type` a| The type of session to be created (DATA or SCHEMA) a| `SessionType` a| 
a| `options` a| ``TypeDBOptions`` for the session a| `TypeDBOptions \| None` a| `None`
|===

[caption=""]
.Returns
`TypeDBSession`

[caption=""]
.Code examples
[source,python]
----
driver.session(database, session_type, options)
----

[#_TypeDBDriver_user__]
==== user

[source,python]
----
user() -> User
----

Returns the logged-in user for the connection. Only for TypeDB Cloud.

[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,python]
----
driver.user()
----

// end::methods[]

