[#_UserManager]
=== UserManager

Provides access to all user management methods.

// tag::methods[]
[#_UserManager_all__]
==== all

[source,python]
----
all() -> List[User]
----

Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
`List[User]`

[caption=""]
.Code examples
[source,python]
----
driver.users.all()
----

[#_UserManager_contains__username_str]
==== contains

[source,python]
----
contains(username: str) -> bool
----

Checks if a user with the given name exists.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The user name to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.users.contains(username)
----

[#_UserManager_create__username_str__password_str]
==== create

[source,python]
----
create(username: str, password: str) -> None
----

Create a user with the given name and password.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be created a| `str` a| 
a| `password` a| The password of the user to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.create(username, password)
----

[#_UserManager_delete__username_str]
==== delete

[source,python]
----
delete(username: str) -> None
----

Deletes a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to be deleted a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.delete(username)
----

[#_UserManager_get__username_str]
==== get

[source,python]
----
get(username: str) -> User | None
----

Retrieve a user with the given name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`User | None`

[caption=""]
.Code examples
[source,python]
----
driver.users.get(username)
----

[#_UserManager_password_set__username_str__password_str]
==== password_set

[source,python]
----
password_set(username: str, password: str) -> None
----

Sets a new password for a user. This operation can only be performed by administrators.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `username` a| The name of the user to set the password of a| `str` a| 
a| `password` a| The new password a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.users.password_set(username, password)
----

// end::methods[]

