[#_struct_ConceptMap]
=== ConceptMap

*Implements traits:*

* `Clone`
* `Debug`
* `From<ConceptMap>`
* `Index<String>`
* `IntoIterator`
* `PartialEq<ConceptMap>`
* `StructuralPartialEq`

Contains a mapping of variables to concepts.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `explainables` a| `Explainables` a| The ``Explainables`` object for this ``ConceptMap``, that exposes which of the concepts in this ``ConceptMap`` are explainable.
a| `map` a| `HashMap<String, Concept>` a| The ``HashMap`` where keys are query variables, and values are concepts.
|===
// end::properties[]

// tag::methods[]
[#_struct_ConceptMap_concepts__]
==== concepts

[source,rust]
----
pub fn concepts(&self) -> impl Iterator<Item = &Concept>
----

Produces an iterator over all concepts in this ``ConceptMap``.

[caption=""]
.Returns
[source,rust]
----
impl Iterator<Item = &Concept>
----

[caption=""]
.Code examples
[source,rust]
----
concept_map.concepts()
----

[#_struct_ConceptMap_get__var_name_str]
==== get

[source,rust]
----
pub fn get(&self, var_name: &str) -> Option<&Concept>
----

Retrieves a concept for a given variable name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `var_name` a| The string representation of a variable a| `&str`
|===

[caption=""]
.Returns
[source,rust]
----
Option<&Concept>
----

[caption=""]
.Code examples
[source,rust]
----
concept_map.get(var_name)
----

// end::methods[]

