[#_IQueryManager]
=== IQueryManager

*Package*: `TypeDB.Driver.Api`



Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Define___string_query_]
==== Define

[source,cs]
----
VoidPromise Define(string query)
----



Performs a TypeQL Define query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Define(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Define___string_query__TypeDBOptions_options_]
==== Define

[source,cs]
----
VoidPromise Define(string query, TypeDBOptions options)
----



Performs a TypeQL Define query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Define(query, options).Resolve()
----

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query_]
==== Delete

[source,cs]
----
VoidPromise Delete(string query)
----



Performs a TypeQL Delete query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Delete(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query__TypeDBOptions_options_]
==== Delete

[source,cs]
----
VoidPromise Delete(string query, TypeDBOptions options)
----



Performs a TypeQL Delete query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Delete(query, options).Resolve()
----

[#_IEnumerable__IExplanation___TypeDB_Driver_Api_IQueryManager_Explain___IConceptMap_IExplainable_explainable_]
==== Explain

[source,cs]
----
IEnumerable< IExplanation > IExplainable explainable)
----



Performs a TypeQL Explain query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Explain(IConceptMap.IExplainable, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IExplanation > IExplainable`

[#_IEnumerable__IExplanation___TypeDB_Driver_Api_IQueryManager_Explain___IConceptMap_IExplainable_explainable__TypeDBOptions_options_]
==== Explain

[source,cs]
----
IEnumerable< IExplanation > IExplainable explainable, TypeDBOptions options)
----



Performs a TypeQL Explain query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The IExplainable to be explained a| `IEnumerable< IExplanation > IExplainable`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IExplanation > IExplainable explainable, TypeDBOptions`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Explain(explainable, options)
----

[#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query_]
==== Fetch

[source,cs]
----
IEnumerable< JObject > Fetch(string query)
----



Performs a TypeQL Fetch (Fetch) with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Fetch(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< JObject >`

[#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query__TypeDBOptions_options_]
==== Fetch

[source,cs]
----
IEnumerable< JObject > Fetch(string query, TypeDBOptions options)
----



Performs a TypeQL Fetch (Fetch) query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Fetch (Fetch) query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< JObject >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Fetch(query, options)
----

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query_]
==== Get

[source,cs]
----
IEnumerable< IConceptMap > Get(string query)
----



Performs a TypeQL Get (Get) with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Get(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query__TypeDBOptions_options_]
==== Get

[source,cs]
----
IEnumerable< IConceptMap > Get(string query, TypeDBOptions options)
----



Performs a TypeQL Get (Get) query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get (Get) query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Get(query, options);
----

[#_Promise__IValue___TypeDB_Driver_Api_IQueryManager_GetAggregate___string_query_]
==== GetAggregate

[source,cs]
----
Promise< IValue > GetAggregate(string query)
----



Performs a TypeQL Get Aggregate query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::GetAggregate(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`Promise< IValue >`

[#_Promise__IValue___TypeDB_Driver_Api_IQueryManager_GetAggregate___string_query__TypeDBOptions_options_]
==== GetAggregate

[source,cs]
----
Promise< IValue > GetAggregate(string query, TypeDBOptions options)
----



Performs a TypeQL Get Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Aggregate query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise< IValue >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.GetAggregate(query, options).Resolve()
----

[#_IEnumerable__IConceptMapGroup___TypeDB_Driver_Api_IQueryManager_GetGroup___string_query_]
==== GetGroup

[source,cs]
----
IEnumerable< IConceptMapGroup > GetGroup(string query)
----



Performs a TypeQL Get Group query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::GetGroup(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IConceptMapGroup >`

[#_IEnumerable__IConceptMapGroup___TypeDB_Driver_Api_IQueryManager_GetGroup___string_query__TypeDBOptions_options_]
==== GetGroup

[source,cs]
----
IEnumerable< IConceptMapGroup > GetGroup(string query, TypeDBOptions options)
----



Performs a TypeQL Get Group query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IConceptMapGroup >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.GetGroup(query, options)
----

[#_IEnumerable__IValueGroup___TypeDB_Driver_Api_IQueryManager_GetGroupAggregate___string_query_]
==== GetGroupAggregate

[source,cs]
----
IEnumerable< IValueGroup > GetGroupAggregate(string query)
----



Performs a TypeQL Get Group Aggregate query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::GetGroupAggregate(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IValueGroup >`

[#_IEnumerable__IValueGroup___TypeDB_Driver_Api_IQueryManager_GetGroupAggregate___string_query__TypeDBOptions_options_]
==== GetGroupAggregate

[source,cs]
----
IEnumerable< IValueGroup > GetGroupAggregate(string query, TypeDBOptions options)
----



Performs a TypeQL Get Group Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group Aggregate query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IValueGroup >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.GetGroupAggregate(query, options)
----

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Insert___string_query_]
==== Insert

[source,cs]
----
IEnumerable< IConceptMap > Insert(string query)
----



Performs a TypeQL Insert query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Insert(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Insert___string_query__TypeDBOptions_options_]
==== Insert

[source,cs]
----
IEnumerable< IConceptMap > Insert(string query, TypeDBOptions options)
----



Performs a TypeQL Insert query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Insert(query, options)
----

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Undefine___string_query_]
==== Undefine

[source,cs]
----
VoidPromise Undefine(string query)
----



Performs a TypeQL Undefine query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Undefine(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Undefine___string_query__TypeDBOptions_options_]
==== Undefine

[source,cs]
----
VoidPromise Undefine(string query, TypeDBOptions options)
----



Performs a TypeQL Undefine query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Undefine(query, options).Resolve()
----

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Update___string_query_]
==== Update

[source,cs]
----
IEnumerable< IConceptMap > Update(string query)
----



Performs a TypeQL Update query with default options.

 

See also
[source,cs]
----
 
 
IQueryManager::Update(string, TypeDBOptions)
---- 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Update___string_query__TypeDBOptions_options_]
==== Update

[source,cs]
----
IEnumerable< IConceptMap > Update(string query, TypeDBOptions options)
----



Performs a TypeQL Update query in the transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query.Update(query, options)
----

// end::methods[]

