[#_ITypeDBTransaction]
=== ITypeDBTransaction

*Package*: `TypeDB.Driver.Api`

// tag::methods[]
[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Close___]
==== Close

[source,cs]
----
void Close()
----



Closes the transaction.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
transaction.Close();
----

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Commit___]
==== Commit

[source,cs]
----
void Commit()
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is committed successfully, it gets closed after the commit call.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
transaction.Commit();
----

[#_IConceptManager_TypeDB_Driver_Api_ITypeDBTransaction_Concepts]
==== Concepts

[source,cs]
----
IConceptManager TypeDB.Driver.Api.ITypeDBTransaction.Concepts
----



The ``ConceptManager`` for this transaction, providing access to all Concept API methods.


[caption=""]
.Returns
`IConceptManager`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts;
----

[#_bool_TypeDB_Driver_Api_ITypeDBTransaction_IsOpen___]
==== IsOpen

[source,cs]
----
bool IsOpen()
----



Checks whether this transaction is open.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
transaction.IsOpen();
----

[#_ILogicManager_TypeDB_Driver_Api_ITypeDBTransaction_Logic]
==== Logic

[source,cs]
----
ILogicManager TypeDB.Driver.Api.ITypeDBTransaction.Logic
----



The ``LogicManager`` for this Transaction, providing access to all Concept API - Logic methods.


[caption=""]
.Returns
`ILogicManager`

[caption=""]
.Code examples
[source,cs]
----
transaction.Logic;
----

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_OnClose___Action__Exception___function_]
==== OnClose

[source,cs]
----
void OnClose(Action< Exception > function)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `Action< Exception >`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
transaction.OnClose(function);
----

[#_TypeDBOptions_TypeDB_Driver_Api_ITypeDBTransaction_Options]
==== Options

[source,cs]
----
TypeDBOptions TypeDB.Driver.Api.ITypeDBTransaction.Options
----



The options for the transaction.


[caption=""]
.Returns
`TypeDBOptions`

[caption=""]
.Code examples
[source,cs]
----
transaction.Options;
----

[#_IQueryManager_TypeDB_Driver_Api_ITypeDBTransaction_Query]
==== Query

[source,cs]
----
IQueryManager TypeDB.Driver.Api.ITypeDBTransaction.Query
----



The````QueryManager```` for this Transaction, from which any TypeQL query can be executed.


[caption=""]
.Returns
`IQueryManager`

[caption=""]
.Code examples
[source,cs]
----
transaction.Query;
----

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Rollback___]
==== Rollback

[source,cs]
----
void Rollback()
----



Rolls back the uncommitted changes made via this transaction.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
transaction.Rollback();
----

[#_TransactionType_TypeDB_Driver_Api_ITypeDBTransaction_Type]
==== Type

[source,cs]
----
TransactionType TypeDB.Driver.Api.ITypeDBTransaction.Type
----



The transaction’s type (Read or Write).


[caption=""]
.Returns
`TransactionType`

[caption=""]
.Code examples
[source,cs]
----
transaction.Type;
----

// end::methods[]

