[#_TypeDB_Driver_Api_IQueryManager_Interface_Reference]
=== TypeDB.Driver.Api.IQueryManager Interface Reference

*Package*: `TypeDB.Driver.Api.IQueryManager Interface Reference`



Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Define___string_query_]
==== Define

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Define(string query)
----



Performs a TypeQL Define query with default options.

 
  See also
 
 
  <<#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Define___string_query__TypeDBOptions_options_,IQueryManager::Define(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Define___string_query__TypeDBOptions_options_]
==== Define

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Define(string query, TypeDBOptions options)
----



Performs a TypeQL Define query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query_]
==== Delete

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Delete(string query)
----



Performs a TypeQL Delete query with default options.

 
  See also
 
 
  <<#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query__TypeDBOptions_options_,IQueryManager::Delete(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query__TypeDBOptions_options_]
==== Delete

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Delete(string query, TypeDBOptions options)
----



Performs a TypeQL Delete query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_IEnumerable__IExplanation___TypeDB_Driver_Api_IQueryManager_Explain___IConceptMap_IExplainable_explainable_]
==== Explain

[source,csharp]
----
IEnumerable< IExplanation > TypeDB.Driver.Api.IQueryManager.Explain(IConceptMap.IExplainable explainable)
----



Performs a TypeQL Explain query with default options.

 
  See also
 
 
  <<#_IEnumerable__IExplanation___TypeDB_Driver_Api_IQueryManager_Explain___IConceptMap_IExplainable_explainable_,IQueryManager::Explain>>(IConceptMap.IExplainable, TypeDBOptions)
 


[caption=""]
.Returns
`IEnumerable< IExplanation >`

[#_IEnumerable__IExplanation___TypeDB_Driver_Api_IQueryManager_Explain___IConceptMap_IExplainable_explainable__TypeDBOptions_options_]
==== Explain

[source,csharp]
----
IEnumerable< IExplanation > TypeDB.Driver.Api.IQueryManager.Explain(IConceptMap.IExplainable explainable, TypeDBOptions options)
----



Performs a TypeQL Explain query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The IExplainable to be explained a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IExplanation >`

[#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query_]
==== Fetch

[source,csharp]
----
IEnumerable< JObject > TypeDB.Driver.Api.IQueryManager.Fetch(string query)
----



Performs a TypeQL Fetch (Fetch) with default options.

 
  See also
 
 
  <<#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query__TypeDBOptions_options_,IQueryManager::Fetch(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< JObject >`

[#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query__TypeDBOptions_options_]
==== Fetch

[source,csharp]
----
IEnumerable< JObject > TypeDB.Driver.Api.IQueryManager.Fetch(string query, TypeDBOptions options)
----



Performs a TypeQL Fetch (Fetch) query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Fetch (Fetch) query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< JObject >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query_]
==== Get

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Get(string query)
----



Performs a TypeQL Get (Get) with default options.

 
  See also
 
 
  <<#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query__TypeDBOptions_options_,IQueryManager::Get(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query__TypeDBOptions_options_]
==== Get

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Get(string query, TypeDBOptions options)
----



Performs a TypeQL Get (Get) query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get (Get) query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_Promise__IValue___TypeDB_Driver_Api_IQueryManager_GetAggregate___string_query_]
==== GetAggregate

[source,csharp]
----
Promise< IValue > TypeDB.Driver.Api.IQueryManager.GetAggregate(string query)
----



Performs a TypeQL Get Aggregate query with default options.

 
  See also
 
 
  <<#_Promise__IValue___TypeDB_Driver_Api_IQueryManager_GetAggregate___string_query__TypeDBOptions_options_,IQueryManager::GetAggregate(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`Promise< IValue >`

[#_Promise__IValue___TypeDB_Driver_Api_IQueryManager_GetAggregate___string_query__TypeDBOptions_options_]
==== GetAggregate

[source,csharp]
----
Promise< IValue > TypeDB.Driver.Api.IQueryManager.GetAggregate(string query, TypeDBOptions options)
----



Performs a TypeQL Get Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Aggregate query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`Promise< IValue >`

[#_IEnumerable__IConceptMapGroup___TypeDB_Driver_Api_IQueryManager_GetGroup___string_query_]
==== GetGroup

[source,csharp]
----
IEnumerable< IConceptMapGroup > TypeDB.Driver.Api.IQueryManager.GetGroup(string query)
----



Performs a TypeQL Get Group query with default options.

 
  See also
 
 
  <<#_IEnumerable__IConceptMapGroup___TypeDB_Driver_Api_IQueryManager_GetGroup___string_query__TypeDBOptions_options_,IQueryManager::GetGroup(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< IConceptMapGroup >`

[#_IEnumerable__IConceptMapGroup___TypeDB_Driver_Api_IQueryManager_GetGroup___string_query__TypeDBOptions_options_]
==== GetGroup

[source,csharp]
----
IEnumerable< IConceptMapGroup > TypeDB.Driver.Api.IQueryManager.GetGroup(string query, TypeDBOptions options)
----



Performs a TypeQL Get Group query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IConceptMapGroup >`

[#_IEnumerable__IValueGroup___TypeDB_Driver_Api_IQueryManager_GetGroupAggregate___string_query_]
==== GetGroupAggregate

[source,csharp]
----
IEnumerable< IValueGroup > TypeDB.Driver.Api.IQueryManager.GetGroupAggregate(string query)
----



Performs a TypeQL Get Group Aggregate query with default options.

 
  See also
 
 
  <<#_IEnumerable__IValueGroup___TypeDB_Driver_Api_IQueryManager_GetGroupAggregate___string_query__TypeDBOptions_options_,IQueryManager::GetGroupAggregate(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< IValueGroup >`

[#_IEnumerable__IValueGroup___TypeDB_Driver_Api_IQueryManager_GetGroupAggregate___string_query__TypeDBOptions_options_]
==== GetGroupAggregate

[source,csharp]
----
IEnumerable< IValueGroup > TypeDB.Driver.Api.IQueryManager.GetGroupAggregate(string query, TypeDBOptions options)
----



Performs a TypeQL Get Group Aggregate query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group Aggregate query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IValueGroup >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Insert___string_query_]
==== Insert

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Insert(string query)
----



Performs a TypeQL Insert query with default options.

 
  See also
 
 
  <<#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Insert___string_query__TypeDBOptions_options_,IQueryManager::Insert(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Insert___string_query__TypeDBOptions_options_]
==== Insert

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Insert(string query, TypeDBOptions options)
----



Performs a TypeQL Insert query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Undefine___string_query_]
==== Undefine

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Undefine(string query)
----



Performs a TypeQL Undefine query with default options.

 
  See also
 
 
  <<#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Undefine___string_query__TypeDBOptions_options_,IQueryManager::Undefine(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Undefine___string_query__TypeDBOptions_options_]
==== Undefine

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IQueryManager.Undefine(string query, TypeDBOptions options)
----



Performs a TypeQL Undefine query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Update___string_query_]
==== Update

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Update(string query)
----



Performs a TypeQL Update query with default options.

 
  See also
 
 
  <<#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Update___string_query__TypeDBOptions_options_,IQueryManager::Update(string, TypeDBOptions)>>
 


[caption=""]
.Returns
`IEnumerable< IConceptMap >`

[#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Update___string_query__TypeDBOptions_options_]
==== Update

[source,csharp]
----
IEnumerable< IConceptMap > TypeDB.Driver.Api.IQueryManager.Update(string query, TypeDBOptions options)
----



Performs a TypeQL Update query in the transaction.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`IEnumerable< IConceptMap >`

// end::methods[]

