[#_enum_Comparator]
=== Comparator

`Class(name=Comparator, anchor=enum_Comparator, enumConstants=[EnumConstant(name=Equal = 0, type=null, value=null), EnumConstant(name=NotEqual = 1, type=null, value=null), EnumConstant(name=LessThan = 2, type=null, value=null), EnumConstant(name=LessOrEqual = 3, type=null, value=null), EnumConstant(name=Greater = 4, type=null, value=null), EnumConstant(name=GreaterOrEqual = 5, type=null, value=null), EnumConstant(name=Like = 6, type=null, value=null), EnumConstant(name=Contains = 7, type=null, value=null)], description=[A representation of the comparator used in a comparison constraint.], examples=[], fields=[], methods=[Method(name=symbol, signature=pub fn symbol(&self) -> &'static str, anchor=enum_Comparator_symbol_, args=[], description=[The symbol representing the comparator in TypeQL], examples=[], mode=async, returnDescription=null, returnType=&'static str)], packagePath=null, superClasses=[], traitImplementors=[], mode=async).nameDescriptor(language)`

A representation of the comparator used in a comparison constraint.

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `Contains = 7`
a| `Equal = 0`
a| `Greater = 4`
a| `GreaterOrEqual = 5`
a| `LessOrEqual = 3`
a| `LessThan = 2`
a| `Like = 6`
a| `NotEqual = 1`
|===
// end::enum_constants[]

// tag::methods[]
[#_enum_Comparator_symbol_]
==== symbol

[source,rust]
----
pub fn symbol(&self) -> &'static str
----

The symbol representing the comparator in TypeQL

[caption=""]
.Returns
[source,rust]
----
&'static str
----

// end::methods[]

