[#_struct_ConstraintSpan]
=== ConstraintSpan

`Class(name=ConstraintSpan, anchor=struct_ConstraintSpan, enumConstants=[], description=[The span of a constraint in the ``source`` of the ``AnalyzedQuery``.], examples=[], fields=[Variable(name=begin, anchor=struct_ConstraintSpan_begin, defaultValue=null, description=The offset of the first character in the span, type=usize), Variable(name=end, anchor=struct_ConstraintSpan_end, defaultValue=null, description=The offset after the last character in the span, type=usize)], methods=[], packagePath=null, superClasses=[Clone, Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`

The span of a constraint in the ``source`` of the ``AnalyzedQuery``.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `begin` a| `usize` a| The offset of the first character in the span
a| `end` a| `usize` a| The offset after the last character in the span
|===
// end::properties[]

