[#_enum_Constraint]
=== Constraint

`Class(name=Constraint, anchor=enum_Constraint, enumConstants=[EnumConstant(name=Isa, type=null, value=null), EnumConstant(name=Has, type=null, value=null), EnumConstant(name=Links, type=null, value=null), EnumConstant(name=Sub, type=null, value=null), EnumConstant(name=Owns, type=null, value=null), EnumConstant(name=Relates, type=null, value=null), EnumConstant(name=Plays, type=null, value=null), EnumConstant(name=FunctionCall, type=null, value=null), EnumConstant(name=Expression, type=null, value=null), EnumConstant(name=Is, type=null, value=null), EnumConstant(name=Iid, type=null, value=null), EnumConstant(name=Comparison, type=null, value=null), EnumConstant(name=Kind, type=null, value=null), EnumConstant(name=Label, type=null, value=null), EnumConstant(name=Value, type=null, value=null), EnumConstant(name=Or, type=null, value=null), EnumConstant(name=Not, type=null, value=null), EnumConstant(name=Try, type=null, value=null)], description=[A representation of a TypeQL constraint.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=async).nameDescriptor(language)`

A representation of a TypeQL constraint.

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `Comparison`
a| `Expression`
a| `FunctionCall`
a| `Has`
a| `Iid`
a| `Is`
a| `Isa`
a| `Kind`
a| `Label`
a| `Links`
a| `Not`
a| `Or`
a| `Owns`
a| `Plays`
a| `Relates`
a| `Sub`
a| `Try`
a| `Value`
|===
// end::enum_constants[]

