[#_enum_ConstraintExactness]
=== ConstraintExactness

`Class(name=ConstraintExactness, anchor=enum_ConstraintExactness, enumConstants=[EnumConstant(name=Exact = 0, type=null, value=null), EnumConstant(name=Subtypes = 1, type=null, value=null)], description=[Tells apart exact variants of constraints from the ones allowing subtype-polymorphism. e.g. <code>isa!</code> would be represented as an <code>Constraint::Isa</code> with its exactness field <code>ConstraintExactness::Exact</code>.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=async).nameDescriptor(language)`

Tells apart exact variants of constraints from the ones allowing subtype-polymorphism. e.g. <code>isa!</code> would be represented as an <code>Constraint::Isa</code> with its exactness field <code>ConstraintExactness::Exact</code>.

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `Exact = 0`
a| `Subtypes = 1`
|===
// end::enum_constants[]

