[#_enum_PipelineStage]
=== PipelineStage

`Class(name=PipelineStage, anchor=enum_PipelineStage, enumConstants=[EnumConstant(name=Match, type=null, value=null), EnumConstant(name=Insert, type=null, value=null), EnumConstant(name=Put, type=null, value=null), EnumConstant(name=Update, type=null, value=null), EnumConstant(name=Delete, type=null, value=null), EnumConstant(name=Select, type=null, value=null), EnumConstant(name=Sort, type=null, value=null), EnumConstant(name=Require, type=null, value=null), EnumConstant(name=Offset, type=null, value=null), EnumConstant(name=Limit, type=null, value=null), EnumConstant(name=Distinct, type=null, value=null), EnumConstant(name=Reduce, type=null, value=null)], description=[Representation of a stage in a <code>Pipeline</code>.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=async).nameDescriptor(language)`

Representation of a stage in a <code>Pipeline</code>.

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Variant
a| `Delete`
a| `Distinct`
a| `Insert`
a| `Limit`
a| `Match`
a| `Offset`
a| `Put`
a| `Reduce`
a| `Require`
a| `Select`
a| `Sort`
a| `Update`
|===
// end::enum_constants[]

