[#_struct_Reducer]
=== Reducer

`Class(name=Reducer, anchor=struct_Reducer, enumConstants=[], description=[Representation of a reducer used either in a ``PipelineStage::Reduce`` or in a function’s ``ReturnOperation``.], examples=[], fields=[Variable(name=arguments, anchor=struct_Reducer_arguments, defaultValue=null, description=The arguments to the reducer., type=Vec<Variable>), Variable(name=reducer, anchor=struct_Reducer_reducer, defaultValue=null, description=The reduce operation applied, type=String)], methods=[], packagePath=null, superClasses=[Clone, Debug], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`

Representation of a reducer used either in a ``PipelineStage::Reduce`` or in a function’s ``ReturnOperation``.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `arguments` a| `Vec<Variable>` a| The arguments to the reducer.
a| `reducer` a| `String` a| The reduce operation applied
|===
// end::properties[]

