[#_ConceptManager]
= ConceptManager

== Description

Provides access for all Concept API methods.

== Methods

// tag::methods[]
[#_get_attribute]
=== get_attribute

==== Signature

[source,python]
----
abstract get_attribute(iid: str) -> Attribute
----

==== Description

Retrieves an `Attribute` by its iid.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the `Attribute` to retrieve a| `str` a| 
|===

==== Returns

`Attribute`

==== Code examples

[source,python]
----
transaction.concepts.get_attribute(iid)
----

[#_get_attribute_type]
=== get_attribute_type

==== Signature

[source,python]
----
abstract get_attribute_type(label: str) -> AttributeType
----

==== Description

Retrieves an `AttributeType` by its label.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `AttributeType` to retrieve a| `str` a| 
|===

==== Returns

`AttributeType`

==== Code examples

[source,python]
----
transaction.concepts.get_attribute_type(label)
----

[#_get_entity]
=== get_entity

==== Signature

[source,python]
----
abstract get_entity(iid: str) -> Entity
----

==== Description

Retrieves an `Entity` by its iid.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the `Entity` to retrieve a| `str` a| 
|===

==== Returns

`Entity`

==== Code examples

[source,python]
----
transaction.concepts.get_entity(iid)
----

[#_get_entity_type]
=== get_entity_type

==== Signature

[source,python]
----
abstract get_entity_type(label: str) -> EntityType
----

==== Description

Retrieves an `EntityType` by its label.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `EntityType` to retrieve a| `str` a| 
|===

==== Returns

`EntityType`

==== Code examples

[source,python]
----
transaction.concepts.get_entity_type(label)
----

[#_get_relation]
=== get_relation

==== Signature

[source,python]
----
abstract get_relation(iid: str) -> Relation
----

==== Description

Retrieves a `Relation` by its iid.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `iid` a| The iid of the `Relation` to retrieve a| `str` a| 
|===

==== Returns

`Relation`

==== Code examples

[source,python]
----
transaction.concepts.get_relation(iid)
----

[#_get_relation_type]
=== get_relation_type

==== Signature

[source,python]
----
abstract get_relation_type(label: str) -> RelationType
----

==== Description

Retrieves a `RelationType` by its label.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `RelationType` to retrieve a| `str` a| 
|===

==== Returns

`RelationType`

==== Code examples

[source,python]
----
transaction.concepts.get_relation_type(label)
----

[#_get_root_attribute_type]
=== get_root_attribute_type

==== Signature

[source,python]
----
abstract get_root_attribute_type() -> AttributeType
----

==== Description

Retrieve the root `AttributeType`, “attribute”.

==== Returns

`AttributeType`

==== Code examples

[source,python]
----
transaction.concepts.get_root_attribute_type()
----

[#_get_root_entity_type]
=== get_root_entity_type

==== Signature

[source,python]
----
abstract get_root_entity_type() -> EntityType
----

==== Description

Retrieves the root `EntityType`, “entity”.

==== Returns

`EntityType`

==== Code examples

[source,python]
----
transaction.concepts.get_root_entity_type()
----

[#_get_root_relation_type]
=== get_root_relation_type

==== Signature

[source,python]
----
abstract get_root_relation_type() -> RelationType
----

==== Description

Retrieve the root `RelationType`, “relation”.

==== Returns

`RelationType`

==== Code examples

[source,python]
----
transaction.concepts.get_root_relation_type()
----

[#_get_schema_exception]
=== get_schema_exception

==== Signature

[source,python]
----
abstract get_schema_exception() -> list[TypeDBException]
----

==== Description

Retrieves a list of all exceptions for the current transaction.

==== Returns

`list[TypeDBException]`

==== Code examples

[source,python]
----
transaction.concepts.get_schema_exception()
----

[#_put_attribute_type]
=== put_attribute_type

==== Signature

[source,python]
----
abstract put_attribute_type(label: str, value_type: ValueType) -> AttributeType
----

==== Description

Creates a new `AttributeType` if none exists with the given label, or retrieves the existing one.

or retrieve. :return:

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `AttributeType` to create or retrieve a| `str` a| 
a| `value_type` a| The value type of the `AttributeType` to create a| `ValueType` a| 
|===

==== Returns

`AttributeType`

==== Code examples

[source,python]
----
transaction.concepts.put_attribute_type(label, value_type)
----

[#_put_entity_type]
=== put_entity_type

==== Signature

[source,python]
----
abstract put_entity_type(label: str) -> EntityType
----

==== Description

Creates a new `EntityType` if none exists with the given label, otherwise retrieves the existing one.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `EntityType` to create or retrieve a| `str` a| 
|===

==== Returns

`EntityType`

==== Code examples

[source,python]
----
transaction.concepts.put_entity_type(label)
----

[#_put_relation_type]
=== put_relation_type

==== Signature

[source,python]
----
abstract put_relation_type(label: str) -> RelationType
----

==== Description

Creates a new `RelationType` if none exists with the given label, otherwise retrieves the existing one.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `label` a| The label of the `RelationType` to create or retrieve a| `str` a| 
|===

==== Returns

`RelationType`

==== Code examples

[source,python]
----
transaction.concepts.put_relation_type(label)
----

// end::methods[]
