[#_ConceptMap]
=== ConceptMap

Contains a mapping of variables to concepts.

// tag::methods[]
[#_concepts]
==== concepts

[source,python]
----
concepts() -> Iterator[Concept]
----

Produces an iterator over all concepts in this ``ConceptMap``.

[caption=""]
.Returns
`Iterator[Concept]`

[caption=""]
.Code examples
[source,python]
----
concept_map.concepts()
----

[#_explainables]
==== explainables

[source,python]
----
explainables() -> Explainables
----

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable.

[caption=""]
.Returns
`Explainables`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables()
----

[#_get]
==== get

[source,python]
----
get(variable: str) -> Concept
----

Retrieves a concept for a given variable name.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,python]
----
concept_map.get(variable)
----

[#_to_json]
==== to_json

[source,python]
----
to_json() -> Mapping[str, Mapping[str, str | int | float | bool]]
----

Retrieves this ``ConceptMap`` as JSON.

[caption=""]
.Returns
`Mapping[str, Mapping[str, str | int | float | bool]]`

[caption=""]
.Code examples
[source,python]
----
concept_map.to_json()
----

[#_variables]
==== variables

[source,python]
----
variables() -> Iterator[str]
----

Produces an iterator over all variables in this ``ConceptMap``.

[caption=""]
.Returns
`Iterator[str]`

[caption=""]
.Code examples
[source,python]
----
concept_map.variables()
----

// end::methods[]

