[#_ConceptMap]
= ConceptMap

== Description

Contains a mapping of variables to concepts.

== Methods

// tag::methods[]
[#_conjunction]
=== conjunction

==== Signature

[source,python]
----
conjunction() -> str
----

==== Description

Retrieves the subquery of the original query that is actually being explained.

==== Returns

`str`

==== Code examples

[source,python]
----
explainable.conjunction()
----

[#_id]
=== id

==== Signature

[source,python]
----
id() -> int
----

==== Description

Retrieves the unique ID that identifies this ``Explainable``.

==== Returns

`int`

==== Code examples

[source,python]
----
explainable.id()
----

[#_attribute]
=== attribute

==== Signature

[source,python]
----
attribute(variable: str) -> Explainable
----

==== Description

Retrieves the explainable attribute with the given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().attribute(variable)
----

[#_attributes]
=== attributes

==== Signature

[source,python]
----
attributes() -> Mapping[str, Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable attributes.

==== Returns

`Mapping[str, Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().attributes()
----

[#_ownership]
=== ownership

==== Signature

[source,python]
----
ownership(owner: str, attribute: str) -> Explainable
----

==== Description

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `owner` a| The string representation of the owner variable a| `str` a| 
a| `attribute` a| The string representation of the attribute variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().ownership(owner, attribute)
----

[#_ownerships]
=== ownerships

==== Signature

[source,python]
----
ownerships() -> Mapping[tuple[str, str], Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable ownerships.

==== Returns

`Mapping[tuple[str, str], Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().ownerships()
----

[#_relation]
=== relation

==== Signature

[source,python]
----
relation(variable: str) -> Explainable
----

==== Description

Retrieves the explainable relation with the given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().relation(variable)
----

[#_relations]
=== relations

==== Signature

[source,python]
----
relations() -> Mapping[str, Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable relations.

==== Returns

`Mapping[str, Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().relations()
----

[#_concepts]
=== concepts

==== Signature

[source,python]
----
concepts() -> Iterator[Concept]
----

==== Description

Produces an iterator over all concepts in this ``ConceptMap``.

==== Returns

`Iterator[Concept]`

==== Code examples

[source,python]
----
concept_map.concepts()
----

[#_explainables]
=== explainables

==== Signature

[source,python]
----
explainables() -> Explainables
----

==== Description

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable.

==== Returns

`Explainables`

==== Code examples

[source,python]
----
concept_map.explainables()
----

[#_get]
=== get

==== Signature

[source,python]
----
get(variable: str) -> Concept
----

==== Description

Retrieves a concept for a given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Concept`

==== Code examples

[source,python]
----
concept_map.get(variable)
----

[#_to_json]
=== to_json

==== Signature

[source,python]
----
to_json() -> Mapping[str, Mapping[str, str | int | float | bool]]
----

==== Description

Retrieves this ``ConceptMap`` as JSON.

==== Returns

`Mapping[str, Mapping[str, str | int | float | bool]]`

==== Code examples

[source,python]
----
concept_map.to_json()
----

[#_variables]
=== variables

==== Signature

[source,python]
----
variables() -> Iterator[str]
----

==== Description

Produces an iterator over all variables in this ``ConceptMap``.

==== Returns

`Iterator[str]`

==== Code examples

[source,python]
----
concept_map.variables()
----

// end::methods[]
