[#_ConceptMap]
= ConceptMap

== Description

Contains a mapping of variables to concepts.

== Methods

// tag::methods[]
[#_concepts]
=== concepts

==== Signature

[source,python]
----
concepts() -> Iterator[Concept]
----

==== Description

Produces an iterator over all concepts in this ``ConceptMap``.

==== Returns

`Iterator[Concept]`

==== Code examples

[source,python]
----
concept_map.concepts()
----

[#_explainables]
=== explainables

==== Signature

[source,python]
----
explainables() -> Explainables
----

==== Description

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable.

==== Returns

`Explainables`

==== Code examples

[source,python]
----
concept_map.explainables()
----

[#_get]
=== get

==== Signature

[source,python]
----
get(variable: str) -> Concept
----

==== Description

Retrieves a concept for a given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Concept`

==== Code examples

[source,python]
----
concept_map.get(variable)
----

[#_to_json]
=== to_json

==== Signature

[source,python]
----
to_json() -> Mapping[str, Mapping[str, str | int | float | bool]]
----

==== Description

Retrieves this ``ConceptMap`` as JSON.

==== Returns

`Mapping[str, Mapping[str, str | int | float | bool]]`

==== Code examples

[source,python]
----
concept_map.to_json()
----

[#_variables]
=== variables

==== Signature

[source,python]
----
variables() -> Iterator[str]
----

==== Description

Produces an iterator over all variables in this ``ConceptMap``.

==== Returns

`Iterator[str]`

==== Code examples

[source,python]
----
concept_map.variables()
----

// end::methods[]
