[#_DatabaseManager]
=== DatabaseManager

Provides access to all database management methods.

// tag::methods[]
[#_all]
==== all

[source,python]
----
all() -> List[Database]
----

Retrieves all databases present on the TypeDB server

[caption=""]
.Returns
`List[Database]`

[caption=""]
.Code examples
[source,python]
----
driver.databases.all()
----

[#_contains]
==== contains

[source,python]
----
contains(name: str) -> bool
----

Checks if a database with the given name exists

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The database name to be checked a| `str` a| 
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
driver.databases.contains(name)
----

[#_create]
==== create

[source,python]
----
create(name: str) -> None
----

Create a database with the given name

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to be created a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
driver.databases.create(name)
----

[#_get]
==== get

[source,python]
----
get(name: str) -> Database
----

Retrieve the database with the given name.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `name` a| The name of the database to retrieve a| `str` a| 
|===

[caption=""]
.Returns
`Database`

[caption=""]
.Code examples
[source,python]
----
driver.databases.get(name)
----

// end::methods[]

