[#_Explainables]
= Explainables

== Description

Contains explainable objects.

== Methods

// tag::methods[]
[#_attribute]
=== attribute

==== Signature

[source,python]
----
abstract attribute(variable: str) -> Explainable
----

==== Description

Retrieves the explainable attribute with the given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().attribute(variable)
----

[#_attributes]
=== attributes

==== Signature

[source,python]
----
abstract attributes() -> Mapping[str, Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable attributes.

==== Returns

`Mapping[str, Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().attributes()
----

[#_ownership]
=== ownership

==== Signature

[source,python]
----
abstract ownership(owner: str, attribute: str) -> Explainable
----

==== Description

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `owner` a| The string representation of the owner variable a| `str` a| 
a| `attribute` a| The string representation of the attribute variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().ownership(owner, attribute)
----

[#_ownerships]
=== ownerships

==== Signature

[source,python]
----
abstract ownerships() -> Mapping[tuple[str, str], Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable ownerships.

==== Returns

`Mapping[tuple[str, str], Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().ownerships()
----

[#_relation]
=== relation

==== Signature

[source,python]
----
abstract relation(variable: str) -> Explainable
----

==== Description

Retrieves the explainable relation with the given variable name.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

==== Returns

`Explainable`

==== Code examples

[source,python]
----
concept_map.explainables().relation(variable)
----

[#_relations]
=== relations

==== Signature

[source,python]
----
abstract relations() -> Mapping[str, Explainable]
----

==== Description

Retrieves all of this ``ConceptMap``’s explainable relations.

==== Returns

`Mapping[str, Explainable]`

==== Code examples

[source,python]
----
concept_map.explainables().relations()
----

// end::methods[]
