[#_Explanation]
= Explanation

== Description

An explanation of which rule was used for inferring the explained concept, the condition of the rule, the conclusion of the rule, and the mapping of variables between the query and the rule’s conclusion.

== Methods

// tag::methods[]
[#_conclusion]
=== conclusion

==== Signature

[source,python]
----
abstract conclusion() -> ConceptMap
----

==== Description

Retrieves the Conclusion for this Explanation.

==== Returns

`ConceptMap`

==== Code examples

[source,python]
----
explanation.conclusion()
----

[#_condition]
=== condition

==== Signature

[source,python]
----
abstract condition() -> ConceptMap
----

==== Description

Retrieves the Condition for this Explanation.

==== Returns

`ConceptMap`

==== Code examples

[source,python]
----
explanation.condition()
----

[#_query_variable_mapping]
=== query_variable_mapping

==== Signature

[source,python]
----
abstract query_variable_mapping(var: str) -> set[str]
----

==== Description

Retrieves the rule variables corresponding to the query variable var for this ``Explanation``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `var` a| The query variable to map to rule variables. a| `str` a| 
|===

==== Returns

`set[str]`

==== Code examples

[source,python]
----
explanation.variable_mapping(var)
----

[#_query_variables]
=== query_variables

==== Signature

[source,python]
----
abstract query_variables() -> set[str]
----

==== Description

Retrieves the query variables for this ``Explanation``.

==== Returns

`set[str]`

==== Code examples

[source,python]
----
explanation.query_variables()
----

[#_rule]
=== rule

==== Signature

[source,python]
----
abstract rule() -> Rule
----

==== Description

Retrieves the Rule for this Explanation.

==== Returns

`Rule`

==== Code examples

[source,python]
----
explanation.rule()
----

// end::methods[]
