[#_Relation]
= Relation

*Supertypes:*

* `Thing`

== Description

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

== Methods

// tag::methods[]
[#_add_player]
=== add_player

==== Signature

[source,python]
----
abstract add_player(transaction: TypeDBTransaction, role_type: RoleType, player: Thing) -> None
----

==== Description

Adds a new role player to play the given role in this `Relation`.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to be played by the `player` a| `RoleType` a| 
a| `player` a| The thing to play the role a| `Thing` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
relation.add_player(transaction, role_type, player)
----

[#_as_relation]
=== as_relation

==== Signature

[source,python]
----
as_relation() -> Relation
----

==== Description

Casts the concept to `Relation`.

==== Returns

`Relation`

==== Code examples

[source,python]
----
relation.as_relation()
----

[#_get_players]
=== get_players

==== Signature

[source,python]
----
abstract get_players(transaction: TypeDBTransaction) -> dict[RoleType, list[Thing]]
----

==== Description

Retrieves a mapping of all instances involved in the `Relation` and the role each play.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`dict[RoleType, list[Thing]]`

==== Code examples

[source,python]
----
relation.get_players(transaction)
----

[#_get_players_by_role_type]
=== get_players_by_role_type

==== Signature

[source,python]
----
abstract get_players_by_role_type(transaction: TypeDBTransaction, *role_types: RoleType) -> Iterator[Thing]
----

==== Description

Retrieves all role players of this `Relation`, optionally filtered by given role types.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_types` a| 0 or more role types a| `RoleType` a| 
|===

==== Returns

`Iterator[Thing]`

==== Code examples

[source,python]
----
relation.get_players_by_role_type(transaction)
relation.get_players_by_role_type(transaction, role_type1, role_type2)
----

[#_get_relating]
=== get_relating

==== Signature

[source,python]
----
abstract get_relating(transaction: TypeDBTransaction) -> Iterator[RoleType]
----

==== Description

Retrieves all role types currently played in this `Relation`.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`Iterator[RoleType]`

==== Code examples

[source,python]
----
relation.get_relating(transaction)
----

[#_get_type]
=== get_type

==== Signature

[source,python]
----
abstract get_type() -> RelationType
----

==== Description

Retrieves the type which this `Relation` belongs to.

==== Returns

`RelationType`

==== Code examples

[source,python]
----
relation.get_type()
----

[#_is_relation]
=== is_relation

==== Signature

[source,python]
----
is_relation() -> bool
----

==== Description

Checks if the concept is a `Relation`.

==== Returns

`bool`

==== Code examples

[source,python]
----
relation.is_relation()
----

[#_remove_player]
=== remove_player

==== Signature

[source,python]
----
abstract remove_player(transaction: TypeDBTransaction, role_type: RoleType, player: Thing) -> None
----

==== Description

Removes the association of the given instance that plays the given role in this `Relation`.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to no longer be played by the thing in this `Relation` a| `RoleType` a| 
a| `player` a| The instance to no longer play the role in this `Relation` a| `Thing` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
relation.remove_player(transaction, role_type, player)
----

// end::methods[]
