[#_RelationType]
=== RelationType

*Supertypes:*

* `ThingType`

Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles.

Other types can play roles in relations if it’s mentioned in their definition.

A relation type must specify at least one role.

// tag::methods[]
[#_RelationType_as_relation_type]
==== as_relation_type

[source,python]
----
as_relation_type() -> RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
relation_type.as_relation_type()
----

[#_RelationType_create]
==== create

[source,python]
----
create(transaction: TypeDBTransaction) -> Relation
----

Creates and returns an instance of this ``RelationType``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,python]
----
relation_type.create(transaction)
----

[#_RelationType_get_instances]
==== get_instances

[source,python]
----
get_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Relation]
----

Retrieves all direct and indirect (or direct only) ``Relation``s that are instances of this ``RelationType``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct relates only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Relation]`

[caption=""]
.Code examples
[source,python]
----
relation_type.get_instances(transaction, transitivity)
----

[#_RelationType_get_relates]
==== get_relates

[source,python]
----
get_relates(transaction: TypeDBTransaction, role_label: str | None = None, transitivity: Transitivity = Transitivity.TRANSITIVE) -> RoleType | None | Iterator[RoleType]
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance. If ``role_label`` is given, returns a corresponding ``RoleType`` or ``None``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_label` a| Label of the role we wish to retrieve (optional) a| `str \| None` a| `None`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited relates, ``Transitivity.EXPLICIT`` for direct relates only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`RoleType | None | Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
relation_type.get_relates(transaction, role_label, transitivity)
----

[#_RelationType_get_relates_overridden]
==== get_relates_overridden

[source,python]
----
get_relates_overridden(transaction: TypeDBTransaction, role_label: str) -> RoleType | None
----

Retrieves a ``RoleType`` that is overridden by the role with the ``role_label``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_label` a| Label of the role that overrides an inherited role a| `str` a| 
|===

[caption=""]
.Returns
`RoleType | None`

[caption=""]
.Code examples
[source,python]
----
relation_type.get_relates_overridden(transaction, role_label)
----

[#_RelationType_get_subtypes]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[RelationType]
----

Retrieves all direct and indirect (or direct only) subtypes of the ``RelationType``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[RelationType]`

[caption=""]
.Code examples
[source,python]
----
relation_type.get_subtypes(transaction, transitivity)
----

[#_RelationType_is_relation_type]
==== is_relation_type

[source,python]
----
is_relation_type() -> bool
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
relation_type.is_relation_type()
----

[#_RelationType_set_relates]
==== set_relates

[source,python]
----
set_relates(transaction: TypeDBTransaction, role_label: str, overridden_label: str | None = None) -> None
----

Sets the new role that this ``RelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_label` a| The new role for the ``RelationType`` to relate to a| `str` a| 
a| `overridden_label` a| The label being overridden, if applicable a| `str \| None` a| `None`
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
relation_type.set_relates(transaction, role_label)
relation_type.set_relates(transaction, role_label, overridden_label)
----

[#_RelationType_set_supertype]
==== set_supertype

[source,python]
----
set_supertype(transaction: TypeDBTransaction, super_relation_type: RelationType) -> None
----

Sets the supplied ``RelationType`` as the supertype of the current ``RelationType``.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `super_relation_type` a| The ``RelationType`` to set as the supertype of this ``RelationType`` a| `RelationType` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
relation_type.set_supertype(transaction, super_relation_type)
----

[#_RelationType_unset_relates]
==== unset_relates

[source,python]
----
unset_relates(transaction: TypeDBTransaction, role_label: str) -> None
----

Disallows this ``RelationType`` from relating to the given role.

[caption=""]
.Input parameters
[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_label` a| The role to not relate to the relation type. a| `str` a| 
|===

[caption=""]
.Returns
`None`

[caption=""]
.Code examples
[source,python]
----
relation_type.unset_relates(transaction, role_label)
----

// end::methods[]

