[#_Rule]
= Rule

== Description

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

== Properties

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `str` a| The unique label of the rule.
a| `then` a| `str` a| The single statement that constitutes the ‘then’ of the rule.
a| `when` a| `str` a| The statements that constitute the ‘when’ of the rule.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_delete]
=== delete

==== Signature

[source,python]
----
abstract delete(transaction: TypeDBTransaction) -> None
----

==== Description

Deletes this rule.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
rule.delete(transaction)
----

[#_is_deleted]
=== is_deleted

==== Signature

[source,python]
----
abstract is_deleted(transaction: TypeDBTransaction) -> bool
----

==== Description

Check if this rule has been deleted.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` a| 
|===

==== Returns

`bool`

==== Code examples

[source,python]
----
rule.is_deleted(transaction)
----

[#_set_label]
=== set_label

==== Signature

[source,python]
----
abstract set_label(transaction: TypeDBTransaction, new_label: str) -> None
----

==== Description

Renames the label of the rule. The new label must remain unique.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` a| 
a| `new_label` a| The new label to be given to the rule a| `str` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
rule.set_label(transaction, new_label)
----

// end::methods[]
