[#_ThingType]
= ThingType

*Supertypes:*

* `Type`

== Methods

// tag::methods[]
[#_get_instances]
=== get_instances

==== Signature

[source,python]
----
abstract get_instances(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Thing]
----

==== Description

Retrieves all direct and indirect (or direct only) ``Thing`` objects that are instances of this ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct instances only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

==== Returns

`Iterator[Thing]`

==== Code examples

[source,python]
----
thing_type.get_instances(transaction)
thing_type.get_instances(transaction, Transitivity.EXPLICIT)
----

[#_get_owns]
=== get_owns

==== Signature

[source,python]
----
abstract get_owns(transaction: TypeDBTransaction, value_type: ValueType | None = None, transitivity: Transitivity = Transitivity.TRANSITIVE, annotations: set[Annotation] | None = None) -> Iterator[AttributeType]
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `value_type` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType \| None` a| `None`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity` a| `Transitivity.TRANSITIVE`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `set[Annotation] \| None` a| `None`
|===

==== Returns

`Iterator[AttributeType]`

==== Code examples

[source,python]
----
thing_type.get_owns(transaction)
thing_type.get_owns(transaction, value_type,
                    transitivity=Transitivity.EXPLICIT,
                    annotations={Annotation.key()})
----

[#_get_owns_overridden]
=== get_owns_overridden

==== Signature

[source,python]
----
abstract get_owns_overridden(transaction: TypeDBTransaction, attribute_type: AttributeType) -> AttributeType | None
----

==== Description

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType` a| 
|===

==== Returns

`AttributeType | None`

==== Code examples

[source,python]
----
thing_type.get_owns_overridden(transaction, attribute_type)
----

[#_get_plays]
=== get_plays

==== Signature

[source,python]
----
abstract get_plays(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[RoleType]
----

==== Description

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

==== Returns

`Iterator[RoleType]`

==== Code examples

[source,python]
----
thing_type.get_plays(transaction)
thing_type.get_plays(transaction, Transitivity.EXPLICIT)
----

[#_get_plays_overridden]
=== get_plays_overridden

==== Signature

[source,python]
----
abstract get_plays_overridden(transaction: TypeDBTransaction, role_type: RoleType) -> RoleType | None
----

==== Description

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The ``RoleType`` that overrides an inherited role a| `RoleType` a| 
|===

==== Returns

`RoleType | None`

==== Code examples

[source,python]
----
thing_type.get_plays_overridden(transaction, role_type)
----

[#_get_subtypes]
=== get_subtypes

==== Signature

[source,python]
----
abstract get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[ThingType]
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

==== Returns

`Iterator[ThingType]`

==== Code examples

[source,python]
----
thing_type.get_subtypes(transaction)
thing_type.get_subtypes(transaction, Transitivity.EXPLICIT)
----

[#_get_supertype]
=== get_supertype

==== Signature

[source,python]
----
abstract get_supertype(transaction: TypeDBTransaction) -> ThingType | None
----

==== Description

Retrieves the most immediate supertype of the ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`ThingType | None`

==== Code examples

[source,python]
----
thing_type.get_supertype(transaction)
----

[#_get_supertypes]
=== get_supertypes

==== Signature

[source,python]
----
abstract get_supertypes(transaction: TypeDBTransaction) -> Iterator[ThingType]
----

==== Description

Retrieves all supertypes of the ``ThingType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`Iterator[ThingType]`

==== Code examples

[source,python]
----
thing_type.get_supertypes(transaction)
----

[#_get_syntax]
=== get_syntax

==== Signature

[source,python]
----
abstract get_syntax(transaction: TypeDBTransaction) -> str
----

==== Description

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`str`

==== Code examples

[source,python]
----
thing_type.get_syntax(transaction)
----

[#_is_thing_type]
=== is_thing_type

==== Signature

[source,python]
----
is_thing_type() -> bool
----

==== Description

Checks if the concept is a ``ThingType``.

==== Returns

`bool`

==== Code examples

[source,python]
----
thing_type.is_thing_type()
----

[#_set_abstract]
=== set_abstract

==== Signature

[source,python]
----
abstract set_abstract(transaction: TypeDBTransaction) -> None
----

==== Description

Set a ``ThingType`` to be abstract, meaning it cannot have instances.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.set_abstract(transaction)
----

[#_set_owns]
=== set_owns

==== Signature

[source,python]
----
abstract set_owns(transaction: TypeDBTransaction, attribute_type: AttributeType, overridden_type: AttributeType | None = None, annotations: set[Annotation] | None = None) -> None
----

==== Description

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType` a| 
a| `overridden_type` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType \| None` a| `None`
a| `annotations` a| Adds annotations to the ownership. a| `set[Annotation] \| None` a| `None`
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.set_owns(transaction, attribute_type)
thing_type.set_owns(transaction, attribute_type,
                    overridden_type=overridden_type,
                    annotations={Annotation.key()})
----

[#_set_plays]
=== set_plays

==== Signature

[source,python]
----
abstract set_plays(transaction: TypeDBTransaction, role_type: RoleType, overriden_type: RoleType | None = None) -> None
----

==== Description

Allows the instances of this ``ThingType`` to play the given role.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to be played by the instances of this type a| `RoleType` a| 
a| `overriden_type` a| The role type that this role overrides, if applicable a| `RoleType \| None` a| `None`
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.set_plays(transaction, role_type)
thing_type.set_plays(transaction, role_type, overridden_type)
----

[#_unset_abstract]
=== unset_abstract

==== Signature

[source,python]
----
abstract unset_abstract(transaction: TypeDBTransaction) -> None
----

==== Description

Set a ``ThingType`` to be non-abstract, meaning it can have instances.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.unset_abstract(transaction)
----

[#_unset_owns]
=== unset_owns

==== Signature

[source,python]
----
abstract unset_owns(transaction: TypeDBTransaction, attribute_type: AttributeType) -> None
----

==== Description

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.unset_owns(transaction, attribute_type)
----

[#_unset_plays]
=== unset_plays

==== Signature

[source,python]
----
abstract unset_plays(transaction: TypeDBTransaction, role_type: RoleType) -> None
----

==== Description

Disallows the instances of this ``ThingType`` from playing the given role.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to not be played by the instances of this type. a| `RoleType` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing_type.unset_plays(transaction, role_type)
----

// end::methods[]
