[#_Thing]
= Thing

*Supertypes:*

* `Concept`

== Methods

// tag::methods[]
[#_as_thing]
=== as_thing

==== Signature

[source,python]
----
as_thing() -> Thing
----

==== Description

Casts the concept to ``Thing``.

==== Returns

`Thing`

==== Code examples

[source,python]
----
thing.as_thing()
----

[#_delete]
=== delete

==== Signature

[source,python]
----
delete(transaction: TypeDBTransaction) -> None
----

==== Description

Deletes this ``Thing``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing.delete(transaction)
----

[#_get_has]
=== get_has

==== Signature

[source,python]
----
get_has(transaction: TypeDBTransaction, attribute_type: AttributeType = None, attribute_types: list[AttributeType] = None, annotations: set[Annotation] = frozenset({})) -> Iterator[Attribute]
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to filter the attributes by a| `AttributeType` a| `None`
a| `attribute_types` a| The ``AttributeType``s to filter the attributes by a| `list[AttributeType]` a| `None`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `set[Annotation]` a| `frozenset({})`
|===

==== Returns

`Iterator[Attribute]`

==== Code examples

[source,python]
----
thing.get_has(transaction)
thing.get_has(transaction, attribute_type=attribute_type,
              annotations=set(Annotation.key()))
----

[#_get_iid]
=== get_iid

==== Signature

[source,python]
----
get_iid() -> str
----

==== Description

Retrieves the unique id of the ``Thing``.

==== Returns

`str`

==== Code examples

[source,python]
----
thing.get_iid()
----

[#_get_playing]
=== get_playing

==== Signature

[source,python]
----
get_playing(transaction: TypeDBTransaction) -> Iterator[RoleType]
----

==== Description

Retrieves the roles that this ``Thing`` is currently playing.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`Iterator[RoleType]`

==== Code examples

[source,python]
----
thing.get_playing(transaction)
----

[#_get_relations]
=== get_relations

==== Signature

[source,python]
----
get_relations(transaction: TypeDBTransaction, role_types: list[RoleType] = None) -> Iterator[Relation]
----

==== Description

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_types` a| The list of roles to filter the relations by. a| `list[RoleType]` a| `None`
|===

==== Returns

`Iterator[Relation]`

==== Code examples

[source,python]
----
thing.get_relations(transaction, role_types)
----

[#_get_type]
=== get_type

==== Signature

[source,python]
----
get_type() -> ThingType
----

==== Description

Retrieves the type which this ``Thing`` belongs to.

==== Returns

`ThingType`

==== Code examples

[source,python]
----
thing.get_type()
----

[#_is_deleted]
=== is_deleted

==== Signature

[source,python]
----
is_deleted(transaction: TypeDBTransaction) -> bool
----

==== Description

Checks if this ``Thing`` is deleted.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

==== Returns

`bool`

==== Code examples

[source,python]
----
thing.is_deleted(transaction)
----

[#_is_inferred]
=== is_inferred

==== Signature

[source,python]
----
is_inferred() -> bool
----

==== Description

Checks if this ``Thing`` is inferred by a [Reasoning Rule].

==== Returns

`bool`

==== Code examples

[source,python]
----
thing.is_inferred()
----

[#_is_thing]
=== is_thing

==== Signature

[source,python]
----
is_thing() -> bool
----

==== Description

Checks if the concept is a ``Thing``.

==== Returns

`bool`

==== Code examples

[source,python]
----
thing.is_thing()
----

[#_set_has]
=== set_has

==== Signature

[source,python]
----
set_has(transaction: TypeDBTransaction, attribute: Attribute) -> None
----

==== Description

Assigns an ``Attribute`` to be owned by this ``Thing``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing.set_has(transaction, attribute)
----

[#_to_json]
=== to_json

==== Signature

[source,python]
----
to_json() -> Mapping[str, str]
----

==== Description

Retrieves a ``Thing`` as JSON.

==== Returns

`Mapping[str, str]`

==== Code examples

[source,python]
----
thing.to_json()
----

[#_unset_has]
=== unset_has

==== Signature

[source,python]
----
unset_has(transaction: TypeDBTransaction, attribute: Attribute) -> None
----

==== Description

Unassigns an ``Attribute`` from this ``Thing``.

==== Input parameters

[cols="~,~,~,~"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` a| 
|===

==== Returns

`None`

==== Code examples

[source,python]
----
thing.unset_has(transaction, attribute)
----

// end::methods[]
