[#_◆_query_define_]
==== query_define

[source,cpp]
----
struct VoidPromise* query_define(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Define query in the transaction.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_query_delete_]
==== query_delete

[source,cpp]
----
struct VoidPromise* query_delete(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Delete query in the transaction.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_query_explain_]
==== query_explain

[source,cpp]
----
struct ExplanationIterator* query_explain(struct Transaction* transaction, const struct Explainable* explainable, const struct Options* options)
----



Performs a TypeQL Explain query in the transaction.

 
  Parameters
 
 
  
   
    
     explainable
     The Explainable to be explained
    
    
     options
     Specify query options
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| 
a| `options` a| Specify query options a| 
|===

[caption=""]
.Returns
`struct ExplanationIterator*`

[#_◆_query_fetch_]
==== query_fetch

[source,cpp]
----
struct StringIterator* query_fetch(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Fetch query in the transaction.

[caption=""]
.Returns
`struct StringIterator*`

[#_◆_query_get_]
==== query_get

[source,cpp]
----
struct ConceptMapIterator* query_get(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Get (Get) query in the transaction.

[caption=""]
.Returns
`struct ConceptMapIterator*`

[#_◆_query_get_aggregate_]
==== query_get_aggregate

[source,cpp]
----
struct ConceptPromise* query_get_aggregate(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Get Aggregate query in the transaction.

[caption=""]
.Returns
`struct ConceptPromise*`

[#_◆_query_get_group_]
==== query_get_group

[source,cpp]
----
struct ConceptMapGroupIterator* query_get_group(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Get Group query in the transaction.

[caption=""]
.Returns
`struct ConceptMapGroupIterator*`

[#_◆_query_get_group_aggregate_]
==== query_get_group_aggregate

[source,cpp]
----
struct ValueGroupIterator* query_get_group_aggregate(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Get Group Aggregate query in the transaction.

[caption=""]
.Returns
`struct ValueGroupIterator*`

[#_◆_query_insert_]
==== query_insert

[source,cpp]
----
struct ConceptMapIterator* query_insert(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Insert query in the transaction.

[caption=""]
.Returns
`struct ConceptMapIterator*`

[#_◆_query_undefine_]
==== query_undefine

[source,cpp]
----
struct VoidPromise* query_undefine(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Undefine query in the transaction.

[caption=""]
.Returns
`struct VoidPromise*`

[#_◆_query_update_]
==== query_update

[source,cpp]
----
struct ConceptMapIterator* query_update(struct Transaction* transaction, const char* query, const struct Options* options)
----



Performs a TypeQL Update query in the transaction.

[caption=""]
.Returns
`struct ConceptMapIterator*`

