[#_TypeDBSession]
=== TypeDBSession

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `database` a| `Database` a| The database of the session. Examples session.database()
Copy
a| `options` a| `TypeDBOptions` a| Gets the options for the session
a| `type` a| `SessionType` a| The current session’s type (SCHEMA or DATA)
|===
// end::properties[]

// tag::methods[]
[#_TypeDBSession_close__]
==== close

[source,nodejs]
----
close(): Promise<void>
----

Closes the session. Before opening a new session, the session currently open should first be closed.

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
session.close()
----

[#_TypeDBSession_isOpen__]
==== isOpen

[source,nodejs]
----
isOpen(): boolean
----

Checks whether this session is open.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
session.isOpen()
----

[#_TypeDBSession_onClose__callback_______Promise_void__]
==== onClose

[source,nodejs]
----
onClose(callback): void
----

Registers a callback function which will be executed when this session is closed.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `callback` a| The callback function. a| `(() => Promise<void>)`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,nodejs]
----
session.onClose(function)
----

[#_TypeDBSession_onReopen__callback_______Promise_void__]
==== onReopen

[source,nodejs]
----
onReopen(callback): void
----

Registers a callback function which will be executed when this session is reopened. A session may be closed if it times out, or loses the connection to the database. In such situations, the session is reopened automatically when opening a new transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `callback` a| The callback function. a| `(() => Promise<void>)`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,nodejs]
----
session.onReopen(function)
----

[#_TypeDBSession_transaction__type_TransactionType__options_TypeDBOptions]
==== transaction

[source,nodejs]
----
transaction(type, options?): Promise<TypeDBTransaction>
----

Opens a transaction to perform read or write queries on the database connected to the session.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `type` a|  a| `TransactionType`
a| `options` a| Options for the session a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<TypeDBTransaction>`

[caption=""]
.Code examples
[source,nodejs]
----
session.transaction(transactionType, options)
----

// end::methods[]

