[#_TypeDBHttpDriver]
=== TypeDBHttpDriver

`Class(name=TypeDBHttpDriver, anchor=TypeDBHttpDriver, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=TypeDBHttpDriver, signature=new TypeDBHttpDriver(params: DriverParams): TypeDBHttpDriver, anchor=TypeDBHttpDriver_TypeDBHttpDriver_params_DriverParams, args=[Variable(name=params, anchor=null, defaultValue=null, description=null, type=DriverParams)], description=[], examples=[], mode=null, returnDescription=null, returnType=TypeDBHttpDriver), Method(name=analyze, signature=analyze( transactionId: string, query: string, analyzeOptions?: AnalyzeOptions, ): Promise<ApiResponse<AnalyzeResponse>>, anchor=TypeDBHttpDriver_analyze_transactionId_string_query_string_analyzeOptions_AnalyzeOptions, args=[Variable(name=transactionId, anchor=null, defaultValue=null, description=null, type=string), Variable(name=query, anchor=null, defaultValue=null, description=null, type=string), Variable(name=analyzeOptions, anchor=null, defaultValue=null, description=null, type=AnalyzeOptions)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<AnalyzeResponse>>), Method(name=closeTransaction, signature=closeTransaction(transactionId: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_closeTransaction_transactionId_string, args=[Variable(name=transactionId, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=commitTransaction, signature=commitTransaction(transactionId: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_commitTransaction_transactionId_string, args=[Variable(name=transactionId, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=createDatabase, signature=createDatabase(name: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_createDatabase_name_string, args=[Variable(name=name, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=createUser, signature=createUser(username: string, password: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_createUser_username_string_password_string, args=[Variable(name=username, anchor=null, defaultValue=null, description=null, type=string), Variable(name=password, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=deleteDatabase, signature=deleteDatabase(name: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_deleteDatabase_name_string, args=[Variable(name=name, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=deleteUser, signature=deleteUser(username: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_deleteUser_username_string, args=[Variable(name=username, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=getCurrentUser, signature=getCurrentUser(): Promise<ApiResponse<User>>, anchor=TypeDBHttpDriver_getCurrentUser_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<User>>), Method(name=getDatabase, signature=getDatabase(name: string): Promise<ApiResponse<Database>>, anchor=TypeDBHttpDriver_getDatabase_name_string, args=[Variable(name=name, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<Database>>), Method(name=getDatabases, signature=getDatabases(): Promise<ApiResponse<DatabasesListResponse>>, anchor=TypeDBHttpDriver_getDatabases_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<DatabasesListResponse>>), Method(name=getDatabaseSchema, signature=getDatabaseSchema(name: string): Promise<ApiResponse<string>>, anchor=TypeDBHttpDriver_getDatabaseSchema_name_string, args=[Variable(name=name, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<string>>), Method(name=getDatabaseTypeSchema, signature=getDatabaseTypeSchema(name: string): Promise<ApiResponse<string>>, anchor=TypeDBHttpDriver_getDatabaseTypeSchema_name_string, args=[Variable(name=name, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<string>>), Method(name=getUser, signature=getUser(username: string): Promise<ApiResponse<User>>, anchor=TypeDBHttpDriver_getUser_username_string, args=[Variable(name=username, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<User>>), Method(name=getUsers, signature=getUsers(): Promise<ApiResponse<UsersListResponse>>, anchor=TypeDBHttpDriver_getUsers_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<UsersListResponse>>), Method(name=health, signature=health(): Promise<ApiResponse>, anchor=TypeDBHttpDriver_health_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=oneShotQuery, signature=oneShotQuery( query: string, commit: boolean, databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>, anchor=TypeDBHttpDriver_oneShotQuery_query_string_commit_boolean_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions_queryOptions_QueryOptions, args=[Variable(name=query, anchor=null, defaultValue=null, description=null, type=string), Variable(name=commit, anchor=null, defaultValue=null, description=null, type=boolean), Variable(name=databaseName, anchor=null, defaultValue=null, description=null, type=string), Variable(name=transactionType, anchor=null, defaultValue=null, description=null, type=TransactionType), Variable(name=transactionOptions, anchor=null, defaultValue=null, description=null, type=TransactionOptions), Variable(name=queryOptions, anchor=null, defaultValue=null, description=null, type=QueryOptions)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<QueryResponse>>), Method(name=openTransaction, signature=openTransaction( databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, ): Promise<ApiResponse<TransactionOpenResponse>>, anchor=TypeDBHttpDriver_openTransaction_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions, args=[Variable(name=databaseName, anchor=null, defaultValue=null, description=null, type=string), Variable(name=transactionType, anchor=null, defaultValue=null, description=null, type=TransactionType), Variable(name=transactionOptions, anchor=null, defaultValue=null, description=null, type=TransactionOptions)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<TransactionOpenResponse>>), Method(name=query, signature=query( transactionId: string, query: string, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>, anchor=TypeDBHttpDriver_query_transactionId_string_query_string_queryOptions_QueryOptions, args=[Variable(name=transactionId, anchor=null, defaultValue=null, description=null, type=string), Variable(name=query, anchor=null, defaultValue=null, description=null, type=string), Variable(name=queryOptions, anchor=null, defaultValue=null, description=null, type=QueryOptions)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<QueryResponse>>), Method(name=rollbackTransaction, signature=rollbackTransaction(transactionId: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_rollbackTransaction_transactionId_string, args=[Variable(name=transactionId, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=updateUser, signature=updateUser(username: string, password: string): Promise<ApiResponse>, anchor=TypeDBHttpDriver_updateUser_username_string_password_string, args=[Variable(name=username, anchor=null, defaultValue=null, description=null, type=string), Variable(name=password, anchor=null, defaultValue=null, description=null, type=string)], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse>), Method(name=version, signature=version(): Promise<ApiResponse<VersionResponse>>, anchor=TypeDBHttpDriver_version_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=Promise<ApiResponse<VersionResponse>>)], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

// tag::methods[]
[#_TypeDBHttpDriver_TypeDBHttpDriver_params_DriverParams]
==== TypeDBHttpDriver

[source,typescript]
----
new TypeDBHttpDriver(params: DriverParams): TypeDBHttpDriver
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `params` a|  a| `DriverParams`
|===

[caption=""]
.Returns
`TypeDBHttpDriver`

[#_TypeDBHttpDriver_analyze_transactionId_string_query_string_analyzeOptions_AnalyzeOptions]
==== analyze

[source,typescript]
----
analyze( transactionId: string, query: string, analyzeOptions?: AnalyzeOptions, ): Promise<ApiResponse<AnalyzeResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
a| `query` a|  a| `string`
a| `analyzeOptions` a|  a| `AnalyzeOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<AnalyzeResponse>>`

[#_TypeDBHttpDriver_closeTransaction_transactionId_string]
==== closeTransaction

[source,typescript]
----
closeTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_commitTransaction_transactionId_string]
==== commitTransaction

[source,typescript]
----
commitTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_createDatabase_name_string]
==== createDatabase

[source,typescript]
----
createDatabase(name: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_createUser_username_string_password_string]
==== createUser

[source,typescript]
----
createUser(username: string, password: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
a| `password` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_deleteDatabase_name_string]
==== deleteDatabase

[source,typescript]
----
deleteDatabase(name: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_deleteUser_username_string]
==== deleteUser

[source,typescript]
----
deleteUser(username: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_getCurrentUser_]
==== getCurrentUser

[source,typescript]
----
getCurrentUser(): Promise<ApiResponse<User>>
----



[caption=""]
.Returns
`Promise<ApiResponse<User>>`

[#_TypeDBHttpDriver_getDatabase_name_string]
==== getDatabase

[source,typescript]
----
getDatabase(name: string): Promise<ApiResponse<Database>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<Database>>`

[#_TypeDBHttpDriver_getDatabaseSchema_name_string]
==== getDatabaseSchema

[source,typescript]
----
getDatabaseSchema(name: string): Promise<ApiResponse<string>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<string>>`

[#_TypeDBHttpDriver_getDatabaseTypeSchema_name_string]
==== getDatabaseTypeSchema

[source,typescript]
----
getDatabaseTypeSchema(name: string): Promise<ApiResponse<string>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<string>>`

[#_TypeDBHttpDriver_getDatabases_]
==== getDatabases

[source,typescript]
----
getDatabases(): Promise<ApiResponse<DatabasesListResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<DatabasesListResponse>>`

[#_TypeDBHttpDriver_getUser_username_string]
==== getUser

[source,typescript]
----
getUser(username: string): Promise<ApiResponse<User>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<User>>`

[#_TypeDBHttpDriver_getUsers_]
==== getUsers

[source,typescript]
----
getUsers(): Promise<ApiResponse<UsersListResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<UsersListResponse>>`

[#_TypeDBHttpDriver_health_]
==== health

[source,typescript]
----
health(): Promise<ApiResponse>
----



[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_oneShotQuery_query_string_commit_boolean_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions_queryOptions_QueryOptions]
==== oneShotQuery

[source,typescript]
----
oneShotQuery( query: string, commit: boolean, databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a|  a| `string`
a| `commit` a|  a| `boolean`
a| `databaseName` a|  a| `string`
a| `transactionType` a|  a| `TransactionType`
a| `transactionOptions` a|  a| `TransactionOptions`
a| `queryOptions` a|  a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<QueryResponse>>`

[#_TypeDBHttpDriver_openTransaction_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions]
==== openTransaction

[source,typescript]
----
openTransaction( databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, ): Promise<ApiResponse<TransactionOpenResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `databaseName` a|  a| `string`
a| `transactionType` a|  a| `TransactionType`
a| `transactionOptions` a|  a| `TransactionOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<TransactionOpenResponse>>`

[#_TypeDBHttpDriver_query_transactionId_string_query_string_queryOptions_QueryOptions]
==== query

[source,typescript]
----
query( transactionId: string, query: string, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
a| `query` a|  a| `string`
a| `queryOptions` a|  a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<QueryResponse>>`

[#_TypeDBHttpDriver_rollbackTransaction_transactionId_string]
==== rollbackTransaction

[source,typescript]
----
rollbackTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_updateUser_username_string_password_string]
==== updateUser

[source,typescript]
----
updateUser(username: string, password: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
a| `password` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_version_]
==== version

[source,typescript]
----
version(): Promise<ApiResponse<VersionResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<VersionResponse>>`

// end::methods[]

