[#_TypeDBHttpDriver]
[.doc-api-reference-driver]
=== TypeDBHttpDriver

`class`

// tag::methods[]
[#_TypeDBHttpDriver_TypeDBHttpDriver_params_DriverParams]
==== method <code>TypeDBHttpDriver</code>

[source,typescript]
----
new TypeDBHttpDriver(params: DriverParams): TypeDBHttpDriver
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `params` a|  a| `DriverParams`
|===

[caption=""]
.Returns
`TypeDBHttpDriver`

[#_TypeDBHttpDriver_analyze_transactionId_string_query_string_analyzeOptions_AnalyzeOptions]
==== method <code>analyze</code>

[source,typescript]
----
analyze( transactionId: string, query: string, analyzeOptions?: AnalyzeOptions, ): Promise<ApiResponse<AnalyzeResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
a| `query` a|  a| `string`
a| `analyzeOptions` a|  a| `AnalyzeOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<AnalyzeResponse>>`

[#_TypeDBHttpDriver_closeTransaction_transactionId_string]
==== method <code>closeTransaction</code>

[source,typescript]
----
closeTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_commitTransaction_transactionId_string]
==== method <code>commitTransaction</code>

[source,typescript]
----
commitTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_createDatabase_name_string]
==== method <code>createDatabase</code>

[source,typescript]
----
createDatabase(name: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_createUser_username_string_password_string]
==== method <code>createUser</code>

[source,typescript]
----
createUser(username: string, password: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
a| `password` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_deleteDatabase_name_string]
==== method <code>deleteDatabase</code>

[source,typescript]
----
deleteDatabase(name: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_deleteUser_username_string]
==== method <code>deleteUser</code>

[source,typescript]
----
deleteUser(username: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_getCurrentUser_]
==== method <code>getCurrentUser</code>

[source,typescript]
----
getCurrentUser(): Promise<ApiResponse<User>>
----



[caption=""]
.Returns
`Promise<ApiResponse<User>>`

[#_TypeDBHttpDriver_getDatabase_name_string]
==== method <code>getDatabase</code>

[source,typescript]
----
getDatabase(name: string): Promise<ApiResponse<Database>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<Database>>`

[#_TypeDBHttpDriver_getDatabaseSchema_name_string]
==== method <code>getDatabaseSchema</code>

[source,typescript]
----
getDatabaseSchema(name: string): Promise<ApiResponse<string>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<string>>`

[#_TypeDBHttpDriver_getDatabaseTypeSchema_name_string]
==== method <code>getDatabaseTypeSchema</code>

[source,typescript]
----
getDatabaseTypeSchema(name: string): Promise<ApiResponse<string>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<string>>`

[#_TypeDBHttpDriver_getDatabases_]
==== method <code>getDatabases</code>

[source,typescript]
----
getDatabases(): Promise<ApiResponse<DatabasesListResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<DatabasesListResponse>>`

[#_TypeDBHttpDriver_getUser_username_string]
==== method <code>getUser</code>

[source,typescript]
----
getUser(username: string): Promise<ApiResponse<User>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse<User>>`

[#_TypeDBHttpDriver_getUsers_]
==== method <code>getUsers</code>

[source,typescript]
----
getUsers(): Promise<ApiResponse<UsersListResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<UsersListResponse>>`

[#_TypeDBHttpDriver_health_]
==== method <code>health</code>

[source,typescript]
----
health(): Promise<ApiResponse>
----



[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_oneShotQuery_query_string_commit_boolean_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions_queryOptions_QueryOptions]
==== method <code>oneShotQuery</code>

[source,typescript]
----
oneShotQuery( query: string, commit: boolean, databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a|  a| `string`
a| `commit` a|  a| `boolean`
a| `databaseName` a|  a| `string`
a| `transactionType` a|  a| `TransactionType`
a| `transactionOptions` a|  a| `TransactionOptions`
a| `queryOptions` a|  a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<QueryResponse>>`

[#_TypeDBHttpDriver_openTransaction_databaseName_string_transactionType_TransactionType_transactionOptions_TransactionOptions]
==== method <code>openTransaction</code>

[source,typescript]
----
openTransaction( databaseName: string, transactionType: TransactionType, transactionOptions?: TransactionOptions, ): Promise<ApiResponse<TransactionOpenResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `databaseName` a|  a| `string`
a| `transactionType` a|  a| `TransactionType`
a| `transactionOptions` a|  a| `TransactionOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<TransactionOpenResponse>>`

[#_TypeDBHttpDriver_query_transactionId_string_query_string_queryOptions_QueryOptions]
==== method <code>query</code>

[source,typescript]
----
query( transactionId: string, query: string, queryOptions?: QueryOptions, ): Promise<ApiResponse<QueryResponse>>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
a| `query` a|  a| `string`
a| `queryOptions` a|  a| `QueryOptions`
|===

[caption=""]
.Returns
`Promise<ApiResponse<QueryResponse>>`

[#_TypeDBHttpDriver_rollbackTransaction_transactionId_string]
==== method <code>rollbackTransaction</code>

[source,typescript]
----
rollbackTransaction(transactionId: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionId` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_updateUser_username_string_password_string]
==== method <code>updateUser</code>

[source,typescript]
----
updateUser(username: string, password: string): Promise<ApiResponse>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a|  a| `string`
a| `password` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<ApiResponse>`

[#_TypeDBHttpDriver_version_]
==== method <code>version</code>

[source,typescript]
----
version(): Promise<ApiResponse<VersionResponse>>
----



[caption=""]
.Returns
`Promise<ApiResponse<VersionResponse>>`

// end::methods[]

