[#_IRelation]
=== IRelation

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

// tag::methods[]
[#_VoidPromise_TypeDB_Driver_Api_IRelation_AddPlayer___ITypeDBTransaction_transaction__IRoleType_roleType__IThing_player_]
==== AddPlayer

[source,cs]
----
VoidPromise AddPlayer(ITypeDBTransaction transaction, IRoleType roleType, IThing player)
----



Adds a new role player to play the given role in this ``IRelation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleType` a| The role to be played by the ``player`` a| `IRoleType`
a| `player` a| The thing to play the role a| `IThing`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
relation.AddPlayer(transaction, roleType, player).Resolve();
----

[#_IRelation_IConcept__TypeDB_Driver_Api_IRelation_AsRelation___]
==== AsRelation

[source,cs]
----
IRelation IConcept. AsRelation()
----



Casts the concept to ``IRelation``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IRelation IConcept.`

[caption=""]
.Code examples
[source,cs]
----
relation.AsRelation();
----

[#_Dictionary__IRoleType__ICollection__IThing_____TypeDB_Driver_Api_IRelation_GetPlayers___ITypeDBTransaction_transaction_]
==== GetPlayers

[source,cs]
----
Dictionary< IRoleType, ICollection< IThing > > GetPlayers(ITypeDBTransaction transaction)
----



Retrieves a mapping of all instances involved in the ``IRelation`` and the role each play.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`Dictionary< IRoleType, ICollection< IThing > >`

[caption=""]
.Code examples
[source,cs]
----
relation.GetPlayers(transaction)
----

[#_IEnumerable__IThing___TypeDB_Driver_Api_IRelation_GetPlayersByRoleType___ITypeDBTransaction_transaction__params_IRoleType___roleTypes_]
==== GetPlayersByRoleType

[source,cs]
----
IEnumerable< IThing > GetPlayersByRoleType(ITypeDBTransaction transaction, params IRoleType[] roleTypes)
----



Retrieves all role players of this ``IRelation``, optionally filtered by given role types.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleTypes` a| 0 or more role types a| `params IRoleType[]`
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[caption=""]
.Code examples
[source,cs]
----
relation.GetPlayersByRoleType(transaction, roleTypes);
----

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IRelation_GetRelating___ITypeDBTransaction_transaction_]
==== GetRelating

[source,cs]
----
IEnumerable< IRoleType > GetRelating(ITypeDBTransaction transaction)
----



Retrieves all role types currently played in this ``IRelation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[caption=""]
.Code examples
[source,cs]
----
relation.GetRelating(transaction);
----

[#_bool_IConcept__TypeDB_Driver_Api_IRelation_IsRelation___]
==== IsRelation

[source,cs]
----
bool IConcept. IsRelation()
----



Checks if the concept is a ``IRelation``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
relation.IsRelation();
----

[#_VoidPromise_TypeDB_Driver_Api_IRelation_RemovePlayer___ITypeDBTransaction_transaction__IRoleType_roleType__IThing_player_]
==== RemovePlayer

[source,cs]
----
VoidPromise RemovePlayer(ITypeDBTransaction transaction, IRoleType roleType, IThing player)
----



Removes the association of the given instance that plays the given role in this ``IRelation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleType` a| The role to no longer be played by the thing in this ``IRelation`` a| `IRoleType`
a| `player` a| The instance to no longer play the role in this ``IRelation`` a| `IThing`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
relation.RemovePlayer(transaction, roleType, player).Resolve();
----

// end::methods[]

