[#_IThing]
=== IThing

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IConcept`

// tag::methods[]
[#_IThing_IConcept__TypeDB_Driver_Api_IThing_AsThing___]
==== AsThing

[source,cs]
----
IThing IConcept. AsThing()
----



Casts the concept to ``IThing``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IThing IConcept.`

[caption=""]
.Code examples
[source,cs]
----
thing.AsThing();
----

[#_VoidPromise_TypeDB_Driver_Api_IThing_Delete___ITypeDBTransaction_transaction_]
==== Delete

[source,cs]
----
VoidPromise Delete(ITypeDBTransaction transaction)
----



Deletes this ``IThing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thing.Delete(transaction).Resolve();
----

[#_IEnumerable__IAttribute___TypeDB_Driver_Api_IThing_GetHas___ITypeDBTransaction_transaction__params_IAttributeType___attributeTypes_]
==== GetHas

[source,cs]
----
IEnumerable< IAttribute > GetHas(ITypeDBTransaction transaction, params IAttributeType[] attributeTypes)
----



Retrieves the ``IAttribute``s that this ``IThing`` owns, optionally filtered by ``IAttributeType``s.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attributeTypes` a| The ``IAttributeType``s to filter the attributes by a| `params IAttributeType[]`
|===

[caption=""]
.Returns
`IEnumerable< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
thing.GetHas(transaction);
thing.GetHas(transaction, attributeType);
----

[#_IEnumerable__IAttribute___TypeDB_Driver_Api_IThing_GetHas___ITypeDBTransaction_transaction__ICollection__Annotation___annotations_]
==== GetHas

[source,cs]
----
IEnumerable< IAttribute > GetHas(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieves the ``IAttribute``s that this ``IThing`` owns, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `ICollection< Annotation >`
|===

[caption=""]
.Returns
`IEnumerable< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
thing.GetHas(transaction);
thing.GetHas(transaction, new []{NewKey()});
----

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IThing_GetPlaying___ITypeDBTransaction_transaction_]
==== GetPlaying

[source,cs]
----
IEnumerable< IRoleType > GetPlaying(ITypeDBTransaction transaction)
----



Retrieves the roles that this ``IThing`` is currently playing.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[caption=""]
.Code examples
[source,cs]
----
thing.GetPlaying(transaction);
----

[#_IEnumerable__IRelation___TypeDB_Driver_Api_IThing_GetRelations___ITypeDBTransaction_transaction__params_IRoleType___roleTypes_]
==== GetRelations

[source,cs]
----
IEnumerable< IRelation > GetRelations(ITypeDBTransaction transaction, params IRoleType[] roleTypes)
----



Retrieves all the ``Relations`` which this ``IThing`` plays a role in, optionally filtered by one or more given roles.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleTypes` a| The array of roles to filter the relations by. a| `params IRoleType[]`
|===

[caption=""]
.Returns
`IEnumerable< IRelation >`

[caption=""]
.Code examples
[source,cs]
----
thing.GetRelations(transaction, roleTypes);
----

[#_string_TypeDB_Driver_Api_IThing_IID]
==== IID

[source,cs]
----
string TypeDB.Driver.Api.IThing.IID
----



The unique id of the ``IThing``.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
thing.IID;
----

[#_Promise__bool___TypeDB_Driver_Api_IThing_IsDeleted___ITypeDBTransaction_transaction_]
==== IsDeleted

[source,cs]
----
Promise< bool > IsDeleted(ITypeDBTransaction transaction)
----



Checks if this ``IThing`` is deleted.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`Promise< bool >`

[caption=""]
.Code examples
[source,cs]
----
thing.IsDeleted(transaction).Resolve();
----

[#_bool_TypeDB_Driver_Api_IThing_IsInferred___]
==== IsInferred

[source,cs]
----
bool IsInferred()
----



Checks if this ``IThing`` is inferred by a [Reasoning Rule].


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
thing.IsInferred();
----

[#_bool_IConcept__TypeDB_Driver_Api_IThing_IsThing___]
==== IsThing

[source,cs]
----
bool IConcept. IsThing()
----



Checks if the concept is a ``IThing``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
thing.IsThing();
----

[#_VoidPromise_TypeDB_Driver_Api_IThing_SetHas___ITypeDBTransaction_transaction__IAttribute_attribute_]
==== SetHas

[source,cs]
----
VoidPromise SetHas(ITypeDBTransaction transaction, IAttribute attribute)
----



Assigns an ``IAttribute`` to be owned by this ``IThing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attribute` a| The ``IAttribute`` to be owned by this ``IThing``. a| `IAttribute`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thing.SetHas(transaction, attribute).Resolve();
----

[#_IThingType_TypeDB_Driver_Api_IThing_Type]
==== Type

[source,cs]
----
IThingType TypeDB.Driver.Api.IThing.Type
----



The type which this ``IThing`` belongs to.


[caption=""]
.Returns
`IThingType`

[caption=""]
.Code examples
[source,cs]
----
thing.Type;
----

[#_VoidPromise_TypeDB_Driver_Api_IThing_UnsetHas___ITypeDBTransaction_transaction__IAttribute_attribute_]
==== UnsetHas

[source,cs]
----
VoidPromise UnsetHas(ITypeDBTransaction transaction, IAttribute attribute)
----



Unassigns an ``IAttribute`` from this ``IThing``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attribute` a| The ``IAttribute`` to be disowned from this ``IThing``. a| `IAttribute`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thing.UnsetHas(transaction, attribute).Resolve();
----

// end::methods[]

