[#_TypeDB_Driver_Api_IThing_Interface_Reference]
=== TypeDB.Driver.Api.IThing Interface Reference

*Package*: `TypeDB.Driver.Api.IThing Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IConcept`

// tag::methods[]
[#_IThing_IConcept__TypeDB_Driver_Api_IThing_AsThing___]
==== AsThing

[source,cs]
----
IThing IConcept. TypeDB.Driver.Api.IThing.AsThing()
----



Casts the concept to ``IThing``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IThing IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IThing_Delete___ITypeDBTransaction_transaction_]
==== Delete

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThing.Delete(ITypeDBTransaction transaction)
----



Deletes this ``IThing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_IEnumerable__IAttribute___TypeDB_Driver_Api_IThing_GetHas___ITypeDBTransaction_transaction__params_IAttributeType___attributeTypes_]
==== GetHas

[source,cs]
----
IEnumerable< IAttribute > TypeDB.Driver.Api.IThing.GetHas(ITypeDBTransaction transaction, params IAttributeType[] attributeTypes)
----



Retrieves the ``IAttribute``s that this ``IThing`` owns, optionally filtered by ``IAttributeType``s.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeTypes` a| The ``IAttributeType``s to filter the attributes by a| 
|===

[caption=""]
.Returns
`IEnumerable< IAttribute >`

[#_IEnumerable__IAttribute___TypeDB_Driver_Api_IThing_GetHas___ITypeDBTransaction_transaction__ICollection__Annotation___annotations_]
==== GetHas

[source,cs]
----
IEnumerable< IAttribute > TypeDB.Driver.Api.IThing.GetHas(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieves the ``IAttribute``s that this ``IThing`` owns, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| 
|===

[caption=""]
.Returns
`IEnumerable< IAttribute >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IThing_GetPlaying___ITypeDBTransaction_transaction_]
==== GetPlaying

[source,cs]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IThing.GetPlaying(ITypeDBTransaction transaction)
----



Retrieves the roles that this ``IThing`` is currently playing.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_IEnumerable__IRelation___TypeDB_Driver_Api_IThing_GetRelations___ITypeDBTransaction_transaction__params_IRoleType___roleTypes_]
==== GetRelations

[source,cs]
----
IEnumerable< IRelation > TypeDB.Driver.Api.IThing.GetRelations(ITypeDBTransaction transaction, params IRoleType[] roleTypes)
----



Retrieves all the ``Relations`` which this ``IThing`` plays a role in, optionally filtered by one or more given roles.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleTypes` a| The array of roles to filter the relations by. a| 
|===

[caption=""]
.Returns
`IEnumerable< IRelation >`

[#_Promise__bool___TypeDB_Driver_Api_IThing_IsDeleted___ITypeDBTransaction_transaction_]
==== IsDeleted

[source,cs]
----
Promise< bool > TypeDB.Driver.Api.IThing.IsDeleted(ITypeDBTransaction transaction)
----



Checks if this ``IThing`` is deleted.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< bool >`

[#_bool_TypeDB_Driver_Api_IThing_IsInferred___]
==== IsInferred

[source,cs]
----
bool TypeDB.Driver.Api.IThing.IsInferred()
----



Checks if this ``IThing`` is inferred by a [Reasoning Rule].


[caption=""]
.Returns
`bool`

[#_bool_IConcept__TypeDB_Driver_Api_IThing_IsThing___]
==== IsThing

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IThing.IsThing()
----



Checks if the concept is a ``IThing``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IThing_SetHas___ITypeDBTransaction_transaction__IAttribute_attribute_]
==== SetHas

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThing.SetHas(ITypeDBTransaction transaction, IAttribute attribute)
----



Assigns an ``IAttribute`` to be owned by this ``IThing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attribute` a| The ``IAttribute`` to be owned by this ``IThing``. a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThing_UnsetHas___ITypeDBTransaction_transaction__IAttribute_attribute_]
==== UnsetHas

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThing.UnsetHas(ITypeDBTransaction transaction, IAttribute attribute)
----



Unassigns an ``IAttribute`` from this ``IThing``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attribute` a| The ``IAttribute`` to be disowned from this ``IThing``. a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

