[#_TypeDB_Driver_Api_IRelation_Interface_Reference]
=== TypeDB.Driver.Api.IRelation Interface Reference

*Package*: `TypeDB.Driver.Api.IRelation Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

// tag::methods[]
[#_VoidPromise_TypeDB_Driver_Api_IRelation_AddPlayer___ITypeDBTransaction_transaction__IRoleType_roleType__IThing_player_]
==== AddPlayer

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IRelation.AddPlayer(ITypeDBTransaction transaction, IRoleType roleType, IThing player)
----



Adds a new role player to play the given role in this ``IRelation``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to be played by the ``player`` a| 
a| `player` a| The thing to play the role a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_IRelation_IConcept__TypeDB_Driver_Api_IRelation_AsRelation___]
==== AsRelation

[source,cs]
----
IRelation IConcept. TypeDB.Driver.Api.IRelation.AsRelation()
----



Casts the concept to ``IRelation``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IRelation IConcept.`

[#_Dictionary__IRoleType__ICollection__IThing_____TypeDB_Driver_Api_IRelation_GetPlayers___ITypeDBTransaction_transaction_]
==== GetPlayers

[source,cs]
----
Dictionary< IRoleType, ICollection< IThing > > TypeDB.Driver.Api.IRelation.GetPlayers(ITypeDBTransaction transaction)
----



Retrieves a mapping of all instances involved in the ``IRelation`` and the role each play.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Dictionary< IRoleType, ICollection< IThing > >`

[#_IEnumerable__IThing___TypeDB_Driver_Api_IRelation_GetPlayersByRoleType___ITypeDBTransaction_transaction__params_IRoleType___roleTypes_]
==== GetPlayersByRoleType

[source,cs]
----
IEnumerable< IThing > TypeDB.Driver.Api.IRelation.GetPlayersByRoleType(ITypeDBTransaction transaction, params IRoleType[] roleTypes)
----



Retrieves all role players of this ``IRelation``, optionally filtered by given role types.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleTypes` a| 0 or more role types a| 
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IRelation_GetRelating___ITypeDBTransaction_transaction_]
==== GetRelating

[source,cs]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IRelation.GetRelating(ITypeDBTransaction transaction)
----



Retrieves all role types currently played in this ``IRelation``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_bool_IConcept__TypeDB_Driver_Api_IRelation_IsRelation___]
==== IsRelation

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IRelation.IsRelation()
----



Checks if the concept is a ``IRelation``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IRelation_RemovePlayer___ITypeDBTransaction_transaction__IRoleType_roleType__IThing_player_]
==== RemovePlayer

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IRelation.RemovePlayer(ITypeDBTransaction transaction, IRoleType roleType, IThing player)
----



Removes the association of the given instance that plays the given role in this ``IRelation``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to no longer be played by the thing in this ``IRelation`` a| 
a| `player` a| The instance to no longer play the role in this ``IRelation`` a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

