[#_TypeDB_Driver_Api_IAttribute_Interface_Reference]
=== TypeDB.Driver.Api.IAttribute Interface Reference

*Package*: `TypeDB.Driver.Api.IAttribute Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_IAttribute_IConcept__TypeDB_Driver_Api_IAttribute_AsAttribute___]
==== AsAttribute

[source,cs]
----
IAttribute IConcept. TypeDB.Driver.Api.IAttribute.AsAttribute()
----



Casts the concept to ``IAttribute``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IAttribute IConcept.`

[#_IEnumerable__IThing___TypeDB_Driver_Api_IAttribute_GetOwners___ITypeDBTransaction_transaction_]
==== GetOwners

[source,cs]
----
IEnumerable< IThing > TypeDB.Driver.Api.IAttribute.GetOwners(ITypeDBTransaction transaction)
----



Retrieves the instances that own this ``IAttribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[#_IEnumerable__IThing___TypeDB_Driver_Api_IAttribute_GetOwners___ITypeDBTransaction_transaction__IThingType_ownerType_]
==== GetOwners

[source,cs]
----
IEnumerable< IThing > TypeDB.Driver.Api.IAttribute.GetOwners(ITypeDBTransaction transaction, IThingType ownerType)
----



Retrieves the instances that own this ``IAttribute``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `ownerType` a| Filter results for only owners of the given type a| 
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[#_bool_IConcept__TypeDB_Driver_Api_IAttribute_IsAttribute___]
==== IsAttribute

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IAttribute.IsAttribute()
----



Checks if the concept is an ``IAttribute``.


Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

// end::methods[]

