[#_methods_connection_consistencylevel]
=== consistencylevel

[#_Struct_ConsistencyLevel]
[.doc-api-reference-driver]
==== Struct ConsistencyLevel

`rust struct (pointer)`



``ConsistencyLevel`` is used to represent consistency levels in FFI. It combines ``ConsistencyLevelTag`` and optional fields to form an instance of the original enum. ``address`` is not null only when tag is ``ReplicaDependent``.

[#_consistency_level_drop]
==== function ``consistency_level_drop``

[source,c]
----
void consistency_level_drop(struct ConsistencyLevel* consistency_level)
----



Drops the ``ConsistencyLevel`` object.

[caption=""]
.Returns
`void`

[#_consistency_level_eventual]
==== function ``consistency_level_eventual``

[source,c]
----
struct ConsistencyLevel* consistency_level_eventual(void)
----



Creates an eventual ``ConsistencyLevel`` object.

[caption=""]
.Returns
`struct ConsistencyLevel*`

[#_consistency_level_replica_dependent]
==== function ``consistency_level_replica_dependent``

[source,c]
----
struct ConsistencyLevel* consistency_level_replica_dependent(const char* address)
----



Creates a replica dependent ``ConsistencyLevel`` object.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the replica to depend on. a| `const char*`
|===

[caption=""]
.Returns
`struct ConsistencyLevel*`

[#_consistency_level_strong]
==== function ``consistency_level_strong``

[source,c]
----
struct ConsistencyLevel* consistency_level_strong(void)
----



Creates a strong ``ConsistencyLevel`` object.

[caption=""]
.Returns
`struct ConsistencyLevel*`

