[#_methods_connection_database]
=== database

[#_Struct_Database]
==== Struct Database

`class`



A TypeDB database

[#_database_close]
==== database_close

[source,cpp]
----
void database_close(const struct Database* database)
----



Frees the native rust ``Database`` object

[caption=""]
.Returns
`void`

[#_database_delete]
==== database_delete

[source,cpp]
----
void database_delete(const struct Database* database)
----



Deletes this database.

[caption=""]
.Returns
`void`

[#_database_export_to_file]
==== database_export_to_file

[source,cpp]
----
void database_export_to_file(const struct Database* database, const char* schema_file, const char* data_file)
----



Export a database into a schema definition and a data files saved to the disk. This is a blocking operation and may take a significant amount of time depending on the database size.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The ``Database`` object to export from. a| `const struct Database*`
a| `schema_file` a| The path to the schema definition file to be created. a| `const char*`
a| `data_file` a| The path to the data file to be created. a| `const char*`
|===

[caption=""]
.Returns
`void`

[#_database_get_name]
==== database_get_name

[source,cpp]
----
char* database_get_name(const struct Database* database)
----



The database name as a string.

[caption=""]
.Returns
`char*`

[#_database_type_schema]
==== database_type_schema

[source,cpp]
----
char* database_type_schema(const struct Database* database)
----



The types in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
`char*`

