[#_methods_connection_driver]
=== driver

[#_Struct_DriverTlsConfig]
[.doc-api-reference-driver]
==== Struct DriverTlsConfig

`rust struct (pointer)`



TLS configuration for the TypeDB driver.

``DriverTlsConfig`` represents a fully constructed and validated TLS configuration. If TLS is enabled, the underlying TLS config is built eagerly at construction time, ensuring that no connection attempt can observe a partially-configured TLS state.

The driver defaults to using TLS with native system trust roots. This matches typical system and container deployments while still allowing explicit opt-out or custom PKI configuration.

[#_driver_close]
==== function ``driver_close``

[source,c]
----
void driver_close(struct TypeDBDriver* driver)
----



Closes the ``TypeDBDriver``. Before instantiating a new driver, the driver that’s currently open should first be closed. Closing a driver frees the underlying Rust object.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `struct TypeDBDriver*`
|===

[caption=""]
.Returns
`void`

[#_driver_force_close]
==== function ``driver_force_close``

[source,c]
----
void driver_force_close(struct TypeDBDriver* driver)
----



Forcibly closes the ``TypeDBDriver``. To be used in exceptional cases.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `struct TypeDBDriver*`
|===

[caption=""]
.Returns
`void`

[#_driver_is_open]
==== function ``driver_is_open``

[source,c]
----
bool driver_is_open(const struct TypeDBDriver* driver)
----



Checks whether this connection is presently open.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
|===

[caption=""]
.Returns
`bool`

[#_driver_new]
==== function ``driver_new``

[source,c]
----
struct TypeDBDriver* driver_new(const char* address, const struct Credentials* credentials, const struct DriverOptions* driver_options, const char* driver_lang)
----



Open a TypeDB Driver to a TypeDB server available at the provided address.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address on which the TypeDB Server is running a| `const char*`
a| `credentials` a| The ``Credentials`` to connect with a| `const struct Credentials*`
a| `driver_options` a| The ``DriverOptions`` to connect with a| `const struct DriverOptions*`
a| `driver_lang` a| The language of the driver connecting to the server. Nullable: pass NULL to default to "c". a| `const char*`
|===

[caption=""]
.Returns
`struct TypeDBDriver*`

[#_driver_new_with_address_translation]
==== function ``driver_new_with_address_translation``

[source,c]
----
struct TypeDBDriver* driver_new_with_address_translation(const char*const* public_addresses, const char*const* private_addresses, const struct Credentials* credentials, const struct DriverOptions* driver_options, const char* driver_lang)
----



Open a TypeDB Driver to a TypeDB cluster, using the provided address translation.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `public_addresses` a| A null-terminated array holding the replica addresses on for connection. a| `const char*const*`
a| `private_addresses` a| A null-terminated array holding the private replica addresses, configured on the server side. This array _must_ have the same length as ``public_addresses``. a| `const char*const*`
a| `credentials` a| The ``Credentials`` to connect with a| `const struct Credentials*`
a| `driver_options` a| The ``DriverOptions`` to connect with a| `const struct DriverOptions*`
a| `driver_lang` a| The language of the driver connecting to the server. Nullable: pass NULL to default to "c". a| `const char*`
|===

[caption=""]
.Returns
`struct TypeDBDriver*`

[#_driver_new_with_addresses]
==== function ``driver_new_with_addresses``

[source,c]
----
struct TypeDBDriver* driver_new_with_addresses(const char*const* addresses, const struct Credentials* credentials, const struct DriverOptions* driver_options, const char* driver_lang)
----



Open a TypeDB Driver to a TypeDB cluster available at the provided addresses.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a| A null-terminated array holding the server addresses on for connection a| `const char*const*`
a| `credentials` a| The ``Credentials`` to connect with a| `const struct Credentials*`
a| `driver_options` a| The ``DriverOptions`` to connect with a| `const struct DriverOptions*`
a| `driver_lang` a| The language of the driver connecting to the server. Nullable: pass NULL to default to "c". a| `const char*`
|===

[caption=""]
.Returns
`struct TypeDBDriver*`

[#_driver_primary_server]
==== function ``driver_primary_server``

[source,c]
----
struct Server* driver_primary_server(const struct TypeDBDriver* driver, const struct ServerRouting* server_routing)
----



Retrieves the server's primary server, if exists.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
a| `server_routing` a| The server routing directive to use for the operation. Auto if null. a| `const struct ServerRouting*`
|===

[caption=""]
.Returns
`struct Server*`

[#_driver_server_version]
==== function ``driver_server_version``

[source,c]
----
struct ServerVersion* driver_server_version(const struct TypeDBDriver* driver, const struct ServerRouting* server_routing)
----



Retrieves the server version and distribution information.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
a| `server_routing` a| The server routing directive to use for the operation. Auto if null. a| `const struct ServerRouting*`
|===

[caption=""]
.Returns
`struct ServerVersion*`

[#_driver_servers]
==== function ``driver_servers``

[source,c]
----
struct ServerIterator* driver_servers(const struct TypeDBDriver* driver, const struct ServerRouting* server_routing)
----



Retrieves the servers.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
a| `server_routing` a| The server routing directive to use for the operation. Auto if null. a| `const struct ServerRouting*`
|===

[caption=""]
.Returns
`struct ServerIterator*`

[#_driver_tls_config_drop]
==== function ``driver_tls_config_drop``

[source,c]
----
void driver_tls_config_drop(struct DriverTlsConfig* tls_config)
----



Frees the native rust ``DriverTlsConfig`` object.

[caption=""]
.Returns
`void`

[#_driver_tls_config_get_root_ca_path]
==== function ``driver_tls_config_get_root_ca_path``

[source,c]
----
char* driver_tls_config_get_root_ca_path(const struct DriverTlsConfig* tls_config)
----



Returns the TLS root CA set in this ``DriverTlsConfig`` object. Panics if a custom root CA is absent.

[caption=""]
.Returns
`char*`

[#_driver_tls_config_has_root_ca_path]
==== function ``driver_tls_config_has_root_ca_path``

[source,c]
----
bool driver_tls_config_has_root_ca_path(const struct DriverTlsConfig* tls_config)
----



Returns whether a custom root CA path is set.

[caption=""]
.Returns
`bool`

[#_driver_tls_config_is_enabled]
==== function ``driver_tls_config_is_enabled``

[source,c]
----
bool driver_tls_config_is_enabled(const struct DriverTlsConfig* tls_config)
----



Returns whether TLS is enabled.

[caption=""]
.Returns
`bool`

[#_driver_tls_config_new_disabled]
==== function ``driver_tls_config_new_disabled``

[source,c]
----
struct DriverTlsConfig* driver_tls_config_new_disabled(void)
----



Creates a new ``DriverTlsConfig`` with TLS disabled.

[caption=""]
.Returns
`struct DriverTlsConfig*`

[#_driver_tls_config_new_enabled_with_native_root_ca]
==== function ``driver_tls_config_new_enabled_with_native_root_ca``

[source,c]
----
struct DriverTlsConfig* driver_tls_config_new_enabled_with_native_root_ca(void)
----



Creates a new ``DriverTlsConfig`` with TLS enabled using system native trust roots.

[caption=""]
.Returns
`struct DriverTlsConfig*`

[#_driver_tls_config_new_enabled_with_root_ca_path]
==== function ``driver_tls_config_new_enabled_with_root_ca_path``

[source,c]
----
struct DriverTlsConfig* driver_tls_config_new_enabled_with_root_ca_path(const char* tls_root_ca)
----



Creates a new ``DriverTlsConfig`` with TLS enabled using a custom root CA certificate (PEM).

[caption=""]
.Returns
`struct DriverTlsConfig*`

[#_init_logging]
==== function ``init_logging``

[source,c]
----
void init_logging(void)
----



Enables logging in the TypeDB driver.

This function sets up tracing with two environment variables:

 ``TYPEDB_DRIVER_LOG``: Fine-grained control using the same syntax as ``RUST_LOG``. Example: ``TYPEDB_DRIVER_LOG=typedb_driver=debug,typedb_driver_clib=trace``
 ``TYPEDB_DRIVER_LOG_LEVEL``: Simple log level that applies to both ``typedb_driver`` and ``typedb_driver_clib`` crates. Overrides any settings from ``TYPEDB_DRIVER_LOG``. Example: ``TYPEDB_DRIVER_LOG_LEVEL=debug``


If neither is set, the default level is INFO for driver crates.

The logging is initialized only once to prevent multiple initializations in applications that create multiple drivers.

[caption=""]
.Returns
`void`

