[#_methods_connection_driveroptions]
=== driveroptions

[#_Struct_DriverOptions]
[.doc-api-reference-driver]
==== Struct DriverOptions

`rust struct (pointer)`



TypeDB driver connection options. DriverOptions object can be used to override the default driver behavior while connecting to TypeDB.


[#_driver_options_drop]
==== function ``driver_options_drop``

[source,c]
----
void driver_options_drop(struct DriverOptions* driver_options)
----



Frees the native rust ``DriverOptions`` object.

[caption=""]
.Returns
`void`

[#_driver_options_get_primary_failover_retries]
==== function ``driver_options_get_primary_failover_retries``

[source,c]
----
int64_t driver_options_get_primary_failover_retries(const struct DriverOptions* options)
----



Returns the value set for the primary failover retries limit in this ``DriverOptions`` object. Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles.

[caption=""]
.Returns
`int64_t`

[#_driver_options_get_server_discovery_attempts]
==== function ``driver_options_get_server_discovery_attempts``

[source,c]
----
int64_t driver_options_get_server_discovery_attempts(const struct DriverOptions* options)
----



Returns the value set for the server discovery attempts limit in this ``DriverOptions`` object. Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most:

 {limit} operations are performed if the limit &lt;= the number of replicas.
 {number of replicas} operations are performed if the limit &gt; the number of replicas.
 {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown.


[caption=""]
.Returns
`int64_t`

[#_driver_options_get_request_timeout_millis]
==== function ``driver_options_get_request_timeout_millis``

[source,c]
----
int64_t driver_options_get_request_timeout_millis(const struct DriverOptions* options)
----



Returns the request timeout in milliseconds set for this ``DriverOptions`` object. Specifies the maximum time to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits).

[caption=""]
.Returns
`int64_t`

[#_driver_options_get_tls_config]
==== function ``driver_options_get_tls_config``

[source,c]
----
struct DriverTlsConfig* driver_options_get_tls_config(const struct DriverOptions* options)
----



Returns the TLS Config set for this ``DriverOptions`` object. Specifies the TLS configuration of the connection to TypeDB.

[caption=""]
.Returns
`struct DriverTlsConfig*`

[#_driver_options_get_use_replication]
==== function ``driver_options_get_use_replication``

[source,c]
----
bool driver_options_get_use_replication(const struct DriverOptions* options)
----



Returns the value set for the replication usage flag in this ``DriverOptions`` object. Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address.

[caption=""]
.Returns
`bool`

[#_driver_options_has_server_discovery_attempts]
==== function ``driver_options_has_server_discovery_attempts``

[source,c]
----
bool driver_options_has_server_discovery_attempts(const struct DriverOptions* options)
----



Checks whether the server discovery attempts limit was explicitly set for this ``DriverOptions`` object.

[caption=""]
.Returns
`bool`

[#_driver_options_new]
==== function ``driver_options_new``

[source,c]
----
struct DriverOptions* driver_options_new(const struct DriverTlsConfig* tls_config)
----



Creates a new ``DriverOptions`` for connecting to TypeDB Server using custom TLS settings. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.

[caption=""]
.Returns
`struct DriverOptions*`

[#_driver_options_set_primary_failover_retries]
==== function ``driver_options_set_primary_failover_retries``

[source,c]
----
void driver_options_set_primary_failover_retries(struct DriverOptions* options, int64_t primary_failover_retries)
----



Limits the number of attempts to redirect a strongly consistent request to another primary replica in case of a failure due to the change of replica roles. Defaults to 1.

[caption=""]
.Returns
`void`

[#_driver_options_set_server_discovery_attempts]
==== function ``driver_options_set_server_discovery_attempts``

[source,c]
----
void driver_options_set_server_discovery_attempts(struct DriverOptions* options, int64_t server_discovery_attempts)
----



Limits the number of driver attempts to discover a single working replica to perform an operation in case of a replica unavailability. Every replica is tested once, which means that at most:

 {limit} operations are performed if the limit &lt;= the number of replicas.
 {number of replicas} operations are performed if the limit &gt; the number of replicas.
 {number of replicas} operations are performed if the limit is None. Affects every eventually consistent operation, including redirect failover, when the new primary replica is unknown. If not set, the maximum (practically unlimited) value is used.


[caption=""]
.Returns
`void`

[#_driver_options_set_request_timeout_millis]
==== function ``driver_options_set_request_timeout_millis``

[source,c]
----
void driver_options_set_request_timeout_millis(struct DriverOptions* options, int64_t timeout_millis)
----



Sets the maximum time (in milliseconds) to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). Set to 0 to disable the timeout (not recommended for production use). Defaults to 2 hours (7200000 milliseconds).

[caption=""]
.Returns
`void`

[#_driver_options_set_tls_config]
==== function ``driver_options_set_tls_config``

[source,c]
----
void driver_options_set_tls_config(struct DriverOptions* options, const struct DriverTlsConfig* tls_config)
----



Overrides the TLS configuration on ``DriverOptions``. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.

[caption=""]
.Returns
`void`

[#_driver_options_set_use_replication]
==== function ``driver_options_set_use_replication``

[source,c]
----
void driver_options_set_use_replication(struct DriverOptions* options, bool use_replication)
----



Specifies whether the connection to TypeDB can use cluster replicas provided by the server or it should be limited to a single configured address. Defaults to true.

[caption=""]
.Returns
`void`

