[#_methods_connection_serverreplica]
=== serverreplica

[#_Struct_ServerReplica]
[.doc-api-reference-driver]
==== Struct ServerReplica

`rust struct (pointer)`



The metadata and state of an individual raft replica of a driver connection.

[#_server_replica_drop]
==== function ``server_replica_drop``

[source,c]
----
void server_replica_drop(struct ServerReplica* replica_info)
----



Frees the native rust ``ServerReplica`` object.

[caption=""]
.Returns
`void`

[#_server_replica_get_address]
==== function ``server_replica_get_address``

[source,c]
----
char* server_replica_get_address(const struct ServerReplica* replica_info)
----



Returns the address this replica is hosted at.

[caption=""]
.Returns
`char*`

[#_server_replica_get_id]
==== function ``server_replica_get_id``

[source,c]
----
int64_t server_replica_get_id(const struct ServerReplica* replica_info)
----



Returns the id of this replica.

[caption=""]
.Returns
`int64_t`

[#_server_replica_get_role]
==== function ``server_replica_get_role``

[source,c]
----
enum ReplicaRole server_replica_get_role(const struct ServerReplica* replica_info)
----



Returns whether this is the primary replica of the raft cluster or any of the supporting roles.

[caption=""]
.Returns
`enum ReplicaRole`

[#_server_replica_get_term]
==== function ``server_replica_get_term``

[source,c]
----
int64_t server_replica_get_term(const struct ServerReplica* replica_info)
----



Returns the raft protocol ‘term’ of this replica.

[caption=""]
.Returns
`int64_t`

[#_server_replica_has_role]
==== function ``server_replica_has_role``

[source,c]
----
bool server_replica_has_role(const struct ServerReplica* replica_info)
----



Returns whether the role of this replica is set.

[caption=""]
.Returns
`bool`

[#_server_replica_has_term]
==== function ``server_replica_has_term``

[source,c]
----
bool server_replica_has_term(const struct ServerReplica* replica_info)
----



Returns whether the raft protocol ‘term’ of this replica exists.

[caption=""]
.Returns
`bool`

[#_server_replica_is_primary]
==== function ``server_replica_is_primary``

[source,c]
----
bool server_replica_is_primary(const struct ServerReplica* replica_info)
----



Checks whether this is the primary replica of the raft cluster.

[caption=""]
.Returns
`bool`

