[#_methods_connection_user]
=== user

[#_user_delete]
==== function ``user_delete``

[source,c]
----
void user_delete(struct User* user, const struct ConsistencyLevel* consistency_level)
----



Deletes this user.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `user` a| The ``User`` to delete. a| `struct User*`
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible if null. a| `const struct ConsistencyLevel*`
|===

[caption=""]
.Returns
`void`

[#_user_drop]
==== function ``user_drop``

[source,c]
----
void user_drop(struct User* user)
----



Frees the native rust ``User`` object.

[caption=""]
.Returns
`void`

[#_user_get_name]
==== function ``user_get_name``

[source,c]
----
char* user_get_name(struct User* user)
----



Returns the name of this user.

[caption=""]
.Returns
`char*`

[#_user_update_password]
==== function ``user_update_password``

[source,c]
----
void user_update_password(struct User* user, const char* password, const struct ConsistencyLevel* consistency_level)
----



Updates the password for the current authenticated user.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `user` a| The user to update the password of - must be the current user. a| `struct User*`
a| `user_manager` a| The ``UserManager`` object on this connection. a| 
a| `password_old` a| The current password of this user. a| 
a| `password_new` a| The new password. a| 
a| `consistency_level` a| The consistency level to use for the operation. Strongest possible if null. a| `const struct ConsistencyLevel*`
|===

[caption=""]
.Returns
`void`

