[#_methods_connection_users]
=== users

[#_users_all]
==== function ``users_all``

[source,c]
----
struct UserIterator* users_all(const struct TypeDBDriver* driver)
----



Retrieves all users which exist on the TypeDB server.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
|===

[caption=""]
.Returns
`struct UserIterator*`

[#_users_contains]
==== function ``users_contains``

[source,c]
----
bool users_contains(const struct TypeDBDriver* driver, const char* username)
----



Checks if a user with the given name exists.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
a| `username` a| The username of the user. a| `const char*`
|===

[caption=""]
.Returns
`bool`

[#_users_create]
==== function ``users_create``

[source,c]
----
void users_create(const struct TypeDBDriver* driver, const char* username, const char* password)
----



Creates a user with the given name &amp; password.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The username of the created user. a| `const char*`
a| `password` a| The password of the created user. a| `const char*`
|===

[caption=""]
.Returns
`void`

[#_users_get]
==== function ``users_get``

[source,c]
----
struct User* users_get(const struct TypeDBDriver* driver, const char* username)
----



Retrieves a user with the given name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
a| `username` a| The username of the user. a| `const char*`
|===

[caption=""]
.Returns
`struct User*`

[#_users_get_current]
==== function ``users_get_current``

[source,c]
----
struct User* users_get_current(const struct TypeDBDriver* driver)
----



Retrieves the username of the user who opened this connection.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `driver` a| The ``TypeDBDriver`` object. a| `const struct TypeDBDriver*`
|===

[caption=""]
.Returns
`struct User*`

