[#_ConceptRowsQueryResponseLegacy]
=== ConceptRowsQueryResponseLegacy

`Class(name=ConceptRowsQueryResponseLegacy, anchor=ConceptRowsQueryResponseLegacy, enumConstants=[], description=[], examples=[], fields=[Variable(name=answers, anchor=null, defaultValue=null, description=null, type=ConceptRowAnswer), Variable(name=answerType, anchor=null, defaultValue=null, description=null, type="conceptRows"), Variable(name=comment, anchor=null, defaultValue=null, description=null, type=string), Variable(name=query, anchor=null, defaultValue=null, description=null, type=QueryStructureLegacy), Variable(name=queryType, anchor=null, defaultValue=null, description=null, type=QueryType)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `answerType` a| `"conceptRows"` a| 
a| `answers` a| `ConceptRowAnswer` a| 
a| `comment` a| `string` a| 
a| `query` a| `QueryStructureLegacy` a| 
a| `queryType` a| `QueryType` a| 
|===
// end::properties[]

