[#_ConstraintExpressionLegacy]
==== ConstraintExpressionLegacy

`Class(name=ConstraintExpressionLegacy, anchor=ConstraintExpressionLegacy, enumConstants=[], description=[], examples=[], fields=[Variable(name=arguments, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=assigned, anchor=null, defaultValue=null, description=null, type=ConstraintVertexVariable), Variable(name=tag, anchor=null, defaultValue=null, description=null, type="expression"), Variable(name=text, anchor=null, defaultValue=null, description=null, type=string), Variable(name=textSpan, anchor=null, defaultValue=null, description=null, type=ConstraintSpan)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `arguments` a| `ConstraintVertexVariable` a| 
a| `assigned` a| `ConstraintVertexVariable` a| 
a| `tag` a| `"expression"` a| 
a| `text` a| `string` a| 
a| `textSpan` a| `ConstraintSpan` a| 
|===
// end::properties[]

