[#_Concept]
=== Concept

*Package*: `com.vaticle.typedb.driver.api.concept`

// tag::methods[]
[#_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isType();
----

[#_isThingType_]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isThingType();
----

[#_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isEntityType();
----

[#_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRoleType();
----

[#_isThing_]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isThing();
----

[#_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isEntity();
----

[#_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRelation();
----

[#_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isAttribute();
----

[#_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isValue();
----

[#_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


.Returns
`Type`

.Code examples
[source,java]
----
concept.asType();
----

[#_asThingType_]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


.Returns
`ThingType`

.Code examples
[source,java]
----
concept.asThingType();
----

[#_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


.Returns
`EntityType`

.Code examples
[source,java]
----
concept.asEntityType();
----

[#_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


.Returns
`RelationType`

.Code examples
[source,java]
----
concept.asRelationType();
----

[#_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


.Returns
`AttributeType`

.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


.Returns
`RoleType`

.Code examples
[source,java]
----
concept.asRoleType();
----

[#_asThing_]
==== asThing

[source,java]
----
default Thing asThing()
----

Casts the concept to ``Thing``. 


.Returns
`Thing`

.Code examples
[source,java]
----
concept.asThing();
----

[#_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


.Returns
`Entity`

.Code examples
[source,java]
----
concept.asEntity();
----

[#_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


.Returns
`Relation`

.Code examples
[source,java]
----
concept.asRelation();
----

[#_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


.Returns
`Attribute`

.Code examples
[source,java]
----
concept.asAttribute();
----

[#_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


.Returns
`Value`

.Code examples
[source,java]
----
concept.asValue();
----

[#_toJSON_]
==== toJSON

[source,java]
----
@CheckReturnValue
com.eclipsesource.json.JsonObject toJSON()
----

Retrieves the concept as JSON. 


.Returns
`com.eclipsesource.json.JsonObject`

.Code examples
[source,java]
----
concept.toJSON();
----

// end::methods[]
