[#_ConceptMap]
= ConceptMap

*Package*: `com.vaticle.typedb.driver.api.answer`

== Description

Contains a mapping of variables to concepts.

== Methods

// tag::methods[]
[#_variables_]
=== variables

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<java.lang.String> variables()
----

==== Description

Produces a stream over all variables in this `ConceptMap`. 


==== Returns

`java.util.stream.Stream<java.lang.String>`

==== Code examples

[source,java]
----
conceptMap.variables();
----

[#_concepts_]
=== concepts

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Concept> concepts()
----

==== Description

Produces a stream over all concepts in this `ConceptMap`. 


==== Returns

`java.util.stream.Stream<Concept>`

==== Code examples

[source,java]
----
conceptMap.concepts();
----

[#_get_java_lang_String]
=== get

==== Signature

[source,java]
----
@CheckReturnValue
Concept get​(java.lang.String variable)
----

==== Description

Retrieves a concept for a given variable name. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String` 
|===

==== Returns

`Concept`

==== Code examples

[source,java]
----
conceptMap.get(variable);
----

[#_toJSON_]
=== toJSON

==== Signature

[source,java]
----
@CheckReturnValue
default com.eclipsesource.json.JsonObject toJSON()
----

==== Description

Retrieves this `ConceptMap` as JSON. 


==== Returns

`com.eclipsesource.json.JsonObject`

==== Code examples

[source,java]
----
conceptMap.toJSON();
----

[#_explainables_]
=== explainables

==== Signature

[source,java]
----
ConceptMap.Explainables explainables()
----

==== Description

Gets the `Explainables` object for this `ConceptMap`, exposing which of the concepts in this `ConceptMap` are explainable. 


==== Returns

`ConceptMap.Explainables`

==== Code examples

[source,java]
----
conceptMap.explainables();
----

// end::methods[]
