[#_ConceptManager]
= ConceptManager

*Package*: `com.vaticle.typedb.driver.api.concept`

== Description

Provides access for all Concept API methods.

== Methods

// tag::methods[]
[#_getRootEntityType_]
=== getRootEntityType

==== Signature

[source,java]
----
@CheckReturnValue
EntityType getRootEntityType()
----

==== Description

Retrieves the root `EntityType`, “entity”. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
transaction.concepts().getRootEntityType();
----

[#_getRootRelationType_]
=== getRootRelationType

==== Signature

[source,java]
----
@CheckReturnValue
RelationType getRootRelationType()
----

==== Description

Retrieve the root `RelationType`, “relation”. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
transaction.concepts().getRootRelationType();
----

[#_getRootAttributeType_]
=== getRootAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
AttributeType getRootAttributeType()
----

==== Description

Retrieve the root `AttributeType`, “attribute”. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
transaction.concepts().getRootAttributeType();
----

[#_getEntityType_java_lang_String]
=== getEntityType

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
EntityType getEntityType​(java.lang.String label)
----

==== Description

Retrieves an `EntityType` by its label. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `EntityType` to retrieve a| `java.lang.String` 
|===

==== Returns

`EntityType`

==== Code examples

[source,java]
----
transaction.concepts().getEntityType(label);
----

[#_getRelationType_java_lang_String]
=== getRelationType

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
RelationType getRelationType​(java.lang.String label)
----

==== Description

Retrieves a `RelationType` by its label. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `RelationType` to retrieve a| `java.lang.String` 
|===

==== Returns

`RelationType`

==== Code examples

[source,java]
----
transaction.concepts().getRelationType(label);
----

[#_getAttributeType_java_lang_String]
=== getAttributeType

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
AttributeType getAttributeType​(java.lang.String label)
----

==== Description

Retrieves an `AttributeType` by its label. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `AttributeType` to retrieve a| `java.lang.String` 
|===

==== Returns

`AttributeType`

==== Code examples

[source,java]
----
transaction.concepts().getAttributeType(label)
----

[#_putEntityType_java_lang_String]
=== putEntityType

==== Signature

[source,java]
----
EntityType putEntityType​(java.lang.String label)
----

==== Description

Creates a new `EntityType` if none exists with the given label, otherwise retrieves the existing one. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `EntityType` to create or retrieve a| `java.lang.String` 
|===

==== Returns

`EntityType`

==== Code examples

[source,java]
----
transaction.concepts().putEntityType(label);
----

[#_putRelationType_java_lang_String]
=== putRelationType

==== Signature

[source,java]
----
RelationType putRelationType​(java.lang.String label)
----

==== Description

Creates a new `RelationType` if none exists with the given label, otherwise retrieves the existing one. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `RelationType` to create or retrieve a| `java.lang.String` 
|===

==== Returns

`RelationType`

==== Code examples

[source,java]
----
transaction.concepts().putRelationType(label);
----

[#_putAttributeType_java_lang_String_com_vaticle_typedb_driver_api_concept_value_Value_Type]
=== putAttributeType

==== Signature

[source,java]
----
AttributeType putAttributeType​(java.lang.String label,
                               Value.Type valueType)
----

==== Description

Creates a new `AttributeType` if none exists with the given label, or retrieves the existing one. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the `AttributeType` to create or retrieve a| `java.lang.String` 
a| `valueType` a| The value type of the `AttributeType` to create a| `Value.Type` 
|===

==== Returns

`AttributeType`

==== Code examples

[source,java]
----
await transaction.concepts().putAttributeType(label, valueType);
----

[#_getEntity_java_lang_String]
=== getEntity

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
Entity getEntity​(java.lang.String iid)
----

==== Description

Retrieves an `Entity` by its iid. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the `Entity` to retrieve a| `java.lang.String` 
|===

==== Returns

`Entity`

==== Code examples

[source,java]
----
transaction.concepts().getEntity(iid);
----

[#_getRelation_java_lang_String]
=== getRelation

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
Relation getRelation​(java.lang.String iid)
----

==== Description

Retrieves a `Relation` by its iid. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the `Relation` to retrieve a| `java.lang.String` 
|===

==== Returns

`Relation`

==== Code examples

[source,java]
----
transaction.concepts().getRelation(iid);
----

[#_getAttribute_java_lang_String]
=== getAttribute

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
Attribute getAttribute​(java.lang.String iid)
----

==== Description

Retrieves an `Attribute` by its iid. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the `Attribute` to retrieve a| `java.lang.String` 
|===

==== Returns

`Attribute`

==== Code examples

[source,java]
----
transaction.concepts().getAttribute(iid);
----

[#_getSchemaExceptions_]
=== getSchemaExceptions

==== Signature

[source,java]
----
@CheckReturnValue
java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException> getSchemaExceptions()
----

==== Description

Retrieves a list of all exceptions for the current transaction. 


==== Returns

`java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException>`

==== Code examples

[source,java]
----
transaction.concepts().getSchemaException();
----

// end::methods[]
