[#_ConceptMap_Explainables]
= ConceptMap.Explainables

*Package*: `com.vaticle.typedb.driver.api.answer`

== Description

Contains explainable objects.

== Methods

// tag::methods[]
[#_relation_java_lang_String]
=== relation

==== Signature

[source,java]
----
ConceptMap.Explainable relation​(java.lang.String variable)
----

==== Description

Retrieves the explainable relation with the given variable name. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String` 
|===

==== Returns

`ConceptMap.Explainable`

==== Code examples

[source,java]
----
conceptMap.explainables().relation(variable);
----

[#_attribute_java_lang_String]
=== attribute

==== Signature

[source,java]
----
ConceptMap.Explainable attribute​(java.lang.String variable)
----

==== Description

Retrieves the explainable attribute with the given variable name. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String` 
|===

==== Returns

`ConceptMap.Explainable`

==== Code examples

[source,java]
----
conceptMap.explainables().attribute(variable);
----

[#_ownership_java_lang_String_java_lang_String]
=== ownership

==== Signature

[source,java]
----
ConceptMap.Explainable ownership​(java.lang.String owner,
                                 java.lang.String attribute)
----

==== Description

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `owner` a| The string representation of the owner variable a| `java.lang.String` 
a| `attribute` a| The string representation of the attribute variable a| `java.lang.String` 
|===

==== Returns

`ConceptMap.Explainable`

==== Code examples

[source,java]
----
conceptMap.explainables().ownership(owner, attribute);
----

[#_relations_]
=== relations

==== Signature

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>> relations()
----

==== Description

Retrieves all of this `ConceptMap`’s explainable relations. 


==== Returns

`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>>`

==== Code examples

[source,java]
----
conceptMap.explainables().relations();
----

[#_attributes_]
=== attributes

==== Signature

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>> attributes()
----

==== Description

Retrieves all of this `ConceptMap`’s explainable attributes. 


==== Returns

`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>>`

==== Code examples

[source,java]
----
conceptMap.explainables().attributes();
----

[#_ownerships_]
=== ownerships

==== Signature

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<com.vaticle.typedb.common.collection.Pair<java.lang.String,​java.lang.String>,​ConceptMap.Explainable>> ownerships()
----

==== Description

Retrieves all of this `ConceptMap`’s explainable ownerships. 


==== Returns

`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<com.vaticle.typedb.common.collection.Pair<java.lang.String,​java.lang.String>,​ConceptMap.Explainable>>`

==== Code examples

[source,java]
----
conceptMap.explainables().ownerships();
----

// end::methods[]
