[#_ConceptMap]
=== ConceptMap

*Package*: `com.vaticle.typedb.driver.api.answer`

Contains a mapping of variables to concepts.

// tag::methods[]
[#_variables_]
==== variables

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<java.lang.String> variables()
----

Produces a stream over all variables in this ``ConceptMap``. 


.Returns
`java.util.stream.Stream<java.lang.String>`

.Code examples
[source,java]
----
conceptMap.variables();
----

[#_concepts_]
==== concepts

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Concept> concepts()
----

Produces a stream over all concepts in this ``ConceptMap``. 


.Returns
`java.util.stream.Stream<Concept>`

.Code examples
[source,java]
----
conceptMap.concepts();
----

[#_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
Concept get​(java.lang.String variable)
----

Retrieves a concept for a given variable name. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String` 
|===

.Returns
`Concept`

.Code examples
[source,java]
----
conceptMap.get(variable);
----

[#_toJSON_]
==== toJSON

[source,java]
----
@CheckReturnValue
default com.eclipsesource.json.JsonObject toJSON()
----

Retrieves this ``ConceptMap`` as JSON. 


.Returns
`com.eclipsesource.json.JsonObject`

.Code examples
[source,java]
----
conceptMap.toJSON();
----

[#_explainables_]
==== explainables

[source,java]
----
ConceptMap.Explainables explainables()
----

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable. 


.Returns
`ConceptMap.Explainables`

.Code examples
[source,java]
----
conceptMap.explainables();
----

// end::methods[]
