[#_Explanation]
=== Explanation

*Package*: `com.vaticle.typedb.driver.api.logic`

An explanation of which rule was used for inferring the explained concept, the condition of the rule, the conclusion of the rule, and the mapping of variables between the query and the rule’s conclusion.

// tag::methods[]
[#_rule_]
==== rule

[source,java]
----
Rule rule()
----

Retrieves the Rule for this Explanation. 


.Returns
`Rule`

.Code examples
[source,java]
----
explanation.rule()
----

[#_conclusion_]
==== conclusion

[source,java]
----
ConceptMap conclusion()
----

Retrieves the Conclusion for this Explanation. 


.Returns
`ConceptMap`

.Code examples
[source,java]
----
explanation.conclusion()
----

[#_condition_]
==== condition

[source,java]
----
ConceptMap condition()
----

Retrieves the Condition for this Explanation. 


.Returns
`ConceptMap`

.Code examples
[source,java]
----
explanation.condition()
----

[#_queryVariables_]
==== queryVariables

[source,java]
----
java.util.Set<java.lang.String> queryVariables()
----

Retrieves the query variables for this ``Explanation``. 


.Returns
`java.util.Set<java.lang.String>`

.Code examples
[source,java]
----
explanation.queryVariables()
----

[#_queryVariableMapping_java_lang_String]
==== queryVariableMapping

[source,java]
----
java.util.Set<java.lang.String> queryVariableMapping​(java.lang.String var)
----

Retrieves the rule variables corresponding to the query variable var for this ``Explanation``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `var` a| The query variable to map to rule variables. a| `java.lang.String` 
|===

.Returns
`java.util.Set<java.lang.String>`

.Code examples
[source,java]
----
explanation.variableMapping(var)
----

// end::methods[]
