[#_LogicManager]
= LogicManager

*Package*: `com.vaticle.typedb.driver.api.logic`

== Description

Provides methods for manipulating rules in the database.

== Methods

// tag::methods[]
[#_getRule_java_lang_String]
=== getRule

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
Rule getRule​(java.lang.String label)
----

==== Description

Retrieves the Rule that has the given label. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or retrieve a| `java.lang.String` 
|===

==== Returns

`Rule`

==== Code examples

[source,java]
----
transaction.logic().getRule(label)
----

[#_getRules_]
=== getRules

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Rule> getRules()
----

==== Description

Retrieves all rules. 


==== Returns

`java.util.stream.Stream<? extends Rule>`

==== Code examples

[source,java]
----
transaction.logic().getRules()
----

[#_putRule_java_lang_String_com_vaticle_typeql_lang_pattern_Pattern_com_vaticle_typeql_lang_pattern_Pattern]
=== putRule

==== Signature

[source,java]
----
Rule putRule​(java.lang.String label,
             com.vaticle.typeql.lang.pattern.Pattern when,
             com.vaticle.typeql.lang.pattern.Pattern then)
----

==== Description

Creates a new Rule if none exists with the given label, or replaces the existing one. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or replace a| `java.lang.String` 
a| `when` a| The when body of the rule to create a| `com.vaticle.typeql.lang.pattern.Pattern` 
a| `then` a| The then body of the rule to create a| `com.vaticle.typeql.lang.pattern.Pattern` 
|===

==== Returns

`Rule`

==== Code examples

[source,java]
----
transaction.logic().putRule(label, when, then)
----

// end::methods[]
