[#_QueryManager]
= QueryManager

*Package*: `com.vaticle.typedb.driver.api.query`

== Description

Provides methods for executing TypeQL queries in the transaction.

== Methods

// tag::methods[]
[#_match_com_vaticle_typeql_lang_query_TypeQLMatch]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(com.vaticle.typeql.lang.query.TypeQLMatch query)
----

==== Description

Performs a TypeQL Match (Get) with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(com.vaticle.typeql.lang.query.TypeQLMatch query,
                                          TypeDBOptions options)
----

==== Description

Performs a TypeQL Match (Get) query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match (Get) query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<ConceptMap>`

==== Code examples

[source,java]
----
transaction.query().match(query, options)
----

[#_match_java_lang_String]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(java.lang.String query)
----

==== Description

Performs a TypeQL Match (Get) with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_match_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(java.lang.String query,
                                          TypeDBOptions options)
----

==== Description


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
Numeric match​(com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate query)
----

==== Description

Performs a TypeQL Match Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Aggregate, TypeDBOptions)`>>


==== Returns

`Numeric`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
Numeric match​(com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate query,
              TypeDBOptions options)
----

==== Description

Performs a TypeQL Match Aggregate query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Numeric`

==== Code examples

[source,java]
----
transaction.query().matchAggregate(query, options)
----

[#_matchAggregate_java_lang_String]
=== matchAggregate

==== Signature

[source,java]
----
@CheckReturnValue
Numeric matchAggregate​(java.lang.String query)
----

==== Description

Performs a TypeQL Match Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Aggregate, TypeDBOptions)`>>


==== Returns

`Numeric`

[#_matchAggregate_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== matchAggregate

==== Signature

[source,java]
----
@CheckReturnValue
Numeric matchAggregate​(java.lang.String query,
                       TypeDBOptions options)
----

==== Description


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Aggregate, TypeDBOptions)`>>


==== Returns

`Numeric`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group query)
----

==== Description

Performs a TypeQL Match Group query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMapGroup>`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group query,
                                               TypeDBOptions options)
----

==== Description

Performs a TypeQL Match Group query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Group` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<ConceptMapGroup>`

==== Code examples

[source,java]
----
transaction.query().matchGroup(query, options)
----

[#_matchGroup_java_lang_String]
=== matchGroup

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> matchGroup​(java.lang.String query)
----

==== Description

Performs a TypeQL Match Group query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMapGroup>`

[#_matchGroup_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== matchGroup

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> matchGroup​(java.lang.String query,
                                                    TypeDBOptions options)
----

==== Description


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMapGroup>`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate query)
----

==== Description

Performs a TypeQL Match Group Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group.Aggregate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<NumericGroup>`

[#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions]
=== match

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate query,
                                            TypeDBOptions options)
----

==== Description

Performs a TypeQL Match Group Aggregate query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<NumericGroup>`

==== Code examples

[source,java]
----
transaction.query().matchGroupAggregate(query, options)
----

[#_matchGroupAggregate_java_lang_String]
=== matchGroupAggregate

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> matchGroupAggregate​(java.lang.String query)
----

==== Description

Performs a TypeQL Match Group Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group.Aggregate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<NumericGroup>`

[#_matchGroupAggregate_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== matchGroupAggregate

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> matchGroupAggregate​(java.lang.String query,
                                                          TypeDBOptions options)
----

==== Description


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,`match(TypeQLMatch.Group.Aggregate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<NumericGroup>`

[#_insert_com_vaticle_typeql_lang_query_TypeQLInsert]
=== insert

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query)
----

==== Description

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,`insert(TypeQLInsert, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions]
=== insert

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query,
                                           TypeDBOptions options)
----

==== Description

Performs a TypeQL Insert query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `com.vaticle.typeql.lang.query.TypeQLInsert` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<ConceptMap>`

==== Code examples

[source,java]
----
transaction.query().insert(query, options)
----

[#_insert_java_lang_String]
=== insert

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query)
----

==== Description

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,`insert(TypeQLInsert, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_insert_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== insert

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query,
                                           TypeDBOptions options)
----

==== Description


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,`insert(TypeQLInsert, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_delete_com_vaticle_typeql_lang_query_TypeQLDelete]
=== delete

==== Signature

[source,java]
----
void delete​(com.vaticle.typeql.lang.query.TypeQLDelete query)
----

==== Description

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,`delete(TypeQLDelete, TypeDBOptions)`>>


==== Returns

`void`

[#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions]
=== delete

==== Signature

[source,java]
----
void delete​(com.vaticle.typeql.lang.query.TypeQLDelete query,
            TypeDBOptions options)
----

==== Description

Performs a TypeQL Delete query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDelete` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
transaction.query().delete(query, options)
----

[#_delete_java_lang_String]
=== delete

==== Signature

[source,java]
----
void delete​(java.lang.String query)
----

==== Description

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,`delete(TypeQLDelete, TypeDBOptions)`>>


==== Returns

`void`

[#_delete_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== delete

==== Signature

[source,java]
----
void delete​(java.lang.String query,
            TypeDBOptions options)
----

==== Description


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,`delete(TypeQLDelete, TypeDBOptions)`>>


==== Returns

`void`

[#_update_com_vaticle_typeql_lang_query_TypeQLUpdate]
=== update

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query)
----

==== Description

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,`update(TypeQLUpdate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions]
=== update

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query,
                                           TypeDBOptions options)
----

==== Description

Performs a TypeQL Update query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUpdate` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<ConceptMap>`

==== Code examples

[source,java]
----
transaction.query().update(query, options)
----

[#_update_java_lang_String]
=== update

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query)
----

==== Description

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,`update(TypeQLUpdate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_update_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== update

==== Signature

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query,
                                           TypeDBOptions options)
----

==== Description


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,`update(TypeQLUpdate, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<ConceptMap>`

[#_define_com_vaticle_typeql_lang_query_TypeQLDefine]
=== define

==== Signature

[source,java]
----
void define​(com.vaticle.typeql.lang.query.TypeQLDefine query)
----

==== Description

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,`define(TypeQLDefine, TypeDBOptions)`>>


==== Returns

`void`

[#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions]
=== define

==== Signature

[source,java]
----
void define​(com.vaticle.typeql.lang.query.TypeQLDefine query,
            TypeDBOptions options)
----

==== Description

Performs a TypeQL Define query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDefine` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
transaction.query().define(query, options)
----

[#_define_java_lang_String]
=== define

==== Signature

[source,java]
----
void define​(java.lang.String query)
----

==== Description

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,`define(TypeQLDefine, TypeDBOptions)`>>


==== Returns

`void`

[#_define_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== define

==== Signature

[source,java]
----
void define​(java.lang.String query,
            TypeDBOptions options)
----

==== Description


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,`define(TypeQLDefine, TypeDBOptions)`>>


==== Returns

`void`

[#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine]
=== undefine

==== Signature

[source,java]
----
void undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query)
----

==== Description

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,`undefine(TypeQLUndefine, TypeDBOptions)`>>


==== Returns

`void`

[#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions]
=== undefine

==== Signature

[source,java]
----
void undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query,
              TypeDBOptions options)
----

==== Description

Performs a TypeQL Undefine query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUndefine` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
transaction.query().undefine(query, options)
----

[#_undefine_java_lang_String]
=== undefine

==== Signature

[source,java]
----
void undefine​(java.lang.String query)
----

==== Description

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,`undefine(TypeQLUndefine, TypeDBOptions)`>>


==== Returns

`void`

[#_undefine_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
=== undefine

==== Signature

[source,java]
----
void undefine​(java.lang.String query,
              TypeDBOptions options)
----

==== Description


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,`undefine(TypeQLUndefine, TypeDBOptions)`>>


==== Returns

`void`

[#_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable]
=== explain

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable)
----

==== Description

Performs a TypeQL Explain query with default options.


See also: <<#_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable_com_vaticle_typedb_driver_api_TypeDBOptions,`explain(ConceptMap.Explainable, TypeDBOptions)`>>


==== Returns

`java.util.stream.Stream<Explanation>`

[#_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable_com_vaticle_typedb_driver_api_TypeDBOptions]
=== explain

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable,
                                             TypeDBOptions options)
----

==== Description

Performs a TypeQL Explain query in the transaction. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `ConceptMap.Explainable` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`java.util.stream.Stream<Explanation>`

==== Code examples

[source,java]
----
transaction.query().explain(explainable, options)
----

// end::methods[]
