[#_Relation]
= Relation

*Package*: `com.vaticle.typedb.driver.api.concept.thing`

*Superinterfaces:*

* `Concept`
* `Thing`

== Description

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

== Methods

// tag::methods[]
[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a ``Relation``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
relation.isRelation();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
@CheckReturnValue
default Relation asRelation()
----

==== Description

Casts the concept to ``Relation``. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
relation.asRelation();
----

[#_getType_]
=== getType

==== Signature

[source,java]
----
@CheckReturnValue
RelationType getType()
----

==== Description

Retrieves the type which this ``Relation`` belongs to. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
relation.getType();
----

[#_addPlayer_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType_com_vaticle_typedb_driver_api_concept_thing_Thing]
=== addPlayer

==== Signature

[source,java]
----
void addPlayer​(TypeDBTransaction transaction,
               RoleType roleType,
               Thing player)
----

==== Description

Adds a new role player to play the given role in this ``Relation``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to be played by the ``player`` a| `RoleType` 
a| `player` a| The thing to play the role a| `Thing` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
relation.addPlayer(transaction, roleType, player);
----

[#_removePlayer_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType_com_vaticle_typedb_driver_api_concept_thing_Thing]
=== removePlayer

==== Signature

[source,java]
----
void removePlayer​(TypeDBTransaction transaction,
                  RoleType roleType,
                  Thing player)
----

==== Description

Removes the association of the given instance that plays the given role in this ``Relation``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to no longer be played by the thing in this ``Relation`` a| `RoleType` 
a| `player` a| The instance to no longer play the role in this ``Relation`` a| `Thing` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
relation.removePlayer(transaction, roleType, player);
----

[#_getPlayersByRoleType_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType___]
=== getPlayersByRoleType

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Thing> getPlayersByRoleType​(TypeDBTransaction transaction,
                                                              RoleType... roleTypes)
----

==== Description

Retrieves all role players of this ``Relation``, optionally filtered by given role types. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleTypes` a| 0 or more role types a| `RoleType[]` 
|===

==== Returns

`java.util.stream.Stream<? extends Thing>`

==== Code examples

[source,java]
----
relation.getPlayersByRoleType(transaction, roleTypes);
----

[#_getPlayers_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getPlayers

==== Signature

[source,java]
----
@CheckReturnValue
java.util.Map<? extends RoleType,​? extends java.util.List<? extends Thing>> getPlayers​(TypeDBTransaction transaction)
----

==== Description

Retrieves a mapping of all instances involved in the ``Relation`` and the role each play. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.Map<? extends RoleType,​? extends java.util.List<? extends Thing>>`

==== Code examples

[source,java]
----
relation.getPlayers(transaction)
----

[#_getRelating_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getRelating

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getRelating​(TypeDBTransaction transaction)
----

==== Description

Retrieves all role types currently played in this ``Relation``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends RoleType>`

==== Code examples

[source,java]
----
relation.getRelating(transaction);
----

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to ``Attribute``. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to ``AttributeType``. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to ``Entity``. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to ``EntityType``. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to ``RelationType``. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
default RoleType asRoleType()
----

==== Description

Casts the concept to ``RoleType``. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
default ThingType asThingType()
----

==== Description

Casts the concept to ``ThingType``. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_asType_]
=== asType

==== Signature

[source,java]
----
default Type asType()
----

==== Description

Casts the concept to ``Type``. 


==== Returns

`Type`

==== Code examples

[source,java]
----
concept.asType();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to ``Value``. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an ``Attribute``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an ``AttributeType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an ``Entity``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an ``EntityType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a ``RelationType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a ``RoleType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a ``ThingType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_isType_]
=== isType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isType()
----

==== Description

Checks if the concept is a ``Type``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isType();
----

[#_isValue_]
=== isValue

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

==== Description

Checks if the concept is a ``Value``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

// end::methods[]
