[#_RoleType]
= RoleType

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`
* `Type`

== Description

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type. Roles allow a schema to enforce logical constraints on types of role players.

== Methods

// tag::methods[]
[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a ``RoleType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default RoleType asRoleType()
----

==== Description

Casts the concept to ``RoleType``. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_getSupertype_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertype

==== Signature

[source,java]
----
RoleType getSupertype​(TypeDBTransaction transaction)
----

==== Description

Retrieves the most immediate supertype of the ``RoleType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`RoleType`

==== Code examples

[source,java]
----
roleType.getSupertype(transaction);
----

[#_getSupertypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends RoleType> getSupertypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all supertypes of the ``RoleType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends RoleType>`

==== Code examples

[source,java]
----
roleType.getSupertypes(transaction);
----

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSubtypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends RoleType> getSubtypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all direct and indirect subtypes of the ``RoleType``. Equivalent to ``getSubtypes(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getSubtypes(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends RoleType>`

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getSubtypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends RoleType> getSubtypes​(TypeDBTransaction transaction,
                                                        Concept.Transitivity transitivity)
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends RoleType>`

==== Code examples

[source,java]
----
roleType.getSubtypes(transaction, transitivity);
----

[#_getRelationType_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getRelationType

==== Signature

[source,java]
----
RelationType getRelationType​(TypeDBTransaction transaction)
----

==== Description

Retrieves the ``RelationType`` that this role is directly related to. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`RelationType`

==== Code examples

[source,java]
----
roleType.getRelationType(transaction);
----

[#_getRelationTypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getRelationTypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends RelationType> getRelationTypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves ``RelationType``s that this role is related to (directly or indirectly). 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends RelationType>`

==== Code examples

[source,java]
----
roleType.getRelationTypes(transaction);
----

[#_getPlayerTypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getPlayerTypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends ThingType> getPlayerTypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves the ``ThingType``s whose instances play this role. Equivalent to ``getPlayerTypes(transaction, Transitivity.TRANSITIVE)``.


See also: <<#_getPlayerTypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getPlayerTypes(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends ThingType>`

[#_getPlayerTypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getPlayerTypes

==== Signature

[source,java]
----
java.util.stream.Stream<? extends ThingType> getPlayerTypes​(TypeDBTransaction transaction,
                                                            Concept.Transitivity transitivity)
----

==== Description

Retrieves the ``ThingType``s whose instances play this role. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends ThingType>`

==== Code examples

[source,java]
----
roleType.getPlayerTypes(transaction, transitivity)
----

[#_getRelationInstances_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getRelationInstances

==== Signature

[source,java]
----
java.util.stream.Stream<? extends Relation> getRelationInstances​(TypeDBTransaction transaction)
----

==== Description

Retrieves the ``Relation`` instances that this role is related to. Equivalent to ````getRelationInstances(transaction, Transitivity.TRANSITIVE)


See also: <<#_getRelationInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getRelationInstances(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends Relation>`

[#_getRelationInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getRelationInstances

==== Signature

[source,java]
----
java.util.stream.Stream<? extends Relation> getRelationInstances​(TypeDBTransaction transaction,
                                                                 Concept.Transitivity transitivity)
----

==== Description

Retrieves the ``Relation`` instances that this role is related to. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect relation, ``Transitivity.EXPLICIT`` for direct relation only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends Relation>`

==== Code examples

[source,java]
----
roleType.getRelationInstances(transaction, transitivity)
----

[#_getPlayerInstances_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getPlayerInstances

==== Signature

[source,java]
----
java.util.stream.Stream<? extends Thing> getPlayerInstances​(TypeDBTransaction transaction)
----

==== Description

Retrieves the ``Thing`` instances that play this role.


See also: <<#_getPlayerTypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getPlayerTypes(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends Thing>`

[#_getPlayerInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getPlayerInstances

==== Signature

[source,java]
----
java.util.stream.Stream<? extends Thing> getPlayerInstances​(TypeDBTransaction transaction,
                                                            Concept.Transitivity transitivity)
----

==== Description

Retrieves the ``Thing`` instances that play this role. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends Thing>`

==== Code examples

[source,java]
----
roleType.getPlayerInstances(transaction, transitivity);
----

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to ``Attribute``. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to ``AttributeType``. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to ``Entity``. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to ``EntityType``. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
default Relation asRelation()
----

==== Description

Casts the concept to ``Relation``. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to ``RelationType``. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asThing_]
=== asThing

==== Signature

[source,java]
----
default Thing asThing()
----

==== Description

Casts the concept to ``Thing``. 


==== Returns

`Thing`

==== Code examples

[source,java]
----
concept.asThing();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
default ThingType asThingType()
----

==== Description

Casts the concept to ``ThingType``. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to ``Value``. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an ``Attribute``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an ``AttributeType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an ``Entity``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an ``EntityType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a ``Relation``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a ``RelationType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isThing_]
=== isThing

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

==== Description

Checks if the concept is a ``Thing``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThing();
----

[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a ``ThingType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_isValue_]
=== isValue

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

==== Description

Checks if the concept is a ``Value``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

// end::methods[]
