[#_Rule]
= Rule

*Package*: `com.vaticle.typedb.driver.api.logic`

== Description

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

== Methods

// tag::methods[]
[#_getLabel_]
=== getLabel

==== Signature

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

==== Description

Retrieves the unique label of the rule.

==== Returns

`java.lang.String`

[#_getWhen_]
=== getWhen

==== Signature

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getWhen()
----

==== Description

The statements that constitute the ‘when’ of the rule.

==== Returns

`com.vaticle.typeql.lang.pattern.Pattern`

[#_getThen_]
=== getThen

==== Signature

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getThen()
----

==== Description

The single statement that constitutes the ‘then’ of the rule.

==== Returns

`com.vaticle.typeql.lang.pattern.Pattern`

[#_setLabel_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
=== setLabel

==== Signature

[source,java]
----
void setLabel​(TypeDBTransaction transaction,
              java.lang.String label)
----

==== Description

Renames the label of the rule. The new label must remain unique. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` 
a| `label` a| The new label to be given to the rule a| `java.lang.String` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
rule.setLabel(transaction, newLabel)
----

[#_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== delete

==== Signature

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

==== Description

Deletes this rule. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
rule.delete(transaction)
----

[#_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== isDeleted

==== Signature

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

==== Description

Check if this rule has been deleted. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current `Transaction` a| `TypeDBTransaction` 
|===

==== Returns

`boolean`

==== Code examples

[source,java]
----
rule.isDeleted(transaction)
----

// end::methods[]
