[#_Thing]
=== Thing

*Package*: `com.vaticle.typedb.driver.api.concept.thing`

*Superinterfaces:*

* `Concept`

// tag::methods[]
[#_getIID_]
==== getIID

[source,java]
----
@CheckReturnValue
java.lang.String getIID()
----

Retrieves the unique id of the ``Thing``. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
thing.getIID();
----

[#_getType_]
==== getType

[source,java]
----
@CheckReturnValue
ThingType getType()
----

Retrieves the type which this ``Thing`` belongs to. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
thing.getType();
----

[#_isInferred_]
==== isInferred

[source,java]
----
@CheckReturnValue
boolean isInferred()
----

Checks if this ``Thing`` is inferred by a [Reasoning Rule]. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
thing.isInferred();
----

[#_isThing_]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
thing.isThing();
----

[#_asThing_]
==== asThing

[source,java]
----
@CheckReturnValue
default Thing asThing()
----

Casts the concept to ``Thing``. 


[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,java]
----
thing.asThing();
----

[#_toJSON_]
==== toJSON

[source,java]
----
default com.eclipsesource.json.JsonObject toJSON()
----

Retrieves a ``Thing`` as JSON. 


[caption=""]
.Returns
`com.eclipsesource.json.JsonObject`

[caption=""]
.Code examples
[source,java]
----
thing.toJSON();
----

[#_setHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_thing_Attribute]
==== setHas

[source,java]
----
void setHas​(TypeDBTransaction transaction,
            Attribute attribute)
----

Assigns an ``Attribute`` to be owned by this ``Thing``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
thing.setHas(transaction, attribute);
----

[#_unsetHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_thing_Attribute]
==== unsetHas

[source,java]
----
void unsetHas​(TypeDBTransaction transaction,
              Attribute attribute)
----

Unassigns an ``Attribute`` from this ``Thing``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
thing.unsetHas(transaction, attribute);
----

[#_getHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType___]
==== getHas

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    AttributeType... attributeTypes)
----

Retrieves the ``Attribute``s that this ``Thing`` owns, optionally filtered by ``AttributeType``s. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Attribute>`

[caption=""]
.Code examples
[source,java]
----
thing.getHas(transaction)
     thing.getHas(transaction, attributeType=attributeType,
     annotations=set(Annotation.key()))
----

[#_getHas_com_vaticle_typedb_driver_api_TypeDBTransaction_java_util_Set]
==== getHas

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    java.util.Set<ThingType.Annotation> annotations)
----

Retrieves the ``Attribute``s that this ``Thing`` owns, filtered by ``Annotation``s. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `java.util.Set<ThingType.Annotation>`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Attribute>`

[caption=""]
.Code examples
[source,java]
----
thing.getHas(transaction);
 thing.getHas(transaction, annotations=set(Annotation.key()));
----

[#_getRelations_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType___]
==== getRelations

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getRelations​(TypeDBTransaction transaction,
                                                         RoleType... roleTypes)
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleTypes` a| The array of roles to filter the relations by. a| `RoleType[]`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends Relation>`

[caption=""]
.Code examples
[source,java]
----
thing.getRelations(transaction, roleTypes);
----

[#_getPlaying_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getPlaying

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getPlaying​(TypeDBTransaction transaction)
----

Retrieves the roles that this ``Thing`` is currently playing. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`java.util.stream.Stream<? extends RoleType>`

[caption=""]
.Code examples
[source,java]
----
thing.getPlaying(transaction);
----

[#_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== delete

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

Deletes this ``Thing``. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
thing.delete(transaction);
----

[#_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== isDeleted

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

Checks if this ``Thing`` is deleted. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
thing.isDeleted(transaction)
----

[#_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_asThingType_]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,java]
----
concept.asThingType();
----

[#_asType_]
==== asType

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_isThingType_]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isThingType();
----

[#_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]

