[#_ThingType_Annotation]
=== ThingType.Annotation

*Package*: `com.vaticle.typedb.driver.api.concept.type`

Annotation

// tag::methods[]
[#_key_]
==== key

[source,java]
----
public static ThingType.Annotation key()
----

Produces a ``@key`` annotation. 


[caption=""]
.Returns
`public static ThingType.Annotation`

[caption=""]
.Code examples
[source,java]
----
ThingType.Annotation.key();
----

[#_unique_]
==== unique

[source,java]
----
public static ThingType.Annotation unique()
----

Produces a ``@unique`` annotation. 


[caption=""]
.Returns
`public static ThingType.Annotation`

[caption=""]
.Code examples
[source,java]
----
Annotation.unique();
----

[#_isKey_]
==== isKey

[source,java]
----
public boolean isKey()
----

Checks if this ``Annotation`` is a ``@key`` annotation. 


[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
annotation.isKey();
----

[#_isUnique_]
==== isUnique

[source,java]
----
public boolean isUnique()
----

Checks if this ``Annotation`` is a ``@unique`` annotation. 


[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
annotation.isUnique();
----

[#_toString_]
==== toString

[source,java]
----
public java.lang.String toString()
----

Retrieves a string representation of this ``Annotation``. 


[caption=""]
.Returns
`public java.lang.String`

[caption=""]
.Code examples
[source,java]
----
annotation.toString();
----

[#_equals_java_lang_Object]
==== equals

[source,java]
----
public boolean equals​(java.lang.Object obj)
----

Checks if this ``Annotation`` is equal to another object. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `obj` a| Object to compare with a| `java.lang.Object`
|===

[caption=""]
.Returns
`public boolean`

[caption=""]
.Code examples
[source,java]
----
annotation.equals(obj);
----

[#_hashCode_]
==== hashCode

[source,java]
----
public int hashCode()
----



[caption=""]
.Returns
`public int`

// end::methods[]

