[#_ThingType]
= ThingType

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`
* `Type`

== Methods

// tag::methods[]
[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a ``ThingType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
@CheckReturnValue
default ThingType asThingType()
----

==== Description

Casts the concept to ``ThingType``. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_getSupertype_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertype

==== Signature

[source,java]
----
@CheckReturnValue
ThingType getSupertype​(TypeDBTransaction transaction)
----

==== Description

Retrieves the most immediate supertype of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`ThingType`

==== Code examples

[source,java]
----
type.getSupertype(transaction);
----

[#_getSupertypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends ThingType> getSupertypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all supertypes of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends ThingType>`

==== Code examples

[source,java]
----
type.getSupertypes(transaction);
----

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSubtypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends ThingType> getSubtypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all direct and indirect subtypes of the type. Equivalent to ``getSubtypes(transaction, Transitivity.TRANSITIVE)``


See also: ``Type.getSubtypes(TypeDBTransaction, Transitivity)``


==== Returns

`java.util.stream.Stream<? extends ThingType>`

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getSubtypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends ThingType> getSubtypes​(TypeDBTransaction transaction,
                                                         Concept.Transitivity transitivity)
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends ThingType>`

==== Code examples

[source,java]
----
type.getSubtypes(transaction);
 type.getSubtypes(transaction, Transitivity.EXPLICIT);
----

[#_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getInstances

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Thing> getInstances​(TypeDBTransaction transaction)
----

==== Description

Retrieves all ``Thing`` objects that are instances of this ``ThingType`` or its subtypes. Equivalent to ``getInstances(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getInstances(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends Thing>`

[#_getInstances_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getInstances

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Thing> getInstances​(TypeDBTransaction transaction,
                                                      Concept.Transitivity transitivity)
----

==== Description

Retrieves ``Thing`` objects that are instances of this exact ``ThingType``, OR this ``ThingType`` and any of its subtypes 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.EXPLICIT`` for direct instances only, ``Transitivity.TRANSITIVE`` to include instances of subtypes a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends Thing>`

==== Code examples

[source,java]
----
thingType.getInstances(transaction);
 thingType.getInstances(transaction, Transitivity.EXPLICIT);
----

[#_setAbstract_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== setAbstract

==== Signature

[source,java]
----
void setAbstract​(TypeDBTransaction transaction)
----

==== Description

Set a ``ThingType`` to be abstract, meaning it cannot have instances. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.setAbstract(transaction);
----

[#_unsetAbstract_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== unsetAbstract

==== Signature

[source,java]
----
void unsetAbstract​(TypeDBTransaction transaction)
----

==== Description

Set a ``ThingType`` to be non-abstract, meaning it can have instances. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.unsetAbstract(transaction);
----

[#_setPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType]
=== setPlays

==== Signature

[source,java]
----
void setPlays​(TypeDBTransaction transaction,
              RoleType roleType)
----

==== Description

Allows the instances of this ``ThingType`` to play the given role.


See also: <<#_setPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType_com_vaticle_typedb_driver_api_concept_type_RoleType,``setPlays(TypeDBTransaction, RoleType, RoleType)``>>


==== Returns

`void`

[#_setPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType_com_vaticle_typedb_driver_api_concept_type_RoleType]
=== setPlays

==== Signature

[source,java]
----
void setPlays​(TypeDBTransaction transaction,
              RoleType roleType,
              RoleType overriddenType)
----

==== Description

Allows the instances of this ``ThingType`` to play the given role. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to be played by the instances of this type a| `RoleType` 
a| `overriddenType` a| The role type that this role overrides, if applicable a| `RoleType` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.setPlays(transaction, roleType)
 thingType.setPlays(transaction, roleType, overriddenType)
----

[#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_com_vaticle_typedb_driver_api_concept_type_AttributeType_java_util_Set]
=== setOwns

==== Signature

[source,java]
----
void setOwns​(TypeDBTransaction transaction,
             AttributeType attributeType,
             AttributeType overriddenType,
             java.util.Set<ThingType.Annotation> annotations)
----

==== Description

Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType` 
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType` 
a| `annotations` a| Adds annotations to the ownership. a| `java.util.Set<ThingType.Annotation>` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.setOwns(transaction, attributeType);
 thingType.setOwns(transaction, attributeType, overriddenType, Collections.singleton(Annotation.key()));
----

[#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_com_vaticle_typedb_driver_api_concept_type_AttributeType]
=== setOwns

==== Signature

[source,java]
----
void setOwns​(TypeDBTransaction transaction,
             AttributeType attributeType,
             AttributeType overriddenType)
----

==== Description

Allows the instances of this ``ThingType`` to own the given ``AttributeType``,


See also: <<#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_com_vaticle_typedb_driver_api_concept_type_AttributeType_java_util_Set,``setOwns(TypeDBTransaction, AttributeType, AttributeType, Set)``>>


==== Returns

`void`

[#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_java_util_Set]
=== setOwns

==== Signature

[source,java]
----
void setOwns​(TypeDBTransaction transaction,
             AttributeType attributeType,
             java.util.Set<ThingType.Annotation> annotations)
----

==== Description

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.


See also: <<#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_com_vaticle_typedb_driver_api_concept_type_AttributeType_java_util_Set,``setOwns(TypeDBTransaction, AttributeType, AttributeType, Set)``>>


==== Returns

`void`

[#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType]
=== setOwns

==== Signature

[source,java]
----
void setOwns​(TypeDBTransaction transaction,
             AttributeType attributeType)
----

==== Description

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.


See also: <<#_setOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType_com_vaticle_typedb_driver_api_concept_type_AttributeType_java_util_Set,``setOwns(TypeDBTransaction, AttributeType, AttributeType, Set)``>>


==== Returns

`void`

[#_getPlays_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getPlays

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getPlays​(TypeDBTransaction transaction)
----

==== Description

Retrieves all direct and inherited roles that are allowed to be played by the instances of this ``ThingType``.


See also: <<#_getPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getPlays(TypeDBTransaction, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends RoleType>`

[#_getPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getPlays

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getPlays​(TypeDBTransaction transaction,
                                                     Concept.Transitivity transitivity)
----

==== Description

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| transitivity: ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends RoleType>`

==== Code examples

[source,java]
----
thingType.getPlays(transaction);
 thingType.getPlays(transaction, Transitivity.EXPLICIT);
----

[#_getPlaysOverridden_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType]
=== getPlaysOverridden

==== Signature

[source,java]
----
@CheckReturnValue
RoleType getPlaysOverridden​(TypeDBTransaction transaction,
                            RoleType roleType)
----

==== Description

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The ``RoleType`` that overrides an inherited role a| `RoleType` 
|===

==== Returns

`RoleType`

==== Code examples

[source,java]
----
thingType.getPlaysOverridden(transaction, roleType);
----

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         Value.Type valueType)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_java_util_Set]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         java.util.Set<ThingType.Annotation> annotations)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         Value.Type valueType,
                                                         java.util.Set<ThingType.Annotation> annotations)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         Concept.Transitivity transitivity)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         Value.Type valueType,
                                                         Concept.Transitivity transitivity)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         java.util.Set<ThingType.Annotation> annotations,
                                                         Concept.Transitivity transitivity)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


See also: <<#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getOwns(TypeDBTransaction, Value.Type, Set, Transitivity)``>>


==== Returns

`java.util.stream.Stream<? extends AttributeType>`

[#_getOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_value_Value_Type_java_util_Set_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getOwns

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends AttributeType> getOwns​(TypeDBTransaction transaction,
                                                         Value.Type valueType,
                                                         java.util.Set<ThingType.Annotation> annotations,
                                                         Concept.Transitivity transitivity)
----

==== Description

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Value.Type` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Concept.Transitivity` 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `java.util.Set<ThingType.Annotation>` 
|===

==== Returns

`java.util.stream.Stream<? extends AttributeType>`

==== Code examples

[source,java]
----
thingType.getOwns(transaction);
 thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT, Collections.singleton(Annotation.key()));
----

[#_getOwnsOverridden_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType]
=== getOwnsOverridden

==== Signature

[source,java]
----
@CheckReturnValue
AttributeType getOwnsOverridden​(TypeDBTransaction transaction,
                                AttributeType attributeType)
----

==== Description

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType` 
|===

==== Returns

`AttributeType`

==== Code examples

[source,java]
----
thingType.getOwnsOverridden(transaction, attributeType);
----

[#_unsetPlays_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType]
=== unsetPlays

==== Signature

[source,java]
----
void unsetPlays​(TypeDBTransaction transaction,
                RoleType roleType)
----

==== Description

Disallows the instances of this ``ThingType`` from playing the given role. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to not be played by the instances of this type. a| `RoleType` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.unsetPlays(transaction, roleType);
----

[#_unsetOwns_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType]
=== unsetOwns

==== Signature

[source,java]
----
void unsetOwns​(TypeDBTransaction transaction,
               AttributeType attributeType)
----

==== Description

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thingType.unsetOwns(transaction, attributeType);
----

[#_getSyntax_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSyntax

==== Signature

[source,java]
----
@CheckReturnValue
java.lang.String getSyntax​(TypeDBTransaction transaction)
----

==== Description

Produces a pattern for creating this ``ThingType`` in a ``define`` query. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.lang.String`

==== Code examples

[source,java]
----
thingType.getSyntax(transaction);
----

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to ``Attribute``. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to ``AttributeType``. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to ``Entity``. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to ``EntityType``. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
default Relation asRelation()
----

==== Description

Casts the concept to ``Relation``. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to ``RelationType``. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
default RoleType asRoleType()
----

==== Description

Casts the concept to ``RoleType``. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_asThing_]
=== asThing

==== Signature

[source,java]
----
default Thing asThing()
----

==== Description

Casts the concept to ``Thing``. 


==== Returns

`Thing`

==== Code examples

[source,java]
----
concept.asThing();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to ``Value``. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an ``Attribute``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an ``AttributeType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an ``Entity``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an ``EntityType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a ``Relation``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a ``RelationType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a ``RoleType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_isThing_]
=== isThing

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

==== Description

Checks if the concept is a ``Thing``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThing();
----

[#_isValue_]
=== isValue

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

==== Description

Checks if the concept is a ``Value``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

// end::methods[]
