[#_Thing]
= Thing

*Package*: `com.vaticle.typedb.driver.api.concept.thing`

*Superinterfaces:*

* `Concept`

== Methods

// tag::methods[]
[#_getIID_]
=== getIID

==== Signature

[source,java]
----
@CheckReturnValue
java.lang.String getIID()
----

==== Description

Retrieves the unique id of the ``Thing``. 


==== Returns

`java.lang.String`

==== Code examples

[source,java]
----
thing.getIID();
----

[#_getType_]
=== getType

==== Signature

[source,java]
----
@CheckReturnValue
ThingType getType()
----

==== Description

Retrieves the type which this ``Thing`` belongs to. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
thing.getType();
----

[#_isInferred_]
=== isInferred

==== Signature

[source,java]
----
@CheckReturnValue
boolean isInferred()
----

==== Description

Checks if this ``Thing`` is inferred by a [Reasoning Rule]. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
thing.isInferred();
----

[#_isThing_]
=== isThing

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

==== Description

Checks if the concept is a ``Thing``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
thing.isThing();
----

[#_asThing_]
=== asThing

==== Signature

[source,java]
----
@CheckReturnValue
default Thing asThing()
----

==== Description

Casts the concept to ``Thing``. 


==== Returns

`Thing`

==== Code examples

[source,java]
----
thing.asThing();
----

[#_toJSON_]
=== toJSON

==== Signature

[source,java]
----
default com.eclipsesource.json.JsonObject toJSON()
----

==== Description

Retrieves a ``Thing`` as JSON. 


==== Returns

`com.eclipsesource.json.JsonObject`

==== Code examples

[source,java]
----
thing.toJSON();
----

[#_setHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_thing_Attribute]
=== setHas

==== Signature

[source,java]
----
void setHas​(TypeDBTransaction transaction,
            Attribute attribute)
----

==== Description

Assigns an ``Attribute`` to be owned by this ``Thing``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thing.setHas(transaction, attribute);
----

[#_unsetHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_thing_Attribute]
=== unsetHas

==== Signature

[source,java]
----
void unsetHas​(TypeDBTransaction transaction,
              Attribute attribute)
----

==== Description

Unassigns an ``Attribute`` from this ``Thing``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thing.unsetHas(transaction, attribute);
----

[#_getHas_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_AttributeType___]
=== getHas

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    AttributeType... attributeTypes)
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns, optionally filtered by ``AttributeType``s. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]` 
|===

==== Returns

`java.util.stream.Stream<? extends Attribute>`

==== Code examples

[source,java]
----
thing.getHas(transaction)
     thing.getHas(transaction, attributeType=attributeType,
     annotations=set(Annotation.key()))
----

[#_getHas_com_vaticle_typedb_driver_api_TypeDBTransaction_java_util_Set]
=== getHas

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Attribute> getHas​(TypeDBTransaction transaction,
                                                    java.util.Set<ThingType.Annotation> annotations)
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns, filtered by ``Annotation``s. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `java.util.Set<ThingType.Annotation>` 
|===

==== Returns

`java.util.stream.Stream<? extends Attribute>`

==== Code examples

[source,java]
----
thing.getHas(transaction);
 thing.getHas(transaction, annotations=set(Annotation.key()));
----

[#_getRelations_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_type_RoleType___]
=== getRelations

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Relation> getRelations​(TypeDBTransaction transaction,
                                                         RoleType... roleTypes)
----

==== Description

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleTypes` a| The array of roles to filter the relations by. a| `RoleType[]` 
|===

==== Returns

`java.util.stream.Stream<? extends Relation>`

==== Code examples

[source,java]
----
thing.getRelations(transaction, roleTypes);
----

[#_getPlaying_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getPlaying

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends RoleType> getPlaying​(TypeDBTransaction transaction)
----

==== Description

Retrieves the roles that this ``Thing`` is currently playing. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends RoleType>`

==== Code examples

[source,java]
----
thing.getPlaying(transaction);
----

[#_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== delete

==== Signature

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

==== Description

Deletes this ``Thing``. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
thing.delete(transaction);
----

[#_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== isDeleted

==== Signature

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

==== Description

Checks if this ``Thing`` is deleted. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`boolean`

==== Code examples

[source,java]
----
thing.isDeleted(transaction)
----

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to ``Attribute``. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to ``AttributeType``. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to ``Entity``. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to ``EntityType``. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
default Relation asRelation()
----

==== Description

Casts the concept to ``Relation``. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to ``RelationType``. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
default RoleType asRoleType()
----

==== Description

Casts the concept to ``RoleType``. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
default ThingType asThingType()
----

==== Description

Casts the concept to ``ThingType``. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_asType_]
=== asType

==== Signature

[source,java]
----
default Type asType()
----

==== Description

Casts the concept to ``Type``. 


==== Returns

`Type`

==== Code examples

[source,java]
----
concept.asType();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to ``Value``. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an ``Attribute``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an ``AttributeType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an ``Entity``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an ``EntityType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a ``Relation``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a ``RelationType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a ``RoleType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a ``ThingType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_isType_]
=== isType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isType()
----

==== Description

Checks if the concept is a ``Type``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isType();
----

[#_isValue_]
=== isValue

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

==== Description

Checks if the concept is a ``Value``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

// end::methods[]
