[#_TypeDBTransaction]
= TypeDBTransaction

*Package*: `com.vaticle.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

== Methods

// tag::methods[]
[#_isOpen_]
=== isOpen

==== Signature

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

==== Description

Checks whether this transaction is open. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
transaction.isOpen();
----

[#_type_]
=== type

==== Signature

[source,java]
----
@CheckReturnValue
TypeDBTransaction.Type type()
----

==== Description

The transaction’s type (READ or WRITE)

==== Returns

`TypeDBTransaction.Type`

[#_options_]
=== options

==== Signature

[source,java]
----
@CheckReturnValue
TypeDBOptions options()
----

==== Description

The options for the transaction

==== Returns

`TypeDBOptions`

[#_concepts_]
=== concepts

==== Signature

[source,java]
----
@CheckReturnValue
ConceptManager concepts()
----

==== Description

The `ConceptManager` for this transaction, providing access to all Concept API methods.

==== Returns

`ConceptManager`

[#_logic_]
=== logic

==== Signature

[source,java]
----
@CheckReturnValue
LogicManager logic()
----

==== Description

The `LogicManager` for this Transaction, providing access to all Concept API - Logic methods.

==== Returns

`LogicManager`

[#_query_]
=== query

==== Signature

[source,java]
----
@CheckReturnValue
QueryManager query()
----

==== Description

The``QueryManager`` for this Transaction, from which any TypeQL query can be executed.

==== Returns

`QueryManager`

[#_onClose_java_util_function_Consumer]
=== onClose

==== Signature

[source,java]
----
void onClose​(java.util.function.Consumer<java.lang.Throwable> function)
----

==== Description

Registers a callback function which will be executed when this session is closed. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `java.util.function.Consumer<java.lang.Throwable>` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
transaction.onClose(function);
----

[#_commit_]
=== commit

==== Signature

[source,java]
----
void commit()
----

==== Description

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call. 


==== Returns

`void`

==== Code examples

[source,java]
----
transaction.commit()
----

[#_rollback_]
=== rollback

==== Signature

[source,java]
----
void rollback()
----

==== Description

Rolls back the uncommitted changes made via this transaction. 


==== Returns

`void`

==== Code examples

[source,java]
----
transaction.rollback()
----

[#_close_]
=== close

==== Signature

[source,java]
----
void close()
----

==== Description

Closes the transaction. 


==== Returns

`void`

==== Code examples

[source,java]
----
transaction.close()
----

// end::methods[]
