[#_Type]
= Type

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`

== Methods

// tag::methods[]
[#_getLabel_]
=== getLabel

==== Signature

[source,java]
----
@CheckReturnValue
com.vaticle.typedb.driver.common.Label getLabel()
----

==== Description

Retrieves the unique label of the type. 


==== Returns

`com.vaticle.typedb.driver.common.Label`

==== Code examples

[source,java]
----
type.getLabel();
----

[#_isRoot_]
=== isRoot

==== Signature

[source,java]
----
@CheckReturnValue
boolean isRoot()
----

==== Description

Checks if the type is a root type. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
type.isRoot();
----

[#_isAbstract_]
=== isAbstract

==== Signature

[source,java]
----
@CheckReturnValue
boolean isAbstract()
----

==== Description

Checks if the type is prevented from having data instances (i.e., `abstract`). 


==== Returns

`boolean`

==== Code examples

[source,java]
----
type.isAbstract();
----

[#_isType_]
=== isType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isType()
----

==== Description

Checks if the concept is a `Type`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isType();
----

[#_asType_]
=== asType

==== Signature

[source,java]
----
@CheckReturnValue
default Type asType()
----

==== Description

Casts the concept to `Type`. 


==== Returns

`Type`

==== Code examples

[source,java]
----
concept.asType();
----

[#_toJSON_]
=== toJSON

==== Signature

[source,java]
----
default com.eclipsesource.json.JsonObject toJSON()
----

==== Description

Retrieves the concept as JSON. 


==== Returns

`com.eclipsesource.json.JsonObject`

==== Code examples

[source,java]
----
concept.toJSON();
----

[#_setLabel_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
=== setLabel

==== Signature

[source,java]
----
void setLabel​(TypeDBTransaction transaction,
              java.lang.String label)
----

==== Description

Renames the label of the type. The new label must remain unique. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `label` a| The new `Label` to be given to the type. a| `java.lang.String` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
type.setLabel(transaction, newLabel)
----

[#_getSupertype_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertype

==== Signature

[source,java]
----
@Nullable
@CheckReturnValue
Type getSupertype​(TypeDBTransaction transaction)
----

==== Description

Retrieves the most immediate supertype of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Type`

==== Code examples

[source,java]
----
type.getSupertype(transaction);
----

[#_getSupertypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSupertypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSupertypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all supertypes of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`java.util.stream.Stream<? extends Type>`

==== Code examples

[source,java]
----
type.getSupertypes(transaction);
----

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== getSubtypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSubtypes​(TypeDBTransaction transaction)
----

==== Description

Retrieves all direct and indirect subtypes of the type. Equivalent to `getSubtypes(transaction, Transitivity.TRANSITIVE)`


See also: <<#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,`getSubtypes(TypeDBTransaction, Transitivity)`>>


==== Returns

`java.util.stream.Stream<? extends Type>`

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
=== getSubtypes

==== Signature

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSubtypes​(TypeDBTransaction transaction,
                                                    Concept.Transitivity transitivity)
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the type. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect subtypes, `Transitivity.EXPLICIT` for direct subtypes only a| `Concept.Transitivity` 
|===

==== Returns

`java.util.stream.Stream<? extends Type>`

==== Code examples

[source,java]
----
type.getSubtypes(transaction);
 type.getSubtypes(transaction, Transitivity.EXPLICIT);
----

[#_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== delete

==== Signature

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

==== Description

Deletes this type from the database. 


==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`void`

==== Code examples

[source,java]
----
type.delete(transaction);
----

[#_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
=== isDeleted

==== Signature

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

==== Description

Check if the concept has been deleted

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`boolean`

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to `Attribute`. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to `AttributeType`. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to `Entity`. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to `EntityType`. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
default Relation asRelation()
----

==== Description

Casts the concept to `Relation`. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to `RelationType`. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
default RoleType asRoleType()
----

==== Description

Casts the concept to `RoleType`. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_asThing_]
=== asThing

==== Signature

[source,java]
----
default Thing asThing()
----

==== Description

Casts the concept to `Thing`. 


==== Returns

`Thing`

==== Code examples

[source,java]
----
concept.asThing();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
default ThingType asThingType()
----

==== Description

Casts the concept to `ThingType`. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to `Value`. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an `Attribute`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an `AttributeType`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an `Entity`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an `EntityType`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a `Relation`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a `RelationType`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a `RoleType`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_isThing_]
=== isThing

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

==== Description

Checks if the concept is a `Thing`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThing();
----

[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a `ThingType`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_isValue_]
=== isValue

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

==== Description

Checks if the concept is a `Value`. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

// end::methods[]
