[#_Type]
=== Type

*Package*: `com.vaticle.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`

// tag::methods[]
[#_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
com.vaticle.typedb.driver.common.Label getLabel()
----

Retrieves the unique label of the type. 


.Returns
`com.vaticle.typedb.driver.common.Label`

.Code examples
[source,java]
----
type.getLabel();
----

[#_isRoot_]
==== isRoot

[source,java]
----
@CheckReturnValue
boolean isRoot()
----

Checks if the type is a root type. 


.Returns
`boolean`

.Code examples
[source,java]
----
type.isRoot();
----

[#_isAbstract_]
==== isAbstract

[source,java]
----
@CheckReturnValue
boolean isAbstract()
----

Checks if the type is prevented from having data instances (i.e., ``abstract``). 


.Returns
`boolean`

.Code examples
[source,java]
----
type.isAbstract();
----

[#_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isType();
----

[#_asType_]
==== asType

[source,java]
----
@CheckReturnValue
default Type asType()
----

Casts the concept to ``Type``. 


.Returns
`Type`

.Code examples
[source,java]
----
concept.asType();
----

[#_toJSON_]
==== toJSON

[source,java]
----
default com.eclipsesource.json.JsonObject toJSON()
----

Retrieves the concept as JSON. 


.Returns
`com.eclipsesource.json.JsonObject`

.Code examples
[source,java]
----
concept.toJSON();
----

[#_setLabel_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== setLabel

[source,java]
----
void setLabel​(TypeDBTransaction transaction,
              java.lang.String label)
----

Renames the label of the type. The new label must remain unique. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `label` a| The new ``Label`` to be given to the type. a| `java.lang.String` 
|===

.Returns
`void`

.Code examples
[source,java]
----
type.setLabel(transaction, newLabel)
----

[#_getSupertype_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getSupertype

[source,java]
----
@Nullable
@CheckReturnValue
Type getSupertype​(TypeDBTransaction transaction)
----

Retrieves the most immediate supertype of the type. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Type`

.Code examples
[source,java]
----
type.getSupertype(transaction);
----

[#_getSupertypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getSupertypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSupertypes​(TypeDBTransaction transaction)
----

Retrieves all supertypes of the type. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`java.util.stream.Stream<? extends Type>`

.Code examples
[source,java]
----
type.getSupertypes(transaction);
----

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSubtypes​(TypeDBTransaction transaction)
----

Retrieves all direct and indirect subtypes of the type. Equivalent to ``getSubtypes(transaction, Transitivity.TRANSITIVE)``


See also: <<#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity,``getSubtypes(TypeDBTransaction, Transitivity)``>>


.Returns
`java.util.stream.Stream<? extends Type>`

[#_getSubtypes_com_vaticle_typedb_driver_api_TypeDBTransaction_com_vaticle_typedb_driver_api_concept_Concept_Transitivity]
==== getSubtypes

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Type> getSubtypes​(TypeDBTransaction transaction,
                                                    Concept.Transitivity transitivity)
----

Retrieves all direct and indirect (or direct only) subtypes of the type. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Concept.Transitivity` 
|===

.Returns
`java.util.stream.Stream<? extends Type>`

.Code examples
[source,java]
----
type.getSubtypes(transaction);
 type.getSubtypes(transaction, Transitivity.EXPLICIT);
----

[#_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== delete

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

Deletes this type from the database. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`void`

.Code examples
[source,java]
----
type.delete(transaction);
----

[#_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== isDeleted

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

Check if the concept has been deleted

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`boolean`

[#_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


.Returns
`Attribute`

.Code examples
[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


.Returns
`AttributeType`

.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


.Returns
`Entity`

.Code examples
[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


.Returns
`EntityType`

.Code examples
[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


.Returns
`Relation`

.Code examples
[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


.Returns
`RelationType`

.Code examples
[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


.Returns
`RoleType`

.Code examples
[source,java]
----
concept.asRoleType();
----

[#_asThing_]
==== asThing

[source,java]
----
default Thing asThing()
----

Casts the concept to ``Thing``. 


.Returns
`Thing`

.Code examples
[source,java]
----
concept.asThing();
----

[#_asThingType_]
==== asThingType

[source,java]
----
default ThingType asThingType()
----

Casts the concept to ``ThingType``. 


.Returns
`ThingType`

.Code examples
[source,java]
----
concept.asThingType();
----

[#_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


.Returns
`Value`

.Code examples
[source,java]
----
concept.asValue();
----

[#_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isRoleType();
----

[#_isThing_]
==== isThing

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

Checks if the concept is a ``Thing``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isThing();
----

[#_isThingType_]
==== isThingType

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

Checks if the concept is a ``ThingType``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isThingType();
----

[#_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


.Returns
`boolean`

.Code examples
[source,java]
----
concept.isValue();
----

// end::methods[]
