[#_TypeDBTransaction]
=== TypeDBTransaction

*Package*: `com.vaticle.typedb.driver.api`

*Superinterfaces:*

* `java.lang.AutoCloseable`

// tag::methods[]
[#_isOpen_]
==== isOpen

[source,java]
----
@CheckReturnValue
boolean isOpen()
----

Checks whether this transaction is open. 


.Returns
`boolean`

.Code examples
[source,java]
----
transaction.isOpen();
----

[#_type_]
==== type

[source,java]
----
@CheckReturnValue
TypeDBTransaction.Type type()
----

The transaction’s type (READ or WRITE)

.Returns
`TypeDBTransaction.Type`

[#_options_]
==== options

[source,java]
----
@CheckReturnValue
TypeDBOptions options()
----

The options for the transaction

.Returns
`TypeDBOptions`

[#_concepts_]
==== concepts

[source,java]
----
@CheckReturnValue
ConceptManager concepts()
----

The ``ConceptManager`` for this transaction, providing access to all Concept API methods.

.Returns
`ConceptManager`

[#_logic_]
==== logic

[source,java]
----
@CheckReturnValue
LogicManager logic()
----

The ``LogicManager`` for this Transaction, providing access to all Concept API - Logic methods.

.Returns
`LogicManager`

[#_query_]
==== query

[source,java]
----
@CheckReturnValue
QueryManager query()
----

The````QueryManager```` for this Transaction, from which any TypeQL query can be executed.

.Returns
`QueryManager`

[#_onClose_java_util_function_Consumer]
==== onClose

[source,java]
----
void onClose​(java.util.function.Consumer<java.lang.Throwable> function)
----

Registers a callback function which will be executed when this session is closed. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `java.util.function.Consumer<java.lang.Throwable>` 
|===

.Returns
`void`

.Code examples
[source,java]
----
transaction.onClose(function);
----

[#_commit_]
==== commit

[source,java]
----
void commit()
----

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call. 


.Returns
`void`

.Code examples
[source,java]
----
transaction.commit()
----

[#_rollback_]
==== rollback

[source,java]
----
void rollback()
----

Rolls back the uncommitted changes made via this transaction. 


.Returns
`void`

.Code examples
[source,java]
----
transaction.rollback()
----

[#_close_]
==== close

[source,java]
----
void close()
----

Closes the transaction. 


.Returns
`void`

.Code examples
[source,java]
----
transaction.close()
----

// end::methods[]
