[#_TypeDBSession_Type]
= TypeDBSession.Type

*Package*: `com.vaticle.typedb.driver.api`

== Description

Used to specify the type of the session. 


== Code examples

[source,java]
----
driver.session(database, TypeDBSession.Type.SCHEMA);
----

// tag::enum_constants[]
== Enum constants

[options="header"]
|===
|Name 
a| `DATA` 
a| `SCHEMA` 
|===
// end::enum_constants[]

== Methods

// tag::methods[]
[#_values_]
=== values

==== Signature

[source,java]
----
public static TypeDBSession.Type[] values()
----

==== Description

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (TypeDBSession.Type c : TypeDBSession.Type.values())
&nbsp;   System.out.println(c);

----


==== Returns

`public static TypeDBSession.Type[]`

==== Code examples

[source,java]
----
for (TypeDBSession.Type c : TypeDBSession.Type.values())
    System.out.println(c);
----

[#_valueOf_java_lang_String]
=== valueOf

==== Signature

[source,java]
----
public static TypeDBSession.Type valueOf​(java.lang.String name)
----

==== Description

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String` 
|===

==== Returns

`public static TypeDBSession.Type`

[#_of_com_vaticle_typedb_driver_jni_SessionType]
=== of

==== Signature

[source,java]
----
public static TypeDBSession.Type of​(com.vaticle.typedb.driver.jni.SessionType sessionType)
----

==== Description



==== Returns

`public static TypeDBSession.Type`

[#_id_]
=== id

==== Signature

[source,java]
----
public int id()
----

==== Description



==== Returns

`public int`

[#_isData_]
=== isData

==== Signature

[source,java]
----
public boolean isData()
----

==== Description



==== Returns

`public boolean`

[#_isSchema_]
=== isSchema

==== Signature

[source,java]
----
public boolean isSchema()
----

==== Description



==== Returns

`public boolean`

// end::methods[]
