[#_Value]
= Value

*Package*: `com.vaticle.typedb.driver.api.concept.value`

*Superinterfaces:*

* `Concept`

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `ISO_LOCAL_DATE_TIME_MILLIS` a| `static java.time.format.DateTimeFormatter` a| 
|===
// end::properties[]

== Methods

// tag::methods[]
[#_isValue_]
=== isValue

==== Signature

[source,java]
----
default boolean isValue()
----

==== Description

Checks if the concept is a ``Value``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isValue();
----

[#_asValue_]
=== asValue

==== Signature

[source,java]
----
default Value asValue()
----

==== Description

Casts the concept to ``Value``. 


==== Returns

`Value`

==== Code examples

[source,java]
----
concept.asValue();
----

[#_getType_]
=== getType

==== Signature

[source,java]
----
Value.Type getType()
----

==== Description

Retrieves the ``Value.Type`` of this value concept. 


==== Returns

`Value.Type`

==== Code examples

[source,java]
----
value.getType()
----

[#_isBoolean_]
=== isBoolean

==== Signature

[source,java]
----
boolean isBoolean()
----

==== Description

Returns ``True`` if the value which this value concept holds is of type ``boolean``. Otherwise, returns ``false``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.isBoolean()
----

[#_isLong_]
=== isLong

==== Signature

[source,java]
----
boolean isLong()
----

==== Description

Returns ``True`` if the value which this value concept holds is of type ``long``. Otherwise, returns ``false``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.isLong();
----

[#_isDouble_]
=== isDouble

==== Signature

[source,java]
----
boolean isDouble()
----

==== Description

Returns ``True`` if the value which this value concept holds is of type ``double``. Otherwise, returns ``false``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.isDouble();
----

[#_isString_]
=== isString

==== Signature

[source,java]
----
boolean isString()
----

==== Description

Returns ``True`` if the value which this value concept holds is of type ``string``. Otherwise, returns ``false``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.isString();
----

[#_isDateTime_]
=== isDateTime

==== Signature

[source,java]
----
boolean isDateTime()
----

==== Description

Returns ``True`` if the value which this value concept holds is of type ``datetime``. Otherwise, returns ``false``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.isDatetime();
----

[#_asBoolean_]
=== asBoolean

==== Signature

[source,java]
----
boolean asBoolean()
----

==== Description

Returns a ``boolean`` value of this value concept. If the value has another type, raises an exception. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
value.asBoolean();
----

[#_asLong_]
=== asLong

==== Signature

[source,java]
----
long asLong()
----

==== Description

Returns a ``long`` value of this value concept. If the value has another type, raises an exception. 


==== Returns

`long`

==== Code examples

[source,java]
----
value.asLong();
----

[#_asDouble_]
=== asDouble

==== Signature

[source,java]
----
double asDouble()
----

==== Description

Returns a ``double`` value of this value concept. If the value has another type, raises an exception. 


==== Returns

`double`

==== Code examples

[source,java]
----
value.asDouble();
----

[#_asString_]
=== asString

==== Signature

[source,java]
----
java.lang.String asString()
----

==== Description

Returns a ``string`` value of this value concept. If the value has another type, raises an exception. 


==== Returns

`java.lang.String`

==== Code examples

[source,java]
----
value.asString();
----

[#_asDateTime_]
=== asDateTime

==== Signature

[source,java]
----
java.time.LocalDateTime asDateTime()
----

==== Description

Returns a ``datetime`` value of this value concept. If the value has another type, raises an exception. 


==== Returns

`java.time.LocalDateTime`

==== Code examples

[source,java]
----
value.asDatetime();
----

[#_toJSON_]
=== toJSON

==== Signature

[source,java]
----
default com.eclipsesource.json.JsonObject toJSON()
----

==== Description

Retrieves the concept as JSON. 


==== Returns

`com.eclipsesource.json.JsonObject`

[#_asAttribute_]
=== asAttribute

==== Signature

[source,java]
----
default Attribute asAttribute()
----

==== Description

Casts the concept to ``Attribute``. 


==== Returns

`Attribute`

==== Code examples

[source,java]
----
concept.asAttribute();
----

[#_asAttributeType_]
=== asAttributeType

==== Signature

[source,java]
----
default AttributeType asAttributeType()
----

==== Description

Casts the concept to ``AttributeType``. 


==== Returns

`AttributeType`

==== Code examples

[source,java]
----
concept.asAttributeType();
----

[#_asEntity_]
=== asEntity

==== Signature

[source,java]
----
default Entity asEntity()
----

==== Description

Casts the concept to ``Entity``. 


==== Returns

`Entity`

==== Code examples

[source,java]
----
concept.asEntity();
----

[#_asEntityType_]
=== asEntityType

==== Signature

[source,java]
----
default EntityType asEntityType()
----

==== Description

Casts the concept to ``EntityType``. 


==== Returns

`EntityType`

==== Code examples

[source,java]
----
concept.asEntityType();
----

[#_asRelation_]
=== asRelation

==== Signature

[source,java]
----
default Relation asRelation()
----

==== Description

Casts the concept to ``Relation``. 


==== Returns

`Relation`

==== Code examples

[source,java]
----
concept.asRelation();
----

[#_asRelationType_]
=== asRelationType

==== Signature

[source,java]
----
default RelationType asRelationType()
----

==== Description

Casts the concept to ``RelationType``. 


==== Returns

`RelationType`

==== Code examples

[source,java]
----
concept.asRelationType();
----

[#_asRoleType_]
=== asRoleType

==== Signature

[source,java]
----
default RoleType asRoleType()
----

==== Description

Casts the concept to ``RoleType``. 


==== Returns

`RoleType`

==== Code examples

[source,java]
----
concept.asRoleType();
----

[#_asThing_]
=== asThing

==== Signature

[source,java]
----
default Thing asThing()
----

==== Description

Casts the concept to ``Thing``. 


==== Returns

`Thing`

==== Code examples

[source,java]
----
concept.asThing();
----

[#_asThingType_]
=== asThingType

==== Signature

[source,java]
----
default ThingType asThingType()
----

==== Description

Casts the concept to ``ThingType``. 


==== Returns

`ThingType`

==== Code examples

[source,java]
----
concept.asThingType();
----

[#_asType_]
=== asType

==== Signature

[source,java]
----
default Type asType()
----

==== Description

Casts the concept to ``Type``. 


==== Returns

`Type`

==== Code examples

[source,java]
----
concept.asType();
----

[#_isAttribute_]
=== isAttribute

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

==== Description

Checks if the concept is an ``Attribute``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttribute();
----

[#_isAttributeType_]
=== isAttributeType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

==== Description

Checks if the concept is an ``AttributeType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isAttributeType();
----

[#_isEntity_]
=== isEntity

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

==== Description

Checks if the concept is an ``Entity``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntity();
----

[#_isEntityType_]
=== isEntityType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

==== Description

Checks if the concept is an ``EntityType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isEntityType();
----

[#_isRelation_]
=== isRelation

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

==== Description

Checks if the concept is a ``Relation``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelation();
----

[#_isRelationType_]
=== isRelationType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

==== Description

Checks if the concept is a ``RelationType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRelationType();
----

[#_isRoleType_]
=== isRoleType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

==== Description

Checks if the concept is a ``RoleType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isRoleType();
----

[#_isThing_]
=== isThing

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThing()
----

==== Description

Checks if the concept is a ``Thing``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThing();
----

[#_isThingType_]
=== isThingType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isThingType()
----

==== Description

Checks if the concept is a ``ThingType``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isThingType();
----

[#_isType_]
=== isType

==== Signature

[source,java]
----
@CheckReturnValue
default boolean isType()
----

==== Description

Checks if the concept is a ``Type``. 


==== Returns

`boolean`

==== Code examples

[source,java]
----
concept.isType();
----

// end::methods[]
