[#_ITypeDBTransaction]
=== ITypeDBTransaction

*Package*: `TypeDB.Driver.Api`



A transaction with a TypeDB database.

// tag::methods[]
[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Close_]
==== Close

[source,cs]
----
void Close()
----



Closes the transaction.

[caption=""]
.Returns
`void`

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Commit_]
==== Commit

[source,cs]
----
void Commit()
----



Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is committed successfully, it gets closed after the commit call.

[caption=""]
.Returns
`void`

[#_bool_TypeDB_Driver_Api_ITypeDBTransaction_IsOpen_]
==== IsOpen

[source,cs]
----
bool IsOpen()
----



Checks whether this transaction is open.

 
  Returns
 
 
  ``true`` if the transaction is open, ``false`` otherwise.
 


[caption=""]
.Returns
`bool`

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_OnClose_Action_Exception_function_]
==== OnClose

[source,cs]
----
void OnClose(Action< Exception? > function)
----



Registers a callback function which will be executed when this transaction is closed.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| `Action< Exception? >`
|===

[caption=""]
.Returns
`void`

[#_IQueryAnswer_TypeDB_Driver_Api_ITypeDBTransaction_Query_string_query_]
==== Query

[source,cs]
----
IQueryAnswer Query(string query)
----



Executes a TypeQL query in this transaction.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
|===

[caption=""]
.Returns
`IQueryAnswer`

[#_IQueryAnswer_TypeDB_Driver_Api_ITypeDBTransaction_Query_string_query_QueryOptions_options_]
==== Query

[source,cs]
----
IQueryAnswer Query(string query, QueryOptions options)
----



Executes a TypeQL query in this transaction with custom options.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL query string to execute. a| `string`
a| `options` a| Query options. a| `QueryOptions`
|===

[caption=""]
.Returns
`IQueryAnswer`

[#_void_TypeDB_Driver_Api_ITypeDBTransaction_Rollback_]
==== Rollback

[source,cs]
----
void Rollback()
----



Rolls back the uncommitted changes made via this transaction.

[caption=""]
.Returns
`void`

[#_TransactionType_TypeDB_Driver_Api_ITypeDBTransaction_Type]
==== Type

[source,cs]
----
TransactionType TypeDB.Driver.Api.ITypeDBTransaction.Type
----



The transaction's type (Read, Write, or Schema).

[caption=""]
.Returns
`TransactionType`

// end::methods[]

