[#_Rule]
=== Rule

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `string` a| The unique label of the rule.
a| `then` a| `string` a| The single statement that constitutes the ‘then’ of the rule.
a| `when` a| `string` a| The statements that constitute the ‘when’ of the rule.
|===
// end::properties[]

// tag::methods[]
[#_Rule_delete__transaction_TypeDBTransaction]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this rule.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
rule.delete(transaction)
----

[#_Rule_isDeleted__transaction_TypeDBTransaction]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Check if this rule has been deleted.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
rule.isDeleted(transaction)
----

[#_Rule_setLabel__transaction_TypeDBTransaction__label_string]
==== setLabel

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

Renames the label of the rule. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
a| `label` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
rule.setLabel(transaction, newLabel)
----

// end::methods[]

