[#_struct_Credential]
=== Credential

*Implements traits:*

* `Clone`
* `Debug`

User credentials and TLS encryption settings for connecting to TypeDB Cloud.

// tag::methods[]
[#_struct_Credential_is_tls_enabled__]
==== is_tls_enabled

[source,rust]
----
pub fn is_tls_enabled(&self) -> bool
----

Retrieves whether TLS is enabled for the connection.

[caption=""]
.Returns
[source,rust]
----
bool
----

[#_struct_Credential_password__]
==== password

[source,rust]
----
pub fn password(&self) -> &str
----

Retrieves the password used.

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_Credential_username__]
==== username

[source,rust]
----
pub fn username(&self) -> &str
----

Retrieves the username used.

[caption=""]
.Returns
[source,rust]
----
&str
----

[#_struct_Credential_with_tls__username_str__password_str__tls_root_ca_Option_Path_]
==== with_tls

[source,rust]
----
pub fn with_tls(
    username: &str,
    password: &str,
    tls_root_ca: Option<&Path>
) -> Result<Self>
----

Creates a credential with username and password. Specifies the connection must use TLS

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `&str`
a| `password` a| The password for the user a| `&str`
a| `tls_root_ca` a| Path to the CA certificate to use for authenticating server certificates. a| `Option<&Path>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[source,rust]
----
Credential::with_tls(username, password, Some(&path_to_ca));
----

[#_struct_Credential_without_tls__username_str__password_str]
==== without_tls

[source,rust]
----
pub fn without_tls(username: &str, password: &str) -> Self
----

Creates a credential with username and password. The connection will not use TLS

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `&str`
a| `password` a| The password for the user a| `&str`
|===

[caption=""]
.Returns
[source,rust]
----
Self
----

[caption=""]
.Code examples
[source,rust]
----
Credential::without_tls(username, password);
----

// end::methods[]

