[#_struct_DatabaseManager]
=== DatabaseManager

*Implements traits:*

* `Clone`
* `Debug`

Provides access to all database management methods.

// tag::methods[]
[#_struct_DatabaseManager_all__]
==== all

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn all(&self) -> Result<Vec<Database>>
----

--

sync::
+
--
[source,rust]
----
pub fn all(&self) -> Result<Vec<Database>>
----

--
====

Retrieves all databases present on the TypeDB server

[caption=""]
.Returns
[source,rust]
----
Result<Vec<Database>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().all().await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().all();
----

--
====

[#_struct_DatabaseManager_contains__name_impl_Into_String_]
==== contains

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn contains(&self, name: impl Into<String>) -> Result<bool>
----

--

sync::
+
--
[source,rust]
----
pub fn contains(&self, name: impl Into<String>) -> Result<bool>
----

--
====

Checks if a database with the given name exists

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The database name to be checked a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<bool>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().contains(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().contains(name);
----

--
====

[#_struct_DatabaseManager_create__name_impl_Into_String_]
==== create

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn create(&self, name: impl Into<String>) -> Result
----

--

sync::
+
--
[source,rust]
----
pub fn create(&self, name: impl Into<String>) -> Result
----

--
====

Create a database with the given name

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to be created a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().create(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().create(name);
----

--
====

[#_struct_DatabaseManager_get__name_impl_Into_String_]
==== get

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn get(&self, name: impl Into<String>) -> Result<Database>
----

--

sync::
+
--
[source,rust]
----
pub fn get(&self, name: impl Into<String>) -> Result<Database>
----

--
====

Retrieve the database with the given name.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to retrieve a| `impl Into<String>`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Database>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
driver.databases().get(name).await;
----

--

sync::
+
--
[source,rust]
----
driver.databases().get(name);
----

--
====

// end::methods[]

