[#_AttributeType]
=== AttributeType

*Supertypes:*

* `Type`

Attribute types represent properties that other types can own.

Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

// tag::methods[]
[#_AttributeType_as_attribute_type_]
==== as_attribute_type

[source,python]
----
as_attribute_type() -> AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
attribute.as_attribute_type()
----

[#_AttributeType_get_value_type_]
==== get_value_type

[source,python]
----
get_value_type() -> str
----

Retrieves the ``str`` describing the value type of this ``AttributeType`` concept.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute_type.get_value_type()
----

[#_AttributeType_is_attribute_type_]
==== is_attribute_type

[source,python]
----
is_attribute_type() -> bool
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_attribute_type()
----

[#_AttributeType_is_boolean_]
==== is_boolean

[source,python]
----
is_boolean() -> bool
----

Returns ``True`` if this attribute type is of type ``boolean``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_boolean()
----

[#_AttributeType_is_date_]
==== is_date

[source,python]
----
is_date() -> bool
----

Returns ``True`` if this attribute type is of type ``date``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_date()
----

[#_AttributeType_is_datetime_]
==== is_datetime

[source,python]
----
is_datetime() -> bool
----

Returns ``True`` if this attribute type is of type ``datetime``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_datetime()
----

[#_AttributeType_is_datetime_tz_]
==== is_datetime_tz

[source,python]
----
is_datetime_tz() -> bool
----

Returns ``True`` if this attribute type is of type ``datetime_tz``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_datetime_tz()
----

[#_AttributeType_is_decimal_]
==== is_decimal

[source,python]
----
is_decimal() -> bool
----

Returns ``True`` if this attribute type is of type ``decimal``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_decimal()
----

[#_AttributeType_is_double_]
==== is_double

[source,python]
----
is_double() -> bool
----

Returns ``True`` if this attribute type is of type ``double``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_double()
----

[#_AttributeType_is_duration_]
==== is_duration

[source,python]
----
is_duration() -> bool
----

Returns ``True`` if this attribute type is of type ``duration``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_duration()
----

[#_AttributeType_is_long_]
==== is_long

[source,python]
----
is_long() -> bool
----

Returns ``True`` if this attribute type is of type ``long``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_long()
----

[#_AttributeType_is_string_]
==== is_string

[source,python]
----
is_string() -> bool
----

Returns ``True`` if this attribute type is of type ``string``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_string()
----

[#_AttributeType_is_struct_]
==== is_struct

[source,python]
----
is_struct() -> bool
----

Returns ``True`` if this attribute type is of type ``struct``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_struct()
----

[#_AttributeType_is_untyped_]
==== is_untyped

[source,python]
----
is_untyped() -> bool
----

Returns ``True`` if this attribute type does not have a value type. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute_type.is_untyped()
----

// end::methods[]

