[#_Type]
=== Type

*Supertypes:*

* `Concept`

// tag::methods[]
[#_Type_delete_transaction_TypeDBTransaction]
==== delete

[source,python]
----
delete(transaction: TypeDBTransaction) -> Promise[None]
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
type_.delete(transaction).resolve()
----

[#_Type_get_label_]
==== get_label

[source,python]
----
get_label() -> Label
----

Retrieves the unique label of the type.

[caption=""]
.Returns
`Label`

[caption=""]
.Code examples
[source,python]
----
type_.get_label()
----

[#_Type_get_subtypes_transaction_TypeDBTransaction_transitivity_Transitivity]
==== get_subtypes

[source,python]
----
get_subtypes(transaction: TypeDBTransaction, transitivity: Transitivity = Transitivity.TRANSITIVE) -> Iterator[Type]
----

Retrieves all direct and indirect (or direct only) subtypes of the type.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity` a| `Transitivity.TRANSITIVE`
|===

[caption=""]
.Returns
`Iterator[Type]`

[caption=""]
.Code examples
[source,python]
----
type_.get_subtypes(transaction)
type_.get_subtypes(transaction, Transitivity.EXPLICIT)
----

[#_Type_get_supertype_transaction_TypeDBTransaction]
==== get_supertype

[source,python]
----
get_supertype(transaction: TypeDBTransaction) -> Promise[Type | None]
----

Retrieves the most immediate supertype of the type.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[Type | None]`

[caption=""]
.Code examples
[source,python]
----
type_.get_supertype(transaction).resolve()
----

[#_Type_get_supertypes_transaction_TypeDBTransaction]
==== get_supertypes

[source,python]
----
get_supertypes(transaction: TypeDBTransaction) -> Iterator[Type]
----

Retrieves all supertypes of the type.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[Type]`

[caption=""]
.Code examples
[source,python]
----
type_.get_supertypes(transaction)
----

[#_Type_is_abstract_]
==== is_abstract

[source,python]
----
is_abstract() -> bool
----

Checks if the type is prevented from having data instances (i.e., ``abstract``).

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_abstract()
----

[#_Type_is_root_]
==== is_root

[source,python]
----
is_root() -> bool
----

Checks if the type is a root type.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_root()
----

[#_Type_is_type_]
==== is_type

[source,python]
----
is_type() -> bool
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
type_.is_type()
----

[#_Type_set_label_transaction_TypeDBTransaction_new_label_str]
==== set_label

[source,python]
----
set_label(transaction: TypeDBTransaction, new_label: str) -> Promise[None]
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `new_label` a| The new name to be given to the type. a| `str` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
type_.set_label(transaction, new_label).resolve()
----

// end::methods[]

