
[#_connection_header]
== Connection

{page-version}@api-ref::partial$csharp/connection/Drivers.adoc[]

{page-version}@api-ref::partial$csharp/connection/ITypeDBDriver.adoc[]

{page-version}@api-ref::partial$csharp/connection/TypeDBCredential.adoc[]

{page-version}@api-ref::partial$csharp/connection/IDatabaseManager.adoc[]

{page-version}@api-ref::partial$csharp/connection/IDatabase.adoc[]

{page-version}@api-ref::partial$csharp/connection/IReplica.adoc[]

{page-version}@api-ref::partial$csharp/connection/IUserManager.adoc[]

{page-version}@api-ref::partial$csharp/connection/IUser.adoc[]

[#_session_header]
== Session

{page-version}@api-ref::partial$csharp/session/ITypeDBSession.adoc[]

{page-version}@api-ref::partial$csharp/session/SessionType.adoc[]

{page-version}@api-ref::partial$csharp/session/TypeDBOptions.adoc[]

[#_transaction_header]
== Transaction

{page-version}@api-ref::partial$csharp/transaction/ITypeDBTransaction.adoc[]

{page-version}@api-ref::partial$csharp/transaction/TransactionType.adoc[]

{page-version}@api-ref::partial$csharp/transaction/IQueryManager.adoc[]

[#_answer_header]
== Answer

{page-version}@api-ref::partial$csharp/answer/IConceptMap.adoc[]

{page-version}@api-ref::partial$csharp/answer/IConceptMapGroup.adoc[]

{page-version}@api-ref::partial$csharp/answer/IValueGroup.adoc[]

// {page-version}@api-ref::partial$csharp/answer/JSON.adoc[]

// {page-version}@api-ref::partial$csharp/answer/JSONType.adoc[]

{page-version}@api-ref::partial$csharp/answer/IExplainables.adoc[]

{page-version}@api-ref::partial$csharp/answer/IExplainable.adoc[]

{page-version}@api-ref::partial$csharp/answer/IExplanation.adoc[]

{page-version}@api-ref::partial$csharp/answer/Promise__T__.adoc[]

{page-version}@api-ref::partial$csharp/answer/VoidPromise.adoc[]

[#_concept_header]
== Concept

{page-version}@api-ref::partial$csharp/concept/IConceptManager.adoc[]

{page-version}@api-ref::partial$csharp/concept/IConcept.adoc[]

{page-version}@api-ref::partial$csharp/concept/Transitivity.adoc[]

[#_schema_header]
== Schema

{page-version}@api-ref::partial$csharp/schema/IType.adoc[]

{page-version}@api-ref::partial$csharp/schema/IThingType.adoc[]

{page-version}@api-ref::partial$csharp/schema/IEntityType.adoc[]

{page-version}@api-ref::partial$csharp/schema/IRelationType.adoc[]

{page-version}@api-ref::partial$csharp/schema/IRoleType.adoc[]

{page-version}@api-ref::partial$csharp/schema/IAttributeType.adoc[]

{page-version}@api-ref::partial$csharp/schema/Annotation.adoc[]

{page-version}@api-ref::partial$csharp/schema/Label.adoc[]

[#_data_header]
== Data

{page-version}@api-ref::partial$csharp/data/IThing.adoc[]

{page-version}@api-ref::partial$csharp/data/IEntity.adoc[]

{page-version}@api-ref::partial$csharp/data/IRelation.adoc[]

{page-version}@api-ref::partial$csharp/data/IAttribute.adoc[]

{page-version}@api-ref::partial$csharp/data/IValue.adoc[]

{page-version}@api-ref::partial$csharp/data/ValueType.adoc[]

{page-version}@api-ref::partial$csharp/data/ValueTypeExtensions.adoc[]

[#_logic_header]
== Logic

{page-version}@api-ref::partial$csharp/logic/ILogicManager.adoc[]

{page-version}@api-ref::partial$csharp/logic/IRule.adoc[]

[#_errors_header]
== Errors

{page-version}@api-ref::partial$csharp/errors/TypeDBDriverException.adoc[]
