[#_Entity]
=== Entity

*Supertypes:*

* `Thing`

Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `string` a| Retrieves the unique id of the Thing.
a| `inferred` a| `boolean` a| Checks if this Thing is inferred by a [Reasoning Rule].
a| `type` a| `EntityType` a| The type which this Entity belongs to.
|===
// end::properties[]

// tag::methods[]
[#_Entity_asAttribute_]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_Entity_asAttributeType_]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_Entity_asEntity_]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_Entity_asEntityType_]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_Entity_asRelation_]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_Entity_asRelationType_]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_Entity_asRoleType_]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_Entity_asThing_]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_Entity_asThingType_]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_Entity_asType_]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_Entity_asValue_]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_Entity_delete_transaction_TypeDBTransaction]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.delete(transaction)
----

[#_Entity_equals_concept_Concept]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_Entity_getHas_transaction_TypeDBTransaction]
==== getHas

[source,nodejs]
----
getHas(transaction): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Entity_getHas_transaction_TypeDBTransaction_annotations_Annotation_]
==== getHas

[source,nodejs]
----
getHas(transaction, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| The ``AttributeType``s to filter the attributes by a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Entity_getHas_transaction_TypeDBTransaction_attributeType_AttributeType]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeType): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType``s to filter the attributes by a| `AttributeType`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Entity_getHas_transaction_TypeDBTransaction_attributeTypes_AttributeType_]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Entity_getHas_transaction_TypeDBTransaction_attributeTypes_AttributeType_annotations_Annotation_]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_Entity_getPlaying_transaction_TypeDBTransaction]
==== getPlaying

[source,nodejs]
----
getPlaying(transaction): Stream<RoleType>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getPlaying(transaction)
----

[#_Entity_getRelations_transaction_TypeDBTransaction]
==== getRelations

[source,nodejs]
----
getRelations(transaction): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Entity_getRelations_transaction_TypeDBTransaction_roleTypes_RoleType_]
==== getRelations

[source,nodejs]
----
getRelations(transaction, roleTypes): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleTypes` a| The list of roles to filter the relations by. a| `RoleType[]`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_Entity_isAttribute_]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_Entity_isAttributeType_]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_Entity_isDeleted_transaction_TypeDBTransaction]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.isDeleted(transaction)
----

[#_Entity_isEntity_]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_Entity_isEntityType_]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_Entity_isRelation_]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_Entity_isRelationType_]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_Entity_isRoleType_]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_Entity_isThing_]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_Entity_isThingType_]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_Entity_isType_]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_Entity_isValue_]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_Entity_setHas_transaction_TypeDBTransaction_attribute_Attribute]
==== setHas

[source,nodejs]
----
setHas(transaction, attribute): Promise<void>
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.setHas(transaction, attribute)
----

[#_Entity_unsetHas_transaction_TypeDBTransaction_attribute_Attribute]
==== unsetHas

[source,nodejs]
----
unsetHas(transaction, attribute): Promise<void>
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thing.unsetHas(transaction, attribute)
----

// end::methods[]

