[#_struct_Entity]
=== Entity

`Class(name=Entity, anchor=struct_Entity, enumConstants=[], description=[Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances.], examples=[], fields=[Variable(name=iid, anchor=struct_Entity_iid, defaultValue=null, description=The unique id of this Entity, type=IID), Variable(name=type_, anchor=struct_Entity_type, defaultValue=null, description=The type which this Entity belongs to, type=Option<EntityType>)], methods=[Method(name=iid, signature=pub fn iid(&self) -> &IID, anchor=struct_Entity_iid_, args=[], description=[Retrieves the unique id of the ``Entity``.], examples=[entity.iid();], mode=async, returnDescription=null, returnType=&IID)], packagePath=null, superClasses=[Clone, Debug, Eq, PartialEq, StructuralPartialEq], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq`
* `StructuralPartialEq`

Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `IID` a| The unique id of this Entity
a| `type_` a| `Option<EntityType>` a| The type which this Entity belongs to
|===
// end::properties[]

// tag::methods[]
[#_struct_Entity_iid_]
==== iid

[source,rust]
----
pub fn iid(&self) -> &IID
----

Retrieves the unique id of the ``Entity``.

[caption=""]
.Returns
[source,rust]
----
&IID
----

[caption=""]
.Code examples
[source,rust]
----
entity.iid();
----

// end::methods[]

