[#_struct_Relation]
=== Relation

`Class(name=Relation, anchor=struct_Relation, enumConstants=[], description=[Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.], examples=[], fields=[Variable(name=iid, anchor=struct_Relation_iid, defaultValue=null, description=The unique id of this Relation, type=IID), Variable(name=type_, anchor=struct_Relation_type, defaultValue=null, description=The type which this Relation belongs to, type=Option<RelationType>)], methods=[Method(name=iid, signature=pub fn iid(&self) -> &IID, anchor=struct_Relation_iid_, args=[], description=[Retrieves the unique id of the ``Relation``.], examples=[relation.iid();], mode=async, returnDescription=null, returnType=&IID)], packagePath=null, superClasses=[Clone, Debug, Eq, PartialEq, StructuralPartialEq], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Clone`
* `Debug`
* `Eq`
* `PartialEq`
* `StructuralPartialEq`

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `IID` a| The unique id of this Relation
a| `type_` a| `Option<RelationType>` a| The type which this Relation belongs to
|===
// end::properties[]

// tag::methods[]
[#_struct_Relation_iid_]
==== iid

[source,rust]
----
pub fn iid(&self) -> &IID
----

Retrieves the unique id of the ``Relation``.

[caption=""]
.Returns
[source,rust]
----
&IID
----

[caption=""]
.Code examples
[source,rust]
----
relation.iid();
----

// end::methods[]

