[#_struct_Attribute]
= Attribute

*Implements traits:*

* `AttributeAPI`
* `Clone`
* `Debug`
* `PartialEq<Attribute>`
* `StructuralPartialEq`
* `ThingAPI`

== Description

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type. Attribute type can be uniquely addressed by its type and value.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `IID` a| 
a| `type_` a| `AttributeType` a| 
a| `value` a| `Value` a| 
a| `is_inferred` a| `bool` a| 
|===
// end::properties[]

== Methods

// tag::methods[]
[#_struct_Attribute_method_get_owners]
=== get_owners

==== Signature

[source,rust]
----
fn get_owners(
    &self,
    transaction: &Transaction<'_>,
    thing_type: Option<ThingType>
) -> Result<BoxStream<'_, Result<Thing>>>
----

==== Description

<<#_trait_AttributeAPI_method_get_owners,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Thing>>>
----

[#_struct_Attribute_tymethod_iid]
=== iid

==== Signature

[source,rust]
----
fn iid(&self) -> &IID
----

==== Description

<<#_trait_ThingAPI_tymethod_iid,Read more>>

==== Returns

[source,rust]
----
&IID
----

[#_struct_Attribute_tymethod_is_inferred]
=== is_inferred

==== Signature

[source,rust]
----
fn is_inferred(&self) -> bool
----

==== Description

<<#_trait_ThingAPI_tymethod_is_inferred,Read more>>

==== Returns

[source,rust]
----
bool
----

[#_struct_Attribute_tymethod_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

<<#_trait_ThingAPI_tymethod_is_deleted,Read more>>

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

[#_struct_Attribute_method_delete]
=== delete

==== Signature

[source,rust]
----
fn delete<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

<<#_trait_ThingAPI_method_delete,Read more>>

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

[#_struct_Attribute_method_get_has]
=== get_has

==== Signature

[source,rust]
----
fn get_has(
    &self,
    transaction: &Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<Attribute>>>
----

==== Description

<<#_trait_ThingAPI_method_get_has,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Attribute>>>
----

[#_struct_Attribute_method_set_has]
=== set_has

==== Signature

[source,rust]
----
fn set_has<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>,
    attribute: Attribute
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

<<#_trait_ThingAPI_method_set_has,Read more>>

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

[#_struct_Attribute_method_unset_has]
=== unset_has

==== Signature

[source,rust]
----
fn unset_has<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>,
    attribute: Attribute
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

<<#_trait_ThingAPI_method_unset_has,Read more>>

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

[#_struct_Attribute_method_get_relations]
=== get_relations

==== Signature

[source,rust]
----
fn get_relations(
    &self,
    transaction: &Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'_, Result<Relation>>>
----

==== Description

<<#_trait_ThingAPI_method_get_relations,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<Relation>>>
----

[#_struct_Attribute_method_get_playing]
=== get_playing

==== Signature

[source,rust]
----
fn get_playing(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RoleType>>>
----

==== Description

<<#_trait_ThingAPI_method_get_playing,Read more>>

==== Returns

[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

// end::methods[]
