[#_struct_DatabaseManager]
= DatabaseManager

*Implements traits:*

* `Clone`
* `Debug`

== Methods

// tag::methods[]
[#_struct_DatabaseManager_method_get]
=== get

==== Signature

[source,rust]
----
pub async fn get(&self, name: impl Into<String>) -> Result<Database>
----

==== Description

Retrieve the database with the given name.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to retrieve a| `impl Into<String>` 
|===

==== Returns

[source,rust]
----
Result<Database>
----

==== Code examples

[source,rust]
----
driver.databases().get(name).await;
----

[#_struct_DatabaseManager_method_contains]
=== contains

==== Signature

[source,rust]
----
pub async fn contains(&self, name: impl Into<String>) -> Result<bool>
----

==== Description

Checks if a database with the given name exists

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The database name to be checked a| `impl Into<String>` 
|===

==== Returns

[source,rust]
----
Result<bool>
----

==== Code examples

[source,rust]
----
driver.databases().contains(name).await;
----

[#_struct_DatabaseManager_method_create]
=== create

==== Signature

[source,rust]
----
pub async fn create(&self, name: impl Into<String>) -> Result
----

==== Description

Create a database with the given name

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to be created a| `impl Into<String>` 
|===

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
driver.databases().create(name).await;
----

[#_struct_DatabaseManager_method_all]
=== all

==== Signature

[source,rust]
----
pub async fn all(&self) -> Result<Vec<Database>>
----

==== Description

Retrieves all databases present on the TypeDB server

==== Returns

[source,rust]
----
Result<Vec<Database>>
----

==== Code examples

[source,rust]
----
driver.databases().all().await;
----

// end::methods[]
