[#_struct_LogicManager]
= LogicManager

*Implements traits:*

* `Clone`
* `Debug`

== Description

Provides methods for manipulating rules in the database.

== Methods

// tag::methods[]
[#_struct_LogicManager_method_put_rule]
=== put_rule

==== Signature

[source,rust]
----
pub async fn put_rule(
    &self,
    label: String,
    when: Conjunction,
    then: Variable
) -> Result<Rule>
----

==== Description

Creates a new Rule if none exists with the given label, or replaces the existing one.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or replace a| `String` 
a| `when` a| The when body of the rule to create a| `Conjunction` 
a| `then` a| The then body of the rule to create a| `Variable` 
|===

==== Returns

[source,rust]
----
Result<Rule>
----

==== Code examples

[source,rust]
----
transaction.logic().put_rule(label, when, then).await
----

[#_struct_LogicManager_method_get_rule]
=== get_rule

==== Signature

[source,rust]
----
pub async fn get_rule(&self, label: String) -> Result<Option<Rule>>
----

==== Description

Retrieves the Rule that has the given label.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the Rule to create or retrieve a| `String` 
|===

==== Returns

[source,rust]
----
Result<Option<Rule>>
----

==== Code examples

[source,rust]
----
transaction.logic().get_rule(label).await
----

[#_struct_LogicManager_method_get_rules]
=== get_rules

==== Signature

[source,rust]
----
pub fn get_rules(&self) -> Result<impl Stream<Item = Result<Rule>>>
----

==== Description

Retrieves all rules.

==== Returns

[source,rust]
----
Result<impl Stream<Item = Result<Rule>>>
----

==== Code examples

[source,rust]
----
transaction.logic.get_rules()
----

// end::methods[]
