[#_trait_ThingAPI]
=== Trait ThingAPI

// tag::methods[]
[#_trait_ThingAPI_tymethod_iid]
==== iid

[source,rust]
----
fn iid(&self) -> &IID
----

Retrieves the unique id of the ``Thing``.

.Returns
[source,rust]
----
&IID
----

.Code examples
[source,rust]
----
thing.iid();
----

[#_trait_ThingAPI_tymethod_is_inferred]
==== is_inferred

[source,rust]
----
fn is_inferred(&self) -> bool
----

Checks if this ``Thing`` is inferred by a [Reasoning Rule].

.Returns
[source,rust]
----
bool
----

.Code examples
[source,rust]
----
thing.is_inferred();
----

[#_trait_ThingAPI_tymethod_is_deleted]
==== is_deleted

[source,rust]
----
fn is_deleted<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>` 
|===

.Returns
[source,rust]
----
Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

.Code examples
[source,rust]
----
thing.is_deleted(transaction).await;
----

[#_trait_ThingAPI_method_delete]
==== delete

[source,rust]
----
fn delete<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>` 
|===

.Returns
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

.Code examples
[source,rust]
----
thing.delete(transaction).await;
----

[#_trait_ThingAPI_method_get_has]
==== get_has

[source,rust]
----
fn get_has(
    &self,
    transaction: &Transaction<'_>,
    attribute_types: Vec<AttributeType>,
    annotations: Vec<Annotation>
) -> Result<BoxStream<'_, Result<Attribute>>>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `attribute_type` a| The ``AttributeType`` to filter the attributes by a| 
a| `attribute_types` a| The ``AttributeType``s to filter the attributes by a| `Vec<AttributeType>` 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Vec<Annotation>` 
|===

.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Attribute>>>
----

.Code examples
[source,rust]
----
thing.get_has(transaction, attribute_type, annotations=vec![Annotation::Key]);
----

[#_trait_ThingAPI_method_set_has]
==== set_has

[source,rust]
----
fn set_has<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>,
    attribute: Attribute
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>` 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` 
|===

.Returns
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

.Code examples
[source,rust]
----
thing.set_has(transaction, attribute).await;
----

[#_trait_ThingAPI_method_unset_has]
==== unset_has

[source,rust]
----
fn unset_has<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>,
    attribute: Attribute
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&'life1 Transaction<'life2>` 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` 
|===

.Returns
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

.Code examples
[source,rust]
----
thing.unset_has(transaction, attribute).await;
----

[#_trait_ThingAPI_method_get_relations]
==== get_relations

[source,rust]
----
fn get_relations(
    &self,
    transaction: &Transaction<'_>,
    role_types: Vec<RoleType>
) -> Result<BoxStream<'_, Result<Relation>>>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
a| `role_types` a| The list of roles to filter the relations by. a| `Vec<RoleType>` 
|===

.Returns
[source,rust]
----
Result<BoxStream<'_, Result<Relation>>>
----

.Code examples
[source,rust]
----
thing.get_relations(transaction, role_types);
----

[#_trait_ThingAPI_method_get_playing]
==== get_playing

[source,rust]
----
fn get_playing(
    &self,
    transaction: &Transaction<'_>
) -> Result<BoxStream<'_, Result<RoleType>>>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `&Transaction<'_>` 
|===

.Returns
[source,rust]
----
Result<BoxStream<'_, Result<RoleType>>>
----

.Code examples
[source,rust]
----
thing.get_playing(transaction);
----

// end::methods[]
