[#_trait_RuleAPI]
= Trait RuleAPI

== Methods

// tag::methods[]
[#_trait_RuleAPI_tymethod_label]
=== label

==== Signature

[source,rust]
----
fn label(&self) -> &String
----

==== Description

Retrieves the unique label of the rule.

==== Returns

[source,rust]
----
&String
----

[#_trait_RuleAPI_tymethod_delete]
=== delete

==== Signature

[source,rust]
----
fn delete<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 mut self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

Deletes this rule.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>` 
|===

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Code examples

[source,rust]
----
rule.delete(transaction).await;
----

[#_trait_RuleAPI_tymethod_set_label]
=== set_label

==== Signature

[source,rust]
----
fn set_label<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 mut self,
    transaction: &'life1 Transaction<'life2>,
    new_label: String
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

Renames the label of the rule. The new label must remain unique.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>` 
a| `new_label` a| The new label to be given to the rule a| `String` 
|===

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Code examples

[source,rust]
----
rule.set_label(transaction, new_label).await;
----

[#_trait_RuleAPI_method_is_deleted]
=== is_deleted

==== Signature

[source,rust]
----
fn is_deleted<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Description

Check if this rule has been deleted.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>` 
|===

==== Returns

[source,rust]
----
Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

==== Code examples

[source,rust]
----
rule.is_deleted(transaction).await
----

// end::methods[]
