[#_struct_Transaction]
= Transaction

*Implements traits:*

* `Debug`

== Methods

// tag::methods[]
[#_struct_Transaction_method_is_open]
=== is_open

==== Signature

[source,rust]
----
pub fn is_open(&self) -> bool
----

==== Description

Closes the transaction.

==== Returns

[source,rust]
----
bool
----

==== Code examples

[source,rust]
----
transaction.close()
----

[#_struct_Transaction_method_type]
=== type_

==== Signature

[source,rust]
----
pub fn type_(&self) -> TransactionType
----

==== Description

Retrieves the transaction’s type (READ or WRITE).

==== Returns

[source,rust]
----
TransactionType
----

[#_struct_Transaction_method_query]
=== query

==== Signature

[source,rust]
----
pub fn query(&self) -> &QueryManager
----

==== Description

Retrieves the``QueryManager`` for this Transaction, from which any TypeQL query can be executed.

==== Returns

[source,rust]
----
&QueryManager
----

[#_struct_Transaction_method_concept]
=== concept

==== Signature

[source,rust]
----
pub fn concept(&self) -> &ConceptManager
----

==== Description

The ``ConceptManager`` for this transaction, providing access to all Concept API methods.

==== Returns

[source,rust]
----
&ConceptManager
----

[#_struct_Transaction_method_logic]
=== logic

==== Signature

[source,rust]
----
pub fn logic(&self) -> &LogicManager
----

==== Description

Retrieves the ``LogicManager`` for this Transaction, providing access to all Concept API - Logic methods.

==== Returns

[source,rust]
----
&LogicManager
----

[#_struct_Transaction_method_on_close]
=== on_close

==== Signature

[source,rust]
----
pub fn on_close(
    &self,
    callback: impl FnOnce(ConnectionError) + Send + Sync + 'static
)
----

==== Description

Registers a callback function which will be executed when this session is closed.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

==== Returns

[source,rust]
----
null
----

==== Code examples

[source,rust]
----
transaction.on_close(function)
----

[#_struct_Transaction_method_force_close]
=== force_close

==== Signature

[source,rust]
----
pub fn force_close(&self)
----

==== Description

Closes the transaction.

==== Returns

[source,rust]
----
null
----

==== Code examples

[source,rust]
----
transaction.force_close()
----

[#_struct_Transaction_method_commit]
=== commit

==== Signature

[source,rust]
----
pub async fn commit(self) -> Result
----

==== Description

Commits the changes made via this transaction to the TypeDB database. Whether or not the transaction is commited successfully, it gets closed after the commit call.

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
transaction.commit().await
----

[#_struct_Transaction_method_rollback]
=== rollback

==== Signature

[source,rust]
----
pub async fn rollback(&self) -> Result
----

==== Description

Rolls back the uncommitted changes made via this transaction.

==== Returns

[source,rust]
----
Result
----

==== Code examples

[source,rust]
----
transaction.rollback().await
----

// end::methods[]
