[#_IAttributeType]
=== IAttributeType

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThingType`
* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`



Attribute types represent properties that other types can own.

IAttribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

// tag::methods[]
[#_IAttributeType_IConcept__TypeDB_Driver_Api_IAttributeType_AsAttributeType___]
==== AsAttributeType

[source,cs]
----
IAttributeType IConcept. AsAttributeType()
----



Casts the concept to ``IAttributeType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IAttributeType IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.AsAttributeType();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__IValue_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, IValue value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `IValue`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__string_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, string value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `string`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__long_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, long value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `long`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__double_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, double value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `double`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__bool_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, bool value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `bool`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__System_DateTime_value_]
==== Get

[source,cs]
----
Promise< IAttribute > Get(ITypeDBTransaction transaction, System.DateTime value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| ``IAttribute``’s value a| `System​.DateTime`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Get(transaction, value).Resolve();
----

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > GetOwners(ITypeDBTransaction transaction)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType`` directly or through inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetOwners(transaction);
----

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__ICollection__Annotation___annotations_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > GetOwners(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``, filtered by ``Annotation``s, directly or through inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``IAttributeType`` with all given ``Annotation``s a| `ICollection< Annotation >`
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetOwners(transaction, annotations);
----

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > GetOwners(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| `IConcept​.Transitivity`
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetOwners(transaction, transitivity);
----

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__ICollection__Annotation___annotations__IConcept_Transitivity_transitivity_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > GetOwners(ITypeDBTransaction transaction, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``IAttributeType`` with all given ``Annotation``s a| `ICollection< Annotation >`
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| `IConcept​.Transitivity`
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetOwners(transaction, annotations, transitivity);
----

[#_Promise__string___TypeDB_Driver_Api_IAttributeType_GetRegex___ITypeDBTransaction_transaction_]
==== GetRegex

[source,cs]
----
Promise< string > GetRegex(ITypeDBTransaction transaction)
----



Retrieves the regular expression that is defined for this ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`Promise< string >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetRegex(transaction).Resolve();
----

[#_IEnumerable__IType___TypeDB_Driver_Api_IAttributeType_GetSubtypes___ITypeDBTransaction_transaction__IValue_ValueType_valueType_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > GetSubtypes(ITypeDBTransaction transaction, IValue.ValueType valueType)
----



Retrieves all direct and indirect subtypes of this ``IAttributeType`` with given ``IValue.ValueType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `valueType` a| ``IValue.ValueType`` for retrieving subtypes a| `IValue​.ValueType`
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetSubtypes(transaction, valueType);
----

[#_IEnumerable__IType___TypeDB_Driver_Api_IAttributeType_GetSubtypes___ITypeDBTransaction_transaction__IValue_ValueType_valueType__IConcept_Transitivity_transitivity_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > GetSubtypes(ITypeDBTransaction transaction, IValue.ValueType valueType, IConcept.Transitivity transitivity)
----



Retrieves all direct and indirect (or direct only) subtypes of this ``IAttributeType`` with given ``IValue.ValueType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `valueType` a| ``IValue.ValueType`` for retrieving subtypes a| `IValue​.ValueType`
a| `transitivity` a| ``Transitive`` for direct and indirect subtypes, ``Explicit`` for direct subtypes only a| `IConcept​.Transitivity`
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.GetSubtypes(transaction, valueType, transitivity);
----

[#_bool_IConcept__TypeDB_Driver_Api_IAttributeType_IsAttributeType___]
==== IsAttributeType

[source,cs]
----
bool IConcept. IsAttributeType()
----



Checks if the concept is an ``IAttributeType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.IsAttributeType();
----

[#_bool_TypeDB_Driver_Api_IAttributeType_IsBool___]
==== IsBool

[source,cs]
----
bool IsBool()
----



Returns ``True`` if the value for attributes of this type is of type ``bool``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
attributeType.IsBool();
----

[#_bool_TypeDB_Driver_Api_IAttributeType_IsDateTime___]
==== IsDateTime

[source,cs]
----
bool IsDateTime()
----



Returns ``True`` if the value for attributes of this type is of type ``datetime``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
attributeType.IsDateTime();
----

[#_bool_TypeDB_Driver_Api_IAttributeType_IsDouble___]
==== IsDouble

[source,cs]
----
bool IsDouble()
----



Returns ``True`` if the value for attributes of this type is of type ``double``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
attributeType.IsDouble();
----

[#_bool_TypeDB_Driver_Api_IAttributeType_IsLong___]
==== IsLong

[source,cs]
----
bool IsLong()
----



Returns ``True`` if the value for attributes of this type is of type ``long``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
attributeType.IsLong();
----

[#_bool_TypeDB_Driver_Api_IAttributeType_IsString___]
==== IsString

[source,cs]
----
bool IsString()
----



Returns ``True`` if the value for attributes of this type is of type ``string``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
attributeType.IsString();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__IValue_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, IValue value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `IValue`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__string_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, string value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``string`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `string`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__long_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, long value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``long`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `long`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__double_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, double value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``double`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `double`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__bool_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, bool value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``bool`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `bool`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__System_DateTime_value_]
==== Put

[source,cs]
----
Promise< IAttribute > Put(ITypeDBTransaction transaction, System.DateTime value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``DateTime`` value. The input DateTime value is treated as timezone naive, with DateTimeKind being ignored.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `value` a| New ``IAttribute``’s value a| `System​.DateTime`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
attributeType.Put(transaction, value).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_SetRegex___ITypeDBTransaction_transaction__string_regex_]
==== SetRegex

[source,cs]
----
VoidPromise SetRegex(ITypeDBTransaction transaction, string regex)
----



Sets a regular expression as a constraint for this ``IAttributeType``. ``Values`` of all ``IAttribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``IAttributeType``s with a ``string`` value type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `regex` a| Regular expression a| `string`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
attributeType.SetRegex(transaction, regex).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_SetSupertype___ITypeDBTransaction_transaction__IAttributeType_attributeType_]
==== SetSupertype

[source,cs]
----
VoidPromise SetSupertype(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Sets the supplied ``IAttributeType`` as the supertype of the current ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attributeType` a| The ``IAttributeType`` to set as the supertype of this ``IAttributeType`` a| `IAttributeType`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
attributeType.SetSupertype(transaction, superType).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_UnsetRegex___ITypeDBTransaction_transaction_]
==== UnsetRegex

[source,cs]
----
VoidPromise UnsetRegex(ITypeDBTransaction transaction)
----



Removes the regular expression that is defined for this ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
attributeType.UnsetRegex(transaction).Resolve();
----

[#_IValue_ValueType_TypeDB_Driver_Api_IAttributeType_ValueType]
==== ValueType

[source,cs]
----
IValue.ValueType TypeDB.Driver.Api.IAttributeType.ValueType
----



The ``IValue.ValueType`` of this ``IAttributeType``.


[caption=""]
.Returns
`IValue.ValueType`

[caption=""]
.Code examples
[source,cs]
----
attributeType.ValueType;
----

// end::methods[]

