[#_IEntityType]
=== IEntityType

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThingType`
* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`



Entity types represent the classification of independent objects in the data model of the business domain.

// tag::methods[]
[#_IEntityType_IConcept__TypeDB_Driver_Api_IEntityType_AsEntityType___]
==== AsEntityType

[source,cs]
----
IEntityType IConcept. AsEntityType()
----



Casts the concept to ``IEntityType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IEntityType IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.AsEntityType();
----

[#_Promise__IEntity___TypeDB_Driver_Api_IEntityType_Create___ITypeDBTransaction_transaction_]
==== Create

[source,cs]
----
Promise< IEntity > Create(ITypeDBTransaction transaction)
----



Creates and returns a new instance of this ``IEntityType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`Promise< IEntity >`

[caption=""]
.Code examples
[source,cs]
----
entityType.Create(transaction).Resolve();
----

[#_bool_IConcept__TypeDB_Driver_Api_IEntityType_IsEntityType___]
==== IsEntityType

[source,cs]
----
bool IConcept. IsEntityType()
----



Checks if the concept is an ``IEntityType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.IsEntityType();
----

[#_VoidPromise_TypeDB_Driver_Api_IEntityType_SetSupertype___ITypeDBTransaction_transaction__IEntityType_superEntityType_]
==== SetSupertype

[source,cs]
----
VoidPromise SetSupertype(ITypeDBTransaction transaction, IEntityType superEntityType)
----



Sets the supplied ``IEntityType`` as the supertype of the current ``IEntityType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `superEntityType` a| The ``IEntityType`` to set as the supertype of this ``IEntityType`` a| `IEntityType`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
entityType.SetSupertype(transaction, entityType).Resolve();
----

// end::methods[]

