[#_Label]
=== Label

*Package*: `TypeDB.Driver.Common`



A ``Label`` holds the uniquely identifying name of a type.

It consists of an optional ``scope``, and a ``name``, represented ``scope:name``. The scope is used only used to distinguish between role-types of the same name declared in different relation types.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `readonly string TypeDB​.Driver​.Common​.Label​.Name` a| `readonly string TypeDB​.Driver​.Common​.Label​.Name` a| Returns the name of this Label.
Examples
[source,cs]
----
label.Name;

----

a| `readonly? string TypeDB​.Driver​.Common​.Label​.Scope` a| `readonly? string TypeDB​.Driver​.Common​.Label​.Scope` a| Returns the scope of this Label.
Examples
[source,cs]
----
label.Scope;

----

|===
// end::properties[]

// tag::methods[]
[#_override_bool_TypeDB_Driver_Common_Label_Equals___object_obj_]
==== Equals

[source,cs]
----
override bool Equals(object? obj)
----



Checks if this Label is equal to another object.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `obj` a| Object to compare with a| `object?`
|===

[caption=""]
.Returns
`override bool`

[caption=""]
.Code examples
[source,cs]
----
label.Equals(obj);
----

[#_TypeDB_Driver_Common_Label_Label___string_scope__string_name_]
==== Label

[source,cs]
----
Label(string? scope, string name)
----



Creates a Label from a specified scope and name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `scope` a| Label scope a| `string?`
a| `name` a| Label name a| `string`
|===

[caption=""]
.Returns
`Label`

[caption=""]
.Code examples
[source,cs]
----
new Label("relation", "role");
----

[#_TypeDB_Driver_Common_Label_Label___string_name_]
==== Label

[source,cs]
----
Label(string name)
----



Creates a Label from a specified name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| Label name a| `string`
|===

[caption=""]
.Returns
`Label`

[caption=""]
.Code examples
[source,cs]
----
new Label("entity");
----

[#_string_TypeDB_Driver_Common_Label_ScopedName]
==== ScopedName

[source,cs]
----
string TypeDB.Driver.Common.Label.ScopedName
----



Returns the string representation of the scoped name.


[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
label.ScopedName;
----

[#_override_string_TypeDB_Driver_Common_Label_ToString___]
==== ToString

[source,cs]
----
override string ToString()
----



Returns the string representation of the scoped name.


[caption=""]
.Returns
`override string`

[caption=""]
.Code examples
[source,cs]
----
label.ToString();
----

// end::methods[]

