[#_TypeDB_Driver_Api_IThingType_Interface_Reference]
=== TypeDB.Driver.Api.IThingType Interface Reference

*Package*: `TypeDB.Driver.Api.IThingType Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`

// tag::methods[]
[#_IThingType_IConcept__TypeDB_Driver_Api_IThingType_AsThingType___]
==== AsThingType

[source,cs]
----
IThingType IConcept. TypeDB.Driver.Api.IThingType.AsThingType()
----



Casts the concept to ``IThingType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IThingType IConcept.`

[#_IEnumerable__IThing___TypeDB_Driver_Api_IThingType_GetInstances___ITypeDBTransaction_transaction_]
==== GetInstances

[source,cs]
----
IEnumerable< IThing > TypeDB.Driver.Api.IThingType.GetInstances(ITypeDBTransaction transaction)
----



Retrieves all ``IThing`` objects that are instances of this ``IThingType`` or its subtypes. Equivalent to ``GetInstances(transaction, Transitive)``

 
  See also
 
 
  ThingType::GetInstances(ITypeDBTransaction, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IThing >`

[#_IEnumerable__IThing___TypeDB_Driver_Api_IThingType_GetInstances___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetInstances

[source,cs]
----
IEnumerable< IThing > TypeDB.Driver.Api.IThingType.GetInstances(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves ``IThing`` objects that are instances of this exact ``IThingType``, OR this ``IThingType`` and any of its subtypes


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Explicit`` for direct instances only, ``Transitive`` to include instances of subtypes a| 
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__IValue_ValueType_valueType_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, IValue.ValueType valueType)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__ICollection__Annotation___annotations_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__IValue_ValueType_valueType__ICollection__Annotation___annotations_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, ICollection< Annotation > annotations)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType?, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__IValue_ValueType_valueType__IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType?, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__ICollection__Annotation___annotations__IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 
  See also
 
 
  ThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection&lt;Annotation&gt;, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwns___ITypeDBTransaction_transaction__IValue_ValueType_valueType__ICollection__Annotation___annotations__IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| 
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| 
|===

[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_Promise__IAttributeType___TypeDB_Driver_Api_IThingType_GetOwnsOverridden___ITypeDBTransaction_transaction__IAttributeType_attributeType_]
==== GetOwnsOverridden

[source,cs]
----
Promise< IAttributeType > TypeDB.Driver.Api.IThingType.GetOwnsOverridden(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Retrieves an ``IAttributeType``, ownership of which is overridden for this ``IThingType`` by a given ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``IAttributeType`` that overrides requested ``IAttributeType`` a| 
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IThingType_GetPlays___ITypeDBTransaction_transaction_]
==== GetPlays

[source,cs]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IThingType.GetPlays(ITypeDBTransaction transaction)
----



Retrieves all direct and inherited roles that are allowed to be played by the instances of this ``IThingType``.

 
  See also
 
 
  ThingType::GetPlays(ITypeDBTransaction, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IThingType_GetPlays___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetPlays

[source,cs]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IThingType.GetPlays(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``IThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| transitivity: ``Transitive`` for direct and indirect playing, ``Explicit`` for direct playing only a| 
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_Promise__IRoleType___TypeDB_Driver_Api_IThingType_GetPlaysOverridden___ITypeDBTransaction_transaction__IRoleType_roleType_]
==== GetPlaysOverridden

[source,cs]
----
Promise< IRoleType > TypeDB.Driver.Api.IThingType.GetPlaysOverridden(ITypeDBTransaction transaction, IRoleType roleType)
----



Retrieves a ``IRoleType`` that is overridden by the given ``role_type`` for this ``IThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The ``IRoleType`` that overrides an inherited role a| 
|===

[caption=""]
.Returns
`Promise< IRoleType >`

[#_Promise__string___TypeDB_Driver_Api_IThingType_GetSyntax___ITypeDBTransaction_transaction_]
==== GetSyntax

[source,cs]
----
Promise< string > TypeDB.Driver.Api.IThingType.GetSyntax(ITypeDBTransaction transaction)
----



Produces a pattern for creating this ``IThingType`` in a ``define`` query.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< string >`

[#_bool_IConcept__TypeDB_Driver_Api_IThingType_IsThingType___]
==== IsThingType

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IThingType.IsThingType()
----



Checks if the concept is a ``IThingType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetAbstract___ITypeDBTransaction_transaction_]
==== SetAbstract

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetAbstract(ITypeDBTransaction transaction)
----



Set a ``IThingType`` to be abstract, meaning it cannot have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns___ITypeDBTransaction_transaction__IAttributeType_attributeType__IAttributeType_overriddenType__ICollection__Annotation___annotations_]
==== SetOwns

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, IAttributeType? overriddenType, ICollection< Annotation > annotations)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``IAttributeType`` to be owned by the instances of this type. a| 
a| `overriddenType` a| The ``IAttributeType`` that this attribute ownership overrides, if applicable. a| 
a| `annotations` a| Adds annotations to the ownership. a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns___ITypeDBTransaction_transaction__IAttributeType_attributeType__IAttributeType_overriddenType_]
==== SetOwns

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, IAttributeType overriddenType)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``,

 
  See also
 
 
  ThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns___ITypeDBTransaction_transaction__IAttributeType_attributeType__ICollection__Annotation___annotations_]
==== SetOwns

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, ICollection< Annotation > annotations)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``.

 
  See also
 
 
  ThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns___ITypeDBTransaction_transaction__IAttributeType_attributeType_]
==== SetOwns

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``.

 
  See also
 
 
  ThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetPlays___ITypeDBTransaction_transaction__IRoleType_roleType_]
==== SetPlays

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetPlays(ITypeDBTransaction transaction, IRoleType roleType)
----



Allows the instances of this ``IThingType`` to play the given role.

 
  See also
 
 
  ThingType::SetPlays(ITypeDBTransaction, IRoleType, IRoleType)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetPlays___ITypeDBTransaction_transaction__IRoleType_roleType__IRoleType_overriddenType_]
==== SetPlays

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.SetPlays(ITypeDBTransaction transaction, IRoleType roleType, IRoleType overriddenType)
----



Allows the instances of this ``IThingType`` to play the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to be played by the instances of this type a| 
a| `overriddenType` a| The role type that this role overrides, if applicable a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetAbstract___ITypeDBTransaction_transaction_]
==== UnsetAbstract

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.UnsetAbstract(ITypeDBTransaction transaction)
----



Set a ``IThingType`` to be non-abstract, meaning it can have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetOwns___ITypeDBTransaction_transaction__IAttributeType_attributeType_]
==== UnsetOwns

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.UnsetOwns(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Disallows the instances of this ``IThingType`` from owning the given ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``IAttributeType`` to not be owned by the type. a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetPlays___ITypeDBTransaction_transaction__IRoleType_roleType_]
==== UnsetPlays

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IThingType.UnsetPlays(ITypeDBTransaction transaction, IRoleType roleType)
----



Disallows the instances of this ``IThingType`` from playing the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to not be played by the instances of this type. a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

