[#_TypeDB_Driver_Api_IType_Interface_Reference]
=== TypeDB.Driver.Api.IType Interface Reference

*Package*: `TypeDB.Driver.Api.IType Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IConcept`

// tag::methods[]
[#_IType_IConcept__TypeDB_Driver_Api_IType_AsType___]
==== AsType

[source,cs]
----
IType IConcept. TypeDB.Driver.Api.IType.AsType()
----



Casts the concept to ``IType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IType IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IType_Delete___ITypeDBTransaction_transaction_]
==== Delete

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IType.Delete(ITypeDBTransaction transaction)
----



Deletes this type from the database.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_IEnumerable__IType___TypeDB_Driver_Api_IType_GetSubtypes___ITypeDBTransaction_transaction_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > TypeDB.Driver.Api.IType.GetSubtypes(ITypeDBTransaction transaction)
----



Retrieves all direct and indirect subtypes of the type. Equivalent to ``GetSubtypes(transaction, Transitive)``

 
  See also
 
 
  Type::GetSubtypes(ITypeDBTransaction, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IType >`

[#_IEnumerable__IType___TypeDB_Driver_Api_IType_GetSubtypes___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > TypeDB.Driver.Api.IType.GetSubtypes(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitive`` for direct and indirect subtypes, ``Explicit`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[#_Promise__IType___TypeDB_Driver_Api_IType_GetSupertype___ITypeDBTransaction_transaction_]
==== GetSupertype

[source,cs]
----
Promise< IType > TypeDB.Driver.Api.IType.GetSupertype(ITypeDBTransaction transaction)
----



Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< IType >`

[#_IEnumerable__IType___TypeDB_Driver_Api_IType_GetSupertypes___ITypeDBTransaction_transaction_]
==== GetSupertypes

[source,cs]
----
IEnumerable< IType > TypeDB.Driver.Api.IType.GetSupertypes(ITypeDBTransaction transaction)
----



Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[#_bool_TypeDB_Driver_Api_IType_IsAbstract___]
==== IsAbstract

[source,cs]
----
bool TypeDB.Driver.Api.IType.IsAbstract()
----



Checks if the type is prevented from having data instances (i.e., ``abstract``).


[caption=""]
.Returns
`bool`

[#_Promise__bool___TypeDB_Driver_Api_IType_IsDeleted___ITypeDBTransaction_transaction_]
==== IsDeleted

[source,cs]
----
Promise< bool > TypeDB.Driver.Api.IType.IsDeleted(ITypeDBTransaction transaction)
----



Check if the concept has been deleted.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< bool >`

[#_bool_TypeDB_Driver_Api_IType_IsRoot___]
==== IsRoot

[source,cs]
----
bool TypeDB.Driver.Api.IType.IsRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[#_bool_IConcept__TypeDB_Driver_Api_IType_IsType___]
==== IsType

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IType.IsType()
----



Checks if the concept is a ``IType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IType_SetLabel___ITypeDBTransaction_transaction__string_label_]
==== SetLabel

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IType.SetLabel(ITypeDBTransaction transaction, string label)
----



Renames the label of the type. The new label must remain unique.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

