[#_TypeDB_Driver_Api_IAttributeType_Interface_Reference]
=== TypeDB.Driver.Api.IAttributeType Interface Reference

*Package*: `TypeDB.Driver.Api.IAttributeType Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IThingType`
* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`



Attribute types represent properties that other types can own.

IAttribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

// tag::methods[]
[#_IAttributeType_IConcept__TypeDB_Driver_Api_IAttributeType_AsAttributeType___]
==== AsAttributeType

[source,cs]
----
IAttributeType IConcept. TypeDB.Driver.Api.IAttributeType.AsAttributeType()
----



Casts the concept to ``IAttributeType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IAttributeType IConcept.`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__IValue_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, IValue value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__string_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, string value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__long_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, long value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__double_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, double value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__bool_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, bool value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Get___ITypeDBTransaction_transaction__System_DateTime_value_]
==== Get

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Get(ITypeDBTransaction transaction, System.DateTime value)
----



Retrieves an ``IAttribute`` of this ``IAttributeType`` with the given value if such ``IAttribute`` exists. Otherwise, returns ``None``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > TypeDB.Driver.Api.IAttributeType.GetOwners(ITypeDBTransaction transaction)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType`` directly or through inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__ICollection__Annotation___annotations_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > TypeDB.Driver.Api.IAttributeType.GetOwners(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``, filtered by ``Annotation``s, directly or through inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``IAttributeType`` with all given ``Annotation``s a| 
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > TypeDB.Driver.Api.IAttributeType.GetOwners(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| 
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[#_IEnumerable__IThingType___TypeDB_Driver_Api_IAttributeType_GetOwners___ITypeDBTransaction_transaction__ICollection__Annotation___annotations__IConcept_Transitivity_transitivity_]
==== GetOwners

[source,cs]
----
IEnumerable< IThingType > TypeDB.Driver.Api.IAttributeType.GetOwners(ITypeDBTransaction transaction, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieve all ``Things`` that own an attribute of this ``IAttributeType``, filtered by ``Annotation``s.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``IAttributeType`` with all given ``Annotation``s a| 
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| 
|===

[caption=""]
.Returns
`IEnumerable< IThingType >`

[#_Promise__string___TypeDB_Driver_Api_IAttributeType_GetRegex___ITypeDBTransaction_transaction_]
==== GetRegex

[source,cs]
----
Promise< string > TypeDB.Driver.Api.IAttributeType.GetRegex(ITypeDBTransaction transaction)
----



Retrieves the regular expression that is defined for this ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< string >`

[#_IEnumerable__IType___TypeDB_Driver_Api_IAttributeType_GetSubtypes___ITypeDBTransaction_transaction__IValue_ValueType_valueType_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > TypeDB.Driver.Api.IAttributeType.GetSubtypes(ITypeDBTransaction transaction, IValue.ValueType valueType)
----



Retrieves all direct and indirect subtypes of this ``IAttributeType`` with given ``IValue.ValueType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| ``IValue.ValueType`` for retrieving subtypes a| 
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[#_IEnumerable__IType___TypeDB_Driver_Api_IAttributeType_GetSubtypes___ITypeDBTransaction_transaction__IValue_ValueType_valueType__IConcept_Transitivity_transitivity_]
==== GetSubtypes

[source,cs]
----
IEnumerable< IType > TypeDB.Driver.Api.IAttributeType.GetSubtypes(ITypeDBTransaction transaction, IValue.ValueType valueType, IConcept.Transitivity transitivity)
----



Retrieves all direct and indirect (or direct only) subtypes of this ``IAttributeType`` with given ``IValue.ValueType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| ``IValue.ValueType`` for retrieving subtypes a| 
a| `transitivity` a| ``Transitive`` for direct and indirect subtypes, ``Explicit`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`IEnumerable< IType >`

[#_bool_IConcept__TypeDB_Driver_Api_IAttributeType_IsAttributeType___]
==== IsAttributeType

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IAttributeType.IsAttributeType()
----



Checks if the concept is an ``IAttributeType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_bool_TypeDB_Driver_Api_IAttributeType_IsBool___]
==== IsBool

[source,cs]
----
bool TypeDB.Driver.Api.IAttributeType.IsBool()
----



Returns ``True`` if the value for attributes of this type is of type ``bool``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IAttributeType_IsDateTime___]
==== IsDateTime

[source,cs]
----
bool TypeDB.Driver.Api.IAttributeType.IsDateTime()
----



Returns ``True`` if the value for attributes of this type is of type ``datetime``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IAttributeType_IsDouble___]
==== IsDouble

[source,cs]
----
bool TypeDB.Driver.Api.IAttributeType.IsDouble()
----



Returns ``True`` if the value for attributes of this type is of type ``double``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IAttributeType_IsLong___]
==== IsLong

[source,cs]
----
bool TypeDB.Driver.Api.IAttributeType.IsLong()
----



Returns ``True`` if the value for attributes of this type is of type ``long``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[#_bool_TypeDB_Driver_Api_IAttributeType_IsString___]
==== IsString

[source,cs]
----
bool TypeDB.Driver.Api.IAttributeType.IsString()
----



Returns ``True`` if the value for attributes of this type is of type ``string``. Otherwise, returns ``False``.


[caption=""]
.Returns
`bool`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__IValue_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, IValue value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__string_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, string value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``string`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__long_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, long value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``long`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__double_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, double value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``double`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__bool_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, bool value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``bool`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttribute___TypeDB_Driver_Api_IAttributeType_Put___ITypeDBTransaction_transaction__System_DateTime_value_]
==== Put

[source,cs]
----
Promise< IAttribute > TypeDB.Driver.Api.IAttributeType.Put(ITypeDBTransaction transaction, System.DateTime value)
----



Adds and returns an ``IAttribute`` of this ``IAttributeType`` with the given ``DateTime`` value. The input DateTime value is treated as timezone naive, with DateTimeKind being ignored.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``IAttribute``’s value a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_SetRegex___ITypeDBTransaction_transaction__string_regex_]
==== SetRegex

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IAttributeType.SetRegex(ITypeDBTransaction transaction, string regex)
----



Sets a regular expression as a constraint for this ``IAttributeType``. ``Values`` of all ``IAttribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``IAttributeType``s with a ``string`` value type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `regex` a| Regular expression a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_SetSupertype___ITypeDBTransaction_transaction__IAttributeType_attributeType_]
==== SetSupertype

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IAttributeType.SetSupertype(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Sets the supplied ``IAttributeType`` as the supertype of the current ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``IAttributeType`` to set as the supertype of this ``IAttributeType`` a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IAttributeType_UnsetRegex___ITypeDBTransaction_transaction_]
==== UnsetRegex

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IAttributeType.UnsetRegex(ITypeDBTransaction transaction)
----



Removes the regular expression that is defined for this ``IAttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

