[#_TypeDB_Driver_Api_IEntityType_Interface_Reference]
=== TypeDB.Driver.Api.IEntityType Interface Reference

*Package*: `TypeDB.Driver.Api.IEntityType Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IThingType`
* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`



Entity types represent the classification of independent objects in the data model of the business domain.

// tag::methods[]
[#_IEntityType_IConcept__TypeDB_Driver_Api_IEntityType_AsEntityType___]
==== AsEntityType

[source,cs]
----
IEntityType IConcept. TypeDB.Driver.Api.IEntityType.AsEntityType()
----



Casts the concept to ``IEntityType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IEntityType IConcept.`

[#_Promise__IEntity___TypeDB_Driver_Api_IEntityType_Create___ITypeDBTransaction_transaction_]
==== Create

[source,cs]
----
Promise< IEntity > TypeDB.Driver.Api.IEntityType.Create(ITypeDBTransaction transaction)
----



Creates and returns a new instance of this ``IEntityType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< IEntity >`

[#_bool_IConcept__TypeDB_Driver_Api_IEntityType_IsEntityType___]
==== IsEntityType

[source,cs]
----
bool IConcept. TypeDB.Driver.Api.IEntityType.IsEntityType()
----



Checks if the concept is an ``IEntityType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IEntityType_SetSupertype___ITypeDBTransaction_transaction__IEntityType_superEntityType_]
==== SetSupertype

[source,cs]
----
VoidPromise TypeDB.Driver.Api.IEntityType.SetSupertype(ITypeDBTransaction transaction, IEntityType superEntityType)
----



Sets the supplied ``IEntityType`` as the supertype of the current ``IEntityType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `superEntityType` a| The ``IEntityType`` to set as the supertype of this ``IEntityType`` a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

