[#_TypeDB_Driver_Api_IRelationType_Interface_Reference]
=== TypeDB.Driver.Api.IRelationType Interface Reference

*Package*: `TypeDB.Driver.Api.IRelationType Interface Reference`

*Supertypes:*

* `TypeDB.Driver.Api.IThingType`
* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`



Relation types (or subtypes of the relation root type) represent relationships between types. Relation types have roles. Other types can play roles in relations if it’s mentioned in their definition. A relation type must specify at least one role.

// tag::methods[]
[#_IRelationType_IConcept__TypeDB_Driver_Api_IRelationType_AsRelationType___]
==== AsRelationType

[source,csharp]
----
IRelationType IConcept. TypeDB.Driver.Api.IRelationType.AsRelationType()
----



Casts the concept to ``IRelationType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IRelationType IConcept.`

[#_Promise__IRelation___TypeDB_Driver_Api_IRelationType_Create___ITypeDBTransaction_transaction_]
==== Create

[source,csharp]
----
Promise< IRelation > TypeDB.Driver.Api.IRelationType.Create(ITypeDBTransaction transaction)
----



Creates and returns an instance of this ``IRelationType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`Promise< IRelation >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelates___ITypeDBTransaction_transaction_]
==== GetRelates

[source,csharp]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IRelationType.GetRelates(ITypeDBTransaction transaction)
----



Retrieves roles that this ``IRelationType`` relates to directly or via inheritance.

 
  See also
 
 
  IRelationType::getRelates(ITypeDBTransaction, IConcept.Transitivity)
 


[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_IEnumerable__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelates___ITypeDBTransaction_transaction__IConcept_Transitivity_transitivity_]
==== GetRelates

[source,csharp]
----
IEnumerable< IRoleType > TypeDB.Driver.Api.IRelationType.GetRelates(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves roles that this ``IRelationType`` relates to directly or via inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitive`` for direct and inherited relates, ``Explicit`` for direct relates only a| 
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_Promise__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelates___ITypeDBTransaction_transaction__string_roleLabel_]
==== GetRelates

[source,csharp]
----
Promise< IRoleType > TypeDB.Driver.Api.IRelationType.GetRelates(ITypeDBTransaction transaction, string roleLabel)
----



Retrieves roles that this ``IRelationType`` relates to directly or via inheritance. If ``role_label`` is given, returns a corresponding ``IRoleType`` or ``null``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleLabel` a| Label of the role we wish to retrieve a| 
|===

[caption=""]
.Returns
`Promise< IRoleType >`

[#_Promise__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelatesOverridden___ITypeDBTransaction_transaction__IRoleType_roleType_]
==== GetRelatesOverridden

[source,csharp]
----
Promise< IRoleType > TypeDB.Driver.Api.IRelationType.GetRelatesOverridden(ITypeDBTransaction transaction, IRoleType roleType)
----



Retrieves a ``IRoleType`` that is overridden by the role with the ``role_label``.

 
  See also
 
 
  <<#_Promise__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelatesOverridden___ITypeDBTransaction_transaction__string_roleLabel_,IRelationType::GetRelatesOverridden(ITypeDBTransaction, string)>>
 


[caption=""]
.Returns
`Promise< IRoleType >`

[#_Promise__IRoleType___TypeDB_Driver_Api_IRelationType_GetRelatesOverridden___ITypeDBTransaction_transaction__string_roleLabel_]
==== GetRelatesOverridden

[source,csharp]
----
Promise< IRoleType > TypeDB.Driver.Api.IRelationType.GetRelatesOverridden(ITypeDBTransaction transaction, string roleLabel)
----



Retrieves a ``IRoleType`` that is overridden by the role with the ``role_label``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleLabel` a| Label of the role that overrides an inherited role a| 
|===

[caption=""]
.Returns
`Promise< IRoleType >`

[#_bool_IConcept__TypeDB_Driver_Api_IRelationType_IsRelationType___]
==== IsRelationType

[source,csharp]
----
bool IConcept. TypeDB.Driver.Api.IRelationType.IsRelationType()
----



Checks if the concept is a ``IRelationType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_SetRelates___ITypeDBTransaction_transaction__string_roleLabel_]
==== SetRelates

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.SetRelates(ITypeDBTransaction transaction, string roleLabel)
----



Sets the new role that this ``IRelationType`` relates to.

 
  See also
 
 
  IRelationType::SetRelates(ITypeDBTransaction, string, string)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_SetRelates___ITypeDBTransaction_transaction__string_roleLabel__IRoleType_overriddenType_]
==== SetRelates

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.SetRelates(ITypeDBTransaction transaction, string roleLabel, IRoleType overriddenType)
----



Sets the new role that this ``IRelationType`` relates to.

 
  See also
 
 
  IRelationType::SetRelates(ITypeDBTransaction, string, string)
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_SetRelates___ITypeDBTransaction_transaction__string_roleLabel__string_overriddenLabel_]
==== SetRelates

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.SetRelates(ITypeDBTransaction transaction, string roleLabel, string? overriddenLabel)
----



Sets the new role that this ``IRelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleLabel` a| The new role for the ``IRelationType`` to relate to a| 
a| `overriddenLabel` a| The label being overridden, if applicable a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_SetSupertype___ITypeDBTransaction_transaction__IRelationType_superRelationType_]
==== SetSupertype

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.SetSupertype(ITypeDBTransaction transaction, IRelationType superRelationType)
----



Sets the supplied ``IRelationType`` as the supertype of the current ``IRelationType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `superRelationType` a| The ``IRelationType`` to set as the supertype of this ``IRelationType`` a| 
|===

[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_UnsetRelates___ITypeDBTransaction_transaction__IRoleType_roleType_]
==== UnsetRelates

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.UnsetRelates(ITypeDBTransaction transaction, IRoleType roleType)
----



Disallows this ``IRelationType`` from relating to the given role.

 
  See also
 
 
  <<#_VoidPromise_TypeDB_Driver_Api_IRelationType_UnsetRelates___ITypeDBTransaction_transaction__string_roleLabel_,IRelationType::UnsetRelates(ITypeDBTransaction, string)>>
 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IRelationType_UnsetRelates___ITypeDBTransaction_transaction__string_roleLabel_]
==== UnsetRelates

[source,csharp]
----
VoidPromise TypeDB.Driver.Api.IRelationType.UnsetRelates(ITypeDBTransaction transaction, string roleLabel)
----



Disallows this ``IRelationType`` from relating to the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleLabel` a| The role to not relate to the relation type. a| 
|===

[caption=""]
.Returns
`VoidPromise`

// end::methods[]

