[#_QueryManager]
=== QueryManager

*Package*: `com.vaticle.typedb.driver.api.query`

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_QueryManager_define__com_vaticle_typeql_lang_query_TypeQLDefine]
==== define

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> define​(com.vaticle.typeql.lang.query.TypeQLDefine query)
----

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_define__com_vaticle_typeql_lang_query_TypeQLDefine__TypeDBOptions]
==== define

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> define​(com.vaticle.typeql.lang.query.TypeQLDefine query,
                               TypeDBOptions options)
----

Performs a TypeQL Define query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDefine`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().define(query, options).resolve()
----

[#_QueryManager_define__java_lang_String]
==== define

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> define​(java.lang.String query)
----

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_define__java_lang_String__TypeDBOptions]
==== define

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> define​(java.lang.String query,
                               TypeDBOptions options)
----


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_delete__com_vaticle_typeql_lang_query_TypeQLDelete]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(com.vaticle.typeql.lang.query.TypeQLDelete query)
----

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_delete__com_vaticle_typeql_lang_query_TypeQLDelete__TypeDBOptions]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(com.vaticle.typeql.lang.query.TypeQLDelete query,
                               TypeDBOptions options)
----

Performs a TypeQL Delete query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDelete`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().delete(query, options).resolve()
----

[#_QueryManager_delete__java_lang_String]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(java.lang.String query)
----

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_delete__java_lang_String__TypeDBOptions]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(java.lang.String query,
                               TypeDBOptions options)
----


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_explain__ConceptMap_Explainable]
==== explain

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable)
----

Performs a TypeQL Explain query with default options.


See also: <<#_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable_com_vaticle_typedb_driver_api_TypeDBOptions,``explain(ConceptMap.Explainable, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<Explanation>`

[#_QueryManager_explain__ConceptMap_Explainable__TypeDBOptions]
==== explain

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable,
                                             TypeDBOptions options)
----

Performs a TypeQL Explain query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `ConceptMap.Explainable`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<Explanation>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().explain(explainable, options)
----

[#_QueryManager_fetch__com_vaticle_typeql_lang_query_TypeQLFetch]
==== fetch

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<JSON> fetch​(com.vaticle.typeql.lang.query.TypeQLFetch query)
----

Performs a TypeQL Fetch (Fetch) with default options.


See also: <<#_fetch_com_vaticle_typeql_lang_query_TypeQLFetch_com_vaticle_typedb_driver_api_TypeDBOptions,``fetch(TypeQLFetch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<JSON>`

[#_QueryManager_fetch__com_vaticle_typeql_lang_query_TypeQLFetch__TypeDBOptions]
==== fetch

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<JSON> fetch​(com.vaticle.typeql.lang.query.TypeQLFetch query,
                                    TypeDBOptions options)
----

Performs a TypeQL Fetch (Fetch) query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Fetch (Fetch) query to be executed a| `com.vaticle.typeql.lang.query.TypeQLFetch`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<JSON>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().fetch(query, options)
----

[#_QueryManager_fetch__java_lang_String]
==== fetch

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<JSON> fetch​(java.lang.String query)
----

Performs a TypeQL Fetch (Fetch) with default options.


See also: <<#_fetch_com_vaticle_typeql_lang_query_TypeQLFetch_com_vaticle_typedb_driver_api_TypeDBOptions,``fetch(TypeQLFetch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<JSON>`

[#_QueryManager_fetch__java_lang_String__TypeDBOptions]
==== fetch

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<JSON> fetch​(java.lang.String query,
                                    TypeDBOptions options)
----


See also: <<#_fetch_com_vaticle_typeql_lang_query_TypeQLFetch_com_vaticle_typedb_driver_api_TypeDBOptions,``fetch(TypeQLFetch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<JSON>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> get​(com.vaticle.typeql.lang.query.TypeQLGet query)
----

Performs a TypeQL Get (Get) with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet__TypeDBOptions]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> get​(com.vaticle.typeql.lang.query.TypeQLGet query,
                                        TypeDBOptions options)
----

Performs a TypeQL Get (Get) query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get (Get) query to be executed a| `com.vaticle.typeql.lang.query.TypeQLGet`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().get(query, options)
----

[#_QueryManager_get__java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> get​(java.lang.String query)
----

Performs a TypeQL Get (Get) with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_get__java_lang_String__TypeDBOptions]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> get​(java.lang.String query,
                                        TypeDBOptions options)
----


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Aggregate]
==== get

[source,java]
----
@CheckReturnValue
Promise<java.util.Optional<Value>> get​(com.vaticle.typeql.lang.query.TypeQLGet.Aggregate query)
----

Performs a TypeQL Get Aggregate query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.util.Optional<Value>>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Aggregate__TypeDBOptions]
==== get

[source,java]
----
@CheckReturnValue
Promise<java.util.Optional<Value>> get​(com.vaticle.typeql.lang.query.TypeQLGet.Aggregate query,
                                       TypeDBOptions options)
----

Performs a TypeQL Get Aggregate query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLGet.Aggregate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<java.util.Optional<Value>>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().getAggregate(query, options).resolve()
----

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Group]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> get​(com.vaticle.typeql.lang.query.TypeQLGet.Group query)
----

Performs a TypeQL Get Group query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Group__TypeDBOptions]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> get​(com.vaticle.typeql.lang.query.TypeQLGet.Group query,
                                             TypeDBOptions options)
----

Performs a TypeQL Get Group query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group query to be executed a| `com.vaticle.typeql.lang.query.TypeQLGet.Group`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().getGroup(query, options)
----

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Group_Aggregate]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ValueGroup> get​(com.vaticle.typeql.lang.query.TypeQLGet.Group.Aggregate query)
----

Performs a TypeQL Get Group Aggregate query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ValueGroup>`

[#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet_Group_Aggregate__TypeDBOptions]
==== get

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ValueGroup> get​(com.vaticle.typeql.lang.query.TypeQLGet.Group.Aggregate query,
                                        TypeDBOptions options)
----

Performs a TypeQL Get Group Aggregate query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLGet.Group.Aggregate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ValueGroup>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().getGroupAggregate(query, options)
----

[#_QueryManager_getAggregate__java_lang_String]
==== getAggregate

[source,java]
----
@CheckReturnValue
Promise<java.util.Optional<Value>> getAggregate​(java.lang.String query)
----

Performs a TypeQL Get Aggregate query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.util.Optional<Value>>`

[#_QueryManager_getAggregate__java_lang_String__TypeDBOptions]
==== getAggregate

[source,java]
----
@CheckReturnValue
Promise<java.util.Optional<Value>> getAggregate​(java.lang.String query,
                                                TypeDBOptions options)
----


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.util.Optional<Value>>`

[#_QueryManager_getGroup__java_lang_String]
==== getGroup

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> getGroup​(java.lang.String query)
----

Performs a TypeQL Get Group query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_getGroup__java_lang_String__TypeDBOptions]
==== getGroup

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> getGroup​(java.lang.String query,
                                                  TypeDBOptions options)
----


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_getGroupAggregate__java_lang_String]
==== getGroupAggregate

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ValueGroup> getGroupAggregate​(java.lang.String query)
----

Performs a TypeQL Get Group Aggregate query with default options.


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ValueGroup>`

[#_QueryManager_getGroupAggregate__java_lang_String__TypeDBOptions]
==== getGroupAggregate

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ValueGroup> getGroupAggregate​(java.lang.String query,
                                                      TypeDBOptions options)
----


See also: <<#_get_com_vaticle_typeql_lang_query_TypeQLGet_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``get(TypeQLGet.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ValueGroup>`

[#_QueryManager_insert__com_vaticle_typeql_lang_query_TypeQLInsert]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query)
----

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_insert__com_vaticle_typeql_lang_query_TypeQLInsert__TypeDBOptions]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query,
                                           TypeDBOptions options)
----

Performs a TypeQL Insert query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `com.vaticle.typeql.lang.query.TypeQLInsert`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().insert(query, options)
----

[#_QueryManager_insert__java_lang_String]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query)
----

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_insert__java_lang_String__TypeDBOptions]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query,
                                           TypeDBOptions options)
----


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_undefine__com_vaticle_typeql_lang_query_TypeQLUndefine]
==== undefine

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query)
----

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_undefine__com_vaticle_typeql_lang_query_TypeQLUndefine__TypeDBOptions]
==== undefine

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query,
                                 TypeDBOptions options)
----

Performs a TypeQL Undefine query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUndefine`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().undefine(query, options).resolve()
----

[#_QueryManager_undefine__java_lang_String]
==== undefine

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> undefine​(java.lang.String query)
----

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_undefine__java_lang_String__TypeDBOptions]
==== undefine

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> undefine​(java.lang.String query,
                                 TypeDBOptions options)
----


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`Promise<java.lang.Void>`

[#_QueryManager_update__com_vaticle_typeql_lang_query_TypeQLUpdate]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query)
----

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_update__com_vaticle_typeql_lang_query_TypeQLUpdate__TypeDBOptions]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query,
                                           TypeDBOptions options)
----

Performs a TypeQL Update query in the transaction. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUpdate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().update(query, options)
----

[#_QueryManager_update__java_lang_String]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query)
----

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_update__java_lang_String__TypeDBOptions]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query,
                                           TypeDBOptions options)
----


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

// end::methods[]

