[#_QueryManager]
=== QueryManager

*Package*: `com.vaticle.typedb.driver.api.query`

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_QueryManager_define_com_vaticle_typeql_lang_query_TypeQLDefine]
==== define

[source,java]
----
void define​(com.vaticle.typeql.lang.query.TypeQLDefine query)
----

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions]
==== define

[source,java]
----
void define​(com.vaticle.typeql.lang.query.TypeQLDefine query,
            TypeDBOptions options)
----

Performs a TypeQL Define query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDefine`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.query().define(query, options)
----

[#_QueryManager_define_java_lang_String]
==== define

[source,java]
----
void define​(java.lang.String query)
----

Performs a TypeQL Define query with default options.


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_define_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== define

[source,java]
----
void define​(java.lang.String query,
            TypeDBOptions options)
----


See also: <<#_define_com_vaticle_typeql_lang_query_TypeQLDefine_com_vaticle_typedb_driver_api_TypeDBOptions,``define(TypeQLDefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_delete_com_vaticle_typeql_lang_query_TypeQLDelete]
==== delete

[source,java]
----
void delete​(com.vaticle.typeql.lang.query.TypeQLDelete query)
----

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions]
==== delete

[source,java]
----
void delete​(com.vaticle.typeql.lang.query.TypeQLDelete query,
            TypeDBOptions options)
----

Performs a TypeQL Delete query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `com.vaticle.typeql.lang.query.TypeQLDelete`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.query().delete(query, options)
----

[#_QueryManager_delete_java_lang_String]
==== delete

[source,java]
----
void delete​(java.lang.String query)
----

Performs a TypeQL Delete query with default options.


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_delete_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== delete

[source,java]
----
void delete​(java.lang.String query,
            TypeDBOptions options)
----


See also: <<#_delete_com_vaticle_typeql_lang_query_TypeQLDelete_com_vaticle_typedb_driver_api_TypeDBOptions,``delete(TypeQLDelete, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable]
==== explain

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable)
----

Performs a TypeQL Explain query with default options.


See also: <<#_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable_com_vaticle_typedb_driver_api_TypeDBOptions,``explain(ConceptMap.Explainable, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<Explanation>`

[#_QueryManager_explain_com_vaticle_typedb_driver_api_answer_ConceptMap_Explainable_com_vaticle_typedb_driver_api_TypeDBOptions]
==== explain

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Explanation> explain​(ConceptMap.Explainable explainable,
                                             TypeDBOptions options)
----

Performs a TypeQL Explain query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `ConceptMap.Explainable`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<Explanation>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().explain(explainable, options)
----

[#_QueryManager_insert_com_vaticle_typeql_lang_query_TypeQLInsert]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query)
----

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(com.vaticle.typeql.lang.query.TypeQLInsert query,
                                           TypeDBOptions options)
----

Performs a TypeQL Insert query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `com.vaticle.typeql.lang.query.TypeQLInsert`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().insert(query, options)
----

[#_QueryManager_insert_java_lang_String]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query)
----

Performs a TypeQL Insert query with default options.


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_insert_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== insert

[source,java]
----
java.util.stream.Stream<ConceptMap> insert​(java.lang.String query,
                                           TypeDBOptions options)
----


See also: <<#_insert_com_vaticle_typeql_lang_query_TypeQLInsert_com_vaticle_typedb_driver_api_TypeDBOptions,``insert(TypeQLInsert, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(com.vaticle.typeql.lang.query.TypeQLMatch query)
----

Performs a TypeQL Match (Get) with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(com.vaticle.typeql.lang.query.TypeQLMatch query,
                                          TypeDBOptions options)
----

Performs a TypeQL Match (Get) query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match (Get) query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().match(query, options)
----

[#_QueryManager_match_java_lang_String]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(java.lang.String query)
----

Performs a TypeQL Match (Get) with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_match_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMap> match​(java.lang.String query,
                                          TypeDBOptions options)
----


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate]
==== match

[source,java]
----
@CheckReturnValue
Numeric match​(com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate query)
----

Performs a TypeQL Match Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Numeric`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions]
==== match

[source,java]
----
@CheckReturnValue
Numeric match​(com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate query,
              TypeDBOptions options)
----

Performs a TypeQL Match Aggregate query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Aggregate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Numeric`

[caption=""]
.Code examples
[source,java]
----
transaction.query().matchAggregate(query, options)
----

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group query)
----

Performs a TypeQL Match Group query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group query,
                                               TypeDBOptions options)
----

Performs a TypeQL Match Group query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Group`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().matchGroup(query, options)
----

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate query)
----

Performs a TypeQL Match Group Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<NumericGroup>`

[#_QueryManager_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions]
==== match

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> match​(com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate query,
                                            TypeDBOptions options)
----

Performs a TypeQL Match Group Aggregate query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `com.vaticle.typeql.lang.query.TypeQLMatch.Group.Aggregate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<NumericGroup>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().matchGroupAggregate(query, options)
----

[#_QueryManager_matchAggregate_java_lang_String]
==== matchAggregate

[source,java]
----
@CheckReturnValue
Numeric matchAggregate​(java.lang.String query)
----

Performs a TypeQL Match Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Numeric`

[#_QueryManager_matchAggregate_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== matchAggregate

[source,java]
----
@CheckReturnValue
Numeric matchAggregate​(java.lang.String query,
                       TypeDBOptions options)
----


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`Numeric`

[#_QueryManager_matchGroup_java_lang_String]
==== matchGroup

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> matchGroup​(java.lang.String query)
----

Performs a TypeQL Match Group query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_matchGroup_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== matchGroup

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<ConceptMapGroup> matchGroup​(java.lang.String query,
                                                    TypeDBOptions options)
----


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMapGroup>`

[#_QueryManager_matchGroupAggregate_java_lang_String]
==== matchGroupAggregate

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> matchGroupAggregate​(java.lang.String query)
----

Performs a TypeQL Match Group Aggregate query with default options.


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<NumericGroup>`

[#_QueryManager_matchGroupAggregate_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== matchGroupAggregate

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<NumericGroup> matchGroupAggregate​(java.lang.String query,
                                                          TypeDBOptions options)
----


See also: <<#_match_com_vaticle_typeql_lang_query_TypeQLMatch_Group_Aggregate_com_vaticle_typedb_driver_api_TypeDBOptions,``match(TypeQLMatch.Group.Aggregate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<NumericGroup>`

[#_QueryManager_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine]
==== undefine

[source,java]
----
void undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query)
----

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions]
==== undefine

[source,java]
----
void undefine​(com.vaticle.typeql.lang.query.TypeQLUndefine query,
              TypeDBOptions options)
----

Performs a TypeQL Undefine query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUndefine`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
transaction.query().undefine(query, options)
----

[#_QueryManager_undefine_java_lang_String]
==== undefine

[source,java]
----
void undefine​(java.lang.String query)
----

Performs a TypeQL Undefine query with default options.


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_undefine_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== undefine

[source,java]
----
void undefine​(java.lang.String query,
              TypeDBOptions options)
----


See also: <<#_undefine_com_vaticle_typeql_lang_query_TypeQLUndefine_com_vaticle_typedb_driver_api_TypeDBOptions,``undefine(TypeQLUndefine, TypeDBOptions)``>>


[caption=""]
.Returns
`void`

[#_QueryManager_update_com_vaticle_typeql_lang_query_TypeQLUpdate]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query)
----

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(com.vaticle.typeql.lang.query.TypeQLUpdate query,
                                           TypeDBOptions options)
----

Performs a TypeQL Update query in the transaction. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `com.vaticle.typeql.lang.query.TypeQLUpdate`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[caption=""]
.Code examples
[source,java]
----
transaction.query().update(query, options)
----

[#_QueryManager_update_java_lang_String]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query)
----

Performs a TypeQL Update query with default options.


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

[#_QueryManager_update_java_lang_String_com_vaticle_typedb_driver_api_TypeDBOptions]
==== update

[source,java]
----
java.util.stream.Stream<ConceptMap> update​(java.lang.String query,
                                           TypeDBOptions options)
----


See also: <<#_update_com_vaticle_typeql_lang_query_TypeQLUpdate_com_vaticle_typedb_driver_api_TypeDBOptions,``update(TypeQLUpdate, TypeDBOptions)``>>


[caption=""]
.Returns
`java.util.stream.Stream<ConceptMap>`

// end::methods[]

