[#_TypeDBTransaction_Type]
=== TypeDBTransaction.Type

*Package*: `com.vaticle.typedb.driver.api`

Used to specify the type of transaction. 


[caption=""]
.Examples
[source,java]
----
session.transaction(TransactionType.READ);
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `READ`
a| `WRITE`
|===
// end::enum_constants[]

// tag::methods[]
[#_TypeDBTransaction_Type_id__]
==== id

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_TypeDBTransaction_Type_isRead__]
==== isRead

[source,java]
----
public boolean isRead()
----



[caption=""]
.Returns
`public boolean`

[#_TypeDBTransaction_Type_isWrite__]
==== isWrite

[source,java]
----
public boolean isWrite()
----



[caption=""]
.Returns
`public boolean`

[#_TypeDBTransaction_Type_valueOf__java_lang_String]
==== valueOf

[source,java]
----
public static TypeDBTransaction.Type valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static TypeDBTransaction.Type`

[#_TypeDBTransaction_Type_values__]
==== values

[source,java]
----
public static TypeDBTransaction.Type[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (TypeDBTransaction.Type c : TypeDBTransaction.Type.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static TypeDBTransaction.Type[]`

[caption=""]
.Code examples
[source,java]
----
for (TypeDBTransaction.Type c : TypeDBTransaction.Type.values())
    System.out.println(c);
----

// end::methods[]

