[#_TypeDB]
=== TypeDB

*Package*: `com.vaticle.typedb.driver`

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `DEFAULT_ADDRESS` a| `static java.lang.String` a| 
|===
// end::properties[]

// tag::methods[]
[#_TypeDB_TypeDB__]
==== TypeDB

[source,java]
----
public TypeDB()
----



[caption=""]
.Returns
`public`

[#_TypeDB_coreDriver__java_lang_String]
==== coreDriver

[source,java]
----
public static TypeDBDriver coreDriver​(java.lang.String address)
----

Open a TypeDB Driver to a TypeDB Core server available at the provided address. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `java.lang.String`
|===

[caption=""]
.Returns
`public static TypeDBDriver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.coreDriver(address);
----

[#_TypeDB_enterpriseDriver__java_lang_String__TypeDBCredential]
==== enterpriseDriver

[source,java]
----
public static TypeDBDriver enterpriseDriver​(java.lang.String address,
                                            TypeDBCredential credential)
----

Open a TypeDB Driver to a TypeDB Enterprise server available at the provided address, using the provided credential. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `java.lang.String`
a| `credential` a| The credential to connect with a| `TypeDBCredential`
|===

[caption=""]
.Returns
`public static TypeDBDriver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.enterpriseDriver(address, credential);
----

[#_TypeDB_enterpriseDriver__java_util_Set_java_lang_String___TypeDBCredential]
==== enterpriseDriver

[source,java]
----
public static TypeDBDriver enterpriseDriver​(java.util.Set<java.lang.String> addresses,
                                            TypeDBCredential credential)
----

Open a TypeDB Driver to TypeDB Enterprise server(s) available at the provided addresses, using the provided credential. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a| The address(es) of the TypeDB server(s) a| `java.util.Set<java.lang.String>`
a| `credential` a| The credential to connect with a| `TypeDBCredential`
|===

[caption=""]
.Returns
`public static TypeDBDriver`

[caption=""]
.Code examples
[source,java]
----
TypeDB.enterpriseDriver(addresses, credential);
----

// end::methods[]

