[#_methods_answer_conceptrow]
=== conceptrow

[#_Struct_ConceptRow]
[.doc-api-reference-driver]
==== Struct ConceptRow

`rust struct (pointer)`



A single row of concepts representing substitutions for variables in the query. Contains a Header (column names and query type), and the row of optional concepts. An empty concept in a column means the variable does not have a substitution in this answer.

[#_concept_row_drop]
===== function ``concept_row_drop``

[source,c]
----
void concept_row_drop(struct ConceptRow* concept_row)
----



Frees the native rust ``ConceptRow`` object.

[caption=""]
.Returns
`void`

[#_concept_row_equals]
===== function ``concept_row_equals``

[source,c]
----
bool concept_row_equals(const struct ConceptRow* lhs, const struct ConceptRow* rhs)
----



Checks whether the provided ``ConceptRow`` objects are equal

[caption=""]
.Returns
`bool`

[#_concept_row_get]
===== function ``concept_row_get``

[source,c]
----
struct Concept* concept_row_get(const struct ConceptRow* concept_row, const char* column_name)
----



Retrieves a concept for a given column name.

[caption=""]
.Returns
`struct Concept*`

[#_concept_row_get_column_names]
===== function ``concept_row_get_column_names``

[source,c]
----
struct StringIterator* concept_row_get_column_names(const struct ConceptRow* concept_row)
----



Produces an ``Iterator`` over all ``String`` column names of the ``ConceptRow``'s header.

[caption=""]
.Returns
`struct StringIterator*`

[#_concept_row_get_concepts]
===== function ``concept_row_get_concepts``

[source,c]
----
struct ConceptIterator* concept_row_get_concepts(const struct ConceptRow* concept_row)
----



Produces an ``Iterator`` over all ``Concepts`` in this ``ConceptRow``.

[caption=""]
.Returns
`struct ConceptIterator*`

[#_concept_row_get_index]
===== function ``concept_row_get_index``

[source,c]
----
struct Concept* concept_row_get_index(const struct ConceptRow* concept_row, uintptr_t column_index)
----



Retrieves a concept for a given column index.

[caption=""]
.Returns
`struct Concept*`

[#_concept_row_get_query_structure]
===== function ``concept_row_get_query_structure``

[source,c]
----
struct Pipeline* concept_row_get_query_structure(const struct ConceptRow* concept_row)
----



Retrieve the executed query's structure from the ``ConceptRow``'s header, if set. It must be requested via "include query structure" in ``QueryOptions``

[caption=""]
.Returns
`struct Pipeline*`

[#_concept_row_get_query_type]
===== function ``concept_row_get_query_type``

[source,c]
----
enum QueryType concept_row_get_query_type(const struct ConceptRow* concept_row)
----



Retrieve the executed query's type of the ``ConceptRow``'s header.

[caption=""]
.Returns
`enum QueryType`

[#_concept_row_involved_conjunctions]
===== function ``concept_row_involved_conjunctions``

[source,c]
----
struct ConjunctionIDIterator* concept_row_involved_conjunctions(const struct ConceptRow* concept_row)
----



Retrieve the ``ConjunctionID``s of ``Conjunction``s that answered this row. May be null.

[caption=""]
.Returns
`struct ConjunctionIDIterator*`

[#_concept_row_to_string]
===== function ``concept_row_to_string``

[source,c]
----
char* concept_row_to_string(const struct ConceptRow* concept_row)
----



A string representation of this ConceptRow.

[caption=""]
.Returns
`char*`

