[#_methods_answer_queryanswer]
=== queryanswer

[#_query_answer_drop]
==== function <code>query_answer_drop</code>

[source,c]
----
void query_answer_drop(struct QueryAnswer* query_answer)
----



Frees the native rust ``QueryAnswer`` object.

[caption=""]
.Returns
`void`

[#_query_answer_get_query_type]
==== function <code>query_answer_get_query_type</code>

[source,c]
----
enum QueryType query_answer_get_query_type(const struct QueryAnswer* query_answer)
----



Retrieve the executed query's type of the ``QueryAnswer``.

[caption=""]
.Returns
`enum QueryType`

[#_query_answer_into_documents]
==== function <code>query_answer_into_documents</code>

[source,c]
----
struct StringIterator* query_answer_into_documents(struct QueryAnswer* query_answer)
----



Produces an ``Iterator`` over all JSON ``ConceptDocument``s in this ``QueryAnswer``.

[caption=""]
.Returns
`struct StringIterator*`

[#_query_answer_into_rows]
==== function <code>query_answer_into_rows</code>

[source,c]
----
struct ConceptRowIterator* query_answer_into_rows(struct QueryAnswer* query_answer)
----



Produces an ``Iterator`` over all ``ConceptRow``s in this ``QueryAnswer``.

[caption=""]
.Returns
`struct ConceptRowIterator*`

[#_query_answer_is_concept_document_stream]
==== function <code>query_answer_is_concept_document_stream</code>

[source,c]
----
bool query_answer_is_concept_document_stream(const struct QueryAnswer* query_answer)
----



Checks if the query answer is a ``ConceptDocumentStream``.

[caption=""]
.Returns
`bool`

[#_query_answer_is_concept_row_stream]
==== function <code>query_answer_is_concept_row_stream</code>

[source,c]
----
bool query_answer_is_concept_row_stream(const struct QueryAnswer* query_answer)
----



Checks if the query answer is a ``ConceptRowStream``.

[caption=""]
.Returns
`bool`

[#_query_answer_is_ok]
==== function <code>query_answer_is_ok</code>

[source,c]
----
bool query_answer_is_ok(const struct QueryAnswer* query_answer)
----



Checks if the query answer is an ``Ok``.

[caption=""]
.Returns
`bool`

