[#_methods_answer_voidpromise]
=== voidpromise

[#_Struct_VoidPromise]
==== Struct VoidPromise

`Class(name=Struct VoidPromise, anchor=Struct_VoidPromise, enumConstants=[], description=[, Promise object representing the result of an asynchronous operation. A VoidPromise does not return a value, but must be resolved using void_promise_resolve(VoidPromise*) to ensure the operation has completed, or for a failed operation to set the error.], examples=[], fields=[], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`



Promise object representing the result of an asynchronous operation. A VoidPromise does not return a value, but must be resolved using void_promise_resolve(VoidPromise*) to ensure the operation has completed, or for a failed operation to set the error.

[#_void_promise_drop]
==== void_promise_drop

[source,cpp]
----
void void_promise_drop(struct VoidPromise* promise)
----



Frees the native rust ``VoidPromise`` object.

[caption=""]
.Returns
`void`

[#_void_promise_resolve]
==== void_promise_resolve

[source,cpp]
----
void void_promise_resolve(struct VoidPromise* promise)
----



Waits for the operation represented by the ``VoidPromise`` to complete. In case the operation failed, the error flag will only be set when the promise is resolved. The native promise object is freed when it is resolved.

[caption=""]
.Returns
`void`

