[#_ConceptRow]
=== ConceptRow

*Package*: `com.typedb.driver.api.answer`

Contains a row of concepts with a header.

// tag::methods[]
[#_ConceptRow_columnNames_]
==== columnNames

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<java.lang.String> columnNames()
----

Produces a stream over all column names (header) in this ``ConceptRow``. Shared between all the rows in a QueryAnswer. 


[caption=""]
.Returns
`java.util.stream.Stream<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.header();
----

[#_ConceptRow_concepts_]
==== concepts

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Concept> concepts()
----

Produces an iterator over all concepts in this `ConceptRow`, skipping empty results. 


[caption=""]
.Returns
`java.util.stream.Stream<? extends Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.concepts();
----

[#_ConceptRow_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
Concept get​(java.lang.String columnName)
----

Retrieves a concept for a given variable name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnName` a| the column name (header) a| `java.lang.String`
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,java]
----
conceptRow.get(columnName);
----

[#_ConceptRow_getIndex_long]
==== getIndex

[source,java]
----
@CheckReturnValue
Concept getIndex​(long columnIndex)
----

Retrieves a concept for a given variable name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnIndex` a| the column index a| `long`
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,java]
----
conceptRow.getIndex(columnIndex);
----

[#_ConceptRow_getQueryType_]
==== getQueryType

[source,java]
----
@CheckReturnValue
QueryType getQueryType()
----

Retrieves the executed query's type of this ``ConceptRow``. Shared between all the rows in a QueryAnswer. 


[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,java]
----
conceptRow.queryType();
----

// end::methods[]

