[#_ConceptRow]
=== ConceptRow

*Package*: `com.typedb.driver.api.answer`

Contains a row of concepts with a header.

// tag::methods[]
[#_ConceptRow_columnNames_]
==== columnNames

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<java.lang.String> columnNames()
----

Produces a stream over all column names (variables) in the header of this ``ConceptRow``. Shared between all the rows in a QueryAnswer. 


[caption=""]
.Returns
`java.util.stream.Stream<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.columnNames();
----

[#_ConceptRow_concepts_]
==== concepts

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<? extends Concept> concepts()
----

Produces a stream over all concepts in this `ConceptRow`, skipping empty results. 


[caption=""]
.Returns
`java.util.stream.Stream<? extends Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.concepts();
----

[#_ConceptRow_get_java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
java.util.Optional<Concept> get​(java.lang.String columnName)
                         throws TypeDBDriverException
----

Retrieves a concept for a given column name (variable). Returns an empty ``Optional`` if the variable has an empty answer. Throws an exception if the variable is not present. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnName` a| the variable (column name from ``column_names``) a| `java.lang.String`
|===

[caption=""]
.Returns
`java.util.Optional<Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.get(columnName);
----

[#_ConceptRow_getIndex_long]
==== getIndex

[source,java]
----
@CheckReturnValue
java.util.Optional<Concept> getIndex​(long columnIndex)
                              throws TypeDBDriverException
----

Retrieves a concept for a given index of the header (``columnNames``). Returns an empty ``Optional`` if the index points to an empty answer. Throws an exception if the index is not in the row's range. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `columnIndex` a| the column index a| `long`
|===

[caption=""]
.Returns
`java.util.Optional<Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptRow.getIndex(columnIndex);
----

[#_ConceptRow_getQueryType_]
==== getQueryType

[source,java]
----
@CheckReturnValue
QueryType getQueryType()
----

Retrieves the executed query's type of this ``ConceptRow``. Shared between all the rows in a QueryAnswer. 


[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,java]
----
conceptRow.getQueryType();
----

[#_ConceptRow_involvedBlocks_]
==== involvedBlocks

[source,java]
----
java.util.stream.Stream<com.typedb.driver.jni.ConjunctionID> involvedBlocks()
----

Retrieve the ``ConjunctionID``s of ``Conjunction`` that answered this row. *

[caption=""]
.Returns
`java.util.stream.Stream<com.typedb.driver.jni.ConjunctionID>`

// end::methods[]

