[#_ConceptDocumentIterator]
=== ConceptDocumentIterator

`Class(name=ConceptDocumentIterator, anchor=ConceptDocumentIterator, enumConstants=[], description=[Represents an iterator over concept documents (represented as ``JSON``s) returned as a server answer.], examples=[], fields=[], methods=[Method(name=isConceptDocuments, signature=default boolean isConceptDocuments(), anchor=ConceptDocumentIterator_isConceptDocuments_, args=[], description=[Checks if the query answer is a ``ConceptDocumentIterator``. 
], examples=[concept.isConceptDocuments();], mode=null, returnDescription=null, returnType=boolean), Method(name=asConceptDocuments, signature=@CheckReturnValue
default ConceptDocumentIterator asConceptDocuments(), anchor=ConceptDocumentIterator_asConceptDocuments_, args=[], description=[Casts the query answer to ``ConceptDocumentIterator``. 
], examples=[concept.asConceptDocuments();], mode=null, returnDescription=null, returnType=ConceptDocumentIterator), Method(name=stream, signature=@CheckReturnValue
java.util.stream.Stream<JSON> stream(), anchor=ConceptDocumentIterator_stream_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=java.util.stream.Stream<JSON>)], packagePath=com.typedb.driver.api.answer, superClasses=[java.util.Iterator<JSON>, QueryAnswer], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.answer`

*Superinterfaces:*

* `java.util.Iterator<JSON>`
* `QueryAnswer`

Represents an iterator over concept documents (represented as ``JSON``s) returned as a server answer.

// tag::methods[]
[#_ConceptDocumentIterator_asConceptDocuments_]
==== asConceptDocuments

[source,java]
----
@CheckReturnValue
default ConceptDocumentIterator asConceptDocuments()
----

Casts the query answer to ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`ConceptDocumentIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptDocuments();
----

[#_ConceptDocumentIterator_isConceptDocuments_]
==== isConceptDocuments

[source,java]
----
default boolean isConceptDocuments()
----

Checks if the query answer is a ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptDocuments();
----

[#_ConceptDocumentIterator_stream_]
==== stream

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<JSON> stream()
----



[caption=""]
.Returns
`java.util.stream.Stream<JSON>`

// end::methods[]

