[#_JSON]
=== JSON

`Class(name=JSON, anchor=JSON, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=JSON, signature=public JSON(), anchor=JSON_JSON_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public), Method(name=parse, signature=public static JSON parse​(java.lang.String string), anchor=JSON_parse_java_lang_String, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public static JSON), Method(name=isObject, signature=public boolean isObject(), anchor=JSON_isObject_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isArray, signature=public boolean isArray(), anchor=JSON_isArray_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isNumber, signature=public boolean isNumber(), anchor=JSON_isNumber_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isString, signature=public boolean isString(), anchor=JSON_isString_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=isBoolean, signature=public boolean isBoolean(), anchor=JSON_isBoolean_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean), Method(name=asObject, signature=public java.util.Map<java.lang.String,​JSON> asObject(), anchor=JSON_asObject_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public java.util.Map<java.lang.String,​JSON>), Method(name=asArray, signature=public java.util.List<JSON> asArray(), anchor=JSON_asArray_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public java.util.List<JSON>), Method(name=asNumber, signature=public double asNumber(), anchor=JSON_asNumber_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public double), Method(name=asString, signature=public java.lang.String asString(), anchor=JSON_asString_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public java.lang.String), Method(name=asBoolean, signature=public boolean asBoolean(), anchor=JSON_asBoolean_, args=[], description=[], examples=[], mode=null, returnDescription=null, returnType=public boolean)], packagePath=com.typedb.driver.api.answer, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.answer`

// tag::methods[]
[#_JSON_JSON_]
==== JSON

[source,java]
----
public JSON()
----



[caption=""]
.Returns
`public`

[#_JSON_asArray_]
==== asArray

[source,java]
----
public java.util.List<JSON> asArray()
----



[caption=""]
.Returns
`public java.util.List<JSON>`

[#_JSON_asBoolean_]
==== asBoolean

[source,java]
----
public boolean asBoolean()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_asNumber_]
==== asNumber

[source,java]
----
public double asNumber()
----



[caption=""]
.Returns
`public double`

[#_JSON_asObject_]
==== asObject

[source,java]
----
public java.util.Map<java.lang.String,​JSON> asObject()
----



[caption=""]
.Returns
`public java.util.Map<java.lang.String,​JSON>`

[#_JSON_asString_]
==== asString

[source,java]
----
public java.lang.String asString()
----



[caption=""]
.Returns
`public java.lang.String`

[#_JSON_isArray_]
==== isArray

[source,java]
----
public boolean isArray()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_isBoolean_]
==== isBoolean

[source,java]
----
public boolean isBoolean()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_isNumber_]
==== isNumber

[source,java]
----
public boolean isNumber()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_isObject_]
==== isObject

[source,java]
----
public boolean isObject()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_isString_]
==== isString

[source,java]
----
public boolean isString()
----



[caption=""]
.Returns
`public boolean`

[#_JSON_parse_java_lang_String]
==== parse

[source,java]
----
public static JSON parse​(java.lang.String string)
----



[caption=""]
.Returns
`public static JSON`

// end::methods[]

