[#_OkQueryAnswer]
[.doc-api-reference-driver]
=== OkQueryAnswer

`class`

*Package*: `com.typedb.driver.api.answer`

*Superinterfaces:*

* `QueryAnswer`

Represents a simple Ok message as a server answer. Doesn't contain concepts.

// tag::methods[]
[#_OkQueryAnswer_asConceptDocuments_]
==== method ``asConceptDocuments``

[source,java]
----
default ConceptDocumentIterator asConceptDocuments()
----

Casts the query answer to ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`ConceptDocumentIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptDocuments();
----

[#_OkQueryAnswer_asConceptRows_]
==== method ``asConceptRows``

[source,java]
----
default ConceptRowIterator asConceptRows()
----

Casts the query answer to ``ConceptRowIterator``. 


[caption=""]
.Returns
`ConceptRowIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptRows();
----

[#_OkQueryAnswer_asOk_]
==== method ``asOk``

[source,java]
----
@CheckReturnValue
default OkQueryAnswer asOk()
----

Casts the query answer to ``OkQueryAnswer``. 


[caption=""]
.Returns
`OkQueryAnswer`

[caption=""]
.Code examples
[source,java]
----
concept.asOk();
----

[#_OkQueryAnswer_getQueryType_]
==== method ``getQueryType``

[source,java]
----
@CheckReturnValue
QueryType getQueryType()
----

Retrieves the executed query's type of this ``QueryAnswer``. 


[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,java]
----
queryAnswer.getQueryType();
----

[#_OkQueryAnswer_isConceptDocuments_]
==== method ``isConceptDocuments``

[source,java]
----
@CheckReturnValue
default boolean isConceptDocuments()
----

Checks if the query answer is a ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptDocuments();
----

[#_OkQueryAnswer_isConceptRows_]
==== method ``isConceptRows``

[source,java]
----
@CheckReturnValue
default boolean isConceptRows()
----

Checks if the query answer is a ``ConceptRowIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptRows();
----

[#_OkQueryAnswer_isOk_]
==== method ``isOk``

[source,java]
----
default boolean isOk()
----

Checks if the query answer is an ``Ok``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isOk();
----

// end::methods[]

