[#_Promise_T]
=== Promise<T>

*Package*: `com.vaticle.typedb.driver.common`

A ``Promise`` represents an asynchronous network operation.

The request it represents is performed immediately. The response is only retrieved once the ``Promise`` is ``resolve``d.

// tag::methods[]
[#_Promise_T_Promise__java_util_function_Supplier_T_]
==== Promise

[source,java]
----
public Promise​(java.util.function.Supplier<T> inner)
----

Promise constructor 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `inner` a| The supplier to function to wrap into the promise a| `java.util.function.Supplier<T>`
|===

[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
new Promise(supplier)
----

[#_Promise_T_map__java_util_function_Supplier_T___java_util_function_Function_T_​U_]
==== map

[source,java]
----
public static <T,​U> Promise<U> map​(java.util.function.Supplier<T> promise,
                                         java.util.function.Function<T,​U> fn)
----

Helper function to map promises. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `promise` a| The supplier function to wrap into the promise a| `java.util.function.Supplier<T>`
a| `fn` a| The mapping function a| `java.util.function.Function<T,​U>`
|===

[caption=""]
.Returns
`public static <T,​U> Promise<U>`

[caption=""]
.Code examples
[source,java]
----
Promise.map(supplier, mapper);
----

[#_Promise_T_resolve__]
==== resolve

[source,java]
----
public T resolve()
----

Retrieves the result of the Promise. 


[caption=""]
.Returns
`public T`

[caption=""]
.Code examples
[source,java]
----
promise.resolve()
----

// end::methods[]

