[#_QueryType]
=== QueryType

`class`

*Package*: `com.typedb.driver.api`

Used to specify the type of the executed query. 


[caption=""]
.Examples
[source,java]
----
conceptRow.queryType();
----

[caption=""]
.Enum constants
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `READ`
a| `SCHEMA`
a| `WRITE`
|===
// end::enum_constants[]

// tag::methods[]
[#_QueryType_id_]
==== id

[source,java]
----
public int id()
----



[caption=""]
.Returns
`public int`

[#_QueryType_isRead_]
==== isRead

[source,java]
----
public boolean isRead()
----



[caption=""]
.Returns
`public boolean`

[#_QueryType_isSchema_]
==== isSchema

[source,java]
----
public boolean isSchema()
----



[caption=""]
.Returns
`public boolean`

[#_QueryType_isWrite_]
==== isWrite

[source,java]
----
public boolean isWrite()
----



[caption=""]
.Returns
`public boolean`

[#_QueryType_of_com_typedb_driver_jni_QueryType]
==== of

[source,java]
----
public static QueryType of​(com.typedb.driver.jni.QueryType nativeType)
----



[caption=""]
.Returns
`public static QueryType`

[#_QueryType_valueOf_java_lang_String]
==== valueOf

[source,java]
----
public static QueryType valueOf​(java.lang.String name)
----

Returns the enum constant of this type with the specified name. The string must match exactly an identifier used to declare an enum constant in this type. (Extraneous whitespace characters are not permitted.)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| the name of the enum constant to be returned. a| `java.lang.String`
|===

[caption=""]
.Returns
`public static QueryType`

[#_QueryType_values_]
==== values

[source,java]
----
public static QueryType[] values()
----

Returns an array containing the constants of this enum type, in the order they are declared. This method may be used to iterate over the constants as follows: 
[source,java]
----
for (QueryType c : QueryType.values())
    System.out.println(c);

----


[caption=""]
.Returns
`public static QueryType[]`

[caption=""]
.Code examples
[source,java]
----
for (QueryType c : QueryType.values())
    System.out.println(c);
----

// end::methods[]

