[#_QueryAnswer]
=== QueryAnswer

`Class(name=QueryAnswer, anchor=QueryAnswer, enumConstants=[], description=[General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.], examples=[], fields=[], methods=[Method(name=getQueryType, signature=@CheckReturnValue
QueryType getQueryType(), anchor=QueryAnswer_getQueryType_, args=[], description=[Retrieves the executed query's type of this ``QueryAnswer``. 
], examples=[queryAnswer.getQueryType();], mode=null, returnDescription=null, returnType=QueryType), Method(name=isOk, signature=@CheckReturnValue
default boolean isOk(), anchor=QueryAnswer_isOk_, args=[], description=[Checks if the query answer is an ``Ok``. 
], examples=[concept.isOk();], mode=null, returnDescription=null, returnType=boolean), Method(name=isConceptRows, signature=@CheckReturnValue
default boolean isConceptRows(), anchor=QueryAnswer_isConceptRows_, args=[], description=[Checks if the query answer is a ``ConceptRowIterator``. 
], examples=[concept.isConceptRows();], mode=null, returnDescription=null, returnType=boolean), Method(name=isConceptDocuments, signature=@CheckReturnValue
default boolean isConceptDocuments(), anchor=QueryAnswer_isConceptDocuments_, args=[], description=[Checks if the query answer is a ``ConceptDocumentIterator``. 
], examples=[concept.isConceptDocuments();], mode=null, returnDescription=null, returnType=boolean), Method(name=asOk, signature=default OkQueryAnswer asOk(), anchor=QueryAnswer_asOk_, args=[], description=[Casts the query answer to ``OkQueryAnswer``. 
], examples=[concept.asOk();], mode=null, returnDescription=null, returnType=OkQueryAnswer), Method(name=asConceptRows, signature=default ConceptRowIterator asConceptRows(), anchor=QueryAnswer_asConceptRows_, args=[], description=[Casts the query answer to ``ConceptRowIterator``. 
], examples=[concept.asConceptRows();], mode=null, returnDescription=null, returnType=ConceptRowIterator), Method(name=asConceptDocuments, signature=default ConceptDocumentIterator asConceptDocuments(), anchor=QueryAnswer_asConceptDocuments_, args=[], description=[Casts the query answer to ``ConceptDocumentIterator``. 
], examples=[concept.asConceptDocuments();], mode=null, returnDescription=null, returnType=ConceptDocumentIterator)], packagePath=com.typedb.driver.api.answer, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.answer`

General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.

// tag::methods[]
[#_QueryAnswer_asConceptDocuments_]
==== asConceptDocuments

[source,java]
----
default ConceptDocumentIterator asConceptDocuments()
----

Casts the query answer to ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`ConceptDocumentIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptDocuments();
----

[#_QueryAnswer_asConceptRows_]
==== asConceptRows

[source,java]
----
default ConceptRowIterator asConceptRows()
----

Casts the query answer to ``ConceptRowIterator``. 


[caption=""]
.Returns
`ConceptRowIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptRows();
----

[#_QueryAnswer_asOk_]
==== asOk

[source,java]
----
default OkQueryAnswer asOk()
----

Casts the query answer to ``OkQueryAnswer``. 


[caption=""]
.Returns
`OkQueryAnswer`

[caption=""]
.Code examples
[source,java]
----
concept.asOk();
----

[#_QueryAnswer_getQueryType_]
==== getQueryType

[source,java]
----
@CheckReturnValue
QueryType getQueryType()
----

Retrieves the executed query's type of this ``QueryAnswer``. 


[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,java]
----
queryAnswer.getQueryType();
----

[#_QueryAnswer_isConceptDocuments_]
==== isConceptDocuments

[source,java]
----
@CheckReturnValue
default boolean isConceptDocuments()
----

Checks if the query answer is a ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptDocuments();
----

[#_QueryAnswer_isConceptRows_]
==== isConceptRows

[source,java]
----
@CheckReturnValue
default boolean isConceptRows()
----

Checks if the query answer is a ``ConceptRowIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptRows();
----

[#_QueryAnswer_isOk_]
==== isOk

[source,java]
----
@CheckReturnValue
default boolean isOk()
----

Checks if the query answer is an ``Ok``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isOk();
----

// end::methods[]

