[#_QueryAnswer]
=== QueryAnswer

`class`

*Package*: `com.typedb.driver.api.answer`

General answer on a query returned by a server. Can be a simple Ok response or a collection of concepts.

// tag::methods[]
[#_QueryAnswer_asConceptDocuments_]
==== asConceptDocuments()

[source,java]
----
default ConceptDocumentIterator asConceptDocuments()
----

Casts the query answer to ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`ConceptDocumentIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptDocuments();
----

[#_QueryAnswer_asConceptRows_]
==== asConceptRows()

[source,java]
----
default ConceptRowIterator asConceptRows()
----

Casts the query answer to ``ConceptRowIterator``. 


[caption=""]
.Returns
`ConceptRowIterator`

[caption=""]
.Code examples
[source,java]
----
concept.asConceptRows();
----

[#_QueryAnswer_asOk_]
==== asOk()

[source,java]
----
default OkQueryAnswer asOk()
----

Casts the query answer to ``OkQueryAnswer``. 


[caption=""]
.Returns
`OkQueryAnswer`

[caption=""]
.Code examples
[source,java]
----
concept.asOk();
----

[#_QueryAnswer_getQueryType_]
==== getQueryType()

[source,java]
----
@CheckReturnValue
QueryType getQueryType()
----

Retrieves the executed query's type of this ``QueryAnswer``. 


[caption=""]
.Returns
`QueryType`

[caption=""]
.Code examples
[source,java]
----
queryAnswer.getQueryType();
----

[#_QueryAnswer_isConceptDocuments_]
==== isConceptDocuments()

[source,java]
----
@CheckReturnValue
default boolean isConceptDocuments()
----

Checks if the query answer is a ``ConceptDocumentIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptDocuments();
----

[#_QueryAnswer_isConceptRows_]
==== isConceptRows()

[source,java]
----
@CheckReturnValue
default boolean isConceptRows()
----

Checks if the query answer is a ``ConceptRowIterator``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isConceptRows();
----

[#_QueryAnswer_isOk_]
==== isOk()

[source,java]
----
@CheckReturnValue
default boolean isOk()
----

Checks if the query answer is an ``Ok``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isOk();
----

// end::methods[]

