[#_trait_RuleAPI]
=== Trait RuleAPI

*Implementors:*

* `Rule`

[tabs]
====
Trait RuleAPI async examples::
+
--
[source,rust]
----
rule.delete(transaction).await
----

, [source,rust]
----
rule.set_label(transaction, new_label).await
----

, [source,rust]
----
rule.is_deleted(transaction).await
----

--

Trait RuleAPI sync examples::
+
--
[source,rust]
----
rule.delete(transaction).resolve()
----

, [source,rust]
----
rule.set_label(transaction, new_label).resolve()
----

, [source,rust]
----
rule.is_deleted(transaction).resolve()
----

--
====

// tag::methods[]
[#_trait_RuleAPI_delete__transaction_&'tx_Transaction_'tx_]
==== delete

[source,rust]
----
fn delete<'tx>(
    &mut self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result>
----

Deletes this rule.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.delete(transaction).await
----

--

sync::
+
--
[source,rust]
----
rule.delete(transaction).resolve()
----

--
====

[#_trait_RuleAPI_is_deleted__transaction_&'tx_Transaction_'tx_]
==== is_deleted

[source,rust]
----
fn is_deleted<'tx>(
    &self,
    transaction: &'tx Transaction<'tx>
) -> BoxPromise<'tx, Result<bool>>
----

Check if this rule has been deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'tx Transaction<'tx>`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result<bool>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.is_deleted(transaction).await
----

--

sync::
+
--
[source,rust]
----
rule.is_deleted(transaction).resolve()
----

--
====

[#_trait_RuleAPI_label__]
==== label

[source,rust]
----
fn label(&self) -> &String
----

Retrieves the unique label of the rule.

[caption=""]
.Returns
[source,rust]
----
&String
----

[#_trait_RuleAPI_set_label__transaction_&'tx_Transaction_'tx___new_label_String]
==== set_label

[source,rust]
----
fn set_label<'tx>(
    &mut self,
    transaction: &'tx Transaction<'tx>,
    new_label: String
) -> BoxPromise<'tx, Result>
----

Renames the label of the rule. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'tx Transaction<'tx>`
a| `new_label` a| The new label to be given to the rule a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
BoxPromise<'tx, Result>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.set_label(transaction, new_label).await
----

--

sync::
+
--
[source,rust]
----
rule.set_label(transaction, new_label).resolve()
----

--
====

// end::methods[]

