[#_trait_RuleAPI]
=== Trait RuleAPI

*Implementors:*

* `Rule`

// tag::methods[]
[#_trait_RuleAPI_tymethod_delete]
==== delete

[tabs]
====
async::
+
--
[source,rust]
----
fn delete<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 mut self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn delete(&mut self, transaction: &Transaction<'_>) -> Result
----

--
====

Deletes this rule.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&Transaction<'_>`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.delete(transaction).await;
----

--

sync::
+
--
[source,rust]
----
rule.delete(transaction);
----

--
====

[#_trait_RuleAPI_method_is_deleted]
==== is_deleted

[tabs]
====
async::
+
--
[source,rust]
----
fn is_deleted<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 self,
    transaction: &'life1 Transaction<'life2>
) -> Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn is_deleted(&self, transaction: &Transaction<'_>) -> Result<bool>
----

--
====

Check if this rule has been deleted.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&Transaction<'_>`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result<bool>> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result<bool>
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.is_deleted(transaction).await
----

--

sync::
+
--
[source,rust]
----
rule.is_deleted(transaction)
----

--
====

[#_trait_RuleAPI_tymethod_label]
==== label

[source,rust]
----
fn label(&self) -> &String
----

Retrieves the unique label of the rule.

[caption=""]
.Returns
[source,rust]
----
&String
----

[#_trait_RuleAPI_tymethod_set_label]
==== set_label

[tabs]
====
async::
+
--
[source,rust]
----
fn set_label<'life0, 'life1, 'life2, 'async_trait>(
    &'life0 mut self,
    transaction: &'life1 Transaction<'life2>,
    new_label: String
) -> Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
fn set_label(
    &mut self,
    transaction: &Transaction<'_>,
    new_label: String
) -> Result
----

--
====

Renames the label of the rule. The new label must remain unique.

[caption=""]
.Input parameters
[tabs]
====
async::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&'life1 Transaction<'life2>`
a| `new_label` a| The new label to be given to the rule a| `String`
|===
--

sync::
+
--
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `&Transaction<'_>`
a| `new_label` a| The new label to be given to the rule a| `String`
|===
--
====


[caption=""]
.Returns
[tabs]
====
async::
+
--
[source,rust]
----
Pin<Box<dyn Future<Output = Result> + Send + 'async_trait>>
where
     Self: 'async_trait,
     'life0: 'async_trait,
     'life1: 'async_trait,
     'life2: 'async_trait,
----

--

sync::
+
--
[source,rust]
----
Result
----

--
====

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
rule.set_label(transaction, new_label).await;
----

--

sync::
+
--
[source,rust]
----
rule.set_label(transaction, new_label);
----

--
====

// end::methods[]

