
[#_connection_header]
== Connection

{page-version}@api-ref::partial$cpp/connection/Driver.adoc[]

{page-version}@api-ref::partial$cpp/connection/Credential.adoc[]

{page-version}@api-ref::partial$cpp/connection/DatabaseManager.adoc[]

{page-version}@api-ref::partial$cpp/connection/Database.adoc[]

{page-version}@api-ref::partial$cpp/connection/ReplicaInfo.adoc[]

{page-version}@api-ref::partial$cpp/connection/UserManager.adoc[]

{page-version}@api-ref::partial$cpp/connection/User.adoc[]

[#_session_header]
== Session

{page-version}@api-ref::partial$cpp/session/Session.adoc[]

{page-version}@api-ref::partial$cpp/session/SessionType.adoc[]

{page-version}@api-ref::partial$cpp/session/Options.adoc[]

[#_transaction_header]
== Transaction

{page-version}@api-ref::partial$cpp/transaction/Transaction.adoc[]

{page-version}@api-ref::partial$cpp/transaction/TransactionType.adoc[]

{page-version}@api-ref::partial$cpp/transaction/QueryManager.adoc[]

[#_answer_header]
== Answer

{page-version}@api-ref::partial$cpp/answer/ConceptMapGroup.adoc[]

{page-version}@api-ref::partial$cpp/answer/ConceptMap.adoc[]

{page-version}@api-ref::partial$cpp/answer/ValueGroup.adoc[]

{page-version}@api-ref::partial$cpp/answer/JSON.adoc[]

{page-version}@api-ref::partial$cpp/answer/JSONType.adoc[]

{page-version}@api-ref::partial$cpp/answer/OwnerAttributePair.adoc[]

{page-version}@api-ref::partial$cpp/answer/Explainables.adoc[]

{page-version}@api-ref::partial$cpp/answer/Explainable.adoc[]

{page-version}@api-ref::partial$cpp/answer/Explanation.adoc[]

{page-version}@api-ref::partial$cpp/answer/Future.adoc[]

{page-version}@api-ref::partial$cpp/answer/Iterable.adoc[]

{page-version}@api-ref::partial$cpp/answer/Iterator.adoc[]

{page-version}@api-ref::partial$cpp/answer/typedefs.adoc[]

[#_concept_header]
== Concept

{page-version}@api-ref::partial$cpp/concept/ConceptManager.adoc[]

{page-version}@api-ref::partial$cpp/concept/Concept.adoc[]

{page-version}@api-ref::partial$cpp/concept/ConceptType.adoc[]

{page-version}@api-ref::partial$cpp/concept/Transitivity.adoc[]

[#_schema_header]
== Schema

{page-version}@api-ref::partial$cpp/schema/Type.adoc[]

{page-version}@api-ref::partial$cpp/schema/ThingType.adoc[]

{page-version}@api-ref::partial$cpp/schema/EntityType.adoc[]

{page-version}@api-ref::partial$cpp/schema/RelationType.adoc[]

{page-version}@api-ref::partial$cpp/schema/RoleType.adoc[]

{page-version}@api-ref::partial$cpp/schema/AttributeType.adoc[]

{page-version}@api-ref::partial$cpp/schema/Annotation.adoc[]

//{page-version}@api-ref::partial$cpp/schema/Transitivity.adoc[]

{page-version}@api-ref::partial$cpp/schema/ValueType.adoc[]

//{page-version}@api-ref::partial$cpp/schema/ScopedLabel.adoc[]

[#_data_header]
== Data

{page-version}@api-ref::partial$cpp/data/Thing.adoc[]

{page-version}@api-ref::partial$cpp/data/Entity.adoc[]

{page-version}@api-ref::partial$cpp/data/Relation.adoc[]

{page-version}@api-ref::partial$cpp/data/Attribute.adoc[]

{page-version}@api-ref::partial$cpp/data/Value.adoc[]

[#_logic_header]
== Logic

{page-version}@api-ref::partial$cpp/logic/LogicManager.adoc[]

{page-version}@api-ref::partial$cpp/logic/Rule.adoc[]

[#_errors_header]
== Errors

{page-version}@api-ref::partial$cpp/errors/DriverException.adoc[]
