# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Keys are suffixes of the fully qualified class name. The longest match is picked.
# The filename will be className.adoc
dir_mapping = {
    "AnalyzedQuery.adoc": "Analyze APIs",
    "Comparator.adoc": "Analyze APIs",
    "Conjunction.adoc": "Analyze APIs",
    "ConstraintExactness.adoc": "Analyze APIs",
    "ConstraintVariant.adoc": "Analyze APIs",
    "Constraint.adoc": "Analyze APIs",
    "Isa.adoc": "Analyze APIs",
    "Has.adoc": "Analyze APIs",
    "Links.adoc": "Analyze APIs",
    "Sub.adoc": "Analyze APIs",
    "Owns.adoc": "Analyze APIs",
    "Relates.adoc": "Analyze APIs",
    "Plays.adoc": "Analyze APIs",
    "FunctionCall.adoc": "Analyze APIs",
    "Expression.adoc": "Analyze APIs",
    "Is.adoc": "Analyze APIs",
    "Iid.adoc": "Analyze APIs",
    "Comparison.adoc": "Analyze APIs",
    "Kind.adoc": "Analyze APIs",
    "Label.adoc": "Analyze APIs",
    "analyze.constraint.Value.adoc": "Analyze APIs", # Longer suffix match to avoid ambiguity with the Value concept
    "Or.adoc": "Analyze APIs",
    "Not.adoc": "Analyze APIs",
    "Try.adoc": "Analyze APIs",
    "Span.adoc": "Analyze APIs",
    "ConstraintVertex.adoc": "Analyze APIs",
    "NamedRole.adoc": "Analyze APIs",
    "Fetch.adoc": "Analyze APIs",
    "FetchVariant.adoc": "Analyze APIs",
    "FetchObject.adoc": "Analyze APIs",
    "FetchList.adoc": "Analyze APIs",
    "FetchLeaf.adoc": "Analyze APIs",
    "Function.adoc": "Analyze APIs",
    "KindVariant.adoc": "Analyze APIs",
    "ReturnOperation.adoc": "Analyze APIs",
    "ReturnOperationVariant.adoc": "Analyze APIs",
    "ReturnOperationStream.adoc": "Analyze APIs",
    "ReturnOperationSingle.adoc": "Analyze APIs",
    "ReturnOperationCheck.adoc": "Analyze APIs",
    "ReturnOperationReduce.adoc": "Analyze APIs",
    "ReturnOperation.Reduce.ReduceAssignment.adoc": "Analyze APIs",
    "Pipeline.adoc": "Analyze APIs",
    "PipelineStage.adoc": "Analyze APIs",
    "PipelineStageVariant.adoc": "Analyze APIs",
    "MatchStage.adoc": "Analyze APIs",
    "InsertStage.adoc": "Analyze APIs",
    "PutStage.adoc": "Analyze APIs",
    "UpdateStage.adoc": "Analyze APIs",
    "DeleteStage.adoc": "Analyze APIs",
    "SelectStage.adoc": "Analyze APIs",
    "SortStage.adoc": "Analyze APIs",
    "RequireStage.adoc": "Analyze APIs",
    "OffsetStage.adoc": "Analyze APIs",
    "LimitStage.adoc": "Analyze APIs",
    "DistinctStage.adoc": "Analyze APIs",
    "ReduceStage.adoc": "Analyze APIs",
    "SortStage.SortVariable.adoc": "Analyze APIs",
    "ReduceStage.ReduceAssignment.adoc": "Analyze APIs",
    "ReduceAssignment.adoc": "Analyze APIs",
    "Reducer.adoc": "Analyze APIs",
    "SortOrder.adoc": "Analyze APIs",
    "SortOrderVariant.adoc": "Analyze APIs",
    "SortVariable.adoc": "Analyze APIs",
    "TypeAnnotations.adoc": "Analyze APIs",
    "VariableAnnotationsVariant.adoc": "Analyze APIs",
    "VariableAnnotations.adoc": "Analyze APIs",

    "TransactionType.adoc": "Transaction APIs",
    "Transaction.adoc": "Transaction APIs",
    "TransactionOptions.adoc": "Transaction APIs",
    "QueryOptions.adoc": "Transaction APIs",
    "QueryAnswer.adoc": "Answer APIs",
    "QueryType.adoc": "Answer APIs",
    "OkQueryAnswer.adoc": "Answer APIs",
    "ConceptRow.adoc": "Answer APIs",
    "ConceptRowIterator.adoc": "Answer APIs",
    "ConceptDocument.adoc": "Answer APIs",
    "ConceptDocumentIterator.adoc": "Answer APIs",
    "ValueGroup.adoc": "Answer APIs",
    "Promise.adoc": "Answer APIs",
    "Concept.adoc": "Concept APIs",
    "TypeDB.adoc": "connection APIs",
    "DriverOptions.adoc": "Connection APIs",
    "Credentials.adoc": "Connection APIs",
    "Driver.adoc": "Connection APIs",
    "User.adoc": "Connection APIs",
    "UserManager.adoc": "Connection APIs",
#    "Replica.adoc": "Connection APIs",
    "Database.adoc": "Connection APIs",
    "DatabaseManager.adoc": "Connection APIs",
    "Relation.adoc": "Data APIs",
    "Entity.adoc": "Data APIs",
    "Attribute.adoc": "Data APIs",
    "Instance.adoc": "Data APIs",
    "Value.adoc": "Data APIs",
    "AttributeType.adoc": "Schema APIs",
    "EntityType.adoc": "Schema APIs",
    "RelationType.adoc": "Schema APIs",
    "RoleType.adoc": "Schema APIs",
    "Type.adoc": "Schema APIs",
    "Datetime.adoc": "Value APIs",
    "Duration.adoc": "Value APIs",
    "TypeDBDriverException.adoc": "Error APIs",
}
