[#_ConceptMap]
=== ConceptMap

Contains a mapping of variables to concepts.

// tag::methods[]
[#_ConceptMap_concepts__]
==== concepts

[source,python]
----
concepts() -> Iterator[Concept]
----

Produces an iterator over all concepts in this ``ConceptMap``.

[caption=""]
.Returns
`Iterator[Concept]`

[caption=""]
.Code examples
[source,python]
----
concept_map.concepts()
----

[#_ConceptMap_explainables__]
==== explainables

[source,python]
----
explainables() -> Explainables
----

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable.

[caption=""]
.Returns
`Explainables`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables()
----

[#_ConceptMap_get__variable_str]
==== get

[source,python]
----
get(variable: str) -> Concept
----

Retrieves a concept for a given variable name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,python]
----
concept_map.get(variable)
----

[#_ConceptMap_map__]
==== map

[source,python]
----
map() -> Mapping[str, Concept]
----

Returns the inner ``Mapping`` where keys are query variables, and values are concepts.

[caption=""]
.Returns
`Mapping[str, Concept]`

[caption=""]
.Code examples
[source,python]
----
concept_map.concepts()
----

[#_ConceptMap_variables__]
==== variables

[source,python]
----
variables() -> Iterator[str]
----

Produces an iterator over all variables in this ``ConceptMap``.

[caption=""]
.Returns
`Iterator[str]`

[caption=""]
.Code examples
[source,python]
----
concept_map.variables()
----

// end::methods[]

