[#_Explainables]
=== Explainables

Contains explainable objects.

// tag::methods[]
[#_Explainables_attribute__variable_str]
==== attribute

[source,python]
----
attribute(variable: str) -> Explainable
----

Retrieves the explainable attribute with the given variable name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().attribute(variable)
----

[#_Explainables_attributes__]
==== attributes

[source,python]
----
attributes() -> Mapping[str, Explainable]
----

Retrieves all of this ``ConceptMap``’s explainable attributes.

[caption=""]
.Returns
`Mapping[str, Explainable]`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().attributes()
----

[#_Explainables_ownership__owner_str__attribute_str]
==== ownership

[source,python]
----
ownership(owner: str, attribute: str) -> Explainable
----

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `owner` a| The string representation of the owner variable a| `str` a| 
a| `attribute` a| The string representation of the attribute variable a| `str` a| 
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().ownership(owner, attribute)
----

[#_Explainables_ownerships__]
==== ownerships

[source,python]
----
ownerships() -> Mapping[tuple[str, str], Explainable]
----

Retrieves all of this ``ConceptMap``’s explainable ownerships.

[caption=""]
.Returns
`Mapping[tuple[str, str], Explainable]`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().ownerships()
----

[#_Explainables_relation__variable_str]
==== relation

[source,python]
----
relation(variable: str) -> Explainable
----

Retrieves the explainable relation with the given variable name.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `variable` a| The string representation of a variable a| `str` a| 
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().relation(variable)
----

[#_Explainables_relations__]
==== relations

[source,python]
----
relations() -> Mapping[str, Explainable]
----

Retrieves all of this ``ConceptMap``’s explainable relations.

[caption=""]
.Returns
`Mapping[str, Explainable]`

[caption=""]
.Code examples
[source,python]
----
concept_map.explainables().relations()
----

// end::methods[]

