[#_Explanation]
=== Explanation

An explanation of which rule was used for inferring the explained concept, the condition of the rule, the conclusion of the rule, and the mapping of variables between the query and the rule’s conclusion.

// tag::methods[]
[#_Explanation_conclusion__]
==== conclusion

[source,python]
----
conclusion() -> ConceptMap
----

Retrieves the Conclusion for this Explanation.

[caption=""]
.Returns
`ConceptMap`

[caption=""]
.Code examples
[source,python]
----
explanation.conclusion()
----

[#_Explanation_condition__]
==== condition

[source,python]
----
condition() -> ConceptMap
----

Retrieves the Condition for this Explanation.

[caption=""]
.Returns
`ConceptMap`

[caption=""]
.Code examples
[source,python]
----
explanation.condition()
----

[#_Explanation_query_variable_mapping__var_str]
==== query_variable_mapping

[source,python]
----
query_variable_mapping(var: str) -> set[str]
----

Retrieves the rule variables corresponding to the query variable var for this ``Explanation``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `var` a| The query variable to map to rule variables. a| `str` a| 
|===

[caption=""]
.Returns
`set[str]`

[caption=""]
.Code examples
[source,python]
----
explanation.variable_mapping(var)
----

[#_Explanation_query_variables__]
==== query_variables

[source,python]
----
query_variables() -> set[str]
----

Retrieves the query variables for this ``Explanation``.

[caption=""]
.Returns
`set[str]`

[caption=""]
.Code examples
[source,python]
----
explanation.query_variables()
----

[#_Explanation_rule__]
==== rule

[source,python]
----
rule() -> Rule
----

Retrieves the Rule for this Explanation.

[caption=""]
.Returns
`Rule`

[caption=""]
.Code examples
[source,python]
----
explanation.rule()
----

// end::methods[]

