[#_IAttribute]
[.doc-api-reference-driver]
=== IAttribute

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IInstance`
* `TypeDB.Driver.Api.IConcept`



Represents an attribute instance in TypeDB. Attribute instances represent properties with values that can be owned by other instances. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IAttribute_IConcept_TypeDB_Driver_Api_IAttribute_AsAttribute_]
==== method ``AsAttribute``

[source,cs]
----
IAttribute IConcept. AsAttribute()
----



Casts the concept to IAttribute.



Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IAttribute IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.AsAttribute()
----

[#_bool_IConcept_TypeDB_Driver_Api_IAttribute_IsAttribute_]
==== method ``IsAttribute``

[source,cs]
----
bool IConcept. IsAttribute()
----



Checks if the concept is an IAttribute.



Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.IsAttribute()
----

[#_new_IAttributeType_TypeDB_Driver_Api_IAttribute_Type]
==== method ``Type [1/2]``

[source,cs]
----
new IAttributeType TypeDB.Driver.Api.IAttribute.Type
----



The attribute type which this attribute instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`new IAttributeType`

[#_IType_IInstance_TypeDB_Driver_Api_IAttribute_Type]
==== method ``Type [2/2]``

[source,cs]
----
IType IInstance. TypeDB.Driver.Api.IAttribute.Type
----



The type which this instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`IType IInstance.`

// end::methods[]

