[#_IAttribute]
[.doc-api-reference-driver]
=== IAttribute

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type. Attributes can be uniquely addressed by their type and value. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IAttribute_IConcept_TypeDB_Driver_Api_IAttribute_AsAttribute_]
==== method ``AsAttribute``

[source,cs]
----
IAttribute IConcept. AsAttribute()
----



Casts the concept to IAttribute.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an attribute.
    
   
  
 


 
  concept.AsAttribute()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IAttribute IConcept.`

[#_bool_TypeDB_Driver_Api_IAttribute_GetBoolean_]
==== method ``GetBoolean``

[source,cs]
----
bool GetBoolean()
----



Returns a boolean value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[#_DateOnly_TypeDB_Driver_Api_IAttribute_GetDate_]
==== method ``GetDate``

[source,cs]
----
DateOnly GetDate()
----



Returns a date value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`DateOnly`

[#_Datetime_TypeDB_Driver_Api_IAttribute_GetDatetime_]
==== method ``GetDatetime``

[source,cs]
----
Datetime GetDatetime()
----



Returns a datetime value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[#_DatetimeTZ_TypeDB_Driver_Api_IAttribute_GetDatetimeTZ_]
==== method ``GetDatetimeTZ``

[source,cs]
----
DatetimeTZ GetDatetimeTZ()
----



Returns a datetime with timezone value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`DatetimeTZ`

[#_decimal_TypeDB_Driver_Api_IAttribute_GetDecimal_]
==== method ``GetDecimal``

[source,cs]
----
decimal GetDecimal()
----



Returns a decimal value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`decimal`

[#_double_TypeDB_Driver_Api_IAttribute_GetDouble_]
==== method ``GetDouble``

[source,cs]
----
double GetDouble()
----



Returns a double value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`double`

[#_Duration_TypeDB_Driver_Api_IAttribute_GetDuration_]
==== method ``GetDuration``

[source,cs]
----
Duration GetDuration()
----



Returns a duration value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[#_long_TypeDB_Driver_Api_IAttribute_GetInteger_]
==== method ``GetInteger``

[source,cs]
----
long GetInteger()
----



Returns an integer (long) value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`long`

[#_string_TypeDB_Driver_Api_IAttribute_GetString_]
==== method ``GetString``

[source,cs]
----
string GetString()
----



Returns a string value of the value concept that this attribute holds. If the value has another type, raises an exception.

[caption=""]
.Returns
`string`

[#_IReadOnlyDictionary_string_IValue_TypeDB_Driver_Api_IAttribute_GetStruct_]
==== method ``GetStruct``

[source,cs]
----
IReadOnlyDictionary< string, IValue? > GetStruct()
----



Returns a struct value of the value concept that this attribute holds represented as a dictionary from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`IReadOnlyDictionary< string, IValue? >`

[#_string_TypeDB_Driver_Api_IAttribute_GetValueType_]
==== method ``GetValueType``

[source,cs]
----
string GetValueType()
----



Retrieves the description of the value type of the value which the attribute instance holds.

[caption=""]
.Returns
`string`

[#_bool_IConcept_TypeDB_Driver_Api_IAttribute_IsAttribute_]
==== method ``IsAttribute``

[source,cs]
----
bool IConcept. IsAttribute()
----



Checks if the concept is an IAttribute.

 
  concept.IsAttribute()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_new_IAttributeType_TypeDB_Driver_Api_IAttribute_Type]
==== method ``Type``

[source,cs]
----
new IAttributeType TypeDB.Driver.Api.IAttribute.Type
----



The type which this attribute belongs to.

Implements TypeDB.Driver.Api.IThing.

[caption=""]
.Returns
`new IAttributeType`

[#_IValue_TypeDB_Driver_Api_IAttribute_Value]
==== method ``Value``

[source,cs]
----
IValue TypeDB.Driver.Api.IAttribute.Value
----



Retrieves the value which the attribute instance holds.

[caption=""]
.Returns
`IValue`

// end::methods[]

