[#_IEntity]
=== IEntity

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IEntity_IConcept_TypeDB_Driver_Api_IEntity_AsEntity_]
==== AsEntity

[source,cs]
----
IEntity IConcept. AsEntity()
----



Casts the concept to IEntity.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an entity.
    
   
  
 


 
  concept.AsEntity()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IEntity IConcept.`

[#_string_TypeDB_Driver_Api_IEntity_IID]
==== IID

[source,cs]
----
string TypeDB.Driver.Api.IEntity.IID
----



The unique id of the entity.

[caption=""]
.Returns
`string`

[#_bool_IConcept_TypeDB_Driver_Api_IEntity_IsEntity_]
==== IsEntity

[source,cs]
----
bool IConcept. IsEntity()
----



Checks if the concept is an IEntity.

 
  concept.IsEntity()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_new_IEntityType_TypeDB_Driver_Api_IEntity_Type]
==== Type

[source,cs]
----
new IEntityType TypeDB.Driver.Api.IEntity.Type
----



The type which this entity belongs to.

Implements TypeDB.Driver.Api.IThing.

[caption=""]
.Returns
`new IEntityType`

// end::methods[]

