[#_IEntity]
[.doc-api-reference-driver]
=== IEntity

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IInstance`
* `TypeDB.Driver.Api.IConcept`



Represents an entity instance in TypeDB. Entity instances are independent objects in the data model. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IEntity_IConcept_TypeDB_Driver_Api_IEntity_AsEntity_]
==== method ``AsEntity``

[source,cs]
----
IEntity IConcept. AsEntity()
----



Casts the concept to IEntity.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not an entity.
    
   
  
 


 
  concept.AsEntity()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IEntity IConcept.`

[#_bool_IConcept_TypeDB_Driver_Api_IEntity_IsEntity_]
==== method ``IsEntity``

[source,cs]
----
bool IConcept. IsEntity()
----



Checks if the concept is an IEntity.

 
  concept.IsEntity()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_new_IEntityType_TypeDB_Driver_Api_IEntity_Type]
==== method ``Type [1/2]``

[source,cs]
----
new IEntityType TypeDB.Driver.Api.IEntity.Type
----



The entity type which this entity instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`new IEntityType`

[#_IType_IInstance_TypeDB_Driver_Api_IEntity_Type]
==== method ``Type [2/2]``

[source,cs]
----
IType IInstance. TypeDB.Driver.Api.IEntity.Type
----



The type which this instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`IType IInstance.`

// end::methods[]

