[#_IRelation]
[.doc-api-reference-driver]
=== IRelation

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IInstance`
* `TypeDB.Driver.Api.IConcept`



Represents a relation instance in TypeDB. Relation instances connect multiple instances together through roles. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IRelation_IConcept_TypeDB_Driver_Api_IRelation_AsRelation_]
==== method ``AsRelation``

[source,cs]
----
IRelation IConcept. AsRelation()
----



Casts the concept to IRelation.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a relation.
    
   
  
 


 
  concept.AsRelation()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IRelation IConcept.`

[#_bool_IConcept_TypeDB_Driver_Api_IRelation_IsRelation_]
==== method ``IsRelation``

[source,cs]
----
bool IConcept. IsRelation()
----



Checks if the concept is a IRelation.

 
  concept.IsRelation()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_new_IRelationType_TypeDB_Driver_Api_IRelation_Type]
==== method ``Type [1/2]``

[source,cs]
----
new IRelationType TypeDB.Driver.Api.IRelation.Type
----



The relation type which this relation instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`new IRelationType`

[#_IType_IInstance_TypeDB_Driver_Api_IRelation_Type]
==== method ``Type [2/2]``

[source,cs]
----
IType IInstance. TypeDB.Driver.Api.IRelation.Type
----



The type which this instance belongs to.

Implements TypeDB.Driver.Api.IInstance.

[caption=""]
.Returns
`IType IInstance.`

// end::methods[]

