[#_IRelation]
=== IRelation

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IThing`
* `TypeDB.Driver.Api.IConcept`



Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IRelation_IConcept_TypeDB_Driver_Api_IRelation_AsRelation_]
==== AsRelation

[source,cs]
----
IRelation IConcept. AsRelation()
----



Casts the concept to IRelation.

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a relation.
    
   
  
 


 
  concept.AsRelation()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IRelation IConcept.`

[#_string_TypeDB_Driver_Api_IRelation_IID]
==== IID

[source,cs]
----
string TypeDB.Driver.Api.IRelation.IID
----



The unique id of the relation.

[caption=""]
.Returns
`string`

[#_bool_IConcept_TypeDB_Driver_Api_IRelation_IsRelation_]
==== IsRelation

[source,cs]
----
bool IConcept. IsRelation()
----



Checks if the concept is a IRelation.

 
  concept.IsRelation()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_new_IRelationType_TypeDB_Driver_Api_IRelation_Type]
==== Type

[source,cs]
----
new IRelationType TypeDB.Driver.Api.IRelation.Type
----



The type which this relation belongs to.

Implements TypeDB.Driver.Api.IThing.

[caption=""]
.Returns
`new IRelationType`

// end::methods[]

