[#_IThing]
[.doc-api-reference-driver]
=== IThing

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IConcept`



Represents an instance (entity, relation, or attribute) in TypeDB. In TypeDB 3.0, instances are read-only data returned from queries.

// tag::methods[]
[#_IThing_IConcept_TypeDB_Driver_Api_IThing_AsThing_]
==== method ``AsThing``

[source,cs]
----
IThing IConcept. AsThing()
----



Casts the concept to IThing (instance).

 
  Exceptions
 
 
  
   
    
     TypeDBDriverException
     If the concept is not a thing/instance.
    
   
  
 


 
  concept.AsThing()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IThing IConcept.`

[#_bool_IConcept_TypeDB_Driver_Api_IThing_IsInstance_]
==== method ``IsInstance``

[source,cs]
----
bool IConcept. IsInstance()
----



Checks if the concept is an instance (entity, relation, or attribute). This is the 3.0 name for what was previously called "Thing".

 
  concept.IsInstance()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_bool_IConcept_TypeDB_Driver_Api_IThing_IsThing_]
==== method ``IsThing``

[source,cs]
----
bool IConcept. IsThing()
----



Checks if the concept is a IThing. Note: In 3.0, this is also known as IsInstance().

 
  concept.IsThing()
 




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[#_IThingType_TypeDB_Driver_Api_IThing_Type]
==== method ``Type``

[source,cs]
----
IThingType TypeDB.Driver.Api.IThing.Type
----



The type which this instance belongs to.

Implemented in TypeDB.Driver.Api.IAttribute, TypeDB.Driver.Api.IEntity, and TypeDB.Driver.Api.IRelation.

[caption=""]
.Returns
`IThingType`

// end::methods[]

