[#_IValue]
[.doc-api-reference-driver]
=== IValue

`class`

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IConcept`



Represents a value concept in TypeDB. In TypeDB 3.0, values are read-only data returned from queries.

// tag::methods[]
[#_IValue_IConcept_TypeDB_Driver_Api_IValue_AsValue_]
==== method ``AsValue``

[source,cs]
----
IValue IConcept. AsValue()
----



Casts the concept to IValue.



Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IValue IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.AsValue()
----

[#_object_TypeDB_Driver_Api_IValue_Get_]
==== method ``Get``

[source,cs]
----
object Get()
----



Returns an untyped object value of this value concept. This is useful for value equality or printing without having to switch on the actual contained value.

[caption=""]
.Returns
`object`

[#_bool_TypeDB_Driver_Api_IValue_GetBoolean_]
==== method ``GetBoolean``

[source,cs]
----
bool GetBoolean()
----



Returns a boolean value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[#_DateOnly_TypeDB_Driver_Api_IValue_GetDate_]
==== method ``GetDate``

[source,cs]
----
DateOnly GetDate()
----



Returns a date value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`DateOnly`

[#_Datetime_TypeDB_Driver_Api_IValue_GetDatetime_]
==== method ``GetDatetime``

[source,cs]
----
Datetime GetDatetime()
----



Returns a datetime value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Datetime`

[#_DatetimeTZ_TypeDB_Driver_Api_IValue_GetDatetimeTZ_]
==== method ``GetDatetimeTZ``

[source,cs]
----
DatetimeTZ GetDatetimeTZ()
----



Returns a datetime with timezone value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`DatetimeTZ`

[#_decimal_TypeDB_Driver_Api_IValue_GetDecimal_]
==== method ``GetDecimal``

[source,cs]
----
decimal GetDecimal()
----



Returns a decimal value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`decimal`

[#_double_TypeDB_Driver_Api_IValue_GetDouble_]
==== method ``GetDouble``

[source,cs]
----
double GetDouble()
----



Returns a double value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`double`

[#_Duration_TypeDB_Driver_Api_IValue_GetDuration_]
==== method ``GetDuration``

[source,cs]
----
Duration GetDuration()
----



Returns a duration value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`Duration`

[#_long_TypeDB_Driver_Api_IValue_GetInteger_]
==== method ``GetInteger``

[source,cs]
----
long GetInteger()
----



Returns an integer (long) value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`long`

[#_string_TypeDB_Driver_Api_IValue_GetString_]
==== method ``GetString``

[source,cs]
----
string GetString()
----



Returns a string value of this value concept. If the value has another type, raises an exception.

[caption=""]
.Returns
`string`

[#_IReadOnlyDictionary_string_IValue_TypeDB_Driver_Api_IValue_GetStruct_]
==== method ``GetStruct``

[source,cs]
----
IReadOnlyDictionary< string, IValue? > GetStruct()
----



Returns a struct value of this value concept represented as a dictionary from field names to values. If the value has another type, raises an exception.

[caption=""]
.Returns
`IReadOnlyDictionary< string, IValue? >`

[#_string_TypeDB_Driver_Api_IValue_GetValueType_]
==== method ``GetValueType``

[source,cs]
----
string GetValueType()
----



Retrieves the value type of this value concept as a string.

[caption=""]
.Returns
`string`

[#_bool_IConcept_TypeDB_Driver_Api_IValue_IsValue_]
==== method ``IsValue``

[source,cs]
----
bool IConcept. IsValue()
----



Checks if the concept is a IValue.



Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.IsValue()
----

// end::methods[]

