[#_ConceptMap]
=== ConceptMap

*Package*: `TypeDB`



Contains a mapping of variables to concepts.

// tag::methods[]
[#_a03461a44a3e60960f2b88cc67316bc24]
==== concepts

[source,cpp]
----
ConceptIterable< Concept > TypeDB::ConceptMap::concepts()
----



Produces an ``Iterator`` over all concepts in this ``ConceptMap``.


[caption=""]
.Returns
`ConceptIterable< Concept >`

[#_a6375fe2c20401d026265ea2ba8704368]
==== explainables

[source,cpp]
----
Explainables TypeDB::ConceptMap::explainables()
----



Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable.


[caption=""]
.Returns
`Explainables`

[#_a8f29ce5780ce17b7bec316c23e654a38]
==== get

[source,cpp]
----
std::unique_ptr< Concept > TypeDB::ConceptMap::get(const std::string& variableName)
----



Retrieves a concept for a given variable name.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| 
|===

[caption=""]
.Returns
`std::unique_ptr< Concept >`

[#_a4efef43c65cf998814a81083e389ea93]
==== map

[source,cpp]
----
std::map< std::string, std::unique_ptr< Concept > > TypeDB::ConceptMap::map()
----



Returns the inner ``Map`` where keys are query variables, and values are concepts.


[caption=""]
.Returns
`std::map< std::string, std::unique_ptr< Concept > >`

[#_a4fd571d238734f410012f186252d4ee7]
==== toString

[source,cpp]
----
std::string TypeDB::ConceptMap::toString()
----



A string representation of this ConceptMap.

[caption=""]
.Returns
`std::string`

[#_a4e8ef2223116dca58e4b2556c61413ef]
==== variables

[source,cpp]
----
StringIterable TypeDB::ConceptMap::variables()
----



Produces an ``Iterator`` stream over all variables in this ``ConceptMap``.


[caption=""]
.Returns
`StringIterable`

// end::methods[]

