[#_Explanation]
=== Explanation

*Package*: `TypeDB`



An explanation of which rule was used to infer the concept and the satisfying ConceptMaps.

An explanation of which rule was used for inferring the explained concept, the condition of the rule, the conclusion of the rule, and the mapping of variables between the query and the rule’s conclusion.

// tag::methods[]
[#_ConceptMap_TypeDBExplanationconclusion___]
==== conclusion

[source,cpp]
----
ConceptMap TypeDB::Explanation::conclusion()
----



Retrieves the Conclusion for this Explanation.


[caption=""]
.Returns
`ConceptMap`

[caption=""]
.Code examples
[source,cpp]
----
explanation.conclusion()
----

[#_ConceptMap_TypeDBExplanationcondition___]
==== condition

[source,cpp]
----
ConceptMap TypeDB::Explanation::condition()
----



Retrieves the Condition for this Explanation.


[caption=""]
.Returns
`ConceptMap`

[caption=""]
.Code examples
[source,cpp]
----
explanation.condition()
----

[#_stdvector__stdstring___TypeDBExplanationqueryVariableMapping___const_stdstring__var_]
==== queryVariableMapping

[source,cpp]
----
std::vector< std::string > TypeDB::Explanation::queryVariableMapping(const std::string& var)
----



Retrieves the rule variables corresponding to the query variable var for this ``Explanation``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `var` a| The query variable to map to rule variables. a| `const std::string&`
|===

[caption=""]
.Returns
`std::vector< std::string >`

[caption=""]
.Code examples
[source,cpp]
----
explanation.variableMapping(var)
----

[#_stdvector__stdstring___TypeDBExplanationqueryVariables___]
==== queryVariables

[source,cpp]
----
std::vector< std::string > TypeDB::Explanation::queryVariables()
----



Retrieves the query variables for this ``Explanation``.


[caption=""]
.Returns
`std::vector< std::string >`

[caption=""]
.Code examples
[source,cpp]
----
explanation.queryVariables()
----

[#_Rule_TypeDBExplanationrule___]
==== rule

[source,cpp]
----
Rule TypeDB::Explanation::rule()
----



Retrieves the Rule for this Explanation.


[caption=""]
.Returns
`Rule`

[caption=""]
.Code examples
[source,cpp]
----
explanation.rule()
----

[#_stdstring_TypeDBExplanationtoString___]
==== toString

[source,cpp]
----
std::string TypeDB::Explanation::toString()
----



A string representation of this Explanation.

[caption=""]
.Returns
`std::string`

// end::methods[]

