[#_Explainables]
=== Explainables

*Package*: `TypeDB`



Contains explainable objects.

// tag::methods[]
[#_Explainable_TypeDBExplainablesattribute___stdstring__variable_]
==== attribute

[source,cpp]
----
Explainable TypeDB::Explainables::attribute(std::string& variable)
----



Retrieves the explainable attribute with the given variable name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `std::string&`
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().attribute(variable);
----

[#_StringIterable_TypeDBExplainablesattributes___]
==== attributes

[source,cpp]
----
StringIterable TypeDB::Explainables::attributes()
----



Retrieves all of this ``ConceptMap``’s explainable attributes.


[caption=""]
.Returns
`StringIterable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().attributes();
----

[#_Explainable_TypeDBExplainablesownership___stdstring__owner__stdstring__attribute_]
==== ownership

[source,cpp]
----
Explainable TypeDB::Explainables::ownership(std::string& owner, std::string& attribute)
----



Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `owner` a| The string representation of the owner variable a| `std::string&`
a| `attribute` a| The string representation of the attribute variable a| `std::string&`
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().ownership(owner, attribute);
----

[#_OwnerAttributePairIterable_TypeDBExplainablesownerships___]
==== ownerships

[source,cpp]
----
OwnerAttributePairIterable TypeDB::Explainables::ownerships()
----



Retrieves all of this ``ConceptMap``’s explainable ownerships.


[caption=""]
.Returns
`OwnerAttributePairIterable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().ownerships();
----

[#_Explainable_TypeDBExplainablesrelation___stdstring__variable_]
==== relation

[source,cpp]
----
Explainable TypeDB::Explainables::relation(std::string& variable)
----



Retrieves the explainable relation with the given variable name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `std::string&`
|===

[caption=""]
.Returns
`Explainable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().relation(variable);
----

[#_StringIterable_TypeDBExplainablesrelations___]
==== relations

[source,cpp]
----
StringIterable TypeDB::Explainables::relations()
----



Retrieves all of this ``ConceptMap``’s explainable relations.


[caption=""]
.Returns
`StringIterable`

[caption=""]
.Code examples
[source,cpp]
----
conceptMap.explainables().relations();
----

[#_stdstring_TypeDBExplainablestoString___]
==== toString

[source,cpp]
----
std::string TypeDB::Explainables::toString()
----



A string representation of this object.

[caption=""]
.Returns
`std::string`

// end::methods[]

