[#_Explanation]
=== Explanation

*Package*: `TypeDB`



An explanation of which rule was used to infer the concept and the satisfying ConceptMaps.

An explanation of which rule was used for inferring the explained concept, the condition of the rule, the conclusion of the rule, and the mapping of variables between the query and the rule’s conclusion.

// tag::methods[]
[#_a75409380ab712cb37df0dfaffd022f8a]
==== conclusion

[source,cpp]
----
ConceptMap TypeDB::Explanation::conclusion()
----



Retrieves the Conclusion for this Explanation.


[caption=""]
.Returns
`ConceptMap`

[#_a43533e53b46d791130fc234ed3d6ed8b]
==== condition

[source,cpp]
----
ConceptMap TypeDB::Explanation::condition()
----



Retrieves the Condition for this Explanation.


[caption=""]
.Returns
`ConceptMap`

[#_aa5d56a4e9f18e37f78bb17a0f6d9e600]
==== queryVariableMapping

[source,cpp]
----
std::vector<std::string> TypeDB::Explanation::queryVariableMapping(const std::string& var)
----



Retrieves the rule variables corresponding to the query variable var for this ``Explanation``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `var` a| The query variable to map to rule variables. a| 
|===

[caption=""]
.Returns
`std::vector< std::string >`

[#_a31622e232561526cc7f801862aacae7d]
==== queryVariables

[source,cpp]
----
std::vector<std::string> TypeDB::Explanation::queryVariables()
----



Retrieves the query variables for this ``Explanation``.


[caption=""]
.Returns
`std::vector< std::string >`

[#_ade2c442a1ab379a2c68a829b52e09d57]
==== rule

[source,cpp]
----
Rule TypeDB::Explanation::rule()
----



Retrieves the Rule for this Explanation.


[caption=""]
.Returns
`Rule`

[#_ae6cdbec3d05e3f790ca9ec598a2a62f9]
==== toString

[source,cpp]
----
std::string TypeDB::Explanation::toString()
----



A string representation of this Explanation.

[caption=""]
.Returns
`std::string`

// end::methods[]

