[#_JSON]
=== JSON

*Package*: `TypeDB`



Simple JSON structure for results of fetch queries.

// tag::methods[]
[#_a2098936f80396f4ec929459ce366207c]
==== asArray

[source,cpp]
----
const JSONArray& TypeDB::JSON::asArray() const
----



if this JSON object holds an array, returns the underlying array. Else throws an exception

[caption=""]
.Returns
`const JSONArray&`

[#_ab0e4a2cecd13e58de143da1819f1b3af]
==== asBoolean

[source,cpp]
----
const JSONBoolean& TypeDB::JSON::asBoolean() const
----



if this JSON object holds a boolean value, returns the value. Else throws an exception

[caption=""]
.Returns
`const JSONBoolean&`

[#_a2b5fa5382142c1f84c4d01bd2abae225]
==== asDouble

[source,cpp]
----
const JSONDouble& TypeDB::JSON::asDouble() const
----



if this JSON object holds a double value, returns the value. Else throws an exception

[caption=""]
.Returns
`const JSONDouble&`

[#_a0c9953282695015768defdb226ab63d7]
==== asLong

[source,cpp]
----
const JSONLong& TypeDB::JSON::asLong() const
----



if this JSON object holds a long value, returns the value. Else throws an exception

[caption=""]
.Returns
`const JSONLong&`

[#_ad90ecedbb2cf4452713bc1afae89ab62]
==== asMap

[source,cpp]
----
const JSONMap& TypeDB::JSON::asMap() const
----



if this JSON object holds a map, returns the underlying map. Else throws an exception

[caption=""]
.Returns
`const JSONMap&`

[#_ad921ddf2e0305ae8781cc1d06f0f449c]
==== asString

[source,cpp]
----
const JSONString& TypeDB::JSON::asString() const
----



if this JSON object holds a string value, returns the value. Else throws an exception

[caption=""]
.Returns
`const JSONString&`

[#_a419d60e5a26870b0fb36bdd0ccd1a6f5]
==== isArray

[source,cpp]
----
bool TypeDB::JSON::isArray() const
----



true if this JSON object holds an array, else false

[caption=""]
.Returns
`bool`

[#_a14c7132a8e9b8feb77a18d870f491221]
==== isBoolean

[source,cpp]
----
bool TypeDB::JSON::isBoolean() const
----



true if this JSON object holds a boolean value, else false

[caption=""]
.Returns
`bool`

[#_a8d85e9d0e08acd2fe63c05f68902c5c6]
==== isDouble

[source,cpp]
----
bool TypeDB::JSON::isDouble() const
----



true if this JSON object holds a double value, else false

[caption=""]
.Returns
`bool`

[#_aa6ec960840bc7c0fef89de2149f1f7b5]
==== isLong

[source,cpp]
----
bool TypeDB::JSON::isLong() const
----



true if this JSON object holds a long value, else false

[caption=""]
.Returns
`bool`

[#_ac3856d405d4a859911bae38ea00eeea7]
==== isMap

[source,cpp]
----
bool TypeDB::JSON::isMap() const
----



true if this JSON object holds a map, else false

[caption=""]
.Returns
`bool`

[#_a8d9a53eab52b25450958e5dac7971d16]
==== isString

[source,cpp]
----
bool TypeDB::JSON::isString() const
----



true if this JSON object holds a string value, else false

[caption=""]
.Returns
`bool`

[#_a80bc5a961a935fd08c5942d5d7d2a132]
==== parse

[source,cpp]
----
static JSON TypeDB::JSON::parse(const std::string& string)
----



Parses a JSON string into a ``JSON`` object.

[caption=""]
.Returns
`static JSON`

// end::methods[]

