[#_DriverOptions]
[.doc-api-reference-driver]
=== DriverOptions

`class`

*Package*: `TypeDB.Driver.Api`



TypeDB driver options. ``DriverOptions`` are used to specify the driver's connection behavior.

// tag::methods[]
[#_TypeDB_Driver_Api_DriverOptions_DriverOptions_DriverTlsConfig_tlsConfig_]
==== method ``DriverOptions``

[source,cs]
----
DriverOptions(DriverTlsConfig tlsConfig)
----



Produces a new ``DriverOptions`` object for connecting to TypeDB Server using custom TLS settings. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `tlsConfig` a| The TLS configuration for the connection. a| `DriverTlsConfig`
|===

[caption=""]
.Returns
`DriverOptions`

[caption=""]
.Code examples
[source,cs]
----
DriverOptions options = new DriverOptions(DriverTlsConfig.EnabledWithNativeRootCA()) { RequestTimeoutMillis = 30000 }; TypeDB.Driver.Api.DriverOptions TypeDB driver options. DriverOptions are used to specify the driver's connection behavior. Definition DriverOptions.cs:29 TypeDB.Driver.Api.DriverTlsConfig TLS configuration for the TypeDB driver. Definition DriverTlsConfig.cs:37 TypeDB.Driver.Api.DriverTlsConfig.EnabledWithNativeRootCA static DriverTlsConfig EnabledWithNativeRootCA() Creates a TLS configuration enabled with system native trust roots. Definition DriverTlsConfig.cs:65
----

[#_int_TypeDB_Driver_Api_DriverOptions_PrimaryFailoverRetries]
==== method ``PrimaryFailoverRetries``

[source,cs]
----
int TypeDB.Driver.Api.DriverOptions.PrimaryFailoverRetries
----



Gets or sets the limit on the number of attempts to redirect a request to another primary server in case of a failure due to the change of server roles. Defaults to 1.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,cs]
----
options.PrimaryFailoverRetries = 3;
----

[#_long_TypeDB_Driver_Api_DriverOptions_RequestTimeoutMillis]
==== method ``RequestTimeoutMillis``

[source,cs]
----
long TypeDB.Driver.Api.DriverOptions.RequestTimeoutMillis
----



Gets or sets the maximum time (in milliseconds) to wait for a response to a unary RPC request. This applies to operations like database creation, user management, and initial transaction opening. It does NOT apply to operations within transactions (queries, commits). Defaults to 2 hours (7200000 milliseconds).

[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,cs]
----
options.RequestTimeoutMillis = 30000;
----

[#_DriverTlsConfig_TypeDB_Driver_Api_DriverOptions_TlsConfig]
==== method ``TlsConfig``

[source,cs]
----
DriverTlsConfig TypeDB.Driver.Api.DriverOptions.TlsConfig
----



Gets or sets the TLS configuration associated with this ``DriverOptions``. Specifies the TLS configuration of the connection to TypeDB. WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.

[caption=""]
.Returns
`DriverTlsConfig`

[caption=""]
.Code examples
[source,cs]
----
options.TlsConfig = DriverTlsConfig.EnabledWithNativeRootCA();
----

// end::methods[]

