[#_IDatabaseManager]
[.doc-api-reference-driver]
=== IDatabaseManager

`class`

*Package*: `TypeDB.Driver.Api`



Provides access to all database management methods.

// tag::methods[]
[#_bool_TypeDB_Driver_Api_IDatabaseManager_Contains_string_name_]
==== method ``Contains``

[source,cs]
----
bool Contains(string name)
----



Checks if a database with the given name exists.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The database name to be checked a| `string`
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases.Contains(name);
----

[#_void_TypeDB_Driver_Api_IDatabaseManager_Create_string_name_]
==== method ``Create``

[source,cs]
----
void Create(string name)
----



Create a database with the given name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to be created a| `string`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases.Create(name);
----

[#_IDatabase_TypeDB_Driver_Api_IDatabaseManager_Get_string_name_]
==== method ``Get``

[source,cs]
----
IDatabase Get(string name)
----



Retrieve the database with the given name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to retrieve a| `string`
|===

[caption=""]
.Returns
`IDatabase`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases.Get(name);
----

[#_IList_IDatabase_TypeDB_Driver_Api_IDatabaseManager_GetAll_]
==== method ``GetAll``

[source,cs]
----
IList< IDatabase > GetAll()
----



Retrieves all databases present on the TypeDB server.


[caption=""]
.Returns
`IList< IDatabase >`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases.GetAll();
----

[#_void_TypeDB_Driver_Api_IDatabaseManager_ImportFromFile_string_name_string_schema_string_dataFile_]
==== method ``ImportFromFile``

[source,cs]
----
void ImportFromFile(string name, string schema, string dataFile)
----



Creates a database with the given name based on previously exported data. This is a blocking operation and may take a significant amount of time depending on the database size.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `name` a| The name of the database to be created. a| `string`
a| `schema` a| The schema definition query string for the database. a| `string`
a| `dataFile` a| The exported database file path to import the data from. a| `string`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases.ImportFromFile("mydb", schemaString, "/path/to/data.typedb");
----

// end::methods[]

