[#_IDatabase]
[.doc-api-reference-driver]
=== IDatabase

`class`

*Package*: `TypeDB.Driver.Api`



A TypeDB database.

// tag::methods[]
[#_void_TypeDB_Driver_Api_IDatabase_Delete_]
==== method ``Delete``

[source,cs]
----
void Delete()
----



Deletes this database.

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
database.Delete();
----

[#_void_TypeDB_Driver_Api_IDatabase_ExportToFile_string_schemaFile_string_dataFile_]
==== method ``ExportToFile``

[source,cs]
----
void ExportToFile(string schemaFile, string dataFile)
----



Exports this database to a schema definition file and a data file on disk. This is a blocking operation and may take a significant amount of time depending on the database size.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaFile` a| The path to the schema definition file to be created. a| `string`
a| `dataFile` a| The path to the data file to be created. a| `string`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
database.ExportToFile("schema.tql", "data.typedb");
----

[#_string_TypeDB_Driver_Api_IDatabase_GetSchema_]
==== method ``GetSchema``

[source,cs]
----
string GetSchema()
----



Returns the full schema text as a valid TypeQL define query string.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.GetSchema();
----

[#_string_TypeDB_Driver_Api_IDatabase_GetTypeSchema_]
==== method ``GetTypeSchema``

[source,cs]
----
string GetTypeSchema()
----



Returns the types in the schema as a valid TypeQL define query string.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.GetTypeSchema();
----

[#_string_TypeDB_Driver_Api_IDatabase_Name]
==== method ``Name``

[source,cs]
----
string TypeDB.Driver.Api.IDatabase.Name
----



The database name as a string.

[caption=""]
.Returns
`string`

[caption=""]
.Code examples
[source,cs]
----
database.Name;
----

// end::methods[]

