[#_IDriver]
[.doc-api-reference-driver]
=== IDriver

`class`

*Package*: `TypeDB.Driver.Api`



A connection to a TypeDB server which serves as the starting point for all interaction.

// tag::methods[]
[#_void_TypeDB_Driver_Api_IDriver_Close_]
==== method ``Close``

[source,cs]
----
void Close()
----



Closes the driver. Before instantiating a new driver, the driver that's currently open should first be closed.

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
driver.Close();
----

[#_IDatabaseManager_TypeDB_Driver_Api_IDriver_Databases]
==== method ``Databases``

[source,cs]
----
IDatabaseManager TypeDB.Driver.Api.IDriver.Databases
----



The IDatabaseManager for this connection, providing access to database management methods.

[caption=""]
.Returns
`IDatabaseManager`

[caption=""]
.Code examples
[source,cs]
----
driver.Databases
----

[#_bool_TypeDB_Driver_Api_IDriver_IsOpen_]
==== method ``IsOpen``

[source,cs]
----
bool IsOpen()
----



Checks whether this connection is presently open.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
driver.IsOpen();
----

[#_ITransaction_TypeDB_Driver_Api_IDriver_Transaction_string_database_TransactionType_type_]
==== method ``Transaction``

[source,cs]
----
ITransaction Transaction(string database, TransactionType type)
----



Opens a transaction to perform read or write queries on the database.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database to open a transaction for. a| `string`
a| `type` a| The type of transaction to be created (Read, Write, or Schema). a| `TransactionType`
|===

[caption=""]
.Returns
`ITransaction`

[caption=""]
.Code examples
[source,cs]
----
driver.Transaction(database, TransactionType.Read); TypeDB.Driver.Api.TransactionType TransactionType Used to specify the type of transaction. Definition ITransaction.cs:99
----

[#_ITransaction_TypeDB_Driver_Api_IDriver_Transaction_string_database_TransactionType_type_TransactionOptions_options_]
==== method ``Transaction``

[source,cs]
----
ITransaction Transaction(string database, TransactionType type, TransactionOptions options)
----



Opens a transaction to perform read or write queries on the database with custom options.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database to open a transaction for. a| `string`
a| `type` a| The type of transaction to be created (Read, Write, or Schema). a| `TransactionType`
a| `options` a| Transaction options to configure the opened transaction. a| `TransactionOptions`
|===

[caption=""]
.Returns
`ITransaction`

[caption=""]
.Code examples
[source,cs]
----
driver.Transaction(database, TransactionType.Read, options);
----

[#_IUserManager_TypeDB_Driver_Api_IDriver_Users]
==== method ``Users``

[source,cs]
----
IUserManager TypeDB.Driver.Api.IDriver.Users
----



The IUserManager instance for this connection, providing access to user management methods.

[caption=""]
.Returns
`IUserManager`

[caption=""]
.Code examples
[source,cs]
----
driver.Users
----

// end::methods[]

