[#_IUserManager]
=== IUserManager

*Package*: `TypeDB.Driver.Api`



Provides access to all user management methods.

// tag::methods[]
[#_bool_TypeDB_Driver_Api_IUserManager_Contains_string_username_]
==== Contains

[source,cs]
----
bool Contains(string username)
----



Checks if a user with the given name exists.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked. a| `string`
|===

[caption=""]
.Returns
`bool`

[#_void_TypeDB_Driver_Api_IUserManager_Create_string_username_string_password_]
==== Create

[source,cs]
----
void Create(string username, string password)
----



Creates a user with the given name and password.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created. a| `string`
a| `password` a| The password of the user to be created. a| `string`
|===

[caption=""]
.Returns
`void`

[#_IUser_TypeDB_Driver_Api_IUserManager_Get_string_username_]
==== Get

[source,cs]
----
IUser? Get(string username)
----



Retrieves a user with the given name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve. a| `string`
|===

[caption=""]
.Returns
`IUser?`

[#_ISet_IUser_TypeDB_Driver_Api_IUserManager_GetAll_]
==== GetAll

[source,cs]
----
ISet< IUser > GetAll()
----



Retrieves all users which exist on the TypeDB server.

 
  Returns
 
 
  A set of all users.
 


 
  driver.Users.GetAll();
 


[caption=""]
.Returns
`ISet< IUser >`

[#_IUser_TypeDB_Driver_Api_IUserManager_GetCurrentUser_]
==== GetCurrentUser

[source,cs]
----
IUser GetCurrentUser()
----



Retrieves the currently logged in user.

 
  Returns
 
 
  The current user.
 


 
  driver.Users.GetCurrentUser();
 


[caption=""]
.Returns
`IUser`

// end::methods[]

