[#_IUserManager]
[.doc-api-reference-driver]
=== IUserManager

`class`

*Package*: `TypeDB.Driver.Api`



Provides access to all user management methods.

// tag::methods[]
[#_bool_TypeDB_Driver_Api_IUserManager_Contains_string_username_]
==== method ``Contains``

[source,cs]
----
bool Contains(string username)
----



Checks if a user with the given name exists.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked. a| `string`
|===

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cs]
----
driver.Users.Contains(username);
----

[#_void_TypeDB_Driver_Api_IUserManager_Create_string_username_string_password_]
==== method ``Create``

[source,cs]
----
void Create(string username, string password)
----



Creates a user with the given name and password.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created. a| `string`
a| `password` a| The password of the user to be created. a| `string`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cs]
----
driver.Users.Create(username, password);
----

[#_IUser_TypeDB_Driver_Api_IUserManager_Get_string_username_]
==== method ``Get``

[source,cs]
----
IUser? Get(string username)
----



Retrieves a user with the given name.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve. a| `string`
|===

[caption=""]
.Returns
`IUser?`

[caption=""]
.Code examples
[source,cs]
----
driver.Users.Get(username);
----

[#_ISet_IUser_TypeDB_Driver_Api_IUserManager_GetAll_]
==== method ``GetAll``

[source,cs]
----
ISet< IUser > GetAll()
----



Retrieves all users which exist on the TypeDB server.

[caption=""]
.Returns
`ISet< IUser >`

[caption=""]
.Code examples
[source,cs]
----
driver.Users.GetAll();
----

[#_IUser_TypeDB_Driver_Api_IUserManager_GetCurrentUser_]
==== method ``GetCurrentUser``

[source,cs]
----
IUser GetCurrentUser()
----



Retrieves the currently logged in user.

[caption=""]
.Returns
`IUser`

[caption=""]
.Code examples
[source,cs]
----
driver.Users.GetCurrentUser();
----

// end::methods[]

