[#_TypeDBCredential]
=== TypeDBCredential

*Package*: `TypeDB.Driver.Api`



User credentials and TLS encryption settings for connecting to TypeDB Cluster.


[caption=""]
.Examples
[source,cs]
----
// Creates a credentials as above, but the connection will be made over TLS.
TypeDBCredential credentials = new TypeDBCredential(username, password, true);

// Creates a credentials as above, but TLS will use the specified CA to authenticate server certificates.
TypeDBCredential credentials = new TypeDBCredential(username, password, Environment.GetEnvironmentVariable("ROOT_CA")!);
----

// tag::methods[]
[#_TypeDB_Driver_Api_TypeDBCredential_TypeDBCredential_string_username_string_password_bool_tlsEnabled_]
==== TypeDBCredential

[source,cs]
----
TypeDBCredential(string username, string password, bool tlsEnabled)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `string`
a| `password` a| The password for the user a| `string`
a| `tlsEnabled` a| Specify whether the connection to TypeDB Cluster must be done over TLS a| `bool`
|===

[caption=""]
.Returns
`TypeDBCredential`

[#_TypeDB_Driver_Api_TypeDBCredential_TypeDBCredential_string_username_string_password_string_tlsRootCAPath_]
==== TypeDBCredential

[source,cs]
----
TypeDBCredential(string username, string password, string? tlsRootCAPath)
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| `string`
a| `password` a| The password for the user a| `string`
a| `tlsRootCAPath` a| Path to the CA certificate to use for authenticating server certificates a| `string?`
|===

[caption=""]
.Returns
`TypeDBCredential`

// end::methods[]

