[#_struct_Options]
=== Options

*Implements traits:*

* `Clone`
* `Copy`
* `Debug`
* `Default`

TypeDB session and transaction options. ``TypeDBOptions`` object can be used to override the default server behaviour. Options are specified using properties assignment.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `explain` a| `Option<bool>` a| If set to ``True``, enables explanations for queries. Only affects read transactions.
a| `infer` a| `Option<bool>` a| If set to ``True``, enables inference for queries. Only settable at transaction level and above. Only affects read transactions.
a| `parallel` a| `Option<bool>` a| If set to ``True``, the server uses parallel instead of single-threaded execution.
a| `prefetch` a| `Option<bool>` a| If set to ``True``, the first batch of answers is streamed to the driver even without an explicit request for it.
a| `prefetch_size` a| `Option<i32>` a| If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.
a| `read_any_replica` a| `Option<bool>` a| If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.
a| `schema_lock_acquire_timeout` a| `Option<Duration>` a| If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.
a| `session_idle_timeout` a| `Option<Duration>` a| If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.
a| `trace_inference` a| `Option<bool>` a| If set to ``True``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.
a| `transaction_timeout` a| `Option<Duration>` a| If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.
|===
// end::properties[]

// tag::methods[]
[#_struct_Options_explain__]
==== explain

[source,rust]
----
pub fn explain(self, explain: bool) -> Self
----

If set to ``True``, enables explanations for queries. Only affects read transactions.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_infer__]
==== infer

[source,rust]
----
pub fn infer(self, infer: bool) -> Self
----

If set to ``True``, enables inference for queries. Only settable at transaction level and above. Only affects read transactions.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_parallel__]
==== parallel

[source,rust]
----
pub fn parallel(self, parallel: bool) -> Self
----

If set to ``True``, the server uses parallel instead of single-threaded execution.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_prefetch__]
==== prefetch

[source,rust]
----
pub fn prefetch(self, prefetch: bool) -> Self
----

If set to ``True``, the first batch of answers is streamed to the driver even without an explicit request for it.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_prefetch_size__]
==== prefetch_size

[source,rust]
----
pub fn prefetch_size(self, prefetch_size: i32) -> Self
----

If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_read_any_replica__]
==== read_any_replica

[source,rust]
----
pub fn read_any_replica(self, read_any_replica: bool) -> Self
----

If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_schema_lock_acquire_timeout__]
==== schema_lock_acquire_timeout

[source,rust]
----
pub fn schema_lock_acquire_timeout(self, timeout: Duration) -> Self
----

If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_session_idle_timeout__]
==== session_idle_timeout

[source,rust]
----
pub fn session_idle_timeout(self, timeout: Duration) -> Self
----

If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_trace_inference__]
==== trace_inference

[source,rust]
----
pub fn trace_inference(self, trace_inference: bool) -> Self
----

If set to ``True``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``.

[caption=""]
.Returns
[source,rust]
----
Self
----

[#_struct_Options_transaction_timeout__]
==== transaction_timeout

[source,rust]
----
pub fn transaction_timeout(self, timeout: Duration) -> Self
----

If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.

[caption=""]
.Returns
[source,rust]
----
Self
----

// end::methods[]

