[#_struct_Session]
=== Session

*Implements traits:*

* `Debug`
* `Drop`

// tag::methods[]
[#_struct_Session_method_database_name]
==== database_name

[source,rust]
----
pub fn database_name(&self) -> &str
----

Returns the name of the database of the session.

[caption=""]
.Returns
[source,rust]
----
&str
----

[caption=""]
.Code examples
[source,rust]
----
session.database_name();
----

[#_struct_Session_method_force_close]
==== force_close

[source,rust]
----
pub fn force_close(&self) -> Result
----

Closes the session. Before opening a new session, the session currently open should first be closed.

[caption=""]
.Returns
[source,rust]
----
Result
----

[caption=""]
.Code examples
[source,rust]
----
session.force_close();
----

[#_struct_Session_method_is_open]
==== is_open

[source,rust]
----
pub fn is_open(&self) -> bool
----

Checks whether this session is open.

[caption=""]
.Returns
[source,rust]
----
bool
----

[caption=""]
.Code examples
[source,rust]
----
session.is_open();
----

[#_struct_Session_method_new]
==== new

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new(database: Database, session_type: SessionType) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new(database: Database, session_type: SessionType) -> Result<Self>
----

--
====

Opens a communication tunnel (session) to the given database with default options. See <<#_struct_Session_method_new_with_options,`Session::new_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[#_struct_Session_method_new_with_options]
==== new_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn new_with_options(
    database: Database,
    session_type: SessionType,
    options: Options
) -> Result<Self>
----

--

sync::
+
--
[source,rust]
----
pub fn new_with_options(
    database: Database,
    session_type: SessionType,
    options: Options
) -> Result<Self>
----

--
====

Opens a communication tunnel (session) to the given database on the running TypeDB server.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The database with which the session connects a| `Database`
a| `session_type` a| The type of session to be created (DATA or SCHEMA) a| `SessionType`
a| `options` a| ``TypeDBOptions`` for the session a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Self>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
Session::new_with_options(database, session_type, options).await;
----

--

sync::
+
--
[source,rust]
----
Session::new_with_options(database, session_type, options);
----

--
====

[#_struct_Session_method_on_close]
==== on_close

[source,rust]
----
pub fn on_close(&self, callback: impl FnOnce() + Send + 'static)
----

Registers a callback function which will be executed when this session is closed.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `function` a| The callback function. a| 
|===

[caption=""]
.Returns
[source,rust]
----
null
----

[caption=""]
.Code examples
[source,rust]
----
session.on_close(function);
----

[#_struct_Session_method_transaction]
==== transaction

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction(
    &self,
    transaction_type: TransactionType
) -> Result<Transaction<'_>>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction(
    &self,
    transaction_type: TransactionType
) -> Result<Transaction<'_>>
----

--
====

Opens a transaction to perform read or write queries on the database connected to the session. See <<#_struct_Session_method_transaction_with_options,`Session::transaction_with_options`>>

[caption=""]
.Returns
[source,rust]
----
Result<Transaction<'_>>
----

[#_struct_Session_method_transaction_with_options]
==== transaction_with_options

[tabs]
====
async::
+
--
[source,rust]
----
pub async fn transaction_with_options(
    &self,
    transaction_type: TransactionType,
    options: Options
) -> Result<Transaction<'_>>
----

--

sync::
+
--
[source,rust]
----
pub fn transaction_with_options(
    &self,
    transaction_type: TransactionType,
    options: Options
) -> Result<Transaction<'_>>
----

--
====

Opens a transaction to perform read or write queries on the database connected to the session.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction_type` a| The type of transaction to be created (READ or WRITE) a| `TransactionType`
a| `options` a| Options for the session a| `Options`
|===

[caption=""]
.Returns
[source,rust]
----
Result<Transaction<'_>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
session.transaction_with_options(transaction_type, options).await;
----

--

sync::
+
--
[source,rust]
----
session.transaction_with_options(transaction_type, options);
----

--
====

[#_struct_Session_method_type]
==== type_

[source,rust]
----
pub fn type_(&self) -> SessionType
----

The current session’s type (SCHEMA or DATA)

[caption=""]
.Returns
[source,rust]
----
SessionType
----

// end::methods[]

