[#_IConceptManager]
=== IConceptManager

*Package*: `TypeDB.Driver.Api`



Provides access for all Concept API methods.

// tag::methods[]
[#_Promise__IAttribute___TypeDB_Driver_Api_IConceptManager_GetAttribute___string_iid_]
==== GetAttribute

[source,cs]
----
Promise< IAttribute > GetAttribute(string iid)
----



Retrieves an ``IAttribute`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetAttribute(iid).Resolve();
----

[#_Promise__IAttributeType___TypeDB_Driver_Api_IConceptManager_GetAttributeType___string_label_]
==== GetAttributeType

[source,cs]
----
Promise< IAttributeType > GetAttributeType(string label)
----



Retrieves an ``IAttributeType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetAttributeType(label).Resolve();
----

[#_Promise__IEntity___TypeDB_Driver_Api_IConceptManager_GetEntity___string_iid_]
==== GetEntity

[source,cs]
----
Promise< IEntity > GetEntity(string iid)
----



Retrieves an ``IEntity`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IEntity >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetEntity(iid).Resolve();
----

[#_Promise__IEntityType___TypeDB_Driver_Api_IConceptManager_GetEntityType___string_label_]
==== GetEntityType

[source,cs]
----
Promise< IEntityType > GetEntityType(string label)
----



Retrieves an ``IEntityType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IEntityType`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IEntityType >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetEntityType(label).Resolve();
----

[#_Promise__IRelation___TypeDB_Driver_Api_IConceptManager_GetRelation___string_iid_]
==== GetRelation

[source,cs]
----
Promise< IRelation > GetRelation(string iid)
----



Retrieves a ``IRelation`` by its iid.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IRelation >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetRelation(iid).Resolve();
----

[#_Promise__IRelationType___TypeDB_Driver_Api_IConceptManager_GetRelationType___string_label_]
==== GetRelationType

[source,cs]
----
Promise< IRelationType > GetRelationType(string label)
----



Retrieves a ``IRelationType`` by its label.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IRelationType`` to retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IRelationType >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetRelationType(label).Resolve();
----

[#_IList__TypeDBException___TypeDB_Driver_Api_IConceptManager_GetSchemaExceptions___]
==== GetSchemaExceptions

[source,cs]
----
IList< TypeDBException > GetSchemaExceptions()
----



A list of all schema exceptions for the current transaction.


[caption=""]
.Returns
`IList< TypeDBException >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.GetSchemaExceptions();
----

[#_Promise__IAttributeType___TypeDB_Driver_Api_IConceptManager_PutAttributeType___string_label__IValue_ValueType_valueType_]
==== PutAttributeType

[source,cs]
----
Promise< IAttributeType > PutAttributeType(string label, IValue.ValueType valueType)
----



Creates a new ``IAttributeType`` if none exists with the given label, or retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IAttributeType`` to create or retrieve. a| `string`
a| `valueType` a| The value type of the ``IAttributeType`` to create. a| `IValue​.ValueType`
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[caption=""]
.Code examples
[source,cs]
----
await transaction.Concepts.PutAttributeType(label, valueType).Resolve();
----

[#_Promise__IEntityType___TypeDB_Driver_Api_IConceptManager_PutEntityType___string_label_]
==== PutEntityType

[source,cs]
----
Promise< IEntityType > PutEntityType(string label)
----



Creates a new ``IEntityType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IEntityType`` to create or retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IEntityType >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.PutEntityType(label).Resolve();
----

[#_Promise__IRelationType___TypeDB_Driver_Api_IConceptManager_PutRelationType___string_label_]
==== PutRelationType

[source,cs]
----
Promise< IRelationType > PutRelationType(string label)
----



Creates a new ``IRelationType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IRelationType`` to create or retrieve. a| `string`
|===

[caption=""]
.Returns
`Promise< IRelationType >`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.PutRelationType(label).Resolve();
----

[#_IAttributeType_TypeDB_Driver_Api_IConceptManager_RootAttributeType]
==== RootAttributeType

[source,cs]
----
IAttributeType TypeDB.Driver.Api.IConceptManager.RootAttributeType
----



The root ``IAttributeType``, “attribute”.


[caption=""]
.Returns
`IAttributeType`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.RootAttributeType;
----

[#_IEntityType_TypeDB_Driver_Api_IConceptManager_RootEntityType]
==== RootEntityType

[source,cs]
----
IEntityType TypeDB.Driver.Api.IConceptManager.RootEntityType
----



The root ``IEntityType``, “entity”.


[caption=""]
.Returns
`IEntityType`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.RootEntityType;
----

[#_IRelationType_TypeDB_Driver_Api_IConceptManager_RootRelationType]
==== RootRelationType

[source,cs]
----
IRelationType TypeDB.Driver.Api.IConceptManager.RootRelationType
----



The root ``IRelationType``, “relation”.


[caption=""]
.Returns
`IRelationType`

[caption=""]
.Code examples
[source,cs]
----
transaction.Concepts.RootRelationType;
----

// end::methods[]

