[#_IConceptManager]
=== IConceptManager

*Package*: `TypeDB.Driver.Api`



Provides access for all Concept API methods.

// tag::methods[]
[#_Promise__IAttribute___TypeDB_Driver_Api_IConceptManager_GetAttribute___string_iid_]
==== GetAttribute

[source,csharp]
----
Promise< IAttribute > GetAttribute(string iid)
----



Retrieves an ``IAttribute`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IAttribute >`

[#_Promise__IAttributeType___TypeDB_Driver_Api_IConceptManager_GetAttributeType___string_label_]
==== GetAttributeType

[source,csharp]
----
Promise< IAttributeType > GetAttributeType(string label)
----



Retrieves an ``IAttributeType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[#_Promise__IEntity___TypeDB_Driver_Api_IConceptManager_GetEntity___string_iid_]
==== GetEntity

[source,csharp]
----
Promise< IEntity > GetEntity(string iid)
----



Retrieves an ``IEntity`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IEntity >`

[#_Promise__IEntityType___TypeDB_Driver_Api_IConceptManager_GetEntityType___string_label_]
==== GetEntityType

[source,csharp]
----
Promise< IEntityType > GetEntityType(string label)
----



Retrieves an ``IEntityType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IEntityType`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IEntityType >`

[#_Promise__IRelation___TypeDB_Driver_Api_IConceptManager_GetRelation___string_iid_]
==== GetRelation

[source,csharp]
----
Promise< IRelation > GetRelation(string iid)
----



Retrieves a ``IRelation`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IRelation >`

[#_Promise__IRelationType___TypeDB_Driver_Api_IConceptManager_GetRelationType___string_label_]
==== GetRelationType

[source,csharp]
----
Promise< IRelationType > GetRelationType(string label)
----



Retrieves a ``IRelationType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IRelationType`` to retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IRelationType >`

[#_IList__TypeDBException___TypeDB_Driver_Api_IConceptManager_GetSchemaExceptions___]
==== GetSchemaExceptions

[source,csharp]
----
IList< TypeDBException > GetSchemaExceptions()
----



A list of all schema exceptions for the current transaction.


[caption=""]
.Returns
`IList< TypeDBException >`

[#_Promise__IAttributeType___TypeDB_Driver_Api_IConceptManager_PutAttributeType___string_label__IValue_ValueType_valueType_]
==== PutAttributeType

[source,csharp]
----
Promise< IAttributeType > PutAttributeType(string label, IValue.ValueType valueType)
----



Creates a new ``IAttributeType`` if none exists with the given label, or retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IAttributeType`` to create or retrieve. a| 
a| `valueType` a| The value type of the ``IAttributeType`` to create. a| 
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[#_Promise__IEntityType___TypeDB_Driver_Api_IConceptManager_PutEntityType___string_label_]
==== PutEntityType

[source,csharp]
----
Promise< IEntityType > PutEntityType(string label)
----



Creates a new ``IEntityType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IEntityType`` to create or retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IEntityType >`

[#_Promise__IRelationType___TypeDB_Driver_Api_IConceptManager_PutRelationType___string_label_]
==== PutRelationType

[source,csharp]
----
Promise< IRelationType > PutRelationType(string label)
----



Creates a new ``IRelationType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``IRelationType`` to create or retrieve. a| 
|===

[caption=""]
.Returns
`Promise< IRelationType >`

// end::methods[]

