[#_struct_ConceptManager]
=== ConceptManager

*Implements traits:*

* `Debug`

Provides access for all Concept API methods.

// tag::methods[]
[#_struct_ConceptManager_get_attribute__iid_IID]
==== get_attribute

[source,rust]
----
pub fn get_attribute(
    &self,
    iid: IID
) -> impl Promise<'tx, Result<Option<Attribute>>>
----

Retrieves an ``Attribute`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `IID`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<Attribute>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_attribute(iid).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_attribute(iid).resolve()
----

--
====

[#_struct_ConceptManager_get_attribute_type__label_String]
==== get_attribute_type

[source,rust]
----
pub fn get_attribute_type(
    &self,
    label: String
) -> impl Promise<'tx, Result<Option<AttributeType>>>
----

Retrieves an ``AttributeType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<AttributeType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_attribute_type(label).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_attribute_type(label).resolve()
----

--
====

[#_struct_ConceptManager_get_entity__iid_IID]
==== get_entity

[source,rust]
----
pub fn get_entity(&self, iid: IID) -> impl Promise<'tx, Result<Option<Entity>>>
----

Retrieves an ``Entity`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `IID`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<Entity>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_entity(iid).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_entity(iid).resolve()
----

--
====

[#_struct_ConceptManager_get_entity_type__label_String]
==== get_entity_type

[source,rust]
----
pub fn get_entity_type(
    &self,
    label: String
) -> impl Promise<'tx, Result<Option<EntityType>>>
----

Retrieves an ``EntityType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<EntityType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_entity_type(label).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_entity_type(label).resolve()
----

--
====

[#_struct_ConceptManager_get_relation__iid_IID]
==== get_relation

[source,rust]
----
pub fn get_relation(
    &self,
    iid: IID
) -> impl Promise<'tx, Result<Option<Relation>>>
----

Retrieves a ``Relation`` by its iid.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `IID`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<Relation>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_relation(iid).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_relation(iid).resolve()
----

--
====

[#_struct_ConceptManager_get_relation_type__label_String]
==== get_relation_type

[source,rust]
----
pub fn get_relation_type(
    &self,
    label: String
) -> impl Promise<'tx, Result<Option<RelationType>>>
----

Retrieves a ``RelationType`` by its label.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<Option<RelationType>>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().get_relation_type(label).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().get_relation_type(label).resolve()
----

--
====

[#_struct_ConceptManager_get_schema_exceptions__]
==== get_schema_exceptions

[source,rust]
----
pub fn get_schema_exceptions(
    &self
) -> Result<impl Stream<Item = Result<SchemaException>> + 'tx>
----

Retrieves a list of all schema exceptions for the current transaction.

[caption=""]
.Returns
[source,rust]
----
Result<impl Stream<Item = Result<SchemaException>> + 'tx>
----

[caption=""]
.Code examples
[source,rust]
----
transaction.concepts().get_schema_exceptions()
----

[#_struct_ConceptManager_put_attribute_type__label_String__value_type_ValueType]
==== put_attribute_type

[source,rust]
----
pub fn put_attribute_type(
    &self,
    label: String,
    value_type: ValueType
) -> impl Promise<'tx, Result<AttributeType>>
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one. or retrieve. :return:

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `String`
a| `value_type` a| The value type of the ``AttributeType`` to create a| `ValueType`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<AttributeType>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().put_attribute_type(label, value_type).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().put_attribute_type(label, value_type).resolve()
----

--
====

[#_struct_ConceptManager_put_entity_type__label_String]
==== put_entity_type

[source,rust]
----
pub fn put_entity_type(
    &self,
    label: String
) -> impl Promise<'tx, Result<EntityType>>
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<EntityType>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().put_entity_type(label).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().put_entity_type(label).resolve()
----

--
====

[#_struct_ConceptManager_put_relation_type__label_String]
==== put_relation_type

[source,rust]
----
pub fn put_relation_type(
    &self,
    label: String
) -> impl Promise<'tx, Result<RelationType>>
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `String`
|===

[caption=""]
.Returns
[source,rust]
----
impl Promise<'tx, Result<RelationType>>
----

[caption=""]
.Code examples
[tabs]
====
async::
+
--
[source,rust]
----
transaction.concepts().put_relation_type(label).await
----

--

sync::
+
--
[source,rust]
----
transaction.concepts().put_relation_type(label).resolve()
----

--
====

// end::methods[]

