[#_Concept]
[.doc-api-reference-driver]
=== Concept

`class`

*Package*: `com.typedb.driver.api.concept`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `DECIMAL_SCALE` a| `static int` a| 
|===
// end::properties[]

// tag::methods[]
[#_Concept_asAttribute_]
===== method ``asAttribute``

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Concept_asAttributeType_]
===== method ``asAttributeType``

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Concept_asEntity_]
===== method ``asEntity``

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Concept_asEntityType_]
===== method ``asEntityType``

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Concept_asInstance_]
===== method ``asInstance``

[source,java]
----
default Instance asInstance()
----

Casts the concept to ``Instance``. 


[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,java]
----
concept.asInstance();
----

[#_Concept_asRelation_]
===== method ``asRelation``

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Concept_asRelationType_]
===== method ``asRelationType``

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Concept_asRoleType_]
===== method ``asRoleType``

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Concept_asType_]
===== method ``asType``

[source,java]
----
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Concept_asValue_]
===== method ``asValue``

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Concept_getLabel_]
===== method ``getLabel``

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Concept_isAttribute_]
===== method ``isAttribute``

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Concept_isAttributeType_]
===== method ``isAttributeType``

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Concept_isBoolean_]
===== method ``isBoolean``

[source,java]
----
@CheckReturnValue
boolean isBoolean()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isBoolean()
----

[#_Concept_isDate_]
===== method ``isDate``

[source,java]
----
@CheckReturnValue
boolean isDate()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDate();
----

[#_Concept_isDatetime_]
===== method ``isDatetime``

[source,java]
----
@CheckReturnValue
boolean isDatetime()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetime();
----

[#_Concept_isDatetimeTZ_]
===== method ``isDatetimeTZ``

[source,java]
----
@CheckReturnValue
boolean isDatetimeTZ()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetimeTZ();
----

[#_Concept_isDecimal_]
===== method ``isDecimal``

[source,java]
----
@CheckReturnValue
boolean isDecimal()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDecimal();
----

[#_Concept_isDouble_]
===== method ``isDouble``

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDouble();
----

[#_Concept_isDuration_]
===== method ``isDuration``

[source,java]
----
@CheckReturnValue
boolean isDuration()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDuration();
----

[#_Concept_isEntity_]
===== method ``isEntity``

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Concept_isEntityType_]
===== method ``isEntityType``

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Concept_isInstance_]
===== method ``isInstance``

[source,java]
----
@CheckReturnValue
default boolean isInstance()
----

Checks if the concept is an ``Instance``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInstance();
----

[#_Concept_isInteger_]
===== method ``isInteger``

[source,java]
----
@CheckReturnValue
boolean isInteger()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInteger();
----

[#_Concept_isRelation_]
===== method ``isRelation``

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Concept_isRelationType_]
===== method ``isRelationType``

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Concept_isRoleType_]
===== method ``isRoleType``

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Concept_isString_]
===== method ``isString``

[source,java]
----
@CheckReturnValue
boolean isString()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isString();
----

[#_Concept_isStruct_]
===== method ``isStruct``

[source,java]
----
@CheckReturnValue
boolean isStruct()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isStruct();
----

[#_Concept_isType_]
===== method ``isType``

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Concept_isValue_]
===== method ``isValue``

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Concept_tryGetBoolean_]
===== method ``tryGetBoolean``

[source,java]
----
java.util.Optional<java.lang.Boolean> tryGetBoolean()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetBoolean();
----

[#_Concept_tryGetDate_]
===== method ``tryGetDate``

[source,java]
----
java.util.Optional<java.time.LocalDate> tryGetDate()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDate>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDate();
----

[#_Concept_tryGetDatetime_]
===== method ``tryGetDatetime``

[source,java]
----
java.util.Optional<java.time.LocalDateTime> tryGetDatetime()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetime();
----

[#_Concept_tryGetDatetimeTZ_]
===== method ``tryGetDatetimeTZ``

[source,java]
----
java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ()
----

Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.ZonedDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetimeTZ();
----

[#_Concept_tryGetDecimal_]
===== method ``tryGetDecimal``

[source,java]
----
java.util.Optional<java.math.BigDecimal> tryGetDecimal()
----

Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.math.BigDecimal>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDecimal();
----

[#_Concept_tryGetDouble_]
===== method ``tryGetDouble``

[source,java]
----
java.util.Optional<java.lang.Double> tryGetDouble()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Double>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDouble();
----

[#_Concept_tryGetDuration_]
===== method ``tryGetDuration``

[source,java]
----
java.util.Optional<Duration> tryGetDuration()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<Duration>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDuration();
----

[#_Concept_tryGetIID_]
===== method ``tryGetIID``

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID()
----

Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetIID();
----

[#_Concept_tryGetInteger_]
===== method ``tryGetInteger``

[source,java]
----
java.util.Optional<java.lang.Long> tryGetInteger()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Long>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetInteger();
----

[#_Concept_tryGetLabel_]
===== method ``tryGetLabel``

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLabel();
----

[#_Concept_tryGetString_]
===== method ``tryGetString``

[source,java]
----
java.util.Optional<java.lang.String> tryGetString()
----

Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetString();
----

[#_Concept_tryGetStruct_]
===== method ``tryGetStruct``

[source,java]
----
java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetStruct();
----

[#_Concept_tryGetValue_]
===== method ``tryGetValue``

[source,java]
----
@CheckReturnValue
java.util.Optional<Value> tryGetValue()
----

Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 


[caption=""]
.Returns
`java.util.Optional<Value>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValue();
----

[#_Concept_tryGetValueType_]
===== method ``tryGetValueType``

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType()
----

Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValueType();
----

// end::methods[]

