[#_ConceptManager]
=== ConceptManager

*Package*: `com.vaticle.typedb.driver.api.concept`

Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptManager_getAttribute__java_lang_String]
==== getAttribute

[source,java]
----
@CheckReturnValue
Promise<? extends Attribute> getAttribute​(java.lang.String iid)
----

Retrieves an ``Attribute`` by its iid. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends Attribute>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getAttribute(iid).resolve();
----

[#_ConceptManager_getAttributeType__java_lang_String]
==== getAttributeType

[source,java]
----
@CheckReturnValue
Promise<? extends AttributeType> getAttributeType​(java.lang.String label)
----

Retrieves an ``AttributeType`` by its label. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends AttributeType>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getAttributeType(label).resolve();
----

[#_ConceptManager_getEntity__java_lang_String]
==== getEntity

[source,java]
----
@CheckReturnValue
Promise<? extends Entity> getEntity​(java.lang.String iid)
----

Retrieves an ``Entity`` by its iid. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends Entity>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getEntity(iid).resolve();
----

[#_ConceptManager_getEntityType__java_lang_String]
==== getEntityType

[source,java]
----
@CheckReturnValue
Promise<? extends EntityType> getEntityType​(java.lang.String label)
----

Retrieves an ``EntityType`` by its label. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends EntityType>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getEntityType(label).resolve();
----

[#_ConceptManager_getRelation__java_lang_String]
==== getRelation

[source,java]
----
@CheckReturnValue
Promise<? extends Relation> getRelation​(java.lang.String iid)
----

Retrieves a ``Relation`` by its iid. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends Relation>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRelation(iid).resolve();
----

[#_ConceptManager_getRelationType__java_lang_String]
==== getRelationType

[source,java]
----
@CheckReturnValue
Promise<? extends RelationType> getRelationType​(java.lang.String label)
----

Retrieves a ``RelationType`` by its label. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends RelationType>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRelationType(label).resolve();
----

[#_ConceptManager_getRootAttributeType__]
==== getRootAttributeType

[source,java]
----
@CheckReturnValue
AttributeType getRootAttributeType()
----

Retrieve the root ``AttributeType``, “attribute”. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootAttributeType();
----

[#_ConceptManager_getRootEntityType__]
==== getRootEntityType

[source,java]
----
@CheckReturnValue
EntityType getRootEntityType()
----

Retrieves the root ``EntityType``, “entity”. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootEntityType();
----

[#_ConceptManager_getRootRelationType__]
==== getRootRelationType

[source,java]
----
@CheckReturnValue
RelationType getRootRelationType()
----

Retrieve the root ``RelationType``, “relation”. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootRelationType();
----

[#_ConceptManager_getSchemaExceptions__]
==== getSchemaExceptions

[source,java]
----
@CheckReturnValue
java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException> getSchemaExceptions()
----

Retrieves a list of all schema exceptions for the current transaction. 


[caption=""]
.Returns
`java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getSchemaException();
----

[#_ConceptManager_putAttributeType__java_lang_String__Value_Type]
==== putAttributeType

[source,java]
----
@CheckReturnValue
Promise<? extends AttributeType> putAttributeType​(java.lang.String label,
                                                  Value.Type valueType)
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `java.lang.String`
a| `valueType` a| The value type of the ``AttributeType`` to create a| `Value.Type`
|===

[caption=""]
.Returns
`Promise<? extends AttributeType>`

[caption=""]
.Code examples
[source,java]
----
await transaction.concepts().putAttributeType(label, valueType).resolve();
----

[#_ConceptManager_putEntityType__java_lang_String]
==== putEntityType

[source,java]
----
@CheckReturnValue
Promise<? extends EntityType> putEntityType​(java.lang.String label)
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends EntityType>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().putEntityType(label).resolve();
----

[#_ConceptManager_putRelationType__java_lang_String]
==== putRelationType

[source,java]
----
@CheckReturnValue
Promise<? extends RelationType> putRelationType​(java.lang.String label)
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<? extends RelationType>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().putRelationType(label).resolve();
----

// end::methods[]

