[#_AttributeType]
=== AttributeType

*Supertypes:*

* `ThingType`

Attribute types represent properties that other types can own. Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type. Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value. Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

[caption=""]
.Namespace variables
// tag::enum_constants[]
[cols="~"]
[options="header"]
|===
|Name
a| `NAME`
|===
// end::enum_constants[]

// tag::methods[]
[#_AttributeType_asAttributeasAttribute__:_Attribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_AttributeType_asAttributeTypeasAttributeType__:_AttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_AttributeType_asEntityasEntity__:_Entity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_AttributeType_asEntityTypeasEntityType__:_EntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_AttributeType_asRelationasRelation__:_Relation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_AttributeType_asRelationTypeasRelationType__:_RelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_AttributeType_asRoleTypeasRoleType__:_RoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_AttributeType_asThingasThing__:_Thing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_AttributeType_asThingTypeasThingType__:_ThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_AttributeType_asTypeasType__:_Type]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_AttributeType_asValueasValue__:_Value]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_AttributeType_deletedelete_transaction_:_Promise_void]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.delete(transaction)
----

[#_AttributeType_equalsequals_concept_:_boolean]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_AttributeType_getget_transaction__value_:_Promise_Attribute]
==== get

[source,nodejs]
----
get(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getBooleangetBoolean_transaction__value_:_Promise_Attribute]
==== getBoolean

[source,nodejs]
----
getBoolean(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `boolean`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getDateTimegetDateTime_transaction__value_:_Promise_Attribute]
==== getDateTime

[source,nodejs]
----
getDateTime(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `Date`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getDoublegetDouble_transaction__value_:_Promise_Attribute]
==== getDouble

[source,nodejs]
----
getDouble(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `number`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getInstancesgetInstances_transaction__transitivity_:_Stream_Attribute]
==== getInstances

[source,nodejs]
----
getInstances(transaction, transitivity): Stream<Attribute>
----

Retrieves all direct and indirect (or direct only) ``Attributes`` that are instances of this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attributeType.getInstances(transaction) attributeType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_AttributeType_getInstancesgetInstances_transaction_:_Stream_Attribute]
==== getInstances

[source,nodejs]
----
getInstances(transaction): Stream<Attribute>
----

Retrieves all direct and indirect (or direct only) ``Thing`` objects that are instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_AttributeType_getLonggetLong_transaction__value_:_Promise_Attribute]
==== getLong

[source,nodejs]
----
getLong(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `number`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getOwnersgetOwners_transaction__annotations__transitivity_:_Stream_ThingType]
==== getOwners

[source,nodejs]
----
getOwners(transaction, annotations, transitivity): Stream<ThingType>
----

Retrieve all ``Things`` that own an attribute of this ``AttributeType``. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``AttributeType`` with all given ``Annotation``s a| `Annotation[]`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<ThingType>`

[caption=""]
.Code examples
[source,nodejs]
----
attributeType.getOwners(transaction) attributeType.getOwners(transaction, [Annotation.UNIQUE]) attributeType.getOwners(transaction, Transitivity.TRANSITIVE) attributeType.getOwners(transaction, [Annotation.UNIQUE], Transitivity.TRANSITIVE)
----

[#_AttributeType_getOwnersgetOwners_transaction_:_Stream_ThingType]
==== getOwners

[source,nodejs]
----
getOwners(transaction): Stream<ThingType>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<ThingType>`

[#_AttributeType_getOwnersgetOwners_transaction__annotations_:_Stream_ThingType]
==== getOwners

[source,nodejs]
----
getOwners(transaction, annotations): Stream<ThingType>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `annotations` a|  a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<ThingType>`

[#_AttributeType_getOwnersgetOwners_transaction__transitivity_:_Stream_ThingType]
==== getOwners

[source,nodejs]
----
getOwners(transaction, transitivity): Stream<ThingType>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `transitivity` a|  a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<ThingType>`

[#_AttributeType_getOwnsgetOwns_transaction_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__valueType_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__annotations_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__valueType__annotations_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__valueType__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__annotations__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsgetOwns_transaction__valueType__annotations__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_AttributeType_getOwnsOverriddengetOwnsOverridden_transaction__attributeType_:_Promise_AttributeType]
==== getOwnsOverridden

[source,nodejs]
----
getOwnsOverridden(transaction, attributeType): Promise<AttributeType>
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwnsOverridden(transaction, attributeType)
----

[#_AttributeType_getPlaysgetPlays_transaction_:_Stream_RoleType]
==== getPlays

[source,nodejs]
----
getPlays(transaction): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_AttributeType_getPlaysgetPlays_transaction__transitivity_:_Stream_RoleType]
==== getPlays

[source,nodejs]
----
getPlays(transaction, transitivity): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_AttributeType_getPlaysOverriddengetPlaysOverridden_transaction__role_:_Promise_RoleType]
==== getPlaysOverridden

[source,nodejs]
----
getPlaysOverridden(transaction, role): Promise<RoleType>
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The ``RoleType`` that overrides an inherited role a| `RoleType`
|===

[caption=""]
.Returns
`Promise<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlaysOverridden(transaction, role)
----

[#_AttributeType_getRegexgetRegex_transaction_:_Promise_string]
==== getRegex

[source,nodejs]
----
getRegex(transaction): Promise<string>
----

Retrieves the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<string>`

[caption=""]
.Code examples
[source,nodejs]
----
attributeType.getRegex(transaction)
----

[#_AttributeType_getStringgetString_transaction__value_:_Promise_Attribute]
==== getString

[source,nodejs]
----
getString(transaction, value): Promise<Attribute>
----

Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``None``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| ``Attribute``’s value a| `string`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_AttributeType_getSubtypesgetSubtypes_transaction_:_Stream_AttributeType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction): Stream<AttributeType>
----

Retrieves all direct and indirect subtypes of the ``ThingType``. Equivalent to getSubtypes(transaction, Transitivity.TRANSITIVE)

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction)
----

[#_AttributeType_getSubtypesgetSubtypes_transaction__valueType_:_Stream_AttributeType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, valueType): Stream<AttributeType>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `ValueType`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_AttributeType_getSubtypesgetSubtypes_transaction__transitivity_:_Stream_AttributeType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, transitivity): Stream<AttributeType>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `transitivity` a|  a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[#_AttributeType_getSubtypesgetSubtypes_transaction__valueType__transitivity_:_Stream_AttributeType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, valueType, transitivity): Stream<AttributeType>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `valueType` a|  a| `ValueType`
a| `transitivity` a|  a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[#_AttributeType_getSupertypegetSupertype_transaction_:_Promise_AttributeType]
==== getSupertype

[source,nodejs]
----
getSupertype(transaction): Promise<AttributeType>
----

Retrieves the most immediate supertype of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertype(transaction)
----

[#_AttributeType_getSupertypesgetSupertypes_transaction_:_Stream_AttributeType]
==== getSupertypes

[source,nodejs]
----
getSupertypes(transaction): Stream<AttributeType>
----

Retrieves all supertypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertypes(transaction)
----

[#_AttributeType_getSyntaxgetSyntax_transaction_:_Promise_string]
==== getSyntax

[source,nodejs]
----
getSyntax(transaction): Promise<string>
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<string>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSyntax(transaction)
----

[#_AttributeType_isAttributeisAttribute__:_boolean]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_AttributeType_isAttributeTypeisAttributeType__:_boolean]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_AttributeType_isDeletedisDeleted_transaction_:_Promise_boolean]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Check if the concept has been deleted

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[#_AttributeType_isEntityisEntity__:_boolean]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_AttributeType_isEntityTypeisEntityType__:_boolean]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_AttributeType_isRelationisRelation__:_boolean]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_AttributeType_isRelationTypeisRelationType__:_boolean]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_AttributeType_isRoleTypeisRoleType__:_boolean]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_AttributeType_isThingisThing__:_boolean]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_AttributeType_isThingTypeisThingType__:_boolean]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_AttributeType_isTypeisType__:_boolean]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_AttributeType_isValueisValue__:_boolean]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_AttributeType_putput_transaction__value_:_Promise_Attribute]
==== put

[source,nodejs]
----
put(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `Value`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_putBooleanputBoolean_transaction__value_:_Promise_Attribute]
==== putBoolean

[source,nodejs]
----
putBoolean(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `boolean`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_putDateTimeputDateTime_transaction__value_:_Promise_Attribute]
==== putDateTime

[source,nodejs]
----
putDateTime(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `Date`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_putDoubleputDouble_transaction__value_:_Promise_Attribute]
==== putDouble

[source,nodejs]
----
putDouble(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `number`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_putLongputLong_transaction__value_:_Promise_Attribute]
==== putLong

[source,nodejs]
----
putLong(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `number`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_putStringputString_transaction__value_:_Promise_Attribute]
==== putString

[source,nodejs]
----
putString(transaction, value): Promise<Attribute>
----

Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `value` a| New ``Attribute``’s value a| `string`
|===

[caption=""]
.Returns
`Promise<Attribute>`

[caption=""]
.Code examples
[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_AttributeType_setAbstractsetAbstract_transaction_:_Promise_void]
==== setAbstract

[source,nodejs]
----
setAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setAbstract(transaction)
----

[#_AttributeType_setLabelsetLabel_transaction__label_:_Promise_void]
==== setLabel

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `label` a| The new ``Label`` to be given to the type. a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.setLabel(transaction, label)
----

[#_AttributeType_setOwnssetOwns_transaction__attributeType_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_AttributeType_setOwnssetOwns_transaction__attributeType__annotations_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `annotations` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_AttributeType_setOwnssetOwns_transaction__attributeType__overriddenType_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_AttributeType_setOwnssetOwns_transaction__attributeType__overriddenType__annotations_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
a| `annotations` a| Adds annotations to the ownership. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_AttributeType_setPlayssetPlays_transaction__role_:_Promise_void]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_AttributeType_setPlayssetPlays_transaction__role__overriddenType_:_Promise_void]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
a| `overriddenType` a| The role type that this role overrides, if applicable a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_AttributeType_setRegexsetRegex_transaction__regex_:_Promise_void]
==== setRegex

[source,nodejs]
----
setRegex(transaction, regex): Promise<void>
----

Sets a regular expression as a constraint for this ``AttributeType``. ``Values`` of all ``Attribute``s of this type (inserted earlier or later) should match this regex. Can only be applied for ``AttributeType``s with a ``string`` value type.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `regex` a| Regular expression a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
attributeType.setRegex(transaction, regex)
----

[#_AttributeType_setSupertypesetSupertype_transaction__type_:_Promise_void]
==== setSupertype

[source,nodejs]
----
setSupertype(transaction, type): Promise<void>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `type` a|  a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[#_AttributeType_toJSONRecordtoJSONRecord__:_Record_string__string_|_number_|_boolean]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

[caption=""]
.Returns
`Record<string, string | number | boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

[#_AttributeType_unsetAbstractunsetAbstract_transaction_:_Promise_void]
==== unsetAbstract

[source,nodejs]
----
unsetAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetAbstract(transaction)
----

[#_AttributeType_unsetOwnsunsetOwns_transaction__attributeType_:_Promise_void]
==== unsetOwns

[source,nodejs]
----
unsetOwns(transaction, attributeType): Promise<void>
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetOwns(transaction, attributeType)
----

[#_AttributeType_unsetPlaysunsetPlays_transaction__role_:_Promise_void]
==== unsetPlays

[source,nodejs]
----
unsetPlays(transaction, role): Promise<void>
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to not be played by the instances of this type. a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetPlays(transaction, role)
----

[#_AttributeType_unsetRegexunsetRegex_transaction_:_Promise_void]
==== unsetRegex

[source,nodejs]
----
unsetRegex(transaction): Promise<void>
----

Removes the regular expression that is defined for this ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
attributeType.unsetRegex(transaction)
----

// end::methods[]

