[#_EntityType]
=== EntityType

*Supertypes:*

* `ThingType`

[caption=""]
.Namespace variables
// tag::enum_constants[]
[cols="~"]
[options="header"]
|===
|Name
a| `NAME`
|===
// end::enum_constants[]

// tag::methods[]
[#_EntityType_asAttributeasAttribute__:_Attribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_EntityType_asAttributeTypeasAttributeType__:_AttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_EntityType_asEntityasEntity__:_Entity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_EntityType_asEntityTypeasEntityType__:_EntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_EntityType_asRelationasRelation__:_Relation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_EntityType_asRelationTypeasRelationType__:_RelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_EntityType_asRoleTypeasRoleType__:_RoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_EntityType_asThingasThing__:_Thing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_EntityType_asThingTypeasThingType__:_ThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_EntityType_asTypeasType__:_Type]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_EntityType_asValueasValue__:_Value]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_EntityType_createcreate_transaction_:_Promise_Entity]
==== create

[source,nodejs]
----
create(transaction): Promise<Entity>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<Entity>`

[#_EntityType_deletedelete_transaction_:_Promise_void]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.delete(transaction)
----

[#_EntityType_equalsequals_concept_:_boolean]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_EntityType_getInstancesgetInstances_transaction_:_Stream_Entity]
==== getInstances

[source,nodejs]
----
getInstances(transaction): Stream<Entity>
----

Retrieves all direct and indirect ``Thing`` objects that are instances of this ``ThingType``. Equivalent to getInstances(transaction, Transitivity.TRANSITIVE)

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Entity>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getInstances(transaction)
----

[#_EntityType_getInstancesgetInstances_transaction__transitivity_:_Stream_Entity]
==== getInstances

[source,nodejs]
----
getInstances(transaction, transitivity): Stream<Entity>
----

Retrieves all direct and indirect (or direct only) ``Thing`` objects that are instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct instances only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<Entity>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_EntityType_getOwnsgetOwns_transaction_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__valueType_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__annotations_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__valueType__annotations_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__valueType__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__annotations__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsgetOwns_transaction__valueType__annotations__transitivity_:_Stream_AttributeType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_EntityType_getOwnsOverriddengetOwnsOverridden_transaction__attributeType_:_Promise_AttributeType]
==== getOwnsOverridden

[source,nodejs]
----
getOwnsOverridden(transaction, attributeType): Promise<AttributeType>
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwnsOverridden(transaction, attributeType)
----

[#_EntityType_getPlaysgetPlays_transaction_:_Stream_RoleType]
==== getPlays

[source,nodejs]
----
getPlays(transaction): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_EntityType_getPlaysgetPlays_transaction__transitivity_:_Stream_RoleType]
==== getPlays

[source,nodejs]
----
getPlays(transaction, transitivity): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_EntityType_getPlaysOverriddengetPlaysOverridden_transaction__role_:_Promise_RoleType]
==== getPlaysOverridden

[source,nodejs]
----
getPlaysOverridden(transaction, role): Promise<RoleType>
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The ``RoleType`` that overrides an inherited role a| `RoleType`
|===

[caption=""]
.Returns
`Promise<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlaysOverridden(transaction, role)
----

[#_EntityType_getSubtypesgetSubtypes_transaction_:_Stream_EntityType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction): Stream<EntityType>
----

Retrieves all direct and indirect subtypes of the ``ThingType``. Equivalent to getSubtypes(transaction, Transitivity.TRANSITIVE)

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction)
----

[#_EntityType_getSubtypesgetSubtypes_transaction__transitivity_:_Stream_EntityType]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, transitivity): Stream<EntityType>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_EntityType_getSupertypegetSupertype_transaction_:_Promise_EntityType]
==== getSupertype

[source,nodejs]
----
getSupertype(transaction): Promise<EntityType>
----

Retrieves the most immediate supertype of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertype(transaction)
----

[#_EntityType_getSupertypesgetSupertypes_transaction_:_Stream_EntityType]
==== getSupertypes

[source,nodejs]
----
getSupertypes(transaction): Stream<EntityType>
----

Retrieves all supertypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<EntityType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertypes(transaction)
----

[#_EntityType_getSyntaxgetSyntax_transaction_:_Promise_string]
==== getSyntax

[source,nodejs]
----
getSyntax(transaction): Promise<string>
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<string>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSyntax(transaction)
----

[#_EntityType_isAttributeisAttribute__:_boolean]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_EntityType_isAttributeTypeisAttributeType__:_boolean]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_EntityType_isDeletedisDeleted_transaction_:_Promise_boolean]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Check if the concept has been deleted

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[#_EntityType_isEntityisEntity__:_boolean]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_EntityType_isEntityTypeisEntityType__:_boolean]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_EntityType_isRelationisRelation__:_boolean]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_EntityType_isRelationTypeisRelationType__:_boolean]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_EntityType_isRoleTypeisRoleType__:_boolean]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_EntityType_isThingisThing__:_boolean]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_EntityType_isThingTypeisThingType__:_boolean]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_EntityType_isTypeisType__:_boolean]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_EntityType_isValueisValue__:_boolean]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_EntityType_setAbstractsetAbstract_transaction_:_Promise_void]
==== setAbstract

[source,nodejs]
----
setAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setAbstract(transaction)
----

[#_EntityType_setLabelsetLabel_transaction__label_:_Promise_void]
==== setLabel

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `label` a| The new ``Label`` to be given to the type. a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.setLabel(transaction, label)
----

[#_EntityType_setOwnssetOwns_transaction__attributeType_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_EntityType_setOwnssetOwns_transaction__attributeType__annotations_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `annotations` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_EntityType_setOwnssetOwns_transaction__attributeType__overriddenType_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_EntityType_setOwnssetOwns_transaction__attributeType__overriddenType__annotations_:_Promise_void]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
a| `annotations` a| Adds annotations to the ownership. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_EntityType_setPlayssetPlays_transaction__role_:_Promise_void]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_EntityType_setPlayssetPlays_transaction__role__overriddenType_:_Promise_void]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
a| `overriddenType` a| The role type that this role overrides, if applicable a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_EntityType_setSupertypesetSupertype_transaction__superEntityType_:_Promise_void]
==== setSupertype

[source,nodejs]
----
setSupertype(transaction, superEntityType): Promise<void>
----



[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `superEntityType` a|  a| `EntityType`
|===

[caption=""]
.Returns
`Promise<void>`

[#_EntityType_toJSONRecordtoJSONRecord__:_Record_string__string_|_number_|_boolean]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

[caption=""]
.Returns
`Record<string, string | number | boolean>`

[caption=""]
.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

[#_EntityType_unsetAbstractunsetAbstract_transaction_:_Promise_void]
==== unsetAbstract

[source,nodejs]
----
unsetAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetAbstract(transaction)
----

[#_EntityType_unsetOwnsunsetOwns_transaction__attributeType_:_Promise_void]
==== unsetOwns

[source,nodejs]
----
unsetOwns(transaction, attributeType): Promise<void>
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetOwns(transaction, attributeType)
----

[#_EntityType_unsetPlaysunsetPlays_transaction__role_:_Promise_void]
==== unsetPlays

[source,nodejs]
----
unsetPlays(transaction, role): Promise<void>
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to not be played by the instances of this type. a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetPlays(transaction, role)
----

// end::methods[]

