[#_RelationType]
=== RelationType

*Supertypes:*

* `ThingType`

[caption=""]
.Namespace variables
// tag::enum_constants[]
[cols=""]
[options="header"]
|===
|Name
a| `NAME`
|===
// end::enum_constants[]

// tag::methods[]
[#_RelationType_asAttribute__]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_RelationType_asAttributeType__]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_RelationType_asEntity__]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_RelationType_asEntityType__]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_RelationType_asRelation__]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_RelationType_asRelationType__]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_RelationType_asRoleType__]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_RelationType_asThing__]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_RelationType_asThingType__]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_RelationType_asType__]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_RelationType_asValue__]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_RelationType_create__transaction_TypeDBTransaction]
==== create

[source,nodejs]
----
create(transaction): Promise<Relation>
----

Creates and returns an instance of this ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.create(transaction)
----

[#_RelationType_delete__transaction_TypeDBTransaction]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.delete(transaction)
----

[#_RelationType_equals__concept_Concept]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_RelationType_getInstances__transaction_TypeDBTransaction]
==== getInstances

[source,nodejs]
----
getInstances(transaction): Stream<Relation>
----

Retrieves all direct and indirect ``Thing`` objects that are instances of this ``ThingType``. Equivalent to getInstances(transaction, Transitivity.TRANSITIVE)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getInstances(transaction)
----

[#_RelationType_getInstances__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getInstances

[source,nodejs]
----
getInstances(transaction, transitivity): Stream<Relation>
----

Retrieves all direct and indirect (or direct only) ``Thing`` objects that are instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect instances, ``Transitivity.EXPLICIT`` for direct instances only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<Relation>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_RelationType_getOwns__transaction_TypeDBTransaction]
==== getOwns

[source,nodejs]
----
getOwns(transaction): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__valueType_ValueType]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__annotations_Annotation__]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__valueType_ValueType__annotations_Annotation__]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getOwns

[source,nodejs]
----
getOwns(transaction, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__valueType_ValueType__transitivity_Transitivity]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__annotations_Annotation____transitivity_Transitivity]
==== getOwns

[source,nodejs]
----
getOwns(transaction, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `annotations` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `Annotation[]`
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwns__transaction_TypeDBTransaction__valueType_ValueType__annotations_Annotation____transitivity_Transitivity]
==== getOwns

[source,nodejs]
----
getOwns(transaction, valueType, annotations, transitivity): Stream<AttributeType>
----

Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited ownership, ``Transitivity.EXPLICIT`` for direct ownership only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_RelationType_getOwnsOverridden__transaction_TypeDBTransaction__attributeType_AttributeType]
==== getOwnsOverridden

[source,nodejs]
----
getOwnsOverridden(transaction, attributeType): Promise<AttributeType>
----

Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``attribute_type``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<AttributeType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getOwnsOverridden(transaction, attributeType)
----

[#_RelationType_getPlays__transaction_TypeDBTransaction]
==== getPlays

[source,nodejs]
----
getPlays(transaction): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_RelationType_getPlays__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getPlays

[source,nodejs]
----
getPlays(transaction, transitivity): Stream<RoleType>
----

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_RelationType_getPlaysOverridden__transaction_TypeDBTransaction__role_RoleType]
==== getPlaysOverridden

[source,nodejs]
----
getPlaysOverridden(transaction, role): Promise<RoleType>
----

Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The ``RoleType`` that overrides an inherited role a| `RoleType`
|===

[caption=""]
.Returns
`Promise<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getPlaysOverridden(transaction, role)
----

[#_RelationType_getRelates__transaction_TypeDBTransaction]
==== getRelates

[source,nodejs]
----
getRelates(transaction): Stream<RoleType>
----

RelationType#getRelates:(1)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[#_RelationType_getRelates__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getRelates

[source,nodejs]
----
getRelates(transaction, transitivity): Stream<RoleType>
----

Retrieves roles that this ``RelationType`` relates to directly or via inheritance. If ``role_label`` is given, returns a corresponding ``RoleType`` or ``None``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and inherited relates, ``Transitivity.EXPLICIT`` for direct relates only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.getRelates(transaction, roleLabel, transitivity)
----

[#_RelationType_getRelatesForRoleLabel__transaction_TypeDBTransaction__roleLabel_string]
==== getRelatesForRoleLabel

[source,nodejs]
----
getRelatesForRoleLabel(transaction, roleLabel): Promise<RoleType>
----



[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a|  a| `TypeDBTransaction`
a| `roleLabel` a|  a| `string`
|===

[caption=""]
.Returns
`Promise<RoleType>`

[#_RelationType_getRelatesOverridden__transaction_TypeDBTransaction__roleLabel_string]
==== getRelatesOverridden

[source,nodejs]
----
getRelatesOverridden(transaction, roleLabel): Promise<RoleType>
----

Retrieves a ``RoleType`` that is overridden by the role with the ``role_label``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| Label of the role that overrides an inherited role a| `string`
|===

[caption=""]
.Returns
`Promise<RoleType>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.getRelatesOverridden(transaction, roleLabel)
----

[#_RelationType_getSubtypes__transaction_TypeDBTransaction]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction): Stream<RelationType>
----

Retrieves all direct and indirect subtypes of the ``ThingType``. Equivalent to getSubtypes(transaction, Transitivity.TRANSITIVE)

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction)
----

[#_RelationType_getSubtypes__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, transitivity): Stream<RelationType>
----

Retrieves all direct and indirect (or direct only) subtypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_RelationType_getSupertype__transaction_TypeDBTransaction]
==== getSupertype

[source,nodejs]
----
getSupertype(transaction): Promise<RelationType>
----

Retrieves the most immediate supertype of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertype(transaction)
----

[#_RelationType_getSupertypes__transaction_TypeDBTransaction]
==== getSupertypes

[source,nodejs]
----
getSupertypes(transaction): Stream<RelationType>
----

Retrieves all supertypes of the ``ThingType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<RelationType>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSupertypes(transaction)
----

[#_RelationType_getSyntax__transaction_TypeDBTransaction]
==== getSyntax

[source,nodejs]
----
getSyntax(transaction): Promise<string>
----

Produces a pattern for creating this ``ThingType`` in a ``define`` query.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<string>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.getSyntax(transaction)
----

[#_RelationType_isAttribute__]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_RelationType_isAttributeType__]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_RelationType_isDeleted__transaction_TypeDBTransaction]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Check if the concept has been deleted

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[#_RelationType_isEntity__]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_RelationType_isEntityType__]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_RelationType_isRelation__]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_RelationType_isRelationType__]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_RelationType_isRoleType__]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_RelationType_isThing__]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_RelationType_isThingType__]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_RelationType_isType__]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_RelationType_isValue__]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_RelationType_setAbstract__transaction_TypeDBTransaction]
==== setAbstract

[source,nodejs]
----
setAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be abstract, meaning it cannot have instances.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setAbstract(transaction)
----

[#_RelationType_setLabel__transaction_TypeDBTransaction__label_string]
==== setLabel

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `label` a| The new ``Label`` to be given to the type. a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.setLabel(transaction, label)
----

[#_RelationType_setOwns__transaction_TypeDBTransaction__attributeType_AttributeType]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_RelationType_setOwns__transaction_TypeDBTransaction__attributeType_AttributeType__annotations_Annotation__]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `annotations` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_RelationType_setOwns__transaction_TypeDBTransaction__attributeType_AttributeType__overriddenType_AttributeType]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_RelationType_setOwns__transaction_TypeDBTransaction__attributeType_AttributeType__overriddenType_AttributeType__annotations_Annotation__]
==== setOwns

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType, annotations): Promise<void>
----

Allows the instances of this ``ThingType`` to own the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType`
a| `annotations` a| Adds annotations to the ownership. a| `Annotation[]`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_RelationType_setPlays__transaction_TypeDBTransaction__role_RoleType]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_RelationType_setPlays__transaction_TypeDBTransaction__role_RoleType__overriddenType_RoleType]
==== setPlays

[source,nodejs]
----
setPlays(transaction, role, overriddenType): Promise<void>
----

Allows the instances of this ``ThingType`` to play the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to be played by the instances of this type a| `RoleType`
a| `overriddenType` a| The role type that this role overrides, if applicable a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_RelationType_setRelates__transaction_TypeDBTransaction__roleLabel_string__overriddenLabel_string]
==== setRelates

[source,nodejs]
----
setRelates(transaction, roleLabel, overriddenLabel?): Promise<void>
----

Sets the new role that this ``RelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| The new role for the ``RelationType`` to relate to a| `string`
a| `overriddenLabel` a| The label being overridden, if applicable a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.setRelates(transaction, roleLabel) relationType.setRelates(transaction, roleLabel, overriddenLabel)
----

[#_RelationType_setSupertype__transaction_TypeDBTransaction__type_RelationType]
==== setSupertype

[source,nodejs]
----
setSupertype(transaction, type): Promise<void>
----

Sets the supplied ``RelationType`` as the supertype of the current ``RelationType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `type` a|  a| `RelationType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.setSupertype(transaction, superRelationType).resolve();
----

[#_RelationType_unsetAbstract__transaction_TypeDBTransaction]
==== unsetAbstract

[source,nodejs]
----
unsetAbstract(transaction): Promise<void>
----

Set a ``ThingType`` to be non-abstract, meaning it can have instances.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetAbstract(transaction)
----

[#_RelationType_unsetOwns__transaction_TypeDBTransaction__attributeType_AttributeType]
==== unsetOwns

[source,nodejs]
----
unsetOwns(transaction, attributeType): Promise<void>
----

Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetOwns(transaction, attributeType)
----

[#_RelationType_unsetPlays__transaction_TypeDBTransaction__role_RoleType]
==== unsetPlays

[source,nodejs]
----
unsetPlays(transaction, role): Promise<void>
----

Disallows the instances of this ``ThingType`` from playing the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `role` a| The role to not be played by the instances of this type. a| `RoleType`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
thingType.unsetPlays(transaction, role)
----

[#_RelationType_unsetRelates__transaction_TypeDBTransaction__roleLabel_string]
==== unsetRelates

[source,nodejs]
----
unsetRelates(transaction, roleLabel): Promise<void>
----

Disallows this ``RelationType`` from relating to the given role.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `roleLabel` a| The role to not relate to the relation type. a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
relationType.unsetRelates(transaction, roleLabel)
----

// end::methods[]

