[#_Type]
=== Type

*Supertypes:*

* `Concept`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `abstract` a| `boolean` a| Whether the type is prevented from having data instances (i.e., abstract).
a| `label` a| `Label` a| The unique label of the type.
a| `root` a| `boolean` a| Whether the type is a root type.
|===
// end::properties[]

// tag::methods[]
[#_Type_asAttribute__]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_Type_asAttributeType__]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_Type_asEntity__]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_Type_asEntityType__]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_Type_asRelation__]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_Type_asRelationType__]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_Type_asRoleType__]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_Type_asThing__]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_Type_asThingType__]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_Type_asType__]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asType()
----

[#_Type_asValue__]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_Type_delete__transaction_TypeDBTransaction]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this type from the database.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.delete(transaction)
----

[#_Type_equals__concept_Concept]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept`
|===

[caption=""]
.Returns
`boolean`

[#_Type_getSubtypes__transaction_TypeDBTransaction]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction): Stream<Type>
----

Retrieves all direct and indirect (or direct only) subtypes of the type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Type>`

[caption=""]
.Code examples
[source,nodejs]
----
type.getSubtypes(transaction) type.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_Type_getSubtypes__transaction_TypeDBTransaction__transitivity_Transitivity]
==== getSubtypes

[source,nodejs]
----
getSubtypes(transaction, transitivity): Stream<Type>
----

Retrieves all direct and indirect (or direct only) subtypes of the type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| `Transitivity`
|===

[caption=""]
.Returns
`Stream<Type>`

[caption=""]
.Code examples
[source,nodejs]
----
type.getSubtypes(transaction) type.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_Type_getSupertype__transaction_TypeDBTransaction]
==== getSupertype

[source,nodejs]
----
getSupertype(transaction): Promise<Type>
----

Retrieves the most immediate supertype of the type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<Type>`

[caption=""]
.Code examples
[source,nodejs]
----
type.getSupertype(transaction)
----

[#_Type_getSupertypes__transaction_TypeDBTransaction]
==== getSupertypes

[source,nodejs]
----
getSupertypes(transaction): Stream<Type>
----

Retrieves all supertypes of the type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Stream<Type>`

[caption=""]
.Code examples
[source,nodejs]
----
type.getSupertypes(transaction)
----

[#_Type_isAttribute__]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_Type_isAttributeType__]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_Type_isDeleted__transaction_TypeDBTransaction]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Check if the concept has been deleted

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<boolean>`

[#_Type_isEntity__]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_Type_isEntityType__]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_Type_isRelation__]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_Type_isRelationType__]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_Type_isRoleType__]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_Type_isThing__]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_Type_isThingType__]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_Type_isType__]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isType()
----

[#_Type_isValue__]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_Type_setLabel__transaction_TypeDBTransaction__label_string]
==== setLabel

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

Renames the label of the type. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction`
a| `label` a| The new ``Label`` to be given to the type. a| `string`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
type.setLabel(transaction, label)
----

// end::methods[]

