[#_IThingType]
=== IThingType

*Package*: `TypeDB.Driver.Api`

*Supertypes:*

* `TypeDB.Driver.Api.IType`
* `TypeDB.Driver.Api.IConcept`

// tag::methods[]
[#_IThingType_IConcept_TypeDB_Driver_Api_IThingType_AsThingType_]
==== AsThingType

[source,cs]
----
IThingType IConcept. AsThingType()
----



Casts the concept to ``IThingType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`IThingType IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.AsThingType();
----

[#_IEnumerable_IThing_TypeDB_Driver_Api_IThingType_GetInstances_ITypeDBTransaction_transaction_]
==== GetInstances

[source,cs]
----
IEnumerable< IThing > GetInstances(ITypeDBTransaction transaction)
----



Retrieves all ``IThing`` objects that are instances of this ``IThingType`` or its subtypes. Equivalent to ``GetInstances(transaction, Transitive)``

 

See also
[source,cs]
----
 
 
IThingType::GetInstances(ITypeDBTransaction, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IThing >`

[#_IEnumerable_IThing_TypeDB_Driver_Api_IThingType_GetInstances_ITypeDBTransaction_transaction_IConcept_Transitivity_transitivity_]
==== GetInstances

[source,cs]
----
IEnumerable< IThing > GetInstances(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves ``IThing`` objects that are instances of this exact ``IThingType``, OR this ``IThingType`` and any of its subtypes


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `transitivity` a| ``Explicit`` for direct instances only, ``Transitive`` to include instances of subtypes a| `IConcept​.Transitivity`
|===

[caption=""]
.Returns
`IEnumerable< IThing >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetInstances(transaction);
thingType.GetInstances(transaction, Explicit);
----

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_IValue_ValueType_valueType_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, IValue.ValueType valueType)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_ICollection_Annotation_annotations_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, ICollection< Annotation > annotations)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_IValue_ValueType_valueType_ICollection_Annotation_annotations_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, ICollection< Annotation > annotations)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType?, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_IValue_ValueType_valueType_IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType?, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_ICollection_Annotation_annotations_IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.

 

See also
[source,cs]
----
 
 
IThingType::GetOwns(ITypeDBTransaction, IValue.ValueType, ICollection<Annotation>, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[#_IEnumerable_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwns_ITypeDBTransaction_transaction_IValue_ValueType_valueType_ICollection_Annotation_annotations_IConcept_Transitivity_transitivity_]
==== GetOwns

[source,cs]
----
IEnumerable< IAttributeType > GetOwns(ITypeDBTransaction transaction, IValue.ValueType? valueType, ICollection< Annotation > annotations, IConcept.Transitivity transitivity)
----



Retrieves ``IAttributeType`` that the instances of this ``IThingType`` are allowed to own directly or via inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `IValue​.ValueType?`
a| `transitivity` a| ``Transitive`` for direct and inherited ownership, ``Explicit`` for direct ownership only a| `IConcept​.Transitivity`
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `ICollection< Annotation >`
|===

[caption=""]
.Returns
`IEnumerable< IAttributeType >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetOwns(transaction);
thingType.GetOwns(transaction, valueType, Explicit, new []{NewKey()}));
----

[#_Promise_IAttributeType_TypeDB_Driver_Api_IThingType_GetOwnsOverridden_ITypeDBTransaction_transaction_IAttributeType_attributeType_]
==== GetOwnsOverridden

[source,cs]
----
Promise< IAttributeType > GetOwnsOverridden(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Retrieves an ``IAttributeType``, ownership of which is overridden for this ``IThingType`` by a given ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attributeType` a| The ``IAttributeType`` that overrides requested ``IAttributeType`` a| `IAttributeType`
|===

[caption=""]
.Returns
`Promise< IAttributeType >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetOwnsOverridden(transaction, attributeType).Resolve();
----

[#_IEnumerable_IRoleType_TypeDB_Driver_Api_IThingType_GetPlays_ITypeDBTransaction_transaction_]
==== GetPlays

[source,cs]
----
IEnumerable< IRoleType > GetPlays(ITypeDBTransaction transaction)
----



Retrieves all direct and inherited roles that are allowed to be played by the instances of this ``IThingType``.

 

See also
[source,cs]
----
 
 
IThingType::GetPlays(ITypeDBTransaction, IConcept.Transitivity)
---- 


[caption=""]
.Returns
`IEnumerable< IRoleType >`

[#_IEnumerable_IRoleType_TypeDB_Driver_Api_IThingType_GetPlays_ITypeDBTransaction_transaction_IConcept_Transitivity_transitivity_]
==== GetPlays

[source,cs]
----
IEnumerable< IRoleType > GetPlays(ITypeDBTransaction transaction, IConcept.Transitivity transitivity)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``IThingType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `transitivity` a| transitivity: ``Transitive`` for direct and indirect playing, ``Explicit`` for direct playing only a| `IConcept​.Transitivity`
|===

[caption=""]
.Returns
`IEnumerable< IRoleType >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetPlays(transaction).Resolve();
thingType.GetPlays(transaction, Explicit).Resolve();
----

[#_Promise_IRoleType_TypeDB_Driver_Api_IThingType_GetPlaysOverridden_ITypeDBTransaction_transaction_IRoleType_roleType_]
==== GetPlaysOverridden

[source,cs]
----
Promise< IRoleType > GetPlaysOverridden(ITypeDBTransaction transaction, IRoleType roleType)
----



Retrieves a ``IRoleType`` that is overridden by the given ``role_type`` for this ``IThingType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleType` a| The ``IRoleType`` that overrides an inherited role a| `IRoleType`
|===

[caption=""]
.Returns
`Promise< IRoleType >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetPlaysOverridden(transaction, roleType).Resolve();
----

[#_Promise_string_TypeDB_Driver_Api_IThingType_GetSyntax_ITypeDBTransaction_transaction_]
==== GetSyntax

[source,cs]
----
Promise< string > GetSyntax(ITypeDBTransaction transaction)
----



Produces a pattern for creating this ``IThingType`` in a ``define`` query.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`Promise< string >`

[caption=""]
.Code examples
[source,cs]
----
thingType.GetSyntax(transaction).Resolve();
----

[#_bool_IConcept_TypeDB_Driver_Api_IThingType_IsThingType_]
==== IsThingType

[source,cs]
----
bool IConcept. IsThingType()
----



Checks if the concept is a ``IThingType``.




Implements TypeDB.Driver.Api.IConcept.

[caption=""]
.Returns
`bool IConcept.`

[caption=""]
.Code examples
[source,cs]
----
concept.IsThingType();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetAbstract_ITypeDBTransaction_transaction_]
==== SetAbstract

[source,cs]
----
VoidPromise SetAbstract(ITypeDBTransaction transaction)
----



Set a ``IThingType`` to be abstract, meaning it cannot have instances.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.SetAbstract(transaction).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns_ITypeDBTransaction_transaction_IAttributeType_attributeType_IAttributeType_overriddenType_ICollection_Annotation_annotations_]
==== SetOwns

[source,cs]
----
VoidPromise SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, IAttributeType? overriddenType, ICollection< Annotation > annotations)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attributeType` a| The ``IAttributeType`` to be owned by the instances of this type. a| `IAttributeType`
a| `overriddenType` a| The ``IAttributeType`` that this attribute ownership overrides, if applicable. a| `IAttributeType?`
a| `annotations` a| Adds annotations to the ownership. a| `ICollection< Annotation >`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.SetOwns(transaction, attributeType).Resolve();
thingType.SetOwns(transaction, attributeType, overriddenType, new []{NewKey()}).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns_ITypeDBTransaction_transaction_IAttributeType_attributeType_IAttributeType_overriddenType_]
==== SetOwns

[source,cs]
----
VoidPromise SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, IAttributeType overriddenType)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``,

 

See also
[source,cs]
----
 
 
IThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns_ITypeDBTransaction_transaction_IAttributeType_attributeType_ICollection_Annotation_annotations_]
==== SetOwns

[source,cs]
----
VoidPromise SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType, ICollection< Annotation > annotations)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``.

 

See also
[source,cs]
----
 
 
IThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetOwns_ITypeDBTransaction_transaction_IAttributeType_attributeType_]
==== SetOwns

[source,cs]
----
VoidPromise SetOwns(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Allows the instances of this ``IThingType`` to own the given ``IAttributeType``.

 

See also
[source,cs]
----
 
 
IThingType::SetOwns(ITypeDBTransaction, IAttributeType, IAttributeType, Set)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetPlays_ITypeDBTransaction_transaction_IRoleType_roleType_]
==== SetPlays

[source,cs]
----
VoidPromise SetPlays(ITypeDBTransaction transaction, IRoleType roleType)
----



Allows the instances of this ``IThingType`` to play the given role.

 

See also
[source,cs]
----
 
 
IThingType::SetPlays(ITypeDBTransaction, IRoleType, IRoleType)
---- 


[caption=""]
.Returns
`VoidPromise`

[#_VoidPromise_TypeDB_Driver_Api_IThingType_SetPlays_ITypeDBTransaction_transaction_IRoleType_roleType_IRoleType_overriddenType_]
==== SetPlays

[source,cs]
----
VoidPromise SetPlays(ITypeDBTransaction transaction, IRoleType roleType, IRoleType overriddenType)
----



Allows the instances of this ``IThingType`` to play the given role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleType` a| The role to be played by the instances of this type a| `IRoleType`
a| `overriddenType` a| The role type that this role overrides, if applicable a| `IRoleType`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.SetPlays(transaction, roleType).Resolve();
thingType.SetPlays(transaction, roleType, overriddenType).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetAbstract_ITypeDBTransaction_transaction_]
==== UnsetAbstract

[source,cs]
----
VoidPromise UnsetAbstract(ITypeDBTransaction transaction)
----



Set a ``IThingType`` to be non-abstract, meaning it can have instances.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.UnsetAbstract(transaction).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetOwns_ITypeDBTransaction_transaction_IAttributeType_attributeType_]
==== UnsetOwns

[source,cs]
----
VoidPromise UnsetOwns(ITypeDBTransaction transaction, IAttributeType attributeType)
----



Disallows the instances of this ``IThingType`` from owning the given ``IAttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `attributeType` a| The ``IAttributeType`` to not be owned by the type. a| `IAttributeType`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.UnsetOwns(transaction, attributeType).Resolve();
----

[#_VoidPromise_TypeDB_Driver_Api_IThingType_UnsetPlays_ITypeDBTransaction_transaction_IRoleType_roleType_]
==== UnsetPlays

[source,cs]
----
VoidPromise UnsetPlays(ITypeDBTransaction transaction, IRoleType roleType)
----



Disallows the instances of this ``IThingType`` from playing the given role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `ITypeDBTransaction`
a| `roleType` a| The role to not be played by the instances of this type. a| `IRoleType`
|===

[caption=""]
.Returns
`VoidPromise`

[caption=""]
.Code examples
[source,cs]
----
thingType.UnsetPlays(transaction, roleType).Resolve();
----

// end::methods[]

