[#_Type]
=== Type

`Class(name=Type, anchor=Type, enumConstants=[], description=[], examples=[], fields=[], methods=[Method(name=isType, signature=@CheckReturnValue
default boolean isType(), anchor=Type_isType_, args=[], description=[Checks if the concept is a ``Type``. 
], examples=[concept.isType();], mode=null, returnDescription=null, returnType=boolean), Method(name=asType, signature=@CheckReturnValue
default Type asType(), anchor=Type_asType_, args=[], description=[Casts the concept to ``Type``. 
], examples=[concept.asType();], mode=null, returnDescription=null, returnType=Type), Method(name=asAttribute, signature=default Attribute asAttribute(), anchor=Type_asAttribute_, args=[], description=[Casts the concept to ``Attribute``. 
], examples=[concept.asAttribute();], mode=null, returnDescription=null, returnType=Attribute), Method(name=asAttributeType, signature=default AttributeType asAttributeType(), anchor=Type_asAttributeType_, args=[], description=[Casts the concept to ``AttributeType``. 
], examples=[concept.asAttributeType();], mode=null, returnDescription=null, returnType=AttributeType), Method(name=asEntity, signature=default Entity asEntity(), anchor=Type_asEntity_, args=[], description=[Casts the concept to ``Entity``. 
], examples=[concept.asEntity();], mode=null, returnDescription=null, returnType=Entity), Method(name=asEntityType, signature=default EntityType asEntityType(), anchor=Type_asEntityType_, args=[], description=[Casts the concept to ``EntityType``. 
], examples=[concept.asEntityType();], mode=null, returnDescription=null, returnType=EntityType), Method(name=asInstance, signature=default Instance asInstance(), anchor=Type_asInstance_, args=[], description=[Casts the concept to ``Instance``. 
], examples=[concept.asInstance();], mode=null, returnDescription=null, returnType=Instance), Method(name=asRelation, signature=default Relation asRelation(), anchor=Type_asRelation_, args=[], description=[Casts the concept to ``Relation``. 
], examples=[concept.asRelation();], mode=null, returnDescription=null, returnType=Relation), Method(name=asRelationType, signature=default RelationType asRelationType(), anchor=Type_asRelationType_, args=[], description=[Casts the concept to ``RelationType``. 
], examples=[concept.asRelationType();], mode=null, returnDescription=null, returnType=RelationType), Method(name=asRoleType, signature=default RoleType asRoleType(), anchor=Type_asRoleType_, args=[], description=[Casts the concept to ``RoleType``. 
], examples=[concept.asRoleType();], mode=null, returnDescription=null, returnType=RoleType), Method(name=asValue, signature=default Value asValue(), anchor=Type_asValue_, args=[], description=[Casts the concept to ``Value``. 
], examples=[concept.asValue();], mode=null, returnDescription=null, returnType=Value), Method(name=getLabel, signature=@CheckReturnValue
java.lang.String getLabel(), anchor=Type_getLabel_, args=[], description=[Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 
], examples=[concept.getLabel();], mode=null, returnDescription=null, returnType=java.lang.String), Method(name=isAttribute, signature=@CheckReturnValue
default boolean isAttribute(), anchor=Type_isAttribute_, args=[], description=[Checks if the concept is an ``Attribute``. 
], examples=[concept.isAttribute();], mode=null, returnDescription=null, returnType=boolean), Method(name=isAttributeType, signature=@CheckReturnValue
default boolean isAttributeType(), anchor=Type_isAttributeType_, args=[], description=[Checks if the concept is an ``AttributeType``. 
], examples=[concept.isAttributeType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isBoolean, signature=@CheckReturnValue
boolean isBoolean(), anchor=Type_isBoolean_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 
], examples=[concept.isBoolean()], mode=null, returnDescription=null, returnType=boolean), Method(name=isDate, signature=@CheckReturnValue
boolean isDate(), anchor=Type_isDate_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 
], examples=[concept.isDate();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDatetime, signature=@CheckReturnValue
boolean isDatetime(), anchor=Type_isDatetime_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 
], examples=[concept.isDatetime();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDatetimeTZ, signature=@CheckReturnValue
boolean isDatetimeTZ(), anchor=Type_isDatetimeTZ_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 
], examples=[concept.isDatetimeTZ();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDecimal, signature=@CheckReturnValue
boolean isDecimal(), anchor=Type_isDecimal_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 
], examples=[concept.isDecimal();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDouble, signature=@CheckReturnValue
boolean isDouble(), anchor=Type_isDouble_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 
], examples=[concept.isDouble();], mode=null, returnDescription=null, returnType=boolean), Method(name=isDuration, signature=@CheckReturnValue
boolean isDuration(), anchor=Type_isDuration_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 
], examples=[concept.isDuration();], mode=null, returnDescription=null, returnType=boolean), Method(name=isEntity, signature=@CheckReturnValue
default boolean isEntity(), anchor=Type_isEntity_, args=[], description=[Checks if the concept is an ``Entity``. 
], examples=[concept.isEntity();], mode=null, returnDescription=null, returnType=boolean), Method(name=isEntityType, signature=@CheckReturnValue
default boolean isEntityType(), anchor=Type_isEntityType_, args=[], description=[Checks if the concept is an ``EntityType``. 
], examples=[concept.isEntityType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isInstance, signature=@CheckReturnValue
default boolean isInstance(), anchor=Type_isInstance_, args=[], description=[Checks if the concept is an ``Instance``. 
], examples=[concept.isInstance();], mode=null, returnDescription=null, returnType=boolean), Method(name=isInteger, signature=@CheckReturnValue
boolean isInteger(), anchor=Type_isInteger_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 
], examples=[concept.isInteger();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelation, signature=@CheckReturnValue
default boolean isRelation(), anchor=Type_isRelation_, args=[], description=[Checks if the concept is a ``Relation``. 
], examples=[concept.isRelation();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRelationType, signature=@CheckReturnValue
default boolean isRelationType(), anchor=Type_isRelationType_, args=[], description=[Checks if the concept is a ``RelationType``. 
], examples=[concept.isRelationType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isRoleType, signature=@CheckReturnValue
default boolean isRoleType(), anchor=Type_isRoleType_, args=[], description=[Checks if the concept is a ``RoleType``. 
], examples=[concept.isRoleType();], mode=null, returnDescription=null, returnType=boolean), Method(name=isString, signature=@CheckReturnValue
boolean isString(), anchor=Type_isString_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 
], examples=[concept.isString();], mode=null, returnDescription=null, returnType=boolean), Method(name=isStruct, signature=@CheckReturnValue
boolean isStruct(), anchor=Type_isStruct_, args=[], description=[Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 
], examples=[concept.isStruct();], mode=null, returnDescription=null, returnType=boolean), Method(name=isValue, signature=@CheckReturnValue
default boolean isValue(), anchor=Type_isValue_, args=[], description=[Checks if the concept is a ``Value``. 
], examples=[concept.isValue();], mode=null, returnDescription=null, returnType=boolean), Method(name=tryGetBoolean, signature=java.util.Optional<java.lang.Boolean> tryGetBoolean(), anchor=Type_tryGetBoolean_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetBoolean();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Boolean>), Method(name=tryGetDate, signature=java.util.Optional<java.time.LocalDate> tryGetDate(), anchor=Type_tryGetDate_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDate();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.LocalDate>), Method(name=tryGetDatetime, signature=java.util.Optional<java.time.LocalDateTime> tryGetDatetime(), anchor=Type_tryGetDatetime_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDatetime();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.LocalDateTime>), Method(name=tryGetDatetimeTZ, signature=java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ(), anchor=Type_tryGetDatetimeTZ_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDatetimeTZ();], mode=null, returnDescription=null, returnType=java.util.Optional<java.time.ZonedDateTime>), Method(name=tryGetDecimal, signature=java.util.Optional<java.math.BigDecimal> tryGetDecimal(), anchor=Type_tryGetDecimal_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDecimal();], mode=null, returnDescription=null, returnType=java.util.Optional<java.math.BigDecimal>), Method(name=tryGetDouble, signature=java.util.Optional<java.lang.Double> tryGetDouble(), anchor=Type_tryGetDouble_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDouble();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Double>), Method(name=tryGetDuration, signature=java.util.Optional<Duration> tryGetDuration(), anchor=Type_tryGetDuration_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetDuration();], mode=null, returnDescription=null, returnType=java.util.Optional<Duration>), Method(name=tryGetIID, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID(), anchor=Type_tryGetIID_, args=[], description=[Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 
], examples=[concept.tryGetIID();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetInteger, signature=java.util.Optional<java.lang.Long> tryGetInteger(), anchor=Type_tryGetInteger_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetInteger();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.Long>), Method(name=tryGetLabel, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel(), anchor=Type_tryGetLabel_, args=[], description=[Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 
], examples=[concept.tryGetLabel();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetString, signature=java.util.Optional<java.lang.String> tryGetString(), anchor=Type_tryGetString_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetString();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>), Method(name=tryGetStruct, signature=java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct(), anchor=Type_tryGetStruct_, args=[], description=[Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 
], examples=[concept.tryGetStruct();], mode=null, returnDescription=null, returnType=java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>), Method(name=tryGetValue, signature=@CheckReturnValue
java.util.Optional<Value> tryGetValue(), anchor=Type_tryGetValue_, args=[], description=[Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 
], examples=[concept.tryGetValue();], mode=null, returnDescription=null, returnType=java.util.Optional<Value>), Method(name=tryGetValueType, signature=@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType(), anchor=Type_tryGetValueType_, args=[], description=[Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 
], examples=[concept.tryGetValueType();], mode=null, returnDescription=null, returnType=java.util.Optional<java.lang.String>)], packagePath=com.typedb.driver.api.concept.type, superClasses=[Concept], traitImplementors=[], mode=null).nameDescriptor(language)`

*Package*: `com.typedb.driver.api.concept.type`

*Superinterfaces:*

* `Concept`

// tag::methods[]
[#_Type_asAttribute_]
==== asAttribute

[source,java]
----
default Attribute asAttribute()
----

Casts the concept to ``Attribute``. 


[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
concept.asAttribute();
----

[#_Type_asAttributeType_]
==== asAttributeType

[source,java]
----
default AttributeType asAttributeType()
----

Casts the concept to ``AttributeType``. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
concept.asAttributeType();
----

[#_Type_asEntity_]
==== asEntity

[source,java]
----
default Entity asEntity()
----

Casts the concept to ``Entity``. 


[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
concept.asEntity();
----

[#_Type_asEntityType_]
==== asEntityType

[source,java]
----
default EntityType asEntityType()
----

Casts the concept to ``EntityType``. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
concept.asEntityType();
----

[#_Type_asInstance_]
==== asInstance

[source,java]
----
default Instance asInstance()
----

Casts the concept to ``Instance``. 


[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,java]
----
concept.asInstance();
----

[#_Type_asRelation_]
==== asRelation

[source,java]
----
default Relation asRelation()
----

Casts the concept to ``Relation``. 


[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
concept.asRelation();
----

[#_Type_asRelationType_]
==== asRelationType

[source,java]
----
default RelationType asRelationType()
----

Casts the concept to ``RelationType``. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
concept.asRelationType();
----

[#_Type_asRoleType_]
==== asRoleType

[source,java]
----
default RoleType asRoleType()
----

Casts the concept to ``RoleType``. 


[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,java]
----
concept.asRoleType();
----

[#_Type_asType_]
==== asType

[source,java]
----
@CheckReturnValue
default Type asType()
----

Casts the concept to ``Type``. 


[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,java]
----
concept.asType();
----

[#_Type_asValue_]
==== asValue

[source,java]
----
default Value asValue()
----

Casts the concept to ``Value``. 


[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,java]
----
concept.asValue();
----

[#_Type_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance ("unknown" if type fetching is disabled). If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
concept.getLabel();
----

[#_Type_isAttribute_]
==== isAttribute

[source,java]
----
@CheckReturnValue
default boolean isAttribute()
----

Checks if the concept is an ``Attribute``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttribute();
----

[#_Type_isAttributeType_]
==== isAttributeType

[source,java]
----
@CheckReturnValue
default boolean isAttributeType()
----

Checks if the concept is an ``AttributeType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isAttributeType();
----

[#_Type_isBoolean_]
==== isBoolean

[source,java]
----
@CheckReturnValue
boolean isBoolean()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``boolean`` or if this ``Concept`` is an ``AttributeType`` of type ``boolean``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isBoolean()
----

[#_Type_isDate_]
==== isDate

[source,java]
----
@CheckReturnValue
boolean isDate()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``date`` or if this ``Concept`` is an ``AttributeType`` of type ``date``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDate();
----

[#_Type_isDatetime_]
==== isDatetime

[source,java]
----
@CheckReturnValue
boolean isDatetime()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetime();
----

[#_Type_isDatetimeTZ_]
==== isDatetimeTZ

[source,java]
----
@CheckReturnValue
boolean isDatetimeTZ()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``datetime-tz`` or if this ``Concept`` is an ``AttributeType`` of type ``datetime-tz``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDatetimeTZ();
----

[#_Type_isDecimal_]
==== isDecimal

[source,java]
----
@CheckReturnValue
boolean isDecimal()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``decimal`` or if this ``Concept`` is an ``AttributeType`` of type ``decimal``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDecimal();
----

[#_Type_isDouble_]
==== isDouble

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``double`` or if this ``Concept`` is an ``AttributeType`` of type ``double``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDouble();
----

[#_Type_isDuration_]
==== isDuration

[source,java]
----
@CheckReturnValue
boolean isDuration()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``duration`` or if this ``Concept`` is an ``AttributeType`` of type ``duration``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isDuration();
----

[#_Type_isEntity_]
==== isEntity

[source,java]
----
@CheckReturnValue
default boolean isEntity()
----

Checks if the concept is an ``Entity``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntity();
----

[#_Type_isEntityType_]
==== isEntityType

[source,java]
----
@CheckReturnValue
default boolean isEntityType()
----

Checks if the concept is an ``EntityType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isEntityType();
----

[#_Type_isInstance_]
==== isInstance

[source,java]
----
@CheckReturnValue
default boolean isInstance()
----

Checks if the concept is an ``Instance``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInstance();
----

[#_Type_isInteger_]
==== isInteger

[source,java]
----
@CheckReturnValue
boolean isInteger()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``integer`` or if this ``Concept`` is an ``AttributeType`` of type ``integer``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isInteger();
----

[#_Type_isRelation_]
==== isRelation

[source,java]
----
@CheckReturnValue
default boolean isRelation()
----

Checks if the concept is a ``Relation``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelation();
----

[#_Type_isRelationType_]
==== isRelationType

[source,java]
----
@CheckReturnValue
default boolean isRelationType()
----

Checks if the concept is a ``RelationType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRelationType();
----

[#_Type_isRoleType_]
==== isRoleType

[source,java]
----
@CheckReturnValue
default boolean isRoleType()
----

Checks if the concept is a ``RoleType``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isRoleType();
----

[#_Type_isString_]
==== isString

[source,java]
----
@CheckReturnValue
boolean isString()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``string`` or if this ``Concept`` is an ``AttributeType`` of type ``string``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isString();
----

[#_Type_isStruct_]
==== isStruct

[source,java]
----
@CheckReturnValue
boolean isStruct()
----

Returns ``true`` if the value which this ``Concept`` holds is of type ``struct`` or if this ``Concept`` is an ``AttributeType`` of type ``struct``. Otherwise, returns ``false``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isStruct();
----

[#_Type_isType_]
==== isType

[source,java]
----
@CheckReturnValue
default boolean isType()
----

Checks if the concept is a ``Type``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isType();
----

[#_Type_isValue_]
==== isValue

[source,java]
----
@CheckReturnValue
default boolean isValue()
----

Checks if the concept is a ``Value``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
concept.isValue();
----

[#_Type_tryGetBoolean_]
==== tryGetBoolean

[source,java]
----
java.util.Optional<java.lang.Boolean> tryGetBoolean()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Boolean&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetBoolean();
----

[#_Type_tryGetDate_]
==== tryGetDate

[source,java]
----
java.util.Optional<java.time.LocalDate> tryGetDate()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDate&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDate>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDate();
----

[#_Type_tryGetDatetime_]
==== tryGetDatetime

[source,java]
----
java.util.Optional<java.time.LocalDateTime> tryGetDatetime()
----

Returns the value of this ``Concept`` as an ``Optional&lt;LocalDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.LocalDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetime();
----

[#_Type_tryGetDatetimeTZ_]
==== tryGetDatetimeTZ

[source,java]
----
java.util.Optional<java.time.ZonedDateTime> tryGetDatetimeTZ()
----

Returns the value of this ``Concept`` as an ``Optional&lt;ZonedDateTime&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.time.ZonedDateTime>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDatetimeTZ();
----

[#_Type_tryGetDecimal_]
==== tryGetDecimal

[source,java]
----
java.util.Optional<java.math.BigDecimal> tryGetDecimal()
----

Returns the value of this ``Concept`` as an ``Optional&lt;BigDecimal&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.math.BigDecimal>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDecimal();
----

[#_Type_tryGetDouble_]
==== tryGetDouble

[source,java]
----
java.util.Optional<java.lang.Double> tryGetDouble()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Double&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Double>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDouble();
----

[#_Type_tryGetDuration_]
==== tryGetDuration

[source,java]
----
java.util.Optional<Duration> tryGetDuration()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Duration&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<Duration>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetDuration();
----

[#_Type_tryGetIID_]
==== tryGetIID

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetIID()
----

Retrieves the unique id of the ``Concept``. Returns ``null`` if absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetIID();
----

[#_Type_tryGetInteger_]
==== tryGetInteger

[source,java]
----
java.util.Optional<java.lang.Long> tryGetInteger()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Long&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.Long>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetInteger();
----

[#_Type_tryGetLabel_]
==== tryGetLabel

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetLabel()
----

Retrieves the unique label of the concept. If this is an ``Instance``, return the label of the type of this instance (``null`` if type fetching is disabled). Returns ``null`` if type fetching is disabled. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetLabel();
----

[#_Type_tryGetString_]
==== tryGetString

[source,java]
----
java.util.Optional<java.lang.String> tryGetString()
----

Returns the value of this ``Concept`` as an ``Optional&lt;String&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetString();
----

[#_Type_tryGetStruct_]
==== tryGetStruct

[source,java]
----
java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>> tryGetStruct()
----

Returns the value of this ``Concept`` as an ``Optional&lt;Map&lt;String, Optional&lt;Value&gt;&gt;&gt;``. If it's not a ``Value`` or it has another type, returns ``null``. 


[caption=""]
.Returns
`java.util.Optional<java.util.Map<java.lang.String,​java.util.Optional<Value>>>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetStruct();
----

[#_Type_tryGetValue_]
==== tryGetValue

[source,java]
----
@CheckReturnValue
java.util.Optional<Value> tryGetValue()
----

Retrieves the value which this ``Concept`` holds. Returns ``null`` if this ``Concept`` does not hold any value. 


[caption=""]
.Returns
`java.util.Optional<Value>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValue();
----

[#_Type_tryGetValueType_]
==== tryGetValueType

[source,java]
----
@CheckReturnValue
java.util.Optional<java.lang.String> tryGetValueType()
----

Retrieves the ``String`` describing the value type of this ``Concept``. Returns ``null`` if not absent. 


[caption=""]
.Returns
`java.util.Optional<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
concept.tryGetValueType();
----

// end::methods[]

