[#_AttributeType]
= AttributeType

*Supertypes:*

* `ThingType`

== Description

Attribute types represent properties that other types can own. Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type. Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value. Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `abstract` a| `boolean` a| Whether the type is prevented from having data instances (i.e., abstract).
a| `label` a| `Label` a| The unique label of the type.
a| `root` a| `boolean` a| Whether the type is a root type.
a| `valueType` a| `ValueType` a| The ValueType of this AttributeType.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_asAttribute]
=== asAttribute

==== Signature

[source,nodejs]
----
asAttribute(): Attribute
----

==== Description

Casts the concept to `Attribute`.

==== Returns

`Attribute`

==== Code examples

[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
=== asAttributeType

==== Signature

[source,nodejs]
----
asAttributeType(): AttributeType
----

==== Description

Casts the concept to `AttributeType`.

==== Returns

`AttributeType`

==== Code examples

[source,nodejs]
----
concept.asAttributeType()
----

[#_asEntity]
=== asEntity

==== Signature

[source,nodejs]
----
asEntity(): Entity
----

==== Description

Casts the concept to `Entity`.

==== Returns

`Entity`

==== Code examples

[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
=== asEntityType

==== Signature

[source,nodejs]
----
asEntityType(): EntityType
----

==== Description

Casts the concept to `EntityType`.

==== Returns

`EntityType`

==== Code examples

[source,nodejs]
----
concept.asEntityType()
----

[#_asRelation]
=== asRelation

==== Signature

[source,nodejs]
----
asRelation(): Relation
----

==== Description

Casts the concept to `Relation`.

==== Returns

`Relation`

==== Code examples

[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
=== asRelationType

==== Signature

[source,nodejs]
----
asRelationType(): RelationType
----

==== Description

Casts the concept to `RelationType`.

==== Returns

`RelationType`

==== Code examples

[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
=== asRoleType

==== Signature

[source,nodejs]
----
asRoleType(): RoleType
----

==== Description

Casts the concept to `RoleType`.

==== Returns

`RoleType`

==== Code examples

[source,nodejs]
----
concept.asRoleType()
----

[#_asThing]
=== asThing

==== Signature

[source,nodejs]
----
asThing(): Thing
----

==== Description

Casts the concept to `Thing`.

==== Returns

`Thing`

==== Code examples

[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
=== asThingType

==== Signature

[source,nodejs]
----
asThingType(): ThingType
----

==== Description

Casts the concept to `ThingType`.

==== Returns

`ThingType`

==== Code examples

[source,nodejs]
----
concept.asThingType()
----

[#_asType]
=== asType

==== Signature

[source,nodejs]
----
asType(): Type
----

==== Description

Casts the concept to `Type`.

==== Returns

`Type`

==== Code examples

[source,nodejs]
----
concept.asType()
----

[#_asValue]
=== asValue

==== Signature

[source,nodejs]
----
asValue(): Value
----

==== Description

Casts the concept to `Value`.

==== Returns

`Value`

==== Code examples

[source,nodejs]
----
concept.asValue()
----

[#_delete]
=== delete

==== Signature

[source,nodejs]
----
delete(transaction): Promise<void>
----

==== Description

Deletes this type from the database.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
type.delete(transaction)
----

[#_equals]
=== equals

==== Signature

[source,nodejs]
----
equals(concept): boolean
----

==== Description

Checks if this concept is equal to the argument `concept`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept` 
|===

==== Returns

`boolean`

[#_get]
=== get

==== Signature

[source,nodejs]
----
get(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `Value` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getBoolean]
=== getBoolean

==== Signature

[source,nodejs]
----
getBoolean(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `boolean` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getDateTime]
=== getDateTime

==== Signature

[source,nodejs]
----
getDateTime(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `Date` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getDouble]
=== getDouble

==== Signature

[source,nodejs]
----
getDouble(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `number` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getInstances]
=== getInstances

==== Signature

[source,nodejs]
----
getInstances(transaction, transitivity): Stream<Attribute>
----

==== Description

Retrieves all direct and indirect (or direct only) `Attributes` that are instances of this `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect subtypes, `Transitivity.EXPLICIT` for direct subtypes only a| `Transitivity` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
attributeType.getInstances(transaction) attributeType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_getInstances]
=== getInstances

==== Signature

[source,nodejs]
----
getInstances(transaction): Stream<Attribute>
----

==== Description

Retrieves all direct and indirect (or direct only) `Thing` objects that are instances of this `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thingType.getInstances(transaction, Transitivity.EXPLICIT)
----

[#_getLong]
=== getLong

==== Signature

[source,nodejs]
----
getLong(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `number` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getOwners]
=== getOwners

==== Signature

[source,nodejs]
----
getOwners(transaction, annotations, transitivity): Stream<ThingType>
----

==== Description

Retrieve all `Things` that own an attribute of this `AttributeType`. Optionally, filtered by `Annotation`s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| Only retrieve `ThingTypes` that have an attribute of this `AttributeType` with all given `Annotation`s a| `Annotation[]` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and inherited ownership, `Transitivity.EXPLICIT` for direct ownership only a| `Transitivity` 
|===

==== Returns

`Stream<ThingType>`

==== Code examples

[source,nodejs]
----
attributeType.getOwners(transaction) attributeType.getOwners(transaction, [Annotation.UNIQUE]) attributeType.getOwners(transaction, Transitivity.TRANSITIVE) attributeType.getOwners(transaction, [Annotation.UNIQUE], Transitivity.TRANSITIVE)
----

[#_getOwners]
=== getOwners

==== Signature

[source,nodejs]
----
getOwners(transaction): Stream<ThingType>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
|===

==== Returns

`Stream<ThingType>`

[#_getOwners]
=== getOwners

==== Signature

[source,nodejs]
----
getOwners(transaction, annotations): Stream<ThingType>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
a| `annotations` a| null a| `Annotation[]` 
|===

==== Returns

`Stream<ThingType>`

[#_getOwners]
=== getOwners

==== Signature

[source,nodejs]
----
getOwners(transaction, transitivity): Stream<ThingType>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
a| `transitivity` a| null a| `Transitivity` 
|===

==== Returns

`Stream<ThingType>`

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, valueType): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `ValueType` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, annotations): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `Annotation[]` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, valueType, annotations): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `ValueType` 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, transitivity): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, valueType, transitivity): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `ValueType` 
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, annotations, transitivity): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `Annotation[]` 
a| `transitivity` a| Only retrieve attribute types owned with annotations. a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwns]
=== getOwns

==== Signature

[source,nodejs]
----
getOwns(transaction, valueType, annotations, transitivity): Stream<AttributeType>
----

==== Description

Retrieves `AttributeType` that the instances of this `ThingType` are allowed to own directly or via inheritance.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| If specified, only attribute types of this `ValueType` will be retrieved. a| `ValueType` 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `Annotation[]` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and inherited ownership, `Transitivity.EXPLICIT` for direct ownership only a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwns(transaction) thingType.getOwns(transaction, valueType, Transitivity.EXPLICIT,[Annotation.KEY])
----

[#_getOwnsOverridden]
=== getOwnsOverridden

==== Signature

[source,nodejs]
----
getOwnsOverridden(transaction, attributeType): Promise<AttributeType>
----

==== Description

Retrieves an `AttributeType`, ownership of which is overridden for this `ThingType` by a given `attribute_type`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` that overrides requested `AttributeType` a| `AttributeType` 
|===

==== Returns

`Promise<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getOwnsOverridden(transaction, attributeType)
----

[#_getPlays]
=== getPlays

==== Signature

[source,nodejs]
----
getPlays(transaction): Stream<RoleType>
----

==== Description

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<RoleType>`

==== Code examples

[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_getPlays]
=== getPlays

==== Signature

[source,nodejs]
----
getPlays(transaction, transitivity): Stream<RoleType>
----

==== Description

Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect playing, `Transitivity.EXPLICIT` for direct playing only a| `Transitivity` 
|===

==== Returns

`Stream<RoleType>`

==== Code examples

[source,nodejs]
----
thingType.getPlays(transaction) thingType.getPlays(transaction, Transitivity.EXPLICIT)
----

[#_getPlaysOverridden]
=== getPlaysOverridden

==== Signature

[source,nodejs]
----
getPlaysOverridden(transaction, role): Promise<RoleType>
----

==== Description

Retrieves a `RoleType` that is overridden by the given `role_type` for this `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `role` a| The `RoleType` that overrides an inherited role a| `RoleType` 
|===

==== Returns

`Promise<RoleType>`

==== Code examples

[source,nodejs]
----
thingType.getPlaysOverridden(transaction, role)
----

[#_getRegex]
=== getRegex

==== Signature

[source,nodejs]
----
getRegex(transaction): Promise<string>
----

==== Description

Retrieves the regular expression that is defined for this `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<string>`

==== Code examples

[source,nodejs]
----
attributeType.getRegex(transaction)
----

[#_getString]
=== getString

==== Signature

[source,nodejs]
----
getString(transaction, value): Promise<Attribute>
----

==== Description

Retrieves an `Attribute` of this `AttributeType` with the given value if such `Attribute` exists. Otherwise, returns `None`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| `Attribute`’s value a| `string` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.get(transaction, value)
----

[#_getSubtypes]
=== getSubtypes

==== Signature

[source,nodejs]
----
getSubtypes(transaction): Stream<AttributeType>
----

==== Description

Retrieves all direct and indirect subtypes of the `ThingType`. Equivalent to getSubtypes(transaction, Transitivity.TRANSITIVE)

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getSubtypes(transaction)
----

[#_getSubtypes]
=== getSubtypes

==== Signature

[source,nodejs]
----
getSubtypes(transaction, valueType): Stream<AttributeType>
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `valueType` a| `Transitivity.TRANSITIVE` for direct and indirect subtypes, `Transitivity.EXPLICIT` for direct subtypes only a| `ValueType` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_getSubtypes]
=== getSubtypes

==== Signature

[source,nodejs]
----
getSubtypes(transaction, transitivity): Stream<AttributeType>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
a| `transitivity` a| null a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

[#_getSubtypes]
=== getSubtypes

==== Signature

[source,nodejs]
----
getSubtypes(transaction, valueType, transitivity): Stream<AttributeType>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
a| `valueType` a| null a| `ValueType` 
a| `transitivity` a| null a| `Transitivity` 
|===

==== Returns

`Stream<AttributeType>`

[#_getSupertype]
=== getSupertype

==== Signature

[source,nodejs]
----
getSupertype(transaction): Promise<AttributeType>
----

==== Description

Retrieves the most immediate supertype of the `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getSupertype(transaction)
----

[#_getSupertypes]
=== getSupertypes

==== Signature

[source,nodejs]
----
getSupertypes(transaction): Stream<AttributeType>
----

==== Description

Retrieves all supertypes of the `ThingType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<AttributeType>`

==== Code examples

[source,nodejs]
----
thingType.getSupertypes(transaction)
----

[#_getSyntax]
=== getSyntax

==== Signature

[source,nodejs]
----
getSyntax(transaction): Promise<string>
----

==== Description

Produces a pattern for creating this `ThingType` in a `define` query.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<string>`

==== Code examples

[source,nodejs]
----
thingType.getSyntax(transaction)
----

[#_isAttribute]
=== isAttribute

==== Signature

[source,nodejs]
----
isAttribute(): boolean
----

==== Description

Checks if the concept is an `Attribute`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
=== isAttributeType

==== Signature

[source,nodejs]
----
isAttributeType(): boolean
----

==== Description

Checks if the concept is an `AttributeType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttributeType()
----

[#_isDeleted]
=== isDeleted

==== Signature

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

==== Description

Check if the concept has been deleted

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<boolean>`

[#_isEntity]
=== isEntity

==== Signature

[source,nodejs]
----
isEntity(): boolean
----

==== Description

Checks if the concept is an `Entity`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
=== isEntityType

==== Signature

[source,nodejs]
----
isEntityType(): boolean
----

==== Description

Checks if the concept is an `EntityType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntityType()
----

[#_isRelation]
=== isRelation

==== Signature

[source,nodejs]
----
isRelation(): boolean
----

==== Description

Checks if the concept is a `Relation`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
=== isRelationType

==== Signature

[source,nodejs]
----
isRelationType(): boolean
----

==== Description

Checks if the concept is a `RelationType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
=== isRoleType

==== Signature

[source,nodejs]
----
isRoleType(): boolean
----

==== Description

Checks if the concept is a `RoleType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRoleType()
----

[#_isThing]
=== isThing

==== Signature

[source,nodejs]
----
isThing(): boolean
----

==== Description

Checks if the concept is a `Thing`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
=== isThingType

==== Signature

[source,nodejs]
----
isThingType(): boolean
----

==== Description

Checks if the concept is a `ThingType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThingType()
----

[#_isType]
=== isType

==== Signature

[source,nodejs]
----
isType(): boolean
----

==== Description

Checks if the concept is a `Type`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isType()
----

[#_isValue]
=== isValue

==== Signature

[source,nodejs]
----
isValue(): boolean
----

==== Description

Checks if the concept is a `Value`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isValue()
----

[#_put]
=== put

==== Signature

[source,nodejs]
----
put(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `Value` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_putBoolean]
=== putBoolean

==== Signature

[source,nodejs]
----
putBoolean(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `boolean` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_putDateTime]
=== putDateTime

==== Signature

[source,nodejs]
----
putDateTime(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `Date` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_putDouble]
=== putDouble

==== Signature

[source,nodejs]
----
putDouble(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `number` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_putLong]
=== putLong

==== Signature

[source,nodejs]
----
putLong(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `number` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_putString]
=== putString

==== Signature

[source,nodejs]
----
putString(transaction, value): Promise<Attribute>
----

==== Description

Adds and returns an `Attribute` of this `AttributeType` with the given value.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `value` a| New `Attribute`’s value a| `string` 
|===

==== Returns

`Promise<Attribute>`

==== Code examples

[source,nodejs]
----
attribute = attributeType.put(transaction, value)
----

[#_setAbstract]
=== setAbstract

==== Signature

[source,nodejs]
----
setAbstract(transaction): Promise<void>
----

==== Description

Set a `ThingType` to be abstract, meaning it cannot have instances.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setAbstract(transaction)
----

[#_setLabel]
=== setLabel

==== Signature

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

==== Description

Renames the label of the type. The new label must remain unique.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `label` a| The new `Label` to be given to the type. a| `string` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
type.setLabel(transaction, label)
----

[#_setOwns]
=== setOwns

==== Signature

[source,nodejs]
----
setOwns(transaction, attributeType): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to own the given `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` to be owned by the instances of this type. a| `AttributeType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_setOwns]
=== setOwns

==== Signature

[source,nodejs]
----
setOwns(transaction, attributeType, annotations): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to own the given `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` to be owned by the instances of this type. a| `AttributeType` 
a| `annotations` a| The `AttributeType` that this attribute ownership overrides, if applicable. a| `Annotation[]` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_setOwns]
=== setOwns

==== Signature

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to own the given `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` to be owned by the instances of this type. a| `AttributeType` 
a| `overriddenType` a| The `AttributeType` that this attribute ownership overrides, if applicable. a| `AttributeType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_setOwns]
=== setOwns

==== Signature

[source,nodejs]
----
setOwns(transaction, attributeType, overriddenType, annotations): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to own the given `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` to be owned by the instances of this type. a| `AttributeType` 
a| `overriddenType` a| The `AttributeType` that this attribute ownership overrides, if applicable. a| `AttributeType` 
a| `annotations` a| Adds annotations to the ownership. a| `Annotation[]` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setOwns(transaction, attributeType) thingType.setOwns(transaction, attributeType, overriddenType,[Annotation.KEY])
----

[#_setPlays]
=== setPlays

==== Signature

[source,nodejs]
----
setPlays(transaction, role): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to play the given role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `role` a| The role to be played by the instances of this type a| `RoleType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_setPlays]
=== setPlays

==== Signature

[source,nodejs]
----
setPlays(transaction, role, overriddenType): Promise<void>
----

==== Description

Allows the instances of this `ThingType` to play the given role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `role` a| The role to be played by the instances of this type a| `RoleType` 
a| `overriddenType` a| The role type that this role overrides, if applicable a| `RoleType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.setPlays(transaction, role) thingType.setPlays(transaction, role, overriddenType)
----

[#_setRegex]
=== setRegex

==== Signature

[source,nodejs]
----
setRegex(transaction, regex): Promise<void>
----

==== Description

Sets a regular expression as a constraint for this `AttributeType`. `Values` of all `Attribute`s of this type (inserted earlier or later) should match this regex. Can only be applied for `AttributeType`s with a `string` value type.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `regex` a| Regular expression a| `string` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
attributeType.setRegex(transaction, regex)
----

[#_setSupertype]
=== setSupertype

==== Signature

[source,nodejs]
----
setSupertype(transaction, type): Promise<void>
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| null a| `TypeDBTransaction` 
a| `type` a| null a| `AttributeType` 
|===

==== Returns

`Promise<void>`

[#_toJSONRecord]
=== toJSONRecord

==== Signature

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

==== Description

Retrieves the concept as JSON.

==== Returns

`Record<string, string | number | boolean>`

==== Code examples

[source,nodejs]
----
concept.toJSONRecord()
----

[#_unsetAbstract]
=== unsetAbstract

==== Signature

[source,nodejs]
----
unsetAbstract(transaction): Promise<void>
----

==== Description

Set a `ThingType` to be non-abstract, meaning it can have instances.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.unsetAbstract(transaction)
----

[#_unsetOwns]
=== unsetOwns

==== Signature

[source,nodejs]
----
unsetOwns(transaction, attributeType): Promise<void>
----

==== Description

Disallows the instances of this `ThingType` from owning the given `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The `AttributeType` to not be owned by the type. a| `AttributeType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.unsetOwns(transaction, attributeType)
----

[#_unsetPlays]
=== unsetPlays

==== Signature

[source,nodejs]
----
unsetPlays(transaction, role): Promise<void>
----

==== Description

Disallows the instances of this `ThingType` from playing the given role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `role` a| The role to not be played by the instances of this type. a| `RoleType` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thingType.unsetPlays(transaction, role)
----

[#_unsetRegex]
=== unsetRegex

==== Signature

[source,nodejs]
----
unsetRegex(transaction): Promise<void>
----

==== Description

Removes the regular expression that is defined for this `AttributeType`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
attributeType.unsetRegex(transaction)
----

// end::methods[]
