[#_ConceptManager]
=== ConceptManager

Provides access for all Concept API methods.

// tag::methods[]
[#_getAttribute]
==== getAttribute

[source,nodejs]
----
getAttribute(iid): Promise<Attribute>
----

Retrieves an ``Attribute`` by its iid.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `string` 
|===

.Returns
`Promise<Attribute>`

.Code examples
[source,nodejs]
----
transaction.concepts().getAttribute(iid)
----

[#_getAttributeType]
==== getAttributeType

[source,nodejs]
----
getAttributeType(label): Promise<AttributeType>
----

Retrieves an ``AttributeType`` by its label.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `string` 
|===

.Returns
`Promise<AttributeType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getAttributeType(label)
----

[#_getEntity]
==== getEntity

[source,nodejs]
----
getEntity(iid): Promise<Entity>
----

Retrieves an ``Entity`` by its iid.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `string` 
|===

.Returns
`Promise<Entity>`

.Code examples
[source,nodejs]
----
transaction.concepts().getEntity(iid)
----

[#_getEntityType]
==== getEntityType

[source,nodejs]
----
getEntityType(label): Promise<EntityType>
----

Retrieves an ``EntityType`` by its label.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `string` 
|===

.Returns
`Promise<EntityType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getEntityType(label)
----

[#_getRelation]
==== getRelation

[source,nodejs]
----
getRelation(iid): Promise<Relation>
----

Retrieves a ``Relation`` by its iid.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `string` 
|===

.Returns
`Promise<Relation>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRelation(iid)
----

[#_getRelationType]
==== getRelationType

[source,nodejs]
----
getRelationType(label): Promise<RelationType>
----

Retrieves a ``RelationType`` by its label.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `string` 
|===

.Returns
`Promise<RelationType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRelationType(label)
----

[#_getRootAttributeType]
==== getRootAttributeType

[source,nodejs]
----
getRootAttributeType(): Promise<AttributeType>
----

Retrieve the root ``AttributeType``, “attribute”.

.Returns
`Promise<AttributeType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRootAttributeType()
----

[#_getRootEntityType]
==== getRootEntityType

[source,nodejs]
----
getRootEntityType(): Promise<EntityType>
----

Retrieves the root ``EntityType``, “entity”.

.Returns
`Promise<EntityType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRootEntityType()
----

[#_getRootRelationType]
==== getRootRelationType

[source,nodejs]
----
getRootRelationType(): Promise<RelationType>
----

Retrieve the root ``RelationType``, “relation”.

.Returns
`Promise<RelationType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRootRelationType()
----

[#_getRootThingType]
==== getRootThingType

[source,nodejs]
----
getRootThingType(): Promise<ThingType>
----

Retrieves the root ``ThingType``, “thing”.

.Returns
`Promise<ThingType>`

.Code examples
[source,nodejs]
----
transaction.concepts().getRootThingType()
----

[#_getSchemaExceptions]
==== getSchemaExceptions

[source,nodejs]
----
getSchemaExceptions(): Promise<TypeDBDriverError[]>
----

Retrieves a list of all exceptions for the current transaction.

.Returns
`Promise<TypeDBDriverError[]>`

.Code examples
[source,nodejs]
----
transaction.concepts().getSchemaException()
----

[#_putAttributeType]
==== putAttributeType

[source,nodejs]
----
putAttributeType(label, valueType): Promise<AttributeType>
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one. or retrieve. :return:

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `string` 
a| `valueType` a| The value type of the ``AttributeType`` to create a| `ValueType` 
|===

.Returns
`Promise<AttributeType>`

.Code examples
[source,nodejs]
----
await transaction.concepts().putAttributeType(label, valueType)
----

[#_putEntityType]
==== putEntityType

[source,nodejs]
----
putEntityType(label): Promise<EntityType>
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `string` 
|===

.Returns
`Promise<EntityType>`

.Code examples
[source,nodejs]
----
transaction.concepts().putEntityType(label)
----

[#_putRelationType]
==== putRelationType

[source,nodejs]
----
putRelationType(label): Promise<RelationType>
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `string` 
|===

.Returns
`Promise<RelationType>`

.Code examples
[source,nodejs]
----
transaction.concepts().putRelationType(label)
----

// end::methods[]
