[#_Concept]
=== Concept

// tag::methods[]
[#_asAttribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

.Returns
`Attribute`

.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

.Returns
`AttributeType`

.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_asEntity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

.Returns
`Entity`

.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

.Returns
`EntityType`

.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_asRelation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

.Returns
`Relation`

.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

.Returns
`RelationType`

.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

.Returns
`RoleType`

.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_asThing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

.Returns
`Thing`

.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

.Returns
`ThingType`

.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_asType]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

.Returns
`Type`

.Code examples
[source,nodejs]
----
concept.asType()
----

[#_asValue]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

.Returns
`Value`

.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_equals]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept` 
|===

.Returns
`boolean`

[#_isAttribute]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_isEntity]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_isRelation]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_isThing]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_isType]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isType()
----

[#_isValue]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_toJSONRecord]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

.Returns
`Record<string, string | number | boolean>`

.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

// end::methods[]
