[#_Entity]
= Entity

*Supertypes:*

* `Thing`

== Description

Instance of data of an entity type, representing a standalone object that exists in the data model independently. Entity does not have a value. It is usually addressed by its ownership over attribute instances and/or roles played in relation instances.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `string` a| Retrieves the unique id of the Thing.
a| `inferred` a| `boolean` a| Checks if this Thing is inferred by a [Reasoning Rule].
a| `type` a| `EntityType` a| The type which this Entity belongs to.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_asAttribute]
=== asAttribute

==== Signature

[source,nodejs]
----
asAttribute(): Attribute
----

==== Description

Casts the concept to ``Attribute``.

==== Returns

`Attribute`

==== Code examples

[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
=== asAttributeType

==== Signature

[source,nodejs]
----
asAttributeType(): AttributeType
----

==== Description

Casts the concept to ``AttributeType``.

==== Returns

`AttributeType`

==== Code examples

[source,nodejs]
----
concept.asAttributeType()
----

[#_asEntity]
=== asEntity

==== Signature

[source,nodejs]
----
asEntity(): Entity
----

==== Description

Casts the concept to ``Entity``.

==== Returns

`Entity`

==== Code examples

[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
=== asEntityType

==== Signature

[source,nodejs]
----
asEntityType(): EntityType
----

==== Description

Casts the concept to ``EntityType``.

==== Returns

`EntityType`

==== Code examples

[source,nodejs]
----
concept.asEntityType()
----

[#_asRelation]
=== asRelation

==== Signature

[source,nodejs]
----
asRelation(): Relation
----

==== Description

Casts the concept to ``Relation``.

==== Returns

`Relation`

==== Code examples

[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
=== asRelationType

==== Signature

[source,nodejs]
----
asRelationType(): RelationType
----

==== Description

Casts the concept to ``RelationType``.

==== Returns

`RelationType`

==== Code examples

[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
=== asRoleType

==== Signature

[source,nodejs]
----
asRoleType(): RoleType
----

==== Description

Casts the concept to ``RoleType``.

==== Returns

`RoleType`

==== Code examples

[source,nodejs]
----
concept.asRoleType()
----

[#_asThing]
=== asThing

==== Signature

[source,nodejs]
----
asThing(): Thing
----

==== Description

Casts the concept to ``Thing``.

==== Returns

`Thing`

==== Code examples

[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
=== asThingType

==== Signature

[source,nodejs]
----
asThingType(): ThingType
----

==== Description

Casts the concept to ``ThingType``.

==== Returns

`ThingType`

==== Code examples

[source,nodejs]
----
concept.asThingType()
----

[#_asType]
=== asType

==== Signature

[source,nodejs]
----
asType(): Type
----

==== Description

Casts the concept to ``Type``.

==== Returns

`Type`

==== Code examples

[source,nodejs]
----
concept.asType()
----

[#_asValue]
=== asValue

==== Signature

[source,nodejs]
----
asValue(): Value
----

==== Description

Casts the concept to ``Value``.

==== Returns

`Value`

==== Code examples

[source,nodejs]
----
concept.asValue()
----

[#_delete]
=== delete

==== Signature

[source,nodejs]
----
delete(transaction): Promise<void>
----

==== Description

Deletes this ``Thing``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thing.delete(transaction)
----

[#_equals]
=== equals

==== Signature

[source,nodejs]
----
equals(concept): boolean
----

==== Description

Checks if this concept is equal to the argument ``concept``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept` 
|===

==== Returns

`boolean`

[#_getHas]
=== getHas

==== Signature

[source,nodejs]
----
getHas(transaction): Stream<Attribute>
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
=== getHas

==== Signature

[source,nodejs]
----
getHas(transaction, annotations): Stream<Attribute>
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| The ``AttributeType``s to filter the attributes by a| `Annotation[]` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
=== getHas

==== Signature

[source,nodejs]
----
getHas(transaction, attributeType): Stream<Attribute>
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The ``AttributeType``s to filter the attributes by a| `AttributeType` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
=== getHas

==== Signature

[source,nodejs]
----
getHas(transaction, attributeTypes): Stream<Attribute>
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
=== getHas

==== Signature

[source,nodejs]
----
getHas(transaction, attributeTypes, annotations): Stream<Attribute>
----

==== Description

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]` 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Annotation[]` 
|===

==== Returns

`Stream<Attribute>`

==== Code examples

[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getPlaying]
=== getPlaying

==== Signature

[source,nodejs]
----
getPlaying(transaction): Stream<RoleType>
----

==== Description

Retrieves the roles that this ``Thing`` is currently playing.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<RoleType>`

==== Code examples

[source,nodejs]
----
thing.getPlaying(transaction)
----

[#_getRelations]
=== getRelations

==== Signature

[source,nodejs]
----
getRelations(transaction): Stream<Relation>
----

==== Description

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<Relation>`

==== Code examples

[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_getRelations]
=== getRelations

==== Signature

[source,nodejs]
----
getRelations(transaction, roleTypes): Stream<Relation>
----

==== Description

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleTypes` a| The list of roles to filter the relations by. a| `RoleType[]` 
|===

==== Returns

`Stream<Relation>`

==== Code examples

[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_isAttribute]
=== isAttribute

==== Signature

[source,nodejs]
----
isAttribute(): boolean
----

==== Description

Checks if the concept is an ``Attribute``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
=== isAttributeType

==== Signature

[source,nodejs]
----
isAttributeType(): boolean
----

==== Description

Checks if the concept is an ``AttributeType``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttributeType()
----

[#_isDeleted]
=== isDeleted

==== Signature

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

==== Description

Checks if this ``Thing`` is deleted.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<boolean>`

==== Code examples

[source,nodejs]
----
thing.isDeleted(transaction)
----

[#_isEntity]
=== isEntity

==== Signature

[source,nodejs]
----
isEntity(): boolean
----

==== Description

Checks if the concept is an ``Entity``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
=== isEntityType

==== Signature

[source,nodejs]
----
isEntityType(): boolean
----

==== Description

Checks if the concept is an ``EntityType``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntityType()
----

[#_isRelation]
=== isRelation

==== Signature

[source,nodejs]
----
isRelation(): boolean
----

==== Description

Checks if the concept is a ``Relation``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
=== isRelationType

==== Signature

[source,nodejs]
----
isRelationType(): boolean
----

==== Description

Checks if the concept is a ``RelationType``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
=== isRoleType

==== Signature

[source,nodejs]
----
isRoleType(): boolean
----

==== Description

Checks if the concept is a ``RoleType``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRoleType()
----

[#_isThing]
=== isThing

==== Signature

[source,nodejs]
----
isThing(): boolean
----

==== Description

Checks if the concept is a ``Thing``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
=== isThingType

==== Signature

[source,nodejs]
----
isThingType(): boolean
----

==== Description

Checks if the concept is a ``ThingType``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThingType()
----

[#_isType]
=== isType

==== Signature

[source,nodejs]
----
isType(): boolean
----

==== Description

Checks if the concept is a ``Type``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isType()
----

[#_isValue]
=== isValue

==== Signature

[source,nodejs]
----
isValue(): boolean
----

==== Description

Checks if the concept is a ``Value``.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isValue()
----

[#_setHas]
=== setHas

==== Signature

[source,nodejs]
----
setHas(transaction, attribute): Promise<void>
----

==== Description

Assigns an ``Attribute`` to be owned by this ``Thing``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thing.setHas(transaction, attribute)
----

[#_toJSONRecord]
=== toJSONRecord

==== Signature

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

==== Description

Retrieves the concept as JSON.

==== Returns

`Record<string, string | number | boolean>`

==== Code examples

[source,nodejs]
----
concept.toJSONRecord()
----

[#_unsetHas]
=== unsetHas

==== Signature

[source,nodejs]
----
unsetHas(transaction, attribute): Promise<void>
----

==== Description

Unassigns an ``Attribute`` from this ``Thing``.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
thing.unsetHas(transaction, attribute)
----

// end::methods[]
