[#_ErrorMessage]
= ErrorMessage

== Description

Class defining the error-code and message template for `TypeDBDriverError`s

== Methods

// tag::methods[]
[#_new_ErrorMessage]
=== new ErrorMessage

==== Signature

[source,nodejs]
----
new ErrorMessage(codePrefix, codeNumber, messagePrefix, messageBody): ErrorMessage
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `codePrefix` a| null a| `string` 
a| `codeNumber` a| null a| `number` 
a| `messagePrefix` a| null a| `string` 
a| `messageBody` a| null a| `((args) => string)` 
|===

==== Returns

`ErrorMessage`

[#_code]
=== code

==== Signature

[source,nodejs]
----
code(): string
----

==== Description

Retrieves the error-code for this ErrorMessage

==== Returns

`string`

[#_message]
=== message

==== Signature

[source,nodejs]
----
message(...args): string
----

==== Description

Generates the error message by substituting `args` into the messageTemplate

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `args` a| The format arguments to the message-template. a| `Stringable[]` 
|===

==== Returns

`string`

[#_toString]
=== toString

==== Signature

[source,nodejs]
----
toString(): string
----

==== Description

Summarises the error into a string

==== Returns

`string`

// end::methods[]
