[#_Explainables]
= Explainables

== Description

Contains explainable objects.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `attributes` a| `Map` a| All of this ConceptMap’s explainable attributes.
a| `ownerships` a| `Map` a| All of this ConceptMap’s explainable ownerships.
a| `relations` a| `Map` a| All of this ConceptMap’s explainable relations.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_attribute]
=== attribute

==== Signature

[source,nodejs]
----
attribute(variable): Explainable
----

==== Description

Retrieves the explainable attribute with the given variable name.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `string` 
|===

==== Returns

`Explainable`

==== Code examples

[source,nodejs]
----
conceptMap.explainables.attribute(variable)
----

[#_ownership]
=== ownership

==== Signature

[source,nodejs]
----
ownership(owner, attribute): Explainable
----

==== Description

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `owner` a| The string representation of the owner variable a| `string` 
a| `attribute` a| The string representation of the attribute variable a| `string` 
|===

==== Returns

`Explainable`

==== Code examples

[source,nodejs]
----
conceptMap.explainables.ownership(owner, attribute)
----

[#_relation]
=== relation

==== Signature

[source,nodejs]
----
relation(variable): Explainable
----

==== Description

Retrieves the explainable relation with the given variable name.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `string` 
|===

==== Returns

`Explainable`

==== Code examples

[source,nodejs]
----
conceptMap.explainables.relation(variable)
----

// end::methods[]
