[#_QueryManager]
= QueryManager

== Description

Provides methods for executing TypeQL queries in the transaction.

== Methods

// tag::methods[]
[#_define]
=== define

==== Signature

[source,nodejs]
----
define(query, options?): Promise<void>
----

==== Description

Performs a TypeQL Define query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
transaction.query.define(query, options)
----

[#_delete]
=== delete

==== Signature

[source,nodejs]
----
delete(query, options?): Promise<void>
----

==== Description

Performs a TypeQL Delete query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
transaction.query.delete(query, options)
----

[#_explain]
=== explain

==== Signature

[source,nodejs]
----
explain(explainable, options?): Stream<Explanation>
----

==== Description

Performs a TypeQL Explain query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `Explainable` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<Explanation>`

==== Code examples

[source,nodejs]
----
transaction.query.explain(explainable, options)
----

[#_insert]
=== insert

==== Signature

[source,nodejs]
----
insert(query, options?): Stream<ConceptMap>
----

==== Description

Performs a TypeQL Insert query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<ConceptMap>`

==== Code examples

[source,nodejs]
----
transaction.query.insert(query, options)
----

[#_match]
=== match

==== Signature

[source,nodejs]
----
match(query, options?): Stream<ConceptMap>
----

==== Description

Performs a TypeQL Match (Get) query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match (Get) query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<ConceptMap>`

==== Code examples

[source,nodejs]
----
transaction.query.match(query, options)
----

[#_matchAggregate]
=== matchAggregate

==== Signature

[source,nodejs]
----
matchAggregate(query, options?): Promise<Numeric>
----

==== Description

Performs a TypeQL Match Aggregate query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Aggregate query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Promise<Numeric>`

==== Code examples

[source,nodejs]
----
transaction.query.matchAggregate(query, options)
----

[#_matchGroup]
=== matchGroup

==== Signature

[source,nodejs]
----
matchGroup(query, options?): Stream<ConceptMapGroup>
----

==== Description

Performs a TypeQL Match Group query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<ConceptMapGroup>`

==== Code examples

[source,nodejs]
----
transaction.query.matchGroup(query, options)
----

[#_matchGroupAggregate]
=== matchGroupAggregate

==== Signature

[source,nodejs]
----
matchGroupAggregate(query, options?): Stream<NumericGroup>
----

==== Description

Performs a TypeQL Match Group Aggregate query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Match Group Aggregate query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<NumericGroup>`

==== Code examples

[source,nodejs]
----
transaction.query.matchGroupAggregate(query, options)
----

[#_undefine]
=== undefine

==== Signature

[source,nodejs]
----
undefine(query, options?): Promise<void>
----

==== Description

Performs a TypeQL Undefine query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
transaction.query.undefine(query, options)
----

[#_update]
=== update

==== Signature

[source,nodejs]
----
update(query, options?): Stream<ConceptMap>
----

==== Description

Performs a TypeQL Update query in the transaction.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `string` 
a| `options` a| Specify query options a| `TypeDBOptions` 
|===

==== Returns

`Stream<ConceptMap>`

==== Code examples

[source,nodejs]
----
transaction.query.update(query, options)
----

// end::methods[]
