[#_Relation]
=== Relation

*Supertypes:*

* `Thing`

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `iid` a| `string` a| Retrieves the unique id of the Thing.
a| `inferred` a| `boolean` a| Checks if this Thing is inferred by a [Reasoning Rule].
a| `type` a| `RelationType` a| The type which this Relation belongs to.
|===
// end::properties[]

// tag::methods[]
[#_addRolePlayer]
==== addRolePlayer

[source,nodejs]
----
addRolePlayer(transaction, roleType, player): Promise<void>
----

Adds a new role player to play the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to be played by the ``player`` a| `RoleType` 
a| `player` a| The thing to play the role a| `Thing` 
|===

.Returns
`Promise<void>`

.Code examples
[source,nodejs]
----
relation.addRolePlayer(transaction, roleType, player)
----

[#_asAttribute]
==== asAttribute

[source,nodejs]
----
asAttribute(): Attribute
----

Casts the concept to ``Attribute``.

.Returns
`Attribute`

.Code examples
[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
==== asAttributeType

[source,nodejs]
----
asAttributeType(): AttributeType
----

Casts the concept to ``AttributeType``.

.Returns
`AttributeType`

.Code examples
[source,nodejs]
----
concept.asAttributeType()
----

[#_asEntity]
==== asEntity

[source,nodejs]
----
asEntity(): Entity
----

Casts the concept to ``Entity``.

.Returns
`Entity`

.Code examples
[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
==== asEntityType

[source,nodejs]
----
asEntityType(): EntityType
----

Casts the concept to ``EntityType``.

.Returns
`EntityType`

.Code examples
[source,nodejs]
----
concept.asEntityType()
----

[#_asRelation]
==== asRelation

[source,nodejs]
----
asRelation(): Relation
----

Casts the concept to ``Relation``.

.Returns
`Relation`

.Code examples
[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
==== asRelationType

[source,nodejs]
----
asRelationType(): RelationType
----

Casts the concept to ``RelationType``.

.Returns
`RelationType`

.Code examples
[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
==== asRoleType

[source,nodejs]
----
asRoleType(): RoleType
----

Casts the concept to ``RoleType``.

.Returns
`RoleType`

.Code examples
[source,nodejs]
----
concept.asRoleType()
----

[#_asThing]
==== asThing

[source,nodejs]
----
asThing(): Thing
----

Casts the concept to ``Thing``.

.Returns
`Thing`

.Code examples
[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
==== asThingType

[source,nodejs]
----
asThingType(): ThingType
----

Casts the concept to ``ThingType``.

.Returns
`ThingType`

.Code examples
[source,nodejs]
----
concept.asThingType()
----

[#_asType]
==== asType

[source,nodejs]
----
asType(): Type
----

Casts the concept to ``Type``.

.Returns
`Type`

.Code examples
[source,nodejs]
----
concept.asType()
----

[#_asValue]
==== asValue

[source,nodejs]
----
asValue(): Value
----

Casts the concept to ``Value``.

.Returns
`Value`

.Code examples
[source,nodejs]
----
concept.asValue()
----

[#_delete]
==== delete

[source,nodejs]
----
delete(transaction): Promise<void>
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Promise<void>`

.Code examples
[source,nodejs]
----
thing.delete(transaction)
----

[#_equals]
==== equals

[source,nodejs]
----
equals(concept): boolean
----

Checks if this concept is equal to the argument ``concept``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept` 
|===

.Returns
`boolean`

[#_getHas]
==== getHas

[source,nodejs]
----
getHas(transaction): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Stream<Attribute>`

.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
==== getHas

[source,nodejs]
----
getHas(transaction, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `annotations` a| The ``AttributeType``s to filter the attributes by a| `Annotation[]` 
|===

.Returns
`Stream<Attribute>`

.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeType): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeType` a| The ``AttributeType``s to filter the attributes by a| `AttributeType` 
|===

.Returns
`Stream<Attribute>`

.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]` 
|===

.Returns
`Stream<Attribute>`

.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getHas]
==== getHas

[source,nodejs]
----
getHas(transaction, attributeTypes, annotations): Stream<Attribute>
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attributeTypes` a| The ``AttributeType``s to filter the attributes by a| `AttributeType[]` 
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `Annotation[]` 
|===

.Returns
`Stream<Attribute>`

.Code examples
[source,nodejs]
----
thing.getHas(transaction) thing.getHas(transaction, attributeType, [Annotation.KEY])
----

[#_getPlayersByRoleType]
==== getPlayersByRoleType

[source,nodejs]
----
getPlayersByRoleType(transaction): Stream<Thing>
----

Retrieves all role players of this ``Relation``, optionally filtered by given role types.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Stream<Thing>`

.Code examples
[source,nodejs]
----
relation.getPlayersByRoleType(transaction) relation.getPlayersByRoleType(transaction, [roleType1, roleType2])
----

[#_getPlayersByRoleType]
==== getPlayersByRoleType

[source,nodejs]
----
getPlayersByRoleType(transaction, roleTypes): Stream<Thing>
----

Retrieves all role players of this ``Relation``, optionally filtered by given role types.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleTypes` a| 0 or more role types a| `RoleType[]` 
|===

.Returns
`Stream<Thing>`

.Code examples
[source,nodejs]
----
relation.getPlayersByRoleType(transaction) relation.getPlayersByRoleType(transaction, [roleType1, roleType2])
----

[#_getPlaying]
==== getPlaying

[source,nodejs]
----
getPlaying(transaction): Stream<RoleType>
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Stream<RoleType>`

.Code examples
[source,nodejs]
----
thing.getPlaying(transaction)
----

[#_getRelating]
==== getRelating

[source,nodejs]
----
getRelating(transaction): Stream<RoleType>
----

Retrieves all role types currently played in this ``Relation``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Stream<RoleType>`

.Code examples
[source,nodejs]
----
relation.getRelating(transaction)
----

[#_getRelations]
==== getRelations

[source,nodejs]
----
getRelations(transaction): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Stream<Relation>`

.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_getRelations]
==== getRelations

[source,nodejs]
----
getRelations(transaction, roleTypes): Stream<Relation>
----

Retrieves all the ``Relations`` which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleTypes` a| The list of roles to filter the relations by. a| `RoleType[]` 
|===

.Returns
`Stream<Relation>`

.Code examples
[source,nodejs]
----
thing.getRelations(transaction, roleTypes)
----

[#_getRolePlayers]
==== getRolePlayers

[source,nodejs]
----
getRolePlayers(transaction): Promise<Map<RoleType, Thing[]>>
----

Retrieves a mapping of all instances involved in the ``Relation`` and the role each play.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Promise<Map<RoleType, Thing[]>>`

.Code examples
[source,nodejs]
----
relation.getRolePlayers(transaction)
----

[#_isAttribute]
==== isAttribute

[source,nodejs]
----
isAttribute(): boolean
----

Checks if the concept is an ``Attribute``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
==== isAttributeType

[source,nodejs]
----
isAttributeType(): boolean
----

Checks if the concept is an ``AttributeType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isAttributeType()
----

[#_isDeleted]
==== isDeleted

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

.Returns
`Promise<boolean>`

.Code examples
[source,nodejs]
----
thing.isDeleted(transaction)
----

[#_isEntity]
==== isEntity

[source,nodejs]
----
isEntity(): boolean
----

Checks if the concept is an ``Entity``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
==== isEntityType

[source,nodejs]
----
isEntityType(): boolean
----

Checks if the concept is an ``EntityType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isEntityType()
----

[#_isRelation]
==== isRelation

[source,nodejs]
----
isRelation(): boolean
----

Checks if the concept is a ``Relation``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
==== isRelationType

[source,nodejs]
----
isRelationType(): boolean
----

Checks if the concept is a ``RelationType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
==== isRoleType

[source,nodejs]
----
isRoleType(): boolean
----

Checks if the concept is a ``RoleType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isRoleType()
----

[#_isThing]
==== isThing

[source,nodejs]
----
isThing(): boolean
----

Checks if the concept is a ``Thing``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
==== isThingType

[source,nodejs]
----
isThingType(): boolean
----

Checks if the concept is a ``ThingType``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isThingType()
----

[#_isType]
==== isType

[source,nodejs]
----
isType(): boolean
----

Checks if the concept is a ``Type``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isType()
----

[#_isValue]
==== isValue

[source,nodejs]
----
isValue(): boolean
----

Checks if the concept is a ``Value``.

.Returns
`boolean`

.Code examples
[source,nodejs]
----
concept.isValue()
----

[#_removeRolePlayer]
==== removeRolePlayer

[source,nodejs]
----
removeRolePlayer(transaction, roleType, player): Promise<void>
----

Removes the association of the given instance that plays the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `roleType` a| The role to no longer be played by the thing in this ``Relation`` a| `RoleType` 
a| `player` a| The instance to no longer play the role in this ``Relation`` a| `Thing` 
|===

.Returns
`Promise<void>`

.Code examples
[source,nodejs]
----
relation.removeRolePlayer(transaction, roleType, player)
----

[#_setHas]
==== setHas

[source,nodejs]
----
setHas(transaction, attribute): Promise<void>
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` 
|===

.Returns
`Promise<void>`

.Code examples
[source,nodejs]
----
thing.setHas(transaction, attribute)
----

[#_toJSONRecord]
==== toJSONRecord

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

Retrieves the concept as JSON.

.Returns
`Record<string, string | number | boolean>`

.Code examples
[source,nodejs]
----
concept.toJSONRecord()
----

[#_unsetHas]
==== unsetHas

[source,nodejs]
----
unsetHas(transaction, attribute): Promise<void>
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` 
|===

.Returns
`Promise<void>`

.Code examples
[source,nodejs]
----
thing.unsetHas(transaction, attribute)
----

// end::methods[]
