[#_RoleType]
= RoleType

*Supertypes:*

* `Type`

== Description

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type. Roles allow a schema to enforce logical constraints on types of role players.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `abstract` a| `boolean` a| Whether the type is prevented from having data instances (i.e., abstract).
a| `label` a| `Label` a| The unique label of the type.
a| `root` a| `boolean` a| Whether the type is a root type.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_asAttribute]
=== asAttribute

==== Signature

[source,nodejs]
----
asAttribute(): Attribute
----

==== Description

Casts the concept to `Attribute`.

==== Returns

`Attribute`

==== Code examples

[source,nodejs]
----
concept.asAttribute()
----

[#_asAttributeType]
=== asAttributeType

==== Signature

[source,nodejs]
----
asAttributeType(): AttributeType
----

==== Description

Casts the concept to `AttributeType`.

==== Returns

`AttributeType`

==== Code examples

[source,nodejs]
----
concept.asAttributeType()
----

[#_asEntity]
=== asEntity

==== Signature

[source,nodejs]
----
asEntity(): Entity
----

==== Description

Casts the concept to `Entity`.

==== Returns

`Entity`

==== Code examples

[source,nodejs]
----
concept.asEntity()
----

[#_asEntityType]
=== asEntityType

==== Signature

[source,nodejs]
----
asEntityType(): EntityType
----

==== Description

Casts the concept to `EntityType`.

==== Returns

`EntityType`

==== Code examples

[source,nodejs]
----
concept.asEntityType()
----

[#_asRelation]
=== asRelation

==== Signature

[source,nodejs]
----
asRelation(): Relation
----

==== Description

Casts the concept to `Relation`.

==== Returns

`Relation`

==== Code examples

[source,nodejs]
----
concept.asRelation()
----

[#_asRelationType]
=== asRelationType

==== Signature

[source,nodejs]
----
asRelationType(): RelationType
----

==== Description

Casts the concept to `RelationType`.

==== Returns

`RelationType`

==== Code examples

[source,nodejs]
----
concept.asRelationType()
----

[#_asRoleType]
=== asRoleType

==== Signature

[source,nodejs]
----
asRoleType(): RoleType
----

==== Description

Casts the concept to `RoleType`.

==== Returns

`RoleType`

==== Code examples

[source,nodejs]
----
concept.asRoleType()
----

[#_asThing]
=== asThing

==== Signature

[source,nodejs]
----
asThing(): Thing
----

==== Description

Casts the concept to `Thing`.

==== Returns

`Thing`

==== Code examples

[source,nodejs]
----
concept.asThing()
----

[#_asThingType]
=== asThingType

==== Signature

[source,nodejs]
----
asThingType(): ThingType
----

==== Description

Casts the concept to `ThingType`.

==== Returns

`ThingType`

==== Code examples

[source,nodejs]
----
concept.asThingType()
----

[#_asType]
=== asType

==== Signature

[source,nodejs]
----
asType(): Type
----

==== Description

Casts the concept to `Type`.

==== Returns

`Type`

==== Code examples

[source,nodejs]
----
concept.asType()
----

[#_asValue]
=== asValue

==== Signature

[source,nodejs]
----
asValue(): Value
----

==== Description

Casts the concept to `Value`.

==== Returns

`Value`

==== Code examples

[source,nodejs]
----
concept.asValue()
----

[#_delete]
=== delete

==== Signature

[source,nodejs]
----
delete(transaction): Promise<void>
----

==== Description

Deletes this type from the database.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
type.delete(transaction)
----

[#_equals]
=== equals

==== Signature

[source,nodejs]
----
equals(concept): boolean
----

==== Description

Checks if this concept is equal to the argument `concept`.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `concept` a| The concept to compare to. a| `Concept` 
|===

==== Returns

`boolean`

[#_getPlayerInstances]
=== getPlayerInstances

==== Signature

[source,nodejs]
----
getPlayerInstances(transaction): Stream<Thing>
----

==== Description

Retrieves the `Thing` instances that play this role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<Thing>`

==== Code examples

[source,nodejs]
----
roleType.getPlayerInstances(transaction, transitivity)
----

[#_getPlayerInstances]
=== getPlayerInstances

==== Signature

[source,nodejs]
----
getPlayerInstances(transaction, transitivity): Stream<Thing>
----

==== Description

Retrieves the `Thing` instances that play this role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect playing, `Transitivity.EXPLICIT` for direct playing only a| `Transitivity` 
|===

==== Returns

`Stream<Thing>`

==== Code examples

[source,nodejs]
----
roleType.getPlayerInstances(transaction, transitivity)
----

[#_getPlayerTypes]
=== getPlayerTypes

==== Signature

[source,nodejs]
----
getPlayerTypes(transaction): Stream<ThingType>
----

==== Description

Retrieves the `ThingType`s whose instances play this role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<ThingType>`

==== Code examples

[source,nodejs]
----
roleType.getPlayerTypes(transaction, transitivity)
----

[#_getPlayerTypes]
=== getPlayerTypes

==== Signature

[source,nodejs]
----
getPlayerTypes(transaction, transitivity): Stream<ThingType>
----

==== Description

Retrieves the `ThingType`s whose instances play this role.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect playing, `Transitivity.EXPLICIT` for direct playing only a| `Transitivity` 
|===

==== Returns

`Stream<ThingType>`

==== Code examples

[source,nodejs]
----
roleType.getPlayerTypes(transaction, transitivity)
----

[#_getRelationInstances]
=== getRelationInstances

==== Signature

[source,nodejs]
----
getRelationInstances(transaction): Stream<Relation>
----

==== Description

Retrieves the `Relation` instances that this role is related to.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<Relation>`

==== Code examples

[source,nodejs]
----
roleType.getRelationInstances(transaction, transitivity)
----

[#_getRelationInstances]
=== getRelationInstances

==== Signature

[source,nodejs]
----
getRelationInstances(transaction, transitivity): Stream<Relation>
----

==== Description

Retrieves the `Relation` instances that this role is related to.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `transitivity` a| `Transitivity.TRANSITIVE` for direct and indirect relation, `Transitivity.EXPLICIT` for direct relation only a| `Transitivity` 
|===

==== Returns

`Stream<Relation>`

==== Code examples

[source,nodejs]
----
roleType.getRelationInstances(transaction, transitivity)
----

[#_getRelationType]
=== getRelationType

==== Signature

[source,nodejs]
----
getRelationType(transaction): Promise<RelationType>
----

==== Description

Retrieves the `RelationType` that this role is directly related to.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<RelationType>`

==== Code examples

[source,nodejs]
----
roleType.getRelationType(transaction)
----

[#_getRelationTypes]
=== getRelationTypes

==== Signature

[source,nodejs]
----
getRelationTypes(transaction): Stream<RelationType>
----

==== Description

Retrieves `RelationType`s that this role is related to (directly or indirectly).

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<RelationType>`

==== Code examples

[source,nodejs]
----
roleType.getRelationTypes(transaction)
----

[#_getSubtypes]
=== getSubtypes

==== Signature

[source,nodejs]
----
getSubtypes(transaction): Stream<RoleType>
----

==== Description

Retrieves all direct and indirect (or direct only) subtypes of the type.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<RoleType>`

==== Code examples

[source,nodejs]
----
type.getSubtypes(transaction) type.getSubtypes(transaction, Transitivity.EXPLICIT)
----

[#_getSupertype]
=== getSupertype

==== Signature

[source,nodejs]
----
getSupertype(transaction): Promise<RoleType>
----

==== Description

Retrieves the most immediate supertype of the type.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<RoleType>`

==== Code examples

[source,nodejs]
----
type.getSupertype(transaction)
----

[#_getSupertypes]
=== getSupertypes

==== Signature

[source,nodejs]
----
getSupertypes(transaction): Stream<RoleType>
----

==== Description

Retrieves all supertypes of the type.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Stream<RoleType>`

==== Code examples

[source,nodejs]
----
type.getSupertypes(transaction)
----

[#_isAttribute]
=== isAttribute

==== Signature

[source,nodejs]
----
isAttribute(): boolean
----

==== Description

Checks if the concept is an `Attribute`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttribute()
----

[#_isAttributeType]
=== isAttributeType

==== Signature

[source,nodejs]
----
isAttributeType(): boolean
----

==== Description

Checks if the concept is an `AttributeType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isAttributeType()
----

[#_isDeleted]
=== isDeleted

==== Signature

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

==== Description

Check if the concept has been deleted

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
|===

==== Returns

`Promise<boolean>`

[#_isEntity]
=== isEntity

==== Signature

[source,nodejs]
----
isEntity(): boolean
----

==== Description

Checks if the concept is an `Entity`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntity()
----

[#_isEntityType]
=== isEntityType

==== Signature

[source,nodejs]
----
isEntityType(): boolean
----

==== Description

Checks if the concept is an `EntityType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isEntityType()
----

[#_isRelation]
=== isRelation

==== Signature

[source,nodejs]
----
isRelation(): boolean
----

==== Description

Checks if the concept is a `Relation`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelation()
----

[#_isRelationType]
=== isRelationType

==== Signature

[source,nodejs]
----
isRelationType(): boolean
----

==== Description

Checks if the concept is a `RelationType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRelationType()
----

[#_isRoleType]
=== isRoleType

==== Signature

[source,nodejs]
----
isRoleType(): boolean
----

==== Description

Checks if the concept is a `RoleType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isRoleType()
----

[#_isThing]
=== isThing

==== Signature

[source,nodejs]
----
isThing(): boolean
----

==== Description

Checks if the concept is a `Thing`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThing()
----

[#_isThingType]
=== isThingType

==== Signature

[source,nodejs]
----
isThingType(): boolean
----

==== Description

Checks if the concept is a `ThingType`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isThingType()
----

[#_isType]
=== isType

==== Signature

[source,nodejs]
----
isType(): boolean
----

==== Description

Checks if the concept is a `Type`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isType()
----

[#_isValue]
=== isValue

==== Signature

[source,nodejs]
----
isValue(): boolean
----

==== Description

Checks if the concept is a `Value`.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
concept.isValue()
----

[#_setLabel]
=== setLabel

==== Signature

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

==== Description

Renames the label of the type. The new label must remain unique.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `TypeDBTransaction` 
a| `label` a| The new `Label` to be given to the type. a| `string` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
type.setLabel(transaction, label)
----

[#_toJSONRecord]
=== toJSONRecord

==== Signature

[source,nodejs]
----
toJSONRecord(): Record<string, string | number | boolean>
----

==== Description

Retrieves the concept as JSON.

==== Returns

`Record<string, string | number | boolean>`

==== Code examples

[source,nodejs]
----
concept.toJSONRecord()
----

// end::methods[]
