[#_Rule]
= Rule

== Description

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `string` a| The unique label of the rule.
a| `then` a| `string` a| The single statement that constitutes the ‘then’ of the rule.
a| `when` a| `string` a| The statements that constitute the ‘when’ of the rule.
|===
// end::properties[]

== Methods

// tag::methods[]
[#_delete]
=== delete

==== Signature

[source,nodejs]
----
delete(transaction): Promise<void>
----

==== Description

Deletes this rule.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
rule.delete(transaction)
----

[#_isDeleted]
=== isDeleted

==== Signature

[source,nodejs]
----
isDeleted(transaction): Promise<boolean>
----

==== Description

Check if this rule has been deleted.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` 
|===

==== Returns

`Promise<boolean>`

==== Code examples

[source,nodejs]
----
rule.isDeleted(transaction)
----

[#_setLabel]
=== setLabel

==== Signature

[source,nodejs]
----
setLabel(transaction, label): Promise<void>
----

==== Description

Renames the label of the rule. The new label must remain unique.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` 
a| `label` a| null a| `string` 
|===

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
rule.setLabel(transaction, newLabel)
----

// end::methods[]
