[#_TypeDBDriverError]
= TypeDBDriverError

*Supertypes:*

* `Error`

== Description

Errors encountered when interacting with TypeDB

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `message` a| `string` a| 
a| `name` a| `string` a| 
a| `stack` a| `string` a| 
a| `prepareStackTrace` a| `any` a| 
a| `stackTraceLimit` a| `number` a| 
|===
// end::properties[]

== Methods

// tag::methods[]
[#_new_TypeDBDriverError]
=== new TypeDBDriverError

==== Signature

[source,nodejs]
----
new TypeDBDriverError(error): TypeDBDriverError
----

==== Description



==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `error` a| null a| `string \| ErrorMessage \| Error \| ServiceError` 
|===

==== Returns

`TypeDBDriverError`

[#_captureStackTrace]
=== captureStackTrace

==== Signature

[source,nodejs]
----
captureStackTrace(targetObject, constructorOpt?): void
----

==== Description

Create .stack property on a target object

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `targetObject` a| null a| `object` 
a| `constructorOpt` a| null a| `Function` 
|===

==== Returns

`void`

[#__messageTemplate]
===  messageTemplate

==== Signature

[source,nodejs]
----
get messageTemplate(): ErrorMessage
----

==== Description

Returns the message template for this error.

==== Returns

`ErrorMessage`

// end::methods[]
