[#_TypeDBSession]
= TypeDBSession

== Fields

// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `database` a| `Database` a| The database of the session. Examples session.database()
Copy
a| `options` a| `TypeDBOptions` a| Gets the options for the session
a| `type` a| `SessionType` a| The current session’s type (SCHEMA or DATA)
|===
// end::properties[]

== Methods

// tag::methods[]
[#_close]
=== close

==== Signature

[source,nodejs]
----
close(): Promise<void>
----

==== Description

Closes the session. Before opening a new session, the session currently open should first be closed.

==== Returns

`Promise<void>`

==== Code examples

[source,nodejs]
----
session.close()
----

[#_isOpen]
=== isOpen

==== Signature

[source,nodejs]
----
isOpen(): boolean
----

==== Description

Checks whether this session is open.

==== Returns

`boolean`

==== Code examples

[source,nodejs]
----
session.isOpen()
----

[#_transaction]
=== transaction

==== Signature

[source,nodejs]
----
transaction(type, options?): Promise<TypeDBTransaction>
----

==== Description

Opens a transaction to perform read or write queries on the database connected to the session.

==== Input parameters

[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `type` a| null a| `TransactionType` 
a| `options` a| Options for the session a| `TypeDBOptions` 
|===

==== Returns

`Promise<TypeDBTransaction>`

==== Code examples

[source,nodejs]
----
session.transaction(transactionType, options)
----

// end::methods[]
