[#_ConceptManager]
=== ConceptManager

*Package*: `TypeDB`



Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptPtrFuture_Attribute__TypeDBConceptManagergetAttribute___const_stdstring__iid___const]
==== getAttribute

[source,cpp]
----
ConceptPtrFuture<Attribute> TypeDB::ConceptManager::getAttribute(const std::string& iid) const
----



Retrieves an ``Attribute`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture_AttributeType__TypeDBConceptManagergetAttributeType___const_stdstring__label___const]
==== getAttributeType

[source,cpp]
----
ConceptPtrFuture<AttributeType> TypeDB::ConceptManager::getAttributeType(const std::string& label) const
----



Retrieves an ``AttributeType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_ConceptPtrFuture_Entity__TypeDBConceptManagergetEntity___const_stdstring__iid___const]
==== getEntity

[source,cpp]
----
ConceptPtrFuture<Entity> TypeDB::ConceptManager::getEntity(const std::string& iid) const
----



Retrieves an ``Entity`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Entity >`

[#_ConceptPtrFuture_EntityType__TypeDBConceptManagergetEntityType___const_stdstring__label___const]
==== getEntityType

[source,cpp]
----
ConceptPtrFuture<EntityType> TypeDB::ConceptManager::getEntityType(const std::string& label) const
----



Retrieves an ``EntityType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[#_ConceptPtrFuture_Relation__TypeDBConceptManagergetRelation___const_stdstring__iid___const]
==== getRelation

[source,cpp]
----
ConceptPtrFuture<Relation> TypeDB::ConceptManager::getRelation(const std::string& iid) const
----



Retrieves a ``Relation`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Relation >`

[#_ConceptPtrFuture_RelationType__TypeDBConceptManagergetRelationType___const_stdstring__label___const]
==== getRelationType

[source,cpp]
----
ConceptPtrFuture<RelationType> TypeDB::ConceptManager::getRelationType(const std::string& label) const
----



Retrieves a ``RelationType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[#_stdunique_ptr_AttributeType__TypeDBConceptManagergetRootAttributeType_____const]
==== getRootAttributeType

[source,cpp]
----
std::unique_ptr<AttributeType> TypeDB::ConceptManager::getRootAttributeType() const
----



Retrieve the root ``AttributeType``, “attribute”.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[#_stdunique_ptr_EntityType__TypeDBConceptManagergetRootEntityType_____const]
==== getRootEntityType

[source,cpp]
----
std::unique_ptr<EntityType> TypeDB::ConceptManager::getRootEntityType() const
----



Retrieves the root ``EntityType``, “entity”.


[caption=""]
.Returns
`std::unique_ptr< EntityType >`

[#_stdunique_ptr_RelationType__TypeDBConceptManagergetRootRelationType_____const]
==== getRootRelationType

[source,cpp]
----
std::unique_ptr<RelationType> TypeDB::ConceptManager::getRootRelationType() const
----



Retrieve the root ``RelationType``, “relation”.


[caption=""]
.Returns
`std::unique_ptr< RelationType >`

[#_stdvector_DriverException__TypeDBConceptManagergetSchemaExceptions___]
==== getSchemaExceptions

[source,cpp]
----
std::vector<DriverException> TypeDB::ConceptManager::getSchemaExceptions()
----



Retrieves a list of all schema exceptions for the current transaction.


[caption=""]
.Returns
`std::vector< DriverException >`

[#_ConceptPtrFuture_AttributeType__TypeDBConceptManagerputAttributeType___const_stdstring__label__ValueType_valueType___const]
==== putAttributeType

[source,cpp]
----
ConceptPtrFuture<AttributeType> TypeDB::ConceptManager::putAttributeType(const std::string& label, ValueType valueType) const
----



Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| 
a| `valueType` a| The value type of the ``AttributeType`` to create a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_ConceptPtrFuture_EntityType__TypeDBConceptManagerputEntityType___const_stdstring__label___const]
==== putEntityType

[source,cpp]
----
ConceptPtrFuture<EntityType> TypeDB::ConceptManager::putEntityType(const std::string& label) const
----



Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[#_ConceptPtrFuture_RelationType__TypeDBConceptManagerputRelationType___const_stdstring__label___const]
==== putRelationType

[source,cpp]
----
ConceptPtrFuture<RelationType> TypeDB::ConceptManager::putRelationType(const std::string& label) const
----



Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

// end::methods[]

