[#_ConceptManager]
=== ConceptManager

*Package*: `TypeDB`



Provides access for all Concept API methods.

// tag::methods[]
[#_a64fd4c71c8e55acd5853ab2dedf9cb58]
==== getAttribute

[source,cpp]
----
ConceptPtrFuture<Attribute> TypeDB::ConceptManager::getAttribute(const std::string& iid) const
----



Retrieves an ``Attribute`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_af088972bf1d279dc138e9c502fd53473]
==== getAttributeType

[source,cpp]
----
ConceptPtrFuture<AttributeType> TypeDB::ConceptManager::getAttributeType(const std::string& label) const
----



Retrieves an ``AttributeType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_ad0397b83a1ef08d286b6bbda3dae9452]
==== getEntity

[source,cpp]
----
ConceptPtrFuture<Entity> TypeDB::ConceptManager::getEntity(const std::string& iid) const
----



Retrieves an ``Entity`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Entity >`

[#_a60214a504adf93147d4be1e46856f9ac]
==== getEntityType

[source,cpp]
----
ConceptPtrFuture<EntityType> TypeDB::ConceptManager::getEntityType(const std::string& label) const
----



Retrieves an ``EntityType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[#_a2d42df1c48cb8cef543057a906854025]
==== getRelation

[source,cpp]
----
ConceptPtrFuture<Relation> TypeDB::ConceptManager::getRelation(const std::string& iid) const
----



Retrieves a ``Relation`` by its iid.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Relation >`

[#_ad0c7c308f6275300bd039303be490199]
==== getRelationType

[source,cpp]
----
ConceptPtrFuture<RelationType> TypeDB::ConceptManager::getRelationType(const std::string& label) const
----



Retrieves a ``RelationType`` by its label.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[#_a7b17a2d8624d77cff53f84ccb6770759]
==== getRootAttributeType

[source,cpp]
----
std::unique_ptr<AttributeType> TypeDB::ConceptManager::getRootAttributeType() const
----



Retrieve the root ``AttributeType``, “attribute”.


[caption=""]
.Returns
`std::unique_ptr< AttributeType >`

[#_af3964441716c4949cb8b6788859a0da2]
==== getRootEntityType

[source,cpp]
----
std::unique_ptr<EntityType> TypeDB::ConceptManager::getRootEntityType() const
----



Retrieves the root ``EntityType``, “entity”.


[caption=""]
.Returns
`std::unique_ptr< EntityType >`

[#_af961615fff7e45da621ae5013acc427b]
==== getRootRelationType

[source,cpp]
----
std::unique_ptr<RelationType> TypeDB::ConceptManager::getRootRelationType() const
----



Retrieve the root ``RelationType``, “relation”.


[caption=""]
.Returns
`std::unique_ptr< RelationType >`

[#_a9cd296d8b6b113cfaa98179168b73b68]
==== getSchemaExceptions

[source,cpp]
----
std::vector<DriverException> TypeDB::ConceptManager::getSchemaExceptions()
----



Retrieves a list of all schema exceptions for the current transaction.


[caption=""]
.Returns
`std::vector< DriverException >`

[#_a84cda974980f70fe6b0a17d423f5ae32]
==== putAttributeType

[source,cpp]
----
ConceptPtrFuture<AttributeType> TypeDB::ConceptManager::putAttributeType(const std::string& label, ValueType valueType) const
----



Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| 
a| `valueType` a| The value type of the ``AttributeType`` to create a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_a467d5a84f49b1d4588e006a356d44d84]
==== putEntityType

[source,cpp]
----
ConceptPtrFuture<EntityType> TypeDB::ConceptManager::putEntityType(const std::string& label) const
----



Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< EntityType >`

[#_a6cf4963c28dc8e41e09003b96b993aa0]
==== putRelationType

[source,cpp]
----
ConceptPtrFuture<RelationType> TypeDB::ConceptManager::putRelationType(const std::string& label) const
----



Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

// end::methods[]

