[#_ConceptDocumentsQueryResponse]
=== ConceptDocumentsQueryResponse

`Class(name=ConceptDocumentsQueryResponse, anchor=ConceptDocumentsQueryResponse, enumConstants=[], description=[], examples=[], fields=[Variable(name=answers, anchor=null, defaultValue=null, description=null, type=Object), Variable(name=answerType, anchor=null, defaultValue=null, description=null, type="conceptDocuments"), Variable(name=comment, anchor=null, defaultValue=null, description=null, type=string), Variable(name=query, anchor=null, defaultValue=null, description=null, type=AnalyzedPipeline), Variable(name=queryType, anchor=null, defaultValue=null, description=null, type=QueryType)], methods=[], packagePath=null, superClasses=[], traitImplementors=[], mode=null).nameDescriptor(language)`

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `answerType` a| `"conceptDocuments"` a| 
a| `answers` a| `Object` a| 
a| `comment` a| `string` a| 
a| `query` a| `AnalyzedPipeline` a| 
a| `queryType` a| `QueryType` a| 
|===
// end::properties[]

