[#_ConceptManager]
=== ConceptManager

*Package*: `com.vaticle.typedb.driver.api.concept`

Provides access for all Concept API methods.

// tag::methods[]
[#_ConceptManager_getAttribute_java_lang_String]
==== getAttribute

[source,java]
----
@Nullable
@CheckReturnValue
Attribute getAttribute​(java.lang.String iid)
----

Retrieves an ``Attribute`` by its iid. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Attribute`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getAttribute(iid);
----

[#_ConceptManager_getAttributeType_java_lang_String]
==== getAttributeType

[source,java]
----
@Nullable
@CheckReturnValue
AttributeType getAttributeType​(java.lang.String label)
----

Retrieves an ``AttributeType`` by its label. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getAttributeType(label)
----

[#_ConceptManager_getEntity_java_lang_String]
==== getEntity

[source,java]
----
@Nullable
@CheckReturnValue
Entity getEntity​(java.lang.String iid)
----

Retrieves an ``Entity`` by its iid. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Entity`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getEntity(iid);
----

[#_ConceptManager_getEntityType_java_lang_String]
==== getEntityType

[source,java]
----
@Nullable
@CheckReturnValue
EntityType getEntityType​(java.lang.String label)
----

Retrieves an ``EntityType`` by its label. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getEntityType(label);
----

[#_ConceptManager_getRelation_java_lang_String]
==== getRelation

[source,java]
----
@Nullable
@CheckReturnValue
Relation getRelation​(java.lang.String iid)
----

Retrieves a ``Relation`` by its iid. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `iid` a| The iid of the ``Relation`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRelation(iid);
----

[#_ConceptManager_getRelationType_java_lang_String]
==== getRelationType

[source,java]
----
@Nullable
@CheckReturnValue
RelationType getRelationType​(java.lang.String label)
----

Retrieves a ``RelationType`` by its label. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRelationType(label);
----

[#_ConceptManager_getRootAttributeType_]
==== getRootAttributeType

[source,java]
----
@CheckReturnValue
AttributeType getRootAttributeType()
----

Retrieve the root ``AttributeType``, “attribute”. 


[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootAttributeType();
----

[#_ConceptManager_getRootEntityType_]
==== getRootEntityType

[source,java]
----
@CheckReturnValue
EntityType getRootEntityType()
----

Retrieves the root ``EntityType``, “entity”. 


[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootEntityType();
----

[#_ConceptManager_getRootRelationType_]
==== getRootRelationType

[source,java]
----
@CheckReturnValue
RelationType getRootRelationType()
----

Retrieve the root ``RelationType``, “relation”. 


[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getRootRelationType();
----

[#_ConceptManager_getSchemaExceptions_]
==== getSchemaExceptions

[source,java]
----
@CheckReturnValue
java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException> getSchemaExceptions()
----

Retrieves a list of all schema exceptions for the current transaction. 


[caption=""]
.Returns
`java.util.List<com.vaticle.typedb.driver.common.exception.TypeDBException>`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().getSchemaException();
----

[#_ConceptManager_putAttributeType_java_lang_String_com_vaticle_typedb_driver_api_concept_value_Value_Type]
==== putAttributeType

[source,java]
----
AttributeType putAttributeType​(java.lang.String label,
                               Value.Type valueType)
----

Creates a new ``AttributeType`` if none exists with the given label, or retrieves the existing one. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``AttributeType`` to create or retrieve a| `java.lang.String`
a| `valueType` a| The value type of the ``AttributeType`` to create a| `Value.Type`
|===

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,java]
----
await transaction.concepts().putAttributeType(label, valueType);
----

[#_ConceptManager_putEntityType_java_lang_String]
==== putEntityType

[source,java]
----
EntityType putEntityType​(java.lang.String label)
----

Creates a new ``EntityType`` if none exists with the given label, otherwise retrieves the existing one. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``EntityType`` to create or retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().putEntityType(label);
----

[#_ConceptManager_putRelationType_java_lang_String]
==== putRelationType

[source,java]
----
RelationType putRelationType​(java.lang.String label)
----

Creates a new ``RelationType`` if none exists with the given label, otherwise retrieves the existing one. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `label` a| The label of the ``RelationType`` to create or retrieve a| `java.lang.String`
|===

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,java]
----
transaction.concepts().putRelationType(label);
----

// end::methods[]

