[#_QueryManager]
=== QueryManager

Provides methods for executing TypeQL queries in the transaction.

// tag::methods[]
[#_QueryManager_define__query_string__options_TypeDBOptions]
==== define

[source,nodejs]
----
define(query, options?): Promise<void>
----

Performs a TypeQL Define query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Define query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.define(query, options)
----

[#_QueryManager_delete__query_string__options_TypeDBOptions]
==== delete

[source,nodejs]
----
delete(query, options?): Promise<void>
----

Performs a TypeQL Delete query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Delete query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.delete(query, options)
----

[#_QueryManager_explain__explainable_Explainable__options_TypeDBOptions]
==== explain

[source,nodejs]
----
explain(explainable, options?): Stream<Explanation>
----

Performs a TypeQL Explain query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `explainable` a| The Explainable to be explained a| `Explainable`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<Explanation>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.explain(explainable, options)
----

[#_QueryManager_fetch__query_string__options_TypeDBOptions]
==== fetch

[source,nodejs]
----
fetch(query, options?): Stream<JSONObject>
----

Performs a TypeQL Fetch query in the transaction.

Returns a stream of JSON Objects of strings to JSON. JSON can be: Arrays of JSON, Objects of strings to JSON, or primitives such as strings or numbers or booleans.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Fetch query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<JSONObject>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.fetch(query, options)
----

[#_QueryManager_get__query_string__options_TypeDBOptions]
==== get

[source,nodejs]
----
get(query, options?): Stream<ConceptMap>
----

Performs a TypeQL Get query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<ConceptMap>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.get(query, options)
----

[#_QueryManager_getAggregate__query_string__options_TypeDBOptions]
==== getAggregate

[source,nodejs]
----
getAggregate(query, options?): Promise<Value>
----

Performs a TypeQL Get Aggregate query in the transaction. Returns an empty promise if the aggregate was not well-defined (such as stddev of 0 elements).

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Aggregate query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<Value>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.getAggregate(query, options)
----

[#_QueryManager_getGroup__query_string__options_TypeDBOptions]
==== getGroup

[source,nodejs]
----
getGroup(query, options?): Stream<ConceptMapGroup>
----

Performs a TypeQL Get Group query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<ConceptMapGroup>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.getGroup(query, options)
----

[#_QueryManager_getGroupAggregate__query_string__options_TypeDBOptions]
==== getGroupAggregate

[source,nodejs]
----
getGroupAggregate(query, options?): Stream<ValueGroup>
----

Performs a TypeQL Get Group Aggregate query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Get Group Aggregate query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<ValueGroup>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.getGroupAggregate(query, options)
----

[#_QueryManager_insert__query_string__options_TypeDBOptions]
==== insert

[source,nodejs]
----
insert(query, options?): Stream<ConceptMap>
----

Performs a TypeQL Insert query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Insert query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<ConceptMap>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.insert(query, options)
----

[#_QueryManager_undefine__query_string__options_TypeDBOptions]
==== undefine

[source,nodejs]
----
undefine(query, options?): Promise<void>
----

Performs a TypeQL Undefine query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Undefine query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Promise<void>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.undefine(query, options)
----

[#_QueryManager_update__query_string__options_TypeDBOptions]
==== update

[source,nodejs]
----
update(query, options?): Stream<ConceptMap>
----

Performs a TypeQL Update query in the transaction.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `query` a| The TypeQL Update query to be executed a| `string`
a| `options` a| Specify query options a| `TypeDBOptions`
|===

[caption=""]
.Returns
`Stream<ConceptMap>`

[caption=""]
.Code examples
[source,nodejs]
----
transaction.query.update(query, options)
----

// end::methods[]

