[#_Concept]
=== Concept

// tag::methods[]
[#_Concept_as_attribute_]
==== as_attribute

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
concept.as_attribute()
----

[#_Concept_as_attribute_type_]
==== as_attribute_type

[source,python]
----
as_attribute_type() -> AttributeType
----

Casts the concept to ``AttributeType``.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
concept.as_attribute_type()
----

[#_Concept_as_entity_]
==== as_entity

[source,python]
----
as_entity() -> Entity
----

Casts the concept to ``Entity``.

[caption=""]
.Returns
`Entity`

[caption=""]
.Code examples
[source,python]
----
concept.as_entity()
----

[#_Concept_as_entity_type_]
==== as_entity_type

[source,python]
----
as_entity_type() -> EntityType
----

Casts the concept to ``EntityType``.

[caption=""]
.Returns
`EntityType`

[caption=""]
.Code examples
[source,python]
----
concept.as_entity_type()
----

[#_Concept_as_instance_]
==== as_instance

[source,python]
----
as_instance() -> Instance
----

Casts the concept to ``Instance``.

[caption=""]
.Returns
`Instance`

[caption=""]
.Code examples
[source,python]
----
concept.as_instance()
----

[#_Concept_as_relation_]
==== as_relation

[source,python]
----
as_relation() -> Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,python]
----
concept.as_relation()
----

[#_Concept_as_relation_type_]
==== as_relation_type

[source,python]
----
as_relation_type() -> RelationType
----

Casts the concept to ``RelationType``.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
concept.as_relation_type()
----

[#_Concept_as_role_type_]
==== as_role_type

[source,python]
----
as_role_type() -> RoleType
----

Casts the concept to ``RoleType``.

[caption=""]
.Returns
`RoleType`

[caption=""]
.Code examples
[source,python]
----
concept.as_role_type()
----

[#_Concept_as_type_]
==== as_type

[source,python]
----
as_type() -> Type
----

Casts the concept to ``Type``.

[caption=""]
.Returns
`Type`

[caption=""]
.Code examples
[source,python]
----
concept.as_type()
----

[#_Concept_as_value_]
==== as_value

[source,python]
----
as_value() -> Value
----

Casts the concept to ``Value``.

[caption=""]
.Returns
`Value`

[caption=""]
.Code examples
[source,python]
----
concept.as_value()
----

[#_Concept_get_label_]
==== get_label

[source,python]
----
get_label() -> str
----

Get the label of the concept. If this is an ``Instance``, return the label of the type of this instance. If this is a ``Value``, return the label of the value type of the value. If this is a ``Type``, return the label of the type.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
concept.get_label()
----

[#_Concept_is_attribute_]
==== is_attribute

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_attribute()
----

[#_Concept_is_attribute_type_]
==== is_attribute_type

[source,python]
----
is_attribute_type() -> bool
----

Checks if the concept is an ``AttributeType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_attribute_type()
----

[#_Concept_is_entity_]
==== is_entity

[source,python]
----
is_entity() -> bool
----

Checks if the concept is an ``Entity``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_entity()
----

[#_Concept_is_entity_type_]
==== is_entity_type

[source,python]
----
is_entity_type() -> bool
----

Checks if the concept is an ``EntityType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_entity_type()
----

[#_Concept_is_instance_]
==== is_instance

[source,python]
----
is_instance() -> bool
----

Checks if the concept is a ``Instance``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_instance()
----

[#_Concept_is_relation_]
==== is_relation

[source,python]
----
is_relation() -> bool
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_relation()
----

[#_Concept_is_relation_type_]
==== is_relation_type

[source,python]
----
is_relation_type() -> bool
----

Checks if the concept is a ``RelationType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_relation_type()
----

[#_Concept_is_role_type_]
==== is_role_type

[source,python]
----
is_role_type() -> bool
----

Checks if the concept is a ``RoleType``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_role_type()
----

[#_Concept_is_type_]
==== is_type

[source,python]
----
is_type() -> bool
----

Checks if the concept is a ``Type``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_type()
----

[#_Concept_is_value_]
==== is_value

[source,python]
----
is_value() -> bool
----

Checks if the concept is a ``Value``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
concept.is_value()
----

// end::methods[]

