[#_ConceptMap_Explainables]
=== ConceptMap.Explainables

*Package*: `com.vaticle.typedb.driver.api.answer`

Contains explainable objects.

// tag::methods[]
[#_ConceptMap_Explainables_attribute__java_lang_String]
==== attribute

[source,java]
----
ConceptMap.Explainable attribute​(java.lang.String variable)
----

Retrieves the explainable attribute with the given variable name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String`
|===

[caption=""]
.Returns
`ConceptMap.Explainable`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().attribute(variable);
----

[#_ConceptMap_Explainables_attributes__]
==== attributes

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>> attributes()
----

Retrieves all of this ``ConceptMap``’s explainable attributes. 


[caption=""]
.Returns
`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().attributes();
----

[#_ConceptMap_Explainables_ownership__java_lang_String__java_lang_String]
==== ownership

[source,java]
----
ConceptMap.Explainable ownership​(java.lang.String owner,
                                 java.lang.String attribute)
----

Retrieves the explainable attribute ownership with the pair of (owner, attribute) variable names. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `owner` a| The string representation of the owner variable a| `java.lang.String`
a| `attribute` a| The string representation of the attribute variable a| `java.lang.String`
|===

[caption=""]
.Returns
`ConceptMap.Explainable`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().ownership(owner, attribute);
----

[#_ConceptMap_Explainables_ownerships__]
==== ownerships

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<com.vaticle.typedb.common.collection.Pair<java.lang.String,​java.lang.String>,​ConceptMap.Explainable>> ownerships()
----

Retrieves all of this ``ConceptMap``’s explainable ownerships. 


[caption=""]
.Returns
`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<com.vaticle.typedb.common.collection.Pair<java.lang.String,​java.lang.String>,​ConceptMap.Explainable>>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().ownerships();
----

[#_ConceptMap_Explainables_relation__java_lang_String]
==== relation

[source,java]
----
ConceptMap.Explainable relation​(java.lang.String variable)
----

Retrieves the explainable relation with the given variable name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String`
|===

[caption=""]
.Returns
`ConceptMap.Explainable`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().relation(variable);
----

[#_ConceptMap_Explainables_relations__]
==== relations

[source,java]
----
java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>> relations()
----

Retrieves all of this ``ConceptMap``’s explainable relations. 


[caption=""]
.Returns
`java.util.stream.Stream<com.vaticle.typedb.common.collection.Pair<java.lang.String,​ConceptMap.Explainable>>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables().relations();
----

// end::methods[]

