[#_ConceptMap]
=== ConceptMap

*Package*: `com.vaticle.typedb.driver.api.answer`

Contains a mapping of variables to concepts.

// tag::methods[]
[#_ConceptMap_concepts__]
==== concepts

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<Concept> concepts()
----

Produces a stream over all concepts in this ``ConceptMap``. 


[caption=""]
.Returns
`java.util.stream.Stream<Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.concepts();
----

[#_ConceptMap_explainables__]
==== explainables

[source,java]
----
ConceptMap.Explainables explainables()
----

Gets the ``Explainables`` object for this ``ConceptMap``, exposing which of the concepts in this ``ConceptMap`` are explainable. 


[caption=""]
.Returns
`ConceptMap.Explainables`

[caption=""]
.Code examples
[source,java]
----
conceptMap.explainables();
----

[#_ConceptMap_get__java_lang_String]
==== get

[source,java]
----
@CheckReturnValue
Concept get​(java.lang.String variable)
----

Retrieves a concept for a given variable name. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `variable` a| The string representation of a variable a| `java.lang.String`
|===

[caption=""]
.Returns
`Concept`

[caption=""]
.Code examples
[source,java]
----
conceptMap.get(variable);
----

[#_ConceptMap_map__]
==== map

[source,java]
----
@CheckReturnValue
java.util.Map<java.lang.String,​Concept> map()
----

Returns the inner ``Map`` where keys are query variables, and values are concepts. 


[caption=""]
.Returns
`java.util.Map<java.lang.String,​Concept>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.map();
----

[#_ConceptMap_variables__]
==== variables

[source,java]
----
@CheckReturnValue
java.util.stream.Stream<java.lang.String> variables()
----

Produces a stream over all variables in this ``ConceptMap``. 


[caption=""]
.Returns
`java.util.stream.Stream<java.lang.String>`

[caption=""]
.Code examples
[source,java]
----
conceptMap.variables();
----

// end::methods[]

