[#_Numeric]
=== Numeric

*Package*: `com.vaticle.typedb.driver.api.answer`

Stores an aggregate query answer.

// tag::methods[]
[#_Numeric_asDouble_]
==== asDouble

[source,java]
----
@CheckReturnValue
double asDouble()
----

Retrieves numeric value of an aggregate answer as a ``double``. 


[caption=""]
.Returns
`double`

[caption=""]
.Code examples
[source,java]
----
numeric.asDouble();
----

[#_Numeric_asLong_]
==== asLong

[source,java]
----
@CheckReturnValue
long asLong()
----

Retrieves numeric value of an aggregate answer as a ``long``. 


[caption=""]
.Returns
`long`

[caption=""]
.Code examples
[source,java]
----
numeric.asLong();
----

[#_Numeric_asNumber_]
==== asNumber

[source,java]
----
@CheckReturnValue
java.lang.Number asNumber()
----

Retrieves numeric value of an aggregate answer. 


[caption=""]
.Returns
`java.lang.Number`

[caption=""]
.Code examples
[source,java]
----
numeric.asNumber();
----

[#_Numeric_isDouble_]
==== isDouble

[source,java]
----
@CheckReturnValue
boolean isDouble()
----

Checks if the type of an aggregate answer is a ``double``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
numeric.isDouble();
----

[#_Numeric_isLong_]
==== isLong

[source,java]
----
@CheckReturnValue
boolean isLong()
----

Checks if the type of an aggregate answer is a ``long``. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
numeric.isLong();
----

[#_Numeric_isNaN_]
==== isNaN

[source,java]
----
@CheckReturnValue
boolean isNaN()
----

Checks if the aggregate answer is not a number. 


[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
numeric.isNaN();
----

[#_Numeric_toString_]
==== toString

[source,java]
----
@CheckReturnValue
java.lang.String toString()
----

Retrieves a string representation of an aggregate answer. 


[caption=""]
.Returns
`java.lang.String`

[caption=""]
.Code examples
[source,java]
----
numeric.toString();
----

// end::methods[]

