[#_Rule]
=== Rule

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

[caption=""]
.Properties
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `label` a| `str` a| The unique label of the rule.
a| `then` a| `str` a| The single statement that constitutes the ‘then’ of the rule.
a| `when` a| `str` a| The statements that constitute the ‘when’ of the rule.
|===
// end::properties[]

// tag::methods[]
[#_Rule_delete__transaction_TypeDBTransaction]
==== delete

[source,python]
----
delete(transaction: TypeDBTransaction) -> Promise[None]
----

Deletes this rule.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
rule.delete(transaction).resolve()
----

[#_Rule_is_deleted__transaction_TypeDBTransaction]
==== is_deleted

[source,python]
----
is_deleted(transaction: TypeDBTransaction) -> Promise[bool]
----

Check if this rule has been deleted.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[bool]`

[caption=""]
.Code examples
[source,python]
----
rule.is_deleted(transaction).resolve()
----

[#_Rule_set_label__transaction_TypeDBTransaction__new_label_str]
==== set_label

[source,python]
----
set_label(transaction: TypeDBTransaction, new_label: str) -> Promise[None]
----

Renames the label of the rule. The new label must remain unique.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction` a| 
a| `new_label` a| The new label to be given to the rule a| `str` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
rule.set_label(transaction, new_label).resolve()
----

// end::methods[]

