[#_Attribute]
=== Attribute

*Supertypes:*

* `Thing`

Attribute is an instance of the attribute type and has a value. This value is fixed and unique for every given instance of the attribute type.

Attributes can be uniquely addressed by their type and value.

// tag::methods[]
[#_Attribute_as_attribute__]
==== as_attribute

[source,python]
----
as_attribute() -> Attribute
----

Casts the concept to ``Attribute``.

[caption=""]
.Returns
`Attribute`

[caption=""]
.Code examples
[source,python]
----
attribute.as_attribute()
----

[#_Attribute_as_boolean__]
==== as_boolean

[source,python]
----
as_boolean() -> bool
----

Returns a ``boolean`` value of the attribute. If the value has another type, raises an exception.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.as_boolean()
----

[#_Attribute_as_datetime__]
==== as_datetime

[source,python]
----
as_datetime() -> datetime
----

Returns a ``datetime`` value of the attribute. If the value has another type, raises an exception.

[caption=""]
.Returns
`datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.as_boolean()
----

[#_Attribute_as_double__]
==== as_double

[source,python]
----
as_double() -> float
----

Returns a ``double`` value of the attribute. If the value has another type, raises an exception.

[caption=""]
.Returns
`float`

[caption=""]
.Code examples
[source,python]
----
attribute.as_boolean()
----

[#_Attribute_as_long__]
==== as_long

[source,python]
----
as_long() -> int
----

Returns a ``long`` value of the attribute. If the value has another type, raises an exception.

[caption=""]
.Returns
`int`

[caption=""]
.Code examples
[source,python]
----
attribute.as_long()
----

[#_Attribute_as_string__]
==== as_string

[source,python]
----
as_string() -> str
----

Returns a ``string`` value of the attribute. If the value has another type, raises an exception.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
attribute.as_boolean()
----

[#_Attribute_get_owners__transaction_TypeDBTransaction__owner_type_ThingType__None]
==== get_owners

[source,python]
----
get_owners(transaction: TypeDBTransaction, owner_type: ThingType | None = None) -> Iterator[Thing]
----

Retrieves the instances that own this ``Attribute``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `owner_type` a| If specified, filter results for only owners of the given type a| `ThingType \| None` a| `None`
|===

[caption=""]
.Returns
`Iterator[Thing]`

[caption=""]
.Code examples
[source,python]
----
attribute.get_owners(transaction)
attribute.get_owners(transaction, owner_type)
----

[#_Attribute_get_type__]
==== get_type

[source,python]
----
get_type() -> AttributeType
----

Retrieves the type which this ``Attribute`` belongs to.

[caption=""]
.Returns
`AttributeType`

[caption=""]
.Code examples
[source,python]
----
attribute.get_type()
----

[#_Attribute_get_value__]
==== get_value

[source,python]
----
get_value() -> bool | int | float | str | datetime
----

Retrieves the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`bool | int | float | str | datetime`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value()
----

[#_Attribute_get_value_type__]
==== get_value_type

[source,python]
----
get_value_type() -> ValueType
----

Retrieves the type of the value which the ``Attribute`` instance holds.

[caption=""]
.Returns
`ValueType`

[caption=""]
.Code examples
[source,python]
----
attribute.get_value_type()
----

[#_Attribute_is_attribute__]
==== is_attribute

[source,python]
----
is_attribute() -> bool
----

Checks if the concept is an ``Attribute``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_attribute()
----

[#_Attribute_is_boolean__]
==== is_boolean

[source,python]
----
is_boolean() -> bool
----

Returns ``True`` if the attribute value is of type ``boolean``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_boolean()
----

[#_Attribute_is_datetime__]
==== is_datetime

[source,python]
----
is_datetime() -> bool
----

Returns ``True`` if the attribute value is of type ``datetime``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_datetime()
----

[#_Attribute_is_double__]
==== is_double

[source,python]
----
is_double() -> bool
----

Returns ``True`` if the attribute value is of type ``double``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_double()
----

[#_Attribute_is_long__]
==== is_long

[source,python]
----
is_long() -> bool
----

Returns ``True`` if the attribute value is of type ``long``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_long()
----

[#_Attribute_is_string__]
==== is_string

[source,python]
----
is_string() -> bool
----

Returns ``True`` if the attribute value is of type ``string``. Otherwise, returns ``False``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
attribute.is_string()
----

// end::methods[]

