[#_Relation]
=== Relation

*Supertypes:*

* `Thing`

Relation is an instance of a relation type and can be uniquely addressed by a combination of its type, owned attributes and role players.

// tag::methods[]
[#_Relation_add_player__transaction_TypeDBTransaction__role_type_RoleType__player_Thing]
==== add_player

[source,python]
----
add_player(transaction: TypeDBTransaction, role_type: RoleType, player: Thing) -> Promise[None]
----

Adds a new role player to play the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to be played by the ``player`` a| `RoleType` a| 
a| `player` a| The thing to play the role a| `Thing` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
relation.add_player(transaction, role_type, player).resolve()
----

[#_Relation_as_relation__]
==== as_relation

[source,python]
----
as_relation() -> Relation
----

Casts the concept to ``Relation``.

[caption=""]
.Returns
`Relation`

[caption=""]
.Code examples
[source,python]
----
relation.as_relation()
----

[#_Relation_get_players__transaction_TypeDBTransaction]
==== get_players

[source,python]
----
get_players(transaction: TypeDBTransaction) -> dict[RoleType, list[Thing]]
----

Retrieves a mapping of all instances involved in the ``Relation`` and the role each play.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`dict[RoleType, list[Thing]]`

[caption=""]
.Code examples
[source,python]
----
relation.get_players(transaction)
----

[#_Relation_get_players_by_role_type__transaction_TypeDBTransaction__role_types_RoleType]
==== get_players_by_role_type

[source,python]
----
get_players_by_role_type(transaction: TypeDBTransaction, *role_types: RoleType) -> Iterator[Thing]
----

Retrieves all role players of this ``Relation``, optionally filtered by given role types.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_types` a| 0 or more role types a| `RoleType` a| 
|===

[caption=""]
.Returns
`Iterator[Thing]`

[caption=""]
.Code examples
[source,python]
----
relation.get_players_by_role_type(transaction)
relation.get_players_by_role_type(transaction, role_type1, role_type2)
----

[#_Relation_get_relating__transaction_TypeDBTransaction]
==== get_relating

[source,python]
----
get_relating(transaction: TypeDBTransaction) -> Iterator[RoleType]
----

Retrieves all role types currently played in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
relation.get_relating(transaction)
----

[#_Relation_get_type__]
==== get_type

[source,python]
----
get_type() -> RelationType
----

Retrieves the type which this ``Relation`` belongs to.

[caption=""]
.Returns
`RelationType`

[caption=""]
.Code examples
[source,python]
----
relation.get_type()
----

[#_Relation_is_relation__]
==== is_relation

[source,python]
----
is_relation() -> bool
----

Checks if the concept is a ``Relation``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
relation.is_relation()
----

[#_Relation_remove_player__transaction_TypeDBTransaction__role_type_RoleType__player_Thing]
==== remove_player

[source,python]
----
remove_player(transaction: TypeDBTransaction, role_type: RoleType, player: Thing) -> Promise[None]
----

Removes the association of the given instance that plays the given role in this ``Relation``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_type` a| The role to no longer be played by the thing in this ``Relation`` a| `RoleType` a| 
a| `player` a| The instance to no longer play the role in this ``Relation`` a| `Thing` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
relation.remove_player(transaction, role_type, player).resolve()
----

// end::methods[]

