[#_Thing]
=== Thing

*Supertypes:*

* `Concept`

// tag::methods[]
[#_Thing_as_thing__]
==== as_thing

[source,python]
----
as_thing() -> Thing
----

Casts the concept to ``Thing``.

[caption=""]
.Returns
`Thing`

[caption=""]
.Code examples
[source,python]
----
thing.as_thing()
----

[#_Thing_delete__transaction_TypeDBTransaction]
==== delete

[source,python]
----
delete(transaction: TypeDBTransaction) -> Promise[None]
----

Deletes this ``Thing``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing.delete(transaction).resolve()
----

[#_Thing_get_has__transaction_TypeDBTransaction__attribute_type_AttributeType__attribute_types_list_AttributeType___annotations_set_Annotation_]
==== get_has

[source,python]
----
get_has(transaction: TypeDBTransaction, attribute_type: AttributeType = None, attribute_types: list[AttributeType] = None, annotations: set[Annotation] = frozenset({})) -> Iterator[Attribute]
----

Retrieves the ``Attribute``s that this ``Thing`` owns. Optionally, filtered by an ``AttributeType`` or a list of ``AttributeType``s. Optionally, filtered by ``Annotation``s.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute_type` a| The ``AttributeType`` to filter the attributes by a| `AttributeType` a| `None`
a| `attribute_types` a| The ``AttributeType``s to filter the attributes by a| `list[AttributeType]` a| `None`
a| `annotations` a| Only retrieve attributes with all given ``Annotation``s a| `set[Annotation]` a| `frozenset({})`
|===

[caption=""]
.Returns
`Iterator[Attribute]`

[caption=""]
.Code examples
[source,python]
----
thing.get_has(transaction)
thing.get_has(transaction, attribute_type=attribute_type,
              annotations=set(Annotation.key()))
----

[#_Thing_get_iid__]
==== get_iid

[source,python]
----
get_iid() -> str
----

Retrieves the unique id of the ``Thing``.

[caption=""]
.Returns
`str`

[caption=""]
.Code examples
[source,python]
----
thing.get_iid()
----

[#_Thing_get_playing__transaction_TypeDBTransaction]
==== get_playing

[source,python]
----
get_playing(transaction: TypeDBTransaction) -> Iterator[RoleType]
----

Retrieves the roles that this ``Thing`` is currently playing.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Iterator[RoleType]`

[caption=""]
.Code examples
[source,python]
----
thing.get_playing(transaction)
----

[#_Thing_get_relations__transaction_TypeDBTransaction__role_types_RoleType]
==== get_relations

[source,python]
----
get_relations(transaction: TypeDBTransaction, *role_types: RoleType) -> Iterator[Relation]
----

Retrieves all the ``Relation``s which this ``Thing`` plays a role in, optionally filtered by one or more given roles.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `role_types` a| 0 or more role types to filter the relations by. a| `RoleType` a| 
|===

[caption=""]
.Returns
`Iterator[Relation]`

[caption=""]
.Code examples
[source,python]
----
thing.get_relations(transaction, role_types)
----

[#_Thing_get_type__]
==== get_type

[source,python]
----
get_type() -> ThingType
----

Retrieves the type which this ``Thing`` belongs to.

[caption=""]
.Returns
`ThingType`

[caption=""]
.Code examples
[source,python]
----
thing.get_type()
----

[#_Thing_is_deleted__transaction_TypeDBTransaction]
==== is_deleted

[source,python]
----
is_deleted(transaction: TypeDBTransaction) -> Promise[bool]
----

Checks if this ``Thing`` is deleted.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
|===

[caption=""]
.Returns
`Promise[bool]`

[caption=""]
.Code examples
[source,python]
----
thing.is_deleted(transaction).resolve()
----

[#_Thing_is_inferred__]
==== is_inferred

[source,python]
----
is_inferred() -> bool
----

Checks if this ``Thing`` is inferred by a [Reasoning Rule].

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
thing.is_inferred()
----

[#_Thing_is_thing__]
==== is_thing

[source,python]
----
is_thing() -> bool
----

Checks if the concept is a ``Thing``.

[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,python]
----
thing.is_thing()
----

[#_Thing_set_has__transaction_TypeDBTransaction__attribute_Attribute]
==== set_has

[source,python]
----
set_has(transaction: TypeDBTransaction, attribute: Attribute) -> Promise[None]
----

Assigns an ``Attribute`` to be owned by this ``Thing``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute` a| The ``Attribute`` to be owned by this ``Thing``. a| `Attribute` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing.set_has(transaction, attribute).resolve()
----

[#_Thing_unset_has__transaction_TypeDBTransaction__attribute_Attribute]
==== unset_has

[source,python]
----
unset_has(transaction: TypeDBTransaction, attribute: Attribute) -> Promise[None]
----

Unassigns an ``Attribute`` from this ``Thing``.

[caption=""]
.Input parameters
[cols=",,,"]
[options="header"]
|===
|Name |Description |Type |Default Value
a| `transaction` a| The current transaction a| `TypeDBTransaction` a| 
a| `attribute` a| The ``Attribute`` to be disowned from this ``Thing``. a| `Attribute` a| 
|===

[caption=""]
.Returns
`Promise[None]`

[caption=""]
.Code examples
[source,python]
----
thing.unset_has(transaction, attribute).resolve()
----

// end::methods[]

