[#_◆_replica_info_drop_]
==== replica_info_drop

[source,cpp]
----
void replica_info_drop(struct ReplicaInfo* replica_info)
----



Frees the native rust ``ReplicaInfo`` object

[caption=""]
.Returns
`void`

[#_◆_replica_info_get_address_]
==== replica_info_get_address

[source,cpp]
----
char* replica_info_get_address(const struct ReplicaInfo* replica_info)
----



Retrieves the address of the server hosting this replica

[caption=""]
.Returns
`char*`

[#_◆_replica_info_get_term_]
==== replica_info_get_term

[source,cpp]
----
int64_t replica_info_get_term(const struct ReplicaInfo* replica_info)
----



The raft protocol ‘term’ of this replica.

[caption=""]
.Returns
`int64_t`

[#_◆_replica_info_is_preferred_]
==== replica_info_is_preferred

[source,cpp]
----
bool replica_info_is_preferred(const struct ReplicaInfo* replica_info)
----



Checks whether this is the preferred replica of the raft cluster. If true, Operations which can be run on any replica will prefer to use this replica.

[caption=""]
.Returns
`bool`

[#_◆_replica_info_is_primary_]
==== replica_info_is_primary

[source,cpp]
----
bool replica_info_is_primary(const struct ReplicaInfo* replica_info)
----



Checks whether this is the primary replica of the raft cluster.

[caption=""]
.Returns
`bool`

[#_◆_replica_info_iterator_drop_]
==== replica_info_iterator_drop

[source,cpp]
----
void replica_info_iterator_drop(struct ReplicaInfoIterator* it)
----



Frees the native rust ``ReplicaInfoIterator`` object

[caption=""]
.Returns
`void`

[#_◆_replica_info_iterator_next_]
==== replica_info_iterator_next

[source,cpp]
----
struct ReplicaInfo* replica_info_iterator_next(struct ReplicaInfoIterator* it)
----



Forwards the ``ReplicaInfoIterator`` and returns the next ``ReplicaInfo`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct ReplicaInfo*`

