[#_methods__connection__replica]
=== replica

[#_Struct_ReplicaInfo]
==== Struct ReplicaInfo



The metadata and state of an individual raft replica of a database.

[#_Struct_ReplicaInfoIterator]
==== Struct ReplicaInfoIterator



Iterator over the ``ReplicaInfo`` corresponding to each replica of a TypeDB cloud database.

[#_replica_info_drop]
==== replica_info_drop

[source,cpp]
----
void replica_info_drop(struct ReplicaInfo* replica_info)
----



Frees the native rust ``ReplicaInfo`` object

[caption=""]
.Returns
`void`

[#_replica_info_get_server]
==== replica_info_get_server

[source,cpp]
----
char* replica_info_get_server(const struct ReplicaInfo* replica_info)
----



The server hosting this replica

[caption=""]
.Returns
`char*`

[#_replica_info_get_term]
==== replica_info_get_term

[source,cpp]
----
int64_t replica_info_get_term(const struct ReplicaInfo* replica_info)
----



The raft protocol ‘term’ of this replica.

[caption=""]
.Returns
`int64_t`

[#_replica_info_is_preferred]
==== replica_info_is_preferred

[source,cpp]
----
bool replica_info_is_preferred(const struct ReplicaInfo* replica_info)
----



Checks whether this is the preferred replica of the raft cluster. If true, Operations which can be run on any replica will prefer to use this replica.

[caption=""]
.Returns
`bool`

[#_replica_info_is_primary]
==== replica_info_is_primary

[source,cpp]
----
bool replica_info_is_primary(const struct ReplicaInfo* replica_info)
----



Checks whether this is the primary replica of the raft cluster.

[caption=""]
.Returns
`bool`

[#_replica_info_iterator_drop]
==== replica_info_iterator_drop

[source,cpp]
----
void replica_info_iterator_drop(struct ReplicaInfoIterator* it)
----



Frees the native rust ``ReplicaInfoIterator`` object

[caption=""]
.Returns
`void`

[#_replica_info_iterator_next]
==== replica_info_iterator_next

[source,cpp]
----
struct ReplicaInfo* replica_info_iterator_next(struct ReplicaInfoIterator* it)
----



Forwards the ``ReplicaInfoIterator`` and returns the next ``ReplicaInfo`` if it exists, or null if there are no more elements.

[caption=""]
.Returns
`struct ReplicaInfo*`

