[#_TypeDBOptions]
=== TypeDBOptions

*Package*: `com.vaticle.typedb.driver.api`

TypeDB session and transaction options. ``TypeDBOptions`` object can be used to override the default server behaviour.

// tag::methods[]
[#_TypeDBOptions_TypeDBOptions__]
==== TypeDBOptions

[source,java]
----
public TypeDBOptions()
----

Produces a new ``TypeDBOptions`` object. 


[caption=""]
.Returns
`public`

[caption=""]
.Code examples
[source,java]
----
TypeDBOptions options = TypeDBOptions();
----

[#_TypeDBOptions_explain__]
==== explain

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> explain()
----

Returns the value set for the explanation in this ``TypeDBOptions`` object. If set to ``true``, explanations for queries are enabled. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.explain();
----

[#_TypeDBOptions_explain__boolean]
==== explain

[source,java]
----
public TypeDBOptions explain​(boolean explain)
----

Explicitly enables or disables explanations. If set to ``true``, enables explanations for queries. Only affects read transactions. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `explain` a| Explicitly enable or disable explanations a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.explain(explain);
----

[#_TypeDBOptions_infer__]
==== infer

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> infer()
----

Returns the value set for the inference in this ``TypeDBOptions`` object. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.infer();
----

[#_TypeDBOptions_infer__boolean]
==== infer

[source,java]
----
public TypeDBOptions infer​(boolean infer)
----

Explicitly enables or disables inference. Only settable at transaction level and above. Only affects read transactions. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `infer` a| Explicitly enable or disable inference a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.infer(infer);
----

[#_TypeDBOptions_parallel__]
==== parallel

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> parallel()
----

Returns the value set for the parallel execution in this ``TypeDBOptions`` object. If set to ``true``, the server uses parallel instead of single-threaded execution. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.parallel();
----

[#_TypeDBOptions_parallel__boolean]
==== parallel

[source,java]
----
public TypeDBOptions parallel​(boolean parallel)
----

Explicitly enables or disables parallel execution. If set to ``true``, the server uses parallel instead of single-threaded execution. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `parallel` a| Explicitly enable or disable parallel execution a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.parallel(parallel);
----

[#_TypeDBOptions_prefetch__]
==== prefetch

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> prefetch()
----

Returns the value set for the prefetching in this ``TypeDBOptions`` object. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.prefetch();
----

[#_TypeDBOptions_prefetch__boolean]
==== prefetch

[source,java]
----
public TypeDBOptions prefetch​(boolean prefetch)
----

Explicitly enables or disables prefetching. If set to ``true``, the first batch of answers is streamed to the driver even without an explicit request for it. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `prefetch` a| Explicitly enable or disable prefetching a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.prefetch(prefetch);
----

[#_TypeDBOptions_prefetchSize__]
==== prefetchSize

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> prefetchSize()
----

Returns the value set for the prefetch size in this ``TypeDBOptions`` object. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.prefetchSize();
----

[#_TypeDBOptions_prefetchSize__int]
==== prefetchSize

[source,java]
----
public TypeDBOptions prefetchSize​(int prefetchSize)
----

Explicitly sets a prefetch size. If set, specifies a guideline number of answers that the server should send before the driver issues a fresh request. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `prefetchSize` a| Number of answers that the server should send before the driver issues a fresh request a| `int`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.prefetchSize(prefetchSize);
----

[#_TypeDBOptions_readAnyReplica__]
==== readAnyReplica

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> readAnyReplica()
----

Returns the value set for reading data from any replica in this ``TypeDBOptions`` object. If set to ``True``, enables reading data from any replica, potentially boosting read throughput. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.readAnyReplica();
----

[#_TypeDBOptions_readAnyReplica__boolean]
==== readAnyReplica

[source,java]
----
public TypeDBOptions readAnyReplica​(boolean readAnyReplica)
----

Explicitly enables or disables reading data from any replica. If set to ``True``, enables reading data from any replica, potentially boosting read throughput. Only settable in TypeDB Cloud. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `readAnyReplica` a| Explicitly enable or disable reading data from any replica a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.readAnyReplica(readAnyReplica);
----

[#_TypeDBOptions_schemaLockAcquireTimeoutMillis__]
==== schemaLockAcquireTimeoutMillis

[source,java]
----
public java.util.Optional<java.lang.Integer> schemaLockAcquireTimeoutMillis()
----

Returns the value set for the schema lock acquire timeout in this ``TypeDBOptions`` object. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.schemaLockAcquireTimeoutMillis();
----

[#_TypeDBOptions_schemaLockAcquireTimeoutMillis__int]
==== schemaLockAcquireTimeoutMillis

[source,java]
----
public TypeDBOptions schemaLockAcquireTimeoutMillis​(int schemaLockAcquireTimeoutMillis)
----

Explicitly sets schema lock acquire timeout. If set, specifies how long the driver should wait if opening a session or transaction is blocked by a schema write lock. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `schemaLockAcquireTimeoutMillis` a| How long the driver should wait if opening a session or transaction is blocked by a schema write lock a| `int`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.schemaLockAcquireTimeoutMillis(schemaLockAcquireTimeoutMillis);
----

[#_TypeDBOptions_sessionIdleTimeoutMillis__]
==== sessionIdleTimeoutMillis

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> sessionIdleTimeoutMillis()
----

Returns the value set for the session idle timeout in this ``TypeDBOptions`` object. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.sessionIdleTimeoutMillis();
----

[#_TypeDBOptions_sessionIdleTimeoutMillis__int]
==== sessionIdleTimeoutMillis

[source,java]
----
public TypeDBOptions sessionIdleTimeoutMillis​(int sessionIdleTimeoutMillis)
----

Explicitly sets a session idle timeout. If set, specifies a timeout that allows the server to close sessions if the driver terminates or becomes unresponsive. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `sessionIdleTimeoutMillis` a| timeout that allows the server to close sessions if the driver terminates or becomes unresponsive a| `int`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.sessionIdleTimeoutMillis(sessionIdleTimeoutMillis);
----

[#_TypeDBOptions_traceInference__]
==== traceInference

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Boolean> traceInference()
----

Returns the value set for reasoning tracing in this ``TypeDBOptions`` object. If set to ``true``, reasoning tracing graphs are output in the logging directory. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
options.traceInference();
----

[#_TypeDBOptions_traceInference__boolean]
==== traceInference

[source,java]
----
public TypeDBOptions traceInference​(boolean traceInference)
----

Explicitly enables or disables reasoning tracing. If set to ``true``, reasoning tracing graphs are output in the logging directory. Should be used with ``parallel = False``. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `traceInference` a| Explicitly enable or disable reasoning tracing a| `boolean`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.traceInference(traceInference);
----

[#_TypeDBOptions_transactionTimeoutMillis__]
==== transactionTimeoutMillis

[source,java]
----
@CheckReturnValue
public java.util.Optional<java.lang.Integer> transactionTimeoutMillis()
----

Returns the value set for the transaction timeout in this ``TypeDBOptions`` object. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions. 


[caption=""]
.Returns
`public java.util.Optional<java.lang.Integer>`

[caption=""]
.Code examples
[source,java]
----
options.transactionTimeoutMillis();
----

[#_TypeDBOptions_transactionTimeoutMillis__int]
==== transactionTimeoutMillis

[source,java]
----
public TypeDBOptions transactionTimeoutMillis​(int transactionTimeoutMillis)
----

Explicitly set a transaction timeout. If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transactionTimeoutMillis` a| Timeout for killing transactions automatically a| `int`
|===

[caption=""]
.Returns
`public TypeDBOptions`

[caption=""]
.Code examples
[source,java]
----
options.transactionTimeoutMillis(transactionTimeoutMillis);
----

// end::methods[]

