[#_struct_Decimal]
=== Decimal

`Class(name=Decimal, anchor=struct_Decimal, enumConstants=[], description=[A fixed-point decimal number. Holds exactly 19 digits after the decimal point and a 64-bit value before the decimal point.], examples=[], fields=[], methods=[Method(name=integer_part, signature=pub fn integer_part(&self) -> i64, anchor=struct_Decimal_integer_part_, args=[], description=[Get the integer part of the decimal as normal signed 64 bit number], examples=[], mode=async, returnDescription=null, returnType=i64), Method(name=fractional_part, signature=pub fn fractional_part(&self) -> u64, anchor=struct_Decimal_fractional_part_, args=[], description=[Get the fractional part of the decimal, in multiples of 10^-19 (Decimal::FRACTIONAL_PART_DENOMINATOR) This means, the smallest decimal representable is 10^-19, and up to 19 decimal places are supported.], examples=[], mode=async, returnDescription=null, returnType=u64)], packagePath=null, superClasses=[Add, Clone, Copy, Debug, Default, Display, Eq, Hash, Neg, Ord, PartialEq, PartialOrd, StructuralPartialEq, Sub], traitImplementors=[], mode=async).nameDescriptor(language)`

*Implements traits:*

* `Add`
* `Clone`
* `Copy`
* `Debug`
* `Default`
* `Display`
* `Eq`
* `Hash`
* `Neg`
* `Ord`
* `PartialEq`
* `PartialOrd`
* `StructuralPartialEq`
* `Sub`

A fixed-point decimal number. Holds exactly 19 digits after the decimal point and a 64-bit value before the decimal point.

// tag::methods[]
[#_struct_Decimal_fractional_part_]
==== fractional_part

[source,rust]
----
pub fn fractional_part(&self) -> u64
----

Get the fractional part of the decimal, in multiples of 10^-19 (Decimal::FRACTIONAL_PART_DENOMINATOR) This means, the smallest decimal representable is 10^-19, and up to 19 decimal places are supported.

[caption=""]
.Returns
[source,rust]
----
u64
----

[#_struct_Decimal_integer_part_]
==== integer_part

[source,rust]
----
pub fn integer_part(&self) -> i64
----

Get the integer part of the decimal as normal signed 64 bit number

[caption=""]
.Returns
[source,rust]
----
i64
----

// end::methods[]

