[#_Rule]
=== Rule

*Package*: `com.vaticle.typedb.driver.api.logic`

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

// tag::methods[]
[#_Rule_delete_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== delete

[source,java]
----
void delete​(TypeDBTransaction transaction)
----

Deletes this rule. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
rule.delete(transaction)
----

[#_Rule_getLabel_]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the rule.

[caption=""]
.Returns
`java.lang.String`

[#_Rule_getThen_]
==== getThen

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getThen()
----

The single statement that constitutes the ‘then’ of the rule.

[caption=""]
.Returns
`com.vaticle.typeql.lang.pattern.Pattern`

[#_Rule_getWhen_]
==== getWhen

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getWhen()
----

The statements that constitute the ‘when’ of the rule.

[caption=""]
.Returns
`com.vaticle.typeql.lang.pattern.Pattern`

[#_Rule_isDeleted_com_vaticle_typedb_driver_api_TypeDBTransaction]
==== isDeleted

[source,java]
----
@CheckReturnValue
boolean isDeleted​(TypeDBTransaction transaction)
----

Check if this rule has been deleted. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`boolean`

[caption=""]
.Code examples
[source,java]
----
rule.isDeleted(transaction)
----

[#_Rule_setLabel_com_vaticle_typedb_driver_api_TypeDBTransaction_java_lang_String]
==== setLabel

[source,java]
----
void setLabel​(TypeDBTransaction transaction,
              java.lang.String label)
----

Renames the label of the rule. The new label must remain unique. 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
a| `label` a| The new label to be given to the rule a| `java.lang.String`
|===

[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,java]
----
rule.setLabel(transaction, newLabel)
----

// end::methods[]

