[#_Rule]
=== Rule

*Package*: `com.vaticle.typedb.driver.api.logic`

Rules are a part of schema and define embedded logic. The reasoning engine uses rules as a set of logic to infer new data. A rule consists of a condition and a conclusion, and is uniquely identified by a label.

// tag::methods[]
[#_Rule_delete__TypeDBTransaction]
==== delete

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> delete​(TypeDBTransaction transaction)
----

Deletes this rule. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
rule.delete(transaction).resolve();
----

[#_Rule_getLabel__]
==== getLabel

[source,java]
----
@CheckReturnValue
java.lang.String getLabel()
----

Retrieves the unique label of the rule.

[caption=""]
.Returns
`java.lang.String`

[#_Rule_getThen__]
==== getThen

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getThen()
----

The single statement that constitutes the ‘then’ of the rule.

[caption=""]
.Returns
`com.vaticle.typeql.lang.pattern.Pattern`

[#_Rule_getWhen__]
==== getWhen

[source,java]
----
@CheckReturnValue
com.vaticle.typeql.lang.pattern.Pattern getWhen()
----

The statements that constitute the ‘when’ of the rule.

[caption=""]
.Returns
`com.vaticle.typeql.lang.pattern.Pattern`

[#_Rule_isDeleted__TypeDBTransaction]
==== isDeleted

[source,java]
----
@CheckReturnValue
Promise<java.lang.Boolean> isDeleted​(TypeDBTransaction transaction)
----

Check if this rule has been deleted. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
|===

[caption=""]
.Returns
`Promise<java.lang.Boolean>`

[caption=""]
.Code examples
[source,java]
----
rule.isDeleted(transaction).resolve();
----

[#_Rule_setLabel__TypeDBTransaction__java_lang_String]
==== setLabel

[source,java]
----
@CheckReturnValue
Promise<java.lang.Void> setLabel​(TypeDBTransaction transaction,
                                 java.lang.String label)
----

Renames the label of the rule. The new label must remain unique. 


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current ``Transaction`` a| `TypeDBTransaction`
a| `label` a| The new label to be given to the rule a| `java.lang.String`
|===

[caption=""]
.Returns
`Promise<java.lang.Void>`

[caption=""]
.Code examples
[source,java]
----
rule.setLabel(transaction, newLabel).resolve();
----

// end::methods[]

