[#_Credential]
=== Credential

*Package*: `TypeDB`



User credentials and TLS encryption settings for connecting to TypeDB Cloud.


[caption=""]
.Examples
[source,cpp]
----
// Creates a credential as above, but the connection will be made over TLS.
Credential credential(username, password, true);

// Creates a credential as above, but TLS will use the specified CA to authenticate server certificates.
Credential credential(username, password, "path/to/ca-certificate.pem");
----

// tag::methods[]
[#_TypeDBCredentialCredential___const_stdstring__username__const_stdstring__password__bool_withTLS__const_stdstring__customRootCAPath__""_]
==== Credential

[source,cpp]
----
TypeDB::Credential::Credential(const std::string& username, const std::string& password, bool withTLS, const std::string& customRootCAPath = "")
----


 
  Parameters
 
 
  
   
    
     username
     The name of the user to connect as
    
    
     password
     The password for the user
    
    
     withTLS
     Specify whether the connection to TypeDB Cloud must be done over TLS
    
    
     customRootCAPath
     Optional, Path to a custom CA certificate to use for authenticating server certificates.
    
   
  
 


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to connect as a| 
a| `password` a| The password for the user a| 
a| `withTLS` a| Specify whether the connection to TypeDB Cloud must be done over TLS a| 
a| `customRootCAPath` a| Optional, Path to a custom CA certificate to use for authenticating server certificates. a| 
|===

[caption=""]
.Returns
`TypeDB::Credential::Credential`

// end::methods[]

