[#_Database]
=== Database

*Package*: `TypeDB`



A TypeDB database.

// tag::methods[]
[#_aaab52fc7442027a9c3812ea7fee37b24]
==== deleteDatabase

[source,cpp]
----
void TypeDB::Database::deleteDatabase()
----



Deletes this database.


[caption=""]
.Returns
`void`

[#_ac523de36171069dbf688ba6108c495d9]
==== name

[source,cpp]
----
std::string TypeDB::Database::name() const
----



The database name as a string.

[caption=""]
.Returns
`std::string`

[#_af709878d1dc613da4245778ce27073bd]
==== preferredReplica

[source,cpp]
----
std::optional< ReplicaInfo > TypeDB::Database::preferredReplica()
----



Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`std::optional< ReplicaInfo >`

[#_aa0bf5a33a2e6c93b2439bd2e4cdd5380]
==== primaryReplica

[source,cpp]
----
std::optional< ReplicaInfo > TypeDB::Database::primaryReplica()
----



Returns the primary replica for this database. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`std::optional< ReplicaInfo >`

[#_a3faf7d65aadf608416cb5cbbb0693d00]
==== replicas

[source,cpp]
----
ReplicaInfoIterable TypeDB::Database::replicas()
----



Set of ``Replica`` instances for this database. Only works in TypeDB Cloud


[caption=""]
.Returns
`ReplicaInfoIterable`

[#_ab49350e1691b89d2abbec44f5157721c]
==== ruleSchema

[source,cpp]
----
std::string TypeDB::Database::ruleSchema()
----



The rules in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

[#_a450cca51ecb54c5a5856e4e0e48fccbd]
==== schema

[source,cpp]
----
std::string TypeDB::Database::schema()
----



A full schema text as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

[#_abe1a292d6829727bf6330698b49a47dd]
==== typeSchema

[source,cpp]
----
std::string TypeDB::Database::typeSchema()
----



The types in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

// end::methods[]

