[#_Database]
=== Database

*Package*: `TypeDB`



A TypeDB database.

// tag::methods[]
[#_void_TypeDBDatabasedeleteDatabase___]
==== deleteDatabase

[source,cpp]
----
void TypeDB::Database::deleteDatabase()
----



Deletes this database.


[caption=""]
.Returns
`void`

[#_stdstring_TypeDBDatabasename_____const]
==== name

[source,cpp]
----
std::string TypeDB::Database::name() const
----



The database name as a string.

[caption=""]
.Returns
`std::string`

[#_stdoptional__ReplicaInfo___TypeDBDatabasepreferredReplica___]
==== preferredReplica

[source,cpp]
----
std::optional< ReplicaInfo > TypeDB::Database::preferredReplica()
----



Returns the preferred replica for this database. Operations which can be run on any replica will prefer to use this replica. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`std::optional< ReplicaInfo >`

[#_stdoptional__ReplicaInfo___TypeDBDatabaseprimaryReplica___]
==== primaryReplica

[source,cpp]
----
std::optional< ReplicaInfo > TypeDB::Database::primaryReplica()
----



Returns the primary replica for this database. _Only works in TypeDB Cloud_


[caption=""]
.Returns
`std::optional< ReplicaInfo >`

[#_ReplicaInfoIterable_TypeDBDatabasereplicas___]
==== replicas

[source,cpp]
----
ReplicaInfoIterable TypeDB::Database::replicas()
----



Set of ``Replica`` instances for this database. Only works in TypeDB Cloud


[caption=""]
.Returns
`ReplicaInfoIterable`

[#_stdstring_TypeDBDatabaseruleSchema___]
==== ruleSchema

[source,cpp]
----
std::string TypeDB::Database::ruleSchema()
----



The rules in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

[#_stdstring_TypeDBDatabaseschema___]
==== schema

[source,cpp]
----
std::string TypeDB::Database::schema()
----



A full schema text as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

[#_stdstring_TypeDBDatabasetypeSchema___]
==== typeSchema

[source,cpp]
----
std::string TypeDB::Database::typeSchema()
----



The types in the schema as a valid TypeQL define query string.


[caption=""]
.Returns
`std::string`

// end::methods[]

