[#_Driver]
=== Driver

*Package*: `TypeDB`



A connection to a TypeDB server which serves as the starting point for all interaction.

[caption=""]
.Fields
// tag::properties[]
[cols="~,~,~"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager TypeDB::Driver` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager TypeDB::Driver` a| Returns the logged-in user for the connection. Only for TypeDB Cloud.
Examples
[source,java]
----
driver.user();

----

|===
// end::properties[]

// tag::methods[]
[#_a44604ccc44f573109edfff21e4916bf5]
==== close

[source,cpp]
----
void TypeDB::Driver::close()
----



Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.


[caption=""]
.Returns
`void`

[#_a8849a1fa0a91a320f5fa94695673ac60]
==== cloudDriver

[source,cpp]
----
static Driver TypeDB::Driver::cloudDriver(const std::vector< std::string >& cloudAddresses, const Credential& credential) static
----



Open a TypeDB Driver to TypeDB Cloud server(s) available at the provided addresses, using the provided credential.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a| The address(es) of the TypeDB server(s) a| 
a| `credential` a| The Credential to connect with a| 
|===

[caption=""]
.Returns
`static Driver`

[#_ab959129d72b038c9b13745b9235d083c]
==== coreDriver

[source,cpp]
----
static Driver TypeDB::Driver::coreDriver(const std::string& coreAddress) static
----



Open a TypeDB Driver to a TypeDB Core server available at the provided address.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| 
|===

[caption=""]
.Returns
`static Driver`

[#_abcdaad79abd69e5207dafee2189d8731]
==== initLogging

[source,cpp]
----
static void TypeDB::Driver::initLogging() static
----



Enables logging in the TypeDB driver.


[caption=""]
.Returns
`static void`

[#_ad780cecfa9442a1cb143f8004c830730]
==== isOpen

[source,cpp]
----
bool TypeDB::Driver::isOpen()
----



Checks whether this connection is presently open.


[caption=""]
.Returns
`bool`

[#_a5eedf328093e30a275a04b19d7cc608f]
==== session

[source,cpp]
----
Session TypeDB::Driver::session(const std::string& database, SessionType sessionType, const Options& options)
----



Opens a communication tunnel (session) to the given database on the running TypeDB server. For more information on the methods, available with sessions, see the ``TypeDBSession`` section.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the session connects a| 
a| `type` a| The type of session to be created (DATA or SCHEMA) a| 
a| `options` a| ``TypeDBOptions`` for the session a| 
|===

[caption=""]
.Returns
`Session`

[#_af4aad2e510a66bd91f4aad85def84b27]
==== user

[source,cpp]
----
User TypeDB::Driver::user()
----



The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud.

[caption=""]
.Returns
`User`

// end::methods[]

