[#_Driver]
=== Driver

*Package*: `TypeDB`



A connection to a TypeDB server which serves as the starting point for all interaction.

[caption=""]
.Fields
// tag::properties[]
[cols=",,"]
[options="header"]
|===
|Name |Type |Description
a| `databases` a| `DatabaseManager TypeDB::Driver` a| The ``DatabaseManager`` for this connection, providing access to database management methods.
a| `users` a| `UserManager TypeDB::Driver` a| The ``UserManager`` instance for this connection, providing access to user management methods. Only for TypeDB Cloud.
|===
// end::properties[]

// tag::methods[]
[#_void_TypeDBDriverclose___]
==== close

[source,cpp]
----
void TypeDB::Driver::close()
----



Closes the driver. Before instantiating a new driver, the driver that’s currently open should first be closed.


[caption=""]
.Returns
`void`

[caption=""]
.Code examples
[source,cpp]
----
driver.close()
----

[#_static_Driver_TypeDBDrivercloudDriver___const_stdvector__stdstring____addresses__const_Credential__credential_]
==== cloudDriver

[source,cpp]
----
static Driver TypeDB::Driver::cloudDriver(const std::vector< std::string >& addresses, const Credential& credential)
----



Open a TypeDB Driver to TypeDB Cloud server(s) available at the provided addresses, using the provided credential.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `addresses` a| The address(es) of the TypeDB server(s) or translation map from addresses received from the TypeDB server(s) to addresses to be used by the driver for connection a| `const std::vector< std::string >&`
a| `credential` a| The Credential to connect with a| `const Credential&`
|===

[caption=""]
.Returns
`static Driver`

[caption=""]
.Code examples
[source,cpp]
----
Driver::cloudDriver(addresses, credential);
----

[#_static_Driver_TypeDBDrivercoreDriver___const_stdstring__address_]
==== coreDriver

[source,cpp]
----
static Driver TypeDB::Driver::coreDriver(const std::string& address)
----



Open a TypeDB Driver to a TypeDB Core server available at the provided address.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `address` a| The address of the TypeDB server a| `const std::string&`
|===

[caption=""]
.Returns
`static Driver`

[caption=""]
.Code examples
[source,cpp]
----
Driver::coreDriver(address);
----

[#_static_void_TypeDBDriverinitLogging___]
==== initLogging

[source,cpp]
----
static void TypeDB::Driver::initLogging()
----



Enables logging in the TypeDB driver.


[caption=""]
.Returns
`static void`

[caption=""]
.Code examples
[source,cpp]
----
Driver::initLogging();
----

[#_bool_TypeDBDriverisOpen___]
==== isOpen

[source,cpp]
----
bool TypeDB::Driver::isOpen()
----



Checks whether this connection is presently open.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
driver.isOpen();
----

[#_Session_TypeDBDriversession___const_stdstring__database__SessionType_sessionType__const_Options__options__Options___]
==== session

[source,cpp]
----
Session TypeDB::Driver::session(const std::string& database, SessionType sessionType, const Options& options = Options())
----



Opens a communication tunnel (session) to the given database on the running TypeDB server. For more information on the methods, available with sessions, see the ``TypeDBSession`` section.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `database` a| The name of the database with which the session connects a| `const std::string&`
a| `type` a| The type of session to be created (DATA or SCHEMA) a| 
a| `options` a| ``TypeDBOptions`` for the session a| 
|===

[caption=""]
.Returns
`Session`

[caption=""]
.Code examples
[source,cpp]
----
driver.session(database, sessionType, options);
----

[#_User_TypeDBDriveruser___]
==== user

[source,cpp]
----
User TypeDB::Driver::user()
----



Returns the logged-in user for the connection. Only for TypeDB Cloud.


[caption=""]
.Returns
`User`

[caption=""]
.Code examples
[source,cpp]
----
driver.user();
----

// end::methods[]

