[#_UserManager]
=== UserManager

*Package*: `TypeDB`



Provides access to all user management methods.

// tag::methods[]
[#_UserIterable_TypeDBUserManagerall_____const]
==== all

[source,cpp]
----
UserIterable TypeDB::UserManager::all() const
----



Retrieves all users which exist on the TypeDB server.


[caption=""]
.Returns
`UserIterable`

[#_bool_TypeDBUserManagercontains___const_stdstring__username___const]
==== contains

[source,cpp]
----
bool TypeDB::UserManager::contains(const std::string& username) const
----



Checks if a user with the given name exists.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The user name to be checked a| 
|===

[caption=""]
.Returns
`bool`

[#_void_TypeDBUserManagercreate___const_stdstring__username__const_stdstring__password___const]
==== create

[source,cpp]
----
void TypeDB::UserManager::create(const std::string& username, const std::string& password) const
----



Creates a user with the given name &amp; password.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be created a| 
a| `password` a| The password of the user to be created a| 
|===

[caption=""]
.Returns
`void`

[#_void_TypeDBUserManagerdeleteUser___const_stdstring__username___const]
==== deleteUser

[source,cpp]
----
void TypeDB::UserManager::deleteUser(const std::string& username) const
----



Deletes a user with the given name.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to be deleted a| 
|===

[caption=""]
.Returns
`void`

[#_stdunique_ptr__User___TypeDBUserManagerget___const_stdstring__username___const]
==== get

[source,cpp]
----
std::unique_ptr< User > TypeDB::UserManager::get(const std::string& username) const
----



Retrieves a user with the given name.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to retrieve a| 
|===

[caption=""]
.Returns
`std::unique_ptr< User >`

[#_void_TypeDBUserManagerpasswordSet___const_stdstring__username__const_stdstring__password___const]
==== passwordSet

[source,cpp]
----
void TypeDB::UserManager::passwordSet(const std::string& username, const std::string& password) const
----



Sets a new password for a user. This operation can only be performed by administrators.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `username` a| The name of the user to set the password of a| 
a| `password` a| The new password a| 
|===

[caption=""]
.Returns
`void`

// end::methods[]

