[#_AttributeType]
=== AttributeType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::ThingType`
* `TypeDB::Type`
* `TypeDB::Concept`



Attribute types represent properties that other types can own.

Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

// tag::methods[]
[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_Value_ptr_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, Value* value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `Value*`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_const_stdstring_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, const std::string& value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_int64_t_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, int64_t value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `int64_t`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_double_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, double value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `double`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_bool_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, bool value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `bool`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeget_Transaction_transaction_DateTime_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, DateTime value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| ``Attribute``’s value a| `DateTime`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.get(transaction, value).get();
----

[#_ConceptIterable_Attribute_TypeDBAttributeTypegetInstances_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getInstances

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::AttributeType::getInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect ``Attributes`` that are instances of this ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getInstances(transaction);
attributeType.getInstances(transaction, transitivity);
 Parameters 
  
    transitivity Transitivity::TRANSITIVE for direct and indirect subtypes, Transitivity::EXPLICIT for direct subtypes only 
    transaction The current transaction
----

[#_ConceptIterable_ThingType_TypeDBAttributeTypegetOwners_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getOwners

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::AttributeType::getOwners(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieve all ``Things`` that own an attribute of this ``AttributeType`` directly or through inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getOwners(transaction);
----

[#_ConceptIterable_ThingType_TypeDBAttributeTypegetOwners_Transaction_transaction_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getOwners

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::AttributeType::getOwners(Transaction& transaction, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable_ThingType_TypeDBAttributeTypegetOwners_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_,getOwners>>(Transaction& transaction, const std::vector<Annotation>& annotations, Transitivity transitivity = Transitivity::TRANSITIVE) for convenience


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``AttributeType`` with all given ``Annotation``s a| `const std::vector< Annotation >&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getOwners(transaction, {Annotation::key()}, transitivity);
 */
ConceptIterable<ThingType> getOwners(Transaction& transaction, const std::initializer_list<Annotation>& annotations, Transitivity transitivity = Transitivity::TRANSITIVE);

/**
   Retrieve all Things that own an attribute of this AttributeType,
   filtered by Annotations, directly or through inheritance.

   Examples
----

[source,cpp]
----
attributeType.getOwners(transaction, annotations);
----

[source,cpp]
----
Parameters 
  
    transaction The current transaction 
    annotations Only retrieve ThingTypes that have an attribute of this AttributeType with all given Annotations 
    transitivity Transitivity::TRANSITIVE for direct and indirect subtypes, Transitivity::EXPLICIT for direct subtypes only
----

[#_OptionalStringFuture_TypeDBAttributeTypegetRegex_Transaction_transaction_]
==== getRegex

[source,cpp]
----
OptionalStringFuture TypeDB::AttributeType::getRegex(Transaction& transaction)
----



Retrieves the regular expression that is defined for this ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`OptionalStringFuture`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getRegex(transaction).get();
----

[#_ConceptIterable_AttributeType_TypeDBAttributeTypegetSubtypes_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::AttributeType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect subtypes of this ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getSubtypes(transaction);
attributeType.getSubtypes(transaction, transitivity);
----

[#_ConceptIterable_AttributeType_TypeDBAttributeTypegetSubtypes_Transaction_transaction_ValueType_valueType_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::AttributeType::getSubtypes(Transaction& transaction, ValueType valueType, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType`` with given ``Value.Type``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `valueType` a| ``Value.Type`` for retrieving subtypes a| `ValueType`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getSubtypes(transaction, valueType, transitivity);
----

[#_ValueType_TypeDBAttributeTypegetValueType_]
==== getValueType

[source,cpp]
----
ValueType TypeDB::AttributeType::getValueType()
----



Retrieves the ``Value.Type`` of this ``AttributeType``.


[caption=""]
.Returns
`ValueType`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.getValueType();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_Value_ptr_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, Value* value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `Value*`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_const_stdstring_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, const std::string& value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``String`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_int64_t_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, int64_t value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``long`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `int64_t`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_double_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, double value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``double`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `double`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_bool_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, bool value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``bool`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `bool`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_ConceptPtrFuture_Attribute_TypeDBAttributeTypeput_Transaction_transaction_DateTime_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, DateTime value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``DateTime`` value.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `value` a| New ``Attribute``’s value a| `DateTime`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.put(transaction, value).get();
----

[#_VoidFuture_TypeDBAttributeTypesetRegex_Transaction_transaction_const_stdstring_regex_]
==== setRegex

[source,cpp]
----
VoidFuture TypeDB::AttributeType::setRegex(Transaction& transaction, const std::string& regex)
----



Sets a regular expression as a constraint for this ``AttributeType``. ``Values`` of all ``Attribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``AttributeType``s with a ``string`` value type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `regex` a| Regular expression a| `const std::string&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.setRegex(transaction, regex).get();
----

[#_VoidFuture_TypeDBAttributeTypesetSupertype_Transaction_transaction_AttributeType_ptr_attributeType_]
==== setSupertype

[source,cpp]
----
VoidFuture TypeDB::AttributeType::setSupertype(Transaction& transaction, AttributeType* attributeType)
----



Sets the supplied ``AttributeType`` as the supertype of the current ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attributeType` a| The ``AttributeType`` to set as the supertype of this ``AttributeType`` a| `AttributeType*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.setSupertype(transaction, superType).get();
----

[#_VoidFuture_TypeDBAttributeTypeunsetRegex_Transaction_transaction_]
==== unsetRegex

[source,cpp]
----
VoidFuture TypeDB::AttributeType::unsetRegex(Transaction& transaction)
----



Removes the regular expression that is defined for this ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
attributeType.unsetRegex(transaction).get();
----

// end::methods[]

