[#_AttributeType]
=== AttributeType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::ThingType`
* `TypeDB::Type`
* `TypeDB::Concept`



Attribute types represent properties that other types can own.

Attribute types have a value type. This value type is fixed and unique for every given instance of the attribute type.

Other types can own an attribute type. That means that instances of these other types can own an instance of this attribute type. This usually means that an object in our domain has a property with the matching value.

Multiple types can own the same attribute type, and different instances of the same type or different types can share ownership of the same attribute instance.

// tag::methods[]
[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__Value__ptr__value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, Value* value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__const_stdstring__value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, const std::string& value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__int64_t_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, int64_t value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__double_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, double value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__bool_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, bool value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeget___Transaction__transaction__DateTime_value_]
==== get

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::get(Transaction& transaction, DateTime value)
----



Retrieves an ``Attribute`` of this ``AttributeType`` with the given value if such ``Attribute`` exists. Otherwise, returns ``nullptr``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptIterable__Attribute___TypeDBAttributeTypegetInstances___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getInstances

[source,cpp]
----
ConceptIterable< Attribute > TypeDB::AttributeType::getInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect ``Attributes`` that are instances of this ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< Attribute >`

[#_ConceptIterable__ThingType___TypeDBAttributeTypegetOwners___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwners

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::AttributeType::getOwners(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieve all ``Things`` that own an attribute of this ``AttributeType`` directly or through inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_ConceptIterable__ThingType___TypeDBAttributeTypegetOwners___Transaction__transaction__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwners

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::AttributeType::getOwners(Transaction& transaction, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable__ThingType___TypeDBAttributeTypegetOwners___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwners>>(Transaction&amp; transaction, const std::vector&lt;Annotation&gt;&amp; annotations, Transitivity transitivity = Transitivity::TRANSITIVE) for convenience


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `annotations` a| Only retrieve ``ThingTypes`` that have an attribute of this ``AttributeType`` with all given ``Annotation``s a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_OptionalStringFuture_TypeDBAttributeTypegetRegex___Transaction__transaction_]
==== getRegex

[source,cpp]
----
OptionalStringFuture TypeDB::AttributeType::getRegex(Transaction& transaction)
----



Retrieves the regular expression that is defined for this ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`OptionalStringFuture`

[#_ConceptIterable__AttributeType___TypeDBAttributeTypegetSubtypes___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::AttributeType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect subtypes of this ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBAttributeTypegetSubtypes___Transaction__transaction__ValueType_valueType__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::AttributeType::getSubtypes(Transaction& transaction, ValueType valueType, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of this ``AttributeType`` with given ``Value.Type``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| ``Value.Type`` for retrieving subtypes a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ValueType_TypeDBAttributeTypegetValueType___]
==== getValueType

[source,cpp]
----
ValueType TypeDB::AttributeType::getValueType()
----



Retrieves the ``Value.Type`` of this ``AttributeType``.


[caption=""]
.Returns
`ValueType`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__Value__ptr__value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, Value* value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__const_stdstring__value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, const std::string& value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``String`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__int64_t_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, int64_t value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``long`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__double_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, double value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``double`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__bool_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, bool value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``bool`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_ConceptPtrFuture__Attribute___TypeDBAttributeTypeput___Transaction__transaction__DateTime_value_]
==== put

[source,cpp]
----
ConceptPtrFuture< Attribute > TypeDB::AttributeType::put(Transaction& transaction, DateTime value)
----



Adds and returns an ``Attribute`` of this ``AttributeType`` with the given ``DateTime`` value.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `value` a| New ``Attribute``’s value a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Attribute >`

[#_VoidFuture_TypeDBAttributeTypesetRegex___Transaction__transaction__const_stdstring__regex_]
==== setRegex

[source,cpp]
----
VoidFuture TypeDB::AttributeType::setRegex(Transaction& transaction, const std::string& regex)
----



Sets a regular expression as a constraint for this ``AttributeType``. ``Values`` of all ``Attribute``s of this type (inserted earlier or later) should match this regex.

Can only be applied for ``AttributeType``s with a ``string`` value type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `regex` a| Regular expression a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBAttributeTypesetSupertype___Transaction__transaction__AttributeType__ptr__attributeType_]
==== setSupertype

[source,cpp]
----
VoidFuture TypeDB::AttributeType::setSupertype(Transaction& transaction, AttributeType* attributeType)
----



Sets the supplied ``AttributeType`` as the supertype of the current ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` to set as the supertype of this ``AttributeType`` a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBAttributeTypeunsetRegex___Transaction__transaction_]
==== unsetRegex

[source,cpp]
----
VoidFuture TypeDB::AttributeType::unsetRegex(Transaction& transaction)
----



Removes the regular expression that is defined for this ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

// end::methods[]

