[#_EntityType]
=== EntityType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::ThingType`
* `TypeDB::Type`
* `TypeDB::Concept`



Entity types represent the classification of independent objects in the data model of the business domain.

// tag::methods[]
[#_ConceptPtrFuture__Entity___TypeDBEntityTypecreate___Transaction__transaction_]
==== create

[source,cpp]
----
ConceptPtrFuture< Entity > TypeDB::EntityType::create(Transaction& transaction)
----



Creates and returns a new instance of this ``EntityType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Entity >`

[caption=""]
.Code examples
[source,cpp]
----
entityType.create(transaction).get();
----

[#_ConceptIterable__Entity___TypeDBEntityTypegetInstances___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getInstances

[source,cpp]
----
ConceptIterable< Entity > TypeDB::EntityType::getInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``Entity`` objects that are instances of this exact ``EntityType`` OR this ``EntityType`` and any of its subtypes.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::EXPLICIT`` for direct instances only, ``Transitivity::TRANSITIVE`` to include subtypes a| 
|===

[caption=""]
.Returns
`ConceptIterable< Entity >`

[caption=""]
.Code examples
[source,cpp]
----
entityType.getInstances(transaction, transitivity);
----

[#_ConceptIterable__EntityType___TypeDBEntityTypegetSubtypes___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< EntityType > TypeDB::EntityType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< EntityType >`

[caption=""]
.Code examples
[source,cpp]
----
entityType.getSubtypes(transaction, transitivity);
----

[#_VoidFuture_TypeDBEntityTypesetSupertype___Transaction__transaction__EntityType__ptr__superEntityType_]
==== setSupertype

[source,cpp]
----
VoidFuture TypeDB::EntityType::setSupertype(Transaction& transaction, EntityType* superEntityType)
----



Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `superEntityType` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| `EntityType*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
entityType.setSupertype(transaction, entityType).get();
----

// end::methods[]

