[#_EntityType]
=== EntityType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::ThingType`
* `TypeDB::Type`
* `TypeDB::Concept`



Entity types represent the classification of independent objects in the data model of the business domain.

// tag::methods[]
[#_a136a9302e7cde78f37cb042707833d5d]
==== create

[source,cpp]
----
ConceptPtrFuture<Entity> TypeDB::EntityType::create(Transaction& transaction)
----



Creates and returns a new instance of this ``EntityType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Entity >`

[#_ae95a2736368a02f27b0fcd8c85524455]
==== getInstances

[source,cpp]
----
ConceptIterable<Entity> TypeDB::EntityType::getInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``Entity`` objects that are instances of this exact ``EntityType`` OR this ``EntityType`` and any of its subtypes.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::EXPLICIT`` for direct instances only, ``Transitivity::TRANSITIVE`` to include subtypes a| 
|===

[caption=""]
.Returns
`ConceptIterable< Entity >`

[#_ae9884d2bc698d670d782e527e6eee18c]
==== getSubtypes

[source,cpp]
----
ConceptIterable<EntityType> TypeDB::EntityType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the ``EntityType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< EntityType >`

[#_aef74680b34cab1104fd748f3cc010c4d]
==== setSupertype

[source,cpp]
----
VoidFuture TypeDB::EntityType::setSupertype(Transaction& transaction, EntityType* superEntityType)
----



Sets the supplied ``EntityType`` as the supertype of the current ``EntityType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `superEntityType` a| The ``EntityType`` to set as the supertype of this ``EntityType`` a| 
|===

[caption=""]
.Returns
`VoidFuture`

// end::methods[]

