[#_RelationType]
=== RelationType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::ThingType`
* `TypeDB::Type`
* `TypeDB::Concept`



Relation types (or subtypes of the relation root type) represent relationships between types.

Relation types have roles. Other types can play roles in relations if it’s mentioned in their definition. A relation type must specify at least one role.

// tag::methods[]
[#_ConceptPtrFuture__Relation___TypeDBRelationTypecreate___Transaction__transaction_]
==== create

[source,cpp]
----
ConceptPtrFuture< Relation > TypeDB::RelationType::create(Transaction& transaction)
----



Creates and returns an instance of this ``RelationType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Relation >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.create(transaction).get();
----

[#_ConceptIterable__Relation___TypeDBRelationTypegetInstances___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getInstances

[source,cpp]
----
ConceptIterable< Relation > TypeDB::RelationType::getInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``Relation``s that are instances of this exact ``RelationType``, OR this ``RelationType`` and any of its subtypes.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect instances, ``Transitivity::EXPLICIT`` for direct relates only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Relation >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getInstances(transaction, transitivity)
----

[#_ConceptIterable__RoleType___TypeDBRelationTypegetRelates___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getRelates

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::RelationType::getRelates(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves roles that this ``RelationType`` relates to directly or via inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and inherited relates, ``Transitivity::EXPLICIT`` for direct relates only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getRelates(transaction, transitivity);
----

[#_ConceptPtrFuture__RoleType___TypeDBRelationTypegetRelates___Transaction__transaction__const_stdstring__roleLabel_]
==== getRelates

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::RelationType::getRelates(Transaction& transaction, const std::string& roleLabel)
----



Retrieves the role with the specified label that this ``RelationType`` relates to, directly or via inheritance. Returns the corresponding ``RoleType`` or ``nullptr``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleLabel` a| Label of the role we wish to retrieve a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getRelates(transaction, roleLabel).get();
----

[#_ConceptPtrFuture__RoleType___TypeDBRelationTypegetRelatesOverridden___Transaction__transaction__RoleType__ptr__roleType_]
==== getRelatesOverridden

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::RelationType::getRelatesOverridden(Transaction& transaction, RoleType* roleType)
----



Retrieves a ``RoleType`` that is overridden by the role with the ``role_label``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleLabel` a| Label of the role that overrides an inherited role a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getRelatesOverridden(transaction, roleLabel).get();
----

[#_ConceptPtrFuture__RoleType___TypeDBRelationTypegetRelatesOverridden___Transaction__transaction__const_stdstring__roleLabel_]
==== getRelatesOverridden

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::RelationType::getRelatesOverridden(Transaction& transaction, const std::string& roleLabel)
----



Retrieves a ``RoleType`` that is overridden by the role with the ``role_label``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleLabel` a| Label of the role that overrides an inherited role a| `const std::string&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getRelatesOverridden(transaction, roleLabel).get();
----

[#_ConceptIterable__RelationType___TypeDBRelationTypegetSubtypes___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< RelationType > TypeDB::RelationType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the ``RelationType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
relationType.getSubtypes(transaction, transitivity);
----

[#_VoidFuture_TypeDBRelationTypesetRelates___Transaction__transaction__const_stdstring__roleLabel_]
==== setRelates

[source,cpp]
----
VoidFuture TypeDB::RelationType::setRelates(Transaction& transaction, const std::string& roleLabel)
----



Variant of <<#_VoidFuture_TypeDBRelationTypesetRelates___Transaction__transaction__const_stdstring__roleLabel__const_stdstring__overriddenLabel_,setRelates(Transaction&amp; transaction, const std::string&amp; roleLabel, const std::string&amp; overriddenLabel)>> where the RoleType does not override an existing role.

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBRelationTypesetRelates___Transaction__transaction__const_stdstring__roleLabel__RoleType__ptr__overriddenType_]
==== setRelates

[source,cpp]
----
VoidFuture TypeDB::RelationType::setRelates(Transaction& transaction, const std::string& roleLabel, RoleType* overriddenType)
----



Variant of <<#_VoidFuture_TypeDBRelationTypesetRelates___Transaction__transaction__const_stdstring__roleLabel__const_stdstring__overriddenLabel_,setRelates(Transaction&amp; transaction, const std::string&amp; roleLabel, const std::string&amp; overriddenLabel)>> where the RoleType is specified directly rather than the label.

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBRelationTypesetRelates___Transaction__transaction__const_stdstring__roleLabel__const_stdstring__overriddenLabel_]
==== setRelates

[source,cpp]
----
VoidFuture TypeDB::RelationType::setRelates(Transaction& transaction, const std::string& roleLabel, const std::string& overriddenLabel)
----



Sets the new role that this ``RelationType`` relates to. If we are setting an overriding type this way, we have to also pass the overridden type as a second argument.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleLabel` a| The new role for the ``RelationType`` to relate to a| `const std::string&`
a| `overriddenLabel` a| The label being overridden, if applicable a| `const std::string&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
relationType.setRelates(transaction, roleLabel).get();
relationType.setRelates(transaction, roleLabel, overriddenLabel).get();
----

[#_VoidFuture_TypeDBRelationTypesetSupertype___Transaction__transaction__RelationType__ptr__superRelationType_]
==== setSupertype

[source,cpp]
----
VoidFuture TypeDB::RelationType::setSupertype(Transaction& transaction, RelationType* superRelationType)
----



Sets the supplied ``RelationType`` as the supertype of the current ``RelationType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `superRelationType` a| The ``RelationType`` to set as the supertype of this ``RelationType`` a| `RelationType*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
relationType.setSupertype(transaction, superRelationType).get();
----

[#_VoidFuture_TypeDBRelationTypeunsetRelates___Transaction__transaction__RoleType__ptr__roleType_]
==== unsetRelates

[source,cpp]
----
VoidFuture TypeDB::RelationType::unsetRelates(Transaction& transaction, RoleType* roleType)
----



Variant of <<#_VoidFuture_TypeDBRelationTypeunsetRelates___Transaction__transaction__const_stdstring__roleLabel_,unsetRelates(Transaction&amp; transaction, const std::string&amp; roleLabel)>> where the RoleType is specified directly rather than the label.

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBRelationTypeunsetRelates___Transaction__transaction__const_stdstring__roleLabel_]
==== unsetRelates

[source,cpp]
----
VoidFuture TypeDB::RelationType::unsetRelates(Transaction& transaction, const std::string& roleLabel)
----



Disallows this ``RelationType`` from relating to the given role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleLabel` a| The role to not relate to the relation type. a| `const std::string&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
relationType.unsetRelates(transaction, roleLabel).get();
----

// end::methods[]

