[#_RoleType]
=== RoleType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Type`
* `TypeDB::Concept`



Defines a role an instance can play in a Relation.

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type. Roles allow a schema to enforce logical constraints on types of role players.

// tag::methods[]
[#_virtual_VoidFuture_TypeDBRoleTypedeleteType_Transaction_transaction_]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::RoleType::deleteType(Transaction& transaction)
----





Deletes this type from the database.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.deleteType(transaction).get();
----

[#_virtual_stdstring_TypeDBRoleTypegetLabel_]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::RoleType::getLabel()
----





Retrieves the unique label of the type.


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual std::string`

[caption=""]
.Code examples
[source,cpp]
----
type.getLabel();
----

[#_stdstring_TypeDBRoleTypegetName_]
==== getName

[source,cpp]
----
std::string TypeDB::RoleType::getName()
----



Returns the name of this role type's label.


[caption=""]
.Returns
`std::string`

[caption=""]
.Code examples
[source,cpp]
----
label.getName();
----

[#_ConceptIterable_Thing_TypeDBRoleTypegetPlayerInstances_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getPlayerInstances

[source,cpp]
----
ConceptIterable< Thing > TypeDB::RoleType::getPlayerInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``Thing`` instances that play this role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect playing, ``Transitivity::EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getPlayerInstances(transaction, transitivity);
----

[#_ConceptIterable_ThingType_TypeDBRoleTypegetPlayerTypes_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getPlayerTypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::RoleType::getPlayerTypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``ThingType``s whose instances play this role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getPlayerTypes(transaction, transitivity)
----

[#_ConceptIterable_Relation_TypeDBRoleTypegetRelationInstances_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getRelationInstances

[source,cpp]
----
ConceptIterable< Relation > TypeDB::RoleType::getRelationInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``Relation`` instances that this role is related to.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect relation, ``Transitivity::EXPLICIT`` for direct relation only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Relation >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getRelationInstances(transaction, transitivity)
----

[#_ConceptPtrFuture_RelationType_TypeDBRoleTypegetRelationType_Transaction_transaction_]
==== getRelationType

[source,cpp]
----
ConceptPtrFuture< RelationType > TypeDB::RoleType::getRelationType(Transaction& transaction)
----



Retrieves the ``RelationType`` that this role is directly related to.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getRelationType(transaction).get();
----

[#_ConceptIterable_RelationType_TypeDBRoleTypegetRelationTypes_Transaction_transaction_]
==== getRelationTypes

[source,cpp]
----
ConceptIterable< RelationType > TypeDB::RoleType::getRelationTypes(Transaction& transaction)
----



Retrieves ``RelationType``s that this role is related to (directly or indirectly).


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< RelationType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getRelationTypes(transaction);
----

[#_stdstring_TypeDBRoleTypegetScope_]
==== getScope

[source,cpp]
----
std::string TypeDB::RoleType::getScope()
----



Returns the scope part of this role type's label.


[caption=""]
.Returns
`std::string`

[caption=""]
.Code examples
[source,cpp]
----
label.getScope();
----

[#_ConceptIterable_RoleType_TypeDBRoleTypegetSubtypes_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::RoleType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getSubtypes(transaction, transitivity);
----

[#_ConceptPtrFuture_RoleType_TypeDBRoleTypegetSupertype_Transaction_transaction_]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::RoleType::getSupertype(Transaction& transaction)
----



Retrieves the most immediate supertype of the ``RoleType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getSupertype(transaction).get();
----

[#_ConceptIterable_RoleType_TypeDBRoleTypegetSupertypes_Transaction_transaction_]
==== getSupertypes

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::RoleType::getSupertypes(Transaction& transaction)
----



Retrieves all supertypes of the ``RoleType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
roleType.getSupertypes(transaction);
----

[#_virtual_bool_TypeDBRoleTypeisAbstract_]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::RoleType::isAbstract()
----





Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual bool`

[caption=""]
.Code examples
[source,cpp]
----
type.isAbstract();
----

[#_virtual_BoolFuture_TypeDBRoleTypeisDeleted_Transaction_transaction_]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::RoleType::isDeleted(Transaction& transaction)
----





Check if the type has been deleted


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual BoolFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.isDeleted(transaction).get();
----

[#_bool_TypeDBRoleTypeisRoot_]
==== isRoot

[source,cpp]
----
bool TypeDB::RoleType::isRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
type.isRoot();
----

[#_virtual_VoidFuture_TypeDBRoleTypesetLabel_Transaction_transaction_const_stdstring_newLabel_]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::RoleType::setLabel(Transaction& transaction, const std::string& newLabel)
----





Renames the label of the type. The new label must remain unique.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.setLabel(transaction, newLabel).get();
----

// end::methods[]

