[#_RoleType]
=== RoleType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Type`
* `TypeDB::Concept`



Defines a role an instance can play in a Relation.

Roles are special internal types used by relations. We can not create an instance of a role in a database. But we can set an instance of another type (role player) to play a role in a particular instance of a relation type. Roles allow a schema to enforce logical constraints on types of role players.

// tag::methods[]
[#_a7d93305987f2b8879ece741d6dcdd63a]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::RoleType::deleteType(Transaction& transaction)
----





Deletes this type from the database.


Implements <<#_a02c119fea52d0812b451b2dc630788f2,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_a05c129cbbf22af3a1481dcd70a271403]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::RoleType::getLabel()
----





Retrieves the unique label of the type.


Implements <<#_a22b6129c06b689a1dcc29f80f5825a5f,TypeDB::Type>>.

[caption=""]
.Returns
`virtual std::string`

[#_a4564bb3b7382cc4610ede5097cb1fc01]
==== getName

[source,cpp]
----
std::string TypeDB::RoleType::getName()
----



Returns the name of this role type's label.


[caption=""]
.Returns
`std::string`

[#_ac8a135b55d2bf28517244075ba5d82f4]
==== getPlayerInstances

[source,cpp]
----
ConceptIterable<Thing> TypeDB::RoleType::getPlayerInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``Thing`` instances that play this role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect playing, ``Transitivity::EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Thing >`

[#_a07b07c522699d5ea13e27d806f981efa]
==== getPlayerTypes

[source,cpp]
----
ConceptIterable<ThingType> TypeDB::RoleType::getPlayerTypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``ThingType``s whose instances play this role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity.TRANSITIVE`` for direct and indirect playing, ``Transitivity.EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_a2c5261e19a25c32bfe4bf1d86fc8b7ef]
==== getRelationInstances

[source,cpp]
----
ConceptIterable<Relation> TypeDB::RoleType::getRelationInstances(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves the ``Relation`` instances that this role is related to.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect relation, ``Transitivity::EXPLICIT`` for direct relation only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Relation >`

[#_aee375cb48b5b0bf0f61495e21896843e]
==== getRelationType

[source,cpp]
----
ConceptPtrFuture<RelationType> TypeDB::RoleType::getRelationType(Transaction& transaction)
----



Retrieves the ``RelationType`` that this role is directly related to.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RelationType >`

[#_a8842f5087b96a1c1e161f04bdcd9e9b7]
==== getRelationTypes

[source,cpp]
----
ConceptIterable<RelationType> TypeDB::RoleType::getRelationTypes(Transaction& transaction)
----



Retrieves ``RelationType``s that this role is related to (directly or indirectly).


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< RelationType >`

[#_a9920c314941a1376d99d5c0a8d1b830c]
==== getScope

[source,cpp]
----
std::string TypeDB::RoleType::getScope()
----



Returns the scope part of this role type's label.


[caption=""]
.Returns
`std::string`

[#_aabcaeb827d5fa7c9cf6b1c203b7fd831]
==== getSubtypes

[source,cpp]
----
ConceptIterable<RoleType> TypeDB::RoleType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the ``RoleType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity::EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[#_a1484fcc5e0c0272d682e2e276ddb5e3c]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture<RoleType> TypeDB::RoleType::getSupertype(Transaction& transaction)
----



Retrieves the most immediate supertype of the ``RoleType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[#_af122798e58d262b219f63b8594b3e3b1]
==== getSupertypes

[source,cpp]
----
ConceptIterable<RoleType> TypeDB::RoleType::getSupertypes(Transaction& transaction)
----



Retrieves all supertypes of the ``RoleType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[#_a5a2d563f46a211a3695c408e98e4ada0]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::RoleType::isAbstract()
----





Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implements <<#_a551a46cdbc57083c935408b9c2dcea92,TypeDB::Type>>.

[caption=""]
.Returns
`virtual bool`

[#_a4d13099f460750c832b81fd642d33c23]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::RoleType::isDeleted(Transaction& transaction)
----





Check if the type has been deleted


Implements <<#_ab74287ca83400d5482e86ba75db86643,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual BoolFuture`

[#_a3004dce5c15018c8bbb12ddff2f95f82]
==== isRoot

[source,cpp]
----
bool TypeDB::RoleType::isRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[#_a7db4f837e7c8343502288a7455884491]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::RoleType::setLabel(Transaction& transaction, const std::string& newLabel)
----





Renames the label of the type. The new label must remain unique.


Implements <<#_ae1a337de1b42d3a0feabda9cf2121a2a,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

// end::methods[]

