[#_ThingType]
=== ThingType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Type`
* `TypeDB::Concept`



Common super-type of EntityType, RelationType, and AttributeType.

// tag::methods[]
[#_virtual_VoidFuture_TypeDBThingTypedeleteType___Transaction__transaction_]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::deleteType(Transaction& transaction)
----





Deletes this type from the database.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.deleteType(transaction).get();
----

[#_virtual_stdstring_TypeDBThingTypegetLabel___]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::ThingType::getLabel()
----





Retrieves the unique label of the type.


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual std::string`

[caption=""]
.Code examples
[source,cpp]
----
type.getLabel();
----

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType`` or ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__const_stdinitializer_list__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Variant of <<#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdinitializer_list__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



See <<#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>>

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable__AttributeType___TypeDBThingTypegetOwns___Transaction__transaction__ValueType_valueType__const_stdvector__Annotation____annotations__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| `ValueType`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and inherited ownership, ``Transitivity::EXPLICIT`` for direct ownership only a| 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| `const std::vector< Annotation >&`
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
thingType.getOwns(transaction);
thingType.getOwns(transaction, valueType, Transitivity::EXPLICIT, Collections.singleton(Annotation.key()));
----

[#_ConceptPtrFuture__AttributeType___TypeDBThingTypegetOwnsOverridden___Transaction__transaction__AttributeType__ptr__attributeType_]
==== getOwnsOverridden

[source,cpp]
----
ConceptPtrFuture< AttributeType > TypeDB::ThingType::getOwnsOverridden(Transaction& transaction, AttributeType* attributeType)
----



Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| `AttributeType*`
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[caption=""]
.Code examples
[source,cpp]
----
thingType.getOwnsOverridden(transaction, attributeType).get();
----

[#_ConceptIterable__RoleType___TypeDBThingTypegetPlays___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getPlays

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::ThingType::getPlays(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| transitivity: ``Transitivity::TRANSITIVE`` for direct and indirect playing, ``Transitivity::EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
thingType.getPlays(transaction).get();
thingType.getPlays(transaction, Transitivity::EXPLICIT).get();
----

[#_ConceptPtrFuture__RoleType___TypeDBThingTypegetPlaysOverridden___Transaction__transaction__RoleType__ptr__roleType_]
==== getPlaysOverridden

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::ThingType::getPlaysOverridden(Transaction& transaction, RoleType* roleType)
----



Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleType` a| The ``RoleType`` that overrides an inherited role a| `RoleType*`
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[caption=""]
.Code examples
[source,cpp]
----
thingType.getPlaysOverridden(transaction, roleType).get();
----

[#_ConceptIterable__ThingType___TypeDBThingTypegetSubtypes___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSubtypes(transaction);
type.getSubtypes(transaction, Transitivity.EXPLICIT);
----

[#_ConceptPtrFuture__ThingType___TypeDBThingTypegetSupertype___Transaction__transaction_]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< ThingType > TypeDB::ThingType::getSupertype(Transaction& transaction)
----





Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSupertype(transaction).get();
----

[#_ConceptIterable__ThingType___TypeDBThingTypegetSupertypes___Transaction__transaction_]
==== getSupertypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSupertypes(Transaction& transaction)
----





Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSupertypes(transaction);
----

[#_StringFuture_TypeDBThingTypegetSyntax___Transaction__transaction_]
==== getSyntax

[source,cpp]
----
StringFuture TypeDB::ThingType::getSyntax(Transaction& transaction)
----



Produces a pattern for creating this ``ThingType`` in a ``define`` query.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`StringFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.getSyntax(transaction).get();
----

[#_virtual_bool_TypeDBThingTypeisAbstract___]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::ThingType::isAbstract()
----





Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual bool`

[caption=""]
.Code examples
[source,cpp]
----
type.isAbstract();
----

[#_virtual_BoolFuture_TypeDBThingTypeisDeleted___Transaction__transaction_]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::ThingType::isDeleted(Transaction& transaction)
----





Check if the type has been deleted


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual BoolFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.isDeleted(transaction).get();
----

[#_bool_TypeDBThingTypeisRoot___]
==== isRoot

[source,cpp]
----
bool TypeDB::ThingType::isRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[caption=""]
.Code examples
[source,cpp]
----
type.isRoot();
----

[#_VoidFuture_TypeDBThingTypesetAbstract___Transaction__transaction_]
==== setAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::setAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be abstract, meaning it cannot have instances.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.setAbstract(transaction).get();
----

[#_virtual_VoidFuture_TypeDBThingTypesetLabel___Transaction__transaction__const_stdstring__newLabel_]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::setLabel(Transaction& transaction, const std::string& newLabel)
----





Renames the label of the type. The new label must remain unique.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.setLabel(transaction, newLabel).get();
----

[#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__const_stdinitializer_list__Annotation____annotations___]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::initializer_list< Annotation >& annotations = {})
----





Variant of <<#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__AttributeType__ptr__overriddenType__const_stdvector__Annotation____annotations_,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__const_stdvector__Annotation____annotations_]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::vector< Annotation >& annotations)
----



Variant of <<#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__AttributeType__ptr__overriddenType__const_stdvector__Annotation____annotations_,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__AttributeType__ptr__overriddenType__const_stdinitializer_list__Annotation____annotations___]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::initializer_list< Annotation >& annotations = {})
----



See <<#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__AttributeType__ptr__overriddenType__const_stdvector__Annotation____annotations_,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>>

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns___Transaction__transaction__AttributeType__ptr__attributeType__AttributeType__ptr__overriddenType__const_stdvector__Annotation____annotations_]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::vector< Annotation >& annotations)
----



Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| `AttributeType*`
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| `AttributeType*`
a| `annotations` a| Adds annotations to the ownership. a| `const std::vector< Annotation >&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.setOwns(transaction, attributeType).get();
thingType.setOwns(transaction, attributeType, overriddenType, Collections.singleton(Annotation.key())).get();
----

[#_VoidFuture_TypeDBThingTypesetPlays___Transaction__transaction__RoleType__ptr__roleType_]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType)
----



Variant of <<#_VoidFuture_TypeDBThingTypesetPlays___Transaction__transaction__RoleType__ptr__roleType__RoleType__ptr__overriddenRoleType_,setPlays(Transaction&amp;, RoleType*, RoleType*)>> with no overridden role type.

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetPlays___Transaction__transaction__RoleType__ptr__roleType__RoleType__ptr__overriddenRoleType_]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType, RoleType* overriddenRoleType)
----



Allows the instances of this ``ThingType`` to play the given role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleType` a| The role to be played by the instances of this type a| `RoleType*`
a| `overriddenType` a| The role type that this role overrides, if applicable a| 
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.setPlays(transaction, roleType).get();
thingType.setPlays(transaction, roleType, overriddenType).get();
----

[#_VoidFuture_TypeDBThingTypeunsetAbstract___Transaction__transaction_]
==== unsetAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be non-abstract, meaning it can have instances.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.unsetAbstract(transaction).get();
----

[#_VoidFuture_TypeDBThingTypeunsetOwns___Transaction__transaction__AttributeType__ptr__attributeType_]
==== unsetOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetOwns(Transaction& transaction, AttributeType* attributeType)
----



Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| `AttributeType*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.unsetOwns(transaction, attributeType).get();
----

[#_VoidFuture_TypeDBThingTypeunsetPlays___Transaction__transaction__RoleType__ptr__roleType_]
==== unsetPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetPlays(Transaction& transaction, RoleType* roleType)
----



Disallows the instances of this ``ThingType`` from playing the given role.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `roleType` a| The role to not be played by the instances of this type. a| `RoleType*`
|===

[caption=""]
.Returns
`VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
thingType.unsetPlays(transaction, roleType).get();
----

// end::methods[]

