[#_ThingType]
=== ThingType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Type`
* `TypeDB::Concept`



Common super-type of EntityType, RelationType, and AttributeType.

// tag::methods[]
[#_a5399fecb5b90485c03922b496f53a835]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::deleteType(Transaction& transaction)
----





Deletes this type from the database.


Implements <<#_a02c119fea52d0812b451b2dc630788f2,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_ae1c92d79118b5f0f245d4e478770f418]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::ThingType::getLabel()
----





Retrieves the unique label of the type.


Implements <<#_a22b6129c06b689a1dcc29f80f5825a5f,TypeDB::Type>>.

[caption=""]
.Returns
`virtual std::string`

[#_a64a46c015db037d78f80310c9ac7486b]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_a0c35ffd9ea1f02a7475c4eb26c2044ea,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType`` or ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_a32a1aba320d8cf2533aa33c2c916a80b]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Variant of <<#_a0c35ffd9ea1f02a7475c4eb26c2044ea,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_a1cb6ec35ce14afddf7acc6beb6a42c76]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_a0c35ffd9ea1f02a7475c4eb26c2044ea,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ad890f46d18c4eb006a50cd32b48163ba]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_a0c35ffd9ea1f02a7475c4eb26c2044ea,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_a3cc94cab07adc9f845398c1682bd039e]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



See <<#_a0c35ffd9ea1f02a7475c4eb26c2044ea,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>>

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_a0c35ffd9ea1f02a7475c4eb26c2044ea]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and inherited ownership, ``Transitivity::EXPLICIT`` for direct ownership only a| 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_aa2d0ef36d711654d89c228c0837c3cfd]
==== getOwnsOverridden

[source,cpp]
----
ConceptPtrFuture< AttributeType > TypeDB::ThingType::getOwnsOverridden(Transaction& transaction, AttributeType* attributeType)
----



Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_a70cb66e125ebbfbd98a4ee9e18655373]
==== getPlays

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::ThingType::getPlays(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| transitivity: ``Transitivity::TRANSITIVE`` for direct and indirect playing, ``Transitivity::EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[#_ad1ca616f6c0a4023f78ba93dfa2a7fa7]
==== getPlaysOverridden

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::ThingType::getPlaysOverridden(Transaction& transaction, RoleType* roleType)
----



Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The ``RoleType`` that overrides an inherited role a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[#_a7813ced713bbf0a55585bb6de0bc0b1e]
==== getSubtypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_a803f2fab52fb3f0794ca53e94c209a54]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< ThingType > TypeDB::ThingType::getSupertype(Transaction& transaction)
----





Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< ThingType >`

[#_a393a12bf0e139cf19470b4c62410252e]
==== getSupertypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSupertypes(Transaction& transaction)
----





Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_a0a65bac5c9c26a899e57af06a4e00b47]
==== getSyntax

[source,cpp]
----
StringFuture TypeDB::ThingType::getSyntax(Transaction& transaction)
----



Produces a pattern for creating this ``ThingType`` in a ``define`` query.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`StringFuture`

[#_adb713b84d84a6c09519a5289ee0c28bb]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::ThingType::isAbstract()
----





Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implements <<#_a551a46cdbc57083c935408b9c2dcea92,TypeDB::Type>>.

[caption=""]
.Returns
`virtual bool`

[#_a041a80538323ae62571c3c213b3fc1d7]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::ThingType::isDeleted(Transaction& transaction)
----





Check if the type has been deleted


Implements <<#_ab74287ca83400d5482e86ba75db86643,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual BoolFuture`

[#_aece1e0da2d8e613421cbaf1e66ec29a9]
==== isRoot

[source,cpp]
----
bool TypeDB::ThingType::isRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[#_a0dad7a52b26f0cf263ae29cf2d9b99c4]
==== setAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::setAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be abstract, meaning it cannot have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a13732daa9c717d18ed3ee850f9b3a69e]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::setLabel(Transaction& transaction, const std::string& newLabel)
----





Renames the label of the type. The new label must remain unique.


Implements <<#_ae1a337de1b42d3a0feabda9cf2121a2a,TypeDB::Type>>.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_ac9704a5142c6044a3138c70d5ec77cf5]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::initializer_list< Annotation >& annotations = {})
----





Variant of <<#_aa2d5e81c11a863f70b7d26bf04dd14fb,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_ad20b07e29444329325154fbaf2601a75]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::vector< Annotation >& annotations)
----



Variant of <<#_aa2d5e81c11a863f70b7d26bf04dd14fb,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_a9de29faaf30b17698d82e5aa51b50add]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::initializer_list< Annotation >& annotations = {})
----



See <<#_aa2d5e81c11a863f70b7d26bf04dd14fb,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>>

[caption=""]
.Returns
`VoidFuture`

[#_aa2d5e81c11a863f70b7d26bf04dd14fb]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::vector< Annotation >& annotations)
----



Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| 
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| 
a| `annotations` a| Adds annotations to the ownership. a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_ada0da232a45800850a6b6b81ccc308c6]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType)
----



Variant of <<#_a7584d9b9b8d53cc53830a5989b0abb2d,setPlays(Transaction&amp;, RoleType*, RoleType*)>> with no overridden role type.

[caption=""]
.Returns
`VoidFuture`

[#_a7584d9b9b8d53cc53830a5989b0abb2d]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType, RoleType* overriddenRoleType)
----



Allows the instances of this ``ThingType`` to play the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to be played by the instances of this type a| 
a| `overriddenType` a| The role type that this role overrides, if applicable a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a12e4d1481ed56f6be2e771080d98340d]
==== unsetAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be non-abstract, meaning it can have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a72f955cdc8812aae30d200e05d006abb]
==== unsetOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetOwns(Transaction& transaction, AttributeType* attributeType)
----



Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_a076ac582adce416549faaa321fdcf346]
==== unsetPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetPlays(Transaction& transaction, RoleType* roleType)
----



Disallows the instances of this ``ThingType`` from playing the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to not be played by the instances of this type. a| 
|===

[caption=""]
.Returns
`VoidFuture`

// end::methods[]

