[#_Type]
=== Type

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Concept`



Common super-type of RoleType &amp; ThingType.

// tag::methods[]
[#_virtual_VoidFuture_TypeDBTypedeleteType___Transaction__transaction_]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::Type::deleteType(Transaction& transaction)
----



Deletes this type from the database.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.deleteType(transaction).get();
----

[#_virtual_stdstring_TypeDBTypegetLabel___]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::Type::getLabel()
----



Retrieves the unique label of the type.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Returns
`virtual std::string`

[caption=""]
.Code examples
[source,cpp]
----
type.getLabel();
----

[#_ConceptIterable__Type___TypeDBTypegetSubtypes___Transaction__transaction__Transitivity_transitivity__TransitivityTRANSITIVE_]
==== getSubtypes

[source,cpp]
----
ConceptIterable< Type > TypeDB::Type::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Type >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSubtypes(transaction);
type.getSubtypes(transaction, Transitivity.EXPLICIT);
----

[#_ConceptPtrFuture__Type___TypeDBTypegetSupertype___Transaction__transaction_]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< Type > TypeDB::Type::getSupertype(Transaction& transaction)
----



Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptPtrFuture< Type >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSupertype(transaction).get();
----

[#_ConceptIterable__Type___TypeDBTypegetSupertypes___Transaction__transaction_]
==== getSupertypes

[source,cpp]
----
ConceptIterable< Type > TypeDB::Type::getSupertypes(Transaction& transaction)
----



Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`ConceptIterable< Type >`

[caption=""]
.Code examples
[source,cpp]
----
type.getSupertypes(transaction);
----

[#_virtual_bool_TypeDBTypeisAbstract___]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::Type::isAbstract()
----



Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Returns
`virtual bool`

[caption=""]
.Code examples
[source,cpp]
----
type.isAbstract();
----

[#_virtual_BoolFuture_TypeDBTypeisDeleted___Transaction__transaction_]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::Type::isDeleted(Transaction& transaction)
----



Check if the type has been deleted


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
|===

[caption=""]
.Returns
`virtual BoolFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.isDeleted(transaction).get();
----

[#_virtual_VoidFuture_TypeDBTypesetLabel___Transaction__transaction__const_stdstring__newLabel_]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::Type::setLabel(Transaction& transaction, const std::string& newLabel)
----



Renames the label of the type. The new label must remain unique.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols=",,"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| `Transaction&`
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[caption=""]
.Code examples
[source,cpp]
----
type.setLabel(transaction, newLabel).get();
----

// end::methods[]

